<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-12">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Partisan Politics, the Welfare State, and Three Worlds of Human Capital Formation – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1596dba0f6ebd5d6ff9514dff97656d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Partisan Politics, the Welfare State, and Three Worlds of Human Capital Formation – Annotated Bibliography">
<meta property="og:description" content="Iversen, T., &amp; Stephens, J. D. (2008). Partisan politics, the welfare state, and three worlds of human capital formation. Comparative Political Studies, 41(4/5), 600–637. https://doi.org/10.1177/0010414007313117">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#introdução-pp.-600602" id="toc-introdução-pp.-600602" class="nav-link" data-scroll-target="#introdução-pp.-600602">Introdução (pp.&nbsp;600–602)</a>
  <ul class="collapse">
  <li><a href="#o-gap-teórico-e-a-proposta-de-síntese-14" id="toc-o-gap-teórico-e-a-proposta-de-síntese-14" class="nav-link" data-scroll-target="#o-gap-teórico-e-a-proposta-de-síntese-14"><span class="header-section-number">0.1</span> O gap teórico e a proposta de síntese [§1–§4]</a></li>
  </ul></li>
  <li><a href="#explicando-as-diferenças-cross-nacionais-prt-e-wpr-pp.-602607" id="toc-explicando-as-diferenças-cross-nacionais-prt-e-wpr-pp.-602607" class="nav-link" data-scroll-target="#explicando-as-diferenças-cross-nacionais-prt-e-wpr-pp.-602607">Explicando as Diferenças Cross-Nacionais: PRT e WPR (pp.&nbsp;602–607)</a>
  <ul class="collapse">
  <li><a href="#fatos-estilizados-sobre-redistribuição-e-barganha-salarial-59" id="toc-fatos-estilizados-sobre-redistribuição-e-barganha-salarial-59" class="nav-link" data-scroll-target="#fatos-estilizados-sobre-redistribuição-e-barganha-salarial-59"><span class="header-section-number">0.2</span> Fatos estilizados sobre redistribuição e barganha salarial [§5–§9]</a></li>
  <li><a href="#o-caso-da-nova-zelândia-e-as-exceções-democrata-cristãs-1013" id="toc-o-caso-da-nova-zelândia-e-as-exceções-democrata-cristãs-1013" class="nav-link" data-scroll-target="#o-caso-da-nova-zelândia-e-as-exceções-democrata-cristãs-1013"><span class="header-section-number">0.3</span> O caso da Nova Zelândia e as exceções democrata-cristãs [§10–§13]</a></li>
  <li><a href="#eficiência-interesse-patronal-e-limites-do-conflito-de-classe-1416" id="toc-eficiência-interesse-patronal-e-limites-do-conflito-de-classe-1416" class="nav-link" data-scroll-target="#eficiência-interesse-patronal-e-limites-do-conflito-de-classe-1416"><span class="header-section-number">0.4</span> Eficiência, interesse patronal e limites do conflito de classe [§14–§16]</a></li>
  </ul></li>
  <li><a href="#os-três-mundos-de-formação-de-capital-humano-pp.-607614" id="toc-os-três-mundos-de-formação-de-capital-humano-pp.-607614" class="nav-link" data-scroll-target="#os-três-mundos-de-formação-de-capital-humano-pp.-607614">Os Três Mundos de Formação de Capital Humano (pp.&nbsp;607–614)</a>
  <ul class="collapse">
  <li><a href="#lme-com-instituições-eleitorais-majoritárias-1719" id="toc-lme-com-instituições-eleitorais-majoritárias-1719" class="nav-link" data-scroll-target="#lme-com-instituições-eleitorais-majoritárias-1719"><span class="header-section-number">0.5</span> LME com instituições eleitorais majoritárias [§17–§19]</a></li>
  <li><a href="#cme-com-rp-e-ausência-de-partido-dc-forte-o-modelo-nórdico-2025" id="toc-cme-com-rp-e-ausência-de-partido-dc-forte-o-modelo-nórdico-2025" class="nav-link" data-scroll-target="#cme-com-rp-e-ausência-de-partido-dc-forte-o-modelo-nórdico-2025"><span class="header-section-number">0.6</span> CME com RP e ausência de partido DC forte: o modelo nórdico [§20–§25]</a></li>
  <li><a href="#cme-com-rp-e-partido-dc-forte-o-modelo-continental-2629" id="toc-cme-com-rp-e-partido-dc-forte-o-modelo-continental-2629" class="nav-link" data-scroll-target="#cme-com-rp-e-partido-dc-forte-o-modelo-continental-2629"><span class="header-section-number">0.7</span> CME com RP e partido DC forte: o modelo continental [§26–§29]</a></li>
  <li><a href="#educação-superior-tensões-distributivas-e-coalizões-3032" id="toc-educação-superior-tensões-distributivas-e-coalizões-3032" class="nav-link" data-scroll-target="#educação-superior-tensões-distributivas-e-coalizões-3032"><span class="header-section-number">0.8</span> Educação Superior: tensões distributivas e coalizões [§30–§32]</a></li>
  </ul></li>
  <li><a href="#evidência-empírica-pp.-614624" id="toc-evidência-empírica-pp.-614624" class="nav-link" data-scroll-target="#evidência-empírica-pp.-614624">Evidência Empírica (pp.&nbsp;614–624)</a>
  <ul class="collapse">
  <li><a href="#variáveis-e-fontes-de-dados-3335" id="toc-variáveis-e-fontes-de-dados-3335" class="nav-link" data-scroll-target="#variáveis-e-fontes-de-dados-3335"><span class="header-section-number">0.9</span> Variáveis e fontes de dados [§33–§35]</a></li>
  <li><a href="#regimes-de-bem-estar-e-capital-humano-evidência-descritiva-tabela-3-3640" id="toc-regimes-de-bem-estar-e-capital-humano-evidência-descritiva-tabela-3-3640" class="nav-link" data-scroll-target="#regimes-de-bem-estar-e-capital-humano-evidência-descritiva-tabela-3-3640"><span class="header-section-number">0.10</span> Regimes de bem-estar e capital humano: evidência descritiva (Tabela 3) [§36–§40]</a></li>
  <li><a href="#determinantes-do-gasto-em-capital-humano-análise-de-painel-tabela-4-4144" id="toc-determinantes-do-gasto-em-capital-humano-análise-de-painel-tabela-4-4144" class="nav-link" data-scroll-target="#determinantes-do-gasto-em-capital-humano-análise-de-painel-tabela-4-4144"><span class="header-section-number">0.11</span> Determinantes do gasto em capital humano: análise de painel (Tabela 4) [§41–§44]</a></li>
  <li><a href="#complementaridades-entre-regimes-correlações-tabela-5-e-figuras-4549" id="toc-complementaridades-entre-regimes-correlações-tabela-5-e-figuras-4549" class="nav-link" data-scroll-target="#complementaridades-entre-regimes-correlações-tabela-5-e-figuras-4549"><span class="header-section-number">0.12</span> Complementaridades entre regimes: correlações (Tabela 5) e figuras [§45–§49]</a></li>
  </ul></li>
  <li><a href="#mudanças-ao-longo-do-tempo-pp.-624630" id="toc-mudanças-ao-longo-do-tempo-pp.-624630" class="nav-link" data-scroll-target="#mudanças-ao-longo-do-tempo-pp.-624630">Mudanças ao Longo do Tempo (pp.&nbsp;624–630)</a>
  <ul class="collapse">
  <li><a href="#origens-históricas-dos-regimes-5057" id="toc-origens-históricas-dos-regimes-5057" class="nav-link" data-scroll-target="#origens-históricas-dos-regimes-5057"><span class="header-section-number">0.13</span> Origens históricas dos regimes [§50–§57]</a></li>
  <li><a href="#trajetórias-pós-guerra-e-consolidação-dos-regimes-5862" id="toc-trajetórias-pós-guerra-e-consolidação-dos-regimes-5862" class="nav-link" data-scroll-target="#trajetórias-pós-guerra-e-consolidação-dos-regimes-5862"><span class="header-section-number">0.14</span> Trajetórias pós-guerra e consolidação dos regimes [§58–§62]</a></li>
  <li><a href="#mudanças-recentes-desindustrialização-e-respostas-governamentais-6368" id="toc-mudanças-recentes-desindustrialização-e-respostas-governamentais-6368" class="nav-link" data-scroll-target="#mudanças-recentes-desindustrialização-e-respostas-governamentais-6368"><span class="header-section-number">0.15</span> Mudanças recentes: desindustrialização e respostas governamentais [§63–§68]</a></li>
  </ul></li>
  <li><a href="#conclusão-pp.-630632" id="toc-conclusão-pp.-630632" class="nav-link" data-scroll-target="#conclusão-pp.-630632">Conclusão (pp.&nbsp;630–632)</a>
  <ul class="collapse">
  <li><a href="#síntese-dos-três-mundos-e-agenda-de-pesquisa-6973" id="toc-síntese-dos-três-mundos-e-agenda-de-pesquisa-6973" class="nav-link" data-scroll-target="#síntese-dos-três-mundos-e-agenda-de-pesquisa-6973"><span class="header-section-number">0.16</span> Síntese dos três mundos e agenda de pesquisa [§69–§73]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético">Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Partisan Politics, the Welfare State, and Three Worlds of Human Capital Formation</h1>
<p class="subtitle lead">Iversen, T., &amp; Stephens, J. D. (2008). Partisan politics, the welfare state, and three worlds of human capital formation. <em>Comparative Political Studies</em>, <em>41</em>(4/5), 600–637. https://doi.org/10.1177/0010414007313117</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Political Economy</div>
    <div class="quarto-category">Welfare State/Social Policy</div>
    <div class="quarto-category">Education Policy</div>
    <div class="quarto-category">Comparative Politics</div>
    <div class="quarto-category">2008</div>
    <div class="quarto-category">2000s</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Informações Técnicas e BibTeX
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Linha de modelo e timestamp:</strong></p>
<pre><code>Última atualização: 2026-05-12
Modelo: Claude Sonnet 4.6 Thinking (Perplexity)
Prompt Version: v17.3 · 2026-05-10
Gerado em: 2026-05-12T22:24:00-03:00
Ocasião da Leitura:</code></pre>
<p><strong>2. Entrada BibTeX → Iversen-Stephens2008</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">Iversen</span>-<span class="ot">Stephens2008</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>  = {Iversen, Torben and Stephens, John D.},</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>   = {Partisan Politics, the Welfare State, and Three Worlds of Human Capital Formation},</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>    = {2008},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">journal</span> = {Comparative Political Studies},</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">volume</span>  = {41},</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">number</span>  = {4/5},</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span>   = {600--637},</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">doi</span>     = {10.1177/0010414007313117},</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.3</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A premissa central é que as teorias de recursos de poder (PRT) e de regimes de produção de bem-estar (WPR) capturam dimensões complementares do mesmo fenômeno. O risco de circularidade está na possibilidade de que os “mundos” sejam construídos com os mesmos dados que pretendem explicar. Uma interpretação alternativa seria que a convergência entre os mundos reflita trajetórias tecnológicas, não política partidária.</td>
<td style="text-align: left;">Por que países avançados diferem sistematicamente em seus padrões de formação de capital humano, e como essas diferenças se relacionam com regimes partidários, sistemas eleitorais e modos de organização capitalista? Pergunta formulada pelos autores de modo explícito, com natureza predominantemente explicativa/causal.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">Há risco de que as questões secundárias sejam meramente ilustrativas das hipóteses já estabelecidas, sem testá-las de modo independente.</td>
<td style="text-align: left;">(1) Como a lógica de coalizão política explica as diferenças nos investimentos em educação pública básica e superior? (2) Por que regimes social-democratas diferem dos democrata-cristãos no gasto em serviços públicos, especialmente creches? (3) Qual é a relação entre compressão salarial, educação vocacional e desigualdade de renda?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno: a literatura de VoC (Hall &amp; Soskice, 2001) tratava educação como exógena ao regime, enquanto a PRT ignorava a composição das habilidades. A lacuna é real e a articulação proposta é original. O risco de generalização excessiva existe, pois o modelo descreve países da OCDE no pós-guerra sem escopo declarado para economias emergentes.</td>
<td style="text-align: left;">Puzzle explicativo: a literatura existente tratava PRT e VoC como teorias rivais, e nenhuma das duas integrava plenamente a política de formação de capital humano (educação geral + formação vocacional + bem-estar social) em um quadro unificado. A contribuição consiste em demonstrar que as duas abordagens são complementares e que, juntas, explicam três mundos distintos de formação de capital humano.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese é sustentada por correlações altas (Tabela 5) e por análise de painel (Tabela 4), mas a causalidade direcional entre equalidade e capital humano não é identificada com rigidez. Os autores reconhecem o caráter de complementaridade mútua, o que ao mesmo tempo é uma força teórica e uma limitação para inferência causal estrita.</td>
<td style="text-align: left;">Países com sistemas proporcionais de representação e ausência de partidos democrata-cristãos fortes tendem a produzir governos de centro-esquerda que investem pesadamente em educação pública em todos os níveis, formação vocacional, políticas ativas de mercado de trabalho e creches — gerando alta formação de capital humano tanto geral quanto específico, especialmente na base da distribuição de habilidades. Regimes democrata-cristãos privilegiam proteção do emprego e seguro social, mas negligenciam o pré-escolar e a educação básica de baixa renda. Regimes liberais (LMEs com sistemas majoritários) concentram investimento privado no ensino superior e produzem estrutura bifurcada de habilidades.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O fichamento cobre a obra inteira (único artigo, 38 pp.). O design é misto: análise de painel com estimadores Prais-Winsten (18 democracias avançadas, pós-guerra) para gasto em educação; análise cross-seccional para habilidades (14 países, OECD/HRDC 2000); e argumento histórico-institucional qualitativo para as origens. A limitação de identificação mais relevante é a endogeneidade entre redistribuição e formação de capital humano: os autores argumentam por complementaridade mútua, mas o design de painel não isola choques exógenos.</td>
<td style="text-align: left;">Estudo cross-national comparativo com três componentes empíricos: (a) descrição comparativa por regimes (Tabela 3); (b) análise de regressão de painel (Tabela 4: Prais-Winsten, PCSE, correção AR-1); (c) análise de correlação cruzada (Tabela 5) e discussão histórico-institucional qualitativa.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP baseia-se fortemente em dados agregados nacionais (OCDE, Huber et al.&nbsp;2004), o que introduz viés de agregação: diferenças internas a cada país (regionais, étnicas, de gênero) são invisíveis. O teste de literacy (OECD/HRDC) está disponível para apenas 14 dos 18 países, o que limita a comparação e pode introduzir seleção amostral (países que participaram do estudo de literacy tendem a ser os mais engajados com reformas educacionais). A operacionalização do “governo de esquerda” como fração de assentos no parlamento é razoável mas suaviza variações ideológicas internas aos partidos.</td>
<td style="text-align: left;">Fenômeno real (formação de capital humano e estrutura de habilidades) → observação via gastos públicos como proxy de política e escores de literacy como medida de output → coleta de dados administrativos e surveys (OECD Education at a Glance, Scruggs 2004, Huber et al.&nbsp;2004, OECD/HRDC 2000) → operacionalização por percentagem do PIB e escores padronizados → análise de regressão de painel e correlações. Unidade de análise: país-ano (painel) e país (corte transversal).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">A correlação entre literacy na 5ª percentil e ALMP (r = .84) é notável. Os resultados da Tabela 4 mostram que governo de esquerda é significativo para todos os quatro gastos de capital humano, enquanto governo democrata-cristão é significativo apenas (e negativamente) para creches — distinção teoricamente bem fundamentada. A contribuição metodológica de reintegrar educação à análise comparativa do Estado de bem-estar é relevante para a agenda de pesquisa.</td>
<td style="text-align: left;">(1) Governo de esquerda é preditor positivo e significativo de gasto em educação pública, ensino superior, creches e políticas ativas de mercado de trabalho. (2) Governo democrata-cristão é significativamente negativo apenas para gasto em creches. (3) Habilidades na base da distribuição são muito mais sensíveis ao regime político do que habilidades no topo. (4) Regimes social-democratas e democrata-cristãos têm taxas de reposição de desemprego idênticas (~74%), mas diferem radicalmente em redistribuição (37% vs.&nbsp;24% de redução da desigualdade por transferências). (5) As trajetórias históricas das VoC precedem os regimes de bem-estar: os sistemas de treinamento vocacional e as organizações patronais já estavam consolidados antes da Primeira Guerra Mundial.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">(a) Endogeneidade não resolvida: a correlação entre gasto público e habilidades pode ser bidirecional; os autores reconhecem isso, mas o design não a isola. (b) O estudo de caso da Nova Zelândia (natural experiment da mudança para RP em 1996) é persuasivo para o argumento eleitoral, mas é um N=1 e pode refletir fatores idiossincráticos. (c) A análise histórica (origens) é essencialmente narrativa e não está conectada formalmente ao modelo quantitativo. (d) A exclusão da Suíça do padrão esperado é reconhecida, mas a explicação ad hoc (pontos de veto institucionais) não é integrada ao modelo preditivo. (e) Questão de scope: o argumento é explicitamente restrito a democracias avançadas da OCDE; a ausência de scope conditions formalizadas pode induzir generalização indevida.</td>
<td style="text-align: left;">O argumento responde adequadamente à pergunta dentro de seus próprios termos, mas a força das afirmações causais excede o que o design identifica. O ponto mais robusto é a associação entre regime político e gasto. O ponto mais vulnerável é a causalidade no sentido igualdade→capital humano→igualdade, que é afirmada como complementaridade mas não identificada causalmente.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> A análise cross-seccional de literacy e educação vocacional limita a complexidade estatística possível; os dados de literacy cobrem apenas 14 dos 18 países; a relação entre igualdade e capital humano é bidirecional. <br> <strong>Não reconhecidas ou subestimadas:</strong> (1) Endogeneidade do sistema eleitoral em relação à estrutura produtiva (o próprio Cusack et al.&nbsp;2007 sugere isso, mas as implicações para a identificação do efeito do sistema eleitoral sobre gasto não são discutidas); (2) Viés de seleção na amostra de democracias avançadas: o argumento sobre o papel da PRT pressupõe condições institucionais que podem não existir fora desse conjunto; (3) Efeitos de composição demográfica (envelhecimento, imigração) são controlados de modo parcial; (4) A medida de “governo de esquerda” não capta variações qualitativas nas plataformas dos partidos ao longo do tempo.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A síntese é teoricamente coerente: PRT opera no nível da distribuição de poder entre classes e da composição das coalizões governamentais; WPR opera no nível das complementaridades institucionais entre regime produtivo e proteção social. A ontologia implícita é institucionalista-histórica com mecanismos de interesse racional. A moldura é adequada à pergunta e à estratégia de evidência mista (quantitativa + histórica).</td>
<td style="text-align: left;">Síntese entre Power Resources Theory (Korpi, Esping-Andersen, Stephens) e Welfare Production Regime Theory / Varieties of Capitalism (Hall &amp; Soskice, Estevez-Abe et al., Iversen). Orientação ontológica institucionalista; epistemologia nomotética com modulação histórico-comparativa.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo com Rueda (2005) sobre insider-outsider é presente mas rapidamente descartado; uma confrontação mais explícita fortaleceria o argumento. Ansell (2005) sobre ensino superior está em working paper, o que reduz a verificabilidade.</td>
<td style="text-align: left;">Esping-Andersen (1990); Hall &amp; Soskice (2001); Estevez-Abe, Iversen &amp; Soskice (2001); Huber &amp; Stephens (2001); Iversen &amp; Soskice (2006, 2007); Korpi (1983, 2006); Thelen (2004); Cusack, Iversen &amp; Soskice (2007); Bradley et al.&nbsp;(2003); Scruggs (2004); OECD/HRDC (2000).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">O artigo é altamente relevante para pesquisas sobre política educacional comparada e Estado de bem-estar. Para pesquisa sobre Brasil: o país não se enquadra nas três categorias (LME, SD-CME, CD-CME), o que convida à reflexão sobre como regimes híbridos ou do Sul Global se posicionam nessa tipologia. A ausência de análise de qualidade — e não apenas quantidade — do gasto educacional é uma lacuna potencialmente importante. O fichamento cobre o artigo completo.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 19%">
<col style="width: 28%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Seção</th>
<th style="text-align: left;">Título / Tema</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Abstract</td>
<td style="text-align: left;">Síntese da contribuição</td>
<td style="text-align: left;">Apresentação do puzzle e da tese</td>
<td style="text-align: left;">Enuncia os três mundos e a síntese PRT+WPR como contribuição central</td>
</tr>
<tr class="even">
<td style="text-align: left;">Introdução (pp.&nbsp;600–602)</td>
<td style="text-align: left;">Limites das teorias existentes e objetivo do artigo</td>
<td style="text-align: left;">Revisão de literatura e delimitação do gap</td>
<td style="text-align: left;">Situa PRT e WPR como abordagens rivais incompletas; justifica a síntese</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seção teórica — PRT e WPR: uma síntese (pp.&nbsp;602–607)</td>
<td style="text-align: left;">Fatos estilizados e mecanismos de coalizão</td>
<td style="text-align: left;">Fundamento teórico</td>
<td style="text-align: left;">Articula como sistema eleitoral, partidos e organização dos empregadores determinam redistribuição e tipo de habilidades</td>
</tr>
<tr class="even">
<td style="text-align: left;">Três mundos de formação de capital humano (pp.&nbsp;607–614)</td>
<td style="text-align: left;">LME/majoritário; CME-SD; CME-DC</td>
<td style="text-align: left;">Extensão do argumento</td>
<td style="text-align: left;">Descreve os três regimes e seus mecanismos distintos de formação de capital humano; inclui Tabela 1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educação Superior (pp.&nbsp;612–614)</td>
<td style="text-align: left;">Política educacional no ensino superior</td>
<td style="text-align: left;">Qualificação</td>
<td style="text-align: left;">Analisa tensão entre efeito distributivo regressivo do ensino superior e interesse da centro-esquerda em democratizá-lo</td>
</tr>
<tr class="even">
<td style="text-align: left;">Evidência Empírica — Comparação por regime (pp.&nbsp;614–618)</td>
<td style="text-align: left;">Tabelas 2 e 3</td>
<td style="text-align: left;">Análise empírica descritiva</td>
<td style="text-align: left;">Documenta os padrões previstos nos três mundos usando dados dos anos 1990</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Determinantes do Gasto em Educação (pp.&nbsp;618–620)</td>
<td style="text-align: left;">Regressões Prais-Winsten (Tabela 4)</td>
<td style="text-align: left;">Análise empírica causal</td>
<td style="text-align: left;">Testa a hipótese de que governo de esquerda aumenta gasto em capital humano; confirma para todos os quatro itens</td>
</tr>
<tr class="even">
<td style="text-align: left;">Complementaridades entre Estado de Bem-Estar e Regimes de Produção (pp.&nbsp;620–624)</td>
<td style="text-align: left;">Correlações (Tabela 5) e Figuras 1–2</td>
<td style="text-align: left;">Análise empírica — complementaridades</td>
<td style="text-align: left;">Demonstra alta correlação entre políticas, habilidades e igualdade; situa os regimes nas dimensões analíticas</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mudanças ao longo do tempo — Origens (pp.&nbsp;624–628)</td>
<td style="text-align: left;">Pré-industrialização, Ständestaaten, formação dos sistemas de treinamento</td>
<td style="text-align: left;">Fundamento histórico-institucional</td>
<td style="text-align: left;">Explica por que os VoC e sistemas de RP se desenvolveram antes dos regimes de bem-estar; ancora a tese na path dependence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mudanças ao longo do tempo — Mudanças Recentes (pp.&nbsp;628–630)</td>
<td style="text-align: left;">Tecnologia, pós-fordismo, desmobilização sindical</td>
<td style="text-align: left;">Extensão do argumento / comparação temporal</td>
<td style="text-align: left;">Mostra que as respostas governamentais à desindustrialização replicam a lógica dos regimes, reforçando a tese</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Conclusão (pp.&nbsp;630–632)</td>
<td style="text-align: left;">Síntese e implicações</td>
<td style="text-align: left;">Síntese e agenda</td>
<td style="text-align: left;">Retoma os três mundos, integra PRT e WPR, e sinaliza implicações para estratificação laboral e agenda de pesquisa</td>
</tr>
</tbody>
</table>
</section>
<section id="introdução-pp.-600602" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introdução-pp.-600602">Introdução (pp.&nbsp;600–602)</h2>
<section id="o-gap-teórico-e-a-proposta-de-síntese-14" class="level3" data-number="0.1">
<h3 data-number="0.1" class="anchored" data-anchor-id="o-gap-teórico-e-a-proposta-de-síntese-14"><span class="header-section-number">0.1</span> O gap teórico e a proposta de síntese [§1–§4]</h3>
<p>O artigo tem como ponto de partida a constatação de que, no momento de publicação de <em>The Three Worlds of Welfare Capitalism</em> de Esping-Andersen (1990), a <strong>Power Resources Theory</strong> (PRT) havia se tornado a abordagem dominante no estudo do desenvolvimento do Estado de bem-estar. Nessa perspectiva, o tamanho e a estrutura do Estado de bem-estar são função da força histórica da esquerda política, mediada por alianças com as classes médias. Iversen e Stephens reconhecem a contribuição central dessa tradição, mas apontam que ela passou a sofrer dois tipos de desafio: de um lado, críticas que apontam para a negligência do papel dos empregadores na configuração do Estado de bem-estar (Mares, 2003; Swenson, 1991, 2002); de outro, o desafio proveniente da perspectiva das <strong>Varieties of Capitalism</strong> (VoC), que propõe que sistemas distintos de proteção social funcionam como complementos eficientes a modos específicos de produção capitalista — o que Estevez-Abe, Iversen e Soskice (2001) denominam <strong>welfare production regimes</strong> (WPR).</p>
<p>Os autores argumentam que PRT e WPR não são rivais, mas teorias complementares. O foco do artigo é demonstrar que, tomadas em conjunto, as duas abordagens permitem explicar diferenças sistemáticas na formação de <strong>capital humano</strong> — conceito que os autores operacionalizam tanto pelo lado das políticas (gastos em educação, creches, políticas ativas de mercado de trabalho) quanto pelo lado dos resultados (habilidades gerais medidas pelo estudo de literacy da OCDE, participação em educação vocacional). A ênfase em capital humano é justificada por sua centralidade não apenas para a distribuição de renda, mas também para o desempenho econômico e a vantagem comparativa das nações.</p>
<p>O argumento sobre educação é apresentado como especialmente necessário dado o tratamento marginal que ela recebeu na literatura comparada de bem-estar. Seguindo Wilensky (1975), boa parte da literatura simplesmente excluiu a educação da análise do Estado de bem-estar com a alegação de que “education is different”. Iversen e Stephens recusam essa separação: os incentivos para adquirir tipos específicos de habilidades são estreitamente relacionados tanto à proteção social quanto ao desempenho econômico, e o gasto educacional tem implicações distributivas tão profundas quanto os demais pilares do Estado de bem-estar.</p>
</section>
</section>
<section id="explicando-as-diferenças-cross-nacionais-prt-e-wpr-pp.-602607" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="explicando-as-diferenças-cross-nacionais-prt-e-wpr-pp.-602607">Explicando as Diferenças Cross-Nacionais: PRT e WPR (pp.&nbsp;602–607)</h2>
<section id="fatos-estilizados-sobre-redistribuição-e-barganha-salarial-59" class="level3" data-number="0.2">
<h3 data-number="0.2" class="anchored" data-anchor-id="fatos-estilizados-sobre-redistribuição-e-barganha-salarial-59"><span class="header-section-number">0.2</span> Fatos estilizados sobre redistribuição e barganha salarial [§5–§9]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Ponto de partida teórico:</strong> Os autores tratam como “fatos estilizados” suficientemente estabelecidos na literatura duas afirmações fundamentais: (a) controle do governo pela esquerda aumenta redistribuição; (b) sindicatos e barganha salarial coordenada reduzem a desigualdade de salários. O restante da seção dedica-se a explicar os mecanismos que ligam essas regularidades aos sistemas eleitorais e às coalizões de classe.</p>
</div>
</div>
<p>A primeira regularidade — esquerda no governo implica maior redistribuição — é documentada por um conjunto robusto de evidências estatísticas e históricas (Allan &amp; Scruggs, 2004; Bradley et al., 2003; Hicks &amp; Swank, 1984; Huber &amp; Stephens, 2001; Korpi, 1983). A segunda — sindicatos e barganha coordenada comprimem salários — é explicada por dois mecanismos: primeiro, trabalhadores qualificados têm incentivo para proteger seus investimentos em habilidades demandando taxas padronizadas entre firmas; segundo, se trabalhadores semiqualificados são complementos dos qualificados na produção, seu consentimento é necessário para acordos coletivos, o que lhes confere poder de barganha dentro do sistema centralizado.</p>
<p>Para explicar por que governos de centro-esquerda dominam politicamente em alguns países mas não em outros, os autores mobilizam a análise de coalizão. Em sistemas partidários com <strong>partidos democrata-cristãos</strong> (DC) fracos, sistemas de <strong>representação proporcional</strong> (RP) tendem a produzir governos de centro-esquerda, enquanto sistemas majoritários tendem a produzir governos de centro-direita. O mecanismo subjacente é o incentivo dos partidos de centro, em sistemas de RP, para se aliarem aos partidos de esquerda e tributar as classes médio-alta e alta (Iversen &amp; Soskice, 2006). A coalizão vencedora mínima que exclui a direita do governo é, na formulação dos autores, condição-chave para redistribuição.</p>
</section>
<section id="o-caso-da-nova-zelândia-e-as-exceções-democrata-cristãs-1013" class="level3" data-number="0.3">
<h3 data-number="0.3" class="anchored" data-anchor-id="o-caso-da-nova-zelândia-e-as-exceções-democrata-cristãs-1013"><span class="header-section-number">0.3</span> O caso da Nova Zelândia e as exceções democrata-cristãs [§10–§13]</h3>
<p>A distinção entre RP e sistemas majoritários é ilustrada empiricamente pelo caso da Nova Zelândia, que os autores tratam como um <strong>experimento natural</strong>: nas 17 eleições de pluralidade em distrito único entre o pós-guerra e 1993, o resultado foi 12 governos do Partido Nacional e apenas 5 do Labour; nas 4 eleições após a mudança para RP em 1996, o resultado foi 3 governos liderados pelo Labour e 1 pelo National. A inversão na frequência dos governos de esquerda é consistente com a previsão do modelo.</p>
<p>Os países com RP que possuem partidos democrata-cristãos <strong>fortes</strong> constituem um caso distinto. Os partidos DC são coalizões de classe cruzada (Kalyvas, 1996; Van Kersbergen, 1995), cujas preferências refletem um compromisso entre grupos de renda distintos. Isso os posiciona como parceiros preferenciais de partidos centristas de classe média, reduzindo ou eliminando a vantagem que a esquerda teria de outra forma nos sistemas de RP. Os autores distinguem dentro desse grupo: nos países do Benelux, os partidos DC são centristas (com liberais à direita e social-democratas à esquerda), gerando maior incidência de governos de centro-esquerda e maiores níveis de redistribuição; na Alemanha e na Itália, os DC são de centro-direita, excluindo sistematicamente a esquerda do governo.</p>
<p>A lógica da democracia-cristã é adicionalmente ilustrada pelo caso da Suíça — o Estado de bem-estar menos redistributivo entre todos os Estados de bem-estar avançados, incluindo os liberais —, explicado pelos múltiplos pontos de veto institucionais (executivo coletivo, bicameralismo forte, federalismo, referendos) que conferem poder de bloqueio às rendas altas.</p>
<blockquote class="blockquote">
<p>O argumento central da seção pode ser sintetizado assim: não é o consenso democrático que explica redistribuição, mas coalizões vencedoras mínimas que excluem a direita; e o sistema eleitoral é o mecanismo que molda a probabilidade de tais coalizões.</p>
</blockquote>
</section>
<section id="eficiência-interesse-patronal-e-limites-do-conflito-de-classe-1416" class="level3" data-number="0.4">
<h3 data-number="0.4" class="anchored" data-anchor-id="eficiência-interesse-patronal-e-limites-do-conflito-de-classe-1416"><span class="header-section-number">0.4</span> Eficiência, interesse patronal e limites do conflito de classe [§14–§16]</h3>
<p>Um dos pontos mais consequentes da seção é a rejeição da narrativa do Estado de bem-estar como resultado de uma luta de classes entre trabalhadores e empregadores. Os autores concordam parcialmente com Swenson (1991) ao reconhecer que a resistência dos empregadores à legislação social foi antes sobre tributação do que sobre política social em si — o que é ilustrado pelo caso sueco, em que o tema central das eleições de 1948 para os conservadores era corte de impostos, não desmonte do bem-estar. No entanto, a aceitação dos empregadores de certas políticas sociais não é interpretada como resultado de preferências reveladas pelas empresas, mas sim como compatibilidade das políticas, moldadas via comitês parlamentares e agências burocráticas com representação corporatista, com mercados de trabalho eficientes.</p>
<p>A ausência de <em>trade-off</em> entre Estado de bem-estar redistributivo e crescimento econômico, competitividade ou investimento (Swank, 1992; Lindert, 2004; Garrett, 1998) é tratada como fato estilizado adicional. A explicação pela ótica da WPR é que alta proteção social incentiva investimento em habilidades específicas, o que viabiliza especialização em nichos de mercado internacional com competição quase-monopolista e margens elevadas. A proteção ao emprego e os altos salários de reposição, ao reduzir a incerteza para os trabalhadores, os tornam mais dispostos a investir em habilidades dificilmente transferíveis — mecanismo central do argumento de Estevez-Abe et al.&nbsp;(2001).</p>
<blockquote class="blockquote">
<p><strong>Nota 1:</strong> Os autores reconhecem que a separação estrita entre políticas de seguro e políticas redistributivas é empiricamente impossível: mesmo as contribuições previdenciárias relacionadas ao salário redistribuem renda. Esse ponto é relevante para a operacionalização empírica das variáveis dependentes nas seções seguintes.</p>
</blockquote>
</section>
</section>
<section id="os-três-mundos-de-formação-de-capital-humano-pp.-607614" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="os-três-mundos-de-formação-de-capital-humano-pp.-607614">Os Três Mundos de Formação de Capital Humano (pp.&nbsp;607–614)</h2>
<section id="lme-com-instituições-eleitorais-majoritárias-1719" class="level3" data-number="0.5">
<h3 data-number="0.5" class="anchored" data-anchor-id="lme-com-instituições-eleitorais-majoritárias-1719"><span class="header-section-number">0.5</span> LME com instituições eleitorais majoritárias [§17–§19]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Regime Liberal:</strong> Baixo gasto em educação básica e pré-escolar pública; gasto público concentrado no ensino superior e no preparo para ele; alta participação privada no ensino superior; baixo seguro social; mercados de trabalho fluidos; estrutura bifurcada de habilidades; desigualdade salarial elevada.</p>
</div>
</div>
<p>Nos países com <strong>Liberal Market Economies</strong> (LME) e sistemas eleitorais majoritários (como Estados Unidos, Reino Unido, Austrália e Nova Zelândia), governos de centro ou centro-direita gastam relativamente poucos recursos em educação primária e pré-escolar de alta qualidade. O grosso do gasto público destina-se a programas que beneficiam a classe média, especialmente o ensino superior e a preparação para ele; já a classe médio-alta investe pesadamente em educação privada. Como o seguro social e a redistribuição são baixos, as classes médias e médio-altas essencialmente se auto-asseguram via investimento em habilidades gerais que facilitam a mobilidade no mercado de trabalho em resposta a choques econômicos.</p>
<p>O sistema de treinamento vocacional é fraco nesses países e a transição da escola para o trabalho é fracamente institucionalizada. Isso implica que o terço inferior da distribuição de habilidades tem poucas oportunidades de adquirir competências valiosas e poucos incentivos para se esforçar na escola, gerando uma estrutura de habilidades altamente bifurcada. No topo, há forte incentivo para se destacar academicamente e ingressar nas melhores universidades. O resultado é uma desigualdade salarial pronunciada, que poderia em princípio ser corrigida por maior gasto público na educação dos grupos mais fracos, mas não há incentivo eleitoral para a classe média votar nesse sentido — ela prefere políticas que mantenham seus salários altos e garantam mobilidade horizontal diante da volatilidade do mercado de trabalho.</p>
</section>
<section id="cme-com-rp-e-ausência-de-partido-dc-forte-o-modelo-nórdico-2025" class="level3" data-number="0.6">
<h3 data-number="0.6" class="anchored" data-anchor-id="cme-com-rp-e-ausência-de-partido-dc-forte-o-modelo-nórdico-2025"><span class="header-section-number">0.6</span> CME com RP e ausência de partido DC forte: o modelo nórdico [§20–§25]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Regime Social-Democrata:</strong> Alto gasto em educação pública em todos os níveis; creches públicas de alta qualidade; políticas ativas de mercado de trabalho; proteção ao emprego moderada mas altas taxas de reposição do seguro-desemprego; estrutura de habilidades comprimida; baixa desigualdade salarial e de renda.</p>
</div>
</div>
<p>Nos países com <strong>Coordinated Market Economies</strong> (CME), RP e ausência de partido DC forte (tipicamente os países nórdicos), governos de coalizão de centro-esquerda produzem alta redistribuição, forte apoio ao investimento em educação primária e secundária, políticas ativas de mercado de trabalho e creches/pré-escolas públicas de alta qualidade. O que ficou conhecido como modelo de <strong>flexicurity</strong> reflete uma coalizão de centro-esquerda entre trabalhadores de baixa e alta qualificação (excluindo profissionais liberais) que incentiva a aquisição de habilidades profundas específicas à indústria, ao mesmo tempo que permite flexibilidade no mercado de trabalho via mobilidade entre firmas e extenso gasto em requalificação e emprego público.</p>
<p>A combinação de gasto pesado em educação pública com sistemas de formação vocacional bem desenvolvidos criou uma estrutura de habilidades muito mais comprimida em comparação com os países de habilidades gerais. Isso se deve não apenas ao fato de que os trabalhadores do segmento inferior possuem habilidades específicas ausentes nos países liberais, mas também porque eles possuem melhores habilidades gerais (especialmente literacia, matemática e tecnologia da informação) — o que é condição prévia para a aquisição de habilidades técnicas mais avançadas.</p>
<p>A expansão do emprego público nos países nórdicos, decorrente de governos frequentemente de centro-esquerda, é interpretada pelos autores como tendo amortecido o desenvolvimento tanto de divisões acentuadas insider-outsider (como nos países europeus continentais) quanto da desigualdade salarial pronunciada (como nos países liberais). O setor público ofereceu seguro implícito às famílias de dupla renda e sustentou a demanda agregada. A <strong>provisão pública de creches</strong> é destacada como política com efeitos múltiplos: pelo lado da demanda, cria empregos; pelo lado da oferta, permite que os pais entrem ou permaneçam no mercado de trabalho; além disso, oferece educação na primeira infância, particularmente importante para filhos de pais menos escolarizados, e facilita taxas de fecundidade mais altas.</p>
<p>A trajetória pós-guerra dos países nórdicos é diferenciada dos países europeus continentais por um processo interativo complexo entre governança social-democrata, força sindical, participação das mulheres no mercado de trabalho e expansão do emprego em serviços sociais públicos. Uma dinâmica de feedback positivo conectou governo de esquerda, força sindical, participação feminina no mercado de trabalho, mobilização política das mulheres e emprego público: à medida que os empregos no setor público eram predominantemente ocupados por mulheres, estimulava-se maior participação feminina e, em consequência, maior mobilização política. Na Suécia, a transição para a tributação separada dos cônjuges em 1971 e a promoção do modelo de família com dupla renda foram marcos políticos explícitos dessa trajetória.</p>
</section>
<section id="cme-com-rp-e-partido-dc-forte-o-modelo-continental-2629" class="level3" data-number="0.7">
<h3 data-number="0.7" class="anchored" data-anchor-id="cme-com-rp-e-partido-dc-forte-o-modelo-continental-2629"><span class="header-section-number">0.7</span> CME com RP e partido DC forte: o modelo continental [§26–§29]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Regime Democrata-Cristão:</strong> Alta proteção ao emprego; seguro social por ocupação/setor; sistema vocacional desenvolvido; baixo gasto em creches e educação básica para crianças de baixa renda; baixa participação feminina no mercado de trabalho; divisão insider-outsider acentuada.</p>
</div>
</div>
<p>Nos países com CME, RP e partido DC forte (tipicamente Alemanha, Áustria, Benelux, Itália), há incentivos para excluir a direita liberal-conservadora das coalizões de governo, mas os partidos DC, como coalizões de classe cruzada, são parceiros preferenciais de partidos centristas. Como é difícil construir consenso sobre redistribuição significativa dentro do partido DC, o foco tem sido em seguro social baseado em ocupação ou renda, garantindo a cada grupo principal alto nível de proteção social. Trabalhadores não qualificados e semiqualificados são majoritariamente organizados por partidos de esquerda fora da coalizão DC-centro, e redistribuição massiva nos moldes escandinavos tem sido rara como consequência.</p>
<p>Em termos da composição das habilidades, a alta proteção ao emprego facilitou o investimento em habilidades específicas à firma e ao setor. Os países europeus continentais (com parcial exceção da França) possuem sistemas de formação vocacional e de barganha coletiva bem desenvolvidos. No entanto, o sistema DC privilegiou os trabalhadores qualificados e ignorou amplamente os interesses dos não qualificados e semiqualificados — padrão reforçado por sindicatos controlados pelos primeiros e por baixas taxas de sindicalização globais. O apoio a gastos públicos pesados em pré-escola e educação primária para crianças de famílias de baixa renda foi correspondentemente menor do que nos países escandinavos.</p>
<p>A trajetória pós-guerra dos Estados de bem-estar DC diferiu significativamente dos países escandinavos em dois aspectos interligados. Primeiro, a questão da migração de mão de obra foi tratada de forma distinta: diferentemente dos países nórdicos, que limitaram o recrutamento de trabalho estrangeiro não nórdico sob influência dos movimentos sindicais, os países continentais importaram mão de obra estrangeira em grande escala — possivelmente por combinar a ênfase DC no modelo de família com provedor masculino e a menor influência sindical sobre políticas de recrutamento. Segundo, os sindicatos continentais europeus, ao contrário dos escandinavos, continuaram a se opor ao trabalho a tempo parcial, enquanto os partidos DC aumentaram as transferências para famílias e criaram incentivos fiscais para que as mulheres ficassem em casa. O resultado foi que, entre os três tipos de Estado de bem-estar, a participação feminina no mercado de trabalho é mais baixa nos países DC continentais.</p>
<blockquote class="blockquote">
<p><strong>Nota 2:</strong> Os autores rejeitam explicitamente a interpretação de Rueda (2005) de que as divisões insider-outsider são um padrão social-democrata, atribuindo-as distintamente ao regime DC. Esse ponto é relevante para a literatura sobre segmentação de mercados de trabalho europeus.</p>
</blockquote>
</section>
<section id="educação-superior-tensões-distributivas-e-coalizões-3032" class="level3" data-number="0.8">
<h3 data-number="0.8" class="anchored" data-anchor-id="educação-superior-tensões-distributivas-e-coalizões-3032"><span class="header-section-number">0.8</span> Educação Superior: tensões distributivas e coalizões [§30–§32]</h3>
<p>A discussão sobre ensino superior introduz uma qualificação importante à hipótese de que gasto de esquerda é universalmente redistributivo. Dados do Reino Unido de 1993 mostram que a razão entre gasto per capita no quintil inferior e no quintil superior é de 0,7 para o ensino superior — a única categoria de gasto em serviços sociais em que os ricos beneficiam-se mais em termos per capita do que os pobres. Contudo, quando se considera que o quintil superior paga uma parcela desproporcional dos impostos que financiam esses benefícios (41,2% da renda domiciliar total vs.&nbsp;7,5% para o quintil inferior), o gasto em ensino superior financiado por imposto proporcional ou moderadamente regressivo (como o IVA) ainda representa uma transferência líquida para o quintil inferior.</p>
<p>A tensão dentro da social-democracia entre o legado histórico de democratização do acesso ao ensino superior e os efeitos distributivos em favor de grupos privilegiados é amenizada à medida que as mulheres se tornam eleitorado social-democrata crescente. Como as mulheres hoje superam os homens em número nas universidades públicas em muitos países, o investimento em ensino superior transfere recursos de forma desproporcionada para as mulheres — reduzindo a tensão distributiva interna à coalizão de esquerda. Os países europeus continentais, por outro lado, parecem estar atrasados em políticas de acesso para a classe trabalhadora ao ensino superior, novamente porque a esquerda não é necessária para formar coalizões governantes nessa configuração institucional.</p>
</section>
</section>
<section id="evidência-empírica-pp.-614624" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="evidência-empírica-pp.-614624">Evidência Empírica (pp.&nbsp;614–624)</h2>
<section id="variáveis-e-fontes-de-dados-3335" class="level3" data-number="0.9">
<h3 data-number="0.9" class="anchored" data-anchor-id="variáveis-e-fontes-de-dados-3335"><span class="header-section-number">0.9</span> Variáveis e fontes de dados [§33–§35]</h3>
<p>A análise empírica procede em três etapas. A Tabela 2 apresenta as variáveis utilizadas na análise poolada e na análise de corte transversal. As variáveis dependentes na análise de painel são: (1) gasto em políticas ativas de mercado de trabalho como percentagem do PIB por desempregado; (2) gasto público em educação como percentagem do PIB; (3) gasto público em ensino superior como percentagem do PIB; (4) gasto em creches como percentagem do PIB. As variáveis políticas de interesse são: gabinete de esquerda (fração de assentos no Parlamento sob governo de esquerda, 1946 em diante); gabinete democrata-cristão (codificado analogamente); estrutura constitucional (pontos de veto); mobilização das mulheres (estimativa por assentos parlamentares femininos).</p>
<p>As variáveis de controle seguem a literatura de determinantes do gasto social (Huber &amp; Stephens, 2000, 2001, 2006) e incluem: percentagem da população acima de 65 anos, participação eleitoral, greves, legado autoritário, PIB per capita, inflação (IPC), desemprego, gasto militar, investimento direto estrangeiro e abertura comercial. Para a análise de corte transversal, são utilizadas: (a) participação em educação vocacional como percentagem de uma coorte etária (proxy de habilidades específicas); (b) escores de literacy do estudo OCDE/HRDC (2000), incluindo percentis 5, 25, 75 e 95; (c) percentual de baixa literacia (Nível 1) e de “literatos na era da informação” (Nível 3 ou superior); (d) taxa de reposição líquida do desemprego de 12 meses; (e) dispersão salarial (razão 90/10); (f) Gini pós-transferência para a população de 25–59 anos; (g) legislação de proteção ao emprego (OCDE 2004).</p>
</section>
<section id="regimes-de-bem-estar-e-capital-humano-evidência-descritiva-tabela-3-3640" class="level3" data-number="0.10">
<h3 data-number="0.10" class="anchored" data-anchor-id="regimes-de-bem-estar-e-capital-humano-evidência-descritiva-tabela-3-3640"><span class="header-section-number">0.10</span> Regimes de bem-estar e capital humano: evidência descritiva (Tabela 3) [§36–§40]</h3>
<p>A Tabela 3 apresenta médias por regime para o conjunto de indicadores na década de 1990. Os resultados são amplamente consistentes com as previsões teóricas. Os regimes social-democratas (Suécia, Noruega, Dinamarca, Finlândia) lideram em todos os indicadores de gasto educacional: média de 7,4% do PIB em gasto público total em educação vs.&nbsp;5,2% nos CD e 5,5% nos liberais; média de 2,0% do PIB em ensino superior vs.&nbsp;1,1% e 1,4%, respectivamente; média de 1,6% em creches vs.&nbsp;0,4% e 0,2%. O gasto em políticas ativas de mercado de trabalho também é substancialmente maior: 0,25% vs.&nbsp;0,14% e 0,07%.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Indicador</th>
<th style="text-align: right;">SD-CME</th>
<th style="text-align: right;">CD-CME</th>
<th style="text-align: right;">Liberal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gasto em educação (% PIB)</td>
<td style="text-align: right;">7,4</td>
<td style="text-align: right;">5,2</td>
<td style="text-align: right;">5,5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ensino superior (% PIB)</td>
<td style="text-align: right;">2,0</td>
<td style="text-align: right;">1,1</td>
<td style="text-align: right;">1,4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Creches (% PIB)</td>
<td style="text-align: right;">1,6</td>
<td style="text-align: right;">0,4</td>
<td style="text-align: right;">0,2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Política ativa de mercado de trabalho</td>
<td style="text-align: right;">0,25</td>
<td style="text-align: right;">0,14</td>
<td style="text-align: right;">0,07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taxa de reposição desemprego (1 ano)</td>
<td style="text-align: right;">0,68</td>
<td style="text-align: right;">0,58</td>
<td style="text-align: right;">0,31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educação vocacional (% coorte)</td>
<td style="text-align: right;">34,0</td>
<td style="text-align: right;">34,0</td>
<td style="text-align: right;">6,8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Literacy — 5º percentil</td>
<td style="text-align: right;">207,9</td>
<td style="text-align: right;">181,0</td>
<td style="text-align: right;">146,3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Literacy — 95º percentil</td>
<td style="text-align: right;">366,0</td>
<td style="text-align: right;">355,3</td>
<td style="text-align: right;">364,0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baixa literacia (Nível 1)</td>
<td style="text-align: right;">8,5%</td>
<td style="text-align: right;">13,5%</td>
<td style="text-align: right;">20,5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Era da informação (Nível 3+)</td>
<td style="text-align: right;">67,6%</td>
<td style="text-align: right;">58,1%</td>
<td style="text-align: right;">52,0%</td>
</tr>
</tbody>
</table>
<p>As diferenças LME-CME na participação em educação vocacional são drásticas: em média 34% para ambos os tipos de CME vs.&nbsp;6,8% para os regimes liberais, confirmando que a formação vocacional é característica transversal a todos os CMEs independentemente do regime político. Os dois tipos de CME diferem, entretanto, nos mecanismos de suporte às habilidades específicas: os CD utilizam alta <strong>Employment Protection Legislation</strong> (EPL) como mecanismo de proteção do investimento em habilidades específicas, enquanto os social-democratas utilizam altas taxas de reposição de desemprego e políticas ativas de mercado de trabalho.</p>
<p>As diferenças nos escores de literacy são mais pronunciadas na base da distribuição do que no topo. O desvio-padrão no 5º percentil é de 30,9 vs.&nbsp;apenas 9,5 no 95º percentil. Isso indica que os regimes político-institucionais afetam predominantemente a qualidade das habilidades dos menos favorecidos, não das elites — achado que tem implicações diretas para a relação entre regime de bem-estar e desigualdade de renda. No topo da distribuição (95º percentil), os dois países norte-americanos (Canadá e EUA) superam todos os demais exceto a Suécia, provavelmente em função dos altos níveis de gasto total (público + privado) em ensino superior (2,6% do PIB no Canadá e 2,7% nos EUA).</p>
</section>
<section id="determinantes-do-gasto-em-capital-humano-análise-de-painel-tabela-4-4144" class="level3" data-number="0.11">
<h3 data-number="0.11" class="anchored" data-anchor-id="determinantes-do-gasto-em-capital-humano-análise-de-painel-tabela-4-4144"><span class="header-section-number">0.11</span> Determinantes do gasto em capital humano: análise de painel (Tabela 4) [§41–§44]</h3>
<p>A Tabela 4 apresenta as estimativas Prais-Winsten com erros-padrão corrigidos por painel e correção para autocorrelação de primeira ordem (sem variável dependente defasada, para evitar o viés discutido por Achen, 2000). O conjunto de controles é idêntico ao de Huber e Stephens (2006), permitindo comparação direta com os determinantes de outros indicadores do esforço do Estado de bem-estar.</p>
<p>Os resultados confirmam as hipóteses principais: <strong>gabinete de esquerda</strong> é positivo e significativo para todos os quatro itens de gasto (p &lt; 0,01 para educação e creches; p &lt; 0,001 para educação e ensino superior). <strong>Gabinete DC</strong> é significativamente negativo apenas para gasto em creches (p &lt; 0,01) e não significativo para os demais — ou seja, os regimes DC são estatisticamente indistinguíveis dos liberais no que diz respeito ao gasto em educação básica, superior e políticas ativas de mercado de trabalho. A <strong>estrutura constitucional</strong> (pontos de veto) não é significativa em nenhuma das equações.</p>
<p>A <strong>mobilização das mulheres</strong> é positiva e significativa para gasto em educação e ensino superior, mas não para creches nem políticas ativas de mercado de trabalho — resultado inesperado para as autoras, dado que creches são a política por excelência de conciliação trabalho-família. Os autores interpretam esse resultado como indicativo de que o efeito da mobilização feminina sobre creches pode ser indireto, mediado pelo governo de esquerda: quando a variável de esquerda é retirada da equação, o coeficiente de mobilização das mulheres aumenta e torna-se altamente significativo.</p>
</section>
<section id="complementaridades-entre-regimes-correlações-tabela-5-e-figuras-4549" class="level3" data-number="0.12">
<h3 data-number="0.12" class="anchored" data-anchor-id="complementaridades-entre-regimes-correlações-tabela-5-e-figuras-4549"><span class="header-section-number">0.12</span> Complementaridades entre regimes: correlações (Tabela 5) e figuras [§45–§49]</h3>
<p>A Tabela 5 apresenta a matriz de correlações entre 12 variáveis de política e de resultado. As correlações confirmam a existência de complementaridades institucionais coerentes com a teoria WPR. Educação vocacional (proxy de habilidades específicas) está altamente correlacionada com EPL (r = .86) e com taxa de reposição de desemprego (r = .76), conforme previsto por Estevez-Abe et al.&nbsp;(2001). A Figura 1 ilustra a relação positiva entre educação vocacional e EPL, mostrando que os países nórdicos não estão no extremo superior da dimensão de proteção ao emprego, confirmando a existência de dois caminhos distintos para habilidades específicas: o nórdico (proteção moderada + alta reposição + ALMP intensiva) e o continental (alta proteção + reposição moderada + ALMP moderada). Múltiplas regressões (não apresentadas) mostram que EPL e taxa de reposição juntos explicam 78% da variância em educação vocacional; EPL e ALMP, 77%.</p>
<p>A Figura 2 apresenta a relação entre literacy no 5º percentil e gasto em ALMP, com os países nórdicos no extremo superior do gráfico — padrão que se repete para o gasto em creches. As habilidades gerais na base da distribuição têm correlação fortíssima com ALMP (r = .84), creches (r = .79), educação vocacional (r = .73) e — diferentemente das habilidades no topo — com a desigualdade de renda (Gini pós-transferências, r = -.85). Esse conjunto de correlações é interpretado como evidência de complementaridades mutuamente reforçantes: igualdade reduzida de renda → melhor aquisição de habilidades na base → maior compressão salarial → menor desigualdade.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Implicação interpretativa central:</strong> As diferenças cross-nacionais em habilidades são muito maiores na base do que no topo da distribuição. Os regimes político-institucionais afetam principalmente quem fica para trás, não quem chega ao topo — o que significa que escolhas de política educacional e social são, antes de tudo, escolhas sobre desigualdade.</p>
</div>
</div>
<p>A informação age literacy (Nível 3+) correlaciona-se fortemente com todas as variáveis de política (colunas 1–7 na Tabela 5) e de forma extremamente negativa com o Gini (r = -.86). Os autores destacam também os dados do Fórum Econômico Mundial sobre o índice de prontidão em rede (<em>networked readiness index</em>): Dinamarca, Suécia e Finlândia estão entre os países melhor posicionados, e as correlações do índice com literacy na era da informação (r = .51) e com gasto público em ensino superior (r = .55) sugerem que os regimes social-democratas não apenas distribuem melhor, mas também competem efetivamente nas indústrias mais intensivas em conhecimento.</p>
</section>
</section>
<section id="mudanças-ao-longo-do-tempo-pp.-624630" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mudanças-ao-longo-do-tempo-pp.-624630">Mudanças ao Longo do Tempo (pp.&nbsp;624–630)</h2>
<section id="origens-históricas-dos-regimes-5057" class="level3" data-number="0.13">
<h3 data-number="0.13" class="anchored" data-anchor-id="origens-históricas-dos-regimes-5057"><span class="header-section-number">0.13</span> Origens históricas dos regimes [§50–§57]</h3>
<p>O fato de que a educação pública antecede a democracia e a legislação social moderna aponta para a estreita relação entre capital humano e eficiência produtiva: habilidades são um fator de produção que não pode ser dissociado dos trabalhadores que as possuem, tornando o investimento público em educação simultaneamente um determinante do poder de barganha e uma questão de política distributiva. Ansell (2005) documentou empiricamente a associação entre democracia e investimento em educação pública para as massas.</p>
<p>A análise histórica dos autores apoia-se fortemente em Cusack, Iversen e Soskice (2007), que constroem sobre Crouch (1993), Thelen (2004) e outros. O argumento é que industrialização e democratização tiveram efeitos muito diferentes sobre o desenvolvimento dos sistemas de habilidades dependendo da organização pré-industrial da produção e da organização pré-democrática do Estado. Os países que adotaram RP e CMEs eram originalmente <em>Ständestaaten</em> — com representação funcional dos interesses econômicos — e apresentavam, no final do século XIX, economias rurais e urbanas localmente coordenadas, combinando cooperativas rurais e sistemas artesanais regulamentados. Os países que emergiram como países majoritários com LMEs possuíam estados liberais que não suportavam representação corporatista, e uma estrutura econômica com grandes fazendas independentes e trabalho agrícola sem terra, combinada com sistemas artesanais fracamente regulamentados.</p>
<p>Onde as guildas eram fracas ou foram abolidas precocemente, o setor artesanal não pôde monopolizar a produção de habilidades, e os sindicatos passaram a representar artesãos com forte incentivo para limitar a entrada no ofício e controlar o conteúdo do trabalho nas empresas. Como os empregadores eram mal organizados e o estado liberal não podia ser usado para superar problemas de ação coletiva, os empregadores responderam pressionando por mercados de trabalho desregulamentados e minimizando benefícios de bem-estar e desemprego para enfraquecer o poder dos sindicatos artesanais. A divisão de interesses entre trabalhadores qualificados e não qualificados impediu o surgimento de uma classe trabalhadora unificada, e a direita não teve razão para se opor a um sistema majoritário que cimentaria essa divisão.</p>
<p>Nos países europeus continentais e na Escandinávia, tanto camponeses quanto artesãos operavam em marcos localmente coordenados, e o setor artesanal urbano era formal ou informalmente regulamentado. A existência de um sistema de formação artesanal relativamente eficaz e formalizado foi importante não apenas por ter produzido ampla oferta de trabalhadores qualificados para a Revolução Industrial, mas também porque significava que os sindicatos não podiam construir estratégias baseadas no controle da oferta de habilidades. Em ambas as economias, continental e escandinava, os sindicatos gradualmente passaram a ver um interesse comum com os empregadores industriais na extensão do sistema vocacional — o que se tornou a base para os sistemas cooperativos de relações industriais e formação vocacional que emergiram nesses países.</p>
<p>Os autores enfatizam que os VoC se desenvolveram <strong>antes</strong> dos regimes de bem-estar, que só se tornaram plenamente reconhecíveis no final dos anos 1960, quando a expansão dos serviços sociais públicos, do ensino superior e da participação feminina no mercado de trabalho começaram a diferenciar claramente os regimes social-democrata e DC. A organização patronal forte já estava estabelecida em 1914. Por meados dos anos 1920, os sindicatos em todos os CMEs (exceto a Finlândia) tinham desenvolvido estruturas centralizadas; nenhum dos LMEs desenvolveu estruturas sindicais semelhantes.</p>
<p>Politicamente, o complemento do corporatismo era a RP. O lado patronal tinha forte razão para favorecer a RP, pois era o único sistema de representação — uma vez que a industrialização havia avançado ao nível nacional — que permitiria regulação conjunta de padrões de formação, relações industriais e seguro social quando acoplado a um sistema corporatista de barganha burocrática entre sindicatos e associações patronais. Em sistemas majoritários de votante mediano, nem o capital nem o trabalho têm garantias de que o governo apoiará o conjunto de arranjos de mercado de trabalho e de formação que um arranjo cooperativo requer.</p>
<blockquote class="blockquote">
<p><strong>Nota 3 (cont.):</strong> Os autores apoiam-se em Hechter e Brustein (1980) para argumentar que a “produção de commodities de pequena escala” (<em>petty commodity production</em>) — redes rurais-urbanas integradas baseadas em artesãos rurais, dispersão da propriedade e ausência de estrutura de classe rígida — foram solo fértil para coalizões de classe cruzada e podem explicar o sucesso continuado dos partidos DC nos países europeus continentais. Esse padrão de organização rural contrasta com a Escandinávia, onde a agricultura não tinha os mesmos laços e dependências das economias urbanas, favorecendo o surgimento de coalizões vermelho-verdes e, posteriormente, de centro-esquerda.</p>
</blockquote>
</section>
<section id="trajetórias-pós-guerra-e-consolidação-dos-regimes-5862" class="level3" data-number="0.14">
<h3 data-number="0.14" class="anchored" data-anchor-id="trajetórias-pós-guerra-e-consolidação-dos-regimes-5862"><span class="header-section-number">0.14</span> Trajetórias pós-guerra e consolidação dos regimes [§58–§62]</h3>
<p>Os autores retomam a contribuição de Hicks (1999) para estabelecer que, embora organizações laborais fortes e partidos social-democratas tenham contribuído para o desenvolvimento da política social antes do período pós-Segunda Guerra Mundial, os regimes distintos de bem-estar não eram ainda discerníveis em 1950. O grupo de países que havia alcançado consolidação do bem-estar em 1952 incluía três regimes liberais (Reino Unido, Austrália e Nova Zelândia) e não incluía nenhum regime social-democrata (a Finlândia estava fora) nem três regimes DC (Suíça, Alemanha e França). O desenvolvimento dos três mundos é em grande medida produto dos padrões distintos de governo partidário experimentados ao final das primeiras três décadas do pós-guerra. <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/8deba3a4-1f2f-488f-8e35-09e59e49c1f0/Iversen-and-Stephens-2008-Partisan-Politics-the-Welfare-State-and-Three-Worlds-of-Human-Capital-Formation.pdf">ppl-ai-file-upload.s3.amazonaws</a></p>
<p>A ligação causal entre as VoC do período entre guerras e as coalizões partidárias do pós-guerra reside na força e estrutura dos sindicatos e no sistema eleitoral. A RP com sindicatos centralizados e moderadamente fortes, característica das CMEs do período entre guerras, levou à dominância social-democrata (países nórdicos), dominância DC (Alemanha) ou coalizões DC–social-democráticas (Benelux). As variações entre CMEs no desenvolvimento do Estado de bem-estar no pós-guerra são explicadas pelas variações na força da democracia-cristã e na força sindical — sendo que a última é parcialmente endógena, já que governos social-democratas facilitaram o crescimento sindical.</p>
<p>O ponto de síntese histórica é que, ao final do período de análise, as configurações que dividiram os países em seus respectivos mundos de bem-estar estavam já em vigor antes de 1950, mesmo que os três mundos não fossem plenamente reconhecíveis até os anos 1970–80. Países com RP e partidos DC significativos produziram governos de coalizão DC, com variações na redistribuição dependendo da força da social-democracia e dos pontos de veto. Países com RP mas sem DC significativo produziram governos social-democratas ou coalizões de centro-esquerda, com alta redistribuição e gasto educacional. Países sem DC significativo e com sistemas majoritários produziram desproporcionalmente governos de direita, com relativamente pouca redistribuição e gasto público em educação.</p>
</section>
<section id="mudanças-recentes-desindustrialização-e-respostas-governamentais-6368" class="level3" data-number="0.15">
<h3 data-number="0.15" class="anchored" data-anchor-id="mudanças-recentes-desindustrialização-e-respostas-governamentais-6368"><span class="header-section-number">0.15</span> Mudanças recentes: desindustrialização e respostas governamentais [§63–§68]</h3>
<p>A combinação de gasto educacional partidário, instituições de formação vocacional e sistemas de relações industriais ajuda a compreender as diferenças cross-nacionais na distribuição de salários em um determinado momento. A questão das mudanças ao longo do tempo requer atenção às transformações tecnológicas e às estruturas de produção que alteram o poder relativo de grupos de trabalhadores. A centralização da barganha e a compressão dos salários interocupacionais nos anos 1960 e 1970 devem ser compreendidas no contexto da difusão das tecnologias de produção em massa fordista, que criou complementaridades fortes entre trabalhadores qualificados e semiqualificados, conferindo a estes últimos um poder de barganha que antes não possuíam. <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/8deba3a4-1f2f-488f-8e35-09e59e49c1f0/Iversen-and-Stephens-2008-Partisan-Politics-the-Welfare-State-and-Three-Worlds-of-Human-Capital-Formation.pdf">ppl-ai-file-upload.s3.amazonaws</a></p>
<p>Essas complementaridades foram desfeitas pelas mudanças tecnológicas dos anos 1980 e 1990, que habilitaram a produção em pequenos lotes e deslocaram a demanda em direção a trabalhadores qualificados (Piore &amp; Sabel, 1984; Streeck, 1991). A elas somou-se a ascensão dos serviços, que dependem intensivamente de trabalho semiqualificado com fracas ligações ao trabalho qualificado. Em sistemas de barganha relativamente fragmentados, como o britânico, essas mudanças significaram que os sindicatos de trabalhadores semiqualificados perderam membros. Em alguns países do norte europeu com sistemas altamente centralizados, as mudanças levaram trabalhadores qualificados e seus empregadores (especialmente no setor de engenharia) a romper com o sistema centralizado. Contudo, em todos os países onde trabalhadores qualificados e empregadores tinham investimentos significativos em ativos coespecíficos, a coordenação salarial foi reestabelecida nos níveis de indústria e setor.</p>
<p>A razão principal pela qual os sindicatos de semiqualificados no Reino Unido e nos EUA perderam a maior parte de seus membros foi o fim do fordismo — sistema baseado em longas linhas de montagem e processos de produção estreitamente acoplados que davam aos sindicatos o poder de interromper a produção. Nos países majoritários, esse declínio foi exacerbado por ataques partidários às bases organizacionais dos sindicatos — um fenômeno amplamente restrito a países majoritários. A notável exceção ao declínio sindical generalizado foram Bélgica, Dinamarca, Finlândia e Suécia, países onde a administração dos benefícios de desemprego e a alocação de novos empregos é delegada aos sindicatos (sistema de Ghent), conferindo-lhes vantagem distinta na organização de trabalhadores. <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/8deba3a4-1f2f-488f-8e35-09e59e49c1f0/Iversen-and-Stephens-2008-Partisan-Politics-the-Welfare-State-and-Three-Worlds-of-Human-Capital-Formation.pdf">ppl-ai-file-upload.s3.amazonaws</a></p>
<p>Embora o efeito das mudanças tecnológicas tenha sido similar entre países, as respostas governamentais variaram notavelmente. Usando pesquisas de especialistas para medir a ideologia esquerda-direita dos partidos com representação legislativa, ponderada por sua proporção de assentos, os autores constatam que não houve virtualmente nenhuma mudança no equilíbrio partidário desde a Segunda Guerra Mundial em termos gerais — mas há diferenças distintas entre países, e os governos partidários responderam aos desafios da mudança tecnológica e da desindustrialização de formas que seguem de perto a estrutura de classe subjacente das coalizões governamentais. Nos países com partidos DC fortes, houve tendência para que a crescente bifurcação de riscos no mercado de trabalho fosse reforçada pelas políticas governamentais, com benefícios de desemprego e políticas ativas de mercado de trabalho não acompanhando as necessidades crescentes dos trabalhadores deslocados. Nos países com forte social-democracia, as políticas governamentais amorteceram os efeitos das mudanças no mercado de trabalho. Nos LMEs, o mercado foi amplamente deixado a se adaptar, sem tentativas concertadas de enfrentar o dramático aumento da desigualdade.</p>
</section>
</section>
<section id="conclusão-pp.-630632" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="conclusão-pp.-630632">Conclusão (pp.&nbsp;630–632)</h2>
<section id="síntese-dos-três-mundos-e-agenda-de-pesquisa-6973" class="level3" data-number="0.16">
<h3 data-number="0.16" class="anchored" data-anchor-id="síntese-dos-três-mundos-e-agenda-de-pesquisa-6973"><span class="header-section-number">0.16</span> Síntese dos três mundos e agenda de pesquisa [§69–§73]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese conclusiva:</strong> A síntese entre PRT e WPR revela que os três mundos de capitalismo de bem-estar correspondem a três mundos distintos de formação de capital humano, cada qual com padrão característico de estratificação do mercado de trabalho — e que as origens históricas desses padrões remontam à organização pré-industrial da produção e da política.</p>
</div>
</div>
<p>A conclusão retoma e sistematiza a contribuição do artigo. Com base nas proposições da WPR, identificam-se dois padrões de política social (CME com alta proteção social e alta proteção ao emprego; LME com baixos níveis em ambas) e dois padrões de educação e formação de habilidades (CME com alta formação vocacional e alta proporção de habilidades específicas; LME com baixa formação vocacional). Com base na PRT, as CMEs são divididas em dois regimes distintos de Estado de bem-estar: os regimes social-democratas (alta redistribuição, alta provisão de serviços sociais públicos, políticas de equidade de gênero e alta participação feminina) e os regimes DC (redistribuição variável, baixa provisão de serviços sociais públicos, baixa equidade de gênero e baixa participação feminina). <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/8deba3a4-1f2f-488f-8e35-09e59e49c1f0/Iversen-and-Stephens-2008-Partisan-Politics-the-Welfare-State-and-Three-Worlds-of-Human-Capital-Formation.pdf">ppl-ai-file-upload.s3.amazonaws</a></p>
<p>Os sistemas eleitorais situam-se na interseção das duas teorias: a RP permite a coordenação na regulação dos sistemas de formação, emprego e proteção social — característica central do sistema político segundo a WPR — ao mesmo tempo em que induz coalizões vencedoras mínimas em políticas fiscais que favorecem o centro-esquerda — central para a PRT. Como os partidos DC são coalizões de classe cruzada, eles modificam a relação entre RP e redistribuição, resultando em proteção social mais baseada em seguro.</p>
<p>O regime social-democrata é caracterizado por: altos gastos em creches, pré-escola, educação primária e secundária, ensino superior, políticas ativas de mercado de trabalho e educação vocacional; proteção ao emprego moderada. O resultado é alta formação de habilidades específicas à indústria e à ocupação e alto nível de habilidades gerais, particularmente na mediana e na base da distribuição — o que os autores identificam como raiz do sucesso desses países em tecnologia da informação e comunicação. <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/8deba3a4-1f2f-488f-8e35-09e59e49c1f0/Iversen-and-Stephens-2008-Partisan-Politics-the-Welfare-State-and-Three-Worlds-of-Human-Capital-Formation.pdf">ppl-ai-file-upload.s3.amazonaws</a></p>
<p>O regime DC é caracterizado por: alta educação vocacional e proteção ao emprego; gasto médio em educação primária, secundária e terciária; baixo gasto em creches, pré-escola e políticas ativas de mercado de trabalho. O resultado é alto nível de habilidades específicas à firma e ao setor, e nível moderadamente alto de habilidades gerais na base. O regime liberal é caracterizado por: baixo gasto em creches, pré-escola, políticas ativas de mercado de trabalho e formação vocacional; baixa proteção ao emprego; gasto moderado em educação primária, secundária e terciária; alto gasto privado em ensino superior. O resultado é baixo nível de habilidades específicas e baixo nível de habilidades gerais na base, mas nível de habilidades no topo comparável ao regime social-democrata.</p>
<p>Correspondendo a esses três mundos de formação de capital humano, há padrões distintos de estratificação do mercado de trabalho: alta desigualdade salarial no regime liberal; alta diferenciação entre <em>insiders</em> seguros e <em>outsiders</em> inseguros no regime DC; relativa ausência de ambas as divisões no regime social-democrata.</p>
</section>
</section>
<section id="argumento-sintético" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="argumento-sintético">Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> Iversen e Stephens argumentam que os três mundos do capitalismo de bem-estar (Esping-Andersen, 1990) correspondem a três mundos distintos de formação de capital humano, gerados pela interação entre sistemas eleitorais, partidos políticos e modos de organização capitalista; e que a integração entre Power Resources Theory e Welfare Production Regime Theory — mediante o papel mediador central dos sistemas de representação proporcional — oferece uma explicação superior para as diferenças cross-nacionais em investimento educacional e estrutura de habilidades do que qualquer uma das duas teorias isoladamente.</p>
<p><strong>Natureza do argumento:</strong> O argumento é simultaneamente causal (regimes político-eleitorais causam padrões de gasto em capital humano, evidenciado por análise de painel), estrutural-comparativo (os três mundos formam tipos coerentes de complementaridades institucionais) e histórico-institucional (as origens dos padrões remontam às formas pré-industriais de organização da produção e do Estado). A contribuição teórica é a reintegração da política educacional na análise comparativa do Estado de bem-estar — campo que havia excluído a educação seguindo Wilensky (1975).</p>
<p><strong>O que o texto demonstra com força:</strong> (1) Governo de esquerda é preditor robusto de gasto em capital humano em análise de painel; (2) os três regimes diferem sistematicamente tanto nos <em>inputs</em> (gasto) quanto nos <em>outputs</em> (habilidades), com diferenças muito mais pronunciadas na base do que no topo da distribuição; (3) as complementaridades institucionais entre regime de bem-estar, sistema de formação vocacional, relações industriais e estrutura salarial são empiricamente muito fortes (Tabela 5); (4) o contraste entre os dois caminhos para habilidades específicas — nórdico e continental — é bem documentado.</p>
<p><strong>O que permanece como hipótese ou agenda:</strong> (1) A causalidade bidirecional entre igualdade e formação de capital humano é afirmada como complementaridade mútua, mas não identificada causalmente — o design não isola choques exógenos; (2) a extensão do argumento a economias emergentes ou do Sul Global permanece como agenda não abordada; (3) o mecanismo pelo qual os sistemas eleitorais e as estruturas pré-industriais geraram os padrões históricos é argumentado narrativamente, sem formalização ou teste comparativo rigoroso.</p>
<p><strong>Contribuição para o debate mais amplo:</strong> O artigo representa um ponto de inflexão na literatura de bem-estar comparado ao demonstrar empiricamente que a dicotomia VoC (CME vs.&nbsp;LME) é insuficiente — porque ignora as diferenças cruciais entre os dois tipos de CME que a PRT permite capturar — e que a PRT é insuficiente sozinha — porque ignora as complementaridades entre proteção social e formação de habilidades. A síntese proposta tornou-se referência central para pesquisas posteriores sobre a política da educação vocacional, acesso ao ensino superior e desigualdade de habilidades em democracias avançadas.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>