<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-10">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: From How to Why — On Luminous Description and Causal Inference in Ethnography (Part I) – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1596dba0f6ebd5d6ff9514dff97656d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/tts-reader-1.0.0/tts-reader.js" defer="true"></script>
<link href="../site_libs/quarto-contrib/tts-reader-1.0.0/tts-reader.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: From How to Why — On Luminous Description and Causal Inference in Ethnography (Part I) – Annotated Bibliography">
<meta property="og:description" content="Katz, J. (2001). From how to why: On luminous description and causal inference in ethnography (Part I). Ethnography, 2(4), 443–473. https://doi.org/10.1177/14661381010020040​13">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#introdução-a-cultura-de-apreciação-e-o-dilema-howwhy-pp.-443449" id="toc-introdução-a-cultura-de-apreciação-e-o-dilema-howwhy-pp.-443449" class="nav-link" data-scroll-target="#introdução-a-cultura-de-apreciação-e-o-dilema-howwhy-pp.-443449"><span class="header-section-number">1</span> Introdução: A Cultura de Apreciação e o Dilema How/Why (pp.&nbsp;443–449)</a>
  <ul class="collapse">
  <li><a href="#o-reflexive-turn-e-a-lacuna-na-metodologia-etnográfica-14" id="toc-o-reflexive-turn-e-a-lacuna-na-metodologia-etnográfica-14" class="nav-link" data-scroll-target="#o-reflexive-turn-e-a-lacuna-na-metodologia-etnográfica-14"><span class="header-section-number">1.1</span> O reflexive turn e a lacuna na metodologia etnográfica [§1–§4]</a></li>
  <li><a href="#o-dilema-prático-por-que-como-precede-por-quê-59" id="toc-o-dilema-prático-por-que-como-precede-por-quê-59" class="nav-link" data-scroll-target="#o-dilema-prático-por-que-como-precede-por-quê-59"><span class="header-section-number">1.2</span> O dilema prático: por que “como” precede “por quê” [§5–§9]</a></li>
  <li><a href="#os-sete-critérios-e-a-tese-do-artigo-1014" id="toc-os-sete-critérios-e-a-tese-do-artigo-1014" class="nav-link" data-scroll-target="#os-sete-critérios-e-a-tese-do-artigo-1014"><span class="header-section-number">1.3</span> Os sete critérios e a tese do artigo [§10–§14]</a></li>
  </ul></li>
  <li><a href="#enigma-paradoxo-e-absurdo-pp.-449453" id="toc-enigma-paradoxo-e-absurdo-pp.-449453" class="nav-link" data-scroll-target="#enigma-paradoxo-e-absurdo-pp.-449453"><span class="header-section-number">2</span> Enigma, Paradoxo e Absurdo (pp.&nbsp;449–453)</a>
  <ul class="collapse">
  <li><a href="#o-enigma-como-convocação-explanatória-ferguson-e-briggs-1522" id="toc-o-enigma-como-convocação-explanatória-ferguson-e-briggs-1522" class="nav-link" data-scroll-target="#o-enigma-como-convocação-explanatória-ferguson-e-briggs-1522"><span class="header-section-number">2.1</span> O enigma como convocação explanatória: Ferguson e Briggs [§15–§22]</a></li>
  <li><a href="#o-absurdo-como-convocação-explanatória-etnometodologia-e-legal-aid-2326" id="toc-o-absurdo-como-convocação-explanatória-etnometodologia-e-legal-aid-2326" class="nav-link" data-scroll-target="#o-absurdo-como-convocação-explanatória-etnometodologia-e-legal-aid-2326"><span class="header-section-number">2.2</span> O absurdo como convocação explanatória: etnometodologia e Legal Aid [§23–§26]</a></li>
  </ul></li>
  <li><a href="#dados-estrategicamente-organizados-pp.-453462" id="toc-dados-estrategicamente-organizados-pp.-453462" class="nav-link" data-scroll-target="#dados-estrategicamente-organizados-pp.-453462"><span class="header-section-number">3</span> Dados Estrategicamente Organizados (pp.&nbsp;453–462)</a>
  <ul class="collapse">
  <li><a href="#bifurcação-do-conjunto-de-dados-frohmann-e-malkki-2734" id="toc-bifurcação-do-conjunto-de-dados-frohmann-e-malkki-2734" class="nav-link" data-scroll-target="#bifurcação-do-conjunto-de-dados-frohmann-e-malkki-2734"><span class="header-section-number">3.1</span> Bifurcação do conjunto de dados: Frohmann e Malkki [§27–§34]</a></li>
  <li><a href="#paralelismo-temporal-becker-e-wacquant-3544" id="toc-paralelismo-temporal-becker-e-wacquant-3544" class="nav-link" data-scroll-target="#paralelismo-temporal-becker-e-wacquant-3544"><span class="header-section-number">3.2</span> Paralelismo temporal: Becker e Wacquant [§35–§44]</a></li>
  </ul></li>
  <li><a href="#dados-ricos-variados-e-densamente-texturizados-pp.-462468" id="toc-dados-ricos-variados-e-densamente-texturizados-pp.-462468" class="nav-link" data-scroll-target="#dados-ricos-variados-e-densamente-texturizados-pp.-462468"><span class="header-section-number">4</span> Dados Ricos, Variados e Densamente Texturizados (pp.&nbsp;462–468)</a>
  <ul class="collapse">
  <li><a href="#tradições-de-descrição-densa-e-a-analogy-com-o-pesquisador-estatístico-4552" id="toc-tradições-de-descrição-densa-e-a-analogy-com-o-pesquisador-estatístico-4552" class="nav-link" data-scroll-target="#tradições-de-descrição-densa-e-a-analogy-com-o-pesquisador-estatístico-4552"><span class="header-section-number">4.1</span> Tradições de descrição densa e a analogy com o pesquisador estatístico [§45–§52]</a></li>
  <li><a href="#analytic-induction-roy-e-road-rage-da-densidade-ao-mecanismo-5358" id="toc-analytic-induction-roy-e-road-rage-da-densidade-ao-mecanismo-5358" class="nav-link" data-scroll-target="#analytic-induction-roy-e-road-rage-da-densidade-ao-mecanismo-5358"><span class="header-section-number">4.2</span> Analytic induction, Roy e road rage: da densidade ao mecanismo [§53–§58]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">5</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: From How to Why — On Luminous Description and Causal Inference in Ethnography (Part I)</h1>
<p class="subtitle lead">Katz, J. (2001). From how to why: On luminous description and causal inference in ethnography (Part I). <em>Ethnography</em>, <em>2</em>(4), 443–473. https://doi.org/10.1177/14661381010020040​13</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Methodology</div>
    <div class="quarto-category">Qualitative Methods</div>
    <div class="quarto-category">Causal Inference</div>
    <div class="quarto-category">Ethnography</div>
    <div class="quarto-category">2001</div>
    <div class="quarto-category">2000s</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Informações Técnicas e BibTeX
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Linha de modelo e timestamp:</strong></p>
<pre><code>Última atualização: 2026-05-10
Modelo: Claude Sonnet 4.5 (Perplexity)
Prompt Version: v17.3 · 2026-05-10
Gerado em: 2026-05-10T21:59:00-03:00
Ocasião da Leitura: Tentando relebrar o texto lido para a disciplina de Adrian Lavalle em 2024.</code></pre>
<p><strong>2. Entrada BibTeX</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 30%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo de texto</th>
<th style="text-align: left;">Entrada BibTeX</th>
<th style="text-align: left;">Campos obrigatórios</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Artigo em periódico</td>
<td style="text-align: left;"><code>@article</code></td>
<td style="text-align: left;">author, title, year, journal, volume, number, pages, doi</td>
</tr>
</tbody>
</table>
<p><strong>Entrada BibTeX → Katz2001</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">Katz2001</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>  = {Katz, Jack},</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>   = {From how to why: On luminous description and causal inference in ethnography ({Part I})},</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>    = {2001},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">journal</span> = {Ethnography},</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">volume</span>  = {2},</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">number</span>  = {4},</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span>   = {443--473},</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">doi</span>     = {10.1177/14661381010020040​13},</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.3</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A questão central parte da premissa de que existe uma tensão real na prática etnográfica entre o momento descritivo (como?) e o momento explicativo (por quê?). Uma interpretação alternativa seria que esse hiato seria um falso problema — que descrição e explicação são sempre simultâneas. Katz antecipa essa objeção mas a dissolve pragmaticamente. O ponto vulnerável é que a pergunta pressupõe que o objetivo normativo da etnografia deve ser a inferência causal.</td>
<td style="text-align: left;">Como etnógrafos podem transitar da descrição de como a vida social se estrutura para explicações de por que ela opera dessa maneira? — Pergunta metodológica de natureza prescritiva e reflexiva.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">Katz distingue duas subperguntas vinculadas: (1) O que na prática ordinária de avaliação de dados já orienta implicitamente esse trânsito? (2) Como cada tipo de dado “luminoso” fornece andaimes específicos para diferentes formas de inferência causal? A relação com a pergunta central é de operacionalização: as sete formas são respostas concretas à pergunta geral.</td>
<td style="text-align: left;">(1) O que constitui a “cultura de apreciação” dos dados etnográficos? (2) Como cada forma de dados luminosos aponta especificamente para mecanismos causais?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é metodológico, com dimensão normativa: é um gap entre prática efetiva e sua justificação explícita. Katz argumenta que etnógrafos já fazem análise causal mas carecem de um vocabulário reflexivo para articulá-la, o que os torna vulneráveis a críticas externas. O puzzle é genuíno e generalizável: o problema da transição indutiva entre descrição e explicação transcende a etnografia.</td>
<td style="text-align: left;">Puzzle metodológico-reflexivo: a etnografia produz inferência causal implicitamente, mas não possui um quadro explícito para articular essa lógica, deixando-a exposta tanto ao imperialismo quantitativo quanto ao anti-causalismo reflexivista.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese combina diagnóstico e prescrição: há sabedoria metodológica latente na cultura avaliativa dos etnógrafos, e essa sabedoria pode ser sistematizada. O <em>claim of discovery</em> é indutivo — derivado de “truques do ofício” — não de teoria dedutiva. Isso é ao mesmo tempo sua força (concretude) e limitação (arbitrariedade da seleção).</td>
<td style="text-align: left;">A tese central é que os critérios com que etnógrafos intuitivamente avaliam dados como “luminosos” já apontam para caminhos metodologicamente sólidos de inferência causal. Sistematizar essa cultura de apreciação é o caminho para articular uma metodologia etnográfica compatível com lógicas causais sem subordinar-se ao paradigma experimental.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O texto é teórico-metodológico com estratégia argumentativa indutiva: Katz parte de exemplos etnográficos concretos de múltiplos autores (Ferguson, Briggs, Frohmann, Malkki, Becker, Wacquant, Roy) para derivar categorias analíticas. Não há coleta original de dados; a evidência é a literatura etnográfica existente. O fichamento cobre a obra inteira (Parte I). Limitação: a seleção de exemplos é declaradamente arbitrária.</td>
<td style="text-align: left;">Ensaio teórico-metodológico. Estratégia indutiva a partir de casos exemplares da literatura antropológica e sociológica. Não utiliza dados originais; mobiliza etnografias existentes como evidência para categorias analíticas. Parte I de II.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP é bibliográfico-argumentativo: o fenômeno real é a prática etnográfica; a observação são os textos publicados; a coleta é a leitura seletiva guiada por critérios de “luminosidade” que o próprio autor está construindo. Há circularidade potencial: os exemplos são escolhidos para ilustrar as categorias que deveriam emergir deles. O viés de seleção é alto — Katz usa casos célebres (Geertz, Becker, Wacquant) que confirmam suas teses; casos onde dados “luminosos” levaram a explicações fracas ou falsas não aparecem.</td>
<td style="text-align: left;">Fenômeno: práticas de avaliação e argumentação etnográfica → Observação: leitura de etnografias publicadas → Coleta: seleção de passagens exemplares → Operacionalização: identificação de formas retóricas de “luminosidade” → Análise: vinculação de cada forma a um tipo de inferência causal → Inferência: indução de categorias analíticas aplicáveis. Viés de confirmação alto; unidade de análise é a passagem descritiva etnográfica.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">As três contribuições da Parte I são: (1) conceitualização de “dado luminoso” como articulador entre retórica descritiva e inferência causal; (2) tipologia de três formas (enigma/paradoxo/absurdo; dados estratégicos; dados ricos e variados); (3) reconceituação de “retrodição” como padrão mínimo de explicação para a etnografia. A contribuição mais forte e identificável pelo design é a tipologia. A conexão com causalidade no terceiro tipo (rich data + analytic induction) é mais robusta do que nos dois primeiros.</td>
<td style="text-align: left;">Contribuição teórico-metodológica: (1) formalização da “cultura de apreciação” etnográfica como recurso metodológico latente; (2) tipologia de três formas de dado luminoso com suas respectivas lógicas de inferência causal; (3) redefinição de explicação como retrodição, compatibilizando etnografia com lógica causal sem exigir positivismo preditivo.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">O argumento é mais forte na seção sobre dados estratégicos (Frohmann, Malkki), onde a lógica de controle de variáveis por comparação é concreta. É mais vulnerável no primeiro tipo (enigma/paradoxo): não é evidente que toda enigma leva a boa explicação causal; o argumento confunde saliência retórica com força epistêmica. A afirmação de que a “cultura de apreciação” é geral carece de evidência empírica. O próprio Katz reconhece isso. A tipologia de sete categorias não é exaustiva nem mutuamente exclusiva.</td>
<td style="text-align: left;">(a) Viés de seleção elevado nos exemplos; (b) O DGP (seleção de casos de sucesso) é incompatível com o <em>claim</em> de que as formas são critérios gerais; (c) Em designs qualitativos: não há rastreamento de mecanismo negativo — casos onde enigmas levaram a explicações fracas são ausentes; (d) A afirmação de que a tipologia é <em>induzida</em> de “tricks of the trade” não é consistente com a seleção deliberada de exemplos célebres; (e) Generalizabilidade: a cultura de apreciação descrita é predominantemente americana e da sociologia urbana qualitativa.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> Arbitrariedade na seleção dos exemplos; as categorias não são exaustivas; a afirmação de que a cultura de apreciação é geral é empírica e carece de evidência formal; o artigo é “apenas um começo”. <br> <strong>Não reconhecidas ou subestimadas:</strong> Circularidade entre seleção de exemplos e categorias analíticas; viés de confirmação na escolha de etnografias “de sucesso”; ausência de casos negativos; a “cultura de apreciação” está ancorada em uma tradição específica (segunda Escola de Chicago, sociologia urbana americana), o que limita sua generalização para etnografias indutivas, interpretativas ou pós-coloniais.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">Pragmatismo metodológico, com raízes na segunda Escola de Chicago (Hughes, Blumer, Becker). Há influência implícita de filosofia da ciência popperiana (falsificação, hipóteses rivais) e de Schutz/Garfinkel (intersubjetividade, etnometodologia como contraponto). A moldura é adequada para a tradição que Katz quer defender, mas cria uma tensão não resolvida: ao reivindicar compatibilidade com lógica causal sem abraçar o positivismo, o artigo fica em território ambíguo quanto ao realismo ontológico subjacente.</td>
<td style="text-align: left;">Pragmatismo metodológico; segunda Escola de Chicago; elementos de filosofia da ciência (retrodição, hipóteses rivais); diálogo crítico com o “reflexive turn” pós-Clifford/Marcus.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">Becker (1998), Frohmann (1991), Malkki (1995), Wacquant (1995/2000), Ferguson (1999), Geertz (1972/1973), Roy (1953), Briggs (1970/1987), Garfinkel (1967). O diálogo com a literatura pós-colonial e com métodos comparativos históricos é praticamente ausente. Não há interlocução com metodologia de inferência causal qualitativa contemporânea (e.g., King, Keohane &amp; Verba, 1994), o que é uma omissão conspícua dado que o artigo reivindica compatibilidade com lógica causal.</td>
<td style="text-align: left;">Becker (1998) como âncora metodológica central; Geertz como interlocutor crítico; Frohmann e Malkki como casos paradigmáticos de dados estratégicos; Wacquant e Roy como exemplos de dados temporais e ricos.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">A ausência de diálogo com KKV (1994) é especialmente notável dado que o artigo foi publicado em 2001 e trata explicitamente de inferência causal. A “retrodição” como padrão mínimo é promissora mas subdeterminada: Katz anuncia que a desenvolverá em trabalho futuro (Katz, “in press”), que seria relevante acompanhar. A Parte II (sets 4–7) é indispensável para avaliar a tipologia completa. Para pesquisa sobre metodologia qualitativa e inferência causal, o artigo é um contrapeso útil ao paradigma KKV, mas deve ser lido em conjunto com literature sobre process tracing e case studies que tomam a causalidade mais a sério analiticamente.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 19%">
<col style="width: 28%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Seção</th>
<th style="text-align: left;">Título / Tema</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Introdução (pp.&nbsp;443–449)</td>
<td style="text-align: left;">A cultura de apreciação e o dilema how/why</td>
<td style="text-align: left;">Apresentação do puzzle e fundamento teórico</td>
<td style="text-align: left;">Estabelece que a transição de como para por quê é um problema prático real; justifica a abordagem indutiva; define “dado luminoso” e anuncia os sete critérios</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção 1 (pp.&nbsp;449–453)</td>
<td style="text-align: left;">Enigma, paradoxo e absurdo</td>
<td style="text-align: left;">Análise empírica — tipo 1 de luminosidade</td>
<td style="text-align: left;">Demonstra que fenômenos enigmáticos ou paradoxais nos dados compelem o leitor à explicação causal; mobiliza Ferguson, Briggs e Katz (1982a)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seção 2 (pp.&nbsp;453–462)</td>
<td style="text-align: left;">Dados estrategicamente organizados</td>
<td style="text-align: left;">Análise empírica — tipo 2 de luminosidade</td>
<td style="text-align: left;">Demonstra duas formas de estratégia: bifurcação do conjunto de dados (Frohmann, Malkki) e paralelismo temporal (Becker et al., Wacquant); cada uma implicitamente nega hipóteses alternativas</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção 3 (pp.&nbsp;462–468)</td>
<td style="text-align: left;">Dados ricos, variados e densamente texturizados</td>
<td style="text-align: left;">Análise empírica — tipo 3 de luminosidade</td>
<td style="text-align: left;">Demonstra como conjuntos de dados densamente variados sobre um fenômeno específico permitem indução analítica e eliminação de rivais; mobiliza Roy e o estudo de road rage do próprio Katz</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Conclusão implícita / Agradecimentos e Notas (pp.&nbsp;468–473)</td>
<td style="text-align: left;">Consolidação e notas substantivas</td>
<td style="text-align: left;">Síntese e qualificação</td>
<td style="text-align: left;">As notas de rodapé 1–7 qualificam e estendem pontos do argumento central; não há conclusão formal — o artigo encerra após a seção 3, remetendo à Parte II</td>
</tr>
</tbody>
</table>
</section>
<section id="introdução-a-cultura-de-apreciação-e-o-dilema-howwhy-pp.-443449" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-a-cultura-de-apreciação-e-o-dilema-howwhy-pp.-443449"><span class="header-section-number">1</span> Introdução: A Cultura de Apreciação e o Dilema How/Why (pp.&nbsp;443–449)</h2>
<section id="o-reflexive-turn-e-a-lacuna-na-metodologia-etnográfica-14" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="o-reflexive-turn-e-a-lacuna-na-metodologia-etnográfica-14"><span class="header-section-number">1.1</span> O reflexive turn e a lacuna na metodologia etnográfica [§1–§4]</h3>
<p>Katz abre o artigo situando-se criticamente em relação ao que chama de “virada reflexiva” na escrita etnográfica, representada por trabalhos como Gusfield (1976), Clifford (1983), Clifford e Marcus (1986) e Van Maanen (1988). Essa literatura, ao revelar como os dispositivos literários da etnografia constroem implicitamente realidades sociais e reivindicam autoridade retórica, abriu linhas produtivas de questionamento — mas, no argumento de Katz, perpetua um fracasso mais antigo: a incapacidade de apreciar a lógica da própria cultura avaliativa por meio da qual os etnógrafos routineiramente julgam seus dados. A reflexividade voltou-se contra a retórica mas não examinou a sabedoria metodológica embutida na prática cotidiana.</p>
<p>Katz propõe que existe, atravessando os estilos de escrita e a divisão antropologia/sociologia, uma comunidade de avaliação de dados etnográficos — difusa, pouco articulada, mas real e operante. Essa comunidade se expressa em <strong>termos de apreciação</strong>: descrições são elogiadas como “ricamente variadas”, “densamente texturizadas”, “reveladoras”, “coloridas”, “vívidas”, “pungentes”, “estratégicas”, “nuançadas”; comportamentos são admirados quando “elaborados”, “situados” ou “ancorados”; e dados ganham valor quando contêm “paradoxos” e “enigmas”. Seu antônimo funcional é igualmente preciso: dados “finos”, “superficiais”, “abstratos”, “não convincentes” ou “estreitos” deflacionam o entusiasmo acadêmico.</p>
<blockquote class="blockquote">
<p><strong>Nota:</strong> A nota de rodapé 1 esclarece que Katz se situa na tradição sociológica (não antropológica) do debate: enquanto para antropólogos o debate pós-reflexivo questiona a possibilidade de escrever sobre cultura como unidade coerente, para sociólogos o foco é nos métodos úteis para descrever pessoas e explicar suas vidas sociais. Katz não rejeita a sensibilidade a cultura global e virtual, mas insiste que a ação humana permanece incorporada e situada. <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/1ee6e45c-43ef-4a74-8627-f386581769a1/Katz-2001-From-how-to-why-On-luminous-description-and-causal-inference-in-ethnography-Part-I.pdf">ppl-ai-file-upload.s3.amazonaws</a></p>
</blockquote>
</section>
<section id="o-dilema-prático-por-que-como-precede-por-quê-59" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="o-dilema-prático-por-que-como-precede-por-quê-59"><span class="header-section-number">1.2</span> O dilema prático: por que “como” precede “por quê” [§5–§9]</h3>
<p>A distinção entre <em>como</em> e <em>por quê</em> não é, para Katz, uma distinção ontológica — ele não afirma que descrição e explicação são separáveis em princípio. A distinção é <strong>prática e sequencial</strong>: na prática do campo, o pesquisador geralmente se dedica à descrição por um período substancial antes de conseguir reorganizar os dados em linhas explanatórias. A transição frequentemente não é óbvia enquanto não se completou uma fase dedicada de descrição.</p>
<p>Perguntar diretamente <em>por quê</em> aos sujeitos de pesquisa é uma saída tentadora, mas metodologicamente problemática. Mills (1940), Becker (1986) e Weiss (1993) alertam que a pergunta “por quê você fez isso?” induz os respondentes a antecipar a avaliação do pesquisador e a produzir justificativas socialmente aceitáveis — formatos atemporais e impessoais de raciocínio moral, não relatos dos processos situados que o pesquisador busca. A pergunta <em>como</em> é superior porque convida a uma resposta historicizada e temporalmente formatada, fazendo emergir a “história longa” de como redes de relações sociais e processos de interação moldaram o status presente do respondente.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Katz observa ainda que a confiança total nas respostas de <em>por quê</em> colocaria em questão a necessidade do próprio analista: se os sujeitos podem explicar confiavelmente suas ações, a análise social se reduziria à amplificação. A contribuição analítica reside precisamente em situar e transcender as explicações que os membros convencionalmente consideram satisfatórias.</p>
</div>
</div>
<p>A diferença entre <em>como</em> e <em>por quê</em> é igualmente decisiva para a prática observacional. Descrever <em>como</em> é uma tarefa razoável na observação <em>in situ</em>. Mas <em>por quê</em> requer logicamente dados em diferentes momentos (para tratar eventos no tempo 2 como resultado de eventos no tempo 1) e em diferentes lugares (para especificar quais características da situação foram tomadas como contingências relevantes pelos atores). Etnógrafos que afirmam ver <em>por quê</em> sem oferecer dados comparativos ficam vulneráveis a duas acusações: invocar poderes mágicos para ver dentro da mente dos sujeitos, ou pregar para o coro aplicando fórmulas explanatórias pré-definidas.</p>
<blockquote class="blockquote">
<p><strong>Nota:</strong> A nota 2 complementa o argumento: experimentos também requerem grupos de controle (comparação transversal) além da dimensão temporal. Isso sugere que a lógica causal subjacente tanto a experimentos quanto a etnografias estratégicas é fundamentalmente a mesma. <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/ea89e0bd-b532-4761-8d12-9b56dd8215a7/v17.3_2026-05-1o_qmd-books-map-update.md">ppl-ai-file-upload.s3.amazonaws</a></p>
</blockquote>
</section>
<section id="os-sete-critérios-e-a-tese-do-artigo-1014" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="os-sete-critérios-e-a-tese-do-artigo-1014"><span class="header-section-number">1.3</span> Os sete critérios e a tese do artigo [§10–§14]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central (§10–§13):</strong> Os critérios intuitivos com que leitores apreciam dados etnográficos como especialmente eficazes apontam, sabiamente, para vínculos metodologicamente sólidos entre a tarefa descritiva (mostrar <em>como</em> a vida social toma a forma que tem) e o desafio explanatório (argumentar <em>por que</em> ela funciona como funciona). Cada um dos sete critérios ilumina um modo distinto pelo qual a descrição etnográfica pode ser <strong>luminosa</strong> — promovendo subtilmente a busca por explicação causal.</p>
</div>
</div>
<p>Katz enumera os sete conjuntos de critérios, dos quais a Parte I trata os três primeiros: (1) dados ressonantes com enigma, paradoxo ou absurdo; (2) dados estrategicamente organizados em pelo menos dois sentidos (bifurcação do conjunto, ou paralelismo temporal com pontos de inflexão na vida dos sujeitos); e (3) dados ricos e variados que facilitam a eliminação de hipóteses rivais. Os critérios 4 a 7 — reveladores, situados, coloridos/vívidos, pungentes — serão tratados na Parte II.</p>
<p>Katz insiste que os sete critérios foram <strong>induzidos de “tricks of the trade”</strong> (Becker, 1998), não deduzidos de teoria ou filosofia. Isso implica três ressalvas: a seleção de exemplos contém arbitrariedade; uma mesma passagem pode caber em vários critérios; e a tipologia não é declaradamente exaustiva. O objetivo não é enunciar a lógica completa para avaliar etnografias, mas demonstrar que critérios de senso comum apontam para conexões metodologicamente defensáveis.</p>
<p>No enquadramento epistemológico mais amplo, Katz posiciona o artigo como parte de uma série de ensaios que buscam construir uma metodologia etnográfica compatível tanto com a tradição causal das ciências sociais quanto com métodos humanísticos. A <strong>explicação causal</strong>, para Katz, não exige o positivismo preditivo (prever o que ocorrerá no tempo 2 com base no tempo 1). Basta a <strong>retrodição</strong>: dado um fenômeno no tempo 2, é possível especificar o que terá ocorrido antes, talvez em uma sequência particular de estágios. Muitas das etnografias mais celebradas — o rinheiro de Geertz (1972), os vendedores de calçada de Duneier (1999) — já funcionam como explicações retrodictivas, mesmo sem ser apresentadas nesses termos.</p>
</section>
</section>
<section id="enigma-paradoxo-e-absurdo-pp.-449453" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="enigma-paradoxo-e-absurdo-pp.-449453"><span class="header-section-number">2</span> Enigma, Paradoxo e Absurdo (pp.&nbsp;449–453)</h2>
<section id="o-enigma-como-convocação-explanatória-ferguson-e-briggs-1522" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="o-enigma-como-convocação-explanatória-ferguson-e-briggs-1522"><span class="header-section-number">2.1</span> O enigma como convocação explanatória: Ferguson e Briggs [§15–§22]</h3>
<p>O primeiro tipo de dado luminoso surge quando o pesquisador se depara com um fenômeno que deveria ter um significado óbvio, mas obstinadamente não o tem. Katz distingue quatro subvariedades: (i) fenômenos inexplicáveis tanto para o pesquisador quanto para os membros; (ii) paradoxos que emergem como obstáculos ao tentar tecer padrões descritivos em uma narrativa coerente; (iii) ações autocontraditórias sustentadas coletivamente; (iv) momentos de absurdo, como quando dois participantes sustentam uma interação prolongada insistindo que não podem interagir.</p>
<p>O exemplo de James Ferguson em seu estudo sobre trabalhadores da Copperbelt zambiana ilustra o primeiro subtipo. Na parede de uma casa, Ferguson encontra a frase “Asia in miniature” cuidadosamente inscrita em letras de um centímetro, em inglês, por alguém que não entendia a língua — copiada da legenda de uma foto num atlas escolar. A frase não significava nada para os moradores. O enigma, porém, expandia-se: havia uma riqueza de estilos culturais não-zambianos justapostos de maneira igualmente indiferente. A explicação fácil (fascinação pela cultura ocidental) não se sustentava porque os objetos adotados eram tão prováveis de ser asiáticos ou caribenhos quanto ocidentais, e os trabalhadores não demonstravam interesse em entender essas culturas.</p>
<p>A resolução de Ferguson é sociologicamente significativa: à medida que os trabalhadores urbanos nas décadas de 1950 e 1960 adquiriram maior capacidade de viver independentemente de suas redes rurais, tornaram-se capazes de desconsiderar as obrigações associadas a essas redes — remessas, dote, visitas, sociabilidade local. Adotar uma mistura bizarra de estilos “estrangeiros” celebrava essa liberdade historicamente temporária dos laços locais. Para Katz, o que importa metodologicamente não é a substância da explicação de Ferguson, mas a sabedoria ampliável de sua experiência: uma única passagem descritiva, descrevendo um enigma transparentemente confrontado, pode lançar efetivamente uma curiosidade explanatória e convocar o leitor para o “jogo” da explicação.</p>
<p>Jean Briggs oferece um segundo caso — o de um paradoxo que emergiu gradualmente, após anos de trabalho de campo. Em suas pesquisas iniciais sobre os Inuit, Briggs havia construído uma imagem cultural baseada nos valores de amor/piedade e racionalidade, que explicava por que um povo aparentemente comprometido com o “controle sobre-humano de impulsos antissociais” conseguia criar crianças de cinco anos muito “bem-comportadas”. Anos depois, ela reconheceu que padrões que sempre havia observado estavam em tensão com essa imagem: havia jogos rotineiros nos quais adultos encenavam dramas sado-masoquistas com crianças — <em>“Por que você não mata seu irmãozinho? Assim!” [demonstrando]; “Me morda — mais forte! Ai! Não é divertido?”</em>. O paradoxo não é uma contradição nos dados, mas uma tensão encenada na própria interação dos sujeitos — o que o torna um enigma para o pesquisador. Briggs sugere que esses momentos de conflito dramatizado no cuidado com as crianças preparam o caminho para longos trechos de vida coletiva overtamente tranquila, e que a equanimidade social polida é uma espécie de pele cultural que detecta e reprime forças destrutivas. Katz observa que análises de práticas sociais autocontraditórias tendem a conter chaves explanatórias de amplo alcance, remetendo à análise de Erikson (1976) sobre a comunidade de Buffalo Creek.</p>
</section>
<section id="o-absurdo-como-convocação-explanatória-etnometodologia-e-legal-aid-2326" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="o-absurdo-como-convocação-explanatória-etnometodologia-e-legal-aid-2326"><span class="header-section-number">2.2</span> O absurdo como convocação explanatória: etnometodologia e Legal Aid [§23–§26]</h3>
<p>O absurdo como tipo de enigma tem uso mais direto na tradição etnometodológica, que parte das contribuições de Husserl, Schutz, Garfinkel e Cicourel. Para essa tradição, toda vida social repousa sobre uma presunção continuamente “bootstrapped” de intersubjetividade. Os experimentos de Garfinkel (1967) — pedir aos estudantes que agissem em casa como hóspedes, ou que pedissem explicitação de tudo que fosse ambíguo na fala de familiares — deliberadamente violavam essa presunção. Katz, porém, nota que etnometodólogos nunca desenvolveram um ofício etnográfico, em parte porque o fieldworker não pode se dar ao luxo de violar a intersubjetividade sistematicamente: precisa construir e manter rapport para coletar dados.</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> A nota 3 remete a Pollner e Emerson (2001) para a distinção relevante entre formas iniciais de etnometodologia (breaching experiments) e estudos posteriores em que o pesquisador tenta tornar-se membro. Cita Goode (1994) como demonstração de como questões etnometodológicas podem ser investigadas com dados etnográficos.</p>
</blockquote>
<p>Se etnógrafos relutam em criar cenas absurdas, encontrar um absurdo naturalmente ocorrente é, para Katz, uma ocasião de alegria metodológica. O exemplo que ele oferece vem de seu próprio estudo sobre advogados de assistência jurídica a clientes pobres: um advogado e um cliente passam ao menos 25 minutos discutindo sobre quem deveria comparecer ao tribunal de despejos — o advogado, que tem autoridade profissional, ou a cliente, que reivindica representação. O advogado afirma, em voz terapeuticamente calma, que se recusa a insultar a cliente tratando o caso por ela, pois ela é plenamente capaz. A cliente retorce: “Isso é Legal Aid; sou uma pessoa pobre, portanto sou sua patroa; e se eu quiser que o senhor me insulte, o senhor vai me insultar.” Katz caracteriza o impasse como um <em>double double bind</em>, um Catch-22 ao quadrado: ao argumentar tão poderosamente pela necessidade de serviço, a cliente demonstra sua capacidade de lidar com o problema; ao defender sua capacidade de cuidar de si mesma, o advogado torna seus serviços disponíveis apenas para quem não percebe precisar deles.</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> A solução organizacional do Legal Aid para evitar que tais absurdos se tornassem corriqueiros incluía criar um staff dedicado apenas a casos de apelação e ação coletiva — advogados que representavam clientes que nunca viam. Outra estratégia era encerrar interações negociando aparências de não-encerramento: “seu caso tem mérito, mas antes de podermos processar, o juiz exigiria x e y; reúna esses documentos e, se não resolver, volte”. A porta eternamente aberta se fechava sobre cliente após cliente sem que ninguém rastreasse se voltavam.</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>A revisão dos quatro subtipos de enigma (inexplicável para todos, paradoxo narrativo, ação autocontraditória sustentada coletivamente, absurdo interacional) consolida uma ideia comum: quando descrições iluminam a operação de enigmas, provocam a curiosidade sobre a grande pergunta sociológica — o que explica o senso de coerência aparente na vida dos sujeitos? O que permite que tomem por garantido que vivem num mundo social compartilhado?</p>
</div>
</div>
</section>
</section>
<section id="dados-estrategicamente-organizados-pp.-453462" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="dados-estrategicamente-organizados-pp.-453462"><span class="header-section-number">3</span> Dados Estrategicamente Organizados (pp.&nbsp;453–462)</h2>
<section id="bifurcação-do-conjunto-de-dados-frohmann-e-malkki-2734" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="bifurcação-do-conjunto-de-dados-frohmann-e-malkki-2734"><span class="header-section-number">3.1</span> Bifurcação do conjunto de dados: Frohmann e Malkki [§27–§34]</h3>
<p>Mesmo que etnógrafos não coletem dados segundo protocolos rígidos, frequentemente conseguem antecipar os debates explanatórios em que inevitavelmente entrarão. Em qualquer era de pesquisa, circulam explicações omnibus que leitores tenderão a aplicar ao que encontrarem no texto. Em resposta, o etnógrafo pode pensar estrategicamente na organização da coleta de dados.</p>
<p>O estudo de Lisa Frohmann (1991) sobre como o discriminação de gênero se insere no processamento judicial de casos de estupro exemplifica a estratégia de <strong>bifurcação do conjunto de dados</strong> pela variável explanatória rival. Frohmann dividiu seu tempo de observação participante entre dois escritórios de promotoria: um numa comunidade afluente e predominantemente branca (Bay City), outro numa cidade de baixa renda e maioria minoritária (Center Heights). Embora os casos diferissem — estupros em encontros amorosos no primeiro, casos com conexões com gangues, prostituição ou tráfico no segundo —, o processo de revisão e construção de casos era essencialmente o mesmo nos dois escritórios. Os promotores, independentemente de gênero, classe ou contexto comunitário, construíam histórias críveis, não julgavam a verdade; eram constrangidos pelos mesmos problemas antecipados (motivos ulteriores, discrepâncias nos relatos, variações da tipificação do ataque sexual) e desenvolviam um <em>habitus</em> profissional com um olhar prismático voltado simultaneamente para o passado da vítima, para o julgamento futuro de audiências e para a reputação que o promotor construía nos círculos de trabalho.</p>
<p>A força dos dados reside no que Katz chama de <strong>luminosidade por negação implícita</strong>: cada vez que um caso de Center Heights é descrito, o leitor automaticamente invoca em segundo plano os casos de Bay City, e vice-versa. Essa dupla camada de leitura opera sem que Frohmann precise explicitar que raça, pobreza ou ecologia comunitária não determinam o processamento — a negação da hipótese rival vem com mais força precisamente por ser feita de forma sutil. O mesmo mecanismo opera para a hipótese de viés de gênero: ao variar o sexo dos promotores nos casos descritos, Frohmann implicitamente nega que o gênero individual seja o agente determinante. O problema de injustiça, se existe, está profundamente implicado na identidade profissional compartilhada por promotores de ambos os sexos.</p>
<p>O estudo de Liisa Malkki (1995) sobre refugiados Hutu bifurca o conjunto de dados pelo lado do <strong>resultado</strong> (ou “variável dependente”). Massacres entre Hutu e Tutsi levaram a grandes movimentos de refugiados; alguns Hutu se instalaram em cidades, muitos foram reassentados em campos administrados por organizações internacionais. Malkki documenta que refugiados nos campos se concebiam como uma nação no exílio, com uma trajetória moral de provações que os habilitaria a reconquistar a “pátria”; refugiados nas cidades tendiam a buscar assimilação e identidades múltiplas e flutuantes.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Katz é explícito em resistir à tentação de chamar o estudo de Malkki de “experimento natural”: não há evidência de alocação aleatória, não há mensuração de identidade pré-refúgio, e a própria “variável independente” — o que especificamente no ambiente de campo ou cidade explica os diferentes processos identitários — permanece a ser explorada. A bifurcação organiza dados em moieties relevantes a debates causais sem comprometer-se com um vocabulário experimental que não seria sustentado pelo design.</p>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Nota :</strong> Katz observa que a bifurcação do conjunto de dados facilita a análise causal ao destacar casos negativos de variação contra-grupal dentro de cada população — Hutu nacionalistas na cidade, Hutu cosmopolitas no campo. O ambiente de campo institucionalizou o passado trágico, deixando pouco espaço identitário além de explorar os pontos em comum; o ambiente urbano convidava a estratégias de invisibilidade e incentivava a desenfatizar a identidade Hutu em acasalamento, residência e trabalho. Investigar os processos biográficos e interacionais que levaram a experiências excepcionais contra-grupais revelaria as contingências da identificação étnica apaixonada.</p>
</blockquote>
</section>
<section id="paralelismo-temporal-becker-e-wacquant-3544" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="paralelismo-temporal-becker-e-wacquant-3544"><span class="header-section-number">3.2</span> Paralelismo temporal: Becker e Wacquant [§35–§44]</h3>
<p>A segunda forma de dados estrategicamente organizados explora a <strong>estrutura temporal da coleta de dados</strong> em paralelo com a estrutura temporal dos processos de mudança pessoal e social examinados. O gênero de “tornar-se um…” tornou-se comum na pesquisa qualitativa americana de meados do século XX, especialmente no trabalho da segunda Escola de Chicago (Becker, Geer, Hughes, Blumer). Estudos de trajetórias em organizações burocráticas — internatos, escolas de medicina, academias de boxe, agências de serviços sociais — oferecem atrações estratégicas porque o pesquisador pode acompanhar coortes de novos membros processadas em calendário preciso através de transformações pessoais.</p>
<p>Katz desenvolve dois exemplos centrais contrastantes em estilo e tradição. No estudo clássico de Becker, Geer, Hughes e Strauss (1961) sobre socialização em escola de medicina, os pesquisadores encontraram estudantes tão tomados pelo <em>carisma</em> da prática médica e do conhecimento enciclopédico dos professores que não conseguiam justificar limitar seus estudos. A solução confortável, quando aparecia, apoiava-se em meios não racionais e sentimentais: a “cultura latente” compartilhada — cultura doméstica de estudantes casados, cultura de fraternidade universitária — fornecia uma base coletiva para negociar limitações de esforço. O que Becker e Geer chamaram de cultura latente foi a contribuição-chave: fornece às pessoas nas regiões mais racionalizadas das culturas tecnologicamente avançadas aquela qualidade mais elusiva e preciosa — a confiança.</p>
<p>Loïc Wacquant (2000), ao entrar como observador participante em uma academia de boxe no gueto de Chicago e investir três anos tornando-se boxeador, moldou um paralelismo estratégico entre a estrutura temporal de sua coleta de dados e a de seu próprio processo de desenvolvimento. Seus dados estabelecem rapidamente que há algo a explicar: a academia é um lugar de civismo rigorosamente disciplinado, e o novato desenvolve um novo perfil moral em contraste com os pares não-boxeadores do gueto. Com respeito à prática, o boxeador adquire um novo <em>habitus</em>, celebrado em uma estética recém-descoberta: “Conseguir dar um soco exatamente como você imaginou que ia dar, <em>isso é uma arte</em>.” O que explica o processo de mudança? Muitas das influências cruciais transcendem a força de vontade. Como um boxeador sabe que tem “coração”? Wacquant demonstra que a interação com outros na academia — como modelos de estilos a imitar, como colegas que empurram a superar limites objetivamente incognoscíveis, como o treinador Dee Dee que distribui julgamentos medidos sobre quando um boxeador está “pronto” — guia o processo de mudança pessoal de maneiras múltiplas.</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> A nota 6 cita Chambliss (1989) sobre nadadores como exemplo de fenômeno que se presta ao paralelismo temporal: carreiras de natação são relativamente curtas, permitindo pesquisa longitudinal verdadeira em poucos anos.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Nota :</strong> A nota 7 cita Wacquant (1995: 507) definindo boxe como “veículo de um projeto de transcendência ontológica pelo qual os que o abraçam buscam literalmente moldar-se em um novo ser para escapar das determinações comuns que pesam sobre eles e da insignificância social à qual essas determinações os condenam”.</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Katz generaliza o argumento: dados etnográficos estrategicamente estruturados para rastrear como pessoas atravessam transições ansiosamente monitoradas de um estado a outro tendem a descobrir que o funcionamento de uma cultura espiritual, mágica ou sentimental é uma contingência-chave — que explica por que alguns fazem a transição e outros não, sem impor determinismo. A retrodição é possível: dado o resultado (tornar-se médico confiante, boxeador pronto para lutar), pode-se especificar as etapas e condições que o antecedem. Quando reversibilidade é possível — boxeadores que “perdem o coração”, escritores que perdem a convicção — dados sobre a erosão do fenômeno oferecem testes adicionais para a explicação causal.</p>
</div>
</div>
</section>
</section>
<section id="dados-ricos-variados-e-densamente-texturizados-pp.-462468" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="dados-ricos-variados-e-densamente-texturizados-pp.-462468"><span class="header-section-number">4</span> Dados Ricos, Variados e Densamente Texturizados (pp.&nbsp;462–468)</h2>
<section id="tradições-de-descrição-densa-e-a-analogy-com-o-pesquisador-estatístico-4552" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="tradições-de-descrição-densa-e-a-analogy-com-o-pesquisador-estatístico-4552"><span class="header-section-number">4.1</span> Tradições de descrição densa e a analogy com o pesquisador estatístico [§45–§52]</h3>
<p>Nesta seção Katz mapeia tradições de apresentação de dados que cultivam a riqueza descritiva como virtude coletiva do ofício, antes de analisar sua função metodológica. Na segunda Escola de Chicago (estudantes de Hughes e Blumer), a escrita tinha simplicidade e diretividade cultivadas; os excertos de dados enfatizavam <em>gerenciamento de impressão</em> na interação face a face, detalhes sobre os desafios práticos do “trabalho” de produzir condutas, e estratégias idiossincráticas para superar problemas comuns. O “método de caso estendido” da Escola de Manchester (Gluckman, Victor Turner) descrevia casos ao longo do tempo e através de estágios distinguíveis, mostrando o interjogo de múltiplos indivíduos e grupos sociais num drama evolutivo — em contraste com a etnografia estrutural-funcional sincrônica de Radcliffe-Brown. Pierre Bourdieu produziu um estilo de colagem em que materiais etnográficos de várias fontes descrevem casos individuais em caixas flutuantes, com estruturas de frases complexas que comprimem descrição, autorreflexão, comentário filosófico e múltiplas ressalvas num único período que o leitor deve manter em movimento.</p>
<p>A “thick description” de Clifford Geertz (1973) é discutida pela sua celebridade e ambiguidade. Para Katz, “thick description” poderia sugerir um texto com numerosos casos ilustrando variações finas em torno de um tema — uma “thick description” do rinheiro em Bali seria construída a partir de evidências sobre um grande número de rinhas, permitindo sentido nuançado das variações entre elas e especificação de distinções para analogias em outras culturas (rinhas em Los Angeles, partidas de futebol que se tornam violência no Brasil, etc.). O que Geertz efetivamente propõe, porém, é mais corretamente <em>thick interpretation</em>: sem descrever casos individuais em detalhe — com apenas uma referência casual às “dezenas de rinhas que vi em Bali” — ele desconstrói o significado dramático de um tipo de evento encontrando por trás de seus modos típicos o funcionamento de múltiplas hierarquias sociais.</p>
<p>A apreciação de dados como “ricos e variados”, “contextualizados” e “densamente texturizados” contém ao menos três dimensões distintas. Primeira, <strong>riqueza, textura e contextualização</strong> capturam qualidades na apresentação de instâncias específicas: descrevem em detalhe fino como pessoas em ação levam em conta e respondem ao ambiente social e material imediato. Segunda, <strong>variados, massivos e densos</strong> voltam a atenção para o conjunto de dados como agregação: um grande número de cenas, ações ou casos. Terceira — e crucialmente —, “densamente texturizados” e “finamente detalhados” sugerem que o foco da pesquisa foi <strong>estreitado e tornado consistente</strong>: os dados como um todo caracterizam-se por variações próximas de cenas ou linhas de ação similares, não por instantâneos dispersos de um vasto terreno. A apreciação é análoga à satisfação do pesquisador estatístico ao ver curvas emergindo quando conecta clusters de pontos num gráfico.</p>
</section>
<section id="analytic-induction-roy-e-road-rage-da-densidade-ao-mecanismo-5358" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analytic-induction-roy-e-road-rage-da-densidade-ao-mecanismo-5358"><span class="header-section-number">4.2</span> Analytic induction, Roy e road rage: da densidade ao mecanismo [§53–§58]</h3>
<p>Katz localiza um problema rotineiro na etnografia: o excesso de descrição não decorre de falta de teoria, mas de excesso de ideias explanatórias. Hipóteses iniciais flutuam em quase todos os projetos etnográficos — como implicações culturais e implicações de estudos anteriores. À medida que se escrevem notas de campo e conduzem entrevistas, tanto parece relevante para tantos debates importantes que os dados, apesar de seu volume enorme, tornam-se dispersos e finos. A solução é colocar teoria e preocupações explanatórias de lado no campo para descrever o que parece ser mais ou menos o mesmo tipo de coisa, feita de novo, no mesmo lugar, por pessoas diferentes. Escrever notas de campo é melhor praticado como um ofício, distinto e separado de objetivos explanatórios substantivos (Emerson et al., 1995). A compilação de um conjunto de dados “massivo, densamente texturizado e ricamente variado” cria o recurso sobre o qual o trabalho de explicação incidirá.</p>
<p>A metodologia mais próxima de uma abordagem geral para minerar dados qualitativos para fins explanatórios é a <strong>indução analítica</strong> — usada implicitamente muito mais do que foi tornada explícita. Na indução analítica, os pesquisadores não sabem exatamente como definir o que deve ser explicado no início; buscam simultaneamente uma explicação que se ajuste a toda a evidência e uma definição do problema que torne relevante apenas a evidência que se ajusta à explicação. Casos negativos dão as ordens do dia: cada caso que não se encaixa força revisão tanto da explicação quanto da definição do problema.</p>
<p>O estudo de Donald Roy sobre restrição de quotas na fábrica ilustra o processo. A sociologia industrial dispunha de duas explicações — ressentimento dos trabalhadores, e auto-interesse econômico (evitar revisão das taxas de peça) — mas nenhuma se ajustava ao que Roy encontrou: trabalhadores às vezes ridicularizavam uns aos outros por não cumprir cotas; em outros momentos, passavam oportunidades lucrativas de trabalho extra; embora frequentemente desacelerassem, os períodos de lentidão eram desdenhados como entediantes e fisicamente cansativos, e os trabalhadores frequentemente se corriam para produzir tão rápido quanto possível. Os dados eram densamente detalhados — focados numa área de comportamento, não dispersos pela vida social da fábrica — e ricamente variados, mostrando não apenas restrição de quota, mas padrões inconsistentes com ela. Ao deslocar o foco explanatório para “satisfação no trabalho” (e mais precisamente, para uma experiência vívida de autodefinição), Roy pôde dar sentido a todas as variações: não se tratar de dinheiro ou ressentimento, mas de interesse em explorar o ambiente de trabalho para que ele devolvesse notícias vívidas sobre o self.</p>
<p>O próprio estudo de Katz sobre fúria no trânsito em Los Angeles (cap. 1 de <em>How Emotions Work</em>, 1999) serve como segundo exemplo. Os dados são densos em quatro sentidos: procedem de múltiplas fontes (observação participante, entrevistas com motoristas, incidentes relatados da perspectiva do passageiro); sua densidade vem de variações finas num ambiente prático específico (dirigir); os eventos são densos de drama porque emoções fortes emergem e normalmente declinam em curtos períodos de tempo; e Katz detalha estilos pessoais de equipar carros, comunicar-se com outros motoristas e usar estereótipos para xingar, especificando etnia, idade, gênero e classe social dos envolvidos — uma amostra extremamente diversa. Esses detalhes “coloridos” e aparentemente frívolos têm razões metodológicas: são formas de manter constantes e eliminar hipóteses rivais (que apenas pessoas de certas idades, gêneros ou etnias ficam com raiva ao volante; que se deve estar com pressa para ser ofendido; que se deve ter tido um dia ruim).</p>
<p>As variações de experiência entre as pessoas presentes também são registradas: passageiros frequentemente estão no mesmo trânsito, indo ao mesmo lugar, no mesmo humor que o motorista antes do incidente, mas enquanto o motorista fica com raiva, eles frequentemente ficam assustados ou acham o evento hilário. Perspectivas do banco do passageiro destacam a <strong>experiência incorporada de dirigir</strong> como condição causal central: parte da explicação terá de levar a sério a afirmação surreal de que motoristas, ao dirigir, literalmente se fundem com seus veículos — e que, quando o carro é interceptado, eles são imediata e intimamente interceptados.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>O drama nos dados não é uma boa representação estatística da experiência de dirigir em Los Angeles. A “cor” das descrições emerge como uma deliberada (embora às vezes não intencional) distorção estratégica: a coleta é guiada pelo objetivo metodológico de criar não uma amostra representativa de condução, mas um conjunto de descrições densamente detalhado, massivo e finamente variado de raiva emergindo e declinando num dado contexto prático. O etnógrafo serve à lógica científica da explicação causal coletando casos tightly clustered e finamente diferenciados, cada um dos quais pode servir para negar e forçar revisão de ideias explanatórias — sem precisar pensar constantemente nos requisitos de evidência científica.</p>
</div>
</div>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">5</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> Etnógrafos já realizam inferência causal implicitamente, ao apreciar certos dados como especialmente eficazes, e a sistematização dessa “cultura de apreciação” oferece uma metodologia para a transição de descrições do <em>como</em> para explicações do <em>por quê</em>.</p>
<p><strong>Natureza do argumento:</strong> Metodológico e prescritivo, com estratégia indutiva: as sete formas de dado luminoso são induzidas de práticas existentes (“tricks of the trade”), não deduzidas de teoria filosófica ou lógica formal. O conceito-chave de “retrodição” — como padrão mínimo de explicação causal — é o instrumento teórico central para compatibilizar etnografia com lógica causal sem exigir positivismo preditivo.</p>
<p><strong>O que o texto demonstra vs.&nbsp;o que fica como hipótese:</strong> A Parte I demonstra com força a segunda forma (dados estratégicos), especialmente o mecanismo de bifurcação comparativa (Frohmann, Malkki), onde a lógica de controle por comparação é mais concreta e verificável. A primeira forma (enigma/paradoxo) é sugestiva mas não demonstra que dados enigmáticos <em>levam a</em> boas explicações — apenas que os exemplos selecionados tiveram esse resultado. A terceira forma (rich data + analytic induction) é convincente como desiderato metodológico mas a conexão entre densidade descritiva e robustez causal permanece parcialmente como programa (a Parte II completará a tipologia).</p>
<p><strong>Contribuição para o debate mais amplo:</strong> O artigo intervém em duas frentes simultaneamente. Contra o “imperialismo quantitativo” (KKV, 1994 e afins), Katz demonstra que a etnografia possui uma lógica causal própria e defensável, distinta do paradigma experimental. Contra o anti-causalismo do reflexive turn (Clifford/Marcus), demonstra que a etnografia já realiza inferência causal — e que o reflexivismo estético ignorou essa dimensão. A contribuição teórica mais durável pode ser a reconceituação de “retrodição” como padrão mínimo de causalidade para métodos qualitativos, embora essa elaboração fique prometida para trabalho futuro.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>