<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-06-06">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Making Race and Nation – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1596dba0f6ebd5d6ff9514dff97656d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/tts-reader-1.0.0/tts-reader.js" defer="true"></script>
<link href="../site_libs/quarto-contrib/tts-reader-1.0.0/tts-reader.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Making Race and Nation – Annotated Bibliography">
<meta property="og:description" content="Marx, A. W. (1998). Making Race and Nation: A Comparison of South Africa, the United States, and Brazil. Cambridge University Press.">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#capítulo-1-introduction-pp.-125" id="toc-capítulo-1-introduction-pp.-125" class="nav-link" data-scroll-target="#capítulo-1-introduction-pp.-125"><span class="header-section-number">1</span> Capítulo 1: Introduction (pp.&nbsp;1–25)</a>
  <ul class="collapse">
  <li><a href="#o-problema-do-color-line-e-o-papel-do-estado-15" id="toc-o-problema-do-color-line-e-o-papel-do-estado-15" class="nav-link" data-scroll-target="#o-problema-do-color-line-e-o-papel-do-estado-15"><span class="header-section-number">1.1</span> O problema do color line e o papel do estado [§1–§5]</a></li>
  <li><a href="#contra-explicações-alternativas-610" id="toc-contra-explicações-alternativas-610" class="nav-link" data-scroll-target="#contra-explicações-alternativas-610"><span class="header-section-number">1.2</span> Contra explicações alternativas [§6–§10]</a></li>
  <li><a href="#a-teoria-da-construção-da-dominação-racial-1116" id="toc-a-teoria-da-construção-da-dominação-racial-1116" class="nav-link" data-scroll-target="#a-teoria-da-construção-da-dominação-racial-1116"><span class="header-section-number">1.3</span> A teoria da construção da dominação racial [§11–§16]</a></li>
  <li><a href="#dinâmica-do-protesto-negro-e-feedback-loops-1723" id="toc-dinâmica-do-protesto-negro-e-feedback-loops-1723" class="nav-link" data-scroll-target="#dinâmica-do-protesto-negro-e-feedback-loops-1723"><span class="header-section-number">1.4</span> Dinâmica do protesto negro e feedback loops [§17–§23]</a></li>
  <li><a href="#implicações-teóricas-e-estrutura-do-livro-2425" id="toc-implicações-teóricas-e-estrutura-do-livro-2425" class="nav-link" data-scroll-target="#implicações-teóricas-e-estrutura-do-livro-2425"><span class="header-section-number">1.5</span> Implicações teóricas e estrutura do livro [§24–§25]</a></li>
  </ul></li>
  <li><a href="#capítulo-2-trajectories-from-colonialism-pp.-2946" id="toc-capítulo-2-trajectories-from-colonialism-pp.-2946" class="nav-link" data-scroll-target="#capítulo-2-trajectories-from-colonialism-pp.-2946"><span class="header-section-number">2</span> Capítulo 2: Trajectories from Colonialism (pp.&nbsp;29–46)</a>
  <ul class="collapse">
  <li><a href="#a-tese-da-tolerância-racial-portuguesa-e-sua-crítica-15" id="toc-a-tese-da-tolerância-racial-portuguesa-e-sua-crítica-15" class="nav-link" data-scroll-target="#a-tese-da-tolerância-racial-portuguesa-e-sua-crítica-15"><span class="header-section-number">2.1</span> A tese da tolerância racial portuguesa e sua crítica [§1–§5]</a></li>
  <li><a href="#a-colonização-portuguesa-no-brasil-615" id="toc-a-colonização-portuguesa-no-brasil-615" class="nav-link" data-scroll-target="#a-colonização-portuguesa-no-brasil-615"><span class="header-section-number">2.2</span> A colonização portuguesa no Brasil [§6–§15]</a></li>
  <li><a href="#colonialismo-holandês-e-britânico-na-áfrica-do-sul-1630" id="toc-colonialismo-holandês-e-britânico-na-áfrica-do-sul-1630" class="nav-link" data-scroll-target="#colonialismo-holandês-e-britânico-na-áfrica-do-sul-1630"><span class="header-section-number">2.3</span> Colonialismo holandês e britânico na África do Sul [§16–§30]</a></li>
  <li><a href="#colonialismo-britânico-na-américa-do-norte-3143" id="toc-colonialismo-britânico-na-américa-do-norte-3143" class="nav-link" data-scroll-target="#colonialismo-britânico-na-américa-do-norte-3143"><span class="header-section-number">2.4</span> Colonialismo britânico na América do Norte [§31–§43]</a></li>
  <li><a href="#síntese-comparativa-4446" id="toc-síntese-comparativa-4446" class="nav-link" data-scroll-target="#síntese-comparativa-4446"><span class="header-section-number">2.5</span> Síntese comparativa [§44–§46]</a></li>
  </ul></li>
  <li><a href="#capítulo-3-lessons-from-slavery-pp.-4764" id="toc-capítulo-3-lessons-from-slavery-pp.-4764" class="nav-link" data-scroll-target="#capítulo-3-lessons-from-slavery-pp.-4764"><span class="header-section-number">3</span> Capítulo 3: Lessons from Slavery (pp.&nbsp;47–64)</a>
  <ul class="collapse">
  <li><a href="#a-escravidão-na-áfrica-do-sul-e-o-problema-da-herança-direta-13" id="toc-a-escravidão-na-áfrica-do-sul-e-o-problema-da-herança-direta-13" class="nav-link" data-scroll-target="#a-escravidão-na-áfrica-do-sul-e-o-problema-da-herança-direta-13"><span class="header-section-number">3.1</span> A escravidão na África do Sul e o problema da herança direta [§1–§3]</a></li>
  <li><a href="#o-mito-da-escravidão-humanitária-brasileira-415" id="toc-o-mito-da-escravidão-humanitária-brasileira-415" class="nav-link" data-scroll-target="#o-mito-da-escravidão-humanitária-brasileira-415"><span class="header-section-number">3.2</span> O mito da escravidão “humanitária” brasileira [§4–§15]</a></li>
  <li><a href="#abolição-no-brasil-continuidade-e-consenso-1625" id="toc-abolição-no-brasil-continuidade-e-consenso-1625" class="nav-link" data-scroll-target="#abolição-no-brasil-continuidade-e-consenso-1625"><span class="header-section-number">3.3</span> Abolição no Brasil: continuidade e consenso [§16–§25]</a></li>
  <li><a href="#escravidão-e-abolição-nos-estados-unidos-2640" id="toc-escravidão-e-abolição-nos-estados-unidos-2640" class="nav-link" data-scroll-target="#escravidão-e-abolição-nos-estados-unidos-2640"><span class="header-section-number">3.4</span> Escravidão e abolição nos Estados Unidos [§26–§40]</a></li>
  <li><a href="#o-desenvolvimento-da-ideologia-racista-nos-eua-4148" id="toc-o-desenvolvimento-da-ideologia-racista-nos-eua-4148" class="nav-link" data-scroll-target="#o-desenvolvimento-da-ideologia-racista-nos-eua-4148"><span class="header-section-number">3.5</span> O desenvolvimento da ideologia racista nos EUA [§41–§48]</a></li>
  <li><a href="#síntese-comparativa-4955" id="toc-síntese-comparativa-4955" class="nav-link" data-scroll-target="#síntese-comparativa-4955"><span class="header-section-number">3.6</span> Síntese comparativa [§49–§55]</a></li>
  </ul></li>
  <li><a href="#capítulo-4-the-uncertain-legacy-of-miscegenation-pp.-6578" id="toc-capítulo-4-the-uncertain-legacy-of-miscegenation-pp.-6578" class="nav-link" data-scroll-target="#capítulo-4-the-uncertain-legacy-of-miscegenation-pp.-6578"><span class="header-section-number">4</span> Capítulo 4: The Uncertain Legacy of Miscegenation (pp.&nbsp;65–78)</a>
  <ul class="collapse">
  <li><a href="#miscigenação-no-brasil-do-fato-demográfico-ao-mito-da-mobilidade-112" id="toc-miscigenação-no-brasil-do-fato-demográfico-ao-mito-da-mobilidade-112" class="nav-link" data-scroll-target="#miscigenação-no-brasil-do-fato-demográfico-ao-mito-da-mobilidade-112"><span class="header-section-number">4.1</span> Miscigenação no Brasil: do fato demográfico ao mito da mobilidade [§1–§12]</a></li>
  <li><a href="#miscigenação-nos-estados-unidos-a-regra-da-one-drop-1320" id="toc-miscigenação-nos-estados-unidos-a-regra-da-one-drop-1320" class="nav-link" data-scroll-target="#miscigenação-nos-estados-unidos-a-regra-da-one-drop-1320"><span class="header-section-number">4.2</span> Miscigenação nos Estados Unidos: a regra da “one drop” [§13–§20]</a></li>
  <li><a href="#miscigenação-na-áfrica-do-sul-a-categoria-coloured-2133" id="toc-miscigenação-na-áfrica-do-sul-a-categoria-coloured-2133" class="nav-link" data-scroll-target="#miscigenação-na-áfrica-do-sul-a-categoria-coloured-2133"><span class="header-section-number">4.3</span> Miscigenação na África do Sul: a categoria “coloured” [§21–§33]</a></li>
  <li><a href="#conclusão-miscigenação-como-categoria-política-não-biológica-3442" id="toc-conclusão-miscigenação-como-categoria-política-não-biológica-3442" class="nav-link" data-scroll-target="#conclusão-miscigenação-como-categoria-política-não-biológica-3442"><span class="header-section-number">4.4</span> Conclusão: miscigenação como categoria política, não biológica [§34–§42]</a></li>
  </ul></li>
  <li><a href="#capítulo-5-we-for-thee-south-africa-the-racial-state-pp.-84119" id="toc-capítulo-5-we-for-thee-south-africa-the-racial-state-pp.-84119" class="nav-link" data-scroll-target="#capítulo-5-we-for-thee-south-africa-the-racial-state-pp.-84119"><span class="header-section-number">5</span> Capítulo 5: “We for Thee, South Africa”: The Racial State (pp.&nbsp;84–119)</a>
  <ul class="collapse">
  <li><a href="#conflito-branco-e-unificação-forçada-pós-guerra-dos-bôeres-125" id="toc-conflito-branco-e-unificação-forçada-pós-guerra-dos-bôeres-125" class="nav-link" data-scroll-target="#conflito-branco-e-unificação-forçada-pós-guerra-dos-bôeres-125"><span class="header-section-number">5.1</span> Conflito branco e unificação forçada pós-Guerra dos Bôeres [§1–§25]</a></li>
  <li><a href="#competição-política-étnica-e-o-aprofundamento-da-segregação-1910-1948-2655" id="toc-competição-política-étnica-e-o-aprofundamento-da-segregação-1910-1948-2655" class="nav-link" data-scroll-target="#competição-política-étnica-e-o-aprofundamento-da-segregação-1910-1948-2655"><span class="header-section-number">5.2</span> Competição política étnica e o aprofundamento da segregação (1910-1948) [§26–§55]</a></li>
  <li><a href="#apartheid-e-a-unidade-branca-sob-o-national-party-1948-1966-5685" id="toc-apartheid-e-a-unidade-branca-sob-o-national-party-1948-1966-5685" class="nav-link" data-scroll-target="#apartheid-e-a-unidade-branca-sob-o-national-party-1948-1966-5685"><span class="header-section-number">5.3</span> Apartheid e a unidade branca sob o National Party (1948-1966) [§56–§85]</a></li>
  <li><a href="#a-crise-e-o-desmantelamento-gradual-1970s-1990s-86104" id="toc-a-crise-e-o-desmantelamento-gradual-1970s-1990s-86104" class="nav-link" data-scroll-target="#a-crise-e-o-desmantelamento-gradual-1970s-1990s-86104"><span class="header-section-number">5.4</span> A crise e o desmantelamento gradual (1970s-1990s) [§86–§104]</a></li>
  </ul></li>
  <li><a href="#capítulo-6-to-bind-up-the-nations-wounds-the-united-states-after-the-civil-war-pp.-12057" id="toc-capítulo-6-to-bind-up-the-nations-wounds-the-united-states-after-the-civil-war-pp.-12057" class="nav-link" data-scroll-target="#capítulo-6-to-bind-up-the-nations-wounds-the-united-states-after-the-civil-war-pp.-12057"><span class="header-section-number">6</span> Capítulo 6: “To Bind Up the Nation’s Wounds”: The United States after the Civil War (pp.&nbsp;120–57)</a>
  <ul class="collapse">
  <li><a href="#a-nação-dividida-guerra-civil-e-o-fortalecimento-do-estado-federal-118" id="toc-a-nação-dividida-guerra-civil-e-o-fortalecimento-do-estado-federal-118" class="nav-link" data-scroll-target="#a-nação-dividida-guerra-civil-e-o-fortalecimento-do-estado-federal-118"><span class="header-section-number">6.1</span> A nação dividida: Guerra Civil e o fortalecimento do estado federal [§1–§18]</a></li>
  <li><a href="#reconstrução-e-abandono-da-promessa-aos-negros-1944" id="toc-reconstrução-e-abandono-da-promessa-aos-negros-1944" class="nav-link" data-scroll-target="#reconstrução-e-abandono-da-promessa-aos-negros-1944"><span class="header-section-number">6.2</span> Reconstrução e abandono da promessa aos negros [§19–§44]</a></li>
  <li><a href="#jim-crow-competição-partidária-e-consolidação-nacional-4575" id="toc-jim-crow-competição-partidária-e-consolidação-nacional-4575" class="nav-link" data-scroll-target="#jim-crow-competição-partidária-e-consolidação-nacional-4575"><span class="header-section-number">6.3</span> Jim Crow, competição partidária e consolidação nacional [§45–§75]</a></li>
  <li><a href="#o-movimento-dos-direitos-civis-e-o-fim-de-jim-crow-76104" id="toc-o-movimento-dos-direitos-civis-e-o-fim-de-jim-crow-76104" class="nav-link" data-scroll-target="#o-movimento-dos-direitos-civis-e-o-fim-de-jim-crow-76104"><span class="header-section-number">6.4</span> O movimento dos direitos civis e o fim de Jim Crow [§76–§104]</a></li>
  <li><a href="#a-brasilianização-das-relações-raciais-pós-jim-crow-105115" id="toc-a-brasilianização-das-relações-raciais-pós-jim-crow-105115" class="nav-link" data-scroll-target="#a-brasilianização-das-relações-raciais-pós-jim-crow-105115"><span class="header-section-number">6.5</span> A “brasilianização” das relações raciais pós-Jim Crow [§105–§115]</a></li>
  </ul></li>
  <li><a href="#capítulo-7-order-and-progress-inclusive-nation-state-building-in-brazil-pp.-15877" id="toc-capítulo-7-order-and-progress-inclusive-nation-state-building-in-brazil-pp.-15877" class="nav-link" data-scroll-target="#capítulo-7-order-and-progress-inclusive-nation-state-building-in-brazil-pp.-15877"><span class="header-section-number">7</span> Capítulo 7: “Order and Progress”: Inclusive Nation-State Building in Brazil (pp.&nbsp;158–77)</a>
  <ul class="collapse">
  <li><a href="#a-imagem-da-unidade-nacional-15" id="toc-a-imagem-da-unidade-nacional-15" class="nav-link" data-scroll-target="#a-imagem-da-unidade-nacional-15"><span class="header-section-number">7.1</span> A imagem da unidade nacional [§1–§5]</a></li>
  <li><a href="#abolição-pacífica-e-federalismo-615" id="toc-abolição-pacífica-e-federalismo-615" class="nav-link" data-scroll-target="#abolição-pacífica-e-federalismo-615"><span class="header-section-number">7.2</span> Abolição pacífica e federalismo [§6–§15]</a></li>
  <li><a href="#a-política-de-branqueamento-whitening-e-a-democracia-racial-como-ideologia-1635" id="toc-a-política-de-branqueamento-whitening-e-a-democracia-racial-como-ideologia-1635" class="nav-link" data-scroll-target="#a-política-de-branqueamento-whitening-e-a-democracia-racial-como-ideologia-1635"><span class="header-section-number">7.3</span> A política de branqueamento (whitening) e a democracia racial como ideologia [§16–§35]</a></li>
  <li><a href="#vargas-e-o-estado-corporativista-3645" id="toc-vargas-e-o-estado-corporativista-3645" class="nav-link" data-scroll-target="#vargas-e-o-estado-corporativista-3645"><span class="header-section-number">7.4</span> Vargas e o estado corporativista [§36–§45]</a></li>
  <li><a href="#a-persistência-da-desigualdade-sob-a-democracia-racial-4655" id="toc-a-persistência-da-desigualdade-sob-a-democracia-racial-4655" class="nav-link" data-scroll-target="#a-persistência-da-desigualdade-sob-a-democracia-racial-4655"><span class="header-section-number">7.5</span> A persistência da desigualdade sob a democracia racial [§46–§55]</a></li>
  </ul></li>
  <li><a href="#capítulo-8-we-are-a-rock-black-racial-identity-mobilization-and-the-new-south-africa-pp.-194216" id="toc-capítulo-8-we-are-a-rock-black-racial-identity-mobilization-and-the-new-south-africa-pp.-194216" class="nav-link" data-scroll-target="#capítulo-8-we-are-a-rock-black-racial-identity-mobilization-and-the-new-south-africa-pp.-194216"><span class="header-section-number">8</span> Capítulo 8: “We Are a Rock”: Black Racial Identity, Mobilization, and the New South Africa (pp.&nbsp;194–216)</a>
  <ul class="collapse">
  <li><a href="#consolidação-da-identidade-racial-e-protesto-inicial-120" id="toc-consolidação-da-identidade-racial-e-protesto-inicial-120" class="nav-link" data-scroll-target="#consolidação-da-identidade-racial-e-protesto-inicial-120"><span class="header-section-number">8.1</span> Consolidação da identidade racial e protesto inicial [§1–§20]</a></li>
  <li><a href="#black-consciousness-e-o-protesto-dos-anos-1970-80-2140" id="toc-black-consciousness-e-o-protesto-dos-anos-1970-80-2140" class="nav-link" data-scroll-target="#black-consciousness-e-o-protesto-dos-anos-1970-80-2140"><span class="header-section-number">8.2</span> Black Consciousness e o protesto dos anos 1970-80 [§21–§40]</a></li>
  <li><a href="#a-transição-negociada-4160" id="toc-a-transição-negociada-4160" class="nav-link" data-scroll-target="#a-transição-negociada-4160"><span class="header-section-number">8.3</span> A transição negociada [§41–§60]</a></li>
  </ul></li>
  <li><a href="#capítulo-9-burying-jim-crow-black-racial-identity-mobilization-and-reform-in-the-united-states-pp.-21749" id="toc-capítulo-9-burying-jim-crow-black-racial-identity-mobilization-and-reform-in-the-united-states-pp.-21749" class="nav-link" data-scroll-target="#capítulo-9-burying-jim-crow-black-racial-identity-mobilization-and-reform-in-the-united-states-pp.-21749"><span class="header-section-number">9</span> Capítulo 9: Burying Jim Crow: Black Racial Identity, Mobilization, and Reform in the United States (pp.&nbsp;217–49)</a>
  <ul class="collapse">
  <li><a href="#em-direção-à-solidariedade-racial-1877-1954-130" id="toc-em-direção-à-solidariedade-racial-1877-1954-130" class="nav-link" data-scroll-target="#em-direção-à-solidariedade-racial-1877-1954-130"><span class="header-section-number">9.1</span> Em direção à solidariedade racial (1877-1954) [§1–§30]</a></li>
  <li><a href="#o-movimento-dos-direitos-civis-3165" id="toc-o-movimento-dos-direitos-civis-3165" class="nav-link" data-scroll-target="#o-movimento-dos-direitos-civis-3165"><span class="header-section-number">9.2</span> O movimento dos direitos civis [§31–§65]</a></li>
  <li><a href="#a-virada-para-o-norte-e-o-black-power-6695" id="toc-a-virada-para-o-norte-e-o-black-power-6695" class="nav-link" data-scroll-target="#a-virada-para-o-norte-e-o-black-power-6695"><span class="header-section-number">9.3</span> A virada para o Norte e o Black Power [§66–§95]</a></li>
  <li><a href="#fragmentação-e-legado-96112" id="toc-fragmentação-e-legado-96112" class="nav-link" data-scroll-target="#fragmentação-e-legado-96112"><span class="header-section-number">9.4</span> Fragmentação e legado [§96–§112]</a></li>
  </ul></li>
  <li><a href="#capítulo-10-breaching-brazils-pact-of-silence-pp.-25063" id="toc-capítulo-10-breaching-brazils-pact-of-silence-pp.-25063" class="nav-link" data-scroll-target="#capítulo-10-breaching-brazils-pact-of-silence-pp.-25063"><span class="header-section-number">10</span> Capítulo 10: Breaching Brazil’s Pact of Silence (pp.&nbsp;250–63)</a>
  <ul class="collapse">
  <li><a href="#a-fragilidade-da-identidade-negra-sob-a-democracia-racial-120" id="toc-a-fragilidade-da-identidade-negra-sob-a-democracia-racial-120" class="nav-link" data-scroll-target="#a-fragilidade-da-identidade-negra-sob-a-democracia-racial-120"><span class="header-section-number">10.1</span> A fragilidade da identidade negra sob a democracia racial [§1–§20]</a></li>
  <li><a href="#a-atuação-do-movimento-negro-2145" id="toc-a-atuação-do-movimento-negro-2145" class="nav-link" data-scroll-target="#a-atuação-do-movimento-negro-2145"><span class="header-section-number">10.2</span> A atuação do movimento negro [§21–§45]</a></li>
  <li><a href="#o-papel-do-estado-e-a-cooptação-4655" id="toc-o-papel-do-estado-e-a-cooptação-4655" class="nav-link" data-scroll-target="#o-papel-do-estado-e-a-cooptação-4655"><span class="header-section-number">10.3</span> O papel do estado e a cooptação [§46–§55]</a></li>
  </ul></li>
  <li><a href="#capítulo-11-conclusion-pp.-26778" id="toc-capítulo-11-conclusion-pp.-26778" class="nav-link" data-scroll-target="#capítulo-11-conclusion-pp.-26778"><span class="header-section-number">11</span> Capítulo 11: Conclusion (pp.&nbsp;267–78)</a>
  <ul class="collapse">
  <li><a href="#síntese-do-argumento-110" id="toc-síntese-do-argumento-110" class="nav-link" data-scroll-target="#síntese-do-argumento-110"><span class="header-section-number">11.1</span> Síntese do argumento [§1–§10]</a></li>
  <li><a href="#o-desmantelamento-da-dominação-legal-1120" id="toc-o-desmantelamento-da-dominação-legal-1120" class="nav-link" data-scroll-target="#o-desmantelamento-da-dominação-legal-1120"><span class="header-section-number">11.2</span> O desmantelamento da dominação legal [§11–§20]</a></li>
  <li><a href="#generalizações-para-outros-casos-2130" id="toc-generalizações-para-outros-casos-2130" class="nav-link" data-scroll-target="#generalizações-para-outros-casos-2130"><span class="header-section-number">11.3</span> Generalizações para outros casos [§21–§30]</a></li>
  <li><a href="#implicações-normativas-3135" id="toc-implicações-normativas-3135" class="nav-link" data-scroll-target="#implicações-normativas-3135"><span class="header-section-number">11.4</span> Implicações normativas [§31–§35]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">12</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Making Race and Nation</h1>
<p class="subtitle lead">Marx, A. W. (1998). <em>Making Race and Nation: A Comparison of South Africa, the United States, and Brazil</em>. Cambridge University Press.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Comparative Politics</div>
    <div class="quarto-category">Race and Ethnic Politics</div>
    <div class="quarto-category">Historical Institutionalism</div>
    <div class="quarto-category">Nation-State Building</div>
    <div class="quarto-category">1998</div>
    <div class="quarto-category">1990s</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Informações Técnicas e BibTeX
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>Última atualização: 2026-06-06
Modelo: GPT-5.1 (OpenAI) via API
Prompt Version: v17.4 · 2026-05-13
Gerado em: 2026-06-06T14:30:00-03:00
Ocasião da Leitura: Fichamento integral para anotação bibliográfica</code></pre>
<p><strong>Entrada BibTeX → Marx1998</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@book</span>{<span class="ot">Marx1998</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>    = {Marx, Anthony W.},</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>     = {Making Race and Nation: A Comparison of South Africa, the United States, and Brazil},</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>      = {1998},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">publisher</span> = {Cambridge University Press},</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">address</span>   = {Cambridge, UK},</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">edition</span>   = {1st paperback},</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">isbn</span>      = {9780521584555},</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">doi</span>       = {}</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.4</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">O autor parte da premissa de que a literatura existente superestima as determinações históricas e culturais (colonialismo, escravidão, miscigenação) e subestima a agência estatal e os cálculos estratégicos de elites. Uma interpretação alternativa seria que os legados históricos de fato determinam as trajetórias, e Marx a refuta. O ponto mais vulnerável é a possível funcionalidade teleológica: o argumento de que a dominação racial foi “usada” para unificar brancos pode parecer, em retrospecto, uma justificativa racional ex post para políticas que emergiram de conflitos contingentes.</td>
<td style="text-align: left;">Pergunta central reconstruída: Por que e como a raça se tornou um aspecto central da política no século XX, resultando em ordens raciais legais drasticamente diferentes na África do Sul (apartheid), Estados Unidos (Jim Crow) e Brasil (democracia racial)?</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">O autor estrutura a resposta em torno de três subperguntas: (1) Como as trajetórias coloniais, a escravidão e a miscigenação pré-configuraram (mas não determinaram) as relações raciais? (2) Como os conflitos intra-brancos (étnicos nos EUA e na África do Sul, ausentes no Brasil) levaram elites a usar a exclusão racial como estratégia de construção de unidade nacional? (3) Como a dominação racial, uma vez institucionalizada, consolidou a identidade negra e provocou protestos que, por fim, forçaram seu desmantelamento?</td>
<td style="text-align: left;">As subperguntas são lógicas e necessárias para a tese principal. A segunda (conflito intra-branco) é o coração causal da explicação.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno e de grande importância comparativa: três sociedades com legados de discriminação racial e escravidão produziram ordens pós-abolição radicalmente distintas — duas com segregação legal (em diferentes graus de centralização) e uma sem segregação legal. O puzzle explicativo é resolvido pela introdução de uma variável omitida — o grau de conflito intra-branco prévio à consolidação do estado-nação.</td>
<td style="text-align: left;">Puzzle explicativo e comparativo, com alto poder de generalização para outros casos de formação do estado em sociedades multiétnicas.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">O autor argumenta que a construção de estados-nação no século XX, em resposta a conflitos internos, foi a força motriz por trás da codificação (ou não) da dominação racial. A tese tem uma estrutura causal clara: conflito intra-branco + ameaça percebida + necessidade de coalizão → exclusão racial legal → unidade branca. A “claim of discovery” é que o nacionalismo não é apenas um produto de exclusão, mas usa a exclusão racial como instrumento ativo de consolidação.</td>
<td style="text-align: left;">A raça foi central para os projetos de construção nacional. Na África do Sul e nos EUA, elites usaram a dominação racial para pacificar conflitos étnicos/regionais entre brancos, unindo-os contra um “outro” negro. No Brasil, a ausência de conflitos intra-brancos comparáveis permitiu a manutenção de uma ordem racial informal sob a ideologia de “democracia racial”. Essa construção da raça “de cima” teve a consequência não intencional de consolidar a identidade e a protesto negros “de baixo”, que eventualmente forçaram o fim da dominação legal.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O estudo é um clássico de análise comparativa histórica qualitativa (QCA em sentido amplo), com estudo de caso estruturado e comparado de três países. As fontes são secundárias (bibliografia extensa), mas também arquivos primários e entrevistas. A estratégia é de “comparação de trajetórias” (comparative historical analysis), buscando identificar mecanismos causais comuns e diferenças em momentos críticos. O fichamento cobre a obra completa.</td>
<td style="text-align: left;">A principal limitação metodológica é a dependência de evidências secundárias para inferências causais sobre intencionalidade de atores históricos (embora ele use citações e documentos primários). O design é forte para rastreamento de mecanismos, mas fraco para generalização estatística — o que ele reconhece implicitamente.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP é histórico-documental: eventos históricos reais (Boer War, Guerra Civil, abolição) → registros em arquivos, discursos políticos, constituições, legislação → seleção e interpretação por Marx → codificação em narrativas causais → comparação de processos. Unidade de análise: o país em períodos-chave (pivotal moments). Agregação: nacional e institucional. Vieses potenciais: seleção de documentos que confirmam a tese, interpretação teleológica de ações estratégicas, subestimação de contingências.</td>
<td style="text-align: left;">O autor é atento a esses vieses, discutindo alternativas (e.g., por que a Grã-Bretanha não se aliou aos negros na África do Sul?). A triangulação entre fontes de arquivo, entrevistas e historiografia secundária mitiga, mas não elimina, o viés de confirmação.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">(1) Teórico: Integração entre teoria do estado (state-building) e teoria racial, mostrando que a raça não é um resíduo, mas um instrumento de consolidação nacional. (2) Empírico: Demonstração sistemática de que a variável “conflito intra-branco” (étnico nos EUA/África do Sul; ausente no Brasil) explica a divergência das ordens legais. (3) Processual: Mostra o ciclo feedback loop — dominação racial → identidade negra → protesto → reforma institucional.</td>
<td style="text-align: left;">A contribuição mais robusta é a explicação para a divergência EUA/África do Sul vs.&nbsp;Brasil. A extensão para a dinâmica de protesto (Parte III) é mais especulativa e menos original, embora coerente. O autor demonstra que a hipótese funcionalista (dominação racial serve a interesses econômicos de classes) é insuficiente.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">O autor responde adequadamente à pergunta central, com evidência histórica convincente. O argumento é mais vulnerável em dois pontos: (1) A periodização dos “momentos críticos” (Boer War, Guerra Civil) pode sobrecarregar a importância de eventos únicos, minimizando processos graduais de mudança racial em outros períodos. (2) A causalidade entre conflito intra-branco e exclusão racial é plausível, mas Marx não testa explicitamente hipóteses rivais (e.g., o papel de ideologias raciais importadas da Europa independentemente do conflito doméstico). A generalizabilidade para outros contextos (e.g., Alemanha nazista, Ruanda) é sugerida, mas não desenvolvida.</td>
<td style="text-align: left;">A força da obra está em seu desenho comparativo; a fraqueza, na ausência de uma ligação microfundamentada mais precisa entre as intenções das elites e as políticas adotadas (embora o uso de fontes primárias amenize).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> O autor admite que a realidade é mais confusa que o esquema teórico, que há interações e feedbacks, e que a análise se concentra em três casos sem testar todas as alternativas. <br> <strong>Não reconhecidas ou subestimadas:</strong> (i) O papel das dinâmicas internacionais (exceto menções pontuais) na formação das políticas raciais; (ii) A agência negra antes da imposição da dominação racial é tratada como preliminar, mas poderia ter moldado as estratégias das elites; (iii) A análise do Brasil é mais frágita, baseando-se muito na ideologia de democracia racial sem explorar contra-exemplos de discriminação legal localizada.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">Instituto Historical Institutionalism (Skocpol, Evans, Tilly) combinado com teoria de movimentos sociais (Tarrow, McAdam) e literatura sobre nacionalismo (Anderson, Brubaker). A ontologia é relacional e processual: instituições e identidades se co-constroem. O método é compatível com a ontologia, pois o process tracing captura bem essa co-construção.</td>
<td style="text-align: left;">A perspectiva é adequada e, à época, inovadora ao trazer o estado de volta para a análise das relações raciais, contrapondo-se tanto ao marxismo economicista quanto ao culturalismo.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">Brubaker (1992) para cidadania excludente na Alemanha; Anderson (1983) para nação como comunidade imaginada; Fredrickson (1981, 1988) para comparação EUA/África do Sul; Tannenbaum (1946) e Degler (1971) para Brasil (refutados); Skocpol, Evans, Tilly (1985) para state-building. O diálogo com a literatura sobre escravidão (Genovese, Fogel) e populismo (Woodward) é robusto.</td>
<td style="text-align: left;">O diálogo com a literatura latino-americana sobre “democracia racial” é crítico e bem informado. Há pouca referência a teorias pós-coloniais ou descoloniais, o que é uma lacuna para a época mas coerente com o quadro institucionalista.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">O livro é uma referência central nos debates sobre raça e estado. A força analítica está na clara especificação da variável “conflito intra-branco” e na demonstração de como ela opera em momentos críticos. A fraqueza relativa é a Parte III, que, embora interessante, é menos inovadora que as Partes I e II. Para pesquisas sobre formação do estado em sociedades divididas, a obra é obrigatória.</td>
<td style="text-align: left;">A cobertura é integral e permite uma avaliação completa da arquitetura argumentativa.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 29%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Capítulo</th>
<th style="text-align: left;">Título</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Introdução (pp.&nbsp;1–25)</td>
<td style="text-align: left;">Introduction</td>
<td style="text-align: left;">Apresentação do puzzle e da tese</td>
<td style="text-align: left;">Define o problema de pesquisa, apresenta a teoria da dominação racial como ferramenta de construção nacional, antecipa as partes do livro e refuta explicações alternativas.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capítulo 2 (pp.&nbsp;29–46)</td>
<td style="text-align: left;">Trajectories from Colonialism</td>
<td style="text-align: left;">Fundamento histórico comparado</td>
<td style="text-align: left;">Estabelece que o legado colonial (português, holandês, britânico) não determinou diretamente as ordens raciais posteriores; destaca a maior unidade e centralização do Brasil vs.&nbsp;os conflitos étnicos/regionais na África do Sul e EUA.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capítulo 3 (pp.&nbsp;47–64)</td>
<td style="text-align: left;">Lessons from Slavery</td>
<td style="text-align: left;">Fundamento histórico comparado</td>
<td style="text-align: left;">Refuta a tese da escravidão mais “humanitária” no Brasil como explicação para a democracia racial; mostra que a escravidão foi brutal em todos os casos, mas que a diferença crucial foi a extensão regional do conflito sobre a escravidão (nacional no Brasil, regional nos EUA).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capítulo 4 (pp.&nbsp;65–78)</td>
<td style="text-align: left;">The Uncertain Legacy of Miscegenation</td>
<td style="text-align: left;">Fundamento histórico comparado</td>
<td style="text-align: left;">Mostra que a miscigenação não impediu a categorização racial rígida nos EUA/África do Sul; no Brasil, a ideologia da miscigenação serviu como mito de mobilidade, não como barreira à discriminação informal.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capítulo 5 (pp.&nbsp;84–119)</td>
<td style="text-align: left;">“We for Thee, South Africa”: The Racial State</td>
<td style="text-align: left;">Estudo de caso (África do Sul)</td>
<td style="text-align: left;">Aplica a tese central: conflito étnico entre britânicos e afrikaners, culminando na Guerra dos Bôeres, leva elites britânicas a abandonarem promessas de direitos aos negros para reconciliar-se com os afrikaners, institucionalizando a supremacia branca e o apartheid.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capítulo 6 (pp.&nbsp;120–57)</td>
<td style="text-align: left;">“To Bind Up the Nation’s Wounds”: The United States after the Civil War</td>
<td style="text-align: left;">Estudo de caso (EUA)</td>
<td style="text-align: left;">Aplica a tese central: conflito regional (Norte vs.&nbsp;Sul) sobre a escravidão leva à Guerra Civil. A vitória do Norte abre espaço para a Reconstrução, mas o medo de reabrir o conflito leva ao Compromisso de 1877 e à institucionalização local de Jim Crow, unindo brancos de ambas as regiões contra os negros.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capítulo 7 (pp.&nbsp;158–77)</td>
<td style="text-align: left;">“Order and Progress”: Inclusive Nation-State Building in Brazil</td>
<td style="text-align: left;">Estudo de caso (Brasil)</td>
<td style="text-align: left;">Aplica a tese central: ausência de conflito intra-branco comparável (unidade colonial portuguesa, transição pacífica do império à república) elimina a pressão para codificar a dominação racial. Em vez disso, o estado promove a ideologia da “democracia racial” como elemento unificador nacional, mantendo discriminação informal.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capítulo 8 (pp.&nbsp;194–216)</td>
<td style="text-align: left;">“We Are a Rock”: Black Racial Identity, Mobilization, and the New South Africa</td>
<td style="text-align: left;">Análise empírica (protesto)</td>
<td style="text-align: left;">Mostra como a dominação racial consolidou a identidade e o protesto negro na África do Sul, desde o ANC até o Black Consciousness, e como esse protesto forçou o regime a negociar o fim do apartheid.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capítulo 9 (pp.&nbsp;217–49)</td>
<td style="text-align: left;">Burying Jim Crow: Black Racial Identity, Mobilization, and Reform in the United States</td>
<td style="text-align: left;">Análise empírica (protesto)</td>
<td style="text-align: left;">Mostra como a segregação de Jim Crow, ao unificar brancos, também consolidou a identidade negra, levando ao movimento dos direitos civis. O protesto forçou a intervenção federal e o fim da segregação legal.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capítulo 10 (pp.&nbsp;250–63)</td>
<td style="text-align: left;">Breaching Brazil’s Pact of Silence</td>
<td style="text-align: left;">Análise empírica (protesto)</td>
<td style="text-align: left;">Mostra que, na ausência de dominação racial legal, a identidade negra e o protesto foram mais fracos e fragmentados. O movimento negro brasileiro enfrentou o mito da democracia racial, com mobilização limitada.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capítulo 11 (pp.&nbsp;267–78)</td>
<td style="text-align: left;">Conclusion</td>
<td style="text-align: left;">Síntese e extensão</td>
<td style="text-align: left;">Reafirma a tese central, discute a “brasilianização” das relações raciais pós-Jim Crow e pós-apartheid, e sugere generalizações para outros casos de exclusão étnica/classista na construção de estados-nação.</td>
</tr>
</tbody>
</table>
</section>
<section id="capítulo-1-introduction-pp.-125" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="capítulo-1-introduction-pp.-125"><span class="header-section-number">1</span> Capítulo 1: Introduction (pp.&nbsp;1–25)</h2>
<section id="o-problema-do-color-line-e-o-papel-do-estado-15" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="o-problema-do-color-line-e-o-papel-do-estado-15"><span class="header-section-number">1.1</span> O problema do color line e o papel do estado [§1–§5]</h3>
<blockquote class="blockquote">
<p>O livro abre com a afirmação de Du Bois de que “o problema da linha de cor” foi a questão pivotal do século XX. Marx argumenta que a industrialização, o conflito de classes, o nacionalismo e a consolidação estatal não fizeram a raça desaparecer, mas, ao contrário, <strong>acentuaram a contenção racial</strong> (p.&nbsp;1).</p>
</blockquote>
<p><strong>Nota 1:</strong> Marx critica explicações “funcionalistas” que reduzem a dominação racial a interesses econômicos imediatos do capital ou do trabalho branco. Ele propõe uma explicação centrada no estado: “States made race: amid pervasive discrimination, official actions enforced racial distinctions or did not, with profound consequences” (p.&nbsp;2).</p>
<p>Marx identifica três legados históricos comuns (discriminação, escravidão, colonialismo) que, no entanto, produziram resultados divergentes. O puzzle central é explicar por que a África do Sul e os EUA codificaram a dominação racial (apartheid e Jim Crow, respectivamente), enquanto o Brasil não o fez, adotando a ideologia da “democracia racial”.</p>
<p>O autor apresenta sua tese de forma condensada: elites políticas e econômicas, diante de <strong>conflitos intra-brancos</strong> (étnicos na África do Sul, regionais nos EUA), usaram o estado para impor a exclusão racial como estratégia de unificação branca. “To bind up the nation’s wounds among whites, blacks were bound down” (p.&nbsp;2). No Brasil, a ausência de conflitos comparáveis eliminou essa pressão.</p>
</section>
<section id="contra-explicações-alternativas-610" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="contra-explicações-alternativas-610"><span class="header-section-number">1.2</span> Contra explicações alternativas [§6–§10]</h3>
<p>Marx examina e refuta três explicações concorrentes para o “excepcionalismo” brasileiro:</p>
<ol type="1">
<li><strong>Demografia</strong>: a maioria negra na África do Sul, minoria nos EUA e situação mista no Brasil não se alinha com os resultados (a minoria nos EUA sofreu Jim Crow, a maioria na África do Sul sofreu apartheid, o caso intermediário — Brasil — não codificou a dominação).</li>
<li><strong>Herança da escravidão</strong>: contra Tannenbaum, Marx argumenta que a escravidão brasileira não foi mais “humanitária” e, se o fosse, a África do Sul (com escravidão limitada e abolição precoce) deveria ter sido a mais tolerante, o que não ocorreu.</li>
<li><strong>Miscigenação</strong>: embora alta no Brasil, a existência de uma população mista não impediu a categorização bipolar nos EUA e na África do Sul; o que importa é como a miscigenação é <strong>interpretada</strong> e usada ideologicamente.</li>
</ol>
<p><strong>Nota 2:</strong> A refutação dessas explicações é crucial para abrir espaço para a variável “conflito intra-branco”. Marx não nega que esses fatores importem, mas argumenta que eles são mediados por escolhas políticas e institucionais.</p>
</section>
<section id="a-teoria-da-construção-da-dominação-racial-1116" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="a-teoria-da-construção-da-dominação-racial-1116"><span class="header-section-number">1.3</span> A teoria da construção da dominação racial [§11–§16]</h3>
<blockquote class="blockquote">
<p>“The overriding interest in order and security required building a unifying racial order, to which ideals of equality, freedom, and justice were subordinated” (p.&nbsp;11).</p>
</blockquote>
<p>Marx desenvolve a explicação causal em três etapas:</p>
<ol type="1">
<li><strong>Conflito intra-branco</strong> (étnico/regional) em momentos críticos (pós-Guerra Civil nos EUA, pós-Guerra dos Bôeres na África do Sul) ameaça a consolidação do estado-nação.</li>
<li>Elites vitoriosas (Norte nos EUA, britânicos na África do Sul) decidem <strong>apaziguar os brancos derrotados</strong> (Sul, afrikaners) em vez de se aliar aos negros, porque os primeiros representam uma ameaça contínua de violência.</li>
<li>A <strong>dominação racial legal</strong> (segregação, desenfranchisement) é institucionalizada, unificando os brancos em torno da supremacia racial e permitindo o desenvolvimento econômico.</li>
</ol>
<p>No Brasil, a transição pacífica do império à república e a ausência de um fragmento europeu rival eliminaram a necessidade desse pacto racial explícito. Em vez disso, o estado promoveu a ideologia da <strong>democracia racial</strong> como cimento nacional.</p>
</section>
<section id="dinâmica-do-protesto-negro-e-feedback-loops-1723" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="dinâmica-do-protesto-negro-e-feedback-loops-1723"><span class="header-section-number">1.4</span> Dinâmica do protesto negro e feedback loops [§17–§23]</h3>
<p>Marx inverte a perspectiva na Parte III do livro: a dominação racial, ao criar categorias legais excludentes, tem o efeito não intencional de <strong>consolidar a identidade racial dos subordinados</strong>. “Racial domination had the unintended consequence of consolidating and legitimating subordinated racial identity into a potential basis for resistance” (p.&nbsp;20).</p>
<p>O protesto negro, por sua vez, força mudanças no estado. Na África do Sul e nos EUA, a crescente mobilização negra acabou se tornando uma ameaça maior do que o conflito intra-branco original, levando elites a abandonarem a dominação legal para preservar a estabilidade. No Brasil, a ausência de um alvo legal claro fragmentou o protesto.</p>
<p><strong>Nota 3:</strong> Essa parte da teoria é uma contribuição importante para a literatura de movimentos sociais, mostrando que a identidade não é pré-política, mas moldada pelo estado. Marx dialoga com Tarrow e McAdam, mas insiste na prioridade da formação da identidade via políticas estatais.</p>
</section>
<section id="implicações-teóricas-e-estrutura-do-livro-2425" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="implicações-teóricas-e-estrutura-do-livro-2425"><span class="header-section-number">1.5</span> Implicações teóricas e estrutura do livro [§24–§25]</h3>
<p>Na conclusão da introdução, Marx explicita a aposta mais ampla: a construção de nações frequentemente se dá pela <strong>exclusão interna</strong> (racial, étnica, de classe), e não pela inclusão cívica. O livro está estruturado em três partes:</p>
<ul>
<li><strong>Parte I</strong> (caps. 2-4): Legados históricos e culturais (colonialismo, escravidão, miscigenação) – mostrando que eles não são determinantes.</li>
<li><strong>Parte II</strong> (caps. 5-7): Dominação racial e estado-nação – os estudos de caso da África do Sul, EUA e Brasil.</li>
<li><strong>Parte III</strong> (caps. 8-10): “Race making from below” – protesto e identidade negra.</li>
<li><strong>Conclusão</strong> (cap. 11): Síntese e generalização.</li>
</ul>
</section>
</section>
<section id="capítulo-2-trajectories-from-colonialism-pp.-2946" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="capítulo-2-trajectories-from-colonialism-pp.-2946"><span class="header-section-number">2</span> Capítulo 2: Trajectories from Colonialism (pp.&nbsp;29–46)</h2>
<section id="a-tese-da-tolerância-racial-portuguesa-e-sua-crítica-15" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="a-tese-da-tolerância-racial-portuguesa-e-sua-crítica-15"><span class="header-section-number">2.1</span> A tese da tolerância racial portuguesa e sua crítica [§1–§5]</h3>
<p>O capítulo inicia com a análise da alegação de que o colonialismo português teria legado ao Brasil uma tradição de tolerância racial, argumento associado a Freyre e Du Bois. Marx demonstra que essa imagem é uma <strong>construção ideológica posterior</strong>, não um fato histórico. Cita Boxer: “the oft-made claim that the Portuguese had no colour-bar cannot be substantiated” (p.&nbsp;34).</p>
<p>A suposta tolerância teria origem no contato com os mouros, mas Marx aponta que a longa guerra contra os mouros gerou antagonismo, não tolerância. Além disso, o colonialismo português na África foi extremamente brutal e discriminatório.</p>
</section>
<section id="a-colonização-portuguesa-no-brasil-615" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="a-colonização-portuguesa-no-brasil-615"><span class="header-section-number">2.2</span> A colonização portuguesa no Brasil [§6–§15]</h3>
<p>A colonização do Brasil foi marcada por:</p>
<ul>
<li><strong>Estado centralizado forte</strong>, com a coroa portuguesa controlando diretamente a economia (o “rei’s plantation”).</li>
<li><strong>Ausência de um fragmento europeu rival</strong> – os holandeses foram expulsos no século XVII, sem deixar uma população significativa.</li>
<li><strong>Transição política sem ruptura violenta</strong>: a fuga da corte portuguesa para o Rio de Janeiro em 1807-1808 e a subsequente independência declarada por Pedro I mantiveram a continuidade institucional.</li>
</ul>
<blockquote class="blockquote">
<p>“There was no Brazilian civil war” (p.&nbsp;33).</p>
</blockquote>
<p>Essa unidade e estabilidade contrastam fortemente com os conflitos que marcaram a formação dos Estados Unidos e da África do Sul.</p>
<p><strong>Nota 4:</strong> Marx argumenta que a ausência de guerra civil ou de independência violenta é a variável crítica. O Brasil não precisou de um “outro” interno (racial) para unificar brancos porque os brancos já estavam unidos sob a coroa.</p>
</section>
<section id="colonialismo-holandês-e-britânico-na-áfrica-do-sul-1630" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="colonialismo-holandês-e-britânico-na-áfrica-do-sul-1630"><span class="header-section-number">2.3</span> Colonialismo holandês e britânico na África do Sul [§16–§30]</h3>
<p>Ao contrário do Brasil, a África do Sul foi palco de <strong>conflito entre dois fragmentos europeus</strong>: holandeses (afrikaners) e britânicos.</p>
<ul>
<li>Os afrikaners, isolados e calvinistas, desenvolveram uma ideologia de supremacia racial desde cedo, justificada religiosamente.</li>
<li>Os britânicos chegaram com uma retórica liberal (abolição da escravatura em 1833, direitos para “coloureds”), mas também praticaram segregação e conquista violenta.</li>
<li>A descoberta de diamantes e ouro (1867, 1886) exacerbou as tensões, levando à Guerra dos Bôeres (1899-1902).</li>
</ul>
<blockquote class="blockquote">
<p>“By the end of the nineteenth century, with imperial aims and mineral riches drawing British north from the Cape, the contest for control between the British and Afrikaners could no longer be finessed” (p.&nbsp;39).</p>
</blockquote>
</section>
<section id="colonialismo-britânico-na-américa-do-norte-3143" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="colonialismo-britânico-na-américa-do-norte-3143"><span class="header-section-number">2.4</span> Colonialismo britânico na América do Norte [§31–§43]</h3>
<p>Nos EUA, o conflito não foi entre fragmentos europeus, mas entre <strong>regiões</strong> (Norte industrial vs.&nbsp;Sul agrário-escravista). A escravidão foi usada desde cedo para unir brancos pobres e ricos no Sul (“the privilege of whipping someone else”).</p>
<ul>
<li>A independência foi conquistada pela guerra contra a Grã-Bretanha, mas a Constituição de 1787 deixou a questão da escravidão em aberto, estabelecendo um equilíbrio delicado entre poderes federais e estaduais.</li>
<li>O Norte também praticou discriminação, mas sem a instituição da escravidão.</li>
</ul>
<blockquote class="blockquote">
<p>“Tocqueville noted that racial prejudice was nowhere ‘more intolerant than in those states where slavery was never known’ or abolished” (p.&nbsp;42).</p>
</blockquote>
</section>
<section id="síntese-comparativa-4446" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="síntese-comparativa-4446"><span class="header-section-number">2.5</span> Síntese comparativa [§44–§46]</h3>
<p>O capítulo conclui que a <strong>herança mais significativa do colonialismo</strong> não foi um grau específico de tolerância racial, mas sim o <strong>grau de unidade e centralização estatal</strong>. O Brasil herdou um estado forte e unificado; a África do Sul e os EUA herdaram configurações fragmentadas e propensas a conflitos intra-brancos. Essa diferença estrutural é a base sobre a qual as elites mais tarde construiriam (ou não) ordens raciais legais.</p>
</section>
</section>
<section id="capítulo-3-lessons-from-slavery-pp.-4764" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="capítulo-3-lessons-from-slavery-pp.-4764"><span class="header-section-number">3</span> Capítulo 3: Lessons from Slavery (pp.&nbsp;47–64)</h2>
<section id="a-escravidão-na-áfrica-do-sul-e-o-problema-da-herança-direta-13" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="a-escravidão-na-áfrica-do-sul-e-o-problema-da-herança-direta-13"><span class="header-section-number">3.1</span> A escravidão na África do Sul e o problema da herança direta [§1–§3]</h3>
<p>Marx abre o capítulo observando que a África do Sul tem sido marginalizada nas comparações sobre escravidão, pois a escravidão foi mais limitada e abolida precocemente (1838). Os holandeses importaram escravos do leste asiático, e em 1821 os escravos compunham 35% da população da Cidade do Cabo. Apesar da brutalidade (escravos não podiam casar, fazer contratos ou possuir propriedades), a abolição foi imposta pela Grã-Bretanha — antes do fim do colonialismo.</p>
<blockquote class="blockquote">
<p>Se a escravidão “mais branda” determinasse a tolerância posterior, a África do Sul deveria ser o caso mais tolerante, o que não ocorreu. Portanto, a herança da escravidão não é direta ou linear (p.&nbsp;47-48).</p>
</blockquote>
<p><strong>Nota 5:</strong> Marx usa a África do Sul como um “teste negativo” das teses de Tannenbaum: abolição precoce e escravidão limitada não produziram democracia racial, mas apartheid. Isso reforça seu argumento de que as escolhas políticas pós-abolicionistas são mais importantes que o passado escravista em si.</p>
</section>
<section id="o-mito-da-escravidão-humanitária-brasileira-415" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="o-mito-da-escravidão-humanitária-brasileira-415"><span class="header-section-number">3.2</span> O mito da escravidão “humanitária” brasileira [§4–§15]</h3>
<p>O cerne do capítulo é a refutação sistemática da tese de Frank Tannenbaum (1946) de que a escravidão brasileira teria sido mais branda devido à influência católica e ao reconhecimento da “personalidade moral” do escravo.</p>
<p><strong>Evidências contrárias:</strong></p>
<ol type="1">
<li><strong>Mortalidade e reposição</strong>: os escravos no Brasil não se reproduziam; a população escrava só se mantinha via importação maciça (3,5 milhões de africanos trazidos ao todo). Em 1798, o Brasil tinha 1,5 milhão de escravos e 400 mil libertos. A alta mortalidade era devida à superexploração e doenças tropicais.</li>
<li><strong>Condições de vida</strong>: escravos eram chicoteados (leis contra açoites só em 1886), trancados à noite, e crianças às vezes eram enterradas até o pescoço durante o dia para que os pais pudessem trabalhar.</li>
<li><strong>Revoltas escravas</strong>: longe de serem dóceis, os escravos brasileiros se rebelaram frequentemente. O quilombo de Palmares (séc. XVII) chegou a ter 20 mil habitantes e forçou um tratado de paz com os portugueses. Na Bahia, houveram pelo menos oito revoltas entre 1807 e 1844, com a maior em 1835 (“perto de se tornar outro Haiti”).</li>
<li><strong>Igreja Católica</strong>: embora teoricamente defendesse a igualdade espiritual, a Igreja possuía escravos, condenava a miscigenação e só tardiamente pressionou por reformas.</li>
</ol>
<blockquote class="blockquote">
<p>“To call Brazilian slavery ‘humanitarian’ is absurd” (p.&nbsp;8, retomado no capítulo).</p>
</blockquote>
<p><strong>Nota 6:</strong> A taxa de manumissão (alforria) era maior no Brasil do que nos EUA, mas Marx argumenta que isso servia aos interesses dos senhores: libertar escravos após o pico de sua capacidade laboral, sendo pagos por eles, e então importar novos escravos mais vigorosos. A alforria era uma válvula de escape, não um sinal de tolerância.</p>
</section>
<section id="abolição-no-brasil-continuidade-e-consenso-1625" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="abolição-no-brasil-continuidade-e-consenso-1625"><span class="header-section-number">3.3</span> Abolição no Brasil: continuidade e consenso [§16–§25]</h3>
<p>Ao contrário dos EUA, a abolição no Brasil foi <strong>gradual e negociada</strong>, não resultado de guerra civil.</p>
<ul>
<li><strong>Leis graduais</strong>: Lei do Ventre Livre (1871) libertava filhos de escravos, mas com obrigação de trabalhar para o senhor até os 21 anos; Lei dos Sexagenários (1885) libertava escravos com mais de 60 anos.</li>
<li><strong>Pressões</strong>: a abolição do tráfico pela Marinha britânica (1850) cortou o suprimento de novos escravos; a Guerra do Paraguai (1865-70) libertou 20 mil escravos que serviram ao exército, que depois se recusou a caçar fugitivos.</li>
<li><strong>Abolição final (1888)</strong>: a “Lei Áurea” libertou os 600 mil escravos restantes, mas sem qualquer política de integração ou compensação. A princesa Isabel “emitiu uma lei que acabou com uma instituição que já estava morta”.</li>
</ul>
<blockquote class="blockquote">
<p>“Emancipation was thus an act of continuity rather than of revolution” (p.&nbsp;55).</p>
</blockquote>
<p>A elite brasileira preferiu “dar o anel para salvar o dedo” — abolir a escravidão para preservar a hierarquia social e evitar uma revolução.</p>
</section>
<section id="escravidão-e-abolição-nos-estados-unidos-2640" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="escravidão-e-abolição-nos-estados-unidos-2640"><span class="header-section-number">3.4</span> Escravidão e abolição nos Estados Unidos [§26–§40]</h3>
<p>A escravidão norte-americana foi brutal e regionalmente concentrada no Sul. Características:</p>
<ul>
<li><strong>Baixa manumissão</strong>: ao contrário do Brasil, a alforria foi praticamente fechada no início do século XIX; na Carolina do Sul, foi proibida em 1841.</li>
<li><strong>Reprodução natural</strong>: como o tráfico foi proibido mais cedo (1808), os senhores norte-americanos tinham incentivo para manter os escravos vivos e em reprodução, o que não os tornava mais “brandos”, mas sim mais dependentes do cativeiro hereditário.</li>
<li><strong>Revoltas menores</strong>: menos revoltas do que no Brasil, em parte porque a proporção de africanos recém-chegados (mais rebeldes) era menor e porque os escravos podiam fugir para o Norte (embora com dificuldade).</li>
</ul>
<p><strong>Nota 7:</strong> Marx cita a estimativa de que os EUA importaram cerca de 400 mil africanos, muito menos que o Brasil (3,5 milhões). Essa diferença demográfica é relevante, mas não determinante, pois ambos os países desenvolveram ordens pós-abolicionistas distintas.</p>
<p>O movimento abolicionista nos EUA foi muito mais forte e polarizador do que no Brasil. Garrison, a <em>Liberator</em>, <em>Uncle Tom’s Cabin</em> (300 mil cópias vendidas em 1852) e a American Colonization Society (que propunha o retorno de negros à África) alimentaram o conflito regional.</p>
</section>
<section id="o-desenvolvimento-da-ideologia-racista-nos-eua-4148" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="o-desenvolvimento-da-ideologia-racista-nos-eua-4148"><span class="header-section-number">3.5</span> O desenvolvimento da ideologia racista nos EUA [§41–§48]</h3>
<blockquote class="blockquote">
<p>“Prior to the 1830s … open assertions of permanent inferiority were exceedingly rare. It took the assault of the abolitionists … to force the practitioners of racial oppression to develop a theory that accorded with their behavior” (p.&nbsp;59).</p>
</blockquote>
<p>A ideologia racista explícita (Gobineau, Darwinismo social) emergiu como <strong>defesa da escravidão contra o abolicionismo</strong>. Após a emancipação, essa ideologia seria usada para justificar a segregação de Jim Crow.</p>
<p>O conflito regional sobre a escravidão tornou-se o eixo da política norte-americana, com o Sul defendendo os “direitos dos estados” e o Norte pressionando por poder federal para conter ou abolir a escravidão. A eleição de Lincoln em 1860 levou à secessão.</p>
</section>
<section id="síntese-comparativa-4955" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="síntese-comparativa-4955"><span class="header-section-number">3.6</span> Síntese comparativa [§49–§55]</h3>
<p>Marx conclui que a escravidão foi <strong>comparavelmente brutal</strong> no Brasil e nos EUA, mas com diferenças importantes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 23%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Brasil</th>
<th style="text-align: left;">Estados Unidos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Manumissão</td>
<td style="text-align: left;">Mais frequente (válvula de escape)</td>
<td style="text-align: left;">Rara, quase inexistente</td>
</tr>
<tr class="even">
<td style="text-align: left;">Reposição da mão de obra</td>
<td style="text-align: left;">Tráfico contínuo (alta mortalidade)</td>
<td style="text-align: left;">Reprodução natural</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Revoltas escravas</td>
<td style="text-align: left;">Mais frequentes e maiores</td>
<td style="text-align: left;">Menos frequentes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abolição</td>
<td style="text-align: left;">Gradual, consensual, sem guerra</td>
<td style="text-align: left;">Resultado da Guerra Civil</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Conflito regional sobre a escravidão</td>
<td style="text-align: left;">Ausente (escravidão nacional)</td>
<td style="text-align: left;">Central (Norte vs.&nbsp;Sul)</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>A diferença crucial não foi a “brandura” da escravidão, mas o <strong>enraizamento da questão escravista em um conflito regional</strong> nos EUA — e sua ausência no Brasil — que moldou a abolição e as ordens raciais posteriores (p.&nbsp;63-64).</p>
</blockquote>
<p>Na África do Sul, a abolição precoce (1833, imposta pela Grã-Bretanha) exacerbou o conflito étnico entre britânicos e afrikaners, que resistiam à “igualdade” com negros. Essa reação alimentou a ideologia racista afrikaner, que mais tarde fundamentaria o apartheid.</p>
<p><strong>Nota 8:</strong> A tabela acima é uma reconstrução da comparação de Marx, que aparece de forma dispersa no texto. Ele não a apresenta de forma tabular, mas a lógica comparativa é clara.</p>
</section>
</section>
<section id="capítulo-4-the-uncertain-legacy-of-miscegenation-pp.-6578" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="capítulo-4-the-uncertain-legacy-of-miscegenation-pp.-6578"><span class="header-section-number">4</span> Capítulo 4: The Uncertain Legacy of Miscegenation (pp.&nbsp;65–78)</h2>
<section id="miscigenação-no-brasil-do-fato-demográfico-ao-mito-da-mobilidade-112" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="miscigenação-no-brasil-do-fato-demográfico-ao-mito-da-mobilidade-112"><span class="header-section-number">4.1</span> Miscigenação no Brasil: do fato demográfico ao mito da mobilidade [§1–§12]</h3>
<p>O capítulo examina a tese de que a alta miscigenação no Brasil teria impedido a formação de uma ordem racial bipolar rígida, criando uma “válvula de escape” (Degler) para mulatos e tornando a segregação impraticável.</p>
<p><strong>Fatos demográficos:</strong></p>
<ul>
<li>Em 1818, o Brasil tinha 60% de negros e 10% de mulatos; em 1890, os mulatos subiram para 41% (24% no Sudeste, 48% no resto).</li>
<li>A proporção de mulheres portuguesas era baixa, e a coroa proibiu a migração de mulheres portuguesas em 1732 para não despovoar a metrópole. A necessidade sexual forçou a miscigenação.</li>
</ul>
<blockquote class="blockquote">
<p>“There was no ‘hypo-descent rule’ that might have otherwise forced a biracial categorization of mulatto offspring simply as black, no matter how small the proportion of their African ancestry” (p.&nbsp;66).</p>
</blockquote>
<p><strong>O mito do “escape hatch”:</strong></p>
<p>Carl Degler argumentou que a mobilidade de mulatos (alguns ascendendo a posições intermediárias) teria tornado a discriminação racial menos rígida. Marx demonstra que essa mobilidade é <strong>largamente um mito</strong>:</p>
<ul>
<li>Estudos estatísticos (Silva, Hasenbalg) mostram que a diferença de renda entre mulatos e negros é insignificante comparada à diferença entre brancos e não-brancos (a renda dos brancos era o dobro em 1960 e 1976).</li>
<li>Mulatos estavam presos em posições intermediárias, mas ainda discriminados (não podiam servir como oficiais da Guarda Nacional após 1850, por exemplo).</li>
<li>A “válvula de escape” funcionava mais como ideologia para encorajar a assimilação e desencorajar a solidariedade negra.</li>
</ul>
</section>
<section id="miscigenação-nos-estados-unidos-a-regra-da-one-drop-1320" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="miscigenação-nos-estados-unidos-a-regra-da-one-drop-1320"><span class="header-section-number">4.2</span> Miscigenação nos Estados Unidos: a regra da “one drop” [§13–§20]</h3>
<p>Nos EUA, a miscigenação ocorreu em menor escala (7,7% dos escravos eram mulatos em 1850, subindo para 12% em 1860). A reação branca foi <strong>proibir o casamento inter-racial</strong> (6 das 13 colônias já o haviam feito) e, após a abolição, <strong>impor a regra de “uma gota de sangue”</strong> (one-drop rule).</p>
<blockquote class="blockquote">
<p>“In 1896, the U.S. Supreme Court declared that even an ‘octoroon’ was subject to segregation within supposedly ‘separate but equal’ facilities” (p.&nbsp;70).</p>
</blockquote>
<p>A partir de 1910, o censo norte-americano deixou de registrar a categoria “mulato”. Qualquer pessoa com ascendência africana, por mínima que fosse, era legalmente negra. Isso <strong>forçou uma solidariedade bipolar</strong>: mulatos e negros compartilhavam o mesmo destino de segregação.</p>
<p><strong>Nota 9:</strong> Marx observa que entre 75% e 90% dos afro-americanos atuais têm alguma ascendência branca, mas a regra da “one drop” tornou essa mistura socialmente irrelevante para a categorização racial. Isso demonstra que a miscigenação biológica não determina as fronteiras raciais: a política as constrói.</p>
</section>
<section id="miscigenação-na-áfrica-do-sul-a-categoria-coloured-2133" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="miscigenação-na-áfrica-do-sul-a-categoria-coloured-2133"><span class="header-section-number">4.3</span> Miscigenação na África do Sul: a categoria “coloured” [§21–§33]</h3>
<p>Na África do Sul, a miscigenação também foi significativa nos primeiros anos da colônia holandesa: “three-quarters of the children born to the [Dutch East India] Company’s slaves had white fathers” (p.&nbsp;70).</p>
<p>Uma categoria <strong>coloured</strong> distinta desenvolveu-se, com um estatuto intermediário:</p>
<ul>
<li>Sob os britânicos, alguns coloureds podiam votar (no Cabo), mas foram banidos das escolas públicas em 1861.</li>
<li>Após a União (1910), o governo procurou cooptar os coloureds, dando-lhes quatro representantes brancos no Senado e algumas preferências trabalhistas.</li>
<li>No entanto, a lógica do apartheid acabou <strong>aproximando coloureds e africanos</strong>: a renda per capita dos coloureds era muito mais próxima da dos negros do que da dos brancos. Nos anos 1970, o movimento Black Consciousness redefiniu “negro” para incluir coloureds e asiáticos.</li>
<li>Em 1994, no entanto, muitos coloureds do Cabo Ocidental votaram no Partido Nacional, temendo a perda de seus privilégios relativos sob o domínio da maioria negra.</li>
</ul>
</section>
<section id="conclusão-miscigenação-como-categoria-política-não-biológica-3442" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="conclusão-miscigenação-como-categoria-política-não-biológica-3442"><span class="header-section-number">4.4</span> Conclusão: miscigenação como categoria política, não biológica [§34–§42]</h3>
<p>Marx conclui que a miscigenação em si não determina a rigidez ou fluidez das fronteiras raciais. O que importa é a <strong>interpretação política e legal</strong> da mistura.</p>
<ul>
<li>Nos EUA, a “one-drop rule” foi uma escolha política para <strong>forçar a bipolaridade</strong>, apesar da mistura real.</li>
<li>Na África do Sul, a categoria “coloured” foi mantida como estratégia de <strong>dividir para governar</strong>, mas acabou sendo corroída pela lógica do apartheid.</li>
<li>No Brasil, a alta miscigenação foi <strong>celebrada como mito de mobilidade e democracia racial</strong>, servindo para desmobilizar a identidade negra.</li>
</ul>
<blockquote class="blockquote">
<p>“Racists believe that physical distinctions are fixed, but racial orders are fluid and contingent. Biology itself draws no strict boundaries of racial categories, nor can it account for historical variations in how such boundaries were used” (p.&nbsp;75).</p>
</blockquote>
<p><strong>Nota 10:</strong> Esta é uma das passagens mais teóricas do livro e dialoga diretamente com a literatura construtivista sobre raça (Omi &amp; Winant, Fields). Marx, no entanto, vai além ao <strong>ancorar a construção da raça nas estratégias do estado</strong>, não apenas na cultura ou no discurso.</p>
</section>
</section>
<section id="capítulo-5-we-for-thee-south-africa-the-racial-state-pp.-84119" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="capítulo-5-we-for-thee-south-africa-the-racial-state-pp.-84119"><span class="header-section-number">5</span> Capítulo 5: “We for Thee, South Africa”: The Racial State (pp.&nbsp;84–119)</h2>
<section id="conflito-branco-e-unificação-forçada-pós-guerra-dos-bôeres-125" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="conflito-branco-e-unificação-forçada-pós-guerra-dos-bôeres-125"><span class="header-section-number">5.1</span> Conflito branco e unificação forçada pós-Guerra dos Bôeres [§1–§25]</h3>
<p>O capítulo começa descrevendo o contexto da África do Sul no final do século XIX: dois fragmentos europeus — britânicos e afrikaners — em conflito crescente, exacerbado pela descoberta de diamantes (1867) e ouro (1886). A Guerra dos Bôeres (1899-1902) foi o ponto culminante.</p>
<p><strong>A guerra e suas consequências:</strong></p>
<ul>
<li>A Grã-Bretanha, esperando uma vitória rápida, enfrentou uma resistência feroz dos afrikaners em guerrilha.</li>
<li>Custos: 448 mil soldados britânicos vs.&nbsp;70 mil afrikaners; 28 mil mulheres e crianças afrikaners morreram em campos de concentração britânicos.</li>
<li>O Tratado de Vereeniging (1902) foi um <strong>compromisso</strong>: os britânicos não impuseram punições severas, permitiram o uso do africâner nas escolas e <strong>abandonaram a promessa de conceder o voto aos negros</strong> (a cláusula original foi riscada à mão pelos generais bôeres Smuts e Hertzog).</li>
</ul>
<blockquote class="blockquote">
<p>“The British authorities accepted this revision, with no noted objection. British rhetoric that they had waged war on behalf of the coloureds and Africans was revealed as pretense” (p.&nbsp;88-89).</p>
</blockquote>
<p><strong>A lógica estratégica:</strong></p>
<p>Lord Milner, alto comissário britânico, já havia previsto o dilema: “You might indeed unite Dutch and English by protecting the black man, but you would unite them against yourself … There is the whole crux of the South African position” (p.&nbsp;92). A solução foi <strong>unir os brancos contra os negros</strong>.</p>
<p><strong>Nota 11:</strong> Marx destaca que os britânicos não se aliaram aos negros (que eram maioria) para isolar os afrikaners, porque os afrikaners haviam demonstrado capacidade de resistência violenta. Os negros, divididos por etnia e desarmados, não representavam uma ameaça comparável. Essa avaliação estratégica — baseada em percepção de ameaça, não em moral — é o núcleo da explicação.</p>
</section>
<section id="competição-política-étnica-e-o-aprofundamento-da-segregação-1910-1948-2655" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="competição-política-étnica-e-o-aprofundamento-da-segregação-1910-1948-2655"><span class="header-section-number">5.2</span> Competição política étnica e o aprofundamento da segregação (1910-1948) [§26–§55]</h3>
<p>Após a União (1910), o conflito entre britânicos e afrikaners não desapareceu, mas passou para o campo político. Dois partidos se alternaram no poder:</p>
<ul>
<li><strong>South African Party (SAP)</strong>, liderado por Botha e Smuts (afrikaners moderados, pró-britânicos), defendia a “unidade branca” via segregação.</li>
<li><strong>National Party (NP)</strong>, liderado por Hertzog (afrikaner nacionalista), defendia o “dois fluxos” — cooperação entre brancos, mas com preservação da cultura afrikaner.</li>
</ul>
<p><strong>A corrida pelo extremo na segregação:</strong></p>
<p>Ambos os partidos usaram a <strong>dominação racial como trunfo eleitoral</strong>. Hertzog, no poder após 1924, reforçou a <em>colour bar</em> na indústria, baniu a sindicalização negra e aprovou a Native Land Act (1913, 1936), que reservava para os negros apenas 13% da terra, forçando-os ao trabalho assalariado barato.</p>
<blockquote class="blockquote">
<p>“The industrial color bar reserving certain jobs for whites, which Smuts had attempted to relax at his electoral peril, was reinforced in 1926” (p.&nbsp;100).</p>
</blockquote>
<p><strong>Nota 12:</strong> A competição partidária entre brancos, longe de ameaçar o sistema, o <strong>estabilizou</strong>, porque ambos os partidos concordavam com a premissa da supremacia branca. A divergência era sobre <em>quão</em> segregacionista ser, não sobre se segregar.</p>
</section>
<section id="apartheid-e-a-unidade-branca-sob-o-national-party-1948-1966-5685" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="apartheid-e-a-unidade-branca-sob-o-national-party-1948-1966-5685"><span class="header-section-number">5.3</span> Apartheid e a unidade branca sob o National Party (1948-1966) [§56–§85]</h3>
<p>A vitória do National Party em 1948, sob D.F. Malan, levou o apartheid ao extremo.</p>
<p><strong>Medidas centrais:</strong></p>
<ul>
<li><em>Population Registration Act</em> (1950): categorização racial oficial (branco, coloured, asiático, nativo).</li>
<li><em>Group Areas Act</em> (1950): segregação residencial compulsória.</li>
<li><em>Bantu Education Act</em> (1953): educação separada e inferior para negros.</li>
<li><em>Reservation of Separate Amenities Act</em> (1953): segregação de espaços públicos.</li>
<li>Revogação da representação política dos coloureds (1956).</li>
</ul>
<p><strong>A unificação dos brancos:</strong></p>
<p>Hendrik Verwoerd (primeiro-ministro 1958-66) levou a lógica ao extremo: criou os <strong>bantustões</strong> (homelands) para “autogoverno” negro, removendo a cidadania sul-africana dos africanos. Ao mesmo tempo, declarou a república (1961) e tentou incorporar os brancos de língua inglesa em um <em>white republicanism</em>, diluindo o nacionalismo afrikaner puro.</p>
<blockquote class="blockquote">
<p>“Verwoerd shifted his rhetoric from Afrikaner nationalism to ‘white republicanism’” (p.&nbsp;107).</p>
</blockquote>
<p><strong>Benefícios econômicos para os brancos:</strong></p>
<ul>
<li>O estado cresceu enormemente para administrar o apartheid (43% da força de trabalho branca estava no setor público em 1972).</li>
<li>O salário médio dos brancos era 7 vezes maior que o dos negros (1972).</li>
<li>Os afrikaners, inicialmente mais pobres, alcançaram paridade econômica com os brancos de língua inglesa nos anos 1970.</li>
</ul>
<blockquote class="blockquote">
<p>“Apartheid profited the Boers while consolidating white privilege more generally” (p.&nbsp;118).</p>
</blockquote>
<p><strong>Nota 13:</strong> Marx argumenta que o apartheid foi funcional para unificar os brancos, mas teve um custo não intencional: consolidou a identidade e o protesto negros. Nas palavras de Biko: “racial domination was ‘not a mistake on the part of whites but a deliberate act’” (p.&nbsp;118-119).</p>
</section>
<section id="a-crise-e-o-desmantelamento-gradual-1970s-1990s-86104" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="a-crise-e-o-desmantelamento-gradual-1970s-1990s-86104"><span class="header-section-number">5.4</span> A crise e o desmantelamento gradual (1970s-1990s) [§86–§104]</h3>
<p>A partir dos anos 1970, o apartheid começou a ruir:</p>
<ul>
<li><strong>Pressão interna</strong>: revoltas do Soweto (1976), crescente mobilização do ANC e da UDF, sindicatos negros (cerca de 2 milhões de filiados em 1985).</li>
<li><strong>Divisões entre brancos</strong>: o Partido Nacional se dividiu entre <em>verligtes</em> (reformistas) e <em>verkramptes</em> (conservadores). P.W. Botha tentou “adaptar ou morrer” (<em>adapt or die</em>), implementando reformas limitadas (fim das leis de passe em 1986, sindicalização negra, parlamento tricameral incluindo coloureds e asiáticos, mas não africanos).</li>
<li><strong>Pressão internacional</strong>: sanções econômicas, fim da Guerra Fria, desinvestimento.</li>
</ul>
<p>F.W. de Klerk, em 1990, libertou Nelson Mandela e iniciou negociações que levaram às eleições de 1994.</p>
<p>Marx conclui que o apartheid cumpriu seu papel estratégico de unificar os brancos, mas, ao fazê-lo, criou um <strong>inimigo negro unificado</strong> que acabou se tornando uma ameaça maior do que o conflito intra-branco original.</p>
</section>
</section>
<section id="capítulo-6-to-bind-up-the-nations-wounds-the-united-states-after-the-civil-war-pp.-12057" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="capítulo-6-to-bind-up-the-nations-wounds-the-united-states-after-the-civil-war-pp.-12057"><span class="header-section-number">6</span> Capítulo 6: “To Bind Up the Nation’s Wounds”: The United States after the Civil War (pp.&nbsp;120–57)</h2>
<section id="a-nação-dividida-guerra-civil-e-o-fortalecimento-do-estado-federal-118" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="a-nação-dividida-guerra-civil-e-o-fortalecimento-do-estado-federal-118"><span class="header-section-number">6.1</span> A nação dividida: Guerra Civil e o fortalecimento do estado federal [§1–§18]</h3>
<p>O capítulo inicia descrevendo a crescente tensão regional entre Norte industrial e Sul agrário-escravista. A escravidão não era o único fator, mas o <strong>ponto de inflexão</strong> para questões mais amplas de poder federal vs.&nbsp;direitos dos estados.</p>
<ul>
<li>O Sul usava os “direitos dos estados” para proteger a escravidão.</li>
<li>O Norte, com sua economia industrial emergente, queria tarifas, um sistema bancário nacional e investimento federal em infraestrutura — tudo isso ameaçava a autonomia sulista.</li>
</ul>
<blockquote class="blockquote">
<p>“The Civil War was determined by such multiple and reinforcing pressures emerging from regional competition” (p.&nbsp;122).</p>
</blockquote>
<p><strong>A Proclamação de Emancipação (1863)</strong> foi uma medida de guerra, não um ato de princípio. Lincoln a emitiu para enfraquecer o Sul e encorajar negros a se juntarem ao exército da União.</p>
<p><strong>Resultados da guerra:</strong></p>
<ul>
<li>623 mil soldados mortos (mais do que em todas as outras guerras dos EUA juntas).</li>
<li>O governo federal expandiu-se enormemente: o orçamento federal passou de $63 milhões (1860) para $1 bilhão (1865); o número de funcionários federais saltou de 53 mil para 256 mil entre 1871 e 1901.</li>
<li>A Décima Quarta e Décima Quinta Emendas foram ratificadas, garantindo direitos iguais e sufrágio aos negros (formalmente).</li>
</ul>
<p><strong>Nota 14:</strong> Marx enfatiza que a guerra <strong>criou um estado central mais forte</strong>, mas não uma lealdade nacional unificada. O Sul permaneceu ressentido e os brancos do Norte estavam cansados do conflito.</p>
</section>
<section id="reconstrução-e-abandono-da-promessa-aos-negros-1944" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="reconstrução-e-abandono-da-promessa-aos-negros-1944"><span class="header-section-number">6.2</span> Reconstrução e abandono da promessa aos negros [§19–§44]</h3>
<p>A Reconstrução (1865-1877) foi uma tentativa de impor reformas raciais no Sul, mas falhou.</p>
<p><strong>Andrew Johnson (presidente, 1865-69)</strong> tentou apaziguar o Sul rapidamente, anulando a distribuição de terras (“40 acres and a mule”) e vetando a extensão do Freedmen’s Bureau. Os estados sulistas responderam com <strong>códigos negros</strong> (black codes) que recriavam a subordinação.</p>
<p><strong>Congressional Reconstruction (1867-77):</strong> O Congresso (controlado pelos republicanos radicais) reagiu impondo o sufrágio negro, a ocupação militar e a Décima Quarta Emenda. Negros foram eleitos para legislaturas estaduais e para o Congresso.</p>
<p><strong>A contraofensiva branca e o Compromisso de 1877:</strong></p>
<ul>
<li>O Sul resistiu com violência (Ku Klux Klan, mais de 2 mil linchamentos nas décadas finais do século).</li>
<li>O Pânico de 1873 e a depressão econômica tornaram o Norte menos disposto a financiar a Reconstrução.</li>
<li>No <strong>Compromisso de 1877</strong>, os republicanos (Hayes) concordaram em retirar as tropas federais do Sul em troca da posse na presidência. O Sul foi “redimido” (<em>redeemed</em>).</li>
</ul>
<blockquote class="blockquote">
<p>“To bind up the nation’s wounds among whites, blacks were bound down” (p.&nbsp;2, retomado aqui).</p>
</blockquote>
<p><strong>Nota 15:</strong> Marx compara explicitamente o Compromisso de 1877 com o Tratado de Vereeniging (1902) na África do Sul. Em ambos os casos, a potência vitoriosa (Norte, Grã-Bretanha) abandonou os negros para reconciliar-se com os brancos derrotados (Sul, afrikaners).</p>
</section>
<section id="jim-crow-competição-partidária-e-consolidação-nacional-4575" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="jim-crow-competição-partidária-e-consolidação-nacional-4575"><span class="header-section-number">6.3</span> Jim Crow, competição partidária e consolidação nacional [§45–§75]</h3>
<p>Após 1877, a segregação de Jim Crow foi institucionalizada no Sul, enquanto o Norte praticava discriminação informal.</p>
<p><strong>Desenfranchisement:</strong> Convenções constitucionais estaduais no Sul (Mississippi 1890, Louisiana 1898) impuseram impostos de votação (<em>poll taxes</em>), testes de alfabetização e cláusulas de avô, reduzindo a participação eleitoral negra de 60% para zero em alguns estados.</p>
<blockquote class="blockquote">
<p>“Sixty-four percent of adult males voted in the South in the 1880s, but after 1900 participation had fallen to 30 percent” (p.&nbsp;138).</p>
</blockquote>
<p><strong>O “Solid South” e o Partido Democrata:</strong></p>
<p>O Partido Democrata tornou-se o partido da supremacia branca no Sul, excluindo não apenas negros, mas também brancos pobres que haviam apoiado o Populismo. Um político da Louisiana declarou: “What is the state? It is the Democratic Party … We met here to establish the supremacy of the white race” (p.&nbsp;138).</p>
<p><strong>A apaziguação do Sul e o crescimento do poder federal:</strong></p>
<p>Embora o governo federal tivesse abandonado a imposição de direitos civis, ele <strong>cresceu em outros aspectos</strong> (regulação econômica, New Deal). Esse crescimento criou as condições para uma futura intervenção federal — o que ocorreu nos anos 1950-60.</p>
<blockquote class="blockquote">
<p>“Increased federal power was not applied immediately to race reform, but did create the potential for such reform at a later date” (p.&nbsp;146).</p>
</blockquote>
</section>
<section id="o-movimento-dos-direitos-civis-e-o-fim-de-jim-crow-76104" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="o-movimento-dos-direitos-civis-e-o-fim-de-jim-crow-76104"><span class="header-section-number">6.4</span> O movimento dos direitos civis e o fim de Jim Crow [§76–§104]</h3>
<p>Marx descreve como a <strong>consolidação da identidade negra</strong> no Sul, sob o peso de Jim Crow, levou ao movimento dos direitos civis.</p>
<p><strong>Brown v. Board of Education (1954):</strong> “for the first time since Reconstruction they felt the federal government was actually on their side” (p.&nbsp;148). A decisão rejeitou a doutrina “separados, mas iguais” e declarou a segregação inconstitucional.</p>
<p><strong>Protestos e intervenção federal:</strong></p>
<ul>
<li>Boicote aos ônibus de Montgomery (1955-56), liderado por MLK.</li>
<li>Sit-ins (Greensboro 1960), Freedom Rides (1961).</li>
<li>Marcha em Selma (1965), que levou ao Voting Rights Act.</li>
</ul>
<p>John F. Kennedy e Lyndon B. Johnson, pressionados pelo movimento, usaram o poder federal para impor a dessegregação, apesar da resistência sulista. Johnson declarou em 1965: “nothing is of greater significance to the welfare and vitality of this nation than the movement to secure equal rights for Negro Americans” (p.&nbsp;151).</p>
<p><strong>O realinhamento partidário:</strong></p>
<p>Os democratas perderam o Sul “sólido” para os republicanos (Goldwater em 1964, Nixon em 1968), mas os negros tornaram-se eleitores democratas leais.</p>
</section>
<section id="a-brasilianização-das-relações-raciais-pós-jim-crow-105115" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="a-brasilianização-das-relações-raciais-pós-jim-crow-105115"><span class="header-section-number">6.5</span> A “brasilianização” das relações raciais pós-Jim Crow [§105–§115]</h3>
<p>Nos anos 1960-70, o movimento de direitos civis foi sucedido pelo <strong>Black Power</strong>, mais separatista e culturalista, especialmente no Norte, onde a discriminação era informal (de facto) e o governo federal relutava em intervir.</p>
<blockquote class="blockquote">
<p>“In the North, the enemy was diffuse, scattered, and often concealed” (James Farmer, p.&nbsp;236).</p>
</blockquote>
<p>Os motins urbanos (Watts 1965, Detroit 1967, mais de 400 distúrbios entre 1964-69) foram, para Marx, uma expressão de frustração com a <strong>falta de intervenção federal no Norte</strong> e com a persistência da pobreza e discriminação.</p>
<p>O fim de Jim Crow não significou o fim da desigualdade racial. Marx argumenta que os EUA pós-1965 se aproximaram da situação brasileira: <strong>discriminação informal, ausência de segregação legal, mas persistência de desigualdade estrutural</strong>.</p>
</section>
</section>
<section id="capítulo-7-order-and-progress-inclusive-nation-state-building-in-brazil-pp.-15877" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="capítulo-7-order-and-progress-inclusive-nation-state-building-in-brazil-pp.-15877"><span class="header-section-number">7</span> Capítulo 7: “Order and Progress”: Inclusive Nation-State Building in Brazil (pp.&nbsp;158–77)</h2>
<section id="a-imagem-da-unidade-nacional-15" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="a-imagem-da-unidade-nacional-15"><span class="header-section-number">7.1</span> A imagem da unidade nacional [§1–§5]</h3>
<p>O capítulo abre com duas imagens emblemáticas: a coroação de Pedro I (1822) incluindo negros e mulatos na cena, e a festa de despedida do imperador Pedro II na Ilha das Cobras (1889), com elites brancas e mulatas. Essas imagens contrastam com a iconografia sul-africana ou norte-americana, que excluía negros da representação da nação.</p>
<blockquote class="blockquote">
<p>“Brazil’s foundation as an independent empire had not been the result of conflict, but of a peaceful transition that retained historical links to the colonial power of Portugal” (p.&nbsp;158).</p>
</blockquote>
<p><strong>Nota 16:</strong> Marx argumenta que essa <strong>ausência de conflito violento na fundação</strong> é a variável crucial. O Brasil não precisou de um “outro” racial interno para unificar brancos porque a unidade já existia.</p>
</section>
<section id="abolição-pacífica-e-federalismo-615" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="abolição-pacífica-e-federalismo-615"><span class="header-section-number">7.2</span> Abolição pacífica e federalismo [§6–§15]</h3>
<p>A abolição no Brasil foi <strong>nacional e gradual</strong>, não regional e violenta como nos EUA.</p>
<ul>
<li>“No region had less than 27 percent slave out of its total population” (p.&nbsp;160) — a escravidão era uniformemente distribuída.</li>
<li>A transição para a república (1889) foi igualmente pacífica; o imperador foi deposto, mas não exilado violentamente.</li>
</ul>
<p>Em vez de centralizar o estado como na África do Sul ou nos EUA, a república brasileira adotou o <strong>federalismo</strong> (inspirado nos EUA), descentralizando o poder. Essa descentralização foi possível porque a elite não temia que isso levasse ao conflito racial — a estabilidade já estava assegurada.</p>
</section>
<section id="a-política-de-branqueamento-whitening-e-a-democracia-racial-como-ideologia-1635" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="a-política-de-branqueamento-whitening-e-a-democracia-racial-como-ideologia-1635"><span class="header-section-number">7.3</span> A política de branqueamento (whitening) e a democracia racial como ideologia [§16–§35]</h3>
<p>Após a abolição, o estado brasileiro promoveu ativamente a <strong>imigração europeia</strong> (3,7 milhões entre 1870-1930) e baniu a imigração negra (1890, 1920s, 1930s). A ideia era “purificar a raça” e “injetar civilização” (p.&nbsp;162).</p>
<p><strong>A ideologia da democracia racial (Gilberto Freyre):</strong></p>
<ul>
<li>A miscigenação foi celebrada como um processo de <strong>branqueamento</strong> (os genes brancos supostamente mais fortes).</li>
<li>A história da escravidão foi reinterpretada como paternalista e tolerante.</li>
<li>A desigualdade racial foi atribuída à <strong>classe</strong>, não à raça.</li>
</ul>
<blockquote class="blockquote">
<p>“Freyre created the most formidable ideological weapon against blacks” (Carlos Hasenbalg, p.&nbsp;167).</p>
</blockquote>
<p><strong>Consequências da ausência de segregação legal:</strong></p>
<ul>
<li>Sem um alvo legal claro, a identidade negra permaneceu fragmentada.</li>
<li>A mobilização política negra foi fraca e frequentemente cooptada.</li>
<li>O estado brasileiro, mesmo sob a ditadura militar (1964-85), suprimiu estudos sobre racismo e omitiu categorias raciais do censo em 1970.</li>
</ul>
<p><strong>Nota 17:</strong> Marx cita a repressão à pesquisa sobre raça sob os militares: “The very concept of race was effectively banned as an enemy of national security” (p.&nbsp;172).</p>
</section>
<section id="vargas-e-o-estado-corporativista-3645" class="level3" data-number="7.4">
<h3 data-number="7.4" class="anchored" data-anchor-id="vargas-e-o-estado-corporativista-3645"><span class="header-section-number">7.4</span> Vargas e o estado corporativista [§36–§45]</h3>
<p>Getúlio Vargas (1930-45, 1951-54) centralizou o estado, mas <strong>não usou a exclusão racial</strong> para isso. Em vez disso, promoveu o <strong>corporativismo</strong>: sindicatos controlados pelo estado, políticas sociais universais (mas com aplicação discriminatória na prática), e a celebração da cultura afro-brasileira (carnaval, candomblé) como símbolo nacional.</p>
<blockquote class="blockquote">
<p>“Vargas engineered a massive expansion of the centralized state, comparable to that achieved earlier in South Africa and in the United States under the contemporaneous New Deal, but without resort to racial exclusion for white unity” (p.&nbsp;170).</p>
</blockquote>
</section>
<section id="a-persistência-da-desigualdade-sob-a-democracia-racial-4655" class="level3" data-number="7.5">
<h3 data-number="7.5" class="anchored" data-anchor-id="a-persistência-da-desigualdade-sob-a-democracia-racial-4655"><span class="header-section-number">7.5</span> A persistência da desigualdade sob a democracia racial [§46–§55]</h3>
<p>Apesar da ideologia da democracia racial, a desigualdade é brutal:</p>
<ul>
<li>Em 1960, a renda média dos brancos era o dobro da dos não-brancos.</li>
<li>Em 1980, a diferença permanecia semelhante.</li>
<li>A proporção de negros na educação superior é drasticamente menor.</li>
</ul>
<blockquote class="blockquote">
<p>“Brazil has no black middle class” (João Jorge Santos Rodrigues, p.&nbsp;172).</p>
</blockquote>
<p><strong>A redemocratização (anos 1980-90)</strong> permitiu a emergência de um movimento negro mais vocal (MNU, PDT de Abdias do Nascimento), mas ainda fraco em comparação com EUA ou África do Sul. A “democracia racial” continua sendo um obstáculo ideológico à mobilização.</p>
</section>
</section>
<section id="capítulo-8-we-are-a-rock-black-racial-identity-mobilization-and-the-new-south-africa-pp.-194216" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="capítulo-8-we-are-a-rock-black-racial-identity-mobilization-and-the-new-south-africa-pp.-194216"><span class="header-section-number">8</span> Capítulo 8: “We Are a Rock”: Black Racial Identity, Mobilization, and the New South Africa (pp.&nbsp;194–216)</h2>
<section id="consolidação-da-identidade-racial-e-protesto-inicial-120" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="consolidação-da-identidade-racial-e-protesto-inicial-120"><span class="header-section-number">8.1</span> Consolidação da identidade racial e protesto inicial [§1–§20]</h3>
<p>Antes da unificação sul-africana (1910), a resistência negra era <strong>étnica e localizada</strong> (Zulus, Xhosa), não racial. A formação do estado unificado e a imposição da segregação (Lei de Terras de 1913, Lei de Áreas Urbanas de 1923) forçaram uma <strong>identidade racial comum</strong>.</p>
<blockquote class="blockquote">
<p>“The African National Congress (ANC) was formed in 1909 … for the purpose of creating national unity and defending our rights and privileges as subordinated Africans rather than as distinct tribes” (p.&nbsp;196).</p>
</blockquote>
<p><strong>Fases do protesto:</strong></p>
<ol type="1">
<li><strong>1910-1940s:</strong> Petições leais à coroa britânica, lideradas por advogados e chefes tradicionais. O ANC era moderado e elitista.</li>
<li><strong>1940s-1950s:</strong> Liga da Juventude do ANC (1944), Programa de Ação (1949), Campanha de Desobediência (1952). O apartheid (1948) radicalizou o movimento.</li>
<li><strong>1955:</strong> Congresso do Povo, adoção da <strong>Freedom Charter</strong>, que pedia uma democracia não-racial.</li>
<li><strong>1960:</strong> Massacre de Sharpeville → ANC e PAC banidos → luta armada (<em>Umkhonto we Sizwe</em>).</li>
</ol>
<p><strong>Nota 18:</strong> Marx destaca a ambiguidade do ANC: defendia o <strong>não-racialismo</strong> (negação das categorias raciais como objetivo final), mas organizava-se <strong>racialmente</strong> na prática (aliança com coloureds e indianos via Congress Alliance). Essa tensão entre integração e afirmação racial persistiu.</p>
</section>
<section id="black-consciousness-e-o-protesto-dos-anos-1970-80-2140" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="black-consciousness-e-o-protesto-dos-anos-1970-80-2140"><span class="header-section-number">8.2</span> Black Consciousness e o protesto dos anos 1970-80 [§21–§40]</h3>
<p>A repressão aos anos 1960 não eliminou a resistência. Nos anos 1970, o <strong>Black Consciousness Movement</strong> (Steve Biko) rejeitou o não-racialismo do ANC, afirmando que “being black” (incluindo coloureds e asiáticos) era uma identidade política positiva.</p>
<blockquote class="blockquote">
<p>“What blacks are doing is merely to respond to a situation in which they find themselves the objects of white racism” (Biko, p.&nbsp;201).</p>
</blockquote>
<p><strong>Soweto (1976):</strong> estudantes protestam contra a imposição do africâner como língua de instrução; a repressão mata centenas e radicaliza uma nova geração.</p>
<p><strong>United Democratic Front (UDF, 1983):</strong> resposta ao parlamento tricameral de P.W. Botha (que incluía coloureds e asiáticos, mas não africanos). A UDF, embora não-racial, mobilizou milhões em boicotes, greves e desobediência civil.</p>
</section>
<section id="a-transição-negociada-4160" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="a-transição-negociada-4160"><span class="header-section-number">8.3</span> A transição negociada [§41–§60]</h3>
<p>A crise dos anos 1980 (greves, sanções, violência) levou o regime a negociar. F.W. de Klerk (1989-94) libertou Mandela e legalizou o ANC.</p>
<p><strong>Fatores explicativos da transição:</strong></p>
<ol type="1">
<li><strong>Esgotamento da opção repressiva:</strong> o estado não podia mais conter o protesto sem destruir a economia.</li>
<li><strong>Mudanças internacionais:</strong> fim da Guerra Fria removeu o medo do comunismo; sanções apertaram.</li>
<li><strong>Cálculo afrikaner:</strong> a elite afrikaner havia alcançado paridade econômica com os ingleses e não via mais vantagem no apartheid.</li>
</ol>
<blockquote class="blockquote">
<p>“De Klerk acted before he fully lost control of the situation” (Mandela, p.&nbsp;208).</p>
</blockquote>
<p><strong>Resultados:</strong> eleições de 1994, governo de unidade nacional (ANC + NP + Inkatha). Marx nota que a transição foi <strong>elite-driven</strong>, com o estado negociando com a oposição moderada, e que a <strong>continuidade econômica</strong> (compromisso de não nacionalizar) foi crucial para acalmar os brancos.</p>
<p><strong>Nota 19:</strong> Marx é cético sobre a “construção da nação” pós-apartheid. Os conflitos étnicos (Zulu vs.&nbsp;Xhosa) e raciais persistem, e a desigualdade econômica continua enorme. “A nação sul-africana ainda não existe; é um processo em andamento” (Beyers Naude, p.&nbsp;213-214).</p>
</section>
</section>
<section id="capítulo-9-burying-jim-crow-black-racial-identity-mobilization-and-reform-in-the-united-states-pp.-21749" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="capítulo-9-burying-jim-crow-black-racial-identity-mobilization-and-reform-in-the-united-states-pp.-21749"><span class="header-section-number">9</span> Capítulo 9: Burying Jim Crow: Black Racial Identity, Mobilization, and Reform in the United States (pp.&nbsp;217–49)</h2>
<section id="em-direção-à-solidariedade-racial-1877-1954-130" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="em-direção-à-solidariedade-racial-1877-1954-130"><span class="header-section-number">9.1</span> Em direção à solidariedade racial (1877-1954) [§1–§30]</h3>
<p>Após a Reconstrução, os afro-americanos se dividiram entre <strong>acomodação</strong> (Booker T. Washington) e <strong>protesto</strong> (W.E.B. Du Bois, NAACP). Garvey (anos 1920) mobilizou as massas urbanas em torno do <strong>nacionalismo negro</strong> e do retorno à África.</p>
<p><strong>A Grande Migração (1910-1970):</strong> 5 milhões de negros se mudam do Sul para o Norte, em busca de empregos industriais e fugindo de Jim Crow. Essa migração <strong>nacionalizou a questão racial</strong> e criou uma base eleitoral negra nos centros urbanos do Norte.</p>
<p><strong>New Deal (1930s):</strong> FDR incluiu negros em alguns programas, mas excluiu trabalhadores domésticos e agrícolas (predominantemente negros) da Segurança Social. O Partido Democrata tornou-se o lar político dos negros, mas o poder do “Solid South” bloqueava reformas civis.</p>
<p><strong>Segunda Guerra Mundial:</strong> a retórica antirracista dos Aliados e a experiência de negros servindo no exterior elevaram as expectativas. O Comitê de Práticas Justas de Emprego (1941) foi uma conquista modesta.</p>
</section>
<section id="o-movimento-dos-direitos-civis-3165" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="o-movimento-dos-direitos-civis-3165"><span class="header-section-number">9.2</span> O movimento dos direitos civis [§31–§65]</h3>
<p>Marx descreve o movimento dos direitos civis como o resultado da <strong>interação entre identidade consolidada, oportunidade política (federal) e ação direta</strong>.</p>
<p><strong>Brown v. Board (1954):</strong> o estímulo judicial inicial.</p>
<p><strong>Boicote de Montgomery (1955-56):</strong> Martin Luther King Jr.&nbsp;emerge como líder. A estratégia de King era <strong>provocar a repressão sulista para forçar a intervenção federal</strong> — e usar a mídia (TV) para ganhar simpatia nacional.</p>
<p><strong>Birmingham (1963):</strong> Bull Connor usa cães e mangueiras de incêndio contra manifestantes; as imagens chocam o país. Kennedy propõe a Lei dos Direitos Civis.</p>
<p><strong>Selma (1965):</strong> a violência da polícia leva ao Voting Rights Act, que finalmente garante o sufrágio negro no Sul.</p>
<blockquote class="blockquote">
<p>“The high-water mark of centralized state authority and power came together with the peak of protest demanding federal civil rights intervention in 1964 and 1965” (p.&nbsp;233).</p>
</blockquote>
</section>
<section id="a-virada-para-o-norte-e-o-black-power-6695" class="level3" data-number="9.3">
<h3 data-number="9.3" class="anchored" data-anchor-id="a-virada-para-o-norte-e-o-black-power-6695"><span class="header-section-number">9.3</span> A virada para o Norte e o Black Power [§66–§95]</h3>
<p>Após 1965, o movimento se desloca para o Norte, onde a segregação é <strong>de facto</strong> (moradia, emprego), não legal. A estratégia de provocar intervenção federal falha, porque não há leis segregacionistas a serem derrubadas.</p>
<p><strong>Motins urbanos (1964-69):</strong> mais de 400 distúrbios. Marx argumenta que os motins foram uma expressão de frustração com a <strong>falta de intervenção federal</strong> e com a persistência da pobreza.</p>
<p><strong>Black Power (Stokely Carmichael, Malcolm X, Panteras Negras):</strong></p>
<ul>
<li>Rejeição da não-violência.</li>
<li>Afirmação da identidade negra (“Black is beautiful”).</li>
<li>Separatismo e autossuficiência econômica.</li>
<li>Crítica ao “não-racialismo” liberal.</li>
</ul>
<blockquote class="blockquote">
<p>“Black Power emerged out of seeing [what was happening in] the South. Spirits were stirred, [while] nothing was happening with them in the North” (Roger Wilkins, p.&nbsp;239).</p>
</blockquote>
</section>
<section id="fragmentação-e-legado-96112" class="level3" data-number="9.4">
<h3 data-number="9.4" class="anchored" data-anchor-id="fragmentação-e-legado-96112"><span class="header-section-number">9.4</span> Fragmentação e legado [§96–§112]</h3>
<p>Nos anos 1970-80, o movimento se fragmenta. A classe média negra se beneficia de políticas de ação afirmativa, mas a pobreza negra persiste. O declínio da indústria manufatureira afeta desproporcionalmente os negros urbanos.</p>
<p><strong>A “brasilianização” das relações raciais:</strong> com o fim de Jim Crow, os EUA se aproximam do modelo brasileiro — discriminação informal, ausência de segregação legal, desigualdade persistente. No entanto, a identidade negra continua mais forte do que no Brasil, devido à história de segregação legal.</p>
<blockquote class="blockquote">
<p>“The end of legal segregation and rise of the black middle class somewhat diminished racial unity, but the reality and perception of a linked fate did not disappear” (p.&nbsp;245).</p>
</blockquote>
<p><strong>Nota 20:</strong> Marx é cético quanto ao “pós-racialismo”. A discriminação persiste e os negros continuam a se identificar racialmente como forma de resistência. No entanto, sem um alvo legal claro, a mobilização de massa diminuiu.</p>
</section>
</section>
<section id="capítulo-10-breaching-brazils-pact-of-silence-pp.-25063" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="capítulo-10-breaching-brazils-pact-of-silence-pp.-25063"><span class="header-section-number">10</span> Capítulo 10: Breaching Brazil’s Pact of Silence (pp.&nbsp;250–63)</h2>
<section id="a-fragilidade-da-identidade-negra-sob-a-democracia-racial-120" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="a-fragilidade-da-identidade-negra-sob-a-democracia-racial-120"><span class="header-section-number">10.1</span> A fragilidade da identidade negra sob a democracia racial [§1–§20]</h3>
<p>O capítulo começa contrastando a situação brasileira com a sul-africana e norte-americana. “Na ausência de racismo legal, a discriminação informal via costumes e consenso é menos definidora, menos explícita em sua origem e mais difícil de desafiar” (p.&nbsp;251).</p>
<p><strong>Consequências para a identidade negra:</strong></p>
<ul>
<li>A ideologia da “democracia racial” leva muitos negros a <strong>internalizarem sua inferioridade</strong> e a buscarem ascensão individual, não coletiva.</li>
<li>“Every black wants to be white” (p.&nbsp;252). A mobilidade social depende de “embranquecer” (passar).</li>
<li>A categoria “mulato” dilui a polarização racial. As pesquisas mostram múltiplas autoidentificações (mais de 100 termos para cor).</li>
</ul>
<blockquote class="blockquote">
<p>“The official Brazilian ideology of non-discrimination, by not reflecting reality and indeed by camouflaging it, achieves without tension the same results as do overtly racist societies” (Anani Dzidzienyo, p.&nbsp;251).</p>
</blockquote>
<p><strong>Nota 21:</strong> Marx cita dados que mostram que a renda de não-brancos é metade da dos brancos (1960, 1976), e que a diferença entre mulatos e negros é insignificante. No entanto, a crença na “válvula de escape” persiste como mito.</p>
</section>
<section id="a-atuação-do-movimento-negro-2145" class="level3" data-number="10.2">
<h3 data-number="10.2" class="anchored" data-anchor-id="a-atuação-do-movimento-negro-2145"><span class="header-section-number">10.2</span> A atuação do movimento negro [§21–§45]</h3>
<p><strong>Frente Negra Brasileira (1931-37):</strong> primeiro movimento negro nacional. Era <strong>patriótica e moderada</strong>, apoiando Vargas e a democracia racial. Foi banida quando Vargas fechou o Congresso em 1937.</p>
<p><strong>Movimento Negro Unificado (MNU, anos 1970-80):</strong> surge durante a abertura política (<em>abertura</em>). Mais militante que a Frente, mas ainda <strong>pequeno e elitista</strong> (menos de 2 mil membros ativos em 1982). Focou em afirmar a identidade negra e denunciar o racismo, mas teve pouca capacidade de mobilização de massa.</p>
<p><strong>Nota 22:</strong> A comparação com o Black Power nos EUA ou o Black Consciousness na África do Sul é gritante: o MNU nunca conseguiu mobilizar centenas de milhares de pessoas. A ausência de segregação legal como alvo concreto é a principal explicação.</p>
<p><strong>Política eleitoral:</strong></p>
<ul>
<li>Benedita da Silva (PT) foi a primeira mulher negra eleita para o Congresso (1986) e depois Senadora. Ela usou discurso racial, mas reconheceu que “In Brazil, it doesn’t help to use race; the identity is not strong” (p.&nbsp;259).</li>
<li>A maioria dos políticos negros evita o discurso racial, preferindo apelar à classe.</li>
</ul>
</section>
<section id="o-papel-do-estado-e-a-cooptação-4655" class="level3" data-number="10.3">
<h3 data-number="10.3" class="anchored" data-anchor-id="o-papel-do-estado-e-a-cooptação-4655"><span class="header-section-number">10.3</span> O papel do estado e a cooptação [§46–§55]</h3>
<p>O estado brasileiro respondeu ao movimento negro com <strong>cooptação</strong>, não repressão (exceto durante a ditadura):</p>
<ul>
<li>Criação de secretarias para assuntos afro-brasileiros (ex.: Secretaria de Promoção e Defesa do Afro-Brasileiro no Rio de Janeiro, liderada por Abdias do Nascimento).</li>
<li>Celebração do centenário da abolição (1988) com ênfase na democracia racial.</li>
<li>Inclusão na Constituição de 1988 de um artigo tornando o racismo crime inafiançável (embora raramente aplicado).</li>
</ul>
<p>Marx conclui que a “democracia racial” é uma forma <strong>engenhosa de engenharia social por omissão</strong>. Ao não codificar a dominação racial, o estado brasileiro evitou a consolidação de uma identidade negra unificada e, portanto, evitou um movimento de protesto em massa. O preço é a persistência de uma desigualdade racial brutal, mas politicamente invisível.</p>
<blockquote class="blockquote">
<p>“The only thing Brazil got right was race” (Januário Garcia, ironicamente, p.&nbsp;262).</p>
</blockquote>
</section>
</section>
<section id="capítulo-11-conclusion-pp.-26778" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="capítulo-11-conclusion-pp.-26778"><span class="header-section-number">11</span> Capítulo 11: Conclusion (pp.&nbsp;267–78)</h2>
<section id="síntese-do-argumento-110" class="level3" data-number="11.1">
<h3 data-number="11.1" class="anchored" data-anchor-id="síntese-do-argumento-110"><span class="header-section-number">11.1</span> Síntese do argumento [§1–§10]</h3>
<p>Marx reafirma a tese central: <strong>a dominação racial foi construída como ferramenta de consolidação do estado-nação</strong> onde havia conflito intra-branco significativo (África do Sul, EUA). Onde esse conflito era ausente (Brasil), a ordem racial permaneceu informal, sob a ideologia da democracia racial.</p>
<blockquote class="blockquote">
<p>“States made race; race made nation-states.”</p>
</blockquote>
<p><strong>Recapitulação dos mecanismos:</strong></p>
<ol type="1">
<li><strong>Conflito intra-branco</strong> (étnico ou regional) ameaça a estabilidade e o desenvolvimento.</li>
<li>Elites usam a <strong>exclusão racial legal</strong> para unificar os brancos contra um “outro” negro.</li>
<li>A dominação racial <strong>consolida a identidade negra</strong> e, com o tempo, gera protesto.</li>
<li>O protesto negro se torna uma nova ameaça à estabilidade, forçando o <strong>desmantelamento da dominação legal</strong>.</li>
<li>No Brasil, a ausência do passo 1 eliminou a pressão para os passos 2 e 3, mantendo a desigualdade informal.</li>
</ol>
</section>
<section id="o-desmantelamento-da-dominação-legal-1120" class="level3" data-number="11.2">
<h3 data-number="11.2" class="anchored" data-anchor-id="o-desmantelamento-da-dominação-legal-1120"><span class="header-section-number">11.2</span> O desmantelamento da dominação legal [§11–§20]</h3>
<p>A transição pós-Jim Crow e pós-apartheid deixou os EUA e a África do Sul em uma situação similar à do Brasil: <strong>discriminação informal, ausência de segregação legal, persistência da desigualdade</strong>.</p>
<ul>
<li>Nos EUA, a “brasilianização” significa que o racismo persiste, mas sem o alvo claro de leis segregacionistas, a mobilização de massa diminuiu. A identidade negra, no entanto, continua forte devido à história de segregação legal e à experiência compartilhada de discriminação.</li>
<li>Na África do Sul, a transição para a democracia não-racial não resolveu a desigualdade econômica. O risco de conflitos étnicos (Zulu vs.&nbsp;Xhosa) e de classe persiste.</li>
</ul>
<p><strong>Nota 23:</strong> Marx argumenta que a “brasilianização” não é necessariamente uma boa notícia. No Brasil, a democracia racial serviu para <strong>camuflar a desigualdade</strong> e desmobilizar a população negra. A “cegueira de cor” (<em>color-blindness</em>) que muitos liberais americanos propõem pode ter efeitos semelhantes.</p>
</section>
<section id="generalizações-para-outros-casos-2130" class="level3" data-number="11.3">
<h3 data-number="11.3" class="anchored" data-anchor-id="generalizações-para-outros-casos-2130"><span class="header-section-number">11.3</span> Generalizações para outros casos [§21–§30]</h3>
<p>Marx sugere que o padrão encontrado pode ser generalizado para outros casos de exclusão interna na construção de estados-nação:</p>
<ul>
<li><strong>Alemanha nazista:</strong> o anti-semitismo foi usado para unificar os alemães contra um inimigo interno, em um contexto de grave conflito de classes e instabilidade política após a Primeira Guerra Mundial.</li>
<li><strong>União Soviética:</strong> a exclusão de classe (capitalistas, kulaks, “inimigos do povo”) serviu para unificar a população em torno do partido comunista, embora o estado soviético também fosse multiétnico.</li>
<li><strong>México (pós-revolução):</strong> ao contrário, a ausência de exclusão legal após a revolução de 1910 levou a um corporativismo inclusivo, semelhante ao Brasil.</li>
</ul>
<p>A implicação mais ampla é que a <strong>construção de nações via exclusão interna</strong> é um padrão histórico recorrente, e não uma exceção.</p>
</section>
<section id="implicações-normativas-3135" class="level3" data-number="11.4">
<h3 data-number="11.4" class="anchored" data-anchor-id="implicações-normativas-3135"><span class="header-section-number">11.4</span> Implicações normativas [§31–§35]</h3>
<p>Marx não oferece receitas políticas, mas alerta contra a ilusão de que o fim da segregação legal significa o fim do racismo.</p>
<blockquote class="blockquote">
<p>“What appears liberal is not” (p.&nbsp;274) — referindo-se à “cegueira de cor” que ignora a desigualdade estrutural.</p>
</blockquote>
<p>A obra conclui com um apelo à <strong>ação institucional</strong> para combater o racismo, mesmo após o desmantelamento das leis segregacionistas. A identidade racial persiste como legado do passado e como recurso para a ação política no presente.</p>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">12</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A tese central de Marx é que a dominação racial legal (apartheid, Jim Crow) foi construída como uma <strong>ferramenta estratégica de consolidação do estado-nação</strong> em contextos de grave conflito intra-branco (étnico na África do Sul, regional nos EUA). Esse argumento é <strong>causal e histórico-institucionalista</strong>: a variável independente é o grau de conflito entre fragmentos brancos; a variável dependente é a codificação (ou não) da exclusão racial; o mecanismo é a apaziguação das elites vitoriosas com os brancos derrotados, à custa dos negros.</p>
<p>O livro demonstra, com evidência histórica robusta, que explicações concorrentes (legados coloniais, tipo de escravidão, grau de miscigenação) são insuficientes. A contribuição central é <strong>integrar a análise de formação do estado com a análise de relações raciais</strong>, mostrando que o nacionalismo não apenas <em>produz</em> exclusão, mas que a exclusão racial é <em>instrumental</em> para o nacionalismo.</p>
<p>A Parte III, sobre protesto negro, é menos original, mas coerente com a lógica geral: a dominação legal consolida a identidade subordinada, e o feedback loop eventualmente força a reforma institucional. A generalização para outros casos (Alemanha, URSS) é sugerida, mas não desenvolvida em profundidade, sendo uma agenda de pesquisa.</p>
<p>A principal limitação do livro é a possível <strong>funcionalidade teleológica</strong>: ao enfatizar a intencionalidade das elites, Marx corre o risco de fazer a dominação racial parecer mais “projetada” e menos contingente do que realmente foi. No entanto, seu uso extensivo de fontes primárias e a atenção a contra-exemplos mitigam essa crítica.</p>
<p>Em suma, <em>Making Race and Nation</em> é um clássico da política comparada, obrigatório para estudiosos de nacionalismo, estado e relações raciais.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>