<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-06-29">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: How Democracies Transform Their Welfare States – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1596dba0f6ebd5d6ff9514dff97656d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: How Democracies Transform Their Welfare States – Annotated Bibliography">
<meta property="og:description" content="Palier, B., Garritzmann, J. L., Häusermann, S., &amp; Fioritto, F. (2022). How democracies transform their welfare states: The reform trajectories and political coalitions of inclusive, stratified, and targeted social investment strategies in capitalist democracies. In J. L. Garritzmann, S. Häusermann, &amp; B. Palier (Eds.), The world politics of social investment (Volume II): The politics of varying social investment strategies (pp.&nbsp;402–475). Oxford University Press. https://doi.org/10.1093/oso/9780197601457.003.0017">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#introdução-pp.-402405" id="toc-introdução-pp.-402405" class="nav-link" data-scroll-target="#introdução-pp.-402405"><span class="header-section-number">1</span> Introdução (pp.&nbsp;402–405)</a>
  <ul class="collapse">
  <li><a href="#pergunta-de-pesquisa-escopo-e-dupla-decomposição-analítica-15" id="toc-pergunta-de-pesquisa-escopo-e-dupla-decomposição-analítica-15" class="nav-link" data-scroll-target="#pergunta-de-pesquisa-escopo-e-dupla-decomposição-analítica-15">Pergunta de pesquisa, escopo e dupla decomposição analítica [§1–§5]</a></li>
  </ul></li>
  <li><a href="#seção-17.1-panorama-cross-regional-das-dinâmicas-ideacionais-estruturais-e-institucionais-pp.-405419" id="toc-seção-17.1-panorama-cross-regional-das-dinâmicas-ideacionais-estruturais-e-institucionais-pp.-405419" class="nav-link" data-scroll-target="#seção-17.1-panorama-cross-regional-das-dinâmicas-ideacionais-estruturais-e-institucionais-pp.-405419"><span class="header-section-number">2</span> Seção 17.1: Panorama Cross-Regional das Dinâmicas Ideacionais, Estruturais e Institucionais (pp.&nbsp;405–419)</a>
  <ul class="collapse">
  <li><a href="#explicando-as-dinâmicas-de-politização-68" id="toc-explicando-as-dinâmicas-de-politização-68" class="nav-link" data-scroll-target="#explicando-as-dinâmicas-de-politização-68">§17.1.1 — Explicando as dinâmicas de politização [§6–§8]</a></li>
  <li><a href="#dinâmicas-ideacionais-911" id="toc-dinâmicas-ideacionais-911" class="nav-link" data-scroll-target="#dinâmicas-ideacionais-911">§17.1.1.1 — Dinâmicas ideacionais [§9–§11]</a></li>
  <li><a href="#dinâmicas-estruturais-condições-sociodemográficas-econômicas-e-demandaoferta-de-qualificações-1221" id="toc-dinâmicas-estruturais-condições-sociodemográficas-econômicas-e-demandaoferta-de-qualificações-1221" class="nav-link" data-scroll-target="#dinâmicas-estruturais-condições-sociodemográficas-econômicas-e-demandaoferta-de-qualificações-1221">§17.1.1.2 — Dinâmicas estruturais: condições sociodemográficas, econômicas e demanda/oferta de qualificações [§12–§21]</a></li>
  <li><a href="#legados-de-bem-estar-2025" id="toc-legados-de-bem-estar-2025" class="nav-link" data-scroll-target="#legados-de-bem-estar-2025">§17.1.1.3 — Legados de bem-estar [§20–§25]</a></li>
  <li><a href="#o-que-impulsiona-a-saliência-das-propostas-de-investimento-social-2629" id="toc-o-que-impulsiona-a-saliência-das-propostas-de-investimento-social-2629" class="nav-link" data-scroll-target="#o-que-impulsiona-a-saliência-das-propostas-de-investimento-social-2629">§17.1.1.4 — O que impulsiona a saliência das propostas de investimento social? [§26–§29]</a></li>
  <li><a href="#dinâmicas-de-formação-de-coalizões-e-tomada-de-decisão-3038" id="toc-dinâmicas-de-formação-de-coalizões-e-tomada-de-decisão-3038" class="nav-link" data-scroll-target="#dinâmicas-de-formação-de-coalizões-e-tomada-de-decisão-3038">§17.1.2 — Dinâmicas de formação de coalizões e tomada de decisão [§30–§38]</a></li>
  </ul></li>
  <li><a href="#seção-17.2-mapeando-e-explicando-o-desenvolvimento-das-políticas-de-investimento-social-por-região-pp.-419446" id="toc-seção-17.2-mapeando-e-explicando-o-desenvolvimento-das-políticas-de-investimento-social-por-região-pp.-419446" class="nav-link" data-scroll-target="#seção-17.2-mapeando-e-explicando-o-desenvolvimento-das-políticas-de-investimento-social-por-região-pp.-419446"><span class="header-section-number">3</span> Seção 17.2: Mapeando e Explicando o Desenvolvimento das Políticas de Investimento Social por Região (pp.&nbsp;419–446)</a>
  <ul class="collapse">
  <li><a href="#introdução-à-análise-regional-3940" id="toc-introdução-à-análise-regional-3940" class="nav-link" data-scroll-target="#introdução-à-análise-regional-3940">Introdução à análise regional [§39–§40]</a></li>
  <li><a href="#os-três-mundos-ocidentais-do-investimento-social-4153" id="toc-os-três-mundos-ocidentais-do-investimento-social-4153" class="nav-link" data-scroll-target="#os-três-mundos-ocidentais-do-investimento-social-4153">Os três mundos ocidentais do investimento social [§41–§53]</a></li>
  <li><a href="#a-europa-do-sul-protecionismo-social-em-vez-de-investimento-social-5158" id="toc-a-europa-do-sul-protecionismo-social-em-vez-de-investimento-social-5158" class="nav-link" data-scroll-target="#a-europa-do-sul-protecionismo-social-em-vez-de-investimento-social-5158">A Europa do Sul: protecionismo social em vez de investimento social [§51–§58]</a></li>
  <li><a href="#a-europa-central-e-oriental-laggards-e-divergência-interna-5463" id="toc-a-europa-central-e-oriental-laggards-e-divergência-interna-5463" class="nav-link" data-scroll-target="#a-europa-central-e-oriental-laggards-e-divergência-interna-5463">A Europa Central e Oriental: laggards e divergência interna [§54–§63]</a></li>
  <li><a href="#ásia-do-nordeste-a-virada-ao-investimento-social-estratificado-6168" id="toc-ásia-do-nordeste-a-virada-ao-investimento-social-estratificado-6168" class="nav-link" data-scroll-target="#ásia-do-nordeste-a-virada-ao-investimento-social-estratificado-6168">Ásia do Nordeste: a virada ao investimento social estratificado [§61–§68]</a></li>
  <li><a href="#américa-latina-capacidades-diferenciadas-para-o-investimento-social-6978" id="toc-américa-latina-capacidades-diferenciadas-para-o-investimento-social-6978" class="nav-link" data-scroll-target="#américa-latina-capacidades-diferenciadas-para-o-investimento-social-6978">América Latina: capacidades diferenciadas para o investimento social [§69–§78]</a></li>
  </ul></li>
  <li><a href="#seção-17.3-as-cinco-coalizões-societais-e-políticas-por-trás-das-cinco-estratégias-de-reforma-pp.-446467" id="toc-seção-17.3-as-cinco-coalizões-societais-e-políticas-por-trás-das-cinco-estratégias-de-reforma-pp.-446467" class="nav-link" data-scroll-target="#seção-17.3-as-cinco-coalizões-societais-e-políticas-por-trás-das-cinco-estratégias-de-reforma-pp.-446467"><span class="header-section-number">4</span> Seção 17.3: As Cinco Coalizões Societais e Políticas por Trás das Cinco Estratégias de Reforma (pp.&nbsp;446–467)</a>
  <ul class="collapse">
  <li><a href="#enquadramento-as-cinco-estratégias-e-a-tipologia-das-coalizões-7986" id="toc-enquadramento-as-cinco-estratégias-e-a-tipologia-das-coalizões-7986" class="nav-link" data-scroll-target="#enquadramento-as-cinco-estratégias-e-a-tipologia-das-coalizões-7986">§17.3 — Enquadramento: as cinco estratégias e a tipologia das coalizões [§79–§86]</a></li>
  <li><a href="#as-duas-coalizões-social-democráticas-8795" id="toc-as-duas-coalizões-social-democráticas-8795" class="nav-link" data-scroll-target="#as-duas-coalizões-social-democráticas-8795">§17.3.1 — As duas coalizões social-democráticas [§87–§95]</a></li>
  <li><a href="#as-coalizões-conservadora-e-liberal-96107" id="toc-as-coalizões-conservadora-e-liberal-96107" class="nav-link" data-scroll-target="#as-coalizões-conservadora-e-liberal-96107">§17.3.2 — As coalizões conservadora e liberal [§96–§107]</a></li>
  <li><a href="#a-coalizão-social-protecionista-108115" id="toc-a-coalizão-social-protecionista-108115" class="nav-link" data-scroll-target="#a-coalizão-social-protecionista-108115">§17.3.3 — A coalizão social-protecionista [§108–§115]</a></li>
  </ul></li>
  <li><a href="#seção-17.4-conclusão-pp.-467471" id="toc-seção-17.4-conclusão-pp.-467471" class="nav-link" data-scroll-target="#seção-17.4-conclusão-pp.-467471"><span class="header-section-number">5</span> Seção 17.4: Conclusão (pp.&nbsp;467–471)</a>
  <ul class="collapse">
  <li><a href="#síntese-dos-achados-116120" id="toc-síntese-dos-achados-116120" class="nav-link" data-scroll-target="#síntese-dos-achados-116120">§17.4.1 — Síntese dos achados [§116–§120]</a></li>
  <li><a href="#investimento-social-durante-e-após-a-crise-do-covid-19-121128" id="toc-investimento-social-durante-e-após-a-crise-do-covid-19-121128" class="nav-link" data-scroll-target="#investimento-social-durante-e-após-a-crise-do-covid-19-121128">§17.4.2 — Investimento social durante e após a crise do COVID-19 [§121–§128]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">6</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: How Democracies Transform Their Welfare States</h1>
<p class="subtitle lead">Palier, B., Garritzmann, J. L., Häusermann, S., &amp; Fioritto, F. (2022). How democracies transform their welfare states: The reform trajectories and political coalitions of inclusive, stratified, and targeted social investment strategies in capitalist democracies. In J. L. Garritzmann, S. Häusermann, &amp; B. Palier (Eds.), <em>The world politics of social investment (Volume II): The politics of varying social investment strategies</em> (pp.&nbsp;402–475). Oxford University Press. https://doi.org/10.1093/oso/9780197601457.003.0017</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Comparative Politics</div>
    <div class="quarto-category">Political Economy</div>
    <div class="quarto-category">Welfare State/Social Policy</div>
    <div class="quarto-category">Social Investment</div>
    <div class="quarto-category">Coalition Analysis</div>
    <div class="quarto-category">Comparative</div>
    <div class="quarto-category">2022</div>
    <div class="quarto-category">2020s</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Informações Técnicas e BibTeX
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>Última atualização: 2026-06-29
Modelo: claude-sonnet-4-6
Prompt Version: v17.4 · 2026-05-13
Gerado em: 2026-06-29T16:00:00-03:00
Ocasião da Leitura:</code></pre>
<p><strong>Entrada BibTeX → Palier-etal2022</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@incollection</span>{<span class="ot">Palier</span>-<span class="ot">etal2022</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>    = {Palier, Bruno and Garritzmann, Julian L. and Häusermann, Silja and Fioritto, Francesco},</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>     = {How Democracies Transform Their Welfare States: The Reform Trajectories and Political Coalitions of Inclusive, Stratified, and Targeted Social Investment Strategies in Capitalist Democracies},</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">booktitle</span> = {The World Politics of Social Investment (Volume II): The Politics of Varying Social Investment Strategies},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">editor</span>    = {Garritzmann, Julian L. and Häusermann, Silja and Palier, Bruno},</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>      = {2022},</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">publisher</span> = {Oxford University Press},</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">address</span>   = {Oxford},</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span>     = {402--475},</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="dt">doi</span>       = {10.1093/oso/9780197601457.003.0017},</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.4</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">O capítulo é explícito ao formular a pergunta; a decomposição em duas subquestões (funções vs.&nbsp;perfil distributivo) é teoricamente sofisticada mas pode criar tensão analítica se os determinantes das duas dimensões não forem independentes.</td>
<td style="text-align: left;">Quais fatores políticos sustentam ou inibem o desenvolvimento de políticas de investimento social em diferentes regiões do mundo? (explicitada, p.&nbsp;402). Desdobra-se em: (a) quais funções predominam nas reformas (criação, mobilização, preservação de capital humano?) e (b) qual é o perfil distributivo das reformas (inclusivo, estratificado ou focalizado?)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">A decomposição regional é empiricamente rica mas a pergunta sobre mecanismos causais fica parcialmente subteorizada — o capítulo tende a identificar correlações entre coalização e política sem especificar o mecanismo que conecta os dois.</td>
<td style="text-align: left;">(1) Como as dinâmicas de politização (ideacionais, estruturais, institucionais) determinam quais funções do investimento social entram na agenda? (2) Como a composição das coalizões políticas determina o perfil distributivo das reformas adotadas? (3) Existe um trade-off sistemático entre políticas compensatórias e de investimento social?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno e generalizável: países com desafios socioeconômicos similares adotam estratégias radicalmente diferentes. No entanto, dado que o capítulo é uma síntese, o “puzzle” pode ser parcialmente pós-hoc — a tipologia foi construída para explicar padrões que os autores já conheciam a partir dos estudos regionais.</td>
<td style="text-align: left;">Puzzle explicativo de variação: por que democracias capitalistas expostas a desafios socioeconômicos análogos (envelhecimento, riscos sociais novos, demanda por qualificação) adotam estratégias tão distintas de investimento social em termos de funções priorizadas e perfil distributivo? O puzzle é genuíno e de alta relevância para a política comparada contemporânea.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">O argumento central é claro e elegante; a dependência da “classe média educada” como variável pivô é bem fundamentada nas evidências regionais, mas pode ser criticada como um fator ad hoc ex post — define-se a classe como pivô e depois identifica-se sua presença ou ausência para explicar os resultados.</td>
<td style="text-align: left;">As funções priorizadas pelo investimento social são moldadas pela interação entre legados de bem-estar, condições estruturais (sociodemográficas e econômicas) e dinâmicas de politização. O perfil distributivo (inclusivo, estratificado ou focalizado) é determinado pelas coalizões políticas que sustentam as reformas. Cinco coalizões sociopolíticas predominam nas democracias capitalistas do século XXI: (1) social-democrática pró-classe média → investimento inclusivo; (2) social-democrática pró-pobre → investimento focalizado integrativo; (3) conservadora-corporatista → investimento estratificado; (4) liberal “Terceira Via” → investimento focalizado substitutivo; (5) protecionista social → ausência de investimento.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O capítulo é uma síntese qualitativa-comparativa de estudos de caso regionais. A evidência primária está nos outros capítulos dos dois volumes; este capítulo opera ao nível da síntese configuracional, sem conduzir análise empírica original. A ausência de um teste formal da tipologia (e.g., QCA) é uma limitação não reconhecida.</td>
<td style="text-align: left;">Síntese comparativa de estudos de caso regionais coletados ao longo do projeto WOPSI (World Politics of Social Investment). Análise qualitativa e comparativa-histórica com desenho de “variance-explaining”. Uso de figuras-resumo (Figures 17.3–17.11) para sistematizar variáveis por região. O fichamento cobre o capítulo completo (pp.&nbsp;402–475).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">Inferência configuracional implícita: observa padrões cross-regionais e formula tipos. O DGP é robusto em termos de amplitude (6 regiões, ~25 países), mas a profundidade da evidência varia regionalmente — a Europa Ocidental é muito mais tratada do que América Latina ou Ásia do Nordeste. Vieses potenciais: seleção de casos (democracias capitalistas exclui África, Sul/Sudeste Asiático); autores são sobretudo europeus com possível viés em favor da experiência europeia como caso “normal”.</td>
<td style="text-align: left;">Dados e análises regionais gerados pelos capítulos dos dois volumes do WOPSI. Unidade de análise primária: região e país. Inferência de tipo configuracional comparativo. Evidências variadas: gastos públicos, análises de coalizões partidárias, estudos de caso de reformas específicas (ECEC, ALMPs, VET, CCTs). As figuras 17.3–17.11 operacionalizam cada variável do framework para cada região.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">Os achados mais robustos são os relativos à Europa Ocidental; os relativos à América Latina e Ásia do Nordeste são mais impressionistas. A tipologia de cinco coalizões é uma contribuição genuína à literatura de economia política comparada, mas sua validade externa (fora das democracias estudadas) permanece em aberto.</td>
<td style="text-align: left;">(1) Tipologia de cinco estratégias de reforma + cinco coalizões políticas correspondentes. (2) Papel central da classe média educada como força pivô nas coalizões; seu tamanho determina o tipo de aliança e o perfil distributivo resultante. (3) Distinção crucial entre investimento focalizado “integrativo” (complementar à compensação) e “substitutivo” (substitui a compensação). (4) Confirmação de que o liberalismo de mercado inclui, de fato, uma componente de investimento social (focalizado substitutivo). (5) Ausência de qualquer caso de renda básica universal implementada. (6) COVID-19 tende a fortalecer lógicas compensatórias e a enfraquecer o investimento social.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">Três vulnerabilidades centrais: (a) as “coalizões” são identificadas ex post a partir dos resultados de política, não rastreadas prospectivamente — não há mecanismo causal que demonstre como a coalizão gera o resultado; (b) a variável “tamanho da classe média educada” é o principal preditor, mas sua mensuração e limiar de suficiência não são especificados; (c) casos desviantes dentro das regiões são tratados como “exceções” sem uma teorização clara de por que as exceções ocorrem.</td>
<td style="text-align: left;">O capítulo responde bem à pergunta descritiva (quais estratégias existem e quais coalizões as sustentam), mas menos bem à pergunta causal (por que determinada coalizão emerge). O argumento da “classe média educada como pivô” é bem sustentado pelos dados europeus, mas menos convincente para os casos da Ásia do Nordeste (onde conservadores dominam e o investimento social ainda avança) e da América Latina (onde coalizões são frequentemente lideradas pelo estado/burocracia, não pela sociedade civil). A distinção entre investimento focalizado “integrativo” e “substitutivo” é conceitualmente valiosa, mas sua operacionalização empírica não é demonstrada sistematicamente.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;">Reconhecidas pelos autores: impossibilidade de integrar as respostas à COVID-19 de forma sistemática; cobertura incompleta do Leste Europeu (ex-Iugoslávia e Europa do Sudeste excluídas); as “instâncias” (instances) são usadas para ilustrar, não para testar formalmente a tipologia. <br> <strong>Não reconhecidas ou subestimadas:</strong> (1) A tipologia das cinco coalizões é construída indutivamente a partir de casos selecionados e não é testada formalmente; (2) a endogeneidade entre legados de bem-estar, tamanho da classe média educada e tipo de coalizão não é discutida; (3) o capítulo exclui democracias semi-periféricas emergentes (África do Sul, Índia, Turquia) onde o framework poderia ser testado de forma mais rigorosa; (4) a temporalidade das coalizões (como surgem, mudam, colapsam) fica analiticamente vaga.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">Intersecção de três tradições: institucionalismo histórico (legados moldam trajetórias), VoC/economia política comparada (morfologia capitalista determina demanda por qualificações), e análise de coalizões de classes (Häusermann &amp; Palier, Power Resources). A combinação é coerente, mas a ausência de diálogo explícito com a literatura sobre clientelismo e com a literatura sobre ideias na política social é uma lacuna.</td>
<td style="text-align: left;">Institucionalismo histórico combinado com economia política comparada (Varieties of Capitalism, Hall &amp; Soskice, 2001) e análise de coalizões de classe (Häusermann &amp; Palier, 2017; Beramendi et al., 2015). Diálogo com Esping-Andersen (1990, 1996), Palier &amp; Thelen (2010), Emmenegger et al.&nbsp;(2012), Hassel &amp; Palier (2021), Green-Pedersen (2007), Culpepper (2010), e Giddens (1998).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">Base bibliográfica sólida e diversificada, com forte representação da literatura europeia. Diálogo menos desenvolvido com a literatura latino-americanista (Barrientos, Bogliaccini, Madariaga) e com a literatura asiática, que aparecem apenas via os capítulos do próprio volume WOPSI.</td>
<td style="text-align: left;">Esping-Andersen (1990, 1996, 2002); Hall &amp; Soskice (2001); Häusermann &amp; Palier (2017); Hassel &amp; Palier (2021a, 2021b); Palier &amp; Thelen (2010); Emmenegger et al.&nbsp;(2012); Beramendi et al.&nbsp;(2015); Green-Pedersen (2007); Culpepper (2010); Giddens (1998); Garritzmann et al.&nbsp;(2022) [Volume I do WOPSI]; Bonoli (2007); Chevalier (2016).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">(1) O capítulo é uma síntese de segunda ordem — a evidência primária está nos outros capítulos dos volumes; avaliá-lo isoladamente implica que se aceite os resultados dos estudos regionais como dados. (2) O texto é rico em tipologias mas pobre em mecanismos causais; seria fortalecido por um capítulo de teoria formal que especificasse as condições de suficiência e necessidade para cada coalizão. (3) O conceito de “investimento social focalizado integrativo” é uma das contribuições mais originais do capítulo e merece mais atenção futura. (4) A seção sobre COVID-19 é normativa e especulativa, o que a diferencia do restante do capítulo. (5) O capítulo lida com capítulo de coletânea — leitura integral coberta.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 19%">
<col style="width: 28%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Seção</th>
<th style="text-align: left;">Título / Tema</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Introdução (pp.&nbsp;402–405)</td>
<td style="text-align: left;">Apresentação do projeto WOPSI, da pergunta de pesquisa e da dupla decomposição analítica</td>
<td style="text-align: left;">Apresentação do puzzle e da tese</td>
<td style="text-align: left;">Formula a pergunta central (quais fatores políticos sustentam ou inibem o investimento social?) e a decompõe em duas dimensões explicativas: funções do investimento e perfil distributivo. Apresenta a Table 17.1 como síntese da variação regional observada.</td>
</tr>
<tr class="even">
<td style="text-align: left;">§17.1 (pp.&nbsp;405–419)</td>
<td style="text-align: left;">Panorama cross-regional das dinâmicas ideacionais, estruturais e institucionais</td>
<td style="text-align: left;">Fundamento teórico e revisão cruzada do framework</td>
<td style="text-align: left;">Revisa sistematicamente as variáveis explicativas do framework WOPSI — ideias, estrutura sociodemográfica e econômica, demanda/oferta de qualificações, legados de bem-estar, atores, coalizões — demonstrando como cada variável se manifesta de forma diferenciada nas regiões estudadas.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">§17.2 (pp.&nbsp;419–446)</td>
<td style="text-align: left;">Mapeamento e explicação regional do desenvolvimento do investimento social</td>
<td style="text-align: left;">Análise empírica comparada por região</td>
<td style="text-align: left;">Aplica o framework aos cinco contextos regionais (Europa Ocidental e América do Norte; Europa do Sul; Europa Central e Oriental; Ásia do Nordeste; América Latina) e preenche as figuras-resumo (17.3–17.11) com as características de cada caso.</td>
</tr>
<tr class="even">
<td style="text-align: left;">§17.3 (pp.&nbsp;446–467)</td>
<td style="text-align: left;">As cinco coalizões societais e políticas por trás das cinco estratégias de reforma</td>
<td style="text-align: left;">Síntese, extensão e contribuição teórica original</td>
<td style="text-align: left;">Supera a análise regional para apresentar uma tipologia transversal de cinco coalizões políticas correspondentes a cinco estratégias de reforma. Demonstra que o perfil distributivo do investimento social é determinado primariamente pela composição das coalizões que o sustentam.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">§17.4 (pp.&nbsp;467–471)</td>
<td style="text-align: left;">Conclusão: síntese dos achados e impacto do COVID-19</td>
<td style="text-align: left;">Síntese, qualificação e agenda normativa</td>
<td style="text-align: left;">Recapitula os achados das três seções anteriores e discute as implicações da pandemia de COVID-19, argumentando que a crise tende a reforçar lógicas compensatórias em detrimento do investimento social inclusivo.</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Divergências internas
</div>
</div>
<div class="callout-body-container callout-body">
<p>O capítulo é uma síntese de autoria coletiva dos próprios organizadores do projeto WOPSI — não há divergências internas no capítulo em si. No conjunto dos dois volumes do projeto, porém, existem tensões entre a ênfase em fatores estruturais (alguns capítulos regionais) e a ênfase em atores e coalizões (este capítulo de síntese). A distinção entre investimento focalizado “integrativo” (América Latina) e “substitutivo” (países liberais) também tensiona com a classificação mais simples da Table 17.1, onde ambos aparecem sob a mesma categoria “targeted social investment.”</p>
</div>
</div>
</section>
<section id="introdução-pp.-402405" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-402405"><span class="header-section-number">1</span> Introdução (pp.&nbsp;402–405)</h2>
<section id="pergunta-de-pesquisa-escopo-e-dupla-decomposição-analítica-15" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="pergunta-de-pesquisa-escopo-e-dupla-decomposição-analítica-15">Pergunta de pesquisa, escopo e dupla decomposição analítica [§1–§5]</h3>
<p>§1 — O capítulo abre marcando sua posição no conjunto da obra: trata-se do capítulo de encerramento do segundo volume do projeto <strong>WOPSI</strong> (<em>World Politics of Social Investment</em>), que reuniu estudos de caso sobre a política do investimento social em cinco grandes regiões do mundo — Europa Ocidental e do Norte, Europa do Sul, Europa Central e Oriental, Ásia do Nordeste e América Latina. Os autores (Palier, Garritzmann, Häusermann e Fioritto) assumem a função de síntese global, mapeando o desenvolvimento das reformas do Estado de bem-estar com atenção especial à sua componente de investimento social.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Pergunta de pesquisa central:</strong> <em>Which political factors support or inhibit the development of social investment policies across different world regions?</em> (p.&nbsp;402)</p>
</div>
</div>
<p>§2 — O capítulo desdobra a pergunta de pesquisa em duas dimensões analíticas. A primeira refere-se às <strong>funções</strong> predominantes das reformas de investimento social: se estão voltadas primariamente para a <em>criação</em> (creation), <em>mobilização</em> (mobilization) ou <em>preservação</em> (preservation) de habilidades e capacidades humanas. A segunda dimensão diz respeito ao <strong>perfil distributivo</strong> das reformas: se são <em>inclusivas</em>, <em>estratificadas</em> ou <em>focalizadas</em> (targeted). Essa tipologia bidimensional, introduzida no Capítulo 1 do Volume I (Garritzmann et al., 2022), serve como grade analítica transversal a todo o capítulo.</p>
<p>§3 — A <strong>Tabela 17.1</strong> sintetiza os principais padrões observados: o investimento social inclusivo (nas três funções) prevalece nos países nórdicos; o estratificado domina na Europa Continental e na Ásia do Nordeste; o focalizado (targeted) é a forma dominante na América Latina (especialmente via transferências condicionadas de renda, CCTs) e nos países anglófonos, embora por razões e mecanismos distintos. Políticas específicas que desviam da estratégia regional dominante são também anotadas — por exemplo, políticas inclusivas de ECEC (<em>Early Childhood Education and Care</em>) nos países bálticos e na Ásia do Nordeste.</p>
<p>§4 — A Europa do Sul destaca-se negativamente: apesar de enfrentar riscos sociais novos, envelhecimento populacional e baixa participação feminina no mercado de trabalho, os países mediterrâneos não conseguiram desenvolver reformas de investimento social politicamente sustentáveis. Este é tratado como caso negativo paradigmático. A América Latina é subdividida entre países mais desenvolvidos (Brasil, Chile, Argentina, Costa Rica, Uruguai, México), que acompanharam os CCTs com expansão de serviços, e países menos desenvolvidos (Peru, Bolívia, Guatemala, Honduras, Nicarágua), cujos programas carecem de capacidade estatal para implementar efetivamente a dimensão investidora.</p>
<p>§5 — O capítulo está organizado em três partes: (i) revisão do framework teórico WOPSI à luz dos achados regionais; (ii) análise integrada por região; (iii) tipologia de cinco coalizões políticas por trás dos diferentes tipos de reforma. Os autores enfatizam que, enquanto as funções priorizadas pelo investimento social dependem principalmente de condições estruturais e legados institucionais, o <strong>perfil distributivo</strong> das reformas depende primariamente das <strong>coalizões políticas</strong> e dos atores que as impulsionam.</p>
</section>
</section>
<section id="seção-17.1-panorama-cross-regional-das-dinâmicas-ideacionais-estruturais-e-institucionais-pp.-405419" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="seção-17.1-panorama-cross-regional-das-dinâmicas-ideacionais-estruturais-e-institucionais-pp.-405419"><span class="header-section-number">2</span> Seção 17.1: Panorama Cross-Regional das Dinâmicas Ideacionais, Estruturais e Institucionais (pp.&nbsp;405–419)</h2>
<section id="explicando-as-dinâmicas-de-politização-68" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="explicando-as-dinâmicas-de-politização-68">§17.1.1 — Explicando as dinâmicas de politização [§6–§8]</h3>
<p>§6 — A seção retoma o framework teórico apresentado na Figure 17.1 (reprodução da Figure 2.1 do Volume I), que decompõe os determinantes da política de investimento social em dinâmicas ideacionais, dinâmicas estruturais (estruturas capitalistas em transformação, demanda por qualificações, mudanças sociodemográficas) e legados de bem-estar, todos agindo sobre os processos de politização e de formação de coalizões. O conceito de <strong>politização</strong> utilizado é o de Green-Pedersen (2007): a crescente importância da competição em torno de um tema nas arenas política e eleitoral.</p>
<p>§7 — O projeto WOPSI confirma que os processos de politização são determinantes para compreender qual função do investimento social prevalece em cada contexto. Entre os casos estudados, os autores identificam tanto processos de politização <strong>demand-driven</strong> (quando o investimento social é muito saliente e há forte demanda societária por ele) quanto processos <strong>supply-driven</strong> (quando a questão não é muito saliente e as políticas emergem mais por iniciativa de produtores, políticos ou burocratas do que em resposta a uma demanda articulada da sociedade).</p>
<p>§8 — A escolha das funções depende parcialmente de pressões socioeconômicas — novos riscos sociais na Europa, envelhecimento e baixa fertilidade na Ásia do Nordeste, pobreza na América Latina —, da demanda por qualificações e das estratégias de crescimento econômico (o tipo de motor do crescimento condiciona o nível e o tipo de qualificações requeridas), e dos legados institucionais de bem-estar (se a compensação social já está bem desenvolvida). Mas também depende das posições dos atores e da capacidade deles de moldar a agenda de reformas.</p>
</section>
<section id="dinâmicas-ideacionais-911" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="dinâmicas-ideacionais-911">§17.1.1.1 — Dinâmicas ideacionais [§9–§11]</h3>
<p>§9 — Jenson e Mahon (Capítulo 3, Volume I) demonstram que houve uma adoção global do paradigma de investimento social nas organizações internacionais ao longo dos anos 1990 e 2000, enquanto Delaporte e Palier (Capítulo 4, Volume I) mostram que essas ideias se difundiram no nível das instituições da UE desde o final dos anos 1990. Contudo, os estudos de caso do Volume II confirmam a hipótese geral sobre dinâmicas ideacionais: na maioria dos casos, <strong>as dinâmicas ideacionais por si sós não são nem necessárias nem suficientes para a politização do investimento social no nível nacional</strong>.</p>
<p>§10 — Os países nórdicos implementaram investimento social muito antes que as organizações internacionais o colocassem na agenda. A dinâmica de emergência das ideias de investimento social na agenda europeia foi mais de <em>uploading</em> de ideias nacionais (anglo-nórdicas nos anos 1990; anglo-germânicas após a metade dos anos 2000) do que de imposição de cima para baixo. Na Europa do Sul, quando a UE pressionou por reformas do bem-estar na esteira das crises financeira e do Euro (início da década de 2010), não havia mais ideias de investimento social — apenas austeridade.</p>
<p>§11 — As dinâmicas ideacionais adquirem significância particular em certos contextos domésticos, especialmente quando a politização é do tipo supply-driven. Este foi o caso na Coreia do Sul, onde o sistema político permite que o presidente molde a agenda política, e em muitos países da América Latina, onde burocratas ou líderes políticos fortes lideraram os esforços de reforma. A relação entre ideias internacionais e adoção nacional é, portanto, mediada por fatores domésticos de forma consistente.</p>
</section>
<section id="dinâmicas-estruturais-condições-sociodemográficas-econômicas-e-demandaoferta-de-qualificações-1221" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="dinâmicas-estruturais-condições-sociodemográficas-econômicas-e-demandaoferta-de-qualificações-1221">§17.1.1.2 — Dinâmicas estruturais: condições sociodemográficas, econômicas e demanda/oferta de qualificações [§12–§21]</h3>
<p>§12 — Em termos sociodemográficos, apenas na Europa Ocidental os <strong>novos riscos sociais</strong> (pobreza de trabalho, emprego precário, desemprego juvenil estrutural, dificuldades de conciliação trabalho-família, desemprego de longa duração, monoparentalidade) desempenharam papel importante em empurrar o investimento social para a agenda política. Em outras regiões (Europa Central e Oriental, América Latina, Ásia do Nordeste, parcialmente América do Norte), esses riscos não se tornaram salientes na agenda política nacional.</p>
<p>§13 — No Sul Global em geral, trabalho informal, pobreza e desigualdade foram identificados como os principais problemas sociais. O foco foi na redução da pobreza e na diminuição da desigualdade — especialmente para evitar a reprodução intergeracional das desigualdades. Nesse contexto, quando se optou por uma abordagem de investimento social, esta assumiu principalmente a forma de políticas de criação de qualificações (ECEC, acesso à saúde, educação, CCTs).</p>
<p>§14 — Na Ásia do Nordeste, nem os novos riscos sociais nem a pobreza ou a desigualdade foram muito proeminentes na agenda. O principal problema percebido foi o <strong>envelhecimento demográfico</strong>. Consequentemente, na medida em que o investimento social foi politizado — de forma comparativamente baixa —, isso aconteceu principalmente em relação ao envelhecimento. Mais foco foi dado a políticas de mobilização de qualificações (especialmente das mulheres) e de conciliação trabalho-vida.</p>
<p>§15 — Em termos de desenvolvimento econômico, a transição para uma economia baseada no conhecimento é importante mas não necessária para explicar a emergência de uma agenda de investimento social. Essa hipótese é confirmada para a Europa e América do Norte, mas não se aplica da mesma forma à América Latina (onde o foco é o ciclo de reprodução da pobreza) ou à Ásia do Nordeste (onde o envelhecimento e a baixa fertilidade são centrais). A educação altamente seletiva e privatizada dos países do Leste Asiático evidencia que o desenvolvimento do conhecimento não implica automaticamente investimento público em capital humano.</p>
<p>§16 — Os <strong>regimes e estratégias de crescimento</strong> nacionais (Hassel &amp; Palier, 2021a, 2021b) também são fundamentais para compreender o tipo de qualificações demandado pelos empregadores e o tipo de provisão pública de qualificações. Há mais demanda por qualificações específicas em regiões que exportam manufatura de alta qualidade (Europa Continental, países Visegrád, Ásia do Nordeste) e por qualificações gerais em países onde os serviços dinâmicos têm papel central (países anglófonos, nórdicos e bálticos). Há baixa demanda por novas qualificações em países com sobrequalificação e descompasso no mercado de trabalho, como a Europa do Sul.</p>
<p>§17 — Em termos de provisão pública, encontra-se uma estratégia de criação de qualificações para todos (investimento inclusivo) e políticas de mobilização e preservação de qualificações para todos nos regimes de crescimento equilibrado dos países nórdicos. A abordagem é mais estratificada nos regimes de crescimento voltados à exportação de manufatura, característicos da Europa Continental dualizada (Avlijaš et al., 2021) e da Ásia do Nordeste.</p>
<p>§18 — Quanto à demanda e oferta de qualificações (Garritzmann et al., Volume I, Capítulo 8), o timing e a forma pela qual o investimento social se torna politizado dependem da relação entre demanda por qualificações (mudanças no mercado de trabalho) e oferta de qualificações (expansão educacional). Políticas de <em>criação</em> de qualificações são mais prováveis quando a oferta é baixa e especialmente quando a demanda supera a oferta. A <em>mobilização</em> é politizada quando a oferta existe mas não é bem conectada ao mercado de trabalho. A <em>preservação</em> emerge quando a oferta supera a demanda.</p>
<p>§19 — Os estudos regionais identificam quatro constelações. Primeiro, em contextos de forte demanda e forte oferta (Europa Nórdica), o que se politiza é a sustentabilidade do investimento social, especialmente seu caráter inclusivo. Segundo, em contextos de forte demanda mas fraca oferta (Europa Continental, Ásia do Nordeste), a politização foca na criação e mobilização de qualificações. Terceiro, em contextos de fraca demanda mas oferta comparativamente alta (teoria: mobilização e preservação), como a Europa do Sul — apenas a Espanha seguiu essa lógica antes das crises financeira e do Euro, enquanto Itália, Grécia e Portugal não expandiram o investimento social. Quarto, com fraca demanda e fraca oferta (América Latina), o investimento social não é mais saliente do que a compensação de bem-estar, e prevalece mais por iniciativa de políticos e burocratas (processo supply-driven).</p>
</section>
<section id="legados-de-bem-estar-2025" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="legados-de-bem-estar-2025">§17.1.1.3 — Legados de bem-estar [§20–§25]</h3>
<p>§20 — A análise dos legados de bem-estar (policy legacies) confirma e amplia a hipótese elaborada no Volume I: a questão-chave é se já ter um grande sistema compensatório de bem-estar inibe o desenvolvimento de políticas de investimento social. Os trade-offs entre compensação e investimento, em termos de direção da reforma e de restrições fiscais, identificados para os Estados de bem-estar maduros da Europa Ocidental, aplicam-se também em contextos muito diferentes de economias emergentes.</p>
<p>§21 — Nos países nórdicos, com legado de alto gasto tanto em bem-estar compensatório quanto investivo, confirma-se que todas as três funções estão presentes na agenda e no debate político. O principal desafio é a sustentabilidade de manter essas políticas universalmente. A classe média crescente e móvel considera a opção por políticas que permitiriam mais escolha ou menores encargos tributários. As políticas auto-reforçadoras (feedback effects) dos sistemas existentes são, no entanto, muito poderosas.</p>
<p>§22 — Em países que dependeram mais de políticas compensatórias no passado (Europa Continental, países mais desenvolvidos da América Latina, Ásia do Nordeste especialmente em termos de taxa de emprego feminina), o desafio comum é uma taxa de emprego relativamente fraca e/ou um mercado de trabalho segmentado ou dualizado. Esses legados criam tensão crescente com a demanda por trabalho qualificado e com as mudanças nos padrões de família e gênero. A politização do investimento social foca no acesso ao mercado de trabalho, no aumento da participação (especialmente de mulheres e outsiders) e na preservação de qualificações.</p>
<p>§23 — Na Ásia do Nordeste, o mercado de trabalho é muito rígido para trabalhadores em grandes empresas exportadoras, onde os trabalhadores são protegidos e a proteção social é generosamente provida no âmbito das firmas. O desenvolvimento demográfico é muito desfavorável. A mobilização do capital humano torna-se um desafio, especialmente a participação feminina no mercado de trabalho. A Coreia do Sul iniciou suas políticas de investimento social mais cedo do que o Japão e Taiwan porque seu sistema de pensões era menos desenvolvido.</p>
<p>§24 — Onde o legado é mais fraco em compensação e relativamente mais forte em investimento (países anglófonos liberais e países bálticos), a mobilização do capital humano não é o principal desafio. A ênfase relativa em investimento no passado e a relativa ausência de políticas compensatórias tendem a colocar o desenvolvimento de qualificações e a educação no centro do debate. Na maioria dos países da América Latina, com mercados de trabalho altamente fragmentados e Estados de bem-estar truncados, as políticas focam em atingir grupos socioeconômicos excluídos da proteção social (trabalhadores informais e seus filhos), priorizando a ruptura do ciclo intergeracional de pobreza.</p>
<p>§25 — Os países do Sul Europeu e Visegrád são os casos mais claros em que o foco crescente em políticas sociais compensatórias, associado à ausência de estratégias de crescimento que exijam mais e melhores qualificações (Avlijaš et al., 2021), impediu quase inteiramente o desenvolvimento de políticas de investimento social. Confirma-se também que o investimento social não é uma resposta automática a questões sociodemográficas específicas ou estruturas econômicas que criam demandas particulares — os processos de politização também são moldados pela oferta política (posições e mobilizações de atores).</p>
</section>
<section id="o-que-impulsiona-a-saliência-das-propostas-de-investimento-social-2629" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="o-que-impulsiona-a-saliência-das-propostas-de-investimento-social-2629">§17.1.1.4 — O que impulsiona a saliência das propostas de investimento social? [§26–§29]</h3>
<p>§26 — Quando o investimento social é um tópico saliente e “ruidoso” na agenda doméstica, a arena eleitoral de política de massas é a mais importante — processo demand-driven. Quando não é saliente, grupos de interesse e/ou burocratas e especialistas nacionais e internacionais são os atores mais relevantes — processo supply-driven (Culpepper, 2010). Na política de massas, é importante considerar não apenas governos e partidos políticos mas também a opinião pública e as atitudes nos respectivos eleitorados.</p>
<p>§27 — Busemeyer e Garritzmann (Capítulo 3 deste volume) argumentam que a saliência é condição necessária mas não suficiente para que a opinião pública afete as políticas. O segundo fator crucial é o grau de <strong>acordo</strong> do público sobre a direção das políticas. Se uma grande maioria concorda sobre um tema, a opinião pública é um fator poderoso (“loud politics”); mas se o público discorda sobre a direção da reforma, os partidos políticos dominam (“loud but noisy politics”). Esta distinção é importante para compreender por que países com saliência similar do tema do investimento social produzem resultados tão diferentes.</p>
<p>§28 — Duas condições são centrais para que o investimento social seja proeminente na opinião pública e saliente no debate público. Primeiro, a demanda política por políticas de investimento social é fortemente correlacionada com a existência e o tamanho de uma <strong>nova classe média educada</strong> (especialmente nos setores de serviços públicos e semipúblicos pós-industriais) (Beramendi et al., 2015; Häusermann &amp; Palier, 2017). O papel da classe média educada é também central para a política partidária: os partidos apoiam políticas de investimento social para atrair votos dessa classe. Segundo, é nos países que enfrentam novos riscos sociais (Europa Nórdica e Continental) ou envelhecimento (Europa Nórdica e Continental, Ásia do Nordeste) que essas questões se tornam salientes.</p>
<p>§29 — Na América Latina e na Europa do Sul e Oriental, as questões de investimento social foram muito menos salientes. Na Europa do Sul e Oriental, ou não há demanda societal ou econômica real por investimento social, ou a demanda por investimento social iguala a demanda por compensação social. Em todos os casos, a configuração concreta das propostas e reformas de investimento social depende em última instância das posições e interações dos atores sociais, econômicos, burocráticos e políticos.</p>
</section>
<section id="dinâmicas-de-formação-de-coalizões-e-tomada-de-decisão-3038" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="dinâmicas-de-formação-de-coalizões-e-tomada-de-decisão-3038">§17.1.2 — Dinâmicas de formação de coalizões e tomada de decisão [§30–§38]</h3>
<p>§30 — A Figure 17.2 (reprodução da Figure 16.2 do Volume I) resume os atores que são protagonistas do investimento social e para qual tipo de função: para a <em>criação</em> de qualificações, são protagonistas o Banco Mundial, sindicatos de professores, Ministérios da Educação, situações de baixa oferta mas alta demanda econômica de qualificações e altos níveis persistentes de pobreza; para a <em>mobilização</em>, partidos de centro-esquerda, opinião pública favorável e saliente, sindicatos inclusivos centralizados, a OCDE e a UE; para a <em>preservação</em>, partidos de centro-direita, Ministérios do Trabalho ou Assuntos Sociais, grupos de votantes femininos qualificados.</p>
<p>§31 — <strong>Partidos políticos e governos.</strong> O partidarismo importa em toda parte, ainda que de formas diferentes. Os partidos de esquerda são mais preocupados com questões de investimento social (em termos de classe e gênero) do que os partidos de direita, e empurram para reformas mais inclusivas. Os partidos de esquerda em geral são protagonistas consistentes do investimento social. Esse é o caso em quase toda parte: o investimento social foi historicamente associado a partidos social-democratas nos países nórdicos; na América Latina e na Coreia do Sul, a adoção de políticas de investimento social está claramente associada ao advento de governos de esquerda.</p>
<blockquote class="blockquote">
<p><strong>Nota 1:</strong> Os autores ressaltam que não há um forte trade-off entre uma esquerda protecionista e uma esquerda orientada ao investimento (Häusermann et al., 2021). O conflito dentro dos partidos de esquerda é menos importante do que ter a esquerda no governo como fator determinante para o desenvolvimento de políticas de investimento social. Quando na oposição mas representando uma ameaça eleitoral séria, a esquerda também dá impulso aos partidos de direita para adotarem políticas de investimento social (caso do Japão).</p>
</blockquote>
<p>§32 — Nem todos os partidos de esquerda perseguem a mesma estratégia. Os inspirados pelos “New Democrats” americanos, pelo “New Labour” britânico ou pelo SPD sob Schröder foram os principais protagonistas de uma virada de investimento social (focalizado ou estratificado) nos anos 1990 e início dos 2000, como parte de uma estratégia para conquistar o poder após anos na oposição. Na Europa do Sul, ao contrário, a esquerda geralmente não foi protagonista do investimento social: a única vez em que políticas de investimento social foram discutidas na Itália foi sob Renzi, um representante dos novos partidos de centro-esquerda. A esquerda é mais dividida nessa região e menos capaz de construir uma maioria que inclua a classe operária e tanto a velha quanto a nova classe média.</p>
<p>§33 — Os partidos de direita não necessariamente impedem o desenvolvimento do investimento social, mas condicionam seu tipo. Na Ásia do Nordeste, as reformas de investimento social aprovadas por partidos de direita foram geralmente orientadas para a eficiência econômica (Japão) ou distorcidas por valores socialmente conservadores (ECEC na Coreia do Sul). Na América Latina, os partidos de direita tendem a exigir CCTs mais condicionais ou investimento social mais estratificado. Na Europa Ocidental, os partidos de direita empurram para propostas de investimento social estratificado (CDU na Alemanha) ou de bem-estar chauvinista (populismo de direita nos países nórdicos).</p>
<p>§34 — Os autores distinguem três tipos de partidos conservadores: (a) a <strong>direita neoliberal</strong> (governos conservadores no Reino Unido, oposição no Chile/Brasil/Uruguai durante a “Maré Rosa”, governos neoliberais nos países bálticos, pequenos partidos liberais/pró-privatização nos países nórdicos) — opõe-se ao investimento social público em geral com base em políticas de austeridade e privatização; (b) a <strong>direita corporatista-conservadora</strong> (CDU-CSU na Alemanha, governos Berlusconi na Itália, conservadores na França, LDP no Japão, partido conservador coreano) — mais tolerante com gastos públicos, mas introduz reformas distorcidas que beneficiam desproporcionalmente as classes médias insiders, produzindo investimento social “estratificado”; (c) a <strong>nova direita populista radical</strong> — atende às necessidades de uma constituency mais velha, etnicamente majoritária, das classes operárias e médias baixas, apoiando políticas de consumo mais tradicionais combinadas com uma postura conservadora-identitária em questões de família e imigração (M5S/Liga na Itália, chauvinismo de bem-estar nos países nórdicos).</p>
<p>§35 — <strong>Posições dos atores sociais e econômicos.</strong> As atitudes de sindicatos e associações de empregadores são altamente contingentes ao contexto socioeconômico e institucional do país. Os sindicatos em geral apoiam o investimento social quando isso é consistente com os interesses de seus membros. Sindicatos do “setor central” (core sector) e sindicatos cujos membros têm a perder com uma virada de investimento social ou uma expansão mais inclusiva dos sistemas existentes geralmente se opõem a reformas inclusivas: caso do IG Metall na Alemanha em relação às reformas da formação profissional (VET), e dos sindicatos conservadores de professores alemães em relação à expansão e equalização educacional.</p>
<p>§36 — Os sindicatos podem apoiar políticas de investimento social se beneficiam seus membros (mecanismo que pode apoiar reformas estratificadas). Quando as políticas de investimento social existentes são bem estabelecidas mas apenas em setores centrais do mercado de trabalho, os sindicatos centrais defendem as políticas existentes mas se opõem à sua expansão para porções mais amplas da população. Se o movimento sindical é altamente centralizado, os sindicatos periféricos com maiores incentivos para apoiar o investimento social inclusivo têm maior visibilidade. Onde a informalidade do mercado de trabalho é alta (América Latina), os sindicatos tendem a defender os interesses dos “trabalhadores” como entidade única, adotando posturas mais inclusivas.</p>
<p>§37 — Quanto às associações de empregadores, quanto mais a economia se aproxima de uma base de conhecimento, mais as firmas tendem a se beneficiar de alto nível de investimento social e mais fortemente o apoiam. O tamanho das firmas importa: as grandes firmas endossam mais investimento social no âmbito da própria firma ou da indústria (economias coordenadas de mercado como Alemanha e Japão), enquanto países com predominância de pequenas firmas de alta intensidade de qualificação tendem a endossar mais o investimento social inclusivo desde que o Estado o financie. Nos países nórdicos, as firmas são centrais no contrato social de flexibilidade-segurança (<em>flexicurity</em>) que sustenta o investimento social financiado publicamente.</p>
<p>§38 — <strong>Coalizões societais e políticas.</strong> A nova classe média educada é o principal suporte do investimento social em muitos países. Porém, como sublinha Häusermann e Palier (2017), essa classe não é grande o suficiente para formar sozinha uma maioria capaz de fazer avançar políticas de investimento social. Há necessidade de coalizões. Conforme o contexto e os fatores detalhados, essas coalizões levarão a diferentes tipos de estratégia de investimento social. O capítulo apresenta brevemente os traços gerais dessas coalizões antes de aprofundá-las na Seção 17.3.</p>
</section>
</section>
<section id="seção-17.2-mapeando-e-explicando-o-desenvolvimento-das-políticas-de-investimento-social-por-região-pp.-419446" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="seção-17.2-mapeando-e-explicando-o-desenvolvimento-das-políticas-de-investimento-social-por-região-pp.-419446"><span class="header-section-number">3</span> Seção 17.2: Mapeando e Explicando o Desenvolvimento das Políticas de Investimento Social por Região (pp.&nbsp;419–446)</h2>
<section id="introdução-à-análise-regional-3940" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="introdução-à-análise-regional-3940">Introdução à análise regional [§39–§40]</h3>
<p>§39 — A seção aplica o framework teórico a cada uma das regiões estudadas no projeto WOPSI. A sequência é: (1) os três mundos ocidentais do regime de bem-estar (Nórdico, Continental/Bismarckiano, Anglo-Saxônico/Liberal); (2) a Europa do Sul como caso negativo; (3) a Europa Central e Oriental como demonstração de que legados comuns levam a trajetórias diferentes segundo as estratégias de crescimento e os atores; (4) a Ásia do Nordeste como caso de virada ao investimento social por parte de países conservadores; (5) a América Latina como conjunto de casos frequentemente negligenciado.</p>
<p>§40 — Em cada região, os autores sintetizam os achados em uma figura (17.3 a 17.11) que preenche as caixas do framework teórico (dinâmicas ideacionais, dinâmicas estruturais, dinâmicas de politização — oferta e demanda —, coalizões, legados, precondições institucionais) com as características específicas da região. Essas figuras funcionam como sínteses visuais das explicações causais configuracionais.</p>
</section>
<section id="os-três-mundos-ocidentais-do-investimento-social-4153" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="os-três-mundos-ocidentais-do-investimento-social-4153">Os três mundos ocidentais do investimento social [§41–§53]</h3>
<p>§41 — As políticas de criação, mobilização e preservação de habilidades humanas apareceram em todos os países da Europa Ocidental, embora de formas diferentes. Nos países <strong>nórdicos</strong>, essas políticas remontam aos anos 1930. Na <strong>Europa Continental</strong>, foram expandidas a partir dos anos 1990 e crescentemente no início dos anos 2000. Os países <strong>liberais anglófonos</strong> desenvolveram algumas políticas de investimento social precocemente (criação de qualificações), mas não desenvolveram uma estratégia abrangente de investimento social.</p>
<p>§42 — <em>Países nórdicos.</em> A tradição bem-estabelecida de universalismo de bem-estar em políticas compensatórias também aparece no investimento social: padrão principalmente inclusivo, entregue por meio de serviços públicos extensivos e de alta qualidade, relativamente igualitários em termos de classe e gênero. Mais recentemente, porém, há discussões sobre limitar a inclusividade das políticas à medida que os partidos populistas radicais de direita ganharam força eleitoral e empurraram por mais chauvinismo de bem-estar — especialmente às custas de pessoas com origens migrantes e minorias linguísticas (por exemplo, reforma do acesso ao crédito estudantil na Dinamarca, cortes em benefícios familiares após o terceiro filho). Pode-se falar assim de alguma “de-universalização” do investimento social nos países nórdicos.</p>
<p>§43 — <em>Europa Continental/Bismarckiana.</em> Ao contrário do que muitos observadores esperavam caracterizando esses Estados de bem-estar como “paisagens congeladas” (Esping-Andersen, 1996; Pierson, 2001), as reformas de investimento social ganharam saliência desde os anos 1990. Atenção particular foi dada à ativação (especialmente de mulheres e jovens) e à construção de qualificações para a economia do conhecimento. Em contraste com a abordagem inclusiva dos países nórdicos, porém, essas reformas assumiram frequentemente a forma de <strong>investimento social estratificado</strong>, cujos benefícios são muitas vezes capturados por aqueles já em melhor situação na sociedade (ou seja, membros das novas classes médias educadas). Os “efeitos Matthew” são particularmente evidentes nas reformas de ECEC na França e na Alemanha, que beneficiam desproporcionalmente mulheres e famílias de classe média.</p>
<p>§44 — Essas desigualdades exacerbam o já amplo fosso entre insiders e outsiders do mercado de trabalho (Emmenegger et al., 2012). A Alemanha é o caso paradigmático: o sistema de ECEC é amplamente fragmentado; incentivos negativos na forma de abono para mães que ficam em casa solapam a inclusividade do sistema; e a reforma do VET de 2004-2005, promovida pelo governo social-democrata-verde em resposta à escassez de vagas de aprendizagem de qualidade, encontrou oposição dos grandes sindicatos do setor metalúrgico (IG Metall), que se opuseram à expansão do sistema de aprendizagem para além do existente — o qual envolvia cooperação entre sindicatos, empregadores e o Estado na supervisão dos programas de aprendizagem.</p>
<p>§45 — <em>Países liberais anglófonos (Europa e América do Norte).</em> A virada ao investimento social foi mais parcial e mais inigualitária, com tendência mais forte de depender de serviços privados em áreas políticas-chave como ECEC, educação e cuidados de longa duração. O financiamento público geralmente se concentra na provisão de educação escolar e, em menor grau, na educação superior acadêmica, enquanto o engajamento público em todas as outras áreas de investimento social permanece muito limitado. O resultado são desigualdades educacionais, salariais e de riqueza extremamente elevadas e persistentes. As poucas políticas de investimento social introduzidas assumiram a forma de investimento social focalizado voltado para grupos marginalizados (crianças pobres, deficientes, grupos desfavorecidos — “affirmative action”).</p>
<p>§46 — No Reino Unido, embora o New Labour de Blair tivesse prometido colocar ênfase em “educação, educação, educação”, a tendência mais geral — especialmente desde o governo de coalizão Tories-Liberal Democrats de 2010 — foi de contenção, austeridade e liberalismo de mercado, com cortes tanto nas políticas compensatórias (benefícios de desemprego) quanto nas políticas de investimento social (programa Surestart de ECEC, sistema de aprendizagem). Na América do Norte, existe uma “curiosa disjunção” entre consideráveis investimentos públicos em educação primária, secundária e parte da educação superior acadêmica e o subdesenvolvimento de outras áreas de investimento social, especialmente programas públicos de ECEC. Os EUA são o único país desenvolvido sem um programa nacional de licença parental paga.</p>
<p>§47 — As explicações para as trajetórias dos três mundos ocidentais combinam fatores estruturais e políticos. No plano estrutural, a emergência dos “novos riscos sociais” e a crescente focalização em empregos intensivos em qualificações criaram novas demandas econômicas e públicas. A relação entre demanda e oferta de qualificações molda a politização de cada função: nos países nórdicos (forte demanda, forte oferta), o que se debate é a sustentabilidade do sistema inclusivo; na Europa Continental (forte demanda, fraca oferta), o foco é na criação e mobilização de qualificações; nos países liberais, o mercado privado trata do equilíbrio entre demanda e oferta.</p>
<p>§48 — O tipo de estratégia de crescimento também contribui para moldar as diferentes funções e perfis do investimento social. No modelo “equilibrado” nórdico (combinando capacidade exportadora de serviços dinâmicos e alto nível de consumo doméstico), o investimento social implica quase naturalmente qualificações para todos (criação e mobilização inclusivas) e políticas igualitárias de conciliação trabalho-família. Na estratégia de crescimento por exportação de manufatura da Europa Continental, encontra-se a dualização do investimento social: investir e proteger os já produtivos (“insiders”) e uma ativação relativamente dura para os demais (Palier &amp; Thelen, 2010). Nos países liberais, o investimento social complementar seria principalmente criação de qualificações e educação privada.</p>
<p>§49 — No plano dos legados e das coalizões, na Europa Continental e nos países anglófonos, o investimento social foi instalado somente depois que as políticas compensatórias já estavam estabelecidas há muitos anos. A introdução ou expansão do investimento social teve consequências para essas políticas, pois ambas competem por recursos financeiros. O investimento social veio frequentemente acompanhado de contenção ou recalibração das políticas compensatórias mais antigas. Nos países nórdicos, coalizões cross-class formaram-se desde cedo (trabalho + agricultores → trabalho + classe média), produzindo políticas inclusivas com poderosos efeitos de feedback positivo. Nos países anglófonos, a ausência de um forte movimento operário e de partidos de esquerda fortes explica por que esses países focaram no liberalismo de mercado e na privatização.</p>
<p>§50 — Na Europa Continental, o investimento social é moldado por coalizões entre a nova classe média educada e empregadores, que veem no investimento social um meio de crescimento econômico. A forte demanda por qualificações e a crescente demanda econômica e social por maior participação feminina no mercado de trabalho criaram uma opinião pública favorável, apoiada por sindicatos e empregadores. Isso deu incentivos aos parlamentares para introduzir e expandir políticas de investimento social, especialmente em política familiar, ECEC e ALMPs. Os partidos democrata-cristãos e de centro-direita (frequentemente governantes nesse grupo) viram nisso uma oportunidade de apelar ao “voto feminino”. Isso também explica por que as políticas de investimento social assumiram uma forma estratificada: os partidos de centro-direita visaram ao eleitorado de classe (nova) média, sem se preocupar muito com os efeitos redistributivos.</p>
</section>
<section id="a-europa-do-sul-protecionismo-social-em-vez-de-investimento-social-5158" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-europa-do-sul-protecionismo-social-em-vez-de-investimento-social-5158">A Europa do Sul: protecionismo social em vez de investimento social [§51–§58]</h3>
<p>§51 — Na maioria dos países da Europa do Sul (Itália, Grécia, Espanha, Portugal), as políticas de investimento social apareceram de forma bastante eclética e não é possível identificar uma “virada” ao investimento social. Os Estados de bem-estar mediterrâneos permanecem altamente focados em políticas compensatórias (especialmente pensões), protegendo principalmente os trabalhadores do sexo masculino, enquanto a participação feminina no mercado de trabalho continua baixa. Podem-se distinguir dois padrões: na Espanha e (em menor grau) em Portugal, programas com clara orientação de investimento social foram adotados na primeira década dos anos 2000 (o programa “Educa3” na Espanha em 2006, que aumentou as provisões de ECEC para crianças com menos de 3 anos). Essa tendência, porém, foi interrompida pelas crises financeira e do Euro, que levaram à consolidação fiscal.</p>
<p>§52 — A Itália nunca realizou nenhuma tentativa séria de estabelecer investimentos sociais (como tampouco o fez a Grécia). A falta de investimento social italiano precede em muito a crise financeira, o que sinaliza que a austeridade não é responsável pela ausência de adesão do país. Mesmo depois da crise, as pressões de consolidação fiscal foram menos severas na Itália do que na Espanha e Portugal, e mesmo assim a Itália não tentou nenhuma medida significativa na direção de mais investimento social (exceto uma tentativa malsucedida sob Renzi, com a reforma <em>Buona Scuola</em> em 2015, que estendeu programas de trabalho-estudo a trilhas não vocacionais do ensino médio e que foi fortemente criticada por sindicatos e pela minoria “esquerdista” dentro da coalizão governamental). Em vez do investimento social, o governo Renzi tentou uma estratégia de desregulamentação do mercado de trabalho orientada para o crescimento mais compensação social — uma tentativa de deter a desagregação percebida da maioria governamental sob o avanço do M5S nas pesquisas.</p>
<p>§53 — As principais explicações para o impasse da Europa do Sul referem-se ao legado de bem-estar e ao pequeno tamanho da classe média educada. As caras políticas de pensões impedem os formuladores de política de recalibrar os Estados de bem-estar. Os principais atores que defendem os sistemas compensatórios industrialistas ainda são poderosos, enquanto os potenciais novos atores políticos permanecem fracos. Em Itália (e na maior parte da Europa do Sul), a classe média educada é pequena e foi negativamente afetada pela estagnação econômica. A demanda por investimento social foi assim ambígua e bastante marginal em comparação com a forte oposição às reduções no bem-estar compensatório, que veio das classes operárias e de partes das classes médias empobrecidas. A tentativa malsucedida de Renzi ilustra bem como, mesmo com uma morfologia social parecida com a de uma coalizão de investimento social, a ausência de demanda pública saliente pode inviabilizar a reforma.</p>
</section>
<section id="a-europa-central-e-oriental-laggards-e-divergência-interna-5463" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-europa-central-e-oriental-laggards-e-divergência-interna-5463">A Europa Central e Oriental: laggards e divergência interna [§54–§63]</h3>
<p>§54 — Entre os países da Europa Central e Oriental, o projeto analisa os países bálticos (Estônia, Letônia e Lituânia) e o grupo de Visegrád (República Tcheca, Hungria, Polônia e Eslováquia). As políticas de investimento social nesses países são muito menos desenvolvidas do que na Europa Ocidental, mas existem diferenças importantes entre os grupos e entre áreas de política. Os países bálticos avançaram muito mais no desenvolvimento de políticas de investimento social (especialmente na criação de qualificações) do que os países Visegrád.</p>
<p>§55 — <em>Países bálticos.</em> Fornecem apenas benefícios sociais residuais em termos compensatórios, mas são mais ativos no desenvolvimento de investimentos sociais. A estratégia concentra-se em promover educação pública universal e abrangente (do pré-escolar ao ensino médio); a maioria das outras áreas de política de investimento social é muito menos desenvolvida e geralmente estratificada. Também possuem generosos esquemas de licença parental e alguns ALMPs limitados, principalmente focalizados. Enquanto os três países bálticos desenvolveram políticas de investimento social amplamente similares, há diferenças entre países: a Lituânia, por exemplo, permaneceu mais agrária e avançou menos em direção a uma economia focada em educação e TIC (tecnologia da informação e comunicação).</p>
<p>§56 — <em>Países Visegrád.</em> Assemelham-se aos tradicionais Estados de bem-estar corporatistas-conservadores da Europa Continental. Suas políticas sociais são fortemente inclinadas para a compensação social; os investimentos sociais permanecem largamente ausentes. Szelewa e Polakowski (Capítulo 8) os classificam como “laggards de investimento social” e caracterizam o investimento social aqui como um “não-tema” político. Após o colapso do bloco soviético, engajaram-se em desinvestimento e refamilialização nos anos 1990. No início dos anos 2000, houve alguma expansão limitada de ALMPs financiada em grande medida pelo Fundo Social Europeu. Desde 2004, porém, entraram em período de “re-politização” à medida que partidos de direita radicais populistas ganharam força eleitoral e desafiaram abertamente as políticas de investimento social e sua imagem associada de modernidade.</p>
<p>§57 — <strong>Os legados comuns e sua divergência.</strong> Todos os países da Europa Central e Oriental partilham uma história política soviética comum, mas não idêntica. Enquanto os países bálticos estavam sob controle muito próximo e direto como parte da União Soviética, os países Visegrád como estados satélites tinham certa autonomia. Essas diferenças pré-existentes influenciaram a forma como os países se reformaram após o colapso do bloco soviético: os países bálticos escolheram uma ruptura rápida e clara com o passado soviético, abrindo rapidamente seus mercados à globalização e retraindo as políticas compensatórias existentes; nos países Visegrád, a mudança foi muito mais gradual. As taxas de sindicalização caíram dramaticamente nos países bálticos, enquanto no grupo Visegrád o declínio na filiação sindical foi muito mais lento e gradual.</p>
<p>§58 — <strong>Estratégias de crescimento econômico divergentes.</strong> As elites político-econômicas domésticas desempenharam papel crucial na modelagem das diferentes reformas de bem-estar. Os formuladores de política nos países bálticos escolheram uma estratégia de crescimento baseada em qualificações, tecnologia e expansão do setor de serviços, complementada por investimento em e expansão da educação pública. Nos países Visegrád, ao contrário, a orientação foi a (re)industrialização, especialmente a manufatura avançada e complexa (Bohle &amp; Greskovits, 2012). Esses países não perceberam grande necessidade de políticas abrangentes de investimento social, mas focaram em políticas compensatórias para compensar financeiramente e politicamente os perdedores das reformas. O desenvolvimento em direção à refamilialização foi também parcialmente devido à escolha da manufatura como principal motor de crescimento: os homens foram priorizados sobre as mulheres na manufatura avançada, levando ao declínio nos níveis de participação feminina no mercado de trabalho.</p>
<p>§59 — <strong>A opinião pública e os parceiros sociais.</strong> Nos países bálticos, a opinião pública foi geralmente liberal-conservadora (algo mais inclinada à esquerda na Lituânia mais agrária), preferindo um Estado de bem-estar compensatório enxuto e políticas compensatórias residuais, exceto quando se trata de educação e formação de qualificações. Sindicatos relativamente fracos (devido à ruptura radical com o legado de filiação obrigatória) e associações patronais relativamente fortes que favoreciam um Estado de bem-estar enxuto reforçaram esse desenvolvimento. Os países bálticos expandiram alguns ALMPs principalmente por pressão e financiamento da UE.</p>
<p>§60 — Nos países Visegrád, o principal argumento de Szelewa e Polakowski é que nenhum ator socioeconômico ou político vocal tinha interesse em expandir os investimentos sociais. Três períodos podem ser distinguidos: (1) após o colapso do bloco oriental, a refamilialização emergiu como um novo direito social e liberdade — o que do ponto de vista da Europa Ocidental parece um “retrocesso conservador” foi percebido como um passo “progressista” na visão de muitos na Europa Central e Oriental, pois as famílias com dois provedores de renda eram a norma antes de 1990; (2) após a adesão à UE em 2004, os países Visegrád desenvolveram ALMPs limitados — mas sem salvar politicamente a questão —, principalmente porque a UE os financiou e promoveu via o Método Aberto de Coordenação; (3) com a ascensão política da direita populista radical, os poucos ALMPs existentes ficaram sob pressão porque esses partidos de direita se opõem à imagem “progressista e liberal” de família associada à perspectiva de investimento social, comparando os esforços de influência da UE à experiência anterior sob o domínio comunista.</p>
</section>
<section id="ásia-do-nordeste-a-virada-ao-investimento-social-estratificado-6168" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ásia-do-nordeste-a-virada-ao-investimento-social-estratificado-6168">Ásia do Nordeste: a virada ao investimento social estratificado [§61–§68]</h3>
<p>§61 — O Japão, Taiwan e a Coreia do Sul são países desenvolvidos com níveis relativamente baixos de gasto social público. Desde o final dos anos 1990, porém, os gastos com pensões e saúde aumentaram rapidamente, sobretudo em razão do envelhecimento da população. Os três países também desenvolveram políticas de creche e família, com o objetivo explícito de mobilizar mulheres para ingressar no mercado de trabalho. Todos esses esforços permanecem bastante estratificados. A virada ao investimento social foi mais explícita na Coreia, com o presidente Roh Moo-hyun (2003-2007) usando a noção de investimento social em sua agenda política; os dois governos conservadores subsequentes continuaram na mesma linha, e Moon Jae-in, eleito em 2017, reiterou essa orientação.</p>
<p>§62 — O investimento social na Ásia do Nordeste é menos voltado à criação de capital humano e qualificações do que à mobilização das mulheres para entrar no mercado de trabalho. Os países parecem muito menos interessados em retornos futuros em termos de conhecimento e integração social do que no aumento das taxas de participação laboral. O objetivo principal é enfrentar os desafios de uma sociedade envelhecida promovendo maior fertilidade (por meio de investimentos em abonos de filho e creches) e aumentando as taxas de participação no mercado de trabalho, incluindo o emprego feminino.</p>
<p>§63 — Os sistemas de proteção social pública não se desenvolveram significativamente nesses países, pois a proteção social baseada na empresa, o emprego masculino vitalício, o familialismo e o modelo do homem provedor predominaram. O gasto em pensões e saúde foi inclinado para os idosos nos anos 1990, enquanto os gastos em educação e políticas de família permaneceram relativamente baixos. Mesmo com um nível geral de gasto baixo, a razão entre políticas compensatórias e políticas de investimento social fortemente favoreceu as compensatórias no Japão e em Taiwan até meados dos anos 2010. Contudo, no início dos anos 2000, a Coreia começou a desenvolver mais políticas de investimento social — beneficiando-se de um sistema de pensões mais recente (estabelecido apenas em 1988) e, portanto, de um legado de política prévia mais leve.</p>
<p>§64 — <strong>A demanda por investimento social em sociedades envelhecidas.</strong> Segundo os autores (Shim, Capítulo 10), as questões de investimento social que ganharam saliência legislativa e midiática em todos os três países são em grande medida voltadas para eleitores em geral e aparecem principalmente como questões de valência orientadas para resolver os problemas de uma sociedade envelhecida e da crise de baixa fertilidade — e muito menos relacionadas à economia do conhecimento e à criação de capital humano. O sistema de educação altamente seletivo e em grande parte privatizado (especialmente no Japão e na Coreia) tornou-se tão arraigado e produziu efeitos de reforço tão poderosos que quase ninguém se opõe à provisão privada de educação (superior), às altas mensalidades e aos baixos gastos públicos.</p>
<p>§65 — A virada do Japão ao investimento social foi desencadeada pelo “choque de 1,57” quando a taxa de fertilidade caiu em 1989 ao seu nível mais baixo desde 1966. Mesmo com a taxa continuando a cair até por volta de 2005, levou tempo para o governo japonês realmente avançar rumo a serviços e políticas de investimento social. Em 2007, o governo redefiniu o problema de “declínio da taxa de natalidade” para “declínio da população”. Somente ao reconhecer o declínio da população o governo percebeu a necessidade de manter as mulheres no mercado de trabalho. A virada do investimento social japonês foi silenciosa e lenta, enquanto a Coreia mostrou uma mudança radical na política de família desde a metade dos anos 2000.</p>
<p>§66 — <strong>O papel do sistema partidário e da competição política.</strong> O que é notável é que o legado do Estado desenvolvimentista não parece ser tão importante para compreender o desenvolvimento do investimento social na Ásia do Nordeste quanto se poderia esperar. Os três países são Estados desenvolvimentistas, mas não introduziram políticas de investimento social até recentemente, e seus caminhos para o investimento social diferiram. Uma razão é que o Estado desenvolvimentista estava fortemente baseado no familialismo e no modelo do homem provedor e considerava as funções de cuidado e bem-estar como responsabilidade das mulheres e famílias. Na Coreia, Lee e Kim (Capítulo 13) sugerem que o legado desenvolvimentista foi de fato mais hostil do que favorável à virada ao investimento social — o mantra político “crescimento econômico primeiro, distribuição depois” tornava a própria ideia de política de bem-estar social impopular entre os formuladores de política e a opinião pública.</p>
<p>§67 — As diferenças nos caminhos para o investimento social entre os três países podem ser explicadas por seus sistemas políticos — em particular o sistema partidário e o tipo de competição política. No Japão, até recentemente, havia quase nenhuma conexão entre eleições e governos, com o mesmo partido no poder mas com governos altamente instáveis. A dominância do partido conservador (LDP) e sua orientação política, apesar das mudanças de liderança, levou à natureza parcial e estratificadora do investimento social. Isso distingue o Japão da Coreia, onde a política competitiva importou muito mais: havia dois campos de longa data, e assim foi mais fácil passar da politização ou agenda para a tomada de decisão e implementação. Nas disputas em distritos competitivos ao redor de Seoul, habitados principalmente por eleitores mais jovens e progressistas, moldaram-se batalhas políticas que eventualmente promoveram aumentos relativamente drásticos nos gastos com ECEC.</p>
<p>§68 — Shim (Capítulo 10) mostra que a afiliação partidária individual de um legislador não determina se um projeto de lei de investimento social é introduzido. Contudo, ao examinar a escolha do tipo de estratégia de investimento social proposta, o efeito do partidarismo é claro: partidos de esquerda tendem a enfatizar objetivos sociais sobre econômicos e a priorizar a criação e preservação de qualificações sobre a mobilização. Governos conservadores — que dominam a vida política nos três países — enfatizam as políticas de mobilização. Muito frequentemente, governos de direita foram empurrados a propor políticas de investimento social pela pressão vinda da oposição.</p>
</section>
<section id="américa-latina-capacidades-diferenciadas-para-o-investimento-social-6978" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="américa-latina-capacidades-diferenciadas-para-o-investimento-social-6978">América Latina: capacidades diferenciadas para o investimento social [§69–§78]</h3>
<p>§69 — Para a América Latina, pode-se falar de uma clara tendência geral de expansão das políticas de investimento social a partir do início dos anos 1990, acelerando-se após a primeira década dos anos 2000. O foco desta expansão recaiu principalmente sobre a criação e preservação de capital humano — saúde e educação (VET, bem como educação pós-secundária e terciária) — e sobre a expansão dos programas de CCT. Durante os anos 2010, programas de ECEC também foram expandidos em vários países.</p>
<p>§70 — Ao contrário da Europa Ocidental, não há uma “virada” ao investimento social em detrimento das políticas compensatórias. Nos Estados de bem-estar geralmente pouco desenvolvidos, fragmentados e truncados da América Latina, o foco da expansão do bem-estar foi geralmente na melhoria da segurança social para as classes mais baixas — em particular as pessoas que trabalham no setor informal. Esse objetivo foi perseguido tanto por meio de políticas de compensação ou transferência de renda quanto por meio de políticas de investimento social. Bogliaccini e Madariaga (Capítulo 7, Volume I) mostram que a generosidade do investimento social e da compensação social parecem positivamente correlacionadas. Ao contrário da Europa, portanto, não existe uma divisão consistente de classe, com as classes baixas apoiando mais a compensação social e as classes altas apoiando mais o investimento social.</p>
<p>§71 — O tipo principal de reforma de investimento social na América Latina é baseado no <strong>investimento social focalizado</strong>, especialmente na forma de CCTs — transferências condicionadas de renda para famílias pobres usualmente condicionadas ao envio dos filhos à escola e/ou a checkups de saúde. O propósito original dessas políticas era atingir a força de trabalho informal (25% a 50% da força de trabalho, dependendo do país), com o duplo objetivo de alívio da pobreza e desenvolvimento do capital humano e qualificações para evitar a reprodução intergeracional da pobreza.</p>
<p>§72 — Os autores distinguem dois grupos de países. O grupo mais desenvolvido (Brasil, Chile, Argentina, Costa Rica e Uruguai — com o México desenvolvendo também um forte programa de CCT) observou o desenvolvimento mais forte do investimento social, notavelmente em educação, saúde e CCTs. No grupo menos desenvolvido (Peru, Bolívia, Guatemala, Nicarágua, Honduras), os países implementaram programas de CCT, mas geralmente sem integrá-los em uma estratégia abrangente de expansão dos serviços correspondentes. Nesses casos, os programas de CCT foram mantidos em baixos níveis de benefício e geralmente careciam de capacidades para monitorar efetivamente a condicionalidade.</p>
<p>§73 — A <strong>efetividade da condicionalidade</strong> e a capacidade de fornecer serviços ligados aos programas de CCT são fundamentais. É somente com serviços médicos ou educativos funcionando que os programas de CCT podem promover capacidades humanas. Em contraste, a ênfase do programa de CCT uruguaio não estava no investimento mas na transferência de renda — as condições eram puramente formais, sem disposições para monitoramento ou sanção em caso de não cumprimento. No Brasil, Argentina e México, os programas envolveram requisitos detalhados verificados de perto e monitorados continuamente. Em outros casos, o foco no desenvolvimento de capital humano estava ausente mesmo quando alguns serviços eram fornecidos: o programa mexicano <em>Estancias</em>, por exemplo, simplesmente visava expandir instalações de creche para que mães de baixa renda pudessem trabalhar, sem consideração pela qualidade do cuidado para as crianças ou pelo bom emprego para as mães.</p>
<p>§74 — A relativa fraqueza ou ausência de clientelismo também é necessária. A quebra de relações patrão-cliente foi um objetivo central do design do programa de CCT brasileiro (<em>Bolsa Família</em>), bem como de programas similares na Bolívia e no Peru. Onde isso não foi bem-sucedido (ex.: Honduras) ou onde sindicatos fortes conseguiram apropriar os ganhos da expansão educacional (ex.: México), os aspectos investivos foram solapados.</p>
<p>§75 — <strong>Explicando a política do investimento social na América Latina.</strong> O desenvolvimento do investimento social precisa ser entendido como uma reação às consequências sociais negativas do neoliberalismo. O papel das organizações internacionais (Banco Mundial, CEPAL, BID) parece mais uma condição de fundo do que um fator explicativo — em vez de empurrar políticas de fora, as organizações reforçaram os atores políticos domésticos. Em cada país, é possível localizar as forças políticas domésticas que empurraram por políticas de investimento social.</p>
<p>§76 — Os <strong>legados institucionais</strong> importaram de três maneiras. Primeiro, moldaram a natureza dos problemas endereçados via iniciativas de investimento social (foco na força de trabalho informal e nos pobres). Segundo, o clientelismo e a falta de capacidade estatal são razões importantes pelas quais os países menos avançados foram geralmente menos capazes de desenvolver programas de investimento social efetivos. Terceiro, os legados estabeleceram atores políticos que podem se opor às reformas, como os sindicatos de professores no Uruguai e no México ou os provedores privados no Chile e no México.</p>
<p>§77 — O <strong>poder explanatório mais importante</strong> para o desenvolvimento variado do investimento social nos países mais avançados da América Latina reside na dinâmica política doméstica. Os governos aparecem como os protagonistas mais importantes do investimento social — em apenas dois casos (movimento <em>sanitaristas</em> na saúde brasileira e movimento estudantil no Chile) atores de movimentos sociais foram mencionados como importantes protagonistas de iniciativas de investimento social. Nem sindicatos nem associações empresariais aparecem como protagonistas importantes.</p>
<p>§78 — A <strong>composição partidária dos governos</strong> também fez uma diferença importante. Governos de esquerda em todos os países latino-americanos analisados mostraram comprometimento com a redução da pobreza e com a expansão da provisão de bem-estar para toda a população, reduzindo a desigualdade em qualidade e acesso. Por contraste, o governo de direita no México perseguiu apenas uma expansão focalizada dos serviços de saúde e ECEC, contribuindo para a solidificação de um sistema fortemente estratificado e dualizado. No grupo menos avançado, burocratas e tecnocratas tiveram papel comparativamente maior — em Peru, tecno-burocratas com conexões internacionais desenvolveram o programa de CCT (para trabalhar contra estruturas clientelistas), com completo desrespeito pelos programas existentes e em oposição a grande parte da política doméstica, o que eventualmente prejudicou sua implementação efetiva.</p>
</section>
</section>
<section id="seção-17.3-as-cinco-coalizões-societais-e-políticas-por-trás-das-cinco-estratégias-de-reforma-pp.-446467" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="seção-17.3-as-cinco-coalizões-societais-e-políticas-por-trás-das-cinco-estratégias-de-reforma-pp.-446467"><span class="header-section-number">4</span> Seção 17.3: As Cinco Coalizões Societais e Políticas por Trás das Cinco Estratégias de Reforma (pp.&nbsp;446–467)</h2>
<section id="enquadramento-as-cinco-estratégias-e-a-tipologia-das-coalizões-7986" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enquadramento-as-cinco-estratégias-e-a-tipologia-das-coalizões-7986">§17.3 — Enquadramento: as cinco estratégias e a tipologia das coalizões [§79–§86]</h3>
<p>§79 — O projeto WOPSI identificou, teoricamente, seis tipos principais de estratégias de reforma do Estado de bem-estar: três estratégias de investimento social (“inclusivo”, “estratificado” e “focalizado”) e três alternativas sem componente de investimento social (“liberalismo de mercado”, “protecionismo social” e “estratégias de renda básica”). Após a revisão dos casos empíricos dos dois volumes, os autores concluem que existem na prática <strong>cinco</strong> tipos principais — quatro com investimento social e um sem nenhuma componente.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>As cinco estratégias de reforma e as cinco coalizões correspondentes:</strong></p>
<ol type="1">
<li>Investimento social <strong>inclusivo</strong> → Coalizão social-democrática pró-classe média (países nórdicos)</li>
<li>Investimento social <strong>estratificado</strong> → Coalizão conservadora-corporatista (Europa Continental, Ásia do Nordeste)</li>
<li>Liberalismo de mercado + investimento social focalizado <strong>substitutivo</strong> → Coalizão liberal “Terceira Via” (países anglófonos)</li>
<li>Investimento social focalizado <strong>integrativo</strong> → Coalizão social-democrática pró-pobre (América Latina)</li>
<li><strong>Protecionismo social</strong> (ausência de investimento) → Coalizão protecionista social (Europa do Sul, Visegrád)</li>
</ol>
</div>
</div>
<p>§80 — O que os estudos de caso empíricos acrescentam ao esperado é que o escopo e o significado do investimento social focalizado podem diferir dependendo do tipo de outras reformas com as quais é combinado. Em alguns contextos, o investimento social focalizado aparece como complemento ao seguro social compensatório existente ou em desenvolvimento — quando este não consegue alcançar um segmento importante da população (casos da América Latina). Nesse caso, é chamado de <strong>investimento social focalizado integrativo</strong>: é usado para integrar na proteção pública uma população geralmente excluída, seja por pobreza extrema ou informalidade laboral.</p>
<p>§81 — Em outros contextos, o investimento social focalizado não é complementar mas <strong>substitutivo</strong>. É usado para substituir a assistência social existente. Nesse caso, o investimento social focalizado substitui transferências de assistência social anteriores incondicionais para populações excluídas e pobres. O objetivo dessa modalidade é ativar essas populações e mercantilizar (commodify) suas capacidades de trabalho sem prestar muita atenção à qualidade dos empregos ou ao conteúdo ou melhoria das qualificações. Os estudos de caso mostram que esse “investimento social focalizado substitutivo” é geralmente associado à estratégia de reforma do Estado de bem-estar do “liberalismo de mercado” (países anglófonos liberais), que inclui de fato algum investimento social principalmente com o objetivo de mobilização.</p>
<p>§82 — Confirma-se também que o investimento social está ausente em grande parte da Europa do Sul e dos países Visegrád da Europa Oriental — a estratégia dominante nesses casos é o protecionismo social. Finalmente, os autores <strong>não encontraram nenhum caso existente de renda básica universal incondicional</strong>. Algumas experiências foram desenvolvidas (Finlândia no final dos anos 2010) sem qualquer esforço de escalonamento. A Itália afirma ter implementado parcialmente a ideia com o <em>reddito di cittadinanza</em> de 2019, mas é mais um benefício sujeito a condicionamento de rendimento (means-tested) condicionado à busca de emprego.</p>
<p>§83 — O que mais interessa são as <strong>coalizões políticas</strong> por trás dessas estratégias. O tamanho e o comportamento político da <strong>classe média educada</strong> em interação com os legados institucionais (prevalência da compensação social) são cruciais para compreender por que uma estratégia prevalece sobre as outras. A classe média educada é principalmente representada por partidos de esquerda (social-democratas, verdes ou liberais sociais, dependendo do país). Seu tamanho varia muito entre países — nos países nórdicos, as pessoas com emprego em ocupações de serviço interpessoal representam cerca de um quarto da força de trabalho, enquanto o mesmo grupo permanece bem abaixo de 10% nos países da Europa do Sul (Beramendi et al., 2015).</p>
<p>§84 — Mesmo nos países nórdicos, essa classe geralmente não é grande nem forte o suficiente para carregar sozinha uma reorientação da política. Onde a classe média educada atinge determinado tamanho, ela entra em coalizões cross-class para avançar sua agenda. São identificadas duas coalizões principais em que a classe média educada é pivô: uma aliança classe média–negócios e uma aliança classe média–classe operária. Dependendo das condições socioeconômicas, do legado de bem-estar, da saliência e da política partidária, cada tipo de coalizão leva a diferentes tipos de estratégia de reforma do Estado de bem-estar.</p>
<p>§85 — A classe média educada nem sempre é grande o suficiente para construir e liderar uma coalizão de reforma de bem-estar. Em países onde ela é pequena, diferentes tipos de coalizões emergirão, em que grupos sociais diferentes atuam como constituency pivô. São identificadas duas dessas coalizões, ambas girando em torno das classes operárias e médias inferiores (industriais) como classes pivô. Onde a classe operária se alia com a emergente classe média educada, o resultado é uma coalizão social-democrática pró-pobre, desenvolvendo investimento social focalizado integrativo (América Latina). Ao contrário, se a coalizão emerge entre a classe operária, a classe média inferior (industrial) e os negócios (pequenas firmas), prevalece o protecionismo social com pouco ou nenhum investimento social.</p>
<p>§86 — A Figure 17.12 sintetiza todas as cinco coalizões em termos de: (i) classe pivô (classe média educada ou classes operárias e médias inferiores); (ii) classe aliada (classe operária e classes médias inferiores, ou comunidade de negócios); (iii) nome da coalizão; (iv) estratégia de reforma de Estado de bem-estar; (v) casos regionais. A figura é apresentada como a principal contribuição teórica do capítulo ao projeto WOPSI.</p>
</section>
<section id="as-duas-coalizões-social-democráticas-8795" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="as-duas-coalizões-social-democráticas-8795">§17.3.1 — As duas coalizões social-democráticas [§87–§95]</h3>
<p>§87 — Os autores identificam dois tipos de coalizões social-democráticas potenciais, que se formam quando a classe média educada (concentrada principalmente em ocupações de serviço interpessoal e cognitivo) se engaja em compromissos políticos com a classe operária em torno de uma agenda de provisão universalista de bem-estar. Isso não precisa necessariamente ser centrado em um programa de investimento social, mas tenderá a incluí-lo desde que a classe média o demande, em linha com seus interesses e valores. Também é necessário que o investimento social seja enquadrado como uma política que também beneficia e mobiliza as classes mais baixas.</p>
<p>§88 — Isso depende, por um lado, da natureza da classe média (quão “nova” e “educada” é) e do nível de proximidade do país com uma economia do conhecimento. Por outro lado, depende também da medida em que o investimento social é politizado como uma estratégia de crescimento inclusivo. Os dois tipos de coalizão social-democrática partilham como característica definidora que o investimento social será concebido como um meio tanto de crescimento econômico quanto de inclusão social.</p>
<p>§89 — A coalizão social-democrática emergirá provavelmente em países onde as novas classes médias educadas e as classes operárias (ou “inferiores”) em geral serão grandes o suficiente juntas para constituir uma maioria eleitoral e estarão abertas a se aliar em um programa de investimento social inclusivo. Isso pode implicar: (1) a nova classe média é grande o suficiente para ser uma constituency eleitoral poderosa e está comprometida com uma agenda de investimento social inclusivo em torno da qual uma aliança com as classes “inferiores” pode ser cimentada (países nórdicos); ou (2) mesmo na ausência de uma nova classe média educada considerável, as classes “inferiores” são apresentadas com uma estratégia de política social investidora que preferem sobre, ou ao menos valorizam tanto quanto, uma expansão dos instrumentos de compensação social (América Latina).</p>
<p>§90 — Vemos assim coalizões social-democráticas emergindo em ambas as extremidades do espectro de desenvolvimento: tanto nos maduros e ricos Estados de bem-estar pós-compensatórios, com uma grande classe média baseada na economia do conhecimento, quanto nas democracias emergentes, onde os legados compensatórios são ausentes ou de influência mínima e onde as classes operárias têm a ganhar com uma estratégia geral de crescimento inclusivo.</p>
<p>§91 — <strong>Coalizão social-democrática nórdica e investimento social inclusivo.</strong> O principal exemplo empírico é o dos países nórdicos, onde as alianças formativas precoces entre o movimento trabalhista e os agricultores evoluíram para abranger os partidos moderados ou liberais, engrenando uma constituency cross-class em apoio ao bem-estar universalista. O acesso aos serviços públicos e a cobertura do seguro foram universalizados, e os riscos sociais foram compartilhados por toda a sociedade. Ao mesmo tempo, foi dado forte ênfase à qualidade dos serviços públicos orientados ao investimento social (especialmente educação) e aos empregos associados. Essa expansão do bem-estar contribuiu para o alargamento da classe média e para o reforço de seu comprometimento com o Estado de bem-estar universal.</p>
<p>§92 — A coalizão social-democrática nórdica conduz no conjunto a políticas de investimento social inclusivo orientadas para as três funções (criação, mobilização e preservação de capital humano). A ameaça principal à estabilidade da coalizão é que a classe média educada retire seu apoio à agenda inclusiva e comece a apoiar um sistema de bem-estar mais estratificado ou mesmo privatizado — cálculo em que baseiam suas estratégias eleitorais partidos como o Liberal Alliance dinamarquês. Contudo, mesmo após a crise econômica de 2008 e a emergência de grupos políticos populistas, a coalizão social-democrática nórdica demonstrou notável resiliência, como evidenciado pela vitória do “bloco vermelho” nas eleições dinamarquesas de 2019 e pelo desempenho dos partidos social-democratas nas eleições suecas de 2018.</p>
<p>§93 — <strong>Coalizão social-democrática na América Latina e investimento social focalizado.</strong> A segunda manifestação é a coalizão social-democrática pró-pobre, observável na América Latina nos finais dos anos 1990 e início dos anos 2000, e na Espanha e Portugal entre o estabelecimento dos regimes democráticos e a crise econômica de 2008 (especialmente na década da “Estratégia de Lisboa”). A grande diferença em relação ao caso nórdico é que a classe média desempenha um papel muito mais marginal, refletindo o estágio de desenvolvimento geralmente menos maduro dessas economias — caracterizável como “fordismo incompleto” e subdesenvolvimento da economia baseada no conhecimento.</p>
<p>§94 — São as classes “inferiores” — a classe operária mais o setor informal na América Latina — que formam a espinha dorsal desse tipo de coalizão, com a (pequena) classe média urbana educada sendo relativamente marginal aos cálculos eleitorais dos partidos social-democratas que geralmente lideram tal coalizão. O investimento social na América Latina não emergiu como uma “virada” em detrimento das políticas orientadas à compensação, mas veio no contexto de uma expansão geral do Estado de bem-estar — como expansões de saúde no Brasil e no Chile, e expansão educacional na Colômbia. Os programas de CCT tornaram-se instrumentos de política extremamente populares, e a aliança entre as pequenas classes médias urbanas e as classes operárias é cimentada pela capacidade do governo de expandir políticas que beneficiam ambos os grupos sociais.</p>
<p>§95 — Três principais fraquezas podem comprometer a sustentabilidade de tais coalizões: (i) a incapacidade do Estado de entregar adequadamente os programas de investimento social, frequente em países com fraca capacidade estatal; (ii) as relações políticas clientelistas entre eleitorados e governos que podem solapar a dimensão investidora dos programas; e (iii) o enfraquecimento potencial do apoio da classe média, que pode pedir mais escolha, isolamento ou mesmo estratificação. O perigo mais premente para as coalizões social-democráticas ao estilo latino é que as classes operárias percam fé na capacidade do investimento social de realmente promover a inclusão e passem a apoiar programas mais intensivos em compensação — como uma possível virada populista (Bolsonaro no Brasil é citado como exemplo).</p>
</section>
<section id="as-coalizões-conservadora-e-liberal-96107" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="as-coalizões-conservadora-e-liberal-96107">§17.3.2 — As coalizões conservadora e liberal [§96–§107]</h3>
<p>§96 — Em países onde a classe média não está interessada em um projeto universalista e/ou onde a classe operária está em posição de defender com sucesso legados compensatórios mais antigos, a coalizão social-democrática não emergirá. Em vez disso, as reformas serão baseadas em diferentes tipos de coalizões, onde a comunidade de negócios, a classe média tradicional (ex.: a pequena burguesia) ou mesmo parte da classe operária industrial tradicional terão voz. Se a classe média educada ainda desempenha papel, o investimento social pode emergir de forma fragmentada ou estratificada (pública) ou como investimento privado com apoio público via isenções fiscais (liberal).</p>
<p>§97 — <strong>A coalizão conservadora corporatista e o investimento social estratificado.</strong> A coalizão de investimento social conservadora emerge quando as classes médias educadas estabelecem uma aliança com a comunidade de negócios e as antigas classes médias industriais, tendo como premissa a necessidade de investimento social orientado ao crescimento econômico. Quando são os partidos de direita que supervisionam o processo de investimento social, o crescimento econômico tende a ter mais peso do que a equidade social. A agenda de investimento social estratificado não abraça nem um programa de provisão universalista de bem-estar nem uma estratégia focalizada combinada de criação de capital humano e redução da pobreza; em vez disso, prevê uma expansão socialmente segmentada das políticas investidoras.</p>
<p>§98 — Enquanto as coalizões social-democráticas enxergam o investimento social como um meio, entre outros, de abordar as desigualdades induzidas pelo mercado, as coalizões conservadoras de investimento social o enxergam principalmente como um meio de estimular o crescimento econômico desenvolvendo qualificações e capital humano em base meritocrática (o que Chevalier [2016] chama de “qualificações para os melhores”). Tais atitudes inigualitárias são frequentemente acompanhadas por valores socialmente conservadores, especialmente em política familiar.</p>
<p>§99 — Do ponto de vista da política partidária, a coalizão conservadora é geralmente liderada por partidos democratas-cristãos ou conservadores — CDU-CSU na Alemanha, LDP no Japão, Partido Republicano e então En Marche! (de Macron) na França. Em termos sociais, as classes médias educadas lucram com a expansão segmentada dos serviços públicos que principalmente as beneficiarão (efeito Matthew), enquanto a comunidade de negócios se beneficia da maior disponibilidade de trabalho qualificado por meio da mobilização de mulheres educadas, num contexto de escassez qualificada de mão de obra. Os negócios também esperam se beneficiar de economias em gasto público com compensação social que uma “virada” ao investimento social provavelmente produzirá.</p>
<p>§100 — Uma questão crucial para tais coalizões é como lidar com as classes operárias politicamente marginalizadas. Em países onde as políticas compensatórias são altamente desenvolvidas e os legados de proteção social são fortes, a questão tende a ser apresentada como um trade-off entre a expansão das políticas de investimento social e a contenção ou recalibração da compensação social. Os Estados de bem-estar cristão-conservadores da Europa são caracterizados por uma forte dualização do mercado de trabalho entre a “velha” classe operária industrial (beneficiária desproporcional do aparato de desmodificação existente) e os novos e jovens outsiders diversificados e amplamente negligenciados do mercado de trabalho (Emmenegger et al., 2012; Palier &amp; Thelen, 2010).</p>
<p>§101 — No modelo alemão de estratificação do investimento social, a erosão da compensação social e das proteções do mercado de trabalho na periferia do mercado de trabalho combina-se com a preservação de algumas políticas compensatórias tradicionais e a implementação de certos investimentos sociais em seu núcleo — mais algumas formas limitadas de universalismo do bem-estar (como a reforma inclusiva de ECEC de 2015 na Alemanha). A reforma do VET de 2004-2005, promovida por um governo de coalizão social-democrata-verde em resposta à escassez de vagas de aprendizagem de qualidade, encontrou oposição do IG Metall (que se opôs à expansão do sistema de aprendizagem para além do sistema existente) e dos sindicatos conservadores de professores (que se opuseram à introdução de escolas compreensivas e à dissipação dos privilégios relativos que desfrutavam no sistema segmentado alemão).</p>
<p>§102 — O que é notável é que, embora haja uma divisão entre trabalhadores padrão e não-padrão também no Japão, Coreia e Taiwan, o estado subdesenvolvido dos sistemas de bem-estar e o baixo nível de sindicalização impediram a formação de uma constituency clara orientada à compensação da classe operária industrial. Isso se reflete na atitude do público em relação ao investimento social e permite a implementação gradual de uma abordagem mais inclusiva (como pode ser visto no ECEC na Coreia). Nos países do Leste Asiático, onde há um legado compensatório fraco e a cobertura sindical dos setores centrais é baixa, as políticas investidoras e compensatórias foram apresentadas não como trade-offs mas como parte da mesma estratégia integrada.</p>
<p>§103 — As coalizões conservadoras de investimento social tendem a abraçar valores socialmente relativamente conservadores. Isso tem consequências de longo alcance para a estratégia de investimento social que essas coalizões promovem, especialmente no campo da política familiar: a política de família tende a ser lacunar e marcada por vieses familialistas arraigados. Nos países bismarckianos da Europa Continental, as políticas de família são orientadas pelo princípio de “livre escolha” — pais podem escolher entre creches formais e licenças parentais para cuidados em casa. Há, no entanto, uma forte distorção na escolha: mães educadas usam creches formais e assim se beneficiam do investimento social, enquanto mães com baixa qualificação optam por longas licenças parentais mal pagas que as mantêm longe do mercado de trabalho e seus filhos longe do investimento social. Este é um forte mecanismo que alimenta a fragmentação social, os efeitos Matthew e a reprodução das desigualdades.</p>
<p>§104 — <strong>A coalizão liberal “Terceira Via” e o investimento social focalizado substitutivo.</strong> A coalizão liberal é composta pelos mesmos grupos que a conservadora, mas emerge em países com uma história institucional muito diferente — onde o compromisso do setor público com a provisão ou coordenação da política social está historicamente ausente. O investimento social é tradicionalmente entregue pelo setor privado. O Estado de bem-estar liberal (Esping-Andersen, 1990) é primariamente destinado a apoiar indivíduos ou grupos vulneráveis que o mercado não pode ou não atende, ou que enfrentam desvantagem sistêmica. Nesses países, o investimento social público é focalizado na população mais deprimente, com os principais objetivos sendo a ativação e a re-mercantilização (re-commodification), enquanto o investimento social que beneficia a classe média educada permanece privado (mas com altos subsídios públicos como isenções fiscais).</p>
<p>§105 — A chamada “nova política social” na forma de investimento social foi desenvolvida pelos “New Democrats” nos EUA sob Clinton e pelo New Labour no Reino Unido sob Blair, e teorizada por Giddens (1998). Para reconquistar o poder após anos de governos conservadores neoliberais, esses partidos propuseram dar mais ênfase à justiça social e às políticas sociais do que os partidos neoliberais conservadores, enquanto deixavam de fora os elementos compensatórios (políticas sociais passivas), para desenvolver novas políticas sociais ativas destinadas tanto a trazer as pessoas de volta ao mercado de trabalho quanto a permitir mais investimento em capital humano. Como Morel et al.&nbsp;(2012) destacam, Giddens e outros proponentes da “Terceira Via” argumentam — contra os neoliberais — por um papel novo, mais ativo e habilitador para o Estado, mas compartilham com os neoliberais um diagnóstico muito similar das falhas do Estado de bem-estar tradicional do pós-guerra.</p>
<p>§106 — Dois métodos principais foram utilizados: tornar o trabalho lucrativo (através de créditos fiscais para trabalhadores de baixa renda, como o <em>Working Family Tax Credit</em> do governo Blair) e reforçar a disponibilidade para o trabalho (limitando o acesso a benefícios para desempregados). O governo Trabalhista no Reino Unido complementou esses mecanismos estabelecendo um tipo de programa “welfare-to-work” que procurava melhorar a formação para os jovens e desempregados crônicos. O processo de recalibração do bem-estar foi concomitante com uma tentativa dos partidos social-democratas e social-liberais de responder à sua marginalização política pela “nova direita” neoliberal ao longo dos anos 1980.</p>
<p>§107 — A distinção entre a coalizão “nova esquerda” e a coalizão social-democrática nórdica é fundamental: no caso liberal, o comprometimento com o investimento social vem de mãos dadas com a erosão das políticas compensatórias estabelecidas (benefícios de desemprego), o que frequentemente equivale a investimentos sociais substitutivos. O comprometimento com as políticas de liberalização coloca as novas coalizões de esquerda em uma categoria muito diferente das coalizões social-democráticas: em vários tópicos, especialmente a política fiscal e monetária, os governos de “nova esquerda” agiram em plena continuidade com seus predecessores de “nova direita”. Tanto no Reino Unido quanto nos EUA, a dissidência das classes operárias e médias inferiores contra a reorientação liberal do Estado de bem-estar emergiu por meio do apoio crescente a grupos protecionistas de direita, dando origem a alguns dos exemplos mais espetaculares de populismo de direita (Trump nos EUA e Brexit no Reino Unido).</p>
</section>
<section id="a-coalizão-social-protecionista-108115" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-coalizão-social-protecionista-108115">§17.3.3 — A coalizão social-protecionista [§108–§115]</h3>
<p>§108 — Se a classe média educada não é grande o suficiente para constituir uma constituency eleitoral apelativa e se a compensação social consome uma grande parte do gasto social público, o investimento social provavelmente não emergirá como uma estratégia de reforma. As classes operárias (industriais) e médias inferiores provavelmente não estão dispostas a embarcar em um programa de desenvolvimento inclusivo. Em vez disso, elas se engajam em uma estratégia defensiva em relação às instituições de bem-estar existentes.</p>
<p>§109 — Sob essas circunstâncias, coalizões provavelmente formarão que abrangem as classes operárias industriais centrais e as classes médias inferiores e podem até se estender para incluir partes da comunidade de negócios. Essas coalizões são organizadas em torno de agendas fragmentadas e conflitantes que tentam atrair apoio de cada uma das prováveis constituencies eleitorais — “política particularista”. Raramente essas coalizões girarão em torno de agendas claramente formuladas de investimento social (público ou privado), e como resultado muitas vezes carecem de um “plano” claro para o futuro da reforma do bem-estar ou do crescimento economicamente sustentável. Isso pode degenerar em clientelismo a nível de grupos.</p>
<p>§110 — A ausência de uma constituency proeminente que defenda o desenvolvimento econômico de longo prazo resulta da capacidade de cada grupo social de racionalmente preferir ganhos mais imediatos em estratégias que não conduzem ao crescimento em vez de apostar na capacidade incerta da economia de transitar para um caminho estável de desenvolvimento inclusivo. Esse tipo de política particularista de curto prazo é típico de países no nível médio-alto do espectro de desenvolvimento econômico, que não completaram sua transição para uma economia baseada no conhecimento. Nesses países, a classe média educada é relativamente pequena e incapaz de se organizar em torno de uma agenda coerente de demandas políticas.</p>
<p>§111 — Os verdadeiros perdedores das coalizões social-protecionistas são as (pequenas) classes médias educadas e os outsiders do mercado de trabalho (especialmente jovens, pouco qualificados, mulheres e migrantes). Os outsiders do mercado de trabalho são excluídos pelas velhas políticas sociais e não veem surgir novas. A deterioração dos mercados de trabalho significa que as poucas oportunidades que encontram serão caracterizadas por baixos requisitos de qualificação e baixos salários. Em resumo, as coalizões de compensação social tendem a engendrar o que poderia ser chamado de “protecionismos sociais rent-seeking” onde declínio econômico, privilégios corporatistas e inclusão particularista coexistem com a preservação de um Estado de bem-estar consumista e protecionista ineficiente e geralmente excludente.</p>
<p>§112 — O exemplo histórico mais óbvio da coalizão social-protecionista é o governo de coalizão que emergiu na Itália após as eleições legislativas de 2018 — a coalizão entre a Liga (partido de direita autoritário que havia começado como separatismo norte-italiano mas que em meados dos anos 2010 fazia campanha principalmente em questões identitárias e de segurança) e o M5S (partido de esquerda populista que havia emergido em 2009 em torno de uma agenda de contestação radical das instituições). Esses partidos anti-establishment capturaram votos de quase todas as classes sociais, exceto as “elites” (a classe média alta educada e a maior parte da comunidade de negócios, que convergiu para o Partido Democrático de centro-esquerda, marcando a transformação desse partido em um partido de “elite”).</p>
<p>§113 — O M5S baseou sua estratégia eleitoral em uma agenda de protecionismo de bem-estar e redução do desemprego voltada para trabalhadores precários e desempregados no Sul; a Liga visou ao eleitorado insatisfeito da antiga centro-direita berluscônica, incluindo principalmente as classes médias do Norte e partes da comunidade de negócios (pequenas firmas e comércio), prometendo medidas mais rígidas anti-imigração e cortes de impostos. As políticas implementadas refletiram essa estrutura: (i) o Estado de bem-estar compensatório foi ampliado via introdução de uma estratégia de redução da pobreza (<em>reddito di cittadinanza</em>), que como de 2020 havia tido um desempenho ruim como meio de inclusão no mercado de trabalho (menos de 5% dos beneficiários conseguiram encontrar emprego); (ii) uma reforma das pensões foi implementada que reduziu a idade de reforma e reintroduziu proteções anteriormente abolidas pela reforma Fornero de 2012; (iii) o governo tentou mas falhou em entregar um corte de impostos.</p>
<p>§114 — Durante esse período, os empregadores italianos se comportaram de forma quase rent-seeking, com apoio morno ao “bem-estar fiscal” (cortes de impostos), mostrando pouco interesse em um plano coerente de reorientação econômica por meio da upgrading e mobilização do capital humano — em linha com a deterioração geral da economia italiana (Kazepov &amp; Ranci, 2017).</p>
<p>§115 — Os países da Europa do Sul são aqueles em que as classes médias são geralmente dominadas pela pequena burguesia, pelas liberais profissões corporatistas tradicionais e pelos trabalhadores de escritório semi-qualificados — grupos mais interessados em isenções fiscais, economias de custos e políticas de compensação social do que em uma estratégia coerente de investimento social favorável ao crescimento. A classe operária está predominantemente empregada no setor de manufatura sob pressão competitiva que leva os sindicatos a pedir compensação social e proteção em caso de redundância. O resultado é uma extrema instabilidade que marca, quase por design, a coalizão social-protecionista — e que tende a aumentar à medida que a economia se deteriora.</p>
</section>
</section>
<section id="seção-17.4-conclusão-pp.-467471" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="seção-17.4-conclusão-pp.-467471"><span class="header-section-number">5</span> Seção 17.4: Conclusão (pp.&nbsp;467–471)</h2>
<section id="síntese-dos-achados-116120" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="síntese-dos-achados-116120">§17.4.1 — Síntese dos achados [§116–§120]</h3>
<p>§116 — Na conclusão, os autores recapitulam os principais insights de cada uma das três partes do capítulo. Em relação às dinâmicas de politização, os achados principais são que as preocupações sociodemográficas importaram em toda parte mas de formas diferentes: novos riscos sociais foram prevalentes na Europa Ocidental e do Sul; envelhecimento e baixa fertilidade na Ásia do Nordeste e na Europa Oriental; pobreza e desigualdade na América Latina. A interação entre demanda e oferta de qualificações elevadas na economia molda a politização dos objetivos que as reformas de investimento social devem perseguir: países com alta demanda e curta oferta focam na criação e mobilização de capital humano; em países onde tanto a oferta quanto a demanda são altas, a sustentabilidade e a inclusividade do sistema de investimento social são politizadas; aqueles com oferta relativamente alta e baixa demanda deveriam (em teoria) focar na preservação e mobilização, embora geralmente tenham falhado em fazê-lo na prática.</p>
<p>§117 — Os legados de bem-estar determinam a margem de manobra para reformas de investimento social (i.e., se estão em competição com as políticas compensatórias pré-existentes em um trade-off entre os dois tipos de políticas de bem-estar). Isso, contudo, não é sempre o caso: em países onde os legados de proteção social eram baixos, tanto as políticas compensatórias quanto as de investimento social emergiram ao mesmo tempo; onde ambos eram altos, o debate de politização se focou mais na sustentabilidade. A saliência influencia a arena em que uma reforma específica é levada adiante — “loud” política de massas versus “quiet” elaboração de políticas burocrática e pluralista — e é influenciada pelo tamanho da classe média educada e pela presença de novos riscos sociais, envelhecimento ou ambos.</p>
<p>§118 — Em relação às dinâmicas de formação de coalizões e tomada de decisão, os principais achados são que partidos de esquerda têm, no conjunto, maior probabilidade de embarcar em reformas de investimento social, embora haja também muitos casos em que os partidos conservadores foram protagonistas-chave. O partidarismo importa muito para determinar o perfil distributivo e a lógica geral das reformas — com a direita conservadora mais propensa a patrocinar reformas estratificadas como meio de estimular o crescimento econômico, e a esquerda mais inclinada a abordar preocupações de inclusão social por meio de reformas inclusivas ou focalizadas (integrativas) voltadas para integrar os segmentos da população excluídos do bem-estar tradicional.</p>
<p>§119 — Em relação à tipologia das cinco coalizões, o argumento principal é que o tamanho e o comportamento político da classe média educada são as principais variáveis explicativas para diferentes estratégias de reforma do bem-estar em termos do perfil distributivo do investimento social e de se as estratégias sem investimento social são preferidas. Identificam-se duas coalizões de classe principais: aliança classe média–negócios e aliança classe média–classe operária. As coalizões de negócios e nova classe média educada podem levar a reforma estratificada de investimento social (notavelmente na Europa Continental e na Ásia do Nordeste) ou a reformas liberais de bem-estar consistindo em contenção, privatização e investimento social focalizado substitutivo da assistência social.</p>
<p>§120 — As coalizões de nova classe média educada e classe operária podem levar a uma estratégia social-democrática de investimento social inclusivo (países nórdicos) ou a investimento social focalizado integrativo (América Latina). Em instâncias onde a velha classe média (industrial) é dominante porque a nova classe média educada permanece bastante pequena, observa-se a prevalência de uma coalizão social-protecionista. Aqui as considerações pró-crescimento e de inclusão social estão fora da mesa.</p>
</section>
<section id="investimento-social-durante-e-após-a-crise-do-covid-19-121128" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="investimento-social-durante-e-após-a-crise-do-covid-19-121128">§17.4.2 — Investimento social durante e após a crise do COVID-19 [§121–§128]</h3>
<p>§121 — Os autores reconhecem que o projeto WOPSI foi finalizado durante a pandemia de COVID-19, tornando impossível integrar as reações dos países à análise detalhada. Sabe-se, contudo, que tanto a Grande Recessão do início do século XXI quanto a crise COVID-19 reafirmaram o poder do Estado, que mobilizou recursos massivos. Os que poderiam se beneficiar do investimento social e que são prováveis de empurrá-lo (os jovens, os trabalhadores de serviços e similares) não receberam muitos dos benefícios emergenciais — o que pode fortalecer o apoio ao bem-estar em geral mas não necessariamente ao investimento social inclusivo em particular.</p>
<p>§122 — O exemplo alemão é ilustrativo: o governo respondeu aos desafios socioeconômicos da crise principalmente com instrumentos tradicionais de política social (provisão de saúde e redes de segurança de desemprego, uso do trabalho de curto prazo [<em>Kurzarbeit</em>] para evitar o desemprego em massa). O que o governo não fez foi focar em investimentos sociais. Apenas no final da terceira onda de COVID-19 na Europa (primavera de 2021) o governo alemão lançou uma grande política educacional com o objetivo declarado de combater as desigualdades educacionais que haviam inequivocamente aumentado durante a crise. Essa medida é extremamente importante, mas é revelador que praticamente não houve medidas preventivas mesmo com observadores alertando repetidamente para o aumento das desigualdades educacionais durante a pandemia — uma lógica típica de “reparar em vez de preparar” (<em>repair rather than prepare</em>), característica da abordagem europeia continental.</p>
<p>§123 — Mais geralmente, a crise parece trabalhar contra as políticas de investimento social, em linha com análises anteriores mostrando que as crises econômicas solapam os gastos discricionários (Breunig &amp; Busemeyer, 2012). Os mais afetados pelo COVID-19 (a doença em si) foram encontrados principalmente entre a população idosa, levando a um foco em proteger e cuidar dos idosos, em muitos casos às custas dos serviços de investimento social e à custa das crianças, dos jovens e da população ativa, que sofreram enormemente com os lockdowns.</p>
<p>§124 — As escolas foram fechadas; estudantes ficaram presos em seus pequenos quartos para o ensino online; as taxas de abandono escolar aumentaram (especialmente entre os mais pobres); a depressão espalhou-se entre jovens e jovens pais. As mulheres sofreram mais dos lockdowns do que os homens; o equilíbrio trabalho-vida (cuidar de filhos enquanto se trabalha em casa) tornou-se ainda mais difícil de encontrar. Assim, de certa forma, a pandemia do COVID-19 está simplesmente amplificando os novos riscos sociais e o stress específico sobre mulheres, jovens e crianças que o investimento social deveria estar endereçando.</p>
<p>§125 — Além disso, há um óbvio viés social contra os grupos sociais mais desfavorecidos durante essa crise: a mortalidade é maior entre as classes mais baixas (Hawkins et al., 2020; Seligman et al., 2021); o acesso às vacinas é desigual contra as classes mais baixas; aqueles com empregos precários e de baixo salário em logística, entrega e serviços interpessoais estão na linha de frente, enquanto as perdas de empregos afetam principalmente os empregos precários de média qualificação ou setores específicos de serviços como turismo, hotéis, restaurantes e cultura. Os empregos ocupados pela classe média educada (serviços públicos, serviços intensivos em conhecimento) foram protegidos dos choques econômicos graças à capacidade de trabalhar em casa.</p>
<p>§126 — Nesse contexto, a indispensabilidade dos empregos de investimento social (em saúde, educação e cuidados) torna-se altamente visível. Os trabalhadores da saúde — enfermeiros, médicos e outros profissionais, assim como trabalhadores de suporte — enfrentam riscos sérios de contrair COVID-19 no local de trabalho. Aproximadamente 70% dos empregos no setor de saúde e trabalho social são ocupados por mulheres (ILO, 2020). A esperança dos autores é que os países compreendam que a recuperação requer o desenvolvimento e a melhoria da qualidade desses empregos de investimento social.</p>
<p>§127 — Os autores concluem com uma afirmação normativa: é somente se o investimento social inclusivo for desenvolvido que nossas sociedades serão capazes de se recuperar no longo prazo e de se preparar para a economia baseada no conhecimento e seus desafios. A pandemia aprofundou a necessidade do investimento social, mas ao mesmo tempo tornou sua realização politicamente mais difícil ao desviar recursos e atenção política para respostas compensatórias de curto prazo.</p>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">6</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central.</strong> O capítulo defende que o perfil distributivo das políticas de investimento social (inclusivo, estratificado ou focalizado) em democracias capitalistas é determinado primariamente pelas <strong>coalizões políticas e atores</strong> que sustentam as reformas; já as <strong>funções</strong> priorizadas pelo investimento social (criação, mobilização ou preservação de capital humano) dependem da interação entre legados de bem-estar, condições estruturais sociodemográficas e econômicas, e dinâmicas de politização. O argumento é de <strong>natureza configuracional-comparativa</strong>: não há um único fator determinante, mas constelações de fatores que, em diferentes contextos regionais, produzem padrões reconhecíveis de reforma.</p>
<p><strong>Natureza do argumento.</strong> O argumento é primariamente <strong>descritivo-explicativo</strong> — mapeia a variação e oferece explicações configuracionais — com um componente <strong>tipológico</strong> original (a tipologia das cinco coalizões) e uma dimensão <strong>normativa</strong> na seção sobre COVID-19. Não é um argumento causal formal: não há modelo explícito de mecanismos causais nem testes formais da tipologia.</p>
<p><strong>O que o texto demonstra vs.&nbsp;o que fica como hipótese.</strong> O texto demonstra com sólida evidência comparativa que: (a) a classe média educada é um ator pivô nas coalizões que sustentam o investimento social; (b) a composição da coalizão (aliança com a classe operária ou com os negócios) determina o perfil distributivo; (c) os legados de bem-estar moldam as margens de manobra mas não determinam o resultado por si sós; (d) o investimento social focalizado varia significativamente em natureza — “integrativo” vs.&nbsp;“substitutivo” — dependendo do contexto. O que fica como hipótese ou agenda futura: (a) os mecanismos causais exatos pelos quais coalizões se formam e são mantidas; (b) as condições de suficiência e necessidade para cada tipo de coalizão (testáveis via QCA); (c) a trajetória das coalizões em contextos de crise (COVID-19, austeridade); (d) a aplicabilidade da tipologia a democracias fora do conjunto analisado (África do Sul, Índia, Turquia, Sudeste Asiático).</p>
<p><strong>Contribuição para o debate mais amplo.</strong> O capítulo representa a síntese mais ambiciosa até o momento sobre a política comparada do investimento social em escala global. Sua tipologia das cinco coalizões avança além das abordagens puramente centradas nos “mundos do bem-estar” de Esping-Andersen (1990) e além das abordagens de Varieties of Capitalism (Hall &amp; Soskice, 2001), ao integrar a análise de coalizões de classes com a dimensão distributiva das reformas. A distinção entre investimento social focalizado “integrativo” e “substitutivo” é uma contribuição conceitual original e potencialmente geradora de pesquisa futura. O capítulo também contribui para o debate sobre dualization (Emmenegger et al., 2012; Palier &amp; Thelen, 2010) ao mostrar como a estratificação do investimento social reproduz e amplia as clivagens insider-outsider existentes nos Estados de bem-estar bismarckianos e do Leste Asiático.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>