<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-09">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: The Train Wrecks of Modernization: Railway Construction and Separatist Mobilization in Europe – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1596dba0f6ebd5d6ff9514dff97656d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: The Train Wrecks of Modernization: Railway Construction and Separatist Mobilization in Europe – Annotated Bibliography">
<meta property="og:description" content="Pengl, Müller-Crepon, Valli, Cederman e Girardin (2026) — American Political Science Review">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#introdução-pp.-3738" id="toc-introdução-pp.-3738" class="nav-link" data-scroll-target="#introdução-pp.-3738"><span class="header-section-number">1</span> Introdução (pp.&nbsp;37–38)</a>
  <ul class="collapse">
  <li><a href="#puzzle-objeto-e-contribuição-14" id="toc-puzzle-objeto-e-contribuição-14" class="nav-link" data-scroll-target="#puzzle-objeto-e-contribuição-14"><span class="header-section-number">1.1</span> Puzzle, objeto e contribuição [§1–§4]</a></li>
  <li><a href="#achados-principais-antecipados-5" id="toc-achados-principais-antecipados-5" class="nav-link" data-scroll-target="#achados-principais-antecipados-5"><span class="header-section-number">1.2</span> Achados principais antecipados [§5]</a></li>
  </ul></li>
  <li><a href="#modernização-e-nacionalismo-na-literatura-pp.-3839" id="toc-modernização-e-nacionalismo-na-literatura-pp.-3839" class="nav-link" data-scroll-target="#modernização-e-nacionalismo-na-literatura-pp.-3839"><span class="header-section-number">2</span> Modernização e Nacionalismo na Literatura (pp.&nbsp;38–39)</a>
  <ul class="collapse">
  <li><a href="#tradição-integracionista-69" id="toc-tradição-integracionista-69" class="nav-link" data-scroll-target="#tradição-integracionista-69"><span class="header-section-number">2.1</span> Tradição integracionista [§6–§9]</a></li>
  <li><a href="#tradição-separatista-e-lacunas-empíricas-1012" id="toc-tradição-separatista-e-lacunas-empíricas-1012" class="nav-link" data-scroll-target="#tradição-separatista-e-lacunas-empíricas-1012"><span class="header-section-number">2.2</span> Tradição separatista e lacunas empíricas [§10–§12]</a></li>
  </ul></li>
  <li><a href="#teoria-ferrovias-e-mobilização-nacionalista-pp.-3943" id="toc-teoria-ferrovias-e-mobilização-nacionalista-pp.-3943" class="nav-link" data-scroll-target="#teoria-ferrovias-e-mobilização-nacionalista-pp.-3943"><span class="header-section-number">3</span> Teoria: Ferrovias e Mobilização Nacionalista (pp.&nbsp;39–43)</a>
  <ul class="collapse">
  <li><a href="#o-contexto-pré-industrial-e-a-transição-1316" id="toc-o-contexto-pré-industrial-e-a-transição-1316" class="nav-link" data-scroll-target="#o-contexto-pré-industrial-e-a-transição-1316"><span class="header-section-number">3.1</span> O contexto pré-industrial e a transição [§13–§16]</a></li>
  <li><a href="#os-três-mecanismos-causais-1722" id="toc-os-três-mecanismos-causais-1722" class="nav-link" data-scroll-target="#os-três-mecanismos-causais-1722"><span class="header-section-number">3.2</span> Os três mecanismos causais [§17–§22]</a></li>
  <li><a href="#hipóteses-derivadas-2328" id="toc-hipóteses-derivadas-2328" class="nav-link" data-scroll-target="#hipóteses-derivadas-2328"><span class="header-section-number">3.3</span> Hipóteses derivadas [§23–§28]</a></li>
  </ul></li>
  <li><a href="#dados-e-variáveis-pp.-4346" id="toc-dados-e-variáveis-pp.-4346" class="nav-link" data-scroll-target="#dados-e-variáveis-pp.-4346"><span class="header-section-number">4</span> Dados e Variáveis (pp.&nbsp;43–46)</a>
  <ul class="collapse">
  <li><a href="#dados-de-assentamentos-étnicos-e-fronteiras-históricas-2932" id="toc-dados-de-assentamentos-étnicos-e-fronteiras-históricas-2932" class="nav-link" data-scroll-target="#dados-de-assentamentos-étnicos-e-fronteiras-históricas-2932"><span class="header-section-number">4.1</span> Dados de assentamentos étnicos e fronteiras históricas [§29–§32]</a></li>
  <li><a href="#variável-independente-principal-e-variáveis-de-desfecho-3337" id="toc-variável-independente-principal-e-variáveis-de-desfecho-3337" class="nav-link" data-scroll-target="#variável-independente-principal-e-variáveis-de-desfecho-3337"><span class="header-section-number">4.2</span> Variável independente principal e variáveis de desfecho [§33–§37]</a></li>
  </ul></li>
  <li><a href="#análises-e-resultados-pp.-4651" id="toc-análises-e-resultados-pp.-4651" class="nav-link" data-scroll-target="#análises-e-resultados-pp.-4651"><span class="header-section-number">5</span> Análises e Resultados (pp.&nbsp;46–51)</a>
  <ul class="collapse">
  <li><a href="#especificação-principal-e-resultados-3842" id="toc-especificação-principal-e-resultados-3842" class="nav-link" data-scroll-target="#especificação-principal-e-resultados-3842"><span class="header-section-number">5.1</span> Especificação principal e resultados [§38–§42]</a></li>
  <li><a href="#robustez-variável-instrumental-4345" id="toc-robustez-variável-instrumental-4345" class="nav-link" data-scroll-target="#robustez-variável-instrumental-4345"><span class="header-section-number">5.2</span> Robustez: variável instrumental [§43–§45]</a></li>
  <li><a href="#robustez-adicional-definição-de-amostra-e-desagregação-do-desfecho-4648" id="toc-robustez-adicional-definição-de-amostra-e-desagregação-do-desfecho-4648" class="nav-link" data-scroll-target="#robustez-adicional-definição-de-amostra-e-desagregação-do-desfecho-4648"><span class="header-section-number">5.3</span> Robustez adicional: definição de amostra e desagregação do desfecho [§46–§48]</a></li>
  <li><a href="#hipóteses-condicionais-moderadores-contextuais-4953" id="toc-hipóteses-condicionais-moderadores-contextuais-4953" class="nav-link" data-scroll-target="#hipóteses-condicionais-moderadores-contextuais-4953"><span class="header-section-number">5.4</span> Hipóteses condicionais: moderadores contextuais [§49–§53]</a></li>
  <li><a href="#mecanismos-causais-desagregados-5457" id="toc-mecanismos-causais-desagregados-5457" class="nav-link" data-scroll-target="#mecanismos-causais-desagregados-5457"><span class="header-section-number">5.5</span> Mecanismos causais desagregados [§54–§57]</a></li>
  </ul></li>
  <li><a href="#conclusão-pp.-5152" id="toc-conclusão-pp.-5152" class="nav-link" data-scroll-target="#conclusão-pp.-5152"><span class="header-section-number">6</span> Conclusão (pp.&nbsp;51–52)</a>
  <ul class="collapse">
  <li><a href="#síntese-e-releitura-da-teoria-modernizacionista-5860" id="toc-síntese-e-releitura-da-teoria-modernizacionista-5860" class="nav-link" data-scroll-target="#síntese-e-releitura-da-teoria-modernizacionista-5860"><span class="header-section-number">6.1</span> Síntese e releitura da teoria modernizacionista [§58–§60]</a></li>
  <li><a href="#agenda-de-pesquisa-61" id="toc-agenda-de-pesquisa-61" class="nav-link" data-scroll-target="#agenda-de-pesquisa-61"><span class="header-section-number">6.2</span> Agenda de pesquisa [§61]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">7</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: The Train Wrecks of Modernization: Railway Construction and Separatist Mobilization in Europe</h1>
<p class="subtitle lead">Pengl, Müller-Crepon, Valli, Cederman e Girardin (2026) — American Political Science Review</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Comparative Politics</div>
    <div class="quarto-category">Political Economy</div>
    <div class="quarto-category">Nationalism and Ethnicity</div>
    <div class="quarto-category">State Building</div>
    <div class="quarto-category">Western Europe</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Citação APA 7:</strong></p>
<p>Pengl, Y. I., Müller-Crepon, C., Valli, R., Cederman, L.-E., &amp; Girardin, L. (2026). The train wrecks of modernization: Railway construction and separatist mobilization in Europe. <em>American Political Science Review</em>, <em>120</em>(1), 37–54. https://doi.org/10.1017/S0003055425000048</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Entrada BibTeX → Pengl-etal2026
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">Pengl</span>-<span class="ot">etal2026</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="dt">author</span>  = {Pengl, Yannick I. and Müller-Crepon, Carl and Valli, Roberto and Cederman, Lars-Erik and Girardin, Luc},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="dt">title</span>   = {The Train Wrecks of Modernization: Railway Construction and Separatist Mobilization in Europe},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="dt">year</span>    = {2026},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="dt">journal</span> = {American Political Science Review},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="dt">volume</span>  = {120},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="dt">number</span>  = {1},</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="dt">pages</span>   = {37--54},</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="dt">doi</span>     = {10.1017/S0003055425000048},</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<pre><code>Última atualização: 2026-05-09
Modelo: Perplexity, powered by Claude Sonnet 4.6
Prompt Version: v17.2 2026-05-08 | Ficha antes do fichamento
Gerado em: 2026-05-09T21:45:00-03:00
Ocasião da Leitura: [Para preenchimento manual do usuário]</code></pre>
<hr>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.2</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A pergunta é causal e comparativa. A premissa central é que ferrovias são uma proxy válida de modernização e que seus efeitos sobre o separatismo podem ser identificados via variação espaço-temporal. O ponto mais vulnerável está na unidimensionalidade do tratamento: “acesso ferroviário” colapsa mecanismos opostos (M1, M2, M3) em um indicador único, o que torna a pergunta analiticamente mais rica do que o design principal pode responder.</td>
<td style="text-align: left;">Como a construção ferroviária — enquanto vetor central da modernização europeia — afetou a mobilização separatista de grupos étnicos periféricos entre 1816 e 1945? Pergunta explicativa-causal, explicitamente formulada.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">As condicionais são onde o argumento ganha maior densidade teórica; a análise de mecanismos é secundária ao efeito médio mas central para a interpretação causal. A relação entre as perguntas secundárias e a central é aditiva: a pergunta central estabelece o efeito médio, as condicionais explicam a heterogeneidade, e a de mecanismos explica o <em>porquê</em>.</td>
<td style="text-align: left;">(1) Sob quais condições contextuais (tamanho do grupo dominante, capacidade estatal, renda per capita, regime político, tamanho do grupo minoritário, distância cultural) o acesso ferroviário aumenta ou reduz o separatismo? (2) Quais mecanismos causais — acesso a mercados (M1), alcance do Estado (M2), conectividade interna (M3) — explicam o efeito observado?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno: a literatura clássica (Weber 1976; Deutsch 1953; Gellner 1983) prevê integração, mas a evidência histórica de desintegração na Europa oriental estava disponível. A originalidade está em operacionalizar e testar sistematicamente a tensão. A generalização além da Europa pré-1945 é reconhecida como arriscada pelos próprios autores, o que é honesto mas limita o alcance teórico.</td>
<td style="text-align: left;">Puzzle explicativo: a teoria modernizacionista dominante prevê que infraestrutura de transporte promove integração nacional, mas a evidência histórica europeia mostra numerosos casos de desintegração etnonacional precisamente nos períodos de expansão ferroviária. O puzzle questiona se Weber (1976) é paradigma ou exceção. É genuíno e generalizável ao nível da hipótese, embora o teste seja restrito à Europa.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">O argumento central é causal e heterogêneo: o efeito médio é positivo (mais separatismo), mas os mecanismos são opostos e contextualmente condicionados. O claim of discovery é sustentado pelo DiD, event study e IV. O que efetivamente sustenta a tese é a convergência de três estratégias de identificação e a análise de mecanismos via medidas de rede.</td>
<td style="text-align: left;">O acesso ferroviário aumentou, em média, a probabilidade de mobilização separatista em cerca do dobro da média amostral. Este efeito se concentra em contextos de baixa capacidade estatal, baixo desenvolvimento econômico, grupos dominantes pequenos e minorias demograficamente grandes. Mecanicamente, a conectividade interna (M3) aumenta o separatismo; o alcance do Estado (M2) o reduz; o acesso a mercados (M1) não tem efeito independente robusto. Argumento causal heterogêneo.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O artigo é quantitativo com dados históricos geoespaciais. O ponto mais vulnerável metodológico é a análise de mecanismos (Tabela 3): sem um design DiD para as medidas contínuas de rede, a identificação causal dos mecanismos individuais é mais fraca do que a do efeito médio. O fichamento cobre o artigo inteiro (pp.&nbsp;37–54).</td>
<td style="text-align: left;">Diferença-em-diferenças (TWFE e 2S-DiD), event study e variável instrumental baseada em redes ferroviárias simuladas. Dados geoespaciais de segmentos étnicos, fronteiras históricas, construção ferroviária (1834–1922) e eventos de separatismo (1816–1945). Unidade de análise: segmento étnico-ano. Fichamento cobre a obra completa (artigo de 18 páginas).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP tem três camadas de construção: (1) mapeamento de assentamentos étnicos a partir de 73 mapas históricos, com padronização via Ethnologue; (2) digitalização de linhas ferroviárias a partir de train.eryx.net; (3) intersecção geoespacial anual. Os principais vieses introduzidos: (a) os mapas étnicos refletem percepções e convenções cartográficas de época; (b) a exclusão das Ilhas Britânicas por lacuna de dados cria truncamento amostral; (c) a definição de grupo dominante como “maior segmento étnico contendo a capital” é operacionalmente simples mas teoricamente discutível.</td>
<td style="text-align: left;">Fenômeno real (expansão ferroviária e mobilização étnica) → digitalização de 73 mapas históricos e de tiles online do train.eryx.net → intersecção geoespacial com fronteiras históricas (CShapes 2.0) → segmentos étnico-ano → cruzamento com dados de guerras civis (Gleditsch 2004; Sarkees e Wayman 2010), secções bem-sucedidas e claims de independência → regressões TWFE e 2S-DiD. Unidade de análise: segmento étnico-ano (não-dominante). Nível de agregação: subnacional. O DGP introduz viés de observação potencial via qualidade heterogênea dos mapas históricos em regiões periféricas, que são precisamente as mais relevantes para a hipótese.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">Os achados principais são bem suportados pelo design. A distinção entre efeitos de TWFE e 2S-DiD é transparente e esperada (downward bias do TWFE em settings de adoção escalonada). A análise de mecanismos é uma contribuição genuína mas com identificação mais fraca.</td>
<td style="text-align: left;">(1) Acesso ferroviário aumenta separatismo ~2x a média amostral (efeito imediato, persistente por ~50 anos). (2) Efeito maior em países pobres, de baixa capacidade fiscal, com grupos dominantes pequenos e minorias grandes. (3) Conectividade interna (M3) aumenta risco de separatismo; alcance do Estado (M2) reduz; acesso a mercados (M1) sem efeito independente robusto. Contribuição metodológica: dataset geoespacial original (HEG + ferrovias digitalizadas) e medidas de rede para mecanismos causais.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">Os autores respondem adequadamente à pergunta principal. Os pontos mais vulneráveis são: (a) a análise de mecanismos (Tabela 3) não usa DiD — a identificação causal dos três mecanismos é cross-sectional com FE, logo sujeita a omitted variables time-variant; (b) a variável de outcome combina claims, guerras e secessions em um único indicador binário, o que pode mascarar heterogeneidade de efeito entre fenômenos qualitativamente distintos; (c) o instrumento (redes simuladas) assume que a distribuição populacional de 1830 é exógena ao separatismo futuro, o que é plausível mas não verificável; (d) a exclusão das Ilhas Britânicas e a cobertura de dados ferroviários apenas até 1922 criam truncamento que pode subestimar efeitos de longo prazo na fase madura das redes. A evidência para H2a (distância linguística) é fraca e os autores reconhecem isso, mas a interpretação oferecida — que, condicional à diferença cultural, processos de politização importam mais — é especulativa.</td>
<td style="text-align: left;">O argumento é mais vulnerável na análise de mecanismos do que no efeito médio. A convergência de DiD, event study e IV para o efeito principal é convincente. A análise de heterogeneidade (Figura 4) usa binning plots de forma cuidadosa (Hainmueller, Mummolo e Xu 2019), o que é boas práticas. Generalizabilidade: os autores são cautelosos, mas a limitação ao período pré-1945 na Europa é uma scope condition fundamental não suficientemente discutida nos termos de mecanismos contemporâneos.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> Exclusão das Ilhas Britânicas por lacuna de dados; cobertura ferroviária limitada a 1834–1922; impossibilidade de distinguir múltiplos caminhos para integração nacional; restrição geográfica à Europa; cautela explícita contra extrapolação para tecnologias contemporâneas. <br> <strong>Não reconhecidas ou subestimadas:</strong> (1) A análise de mecanismos (Tabela 3) usa modelos TWFE com variáveis contínuas de rede mas sem o mesmo rigor de identificação causal do efeito principal — isso não é explicitado como limitação; (2) a construção do outcome combinado (secession + civil war + claims) agrega fenômenos com diferentes limiares de custo e diferentes dinâmicas causais, o que pode obscurecer heterogeneidade teoricamente relevante; (3) a medida de grupo dominante (“maior segmento contendo a capital”) é operacionalmente ad hoc e não discutida como fonte de incerteza de mensuração.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A moldura teórica é coerente com o design empírico subnacional e comparativo. A escolha de focar em separatismo como proxy de falha de nation-building é inteligente para fins de mensuração, mas deixa de lado variação nos graus e formas de integração.</td>
<td style="text-align: left;">Pluralismo teórico moderado dentro do paradigma modernizacionista: dialoga com Deutsch (1953), Gellner (1983), Weber (1976) para integração; Hechter (2000, 1977), Breuilly (1982) para separatismo; Mann (1993) para poder infraestrutural do Estado. A moldura de custos-benefícios da mobilização separatista é implicitamente racionalista, com ênfase em oportunidades estruturais mais do que identidades. Adequada ao tipo de pergunta e ao design quantitativo comparado. Coerência ontológica: grupos étnicos são tratados como unidades relativamente estáveis, definidas linguisticamente, o que é uma simplificação necessária mas que pode subrepresentar a fluidez identitária no período.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo com a literatura é extenso e equilibrado, cobrindo economia histórica (Donaldson 2018; Hornung 2015), sociologia histórica do nacionalismo (Weber 1976; Gellner 1983; Deutsch 1953; Hechter 2000), e metodologia de DiD recente (Callaway e Sant’Anna 2021; Goodman-Bacon 2021; Gardner 2022; Liu, Wang e Xu 2024).</td>
<td style="text-align: left;">Weber (1976), Deutsch (1953), Gellner (1983), Hechter (2000, 1977, 2013), Breuilly (1982), Mann (1993), Wimmer (2018), Cermeño, Enflo e Lindvall (2022), Müller-Crepon, Hunziker e Cederman (2021), Gardner (2022), Goodman-Bacon (2021). Diálogo ausente ou escasso: literatura sobre imperialismo e administração colonial como moldura para os Impérios Habsburgo e Russo; teoria da etnicidade como construção social e dinâmica (vs.&nbsp;mapeamentos fixos).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">O artigo tem forte coerência interna e contribuição genuína, mas a assimetria entre o rigor da identificação do efeito médio e o da análise de mecanismos é a principal lacuna analítica. Para pesquisas sobre desigualdade territorial, construção estatal e mobilização étnica, o paper oferece instrumental metodológico (HEG dataset, medidas de rede) potencialmente replicável em outros contextos históricos. A restrição à Europa histórica é simultaneamente força (comparabilidade institucional relativa) e limitação (escopo). O caso francês como outlier integrador — não como paradigma — é uma das contribuições interpretativas mais interessantes do paper para a teoria comparada do nation-building.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<hr>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<p>Como se trata de um artigo único (não de livro), esta seção sintetiza a progressão argumentativa interna por grandes blocos:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 30%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Bloco</th>
<th style="text-align: left;">Título</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Introdução</td>
<td style="text-align: left;">Railway Construction and Separatist Mobilization in Europe</td>
<td style="text-align: left;">Apresentação do puzzle e da tese</td>
<td style="text-align: left;">Estabelece a tensão entre teoria integracionista e evidência histórica de desintegração; define o objeto (separatismo étnico); anuncia os três mecanismos e os achados principais</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bloco 1</td>
<td style="text-align: left;">Modernization and Nationalism in the Literature</td>
<td style="text-align: left;">Revisão de literatura</td>
<td style="text-align: left;">Mapeia as duas tradições (integração vs.&nbsp;separatismo); identifica três lacunas que o artigo endereça (abrangência comparada, mecanismos, subnacionalidade)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bloco 2</td>
<td style="text-align: left;">Railways and Nationalist Mobilization</td>
<td style="text-align: left;">Fundamento teórico</td>
<td style="text-align: left;">Desenvolve os três mecanismos (M1 mercado, M2 alcance estatal, M3 conectividade interna); deriva H1, H2 (a–f) e H3 (a–c)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bloco 3</td>
<td style="text-align: left;">Data and Variables</td>
<td style="text-align: left;">Operacionalização</td>
<td style="text-align: left;">Descreve HEG, CShapes 2.0, train.eryx.net e a construção do outcome combinado; justifica a unidade de análise (segmento étnico-ano)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bloco 4</td>
<td style="text-align: left;">Analyses and Results</td>
<td style="text-align: left;">Análise empírica principal</td>
<td style="text-align: left;">DiD (TWFE e 2S-DiD): confirma H1 (efeito médio positivo e imediato); event study valida tendências paralelas; IV reforça causalidade</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bloco 5</td>
<td style="text-align: left;">Testing Conditional Hypotheses</td>
<td style="text-align: left;">Análise de heterogeneidade</td>
<td style="text-align: left;">Marginal effects e binning: confirma H2b, H2c, H2d, H2e; H2a (distância linguística) tem suporte fraco; qualifica o efeito médio com estrutura contextual</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bloco 6</td>
<td style="text-align: left;">Exploring Causal Mechanisms</td>
<td style="text-align: left;">Extensão do argumento</td>
<td style="text-align: left;">Mecanismos desagregados via medidas de rede: M2 reduz separatismo, M3 aumenta; M1 sem efeito independente — explica <em>por quê</em> o efeito médio é positivo</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão</td>
<td style="text-align: left;">Conclusion</td>
<td style="text-align: left;">Síntese e agenda</td>
<td style="text-align: left;">Sintetiza que a experiência francesa é exceção, não paradigma; sinaliza agenda para tecnologias de comunicação contemporâneas; reconhece limites de generalização</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="introdução-pp.-3738" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-3738"><span class="header-section-number">1</span> Introdução (pp.&nbsp;37–38)</h2>
<section id="puzzle-objeto-e-contribuição-14" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="puzzle-objeto-e-contribuição-14"><span class="header-section-number">1.1</span> Puzzle, objeto e contribuição [§1–§4]</h3>
<p>O artigo abre estabelecendo o contexto de transformação acelerada que marcou a Europa dos séculos XIX e início do XX: economias industrializando-se, mercados em expansão, Estados centralizando-se e ideologias nacionalistas remodelando a vida pública e privada. Nesse cenário, as ferrovias ocupam um papel de destaque como a inovação tecnológica definitória da Primeira Revolução Industrial, conectando regiões antes isoladas, fomentando a industrialização e ampliando a capacidade dos Estados de alcançar e governar populações periféricas. A literatura clássica — Anderson (1983), Deutsch (1953), Gellner (1983) — associa exatamente esses processos à formação de identidades nacionais integradoras.</p>
<p>A contribuição central do artigo é investigar sistematicamente se essa expectativa integracionista se sustenta empiricamente. Os autores anunciam três mecanismos pelos quais as ferrovias podem afetar a competição entre o Estado central e grupos étnicos periféricos: (1) acesso a mercados e comunicação social (M1); (2) alcance e penetração do Estado (M2); (3) conectividade interna e capacidade de mobilização (M3). A premissa de fundo é que esses mecanismos operam em direções opostas e com diferentes temporalidades, de modo que o efeito líquido permanece uma questão empírica aberta.</p>
<p>Os autores identificam três lacunas na literatura existente que seu trabalho endereça. Primeiro, o debate permanece não resolvido quanto a se a modernização reforça o nacionalismo pró-Estado ou o separatismo. Segundo, há pouca orientação teórica ou empírica sobre as condições contextuais que levam à integração ou à desintegração. Terceiro, enquanto as contribuições clássicas carecem de evidência sistemática, os estudos micro recentes validam partes das teorias em países isolados sem oferecer perspectiva comparada — e é precisamente esse vácuo comparativo e subnacional que o artigo propõe preencher.</p>
</section>
<section id="achados-principais-antecipados-5" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="achados-principais-antecipados-5"><span class="header-section-number">1.2</span> Achados principais antecipados [§5]</h3>
<p>Já na introdução, os autores adiantam os três resultados centrais: em média, o acesso ferroviário está associado a um aumento de aproximadamente duas vezes na probabilidade de mobilização separatista; efeitos heterogêneos concentram-se em países com baixo desenvolvimento econômico, baixa capacidade estatal, grupos dominantes pequenos e minorias demograficamente grandes; e a análise desagregada de mecanismos mostra que a conectividade interna (M3) facilita a mobilização, enquanto o alcance estatal (M2) a inibe, e o acesso a mercados (M1) tem efeito marginal insignificante.</p>
<hr>
</section>
</section>
<section id="modernização-e-nacionalismo-na-literatura-pp.-3839" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="modernização-e-nacionalismo-na-literatura-pp.-3839"><span class="header-section-number">2</span> Modernização e Nacionalismo na Literatura (pp.&nbsp;38–39)</h2>
<section id="tradição-integracionista-69" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="tradição-integracionista-69"><span class="header-section-number">2.1</span> Tradição integracionista [§6–§9]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A distinção entre dois campos teóricos — integração nacional <em>vs.</em> separatismo reativo — estrutura toda a revisão de literatura e fornece as hipóteses concorrentes que o artigo se propõe a arbitrar empiricamente.</p>
</div>
</div>
<p>A revisão da literatura identifica duas grandes correntes no estudo da relação entre modernização e nacionalismo. A corrente integracionista espera homogeneização cultural crescente e identificação com a nação dominante. As abordagens políticas destacam o Estado moderno como agente central: em Hintze (1975), Posen (1993) e Tilly (1994), os Estados concebem e implementam programas de construção nacional em resposta a ameaças internacionais e domésticas. Em complemento, a perspectiva econômica de Gellner (1983) vê a transição de economias agrárias para industriais como força integradora pela via da padronização linguística. Deutsch (1953) enfatiza as redes de comunicação ampliadas pela inovação tecnológica, migração laboral e intercâmbio mercantil como motores industriais do nacionalismo.</p>
<p>Evidências empíricas dessa tradição incluem Weber (1976), que traça a formação da identidade nacional francesa no século XIX atribuindo papel central a industrialização, redes de transporte e políticas estatais. Estudos comparados mais recentes mostram que reformas educacionais estatais tornam-se mais prováveis quando governantes enfrentam ameaças internacionais (Aghion <em>et al.</em> 2019) ou domésticas (Alesina, Giuliano e Reich 2021; Paglayan 2022). Os autores assinalam, porém, que a mera adoção de tais políticas não garante seu sucesso — uma ressalva crítica para o desenho do artigo.</p>
</section>
<section id="tradição-separatista-e-lacunas-empíricas-1012" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="tradição-separatista-e-lacunas-empíricas-1012"><span class="header-section-number">2.2</span> Tradição separatista e lacunas empíricas [§10–§12]</h3>
<p>Apesar de seu impulso integracionista, as teorias modernistas também iluminam a desintegração nacional. Breuilly (1982) e Hechter (2000) esperam que a transição do domínio indireto ao direto dispare mobilização reativa, especialmente onde elites periféricas gozavam de autonomia anterior à centralização estatal. Deutsch (1953) nota que onde a mobilização social supera a assimilação, o conflito nacionalista torna-se mais provável. Gellner (1983) prevê que a combinação de diferença cultural preexistente e desenvolvimento desigual aciona o separatismo.</p>
<p>No plano empírico comparado, Wimmer e Feinstein (2010) usaram densidade ferroviária como <em>proxy</em> de modernização em amostra global de 145 territórios e encontraram nenhum efeito sobre a transição para Estados-nação. Os autores do presente artigo apontam um problema fundamental nesse design: o viés de retroprojeção (<em>hindsight bias</em>) resultante de usar unidades contemporâneas de observação que foram moldadas ao longo das fronteiras étnicas precisamente como resultado das transformações que o estudo quer explicar — citando Cederman, Girardin e Müller-Crepon (2023) e Müller-Crepon, Schvitz e Cederman (2025) como suporte. Em suma, a literatura existente oferece pouca orientação comparada e subnacional, o que motiva o design inovador do presente artigo.</p>
<hr>
</section>
</section>
<section id="teoria-ferrovias-e-mobilização-nacionalista-pp.-3943" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="teoria-ferrovias-e-mobilização-nacionalista-pp.-3943"><span class="header-section-number">3</span> Teoria: Ferrovias e Mobilização Nacionalista (pp.&nbsp;39–43)</h2>
<section id="o-contexto-pré-industrial-e-a-transição-1316" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="o-contexto-pré-industrial-e-a-transição-1316"><span class="header-section-number">3.1</span> O contexto pré-industrial e a transição [§13–§16]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conceito-chave:</strong> <em>Segmentos étnicos</em> são definidos como as intersecções espaciais entre áreas de assentamento étnico e fronteiras estatais — unidade de análise que permite capturar a variação subnacional e superar o viés de retroprojeção de estudos centrados em Estados.</p>
</div>
</div>
<p>O quadro teórico parte do diagnóstico de que, antes da industrialização, os governos centrais típicos da Europa governavam grupos não-dominantes de forma indireta, terceirizando tarefas governamentais a intermediários locais. Diferença cultural e formas mediadas de projetar poder significavam que a maioria dos Estados europeus operava mais como impérios do que como Estados nacionais modernos — os autores citam Burbank e Cooper (2010) e a noção historiográfica de “monarquias compostas” (Elliott 1992). A situação mudou quando industrialização, formas diretas de governo e ideologias nacionalistas varreram a Europa no século XIX.</p>
<p>O separatismo emergiu onde elites de grupos não-dominantes conseguiram mobilizar seguidores contra o Estado. Essas elites — velhas ou novas — dispunham de motivações específicas: a independência nacional garantiria acesso exclusivo aos benefícios da governança local, ameaçados pela expansão do Estado central (Hechter 2000); o apelo à unidade cultural em nível local facilitava coalizões entre velhas elites agrárias e classes médias emergentes com interesses econômicos desalinhados (Breuilly 1982); resistir à dominação de uma elite culturalmente estranha permitia mobilizar populações locais de forma mais eficaz (Gellner 1983); e o separatismo ampliava a perspectiva de apoio de grandes potências crescentemente receptivas ao ideal de autodeterminação.</p>
</section>
<section id="os-três-mecanismos-causais-1722" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="os-três-mecanismos-causais-1722"><span class="header-section-number">3.2</span> Os três mecanismos causais [§17–§22]</h3>
<p>Os autores elaboram três mecanismos pelos quais a construção ferroviária pode afetar as motivações e oportunidades para mobilização separatista, ilustrados na Figura 1 do artigo:</p>
<p><strong>M1 — Acesso a Mercados e Comunicação Social.</strong> Ferrovias aumentam os custos da secessão ao tornar a independência econômica menos atraente e ao fornecer incentivos materiais para que populações periféricas se orientem para uma economia nacional crescentemente integrada. Em alguns casos, podem até levar à assimilação cultural em identidades nacionais supralocais — processo descrito por Weber (1976) como precondição tecnológica para “mudança cultural radical” na França nacionalizadora. Maier (2016) chega a usar o termo “nacionalismo ferroviário” para descrever esses efeitos transformadores. No entanto, o mecanismo pode também operar em sentido contrário: onde grupos étnicos distintos competem pelos benefícios escassos da modernização, a integração econômica pode tornar a diferença mais saliente (Bates 1983), e Gellner (1983) descreve como fluxos de informação podem tornar periferias etnicamente distintas agudamente conscientes de seu status subordinado.</p>
<p><strong>M2 — Alcance e Domínio Direto do Estado.</strong> As ferrovias são parte do que Mann (1993) define como “poder infraestrutural” dos Estados europeus — a capacidade institucional de penetrar territórios e implementar decisões logisticamente. Ferrovias conectando a capital às regiões periféricas reduzem os tempos de deslocamento, ampliam a capacidade de monitoramento de burocratas e de repressão de elites locais, e tornam viáveis políticas de <em>nation-building</em> como educação de massa (Cermeño, Enflo e Lindvall 2022) e serviço militar. Ao mesmo tempo, o aumento da penetração estatal e do <em>nation-building</em> de cima para baixo pode acionar reações onde são percebidos como exploração — o que Hechter (1977) chama de “colonialismo interno” — alimentando o que Hechter (2000) denomina “nacionalismo reativo”.</p>
<p><strong>M3 — Conectividade Interna e Mobilização Social.</strong> Ferrovias que melhoram a conectividade interna de regiões periféricas — sem necessariamente ampliar o alcance do Estado ou o acesso ao mercado nacional — reduzem os custos de coordenação e ação coletiva de movimentos separatistas. A rápida difusão de informação, ideias e laços sociais entre líderes, ativistas e cidadãos é ingrediente fundamental para mobilização bem-sucedida (Granovetter 1978; Kuran 1992). Evidências empíricas de outros contextos sustentam esse mecanismo: García-Jimeno, Iglesias e Yildirim (2022) mostram como a conectividade ferroviária contribuiu para a difusão de movimentos de oposição nos EUA do século XIX; Brooke e Ketchley (2018) encontram efeito similar no Egito do entreguerras; Melander (2021) na Suécia pré-democrática.</p>
</section>
<section id="hipóteses-derivadas-2328" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="hipóteses-derivadas-2328"><span class="header-section-number">3.3</span> Hipóteses derivadas [§23–§28]</h3>
<blockquote class="blockquote">
<p>A hipótese central do artigo: <strong>Hipótese 1.</strong> A construção ferroviária em regiões não-dominantes aumenta a probabilidade de mobilização separatista, pelo menos no curto prazo.</p>
</blockquote>
<p>A lógica por trás da H1 é tripartite. Primeiro, ferrovias construídas <em>dentro</em> da área de assentamento de um grupo não-dominante melhoram inequivocamente a conectividade interna (M3), enquanto os mecanismos M1 e M2 dependem também de ferrovias fora dessa área. Segundo, tanto M1 quanto M2 podem fomentar resistência e não apenas integração. Terceiro — e crucialmente — os efeitos integradores da comunicação de mercado e do alcance estatal tendem a se desdobrar lentamente e a se materializar plenamente apenas no longo prazo, enquanto a reação ao backlash ocorre imediatamente. Na França, esse processo de integração levou um século inteiro após a Revolução Francesa (Weber 1976).</p>
<p>As hipóteses condicionais (H2a–f) especificam que o efeito desestabilizador do acesso ferroviário é ampliado por: distância cultural entre grupo não-dominante e grupo estatal (H2a); pequeno peso demográfico do grupo nacional dominante (H2b); grande população do grupo não-dominante (H2c); baixo nível de desenvolvimento econômico do país (H2d); baixa capacidade estatal (H2e); e regime autocrático (H2f). Já as hipóteses de mecanismo (H3a–c) preveem que acesso ao mercado nacional reduz separatismo (H3a), alcance estatal reduz separatismo (H3b), e conectividade interna aumenta separatismo (H3c).</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> Weber (1976, pp.&nbsp;205–7) destaca que, embora o processo geral de assimilação à identidade nacional francesa seja lento, a <em>primeira</em> chegada de uma ferrovia a uma localidade era um evento transformador abrupto que empurrava áreas rurais para fora de sua letargia pré-moderna. Em áreas etnicamente distintas, esse choque frequentemente funcionou como gatilho para a mobilização contra o Estado. [nota incluída por relevância argumentativa]</p>
</blockquote>
<hr>
</section>
</section>
<section id="dados-e-variáveis-pp.-4346" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="dados-e-variáveis-pp.-4346"><span class="header-section-number">4</span> Dados e Variáveis (pp.&nbsp;43–46)</h2>
<section id="dados-de-assentamentos-étnicos-e-fronteiras-históricas-2932" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="dados-de-assentamentos-étnicos-e-fronteiras-históricas-2932"><span class="header-section-number">4.1</span> Dados de assentamentos étnicos e fronteiras históricas [§29–§32]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conceito-chave:</strong> O dataset <em>Historical Ethnic Geography</em> (HEG) é o principal insumo original do artigo, construído a partir da seleção e padronização de 73 mapas históricos de assentamentos étnicos cobrindo o período 1816–1945.</p>
</div>
</div>
<p>As informações sobre assentamentos étnicos históricos provêm do dataset HEG, baseado em 73 mapas históricos (ver Seção A1 do Material Suplementar). Praticamente todas as categorias étnicas nesses mapas referem-se a marcadores de identidade linguística, refletindo uma característica reconhecida do nacionalismo europeu (Barbour e Carmichael 2000). As categorias são padronizadas com o auxílio da árvore linguística do <em>Ethnologue</em> (Lewis 2009) e consolidadas em uma lista-mestra invariante no tempo. A partir da sobreposição de todos os mapas disponíveis para cada combinação grupo-período, constroem-se polígonos de assentamento que constituem a “melhor estimativa” da distribuição espacial de cada grupo.</p>
<p>Dados espaciais sobre fronteiras estatais desde 1886 provêm do dataset CShapes 2.0 (Schvitz <em>et al.</em> 2022), com cobertura global desde a “Partilha da África”. Para a Europa, esses dados foram retroestendidos até 1816 a partir de fontes não-espaciais (Gleditsch e Ward 1999; Tir <em>et al.</em> 1998; Reed 2008), incluindo dezenas de microestados que existiam antes das unificações alemã e italiana. A intersecção espacial dos polígonos étnicos agregados com os dados anuais de fronteiras europeias gera a unidade de análise principal: <strong>segmentos étnicos-anos</strong> de 1816 a 1945. Para cada observação, calculam-se área absoluta e população (fonte: HYDE; Goldewijk, Beusen e Janssen 2010).</p>
</section>
<section id="variável-independente-principal-e-variáveis-de-desfecho-3337" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="variável-independente-principal-e-variáveis-de-desfecho-3337"><span class="header-section-number">4.2</span> Variável independente principal e variáveis de desfecho [§33–§37]</h3>
<p>Os dados geográficos sobre a rede ferroviária europeia em expansão provêm de train.eryx.net, um site construído por entusiastas ferroviários franceses (Bernard e Raymond Cima). Os autores georreferenciaram os tiles anuais do site e digitalizaram todas as linhas para construir um dataset geoespacial de ferrovias europeias de 1834 a 1922. O indicador de tratamento principal é uma variável dicotômica de <em>acesso ferroviário</em>, derivada da intersecção dos polígonos anuais de segmentos étnicos com os datasets anuais de linhas. Para operacionalizar os mecanismos M1–M3, utilizou-se a estrutura de rede para calcular proxies contínuas de conectividade do segmento com mercados econômicos nacionais, alcance do Estado e conectividade interna (ver Seção A4 do Material Suplementar).</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> A resolução anual do dataset ferroviário melhora substancialmente em relação à codificação de redes ferroviárias em nível de décadas utilizada em Martí-Henneberg (2021) e Alvarez-Palau, Díez-Minguela e Martí-Henneberg (2021). [nota incluída por relevância argumentativa]</p>
</blockquote>
<p>A variável de desfecho principal combina três dimensões: (1) <em>onset</em> de guerra civil etno-territorial (dummy codificada para guerras civis listadas em Gleditsch 2004 e Sarkees e Wayman 2010 que foram travadas em nome de grupos étnicos específicos); (2) secession bem-sucedida (dummy que assume valor 1 quando um segmento não-dominante se torna segmento dominante em um Estado recém-independente no ano <em>t+1</em>); e (3) uma nova medida de <em>claims</em> nacionalistas, codificando a primeira reivindicação de independência nacional plena ou autonomia regional feita por uma organização nacionalista ao nível do segmento étnico-ano. O indicador de desintegração combinado assume valor 1 se qualquer um dos três fenômenos ocorre em dado ano.</p>
<hr>
</section>
</section>
<section id="análises-e-resultados-pp.-4651" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="análises-e-resultados-pp.-4651"><span class="header-section-number">5</span> Análises e Resultados (pp.&nbsp;46–51)</h2>
<section id="especificação-principal-e-resultados-3842" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="especificação-principal-e-resultados-3842"><span class="header-section-number">5.1</span> Especificação principal e resultados [§38–§42]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conceito-chave:</strong> O modelo de <strong>diferença-em-diferenças de dois estágios</strong> (2S-DiD) de Gardner (2022) e Liu, Wang e Xu (2024) é utilizado para corrigir os vieses mecânicos de subestimação do TWFE convencional em settings de adoção escalonada (<em>staggered treatment</em>) com efeitos de tratamento heterogêneos.</p>
</div>
</div>
<p>A especificação de linha de base é um modelo de probabilidade linear TWFE com o indicador dicotômico de acesso ferroviário como variável de tratamento. Todos os modelos incluem efeitos fixos de segmento étnico e efeitos fixos de ano ou país-ano, além de uma variável de contagem de conflitos territoriais passados desde 1816 e dummies de <em>peace years</em> para abordar preocupações de causalidade reversa.</p>
<p>A Tabela 1 do artigo apresenta os resultados principais:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">100 × Secessão, Guerra Civil Territorial ou Claim</th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1)</td>
<td style="text-align: center;">(2)</td>
<td style="text-align: center;">(3)</td>
<td style="text-align: center;">(4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rails (S/N)</td>
<td style="text-align: center;">1,486***</td>
<td style="text-align: center;">1,076**</td>
<td style="text-align: center;">2,096***</td>
<td style="text-align: center;">1,693***</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0,352)</td>
<td style="text-align: center;">(0,341)</td>
<td style="text-align: center;">(0,493)</td>
<td style="text-align: center;">(0,446)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Segmento FE</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ano FE</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Não</td>
</tr>
<tr class="even">
<td style="text-align: left;">País-Ano FE</td>
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Sim</td>
<td style="text-align: center;">Não</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Estimador</td>
<td style="text-align: center;">TWFE</td>
<td style="text-align: center;">TWFE</td>
<td style="text-align: center;">2S-DiD</td>
<td style="text-align: center;">2S-DiD</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média VD</td>
<td style="text-align: center;">1,115</td>
<td style="text-align: center;">1,115</td>
<td style="text-align: center;">1,076</td>
<td style="text-align: center;">1,069</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Observações</td>
<td style="text-align: center;">13.007</td>
<td style="text-align: center;">13.007</td>
<td style="text-align: center;">11.711</td>
<td style="text-align: center;">9.818</td>
</tr>
</tbody>
</table>
<p>O modelo 1 indica que a probabilidade de separatismo aumenta 1,49 pp após a chegada da primeira ferrovia — aumento de mais do dobro da média amostral de 1,12 ocorrências por cem segmento-anos. O modelo 3 (2S-DiD) eleva a estimativa para 2,10 pp, equivalente a um aumento de 195% em relação à média, com a diferença em relação ao TWFE explicada pelo viés mecânico de subestimação que os modelos TWFE produzem em settings de adoção escalonada com heterogeneidade temporal de efeitos (Goodman-Bacon 2021).</p>
<p>O event study (Figura 3 do artigo) exibe tendências pré-tratamento predominantemente paralelas entre unidades tratadas e não tratadas, com coeficientes pré-tratamento próximos de zero e conjuntamente insignificantes na maioria das especificações. Os coeficientes pós-tratamento indicam aumento imediato no risco de conflito após a construção da primeira ferrovia, com efeitos ainda maiores aproximadamente 35 anos após o tratamento e tendência de atenuação a partir do 50º ano pós-tratamento, especialmente na especificação com FE de país-ano.</p>
</section>
<section id="robustez-variável-instrumental-4345" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="robustez-variável-instrumental-4345"><span class="header-section-number">5.2</span> Robustez: variável instrumental [§43–§45]</h3>
<p>Para endereçar o potencial de causalidade reversa (construção ferroviária motivada por considerações estratégicas relacionadas ao separatismo) e viés de variável omitida, os autores implementam uma estratégia de variável instrumental baseada em redes ferroviárias simuladas. O instrumento é construído colocando heuristicamente ferrovias para cada país-ano de forma a maximizar a conectividade da população estatal, utilizando dados populacionais invariantes no tempo estimados para 1830 (HYDE) — excluindo assim causas potencialmente enviesantes de ordem militar, demográfica ou econômica.</p>
<p>A Tabela 2 do artigo mostra que o instrumento é fortemente preditivo da construção ferroviária efetiva (estatística F de 39). O <em>reduced form</em> e o segundo estágio são positivos e estatisticamente significativos, com a estimativa do segundo estágio (2,341) ligeiramente superior ao TWFE mas similar ao 2S-DiD.</p>
</section>
<section id="robustez-adicional-definição-de-amostra-e-desagregação-do-desfecho-4648" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="robustez-adicional-definição-de-amostra-e-desagregação-do-desfecho-4648"><span class="header-section-number">5.3</span> Robustez adicional: definição de amostra e desagregação do desfecho [§46–§48]</h3>
<p>Verificações adicionais de robustez incluem: (1) censura de observações após o primeiro <em>onset</em> de separatismo, que produz estimativas menores mas positivas e significativas, interpretáveis como o efeito das ferrovias sobre o risco de separatismo dado nenhum esforço separatista anterior; (2) exclusão de unidades nunca tratadas, que produz efeitos similares ou maiores; (3) censura da amostra em 1922 (ano final dos dados ferroviários), com resultados robustos e de mesmo tamanho ou maiores. A desagregação do desfecho sugere que os resultados principais são impulsionados principalmente por guerras civis territoriais e <em>claims</em> nacionalistas; os efeitos sobre secessions bem-sucedidas (desfecho mais raro e extremo) são positivos e significativos no 2S-DiD mas pequenos e insignificantes no TWFE.</p>
</section>
<section id="hipóteses-condicionais-moderadores-contextuais-4953" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="hipóteses-condicionais-moderadores-contextuais-4953"><span class="header-section-number">5.4</span> Hipóteses condicionais: moderadores contextuais [§49–§53]</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A análise de heterogeneidade revela que o efeito desestabilizador das ferrovias não é universal — ele se concentra em contextos estruturalmente propensos à desintegração, o que requalifica a teoria modernizacionista: a experiência francesa de integração bem-sucedida não é o paradigma, mas a exceção.</p>
</div>
</div>
<p>A Figura 4 do artigo apresenta gráficos de efeito marginal e estimativas de <em>binning</em> (Hainmueller, Mummolo e Xu 2019) para os seis moderadores contextuais. Os resultados são:</p>
<ul>
<li><strong>H2a (distância linguística):</strong> coeficiente de interação positivo mas apenas marginalmente significativo. Os autores interpretam esse não-resultado como indicação de que, condicional a alguma diferença cultural, processos de politização e mobilização de grupo importam mais do que a distância cultural em si.</li>
<li><strong>H2b (participação do grupo dominante):</strong> coeficiente de interação negativo e significativo — ferrovias são particularmente prováveis de acender campanhas separatistas em países com grupos governantes relativamente pequenos. Os <em>binning plots</em> sugerem, porém, que o efeito linear é impulsionado por um pequeno número de casos com grupos dominantes especialmente pequenos.</li>
<li><strong>H2c (população do segmento):</strong> ferrovias impulsionam principalmente o separatismo em segmentos étnicos demograficamente grandes. Casos ilustrativos: bielorussos, poloneses e ucranianos na Rússia, tchecos, húngaros e italianos na Áustria-Hungria. Em segmentos muito pequenos, o efeito é negativo.</li>
<li><strong>H2d (PIB per capita):</strong> interação negativa e significativa — os resultados são impulsionados por país-anos relativamente pobres e menos industrializados, confirmando H2d.</li>
<li><strong>H2e (capacidade fiscal):</strong> estimativas de <em>binning</em> sugerem efeito significativamente maior em valores tipicamente baixos de capacidade fiscal. Casos de separatismo em Estados de baixa capacidade concentram-se nos Impérios Russo e Otomano e seus Estados sucessores.</li>
<li><strong>H2f (democracia liberal):</strong> interação negativa e significativa, mas os <em>binning plots</em> revelam que o efeito é mais alto em valores baixos a intermediários de democracia liberal, predominantemente nos Impérios Otomano e Russo durante a segunda metade do século XIX.</li>
</ul>
</section>
<section id="mecanismos-causais-desagregados-5457" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="mecanismos-causais-desagregados-5457"><span class="header-section-number">5.5</span> Mecanismos causais desagregados [§54–§57]</h3>
<p>A Tabela 3 apresenta os modelos TWFE nos quais as três medidas contínuas de rede substituem o indicador dicotômico de tratamento, testando H3a–c:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">100 × Secessão, Guerra Civil ou Claim</th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1)</td>
<td style="text-align: center;">(2)</td>
<td style="text-align: center;">(3)</td>
<td style="text-align: center;">(4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Acesso ao mercado nacional</td>
<td style="text-align: center;">−0,143+</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">−0,001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alcance do Estado</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">−0,008**</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">−0,008**</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conectividade interna</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">0,015*</td>
<td style="text-align: center;">0,016*</td>
</tr>
</tbody>
</table>
<p>Todos os coeficientes apontam na direção esperada. Melhorias no alcance estatal (M2) de um desvio padrão reduzem o risco de separatismo em 0,79 pp (70% da média amostral). A conectividade interna (M3) aumenta o risco em 0,34 pp por desvio padrão. O efeito do acesso ao mercado nacional torna-se pequeno e insignificante quando o alcance do Estado é controlado, sugerindo que o efeito negativo do Modelo 1 era capturado por melhores conexões com a capital — ou seja, M2 absorve M1.</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> Ver Tabela A17 na Seção A10 do Material Suplementar para resultados com medidas de rede padronizadas que facilitam a comparação de coeficientes. [nota incluída por relevância argumentativa]</p>
</blockquote>
<p>Os autores discutem uma interpretação alternativa: as redes ferroviárias nacionais em expansão exercem efeitos heterogêneos em diferentes contextos, e, na média, as respostas integrativas e desintegrativas se cancelam mutuamente (nota 16). O fato de que o modelo de linha de base mostra efeitos positivos da <em>primeira</em> conexão ferroviária em um segmento pode refletir que conexões periféricas na Europa histórica fortaleciam principalmente os laços locais antes de efetivamente ampliar a capacidade estatal ou integrar mercados nacionais.</p>
<hr>
</section>
</section>
<section id="conclusão-pp.-5152" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="conclusão-pp.-5152"><span class="header-section-number">6</span> Conclusão (pp.&nbsp;51–52)</h2>
<section id="síntese-e-releitura-da-teoria-modernizacionista-5860" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="síntese-e-releitura-da-teoria-modernizacionista-5860"><span class="header-section-number">6.1</span> Síntese e releitura da teoria modernizacionista [§58–§60]</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>A conclusão central do artigo inverte o ônus da prova na teoria modernizacionista: a integração nacional bem-sucedida via ferrovias não é o caso típico, mas o caso excepcional — e a excepcionalidade francesa pode ter distorcido décadas de teorização.</p>
</div>
</div>
<p>A conclusão retoma a premissa convencional de que a infraestrutura de transporte moderna fortaleceu o <em>nation-building</em> europeu, para então contrastá-la sistematicamente com a evidência produzida pelo artigo: se há algo, a construção ferroviária em regiões de minorias étnicas tendeu a ameaçar a integridade dos Estados e impérios europeus. A análise condicional revela as dimensões estruturais que dificultaram a integração nacional nos Estados multiétnicos, especialmente na Europa oriental — grupos minoritários grandes, participações populacionais pequenas dos grupos dominantes, baixa capacidade estatal e baixa renda per capita colocavam desafios formidáveis à centralização estatal e ao <em>nation-building</em> de cima para baixo.</p>
<p>A experiência francesa, amplamente tomada como paradigma da teoria modernizacionista, emerge dos dados como exceção notável. Em sentido complementar, os autores mostram como os efeitos agregados do acesso ferroviário mascaram efeitos opostos da estrutura da rede: o separatismo torna-se mais provável onde as ferrovias facilitam a mobilização pela melhoria da conectividade interna de regiões étnicas periféricas, e menos provável onde aproximam essas regiões da capital do Estado.</p>
</section>
<section id="agenda-de-pesquisa-61" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="agenda-de-pesquisa-61"><span class="header-section-number">6.2</span> Agenda de pesquisa [§61]</h3>
<p>Os autores situam o estudo em uma agenda mais ampla que analisa a integração e a desintegração nacionais por meio de diversas formas de comunicação social e mecanismos de formação de identidade: linhas telegráficas, redes viárias, educação de massa e meios de comunicação de massa. Há também uma agenda crescente sobre como processos de mobilização são influenciados por tecnologias mais recentes — rádio (Warren 2014), telefonia celular (Shapiro e Weidmann 2015), redes sociais (Gohdes 2020; Weidmann 2015). Os autores concluem com cautela explícita: embora o presente estudo sirva como lembrete de que avanços tecnológicos podem ter efeitos desintegradores, pesquisa empírica cuidadosa é necessária antes de aplicar seus achados a contextos além dos casos clássicos do <em>nation-building</em> europeu.</p>
<hr>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">7</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> A construção ferroviária em regiões habitadas por grupos étnicos não-dominantes na Europa de 1816 a 1945 aumentou, em média, a probabilidade de mobilização separatista em cerca do dobro da média amostral — contrariando a expectativa integracionista dominante na teoria modernizacionista.</p>
<p><strong>Natureza do argumento:</strong> Causal e heterogêneo. O artigo opera em três camadas argumentativas que se reforçam mutuamente: (1) estimação do efeito médio de tratamento via DiD, event study e IV; (2) análise de moderação contextual que especifica <em>quando</em> o efeito é amplificado ou atenuado; e (3) análise de mecanismos desagregados que explica <em>por que</em> o efeito médio é positivo — com a conectividade interna (M3) e o alcance do Estado (M2) operando em direções opostas.</p>
<p><strong>O que o texto demonstra vs.&nbsp;o que fica como hipótese ou agenda:</strong> O efeito causal médio (H1) está bem identificado pela convergência de três estratégias empíricas. A análise de heterogeneidade (H2) está bem sustentada pela abordagem de <em>binning</em> e pela convergência dos resultados condicionais. A análise de mecanismos (H3) é sugestiva mas metodologicamente mais fraca — por não utilizar um design DiD para as medidas contínuas de rede, a identificação causal dos mecanismos individuais requer premissas mais fortes. Fica como agenda: a exploração de heterogeneidade de efeitos entre contextos (a nota 16 reconhece essa limitação) e a extrapolação para tecnologias contemporâneas.</p>
<p><strong>Contribuição para o debate:</strong> O artigo faz três contribuições ao debate sobre modernização, nacionalismo e separatismo. Metodologicamente, produz o primeiro dataset geoespacial de assentamentos étnicos históricos europeus cruzado com dados anuais de construção ferroviária, superando o viés de retroprojeção dos estudos anteriores. Teoricamente, especifica os mecanismos contraditórios pelos quais ferrovias afetam o <em>nation-building</em> e identifica as condições contextuais que determinam o resultado. Empiricamente, demonstra que a experiência francesa de integração bem-sucedida é a exceção e não o paradigma — com implicações diretas para teorias de <em>nation-building</em> que tomaram o caso francês como referência normativa.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>