<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-08">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Case Selection Techniques in Case Study Research: A Menu of Qualitative and Quantitative Options – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1596dba0f6ebd5d6ff9514dff97656d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/tts-reader-1.0.0/tts-reader.js" defer="true"></script>
<link href="../site_libs/quarto-contrib/tts-reader-1.0.0/tts-reader.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Case Selection Techniques in Case Study Research: A Menu of Qualitative and Quantitative Options – Annotated Bibliography">
<meta property="og:description" content="Seawright, J. &amp; Gerring, J. (2008) — Political Research Quarterly, SAGE">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#introdução-a-tarefa-primordial-e-o-argumento-geral-pp.-294295" id="toc-introdução-a-tarefa-primordial-e-o-argumento-geral-pp.-294295" class="nav-link" data-scroll-target="#introdução-a-tarefa-primordial-e-o-argumento-geral-pp.-294295"><span class="header-section-number">1</span> Introdução — A Tarefa Primordial e o Argumento Geral (pp.&nbsp;294–295)</a>
  <ul class="collapse">
  <li><a href="#o-problema-da-seleção-como-tarefa-constitutiva-do-estudo-de-caso-13" id="toc-o-problema-da-seleção-como-tarefa-constitutiva-do-estudo-de-caso-13" class="nav-link" data-scroll-target="#o-problema-da-seleção-como-tarefa-constitutiva-do-estudo-de-caso-13"><span class="header-section-number">1.1</span> O problema da seleção como tarefa constitutiva do estudo de caso [§1–§3]</a></li>
  <li><a href="#a-lacuna-na-literatura-e-a-proposta-do-artigo-46" id="toc-a-lacuna-na-literatura-e-a-proposta-do-artigo-46" class="nav-link" data-scroll-target="#a-lacuna-na-literatura-e-a-proposta-do-artigo-46"><span class="header-section-number">1.2</span> A lacuna na literatura e a proposta do artigo [§4–§6]</a></li>
  </ul></li>
  <li><a href="#por-que-não-escolher-casos-aleatoriamente-p.-295" id="toc-por-que-não-escolher-casos-aleatoriamente-p.-295" class="nav-link" data-scroll-target="#por-que-não-escolher-casos-aleatoriamente-p.-295"><span class="header-section-number">2</span> Por Que Não Escolher Casos Aleatoriamente? (p.&nbsp;295)</a>
  <ul class="collapse">
  <li><a href="#monte-carlo-e-a-insuficiência-da-aleatorização-em-n-pequeno-79" id="toc-monte-carlo-e-a-insuficiência-da-aleatorização-em-n-pequeno-79" class="nav-link" data-scroll-target="#monte-carlo-e-a-insuficiência-da-aleatorização-em-n-pequeno-79"><span class="header-section-number">2.1</span> Monte Carlo e a insuficiência da aleatorização em N pequeno [§7–§9]</a></li>
  </ul></li>
  <li><a href="#técnicas-de-seleção-de-casos-enquadramento-geral-pp.-296297" id="toc-técnicas-de-seleção-de-casos-enquadramento-geral-pp.-296297" class="nav-link" data-scroll-target="#técnicas-de-seleção-de-casos-enquadramento-geral-pp.-296297"><span class="header-section-number">3</span> Técnicas de Seleção de Casos: Enquadramento Geral (pp.&nbsp;296–297)</a>
  <ul class="collapse">
  <li><a href="#os-dois-objetivos-da-seleção-e-os-sete-tipos-1012" id="toc-os-dois-objetivos-da-seleção-e-os-sete-tipos-1012" class="nav-link" data-scroll-target="#os-dois-objetivos-da-seleção-e-os-sete-tipos-1012"><span class="header-section-number">3.1</span> Os dois objetivos da seleção e os sete tipos [§10–§12]</a></li>
  <li><a href="#caveats-metodológicos-e-o-que-o-artigo-não-cobre-13" id="toc-caveats-metodológicos-e-o-que-o-artigo-não-cobre-13" class="nav-link" data-scroll-target="#caveats-metodológicos-e-o-que-o-artigo-não-cobre-13"><span class="header-section-number">3.2</span> Caveats metodológicos e o que o artigo não cobre [§13]</a></li>
  </ul></li>
  <li><a href="#o-caso-típico-pp.-298300" id="toc-o-caso-típico-pp.-298300" class="nav-link" data-scroll-target="#o-caso-típico-pp.-298300"><span class="header-section-number">4</span> O Caso Típico (pp.&nbsp;298–300)</a>
  <ul class="collapse">
  <li><a href="#definição-e-lógica-analítica-1416" id="toc-definição-e-lógica-analítica-1416" class="nav-link" data-scroll-target="#definição-e-lógica-analítica-1416"><span class="header-section-number">4.1</span> Definição e lógica analítica [§14–§16]</a></li>
  <li><a href="#operacionalização-quantitativa-e-o-exemplo-empírico-1719" id="toc-operacionalização-quantitativa-e-o-exemplo-empírico-1719" class="nav-link" data-scroll-target="#operacionalização-quantitativa-e-o-exemplo-empírico-1719"><span class="header-section-number">4.2</span> Operacionalização quantitativa e o exemplo empírico [§17–§19]</a></li>
  </ul></li>
  <li><a href="#o-caso-diverso-pp.-300301" id="toc-o-caso-diverso-pp.-300301" class="nav-link" data-scroll-target="#o-caso-diverso-pp.-300301"><span class="header-section-number">5</span> O Caso Diverso (pp.&nbsp;300–301)</a>
  <ul class="collapse">
  <li><a href="#lógica-de-máxima-variância-e-tipos-de-diversidade-2022" id="toc-lógica-de-máxima-variância-e-tipos-de-diversidade-2022" class="nav-link" data-scroll-target="#lógica-de-máxima-variância-e-tipos-de-diversidade-2022"><span class="header-section-number">5.1</span> Lógica de máxima variância e tipos de diversidade [§20–§22]</a></li>
  <li><a href="#operacionalização-e-alcance-da-representatividade-2324" id="toc-operacionalização-e-alcance-da-representatividade-2324" class="nav-link" data-scroll-target="#operacionalização-e-alcance-da-representatividade-2324"><span class="header-section-number">5.2</span> Operacionalização e alcance da representatividade [§23–§24]</a></li>
  </ul></li>
  <li><a href="#o-caso-extremo-pp.-301302" id="toc-o-caso-extremo-pp.-301302" class="nav-link" data-scroll-target="#o-caso-extremo-pp.-301302"><span class="header-section-number">6</span> O Caso Extremo (pp.&nbsp;301–302)</a>
  <ul class="collapse">
  <li><a href="#distinção-conceitual-em-relação-ao-caso-desviante-2526" id="toc-distinção-conceitual-em-relação-ao-caso-desviante-2526" class="nav-link" data-scroll-target="#distinção-conceitual-em-relação-ao-caso-desviante-2526"><span class="header-section-number">6.1</span> Distinção conceitual em relação ao caso desviante [§25–§26]</a></li>
  <li><a href="#operacionalização-e-a-questão-da-seleção-no-dependente-2728" id="toc-operacionalização-e-a-questão-da-seleção-no-dependente-2728" class="nav-link" data-scroll-target="#operacionalização-e-a-questão-da-seleção-no-dependente-2728"><span class="header-section-number">6.2</span> Operacionalização e a questão da “seleção no dependente” [§27–§28]</a></li>
  </ul></li>
  <li><a href="#o-caso-desviante-pp.-302303" id="toc-o-caso-desviante-pp.-302303" class="nav-link" data-scroll-target="#o-caso-desviante-pp.-302303"><span class="header-section-number">7</span> O Caso Desviante (pp.&nbsp;302–303)</a>
  <ul class="collapse">
  <li><a href="#deviantness-como-função-de-um-modelo-causal-2931" id="toc-deviantness-como-função-de-um-modelo-causal-2931" class="nav-link" data-scroll-target="#deviantness-como-função-de-um-modelo-causal-2931"><span class="header-section-number">7.1</span> Deviantness como função de um modelo causal [§29–§31]</a></li>
  <li><a href="#operacionalização-e-exemplo-empírico-3233" id="toc-operacionalização-e-exemplo-empírico-3233" class="nav-link" data-scroll-target="#operacionalização-e-exemplo-empírico-3233"><span class="header-section-number">7.2</span> Operacionalização e exemplo empírico [§32–§33]</a></li>
  </ul></li>
  <li><a href="#o-caso-influente-pp.-303304" id="toc-o-caso-influente-pp.-303304" class="nav-link" data-scroll-target="#o-caso-influente-pp.-303304"><span class="header-section-number">8</span> O Caso Influente (pp.&nbsp;303–304)</a>
  <ul class="collapse">
  <li><a href="#influência-versus-desvio-uma-distinção-essencial-3436" id="toc-influência-versus-desvio-uma-distinção-essencial-3436" class="nav-link" data-scroll-target="#influência-versus-desvio-uma-distinção-essencial-3436"><span class="header-section-number">8.1</span> Influência versus desvio: uma distinção essencial [§34–§36]</a></li>
  <li><a href="#hat-matrix-cooks-distance-e-o-exemplo-nepal-3739" id="toc-hat-matrix-cooks-distance-e-o-exemplo-nepal-3739" class="nav-link" data-scroll-target="#hat-matrix-cooks-distance-e-o-exemplo-nepal-3739"><span class="header-section-number">8.2</span> Hat matrix, Cook’s distance e o exemplo Nepal [§37–§39]</a></li>
  </ul></li>
  <li><a href="#os-casos-mais-similar-e-mais-diferente-pp.-304306" id="toc-os-casos-mais-similar-e-mais-diferente-pp.-304306" class="nav-link" data-scroll-target="#os-casos-mais-similar-e-mais-diferente-pp.-304306"><span class="header-section-number">9</span> Os Casos Mais Similar e Mais Diferente (pp.&nbsp;304–306)</a>
  <ul class="collapse">
  <li><a href="#a-lógica-do-método-mais-similar-e-sua-conexão-com-mill-4042" id="toc-a-lógica-do-método-mais-similar-e-sua-conexão-com-mill-4042" class="nav-link" data-scroll-target="#a-lógica-do-método-mais-similar-e-sua-conexão-com-mill-4042"><span class="header-section-number">9.1</span> A lógica do método mais similar e sua conexão com Mill [§40–§42]</a></li>
  <li><a href="#propensity-score-matching-como-ferramenta-de-operacionalização-4345" id="toc-propensity-score-matching-como-ferramenta-de-operacionalização-4345" class="nav-link" data-scroll-target="#propensity-score-matching-como-ferramenta-de-operacionalização-4345"><span class="header-section-number">9.2</span> Propensity-score matching como ferramenta de operacionalização [§43–§45]</a></li>
  <li><a href="#o-método-dos-casos-mais-diferentes-46" id="toc-o-método-dos-casos-mais-diferentes-46" class="nav-link" data-scroll-target="#o-método-dos-casos-mais-diferentes-46"><span class="header-section-number">9.3</span> O método dos casos mais diferentes [§46]</a></li>
  </ul></li>
  <li><a href="#complicações-pp.-306307" id="toc-complicações-pp.-306307" class="nav-link" data-scroll-target="#complicações-pp.-306307"><span class="header-section-number">10</span> Complicações (pp.&nbsp;306–307)</a>
  <ul class="collapse">
  <li><a href="#combinações-de-estratégias-e-mudança-de-estratégia-no-curso-da-pesquisa-4749" id="toc-combinações-de-estratégias-e-mudança-de-estratégia-no-curso-da-pesquisa-4749" class="nav-link" data-scroll-target="#combinações-de-estratégias-e-mudança-de-estratégia-no-curso-da-pesquisa-4749"><span class="header-section-number">10.1</span> Combinações de estratégias e mudança de estratégia no curso da pesquisa [§47–§49]</a></li>
  <li><a href="#o-problema-irresolvível-da-representatividade-5051" id="toc-o-problema-irresolvível-da-representatividade-5051" class="nav-link" data-scroll-target="#o-problema-irresolvível-da-representatividade-5051"><span class="header-section-number">10.2</span> O problema irresolvível da representatividade [§50–§51]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">11</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Case Selection Techniques in Case Study Research: A Menu of Qualitative and Quantitative Options</h1>
<p class="subtitle lead">Seawright, J. &amp; Gerring, J. (2008) — Political Research Quarterly, SAGE</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Methodology</div>
    <div class="quarto-category">Comparative Politics</div>
    <div class="quarto-category">Case Study Research</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 8, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Seawright, J., &amp; Gerring, J. (2008). Case selection techniques in case study research: A menu of qualitative and quantitative options. <em>Political Research Quarterly</em>, <em>61</em>(2), 294–308. https://doi.org/10.1177/1065912907313077</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Entrada BibTeX → Seawright-Gerring2008
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">Seawright</span>-<span class="ot">Gerring2008</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>  = {Seawright, Jason and Gerring, John},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>   = {Case Selection Techniques in Case Study Research: A Menu of Qualitative and Quantitative Options},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>    = {2008},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">journal</span> = {Political Research Quarterly},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">volume</span>  = {61},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">number</span>  = {2},</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span>   = {294--308},</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">doi</span>     = {10.1177/1065912907313077},</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>Última atualização: 2026-05-08 Modelo: Perplexity — Claude Sonnet 4.6 Prompt Version: v17.2 2026-05-08 | Ficha antes do fichamento Gerado em: 2026-05-08T21:44:00-03:00 Ocasião da Leitura: ___</p>
<hr>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.2</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A pergunta pressupõe que os problemas de seleção amostral em estudos de caso podem ser sistematizados; a vulnerabilidade central é saber se a sistematização proposta é viável quando os pressupostos de dados e especificação do modelo não se sustentam.</td>
<td style="text-align: left;">Como pesquisadores devem selecionar casos de um universo amplo para análise intensiva em estudos de caso? Questão explicativa-metodológica; explicitada pelos autores na introdução.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">As questões secundárias são derivadas da central e bem integradas; a lacuna é que a questão da independência dos casos é mencionada apenas de passagem (nota 1).</td>
<td style="text-align: left;">(1) Por que a amostragem aleatória é insuficiente em amostras muito pequenas? (2) Quais técnicas específicas servem a cada objetivo analítico (exploratório vs.&nbsp;confirmatório)? (3) Como técnicas quantitativas disponíveis operacionalizam cada estratégia de seleção?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno: a literatura tinha nomes para tipos de caso mas não oferecia procedimentos formalizados para populações grandes. A generalização do puzzle para além de estudos de caso de países é plausível, mas os autores não a desenvolvem.</td>
<td style="text-align: left;">Puzzle metodológico: os termos clássicos de seleção de casos (extremo, desviante, mais similar etc.) são mal definidos e não oferecem orientação prática quando a população potencial é de centenas ou milhares de casos. Puzzle generalizável a qualquer pesquisa intensiva de unidades em ciências sociais.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese é clara e razoavelmente bem sustentada pelo exemplo empírico GDP–democracia. O claim central — de que técnicas estatísticas padrão podem ser reapropriadas para seleção de casos — é apresentado como contribuição genuína, mas o artigo demonstra viabilidade ilustrativa, não eficácia avaliada.</td>
<td style="text-align: left;">Propõe sete estratégias de seleção de casos (típico, diverso, extremo, desviante, influente, mais similar, mais diferente), cada uma associada a um objetivo analítico específico, e mostra como técnicas de regressão, análise de resíduos, hat matrix, Cook’s distance e propensity-score matching operacionalizam essas estratégias em populações grandes. Argumento metodológico-prescritivo.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O artigo é teórico-metodológico; a estratégia argumentativa combina revisão de literatura com exemplos ilustrativos quantitativos usando dados de PIB per capita (Summers &amp; Heston 1991) e democracia (Polity IV, 1995). O fichamento cobre a obra completa. As principais limitações de identificação são as do exemplo ilustrativo, não do argumento metodológico em si.</td>
<td style="text-align: left;">Artigo metodológico. Revisão de literatura sobre seleção de casos; dois experimentos de Monte Carlo para demonstrar insuficiência da aleatorização em N pequeno; aplicação ilustrativa de modelo OLS com termo quadrático sobre dados cross-section de 1995 (N ≈ 135 países). Não há análise causal original — o exemplo serve apenas como veículo heurístico.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP dos exemplos empíricos (PIB per capita e Polity2) é opaco: os autores não discutem quais países estão incluídos, perdas por missingness, ou como a amostra de 1995 se relaciona com o universo de inferência declarado. Isso enfraquece a força demonstrativa dos exemplos sem, contudo, invalidar o argumento metodológico.</td>
<td style="text-align: left;">Dados cross-section de países para 1995: PIB per capita (Penn World Tables) como X; Polity2 como Y. Unidade de análise: país-ano (único ponto temporal). O processo de geração dos exemplos é secundário ao argumento: servem para ilustrar como calcular resíduos, escores de extremidade e Cook’s distance. Viés de seleção no exemplo: só países com dados disponíveis em ambas as fontes para 1995.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">A contribuição mais robusta é a sistematização taxonômica (Tabela 1) e a vinculação de cada tipo de caso a um objetivo analítico e a uma técnica quantitativa correspondente. Os exemplos numéricos adicionam clareza operacional, mas não demonstram a superioridade das técnicas propostas.</td>
<td style="text-align: left;">(1) Sistematização de sete estratégias de seleção com suas lógicas analíticas e técnicas quantitativas correspondentes; (2) distinção clara entre exploratório e confirmatório como critério de escolha de estratégia; (3) proposta de integração qualitativo-quantitativo na fase de seleção (não apenas de análise); (4) identificação do propensity-score matching como ferramenta para seleção de casos “mais similares” em populações grandes.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">(a) Viés de circularidade: as técnicas quantitativas propostas dependem de um modelo bem especificado — mas o modelo é frequentemente o que o estudo de caso pretende corrigir ou construir. (b) O exemplo GDP–democracia assume log-linearidade e causalidade assimétrica (GDP → democracia) sem justificação suficiente, tornando os resultados ilustrativos sensíveis à especificação. (c) A generalização para casos não-nacionais (organizações, municípios, períodos históricos) não é discutida. (d) A lógica do “caso influente” como estratégia de seleção é a mais frágil: influência estatística não equivale a relevância teórica. (e) A discussão sobre representatividade permanece normativa (“o caso deve representar uma população”) sem oferecer testes robustos além do resíduo.</td>
<td style="text-align: left;">O argumento responde adequadamente à pergunta nos seus próprios termos (articulação taxonômica + exemplos ilustrativos), mas permanece vulnerável: (a) circularidade entre especificação do modelo e seleção do caso; (b) scope conditions implícitas (dados quantitativos disponíveis para a população; inferência causal como objetivo) não são adequadamente declaradas na introdução; (c) a técnica de propensity-score matching para seleção qualitativa é inovadora mas tratada de forma superficial — os autores usam um “modelo cartoon” e reconhecem isso, mas não discutem as consequências para a qualidade das comparações.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> modelo de propensity-score é simplificado (“cartoon model”); aleatorização é insuficiente para N pequeno; o artigo não cobre escolha de casos por características within-case; a seleção por razões pragmáticas é legítima mas não garante validade metodológica. <br> <strong>Não reconhecidas ou subestimadas:</strong> (1) circularidade entre modelo e seleção; (2) ausência de discussão sobre cases com missing data; (3) limitação às unidades nacionais no exemplo; (4) pressuposto implícito de que o pesquisador já conhece o modelo correto antes da seleção; (5) não discute o que fazer quando múltiplas estratégias produzem conjuntos de casos incompatíveis.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A moldura é coerente: o artigo opera dentro da tradição de <em>design-based inference</em> e da meta-metodologia comparativa (Eckstein, Lijphart, Przeworski &amp; Teune), estendendo-a com ferramentas econométricas contemporâneas. A ontologia implícita é realista moderada: assume que há relações causais regulares identificáveis por variação sistemática entre casos.</td>
<td style="text-align: left;">Metodologia das ciências sociais comparadas; tradição de King, Keohane &amp; Verba (1994) adaptada para estudos de caso; integração com literatura de matching estatístico (Rosenbaum &amp; Rubin 1983). A moldura é adequada à pergunta, embora negligencie perspectivas interpretativistas ou process-tracing puro, que têm lógicas distintas de seleção de caso.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo é sólido com a tradição qualitativa (Eckstein 1975, Lijphart 1971, Przeworski &amp; Teune 1970) e com a literatura de matching (Rosenbaum &amp; Rubin 1983, Ho et al.&nbsp;2007). Há subutilização de literatura sobre process-tracing (Bennett &amp; Checkel, ausente) e de análise comparativa de conjuntos (Ragin 2000 é citado mas não integrado).</td>
<td style="text-align: left;">Eckstein (1975), Lijphart (1971, 1975), Przeworski &amp; Teune (1970), King, Keohane &amp; Verba (1994), Rosenbaum &amp; Rubin (1983), George &amp; Bennett (2005), Ragin (2000), Ho et al.&nbsp;(2007), Brady &amp; Collier (2004).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">Texto identificado como artigo de periódico (único, 15 páginas, publicado em <em>Political Research Quarterly</em> v.61 n.2, 2008). Nenhuma inferência sobre tipo de texto foi necessária. Relevância direta para pesquisa comparada de políticas educacionais: a estratégia de caso típico e caso desviante é particularmente aplicável a estudos sobre sistemas de cotas no ensino superior brasileiro em perspectiva comparada. A Tabela 1 é a contribuição mais imediatamente operacionalizável.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<hr>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<p>O artigo não possui divisão em capítulos formais, mas organiza-se em blocos argumentativos claramente delimitados:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 30%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Bloco</th>
<th style="text-align: left;">Título</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Introdução</td>
<td style="text-align: left;">“Case Selection is the Primordial Task…” (pp.&nbsp;294–295)</td>
<td style="text-align: left;">Apresentação do puzzle e da tese</td>
<td style="text-align: left;">Estabelece que seleção de casos é subestudada e que os termos existentes são mal compreendidos; motiva a necessidade de sistematização</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bloco 1</td>
<td style="text-align: left;">“Why Not Choose Cases Randomly?” (p.&nbsp;295)</td>
<td style="text-align: left;">Fundamento teórico-negativo</td>
<td style="text-align: left;">Demonstra via Monte Carlo que aleatorização em N pequeno produz amostras sistematicamente não-representativas, justificando a seleção purposiva</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bloco 2</td>
<td style="text-align: left;">“Techniques of Case Selection” (pp.&nbsp;296)</td>
<td style="text-align: left;">Revisão e enquadramento</td>
<td style="text-align: left;">Define os objetivos duais da seleção (representatividade + variação útil), estabelece os sete tipos e lista caveats metodológicos essenciais</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bloco 3</td>
<td style="text-align: left;">“Typical Case” (pp.&nbsp;298–300)</td>
<td style="text-align: left;">Análise empírica ilustrativa</td>
<td style="text-align: left;">Operacionaliza o caso típico como baixo resíduo na regressão; apresenta modelo quadrático GDP–democracia</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bloco 4</td>
<td style="text-align: left;">“Diverse Cases” (pp.&nbsp;300–301)</td>
<td style="text-align: left;">Análise empírica ilustrativa</td>
<td style="text-align: left;">Operacionaliza diversidade via amostragem estratificada, análise discriminante e caminhos causais alternativos</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bloco 5</td>
<td style="text-align: left;">“Extreme Case” (pp.&nbsp;301–302)</td>
<td style="text-align: left;">Análise empírica ilustrativa</td>
<td style="text-align: left;">Operacionaliza extremidade como Z-score absoluto; aplica ao exemplo democracia (Qatar e Arábia Saudita como extremos)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bloco 6</td>
<td style="text-align: left;">“Deviant Case” (pp.&nbsp;302–303)</td>
<td style="text-align: left;">Análise empírica ilustrativa</td>
<td style="text-align: left;">Operacionaliza deviantness como alto resíduo absoluto; distingue do caso extremo pela referência a um modelo causal e não a uma distribuição univariada</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bloco 7</td>
<td style="text-align: left;">“Influential Case” (pp.&nbsp;303–304)</td>
<td style="text-align: left;">Análise empírica ilustrativa</td>
<td style="text-align: left;">Operacionaliza influência via Cook’s distance e hat matrix; identifica Nepal como caso mais influente no exemplo</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bloco 8</td>
<td style="text-align: left;">“Most Similar/Most Different Cases” (pp.&nbsp;304–306)</td>
<td style="text-align: left;">Extensão do argumento</td>
<td style="text-align: left;">Conecta matching estatístico (propensity scores) à lógica qualitativa clássica de Mill; ilustra com Costa Rica/Benin e Índia/Singapura</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão</td>
<td style="text-align: left;">“Complications” (pp.&nbsp;306–307)</td>
<td style="text-align: left;">Qualificação e síntese</td>
<td style="text-align: left;">Discute combinações de estratégias, mudança de estratégia no curso da pesquisa e o problema irresolvível da representatividade</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Divergências internas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nenhuma divergência substantiva identificada. Trata-se de artigo de dois autores com argumento unificado e progressivo.</p>
</div>
</div>
<hr>
</section>
<section id="introdução-a-tarefa-primordial-e-o-argumento-geral-pp.-294295" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-a-tarefa-primordial-e-o-argumento-geral-pp.-294295"><span class="header-section-number">1</span> Introdução — A Tarefa Primordial e o Argumento Geral (pp.&nbsp;294–295)</h2>
<section id="o-problema-da-seleção-como-tarefa-constitutiva-do-estudo-de-caso-13" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="o-problema-da-seleção-como-tarefa-constitutiva-do-estudo-de-caso-13"><span class="header-section-number">1.1</span> O problema da seleção como tarefa constitutiva do estudo de caso [§1–§3]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> A seleção de casos é inseparável da análise de casos em pesquisa intensiva de pequeno N, e os termos disponíveis na tradição qualitativa são insuficientes para orientar pesquisadores quando a população potencial é numerosa.</p>
</div>
</div>
<p>Seawright e Gerring abrem o artigo afirmando que a seleção de casos é a “tarefa primordial” (<em>primordial task</em>) do pesquisador de estudos de caso, pois ao escolher o caso, o pesquisador simultaneamente define a agenda analítica. Diferentemente da análise cross-case de grande N, onde amostragem e análise são etapas relativamente separáveis, o estudo de caso articula essas duas dimensões de maneira estruturalmente indissociável: o método de escolha e o método de análise “mal podem ser separados” quando o foco recai sobre uma ou poucas instâncias de um fenômeno mais amplo.</p>
<p>A maioria dos estudos de caso não é autorreferente — não busca apenas descrever o caso em si, mas elucidar características de uma população mais ampla. O caso escolhido é chamado a “desempenhar um papel heroico”: representar uma população frequentemente muito maior do que ele próprio. Se os casos forem países, a população pode ser uma região, um tipo de país ou o mundo inteiro em determinado período. Isso torna o problema da representatividade ineludível, ao mesmo tempo em que um caso genuinamente representativo é difícil de identificar a priori.</p>
<p>Os autores identificam três dificuldades específicas: (1) o problema da representatividade; (2) a necessidade de variação em dimensões teoricamente relevantes; e (3) o papel informal de casos de fundo (<em>background cases</em>), que participam da análise sem serem formalmente selecionados — o que torna a fronteira entre caso e população especialmente porosa nos estudos de caso.</p>
</section>
<section id="a-lacuna-na-literatura-e-a-proposta-do-artigo-46" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="a-lacuna-na-literatura-e-a-proposta-do-artigo-46"><span class="header-section-number">1.2</span> A lacuna na literatura e a proposta do artigo [§4–§6]</h3>
<p>Apesar da importância do tema, os autores diagnosticam que ele recebeu atenção relativamente escassa desde os trabalhos pioneiros de Eckstein (1975), Lijphart (1971, 1975) e Przeworski e Teune (1970). A literatura subsequente debateu longamente o viés de seleção amostral — Achen e Snidal (1989), Collier e Mahoney (1996), Geddes (1990), King, Keohane e Verba (1994) — mas não ofereceu soluções além daquelas implícitas nos clássicos.</p>
<p>Na ausência de tratamentos formais, os pesquisadores continuam a selecionar casos com base em considerações pragmáticas — tempo, recursos, expertise, acesso — ou na proeminência teórica do caso na literatura. Os autores reconhecem que esses são fatores legítimos, mas insistem que não oferecem justificação <em>metodológica</em> para preferir o caso A ao caso B. Mesmo quando selecionados por razões pragmáticas, é essencial que os pesquisadores compreendam retroativamente como as propriedades dos casos escolhidos se relacionam com o restante da população.</p>
<p>O artigo propõe, portanto, três contribuições: (1) clarificar os problemas metodológicos envolvidos na seleção de casos orientada à construção e teste de teorias causais gerais; (2) oferecer um menu mais abrangente de opções; (3) apresentar novas técnicas para seleção quando dados quantitativos estão disponíveis para a população, mostrando que técnicas estatísticas padrão podem ser proveitosamente empregadas nesse contexto de integração quali-quanti.</p>
<hr>
</section>
</section>
<section id="por-que-não-escolher-casos-aleatoriamente-p.-295" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="por-que-não-escolher-casos-aleatoriamente-p.-295"><span class="header-section-number">2</span> Por Que Não Escolher Casos Aleatoriamente? (p.&nbsp;295)</h2>
<section id="monte-carlo-e-a-insuficiência-da-aleatorização-em-n-pequeno-79" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="monte-carlo-e-a-insuficiência-da-aleatorização-em-n-pequeno-79"><span class="header-section-number">2.1</span> Monte Carlo e a insuficiência da aleatorização em N pequeno [§7–§9]</h3>
<blockquote class="blockquote">
<p><strong>Puzzle central:</strong> Se a aleatorização é o padrão-ouro para evitar viés de seleção em amostras grandes, por que ela falha sistematicamente em estudos comparativos de poucos casos?</p>
</blockquote>
<p>Os autores respondem à objeção mais óbvia contra seleção purposiva — a de que ela introduz viés de seleção — com dois experimentos de Monte Carlo. Em ambos, a variável de interesse varia de 0 a 1 com média 0,5 na população. No primeiro experimento, o computador gera 500 amostras aleatórias de N = 1.000 casos cada; no segundo, 500 amostras de N = 5.</p>
<p>Os resultados são reveladores: ambos os procedimentos produzem amostras não-enviesadas em média (0,499 e 0,508, respectivamente), mas diferem dramaticamente na variância. Com N = 1.000, o desvio padrão das médias amostrais é aproximadamente 0,009; com N = 5, sobe para 0,128. Isso demonstra que para estudos comparativos compostos de cinco casos ou menos — o padrão em muito da pesquisa comparativa intensiva — a aleatorização frequentemente produz amostras substancialmente não-representativas da população.</p>
<p>A conclusão é que, dada a insuficiência da aleatorização e os problemas da seleção puramente pragmática, o argumento por alguma forma de seleção <em>purposiva</em> é forte. Os métodos purposivos não eliminam a confiabilidade inerentemente limitada de generalizações a partir de N pequeno, mas podem contribuir significativamente ao processo inferencial, permitindo que pesquisadores escolham os casos mais adequados a uma estratégia analítica específica.</p>
<hr>
</section>
</section>
<section id="técnicas-de-seleção-de-casos-enquadramento-geral-pp.-296297" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="técnicas-de-seleção-de-casos-enquadramento-geral-pp.-296297"><span class="header-section-number">3</span> Técnicas de Seleção de Casos: Enquadramento Geral (pp.&nbsp;296–297)</h2>
<section id="os-dois-objetivos-da-seleção-e-os-sete-tipos-1012" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="os-dois-objetivos-da-seleção-e-os-sete-tipos-1012"><span class="header-section-number">3.1</span> Os dois objetivos da seleção e os sete tipos [§10–§12]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A seleção de casos em estudos de caso compartilha os mesmos objetivos duais da amostragem aleatória: (1) uma amostra representativa e (2) variação útil nas dimensões de interesse teórico. Os sete tipos derivam da forma como um caso se posiciona nessas dimensões dentro da população de interesse.</p>
</div>
</div>
<p>Os autores situam a proposta em relação à literatura existente: os termos típico, extremo, desviante, crucial, mais similar são reconhecíveis, mas mal compreendidos e frequentemente mal aplicados. O menu proposto articula sete estratégias — <strong>típico</strong>, <strong>diverso</strong>, <strong>extremo</strong>, <strong>desviante</strong>, <strong>influente</strong>, <strong>mais similar</strong> e <strong>mais diferente</strong> — cada qual pressupondo um objetivo metodológico distinto para a análise within-case.</p>
<p>Antes de apresentar as técnicas, os autores emitem quatro ressalvas importantes. Primeira: os procedimentos se aplicam a estudos de caso orientados à inferência causal sobre uma população mais ampla, não a estudos cujo objetivo é iluminar características específicas de um caso particular (esse segundo estilo é tratado em Gerring 2006). Segunda: o foco é em inferência causal, não descritiva ou preditiva. Terceira: as técnicas dependem de uma noção clara de qual é a população da inferência — se a população for desconhecida, as técnicas não podem ser implementadas. Quarta: para o uso de raciocínio estatístico, três condições devem ser satisfeitas: (a) a população deve ser grande o suficiente; (b) dados relevantes devem estar disponíveis; (c) os pressupostos-padrão da pesquisa estatística devem ser cuidadosamente considerados.</p>
</section>
<section id="caveats-metodológicos-e-o-que-o-artigo-não-cobre-13" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="caveats-metodológicos-e-o-que-o-artigo-não-cobre-13"><span class="header-section-number">3.2</span> Caveats metodológicos e o que o artigo não cobre [§13]</h3>
<p>Os autores delimitam explicitamente o escopo: a discussão ignora duas classes de considerações relevantes para a seleção. A primeira é pragmático-logística — proeminência teórica do caso na literatura, acessibilidade de campo, recursos disponíveis. Esses fatores são legítimos, mas não têm caráter metodológico; não afetam a validade da inferência. A segunda são as características <em>within-case</em> — a estrutura interna do caso que o torna mais ou menos adequado para uma estratégia analítica específica. Esse segundo fator é metodológico, mas está fora do escopo do presente artigo (remetido a Gerring e McDermott 2007).</p>
<p>A Tabela 1 — reproduzida abaixo — sintetiza os sete métodos, suas definições, técnicas de grande N correspondentes, usos analíticos e implicações de representatividade:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 27%">
<col style="width: 8%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Método</th>
<th style="text-align: left;">Definição</th>
<th style="text-align: left;">Técnica Large-N</th>
<th style="text-align: left;">Uso</th>
<th style="text-align: left;">Representatividade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Típico</td>
<td style="text-align: left;">Caso(s) exemplar(es) de uma relação cross-case estável</td>
<td style="text-align: left;">Caso de baixo resíduo (on-lier)</td>
<td style="text-align: left;">Confirmatório; sonda mecanismos causais</td>
<td style="text-align: left;">Por definição representativo na relação especificada</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diverso</td>
<td style="text-align: left;">Casos que exemplificam valores diversos de X, Y ou X/Y</td>
<td style="text-align: left;">Amostragem estratificada; análise discriminante</td>
<td style="text-align: left;">Exploratório ou confirmatório</td>
<td style="text-align: left;">Representativo no sentido mínimo da variação completa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Extremo</td>
<td style="text-align: left;">Caso(s) com valor extremo em X ou Y</td>
<td style="text-align: left;">Caso muitos desvios-padrão acima/abaixo da média</td>
<td style="text-align: left;">Exploratório; sonda causas de X ou efeitos de Y</td>
<td style="text-align: left;">Apenas comparativamente a uma amostra maior</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desviante</td>
<td style="text-align: left;">Caso(s) que desviam de relação causal conhecida</td>
<td style="text-align: left;">Caso de alto resíduo (outlier)</td>
<td style="text-align: left;">Exploratório/confirmatório; novas explicações ou refutação determinística</td>
<td style="text-align: left;">Problemática; resolvida se nova variável “absorver” o desvio</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Influente</td>
<td style="text-align: left;">Caso(s) com configurações influentes nas variáveis independentes</td>
<td style="text-align: left;">Hat matrix ou Cook’s distance</td>
<td style="text-align: left;">Confirmatório; verifica robustez da análise cross-case</td>
<td style="text-align: left;">Tipicamente não representativo</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mais similar</td>
<td style="text-align: left;">Casos similares em variáveis de controle, diferentes em X₁ e/ou Y</td>
<td style="text-align: left;">Matching estatístico</td>
<td style="text-align: left;">Exploratório/confirmatório</td>
<td style="text-align: left;">Representatividade proporcional à qualidade do match</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mais diferente</td>
<td style="text-align: left;">Casos diferentes em variáveis de controle, similares em X₁ e Y</td>
<td style="text-align: left;">Inverso do matching</td>
<td style="text-align: left;">Exploratório/confirmatório</td>
<td style="text-align: left;">Representatividade proporcional à qualidade do match</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="o-caso-típico-pp.-298300" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="o-caso-típico-pp.-298300"><span class="header-section-number">4</span> O Caso Típico (pp.&nbsp;298–300)</h2>
<section id="definição-e-lógica-analítica-1416" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="definição-e-lógica-analítica-1416"><span class="header-section-number">4.1</span> Definição e lógica analítica [§14–§16]</h3>
<p>O <strong>caso típico</strong> foca um caso que exemplifica uma relação cross-case estável — por construção, pode também ser chamado de <em>caso representativo</em>, como na literatura psicológica (Hersen e Barlow 1976). Como o caso típico é bem explicado pelo modelo existente, o interesse analítico recai no interior do caso: o pesquisador quer explorar os mecanismos causais em operação em uma relação cross-case geral. Essa exploração pode conduzir a diferentes conclusões. Se a teoria sugere um caminho causal específico, o pesquisador pode realizar uma investigação de <em>pattern-matching</em>, avaliando se as evidências do caso validam os mecanismos estipulados. Alternativamente, o pesquisador pode mostrar que os mecanismos são diferentes dos presumidos, ou que não há mecanismos plausíveis conectando X ao resultado Y — nesse último caso, o design de caso típico pode fornecer evidência <em>desconfirmatória</em> de uma proposição causal geral.</p>
</section>
<section id="operacionalização-quantitativa-e-o-exemplo-empírico-1719" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="operacionalização-quantitativa-e-o-exemplo-empírico-1719"><span class="header-section-number">4.2</span> Operacionalização quantitativa e o exemplo empírico [§17–§19]</h3>
<p>A operacionalização via grande N consiste em identificar o menor resíduo possível para todos os casos em uma análise multivariada. O resíduo — distância entre valor predito e valor observado — é o indicador de tipicidade: quanto menor, mais típico. Em amostras grandes, muitos casos podem ter resíduos igualmente próximos de zero; nesses casos, os autores recomendam seleção aleatória estratificada ou escolha por critérios não-metodológicos.</p>
<p>O exemplo utiliza a relação GDP per capita–democracia com dados de 1995. O modelo estimado é:</p>
<p>[E(_i) = 10{,}52 - 4{,}59 _i + 0{,}45 _i^2]</p>
<p>Os resíduos são computados e exibidos em histograma (Figura 2). Vinte e seis casos apresentam escore de tipicidade entre 0 e −1, qualificando-se para análise intensiva. Os autores observam que uma proporção maior de casos cai abaixo da linha de regressão do que acima, sugerindo ou incompletude do modelo ou distribuição não-normal do erro — aspecto que a análise within-case poderia elucidar.</p>
<blockquote class="blockquote">
<p><strong>Nota sobre limitações:</strong> Os autores advertem que o teste de tipicidade via resíduo é enganoso se o modelo estatístico for mal especificado. Um caso pode estar diretamente sobre a linha de regressão e ainda ser, em aspectos relevantes, atípico.</p>
</blockquote>
<hr>
</section>
</section>
<section id="o-caso-diverso-pp.-300301" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="o-caso-diverso-pp.-300301"><span class="header-section-number">5</span> O Caso Diverso (pp.&nbsp;300–301)</h2>
<section id="lógica-de-máxima-variância-e-tipos-de-diversidade-2022" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="lógica-de-máxima-variância-e-tipos-de-diversidade-2022"><span class="header-section-number">5.1</span> Lógica de máxima variância e tipos de diversidade [§20–§22]</h3>
<p>O <strong>método de casos diversos</strong> tem como objetivo primário cobrir a máxima variância nas dimensões relevantes. Requer ao mínimo dois casos que representem o espectro completo de valores de X, Y ou de uma relação X/Y específica. A investigação é exploratória quando focada em X ou Y isoladamente, e confirmatória quando focada na relação X/Y.</p>
<p>Para variáveis categóricas, a identificação da diversidade é direta: o pesquisador seleciona um caso de cada categoria. Para variáveis contínuas, os casos de valores extremos (alto e baixo) são selecionados, eventualmente com inclusão da média ou mediana. O pesquisador pode também buscar pontos de ruptura naturais na distribuição que correspondam a diferenças categoriais substantivas entre casos.</p>
<p>A diversidade pode também ser compreendida em termos de <em>caminhos causais</em>: se três variáveis X₁, X₂, X₃ causam Y independentemente (cada uma como causa suficiente — o que Elman 2005 e George e Bennett 2005 chamam de <em>causal equifinality</em>), o pesquisador pode selecionar casos que exemplifiquem cada mecanismo causal. Isso pode ser identificado por análise de caminhos, análise comparativa qualitativa (Ragin 2000), análise de sequências (Abbott e Tsay 2000) ou tipologias qualitativas.</p>
</section>
<section id="operacionalização-e-alcance-da-representatividade-2324" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="operacionalização-e-alcance-da-representatividade-2324"><span class="header-section-number">5.2</span> Operacionalização e alcance da representatividade [§23–§24]</h3>
<p>Para variáveis causais contínuas com resultado dicotômico, os autores sugerem análise discriminante para identificação de casos diversos. Para variáveis categóricas, a amostragem aleatória estratificada (Cochran 1977) é a técnica recomendada: o pesquisador identifica as categorias substantivas relevantes, determina quantos casos selecionar de cada uma, e então escolhe aleatoriamente dentro de cada categoria.</p>
<p>A representatividade do método diverso é de natureza mínima: a amostra cobre o espectro de variação da população, mas não necessariamente espelha a <em>distribuição</em> dessa variação. Se há mais casos com valor alto do que com valor baixo na população e o pesquisador seleciona um de cada, a amostra resultante não é perfeitamente representativa — ainda que o método diverso provavelmente tenha as maiores reivindicações de representatividade entre todos os métodos de pequeno N, incluindo o caso típico.</p>
<hr>
</section>
</section>
<section id="o-caso-extremo-pp.-301302" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="o-caso-extremo-pp.-301302"><span class="header-section-number">6</span> O Caso Extremo (pp.&nbsp;301–302)</h2>
<section id="distinção-conceitual-em-relação-ao-caso-desviante-2526" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="distinção-conceitual-em-relação-ao-caso-desviante-2526"><span class="header-section-number">6.1</span> Distinção conceitual em relação ao caso desviante [§25–§26]</h3>
<p>O <strong>método do caso extremo</strong> seleciona um caso por seu valor extremo na variável independente (X) ou dependente (Y) de interesse. Um valor extremo é uma observação distante da média de uma distribuição univariada — é <em>incomum</em>. Crucialmente, a raridade do valor é o que torna o caso valioso para análise, não a direção (positivo ou negativo). Isso distingue o caso extremo do caso desviante: casos extremos são julgados relativamente à média de uma distribuição univariada; casos desviantes são julgados relativamente a um modelo de relações causais.</p>
<p>O método é puramente exploratório — uma forma de sondar possíveis causas de Y ou possíveis efeitos de X de maneira aberta. Se o pesquisador já tem alguma noção dos fatores adicionais que podem afetar o resultado, deve recorrer a outro método. O método do caso extremo frequentemente serve como ponto de entrada em um tema, que é subsequentemente investigado com métodos mais determinados.</p>
</section>
<section id="operacionalização-e-a-questão-da-seleção-no-dependente-2728" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="operacionalização-e-a-questão-da-seleção-no-dependente-2728"><span class="header-section-number">6.2</span> Operacionalização e a questão da “seleção no dependente” [§27–§28]</h3>
<p>A extremidade (E) para o <em>i</em>-ésimo caso é definida como o valor absoluto do Z-score:</p>
<p>[E_i = ||]</p>
<p>No exemplo empírico, os autores calculam os escores de extremidade para o nível de democracia (Polity2) em 1995. A média do índice é 2,76 e o desvio padrão é 6,92. Os dois países com maior escore de extremidade (1,84) são Catar e Arábia Saudita, ambos classificados como −10 no sistema de 21 pontos da Polity — os regimes mais autocráticos da amostra.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>O método aparentemente viola a advertência clássica contra “selecionar no dependente” (Geddes 1990; King, Keohane e Verba 1994). Os autores respondem que essa crítica pressupõe que o caso extremo seria tratado como representativo de uma população — o que não é o uso adequado do método. O caso extremo sempre remete a uma amostra maior de casos de fundo que fornecem a variação completa. Desde que esses casos de fundo não sejam esquecidos, a análise não está sujeita a problemas de viés de seleção amostral. O método é, portanto, uma tentativa consciente de <em>maximizar</em> — não minimizar — a variância na dimensão de interesse.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="o-caso-desviante-pp.-302303" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="o-caso-desviante-pp.-302303"><span class="header-section-number">7</span> O Caso Desviante (pp.&nbsp;302–303)</h2>
<section id="deviantness-como-função-de-um-modelo-causal-2931" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="deviantness-como-função-de-um-modelo-causal-2931"><span class="header-section-number">7.1</span> Deviantness como função de um modelo causal [§29–§31]</h3>
<p>O <strong>método do caso desviante</strong> seleciona aquele caso que, por referência a algum entendimento geral de um tópico (teoria específica ou senso comum), demonstra um valor surpreendente — é mal explicado. O caso desviante está, portanto, intimamente ligado à investigação de anomalias teóricas. “Dizer desviante é implicar anômalo.”</p>
<p>A distinção em relação ao caso extremo é precisa: enquanto casos extremos são julgados relativamente à média de uma distribuição univariada, casos desviantes são julgados relativamente a um modelo de relações causais. A deviantness de um caso só pode ser avaliada relativamente ao modelo geral empregado — o que implica que a deviantness relativa de um caso tende a mudar sempre que o modelo geral é alterado.</p>
<p>O propósito usual é sondar novas explicações, ainda não especificadas, para Y. Nesse sentido, o método é apenas ligeiramente mais delimitado do que o método do caso extremo. O pesquisador espera que os processos causais internos ao caso desviante ilustrem algum fator causal aplicável a outros casos (desviantes). Há também um segundo uso, menos comum: se o pesquisador quer <em>refutar</em> uma proposição determinística, qualquer caso desviante serve, desde que pertença à população especificada (Dion 1998).</p>
</section>
<section id="operacionalização-e-exemplo-empírico-3233" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="operacionalização-e-exemplo-empírico-3233"><span class="header-section-number">7.2</span> Operacionalização e exemplo empírico [§32–§33]</h3>
<p>Em termos estatísticos, a seleção de caso desviante é o oposto da seleção de caso típico. A deviantness é definida como:</p>
<p>[(i) = |y_i - <em>i| = |y_i - b_0 + b_1 x</em>{1,i} + + b_K x_{K,i}|]</p>
<p>A deviantness varia de 0 (exatamente sobre a linha de regressão) até infinito positivo. No exemplo de democracia e riqueza, os oito países com escore de deviantness superior a 10 — Croácia, Cuba, Indonésia, Irã, Marrocos, Singapura, Síria e Uzbequistão — estão todos <em>abaixo</em> da linha de regressão (menos democráticos do que o GDP per capita preveria).</p>
<p>A representatividade do caso desviante é problemática por construção — o caso é atípico. Essa dificuldade é parcialmente resolvida se o pesquisador generalizar a proposição identificada pelo estudo de caso para outros casos: uma nova variável é adicionada ao modelo de referência, e o modelo modificado deve “puxar” o caso desviante em direção ao valor esperado. O caso desviante, idealmente, torna-se mais ou menos típico após a nova variável ser incorporada.</p>
<blockquote class="blockquote">
<p><strong>Nota 6:</strong> Os autores utilizam o termo <em>deviantness</em> em vez do mais natural <em>deviance</em> porque <em>deviance</em> já tem um significado distinto na estatística. [nota incluída por relevância argumentativa]</p>
</blockquote>
<hr>
</section>
</section>
<section id="o-caso-influente-pp.-303304" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="o-caso-influente-pp.-303304"><span class="header-section-number">8</span> O Caso Influente (pp.&nbsp;303–304)</h2>
<section id="influência-versus-desvio-uma-distinção-essencial-3436" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="influência-versus-desvio-uma-distinção-essencial-3436"><span class="header-section-number">8.1</span> Influência versus desvio: uma distinção essencial [§34–§36]</h3>
<p>O <strong>método do caso influente</strong> responde a uma motivação distinta das estratégias anteriores: a necessidade de verificar os pressupostos de algum modelo geral de relações causais. Aqui, o que importa não é se o caso se ajusta bem ou mal ao modelo em si, mas o quanto aquele caso afeta os resultados globais da análise para toda a população. Uma vez identificados os casos que influenciam as estimativas, é importante decidir se eles genuinamente pertencem à amostra (e se podem fornecer pistas sobre variáveis omitidas relevantes).</p>
<p>O objetivo do caso influente é explorar casos que podem ser influentes vis-à-vis uma teoria cross-case maior — não propor novas formulações teóricas (ainda que isso possa ser subproduto da análise).</p>
</section>
<section id="hat-matrix-cooks-distance-e-o-exemplo-nepal-3739" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="hat-matrix-cooks-distance-e-o-exemplo-nepal-3739"><span class="header-section-number">8.2</span> Hat matrix, Cook’s distance e o exemplo Nepal [§37–§39]</h3>
<p>Duas medidas quantitativas são discutidas. A primeira é a <strong>alavancagem</strong> (<em>leverage</em>), derivada da hat matrix. Uma característica importante: a hat matrix não depende dos valores do dependente. Assim, a alavancagem é uma medida de <em>influência potencial</em> — informa o quanto o caso faria diferença na estimativa final <em>se</em> tivesse um valor incomum em Y, sem revelar quanto o caso <em>efetivamente</em> diferencia as estimativas. É útil quando há incerteza a priori sobre os valores do dependente — situação comum em estudos de caso onde parte da contribuição é justamente a mensuração refinada de Y.</p>
<p>A segunda medida é a <strong>distância de Cook</strong> (<em>Cook’s distance</em>), que mede o quanto as estimativas dos parâmetros β₁ mudariam se determinado caso fosse omitido da análise. Essa estatística depende de dois componentes: o tamanho do resíduo e a alavancagem do caso. Os casos mais influentes são aqueles com alavancagem substancial <em>e</em> resíduo significativo — contribuem fortemente para as inferências extraídas da análise. Os autores utilizam Cook’s distance como medida primária no exemplo.</p>
<p>A Figura 4 exibe os escores para os países da amostra de 1995. A maioria apresenta Cook’s distances muito baixas. As três exceções mais sérias são Jamaica (74), Japão (75) e Nepal (105) — sendo Nepal o mais influente por ampla margem. Qualquer estudo de caso sobre casos influentes na relação democracia–desenvolvimento deveria começar por Nepal.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A estratégia do caso influente é a única entre as sete para a qual os autores afirmam explicitamente que a representatividade <em>não</em> é um critério relevante: o caso é escolhido precisamente porque se desvia da amostra como um todo de modo que não seria esperado de um caso representativo.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="os-casos-mais-similar-e-mais-diferente-pp.-304306" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="os-casos-mais-similar-e-mais-diferente-pp.-304306"><span class="header-section-number">9</span> Os Casos Mais Similar e Mais Diferente (pp.&nbsp;304–306)</h2>
<section id="a-lógica-do-método-mais-similar-e-sua-conexão-com-mill-4042" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="a-lógica-do-método-mais-similar-e-sua-conexão-com-mill-4042"><span class="header-section-number">9.1</span> A lógica do método mais similar e sua conexão com Mill [§40–§42]</h3>
<p>O <strong>método dos casos mais similares</strong> (<em>most similar method</em>) remonta ao trabalho clássico de J. S. Mill (1872) e é um dos mais reconhecidos na tradição qualitativa (Lijphart 1971, 1975; Przeworski e Teune 1970; Skocpol e Somers 1980). Em sua forma mais pura, o par de casos selecionados é similar em todas as variáveis independentes medidas, <em>exceto</em> na variável independente de interesse (X₁) — e difere no resultado (Y). A Tabela 2 formaliza essa lógica para o caso mais simples (dois casos, variáveis dicotômicas):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Caso</th>
<th style="text-align: left;">X₁</th>
<th style="text-align: left;">X₂</th>
<th style="text-align: left;">Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">−</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">−</td>
</tr>
</tbody>
</table>
<p>Do padrão de covariação — mesmas condições de fundo (X₂), diferença em X₁, diferença em Y — infere-se que a presença ou ausência de X₁ causa a variação em Y.</p>
</section>
<section id="propensity-score-matching-como-ferramenta-de-operacionalização-4345" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="propensity-score-matching-como-ferramenta-de-operacionalização-4345"><span class="header-section-number">9.2</span> Propensity-score matching como ferramenta de operacionalização [§43–§45]</h3>
<p>Para identificar tais casos em grandes populações, os autores recomendam técnicas de <em>matching</em> estatístico. A literatura sobre matching tem raízes na estatística (Rosenbaum e Rubin 1983), avançou na econometria (Hahn 1998; Hirano, Imbens e Ridder 2003) e chegou à ciência política (Ho et al.&nbsp;2007; Imai 2005). A lógica fundamenta-se na extensão da lógica experimental: em experimentos aleatorizados de grande N, tratamento e controle são similares em variáveis medidas e não medidas — e uma simples diferença de médias é suficiente para causalidade. Em estudos observacionais, o grupo de “tratamento” geralmente difere do “controle” em muitas dimensões confundidoras.</p>
<p>O <strong>matching exato</strong> — encontrar casos com exatamente os mesmos valores nas variáveis de controle — é praticamente impossível para variáveis contínuas. A alternativa é o <strong>matching aproximado</strong>, especificamente via <em>propensity-score matching</em>: estima-se um modelo da probabilidade de cada caso pertencer ao grupo de tratamento (condicional nas variáveis de matching), e casos com escores de propensão similares são pareados.</p>
<p>O exemplo ilustra a seleção de casos “mais similares” a Índia e Costa Rica para estudar riqueza e democracia. As variáveis de matching são a origem do sistema legal (britânico, francês, alemão, escandinavo ou socialista) e a latitude da capital do país. O propensity score de Costa Rica é 7,63; o de Benin, 7,58 — com PIB per capita de US$ 1.163 (versus US$ 5.486 da Costa Rica). Para a Índia (escore 8,02), Singapura tem escore 7,99 e PIB per capita de US$ 27.020 (versus US$ 2.066 da Índia). Esses dois pares — Costa Rica/Benin e Índia/Singapura — constituem casos mais similares para testar a relação riqueza–democracia.</p>
<blockquote class="blockquote">
<p><strong>Nota 9:</strong> Para boas introduções ao matching, os autores remetem a Ho et al.&nbsp;(2007), Morgan e Harding (2005), Rosenbaum (2004) e Rosenbaum e Silber (2001).</p>
</blockquote>
</section>
<section id="o-método-dos-casos-mais-diferentes-46" class="level3" data-number="9.3">
<h3 data-number="9.3" class="anchored" data-anchor-id="o-método-dos-casos-mais-diferentes-46"><span class="header-section-number">9.3</span> O método dos casos mais diferentes [§46]</h3>
<p>O <strong>método dos casos mais diferentes</strong> é a imagem especular do anterior. Em vez de buscar casos similares nos controles, busca-se casos diferentes em todas as variáveis de controle relevantes, mas similares na variável causal de interesse (X₁) e no resultado (Y). A técnica de grande N é o inverso do matching para o método mais similar. Os analistas tipicamente consideram esse design um instrumento mais fraco para inferência causal do que o método mais similar — tema tratado em Gerring (2007).</p>
<hr>
</section>
</section>
<section id="complicações-pp.-306307" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="complicações-pp.-306307"><span class="header-section-number">10</span> Complicações (pp.&nbsp;306–307)</h2>
<section id="combinações-de-estratégias-e-mudança-de-estratégia-no-curso-da-pesquisa-4749" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="combinações-de-estratégias-e-mudança-de-estratégia-no-curso-da-pesquisa-4749"><span class="header-section-number">10.1</span> Combinações de estratégias e mudança de estratégia no curso da pesquisa [§47–§49]</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>A seleção de casos não precisa — e frequentemente não deveria — aderir a uma única estratégia durante todo o curso de uma pesquisa. Muitos estudos de caso combinam estratégias, e a revisão da estratégia é normal e esperada conforme a pesquisa progride de modo exploratório para confirmatório.</p>
</div>
</div>
<p>Os sete tipos apresentados na Tabela 1 são intencionalmente apresentados como um <em>menu</em> — não como categorias mutuamente exclusivas. Muitos estudos de caso combinam e articulam estratégias, e onde os casos permitem uma variedade de estratégias empíricas, não há razão para não perseguir todas.</p>
<p>O segundo ponto é a mudança de status de um caso ao longo da investigação. Frequentemente, o pesquisador começa em modo exploratório e progride para o confirmatório — desenvolvendo uma hipótese X/Y específica. As estratégias ideais para exploração nem sempre são ideais para confirmação. Uma vez adotada uma hipótese específica, o pesquisador deve mudar de design. Três caminhos são possíveis: (1) explicar explicitamente que a pesquisa inicial foi exploratória e não foi construída para testar a hipótese que é agora o argumento central; (2) redesenhar o estudo após a nova hipótese ter sido formulada, possivelmente integrando novos casos ou variáveis; (3) simplesmente desenfatizar a porção da pesquisa que não mais aborda a hipótese revisada.</p>
</section>
<section id="o-problema-irresolvível-da-representatividade-5051" class="level3" data-number="10.2">
<h3 data-number="10.2" class="anchored" data-anchor-id="o-problema-irresolvível-da-representatividade-5051"><span class="header-section-number">10.2</span> O problema irresolvível da representatividade [§50–§51]</h3>
<p>A representatividade emerge como a complicação final e mais fundamental. Há apenas uma situação em que o pesquisador não precisa se preocupar com ela: o design de caso influente, onde o caso é escolhido precisamente por sua influência sobre um modelo cross-case e não se espera que seja representativo. Em todas as demais circunstâncias, os casos devem ser representativos da população de interesse de maneiras relevantes para a proposição em questão.</p>
<p>Em contextos de grande N, o resíduo do caso no modelo de maior confiança do pesquisador é um ponto de partida razoável para testar representatividade. Mas esse teste é tão bom quanto o modelo disponível: especificações incorretas ou procedimentos de modelagem inadequados podem enviesar a avaliação de “tipicidade” de cada caso. Dado o peso explicativo que casos individuais devem suportar em análises de estudo de caso, os autores recomendam ir além do teste de resíduo e incorporar raciocínio dedutivo — expectativas sobre as relações causais de interesse e sobre o caso escolhido. Em suma, estudos de caso (com as duas exceções já apontadas) repousam sobre uma sinédoque pressuposta: o caso deve representar uma população. Se essa premissa não se sustentar, a utilidade do estudo de caso é severamente comprometida.</p>
<hr>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">11</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> A seleção de casos em estudos de caso pode e deve ser sistematizada por meio de sete estratégias distintas — típico, diverso, extremo, desviante, influente, mais similar e mais diferente — cada qual orientada a um objetivo analítico específico e operacionalizável por técnicas estatísticas padrão quando dados quantitativos estão disponíveis para a população de interesse.</p>
<p><strong>Natureza do argumento:</strong> Metodológico-prescritivo. O artigo não realiza análise causal original, mas reapropria técnicas existentes (análise de resíduos, Z-scores, Cook’s distance, propensity-score matching) para um novo contexto — a fase de <em>design</em> da pesquisa qualitativa.</p>
<p><strong>O que o texto demonstra vs.&nbsp;o que permanece como hipótese:</strong> O artigo demonstra a <em>viabilidade ilustrativa</em> das técnicas propostas por meio de um exemplo empírico unificado (GDP per capita e democracia, dados de 1995). Não demonstra a <em>superioridade</em> das técnicas em termos de validade inferencial em estudos de caso reais, nem avalia como os diferentes métodos interagem quando aplicados simultaneamente. A eficácia dos métodos para seleção de casos fora do paradigma de inferência causal quantitativa (process-tracing, comparativo-histórico) permanece como agenda aberta.</p>
<p><strong>Contribuição para o debate mais amplo:</strong> O artigo insere-se no esforço de integração qualitativo-quantitativa em ciências sociais (Brady e Collier 2004; George e Bennett 2005; King, Keohane e Verba 1994) e representa a contribuição mais sistematizada e pedagogicamente acessível ao problema da seleção de casos até sua data de publicação. A Tabela 1 tornou-se referência canônica no campo. A principal vulnerabilidade duradoura é a circularidade entre especificação do modelo quantitativo e seleção do caso qualitativo — limitação que o artigo reconhece mas não resolve.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>