<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-04-18">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Equilibrium Price Responses to Targeted Student Financial Aid – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-446ba4faaf7890b510536beef49c91e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Equilibrium Price Responses to Targeted Student Financial Aid – Annotated Bibliography">
<meta property="og:description" content="Barahona, Dobbin &amp; Otero (2026)">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introdução-pp.-17" id="toc-introdução-pp.-17" class="nav-link active" data-scroll-target="#introdução-pp.-17"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–7)</a>
  <ul class="collapse">
  <li><a href="#motivação-e-puzzle-central-13" id="toc-motivação-e-puzzle-central-13" class="nav-link" data-scroll-target="#motivação-e-puzzle-central-13"><span class="header-section-number">1.1</span> Motivação e puzzle central [§1–§3]</a></li>
  <li><a href="#estratégia-do-artigo-e-achados-em-síntese-47" id="toc-estratégia-do-artigo-e-achados-em-síntese-47" class="nav-link" data-scroll-target="#estratégia-do-artigo-e-achados-em-síntese-47"><span class="header-section-number">1.2</span> Estratégia do artigo e achados em síntese [§4–§7]</a></li>
  <li><a href="#contribuições-à-literatura-811" id="toc-contribuições-à-literatura-811" class="nav-link" data-scroll-target="#contribuições-à-literatura-811"><span class="header-section-number">1.3</span> Contribuições à literatura [§8–§11]</a></li>
  </ul></li>
  <li><a href="#framework-conceitual-efeitos-de-preço-do-auxílio-focalizado-pp.-712" id="toc-framework-conceitual-efeitos-de-preço-do-auxílio-focalizado-pp.-712" class="nav-link" data-scroll-target="#framework-conceitual-efeitos-de-preço-do-auxílio-focalizado-pp.-712"><span class="header-section-number">2</span> Framework Conceitual: Efeitos de Preço do Auxílio Focalizado (pp.&nbsp;7–12)</a>
  <ul class="collapse">
  <li><a href="#subsídio-focalizado-num-sistema-de-demanda-linear-1217" id="toc-subsídio-focalizado-num-sistema-de-demanda-linear-1217" class="nav-link" data-scroll-target="#subsídio-focalizado-num-sistema-de-demanda-linear-1217"><span class="header-section-number">2.1</span> Subsídio focalizado num sistema de demanda linear [§12–§17]</a></li>
  <li><a href="#efeitos-de-preço-do-auxílio-focalizado-num-sistema-de-demanda-flexível-1823" id="toc-efeitos-de-preço-do-auxílio-focalizado-num-sistema-de-demanda-flexível-1823" class="nav-link" data-scroll-target="#efeitos-de-preço-do-auxílio-focalizado-num-sistema-de-demanda-flexível-1823"><span class="header-section-number">2.2</span> Efeitos de preço do auxílio focalizado num sistema de demanda flexível [§18–§23]</a></li>
  </ul></li>
  <li><a href="#contexto-dados-e-amostra-pp.-1115" id="toc-contexto-dados-e-amostra-pp.-1115" class="nav-link" data-scroll-target="#contexto-dados-e-amostra-pp.-1115"><span class="header-section-number">3</span> Contexto, Dados e Amostra (pp.&nbsp;11–15)</a>
  <ul class="collapse">
  <li><a href="#o-mercado-brasileiro-de-ensino-superior-privado-2428" id="toc-o-mercado-brasileiro-de-ensino-superior-privado-2428" class="nav-link" data-scroll-target="#o-mercado-brasileiro-de-ensino-superior-privado-2428"><span class="header-section-number">3.1</span> O mercado brasileiro de ensino superior privado [§24–§28]</a></li>
  <li><a href="#dados-e-construção-da-amostra-2935" id="toc-dados-e-construção-da-amostra-2935" class="nav-link" data-scroll-target="#dados-e-construção-da-amostra-2935"><span class="header-section-number">3.2</span> Dados e construção da amostra [§29–§35]</a></li>
  </ul></li>
  <li><a href="#evidência-descritiva-pp.-1521" id="toc-evidência-descritiva-pp.-1521" class="nav-link" data-scroll-target="#evidência-descritiva-pp.-1521"><span class="header-section-number">4</span> Evidência Descritiva (pp.&nbsp;15–21)</a>
  <ul class="collapse">
  <li><a href="#a-reforma-do-fies-de-2015-3640" id="toc-a-reforma-do-fies-de-2015-3640" class="nav-link" data-scroll-target="#a-reforma-do-fies-de-2015-3640"><span class="header-section-number">4.1</span> A Reforma do FIES de 2015 [§36–§40]</a></li>
  <li><a href="#efeitos-do-auxílio-financeiro-sobre-mensalidades-e-matrículas-4146" id="toc-efeitos-do-auxílio-financeiro-sobre-mensalidades-e-matrículas-4146" class="nav-link" data-scroll-target="#efeitos-do-auxílio-financeiro-sobre-mensalidades-e-matrículas-4146"><span class="header-section-number">4.2</span> Efeitos do auxílio financeiro sobre mensalidades e matrículas [§41–§46]</a></li>
  <li><a href="#efeitos-direto-e-de-composição-4752" id="toc-efeitos-direto-e-de-composição-4752" class="nav-link" data-scroll-target="#efeitos-direto-e-de-composição-4752"><span class="header-section-number">4.3</span> Efeitos direto e de composição [§47–§52]</a></li>
  </ul></li>
  <li><a href="#modelo-de-equilíbrio-do-ensino-superior-com-auxílio-focalizado-pp.-2027" id="toc-modelo-de-equilíbrio-do-ensino-superior-com-auxílio-focalizado-pp.-2027" class="nav-link" data-scroll-target="#modelo-de-equilíbrio-do-ensino-superior-com-auxílio-focalizado-pp.-2027"><span class="header-section-number">5</span> Modelo de Equilíbrio do Ensino Superior com Auxílio Focalizado (pp.&nbsp;20–27)</a>
  <ul class="collapse">
  <li><a href="#demanda-5361" id="toc-demanda-5361" class="nav-link" data-scroll-target="#demanda-5361"><span class="header-section-number">5.1</span> Demanda [§53–§61]</a></li>
  <li><a href="#alocação-do-auxílio-financeiro-6266" id="toc-alocação-do-auxílio-financeiro-6266" class="nav-link" data-scroll-target="#alocação-do-auxílio-financeiro-6266"><span class="header-section-number">5.2</span> Alocação do auxílio financeiro [§62–§66]</a></li>
  <li><a href="#oferta-e-equilíbrio-de-preços-6774" id="toc-oferta-e-equilíbrio-de-preços-6774" class="nav-link" data-scroll-target="#oferta-e-equilíbrio-de-preços-6774"><span class="header-section-number">5.3</span> Oferta e equilíbrio de preços [§67–§74]</a></li>
  </ul></li>
  <li><a href="#estimação-do-modelo-pp.-2734" id="toc-estimação-do-modelo-pp.-2734" class="nav-link" data-scroll-target="#estimação-do-modelo-pp.-2734"><span class="header-section-number">6</span> Estimação do Modelo (pp.&nbsp;27–34)</a>
  <ul class="collapse">
  <li><a href="#instrumentos-micro-momentos-e-identificação-7584" id="toc-instrumentos-micro-momentos-e-identificação-7584" class="nav-link" data-scroll-target="#instrumentos-micro-momentos-e-identificação-7584"><span class="header-section-number">6.1</span> Instrumentos, micro-momentos e identificação [§75–§84]</a></li>
  <li><a href="#elasticidades-estimadas-e-aderência-do-modelo-8588" id="toc-elasticidades-estimadas-e-aderência-do-modelo-8588" class="nav-link" data-scroll-target="#elasticidades-estimadas-e-aderência-do-modelo-8588"><span class="header-section-number">6.2</span> Elasticidades estimadas e aderência do modelo [§85–§88]</a></li>
  </ul></li>
  <li><a href="#simulações-contrafactuais-pp.-3338" id="toc-simulações-contrafactuais-pp.-3338" class="nav-link" data-scroll-target="#simulações-contrafactuais-pp.-3338"><span class="header-section-number">7</span> Simulações Contrafactuais (pp.&nbsp;33–38)</a>
  <ul class="collapse">
  <li><a href="#efeitos-de-equilíbrio-dos-esquemas-de-focalização-sobre-as-mensalidades-8995" id="toc-efeitos-de-equilíbrio-dos-esquemas-de-focalização-sobre-as-mensalidades-8995" class="nav-link" data-scroll-target="#efeitos-de-equilíbrio-dos-esquemas-de-focalização-sobre-as-mensalidades-8995"><span class="header-section-number">7.1</span> Efeitos de equilíbrio dos esquemas de focalização sobre as mensalidades [§89–§95]</a></li>
  <li><a href="#efeitos-de-equilíbrio-sobre-a-matrícula-96101" id="toc-efeitos-de-equilíbrio-sobre-a-matrícula-96101" class="nav-link" data-scroll-target="#efeitos-de-equilíbrio-sobre-a-matrícula-96101"><span class="header-section-number">7.2</span> Efeitos de equilíbrio sobre a matrícula [§96–§101]</a></li>
  <li><a href="#implicações-de-política-102104" id="toc-implicações-de-política-102104" class="nav-link" data-scroll-target="#implicações-de-política-102104"><span class="header-section-number">7.3</span> Implicações de política [§102–§104]</a></li>
  </ul></li>
  <li><a href="#conclusão-pp.-3738" id="toc-conclusão-pp.-3738" class="nav-link" data-scroll-target="#conclusão-pp.-3738"><span class="header-section-number">8</span> Conclusão (pp.&nbsp;37–38)</a>
  <ul class="collapse">
  <li><a href="#síntese-das-três-contribuições-105108" id="toc-síntese-das-três-contribuições-105108" class="nav-link" data-scroll-target="#síntese-das-três-contribuições-105108"><span class="header-section-number">8.1</span> Síntese das três contribuições [§105–§108]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">9</span> Argumento Sintético</a></li>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Equilibrium Price Responses to Targeted Student Financial Aid</h1>
<p class="subtitle lead">Barahona, Dobbin &amp; Otero (2026)</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Economics of Education</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Barahona, N., Dobbin, C., &amp; Otero, S. (2026, April 6). <em>Equilibrium price responses to targeted student financial aid</em> [Working paper]. University of California, Berkeley; Georgetown University; Columbia University.</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Entrada BibTeX → Barahona-etal2026
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@unpublished</span>{<span class="ot">Barahona</span>-<span class="ot">etal2026</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>    = {Barahona, Nano and Dobbin, Cau{<span class="ch">\^</span>e} and Otero, Sebasti{<span class="ch">\'</span>a}n},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>     = {Equilibrium Price Responses to Targeted Student Financial Aid},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>      = {2026},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">month</span>     = {April},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">note</span>      = {Working paper},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">institution</span> = {UC Berkeley; Georgetown University; Columbia University}</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>Última atualização: 2026-04-19<br>
Modelo: Perplexity — Claude Sonnet 4.6 Thinking<br>
Gerado em: 2026-04-18T22:55:00-03:00</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Campo</th>
<th style="text-align: left;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Autores</td>
<td style="text-align: left;">Nano Barahona, Cauê Dobbin, Sebastián Otero</td>
</tr>
<tr class="even">
<td style="text-align: left;">Título</td>
<td style="text-align: left;">Equilibrium Price Responses to Targeted Student Financial Aid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ano</td>
<td style="text-align: left;">2026 (draft, April 6, 2026)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tipo</td>
<td style="text-align: left;">Working paper</td>
</tr>
<tr class="odd">
<td style="text-align: left;">JEL</td>
<td style="text-align: left;">L13, I22, I23, H22</td>
</tr>
<tr class="even">
<td style="text-align: left;">Palavras-chave</td>
<td style="text-align: left;">Student financial aid, Pass-through, Targeting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Contexto empírico</td>
<td style="text-align: left;">Mercado de ensino superior privado brasileiro, Reforma do FIES (2015)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Período da amostra</td>
<td style="text-align: left;">2012–2017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Unidade de análise</td>
<td style="text-align: left;">Cursos (combinação de habilitação, IES e turno) × região × ano</td>
</tr>
<tr class="even">
<td style="text-align: left;">N observações</td>
<td style="text-align: left;">&gt; 20 milhões de candidatos ao ENEM; 13.567 cursos em 695 IES</td>
</tr>
</tbody>
</table>
<section id="introdução-pp.-17" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-17"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–7)</h2>
<section id="motivação-e-puzzle-central-13" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="motivação-e-puzzle-central-13"><span class="header-section-number">1.1</span> Motivação e puzzle central [§1–§3]</h3>
<p>O artigo abre constatando que governos ao redor do mundo investem volumes expressivos de recursos em programas de auxílio financeiro estudantil com o objetivo declarado de ampliar o acesso ao ensino superior. Tais programas são onipresentes tanto na América Latina quanto nos países da OCDE. Apesar de sua prevalência, há uma preocupação de longa data entre formuladores de política pública: os programas de auxílio podem criar incentivos para que as instituições de ensino elevem as mensalidades e se apropriem de parcela dos fundos públicos — fenômeno conhecido na literatura como <strong>Hipótese de Bennett</strong> (Bennett, 1987).</p>
<p>Do ponto de vista conceitual, os autores identificam duas forças opostas geradas por programas de auxílio estudantil. Por um lado, o auxílio aumenta a capacidade de pagamento dos estudantes, o que pode induzir as IES a elevar as mensalidades. Por outro lado, se o auxílio for direcionado a estudantes de menor renda — que tipicamente possuem menor <strong>disposição a pagar</strong> (<em>willingness to pay</em>, WTP) —, as IES poderiam reduzir as mensalidades para atraí-los. O impacto líquido sobre preços é, portanto, teoricamente ambíguo e depende crucialmente de <em>como</em> o auxílio é distribuído — um mecanismo que, segundo os autores, foi negligenciado pela literatura prévia.</p>
<blockquote class="blockquote">
<p><strong>Puzzle central:</strong> O impacto do auxílio financeiro estudantil sobre as mensalidades depende do perfil de sensibilidade ao preço dos estudantes beneficiados — e não apenas da magnitude do subsídio — tornando a resposta da Hipótese de Bennett contingente ao desenho de focalização do programa.</p>
</blockquote>
</section>
<section id="estratégia-do-artigo-e-achados-em-síntese-47" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="estratégia-do-artigo-e-achados-em-síntese-47"><span class="header-section-number">1.2</span> Estratégia do artigo e achados em síntese [§4–§7]</h3>
<p>O artigo se estrutura em três etapas complementares. Primeiro, apresenta um <strong>framework conceitual</strong> que formaliza os canais pelos quais o auxílio afeta as mensalidades sob concorrência imperfeita. Segundo, fornece evidência empírica da relevância quantitativa desses canais, aproveitando uma grande reforma do programa federal de crédito estudantil brasileiro em 2015. Terceiro, estima um <strong>modelo de equilíbrio</strong> de oferta e demanda no ensino superior para avaliar políticas contrafactuais.</p>
<p>Os autores decompõem o efeito do auxílio sobre mensalidades em dois componentes: um <strong>efeito direto</strong> (o auxílio eleva a WTP dos recipientes, deslocando a curva de demanda para cima e pressionando os preços para cima) e um <strong>efeito composição</strong> (cuja direção depende do perfil de sensibilidade ao preço dos beneficiados). Quando o auxílio é direcionado a estudantes com menor WTP de linha de base, a curva de demanda se torna mais plana (mais elástica), o que pressiona os preços para baixo. Quando é direcionado a estudantes com alta WTP, a curva se torna mais íngreme (menos elástica), amplificando a alta de preços. Os três parâmetros que determinam as magnitudes relativas são: (i) a intensidade com que o auxílio eleva a WTP; (ii) o grau de heterogeneidade na WTP entre beneficiados e não beneficiados; e (iii) o grau de discriminação de preços praticado pelas IES.</p>
<p>Os achados centrais do artigo são que a focalização por mérito (<em>merit-based targeting</em>) eleva as mensalidades em 2,2%, enquanto a focalização por necessidade (<em>need-based targeting</em>) as reduz em 0,8%, em relação ao cenário sem empréstimos. Esses efeitos de preço têm impactos substanciais sobre a matrícula: sob focalização por necessidade, o ganho de matrícula sobe de 35,8% (efeito apenas de demanda) para 39,6% (equilíbrio); sob focalização por mérito, cai de 24,2% para apenas 15,8%.</p>
</section>
<section id="contribuições-à-literatura-811" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="contribuições-à-literatura-811"><span class="header-section-number">1.3</span> Contribuições à literatura [§8–§11]</h3>
<p>O artigo dialoga com três vertentes da literatura. Primeiro, contribui para a literatura sobre <strong>incidência tributária sob concorrência imperfeita</strong> (Delipalla &amp; Keen, 1992; Anderson et al., 2001; Weyl &amp; Fabinger, 2013; Miravete et al., 2018; Kroft et al., 2024a, b). Um resultado central dessa literatura é que o <em>pass-through</em> depende da elasticidade e da curvatura da demanda, mas essas intuições foram desenvolvidas principalmente para políticas uniformes. Os autores demonstram que quando os subsídios são focalizados — como é comum em programas de auxílio estudantil e em outros programas de transferência —, emerge uma força adicional: a focalização realoca a demanda entre consumidores com heterogeneidade em sensibilidade ao preço, alterando endogenamente a elasticidade da demanda residual enfrentada pelas firmas.</p>
<p>Segundo, os autores relacionam seu efeito composição ao conceito de <strong>“demographic externality”</strong> introduzido por Polyakova &amp; Ryan (2022) no contexto dos mercados de seguro de saúde. Ambos os artigos compartilham a ideia de que subsídios focalizados alteram a composição da demanda e, com isso, a elasticidade residual enfrentada pelas firmas. Os artigos divergem em três aspectos: o framework de Barahona et al.&nbsp;isola o que determina a <em>direção</em> do efeito composição (se o auxílio é direcionado a consumidores mais ou menos sensíveis ao preço); comparam diferentes esquemas de focalização; e analisam um mercado com descontos de mensalidades, que podem atenuar o efeito composição. Além disso, nos EUA as IES utilizam dados de solicitação de auxílio para discriminar preços (Fillmore, 2023), o que reduz a relevância dos efeitos de composição em contraste com o contexto brasileiro.</p>
<p>Terceiro, o artigo contribui para a literatura empírica sobre a relação entre auxílio estudantil e mensalidades (Long, 2004; Singell &amp; Stone, 2007; Cellini &amp; Goldin, 2014; Lucca et al., 2019; Baird et al., 2022; Black et al., 2023; De Mello &amp; Duarte, 2020). Essa literatura encontrou em geral que expansões do auxílio elevam as mensalidades, em linha com a Hipótese de Bennett. Os autores oferecem uma reinterpretação: as respostas de preços ao auxílio não necessariamente refletem <em>pass-through</em> puro; podem também ser respostas de equilíbrio às mudanças na composição dos estudantes matriculados. A Hipótese de Bennett não é simplesmente verdadeira ou falsa — depende de como o auxílio está direcionado. Por fim, o artigo se insere na literatura sobre modelos de equilíbrio dos mercados de educação (Epple &amp; Romano, 1998; Epple et al., 2006; Fillmore, 2023; Fu, 2014; Bucarey, 2018; Neilson, 2021; Allende, 2021; Armona &amp; Cao, 2024), contribuindo ao incorporar explicitamente o canal de composição da demanda.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central em formulação preliminar:</strong> O impacto de programas de auxílio financeiro estudantil sobre as mensalidades depende de quem recebe o auxílio: a focalização por necessidade (estudantes de baixa renda e alta sensibilidade ao preço) reduz as mensalidades via efeito composição, enquanto a focalização por mérito (estudantes de alta renda e baixa sensibilidade ao preço) as eleva.</p>
</div>
</div>
</section>
</section>
<section id="framework-conceitual-efeitos-de-preço-do-auxílio-focalizado-pp.-712" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="framework-conceitual-efeitos-de-preço-do-auxílio-focalizado-pp.-712"><span class="header-section-number">2</span> Framework Conceitual: Efeitos de Preço do Auxílio Focalizado (pp.&nbsp;7–12)</h2>
<section id="subsídio-focalizado-num-sistema-de-demanda-linear-1217" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="subsídio-focalizado-num-sistema-de-demanda-linear-1217"><span class="header-section-number">2.1</span> Subsídio focalizado num sistema de demanda linear [§12–§17]</h3>
<p>A seção 2 formaliza os mecanismos teóricos. O modelo mais simples considera um mercado com um monopolista vendendo um único produto ao preço <em>p</em> com custo marginal zero. Um contínuo de consumidores indexados por <em>i ∈ I</em> participa do mercado. O governo provê um subsídio específico na forma de uma transferência fixa τᵢ ∈ ℝ, condicionada à compra do bem. A WTP dos consumidores é θᵢ + τᵢ, com θᵢ uniformemente distribuído no intervalo [0, 2]. O monopolista maximiza lucros resolvendo:</p>
<p>[p^*(T) = _p , Q(p T) p (1)]</p>
<p>A condição de primeira ordem implica que a firma fixa <em>p*</em> de forma que a elasticidade-preço absoluta da demanda seja igual a um: η(p*(T) | T) = 1.</p>
<p>Os autores analisam três cenários. No <strong>benchmark sem subsídio</strong> (T₀ ≡ {τᵢ = 0, ∀i}), a curva de demanda linear é P = 2 − Q e o preço ótimo é <em>p</em> tal que η₀ = 1. No caso de <strong>subsídio uniforme</strong> (Tₐ ≡ {τᵢ = τ &gt; 0, ∀i}), a WTP de todos os consumidores sobe para θ̃ᵢ = θᵢ + τ, deslocando a curva de demanda paralelamente para P = 2 − Q + τ. Esse deslocamento paralelo reduz a elasticidade no preço original para ηₐ₁ = 1/(1 + τ) &lt; 1, levando o monopolista a elevar o preço até p̃ₐ &gt; p (confirmando a Hipótese de Bennett para subsídios uniformes). No caso de <strong>subsídio focalizado</strong> (Tᵦ ≡ {τ·(θ̄ − θᵢ), ∀i}, onde θ̄ = 1 é a WTP mediana), apenas os consumidores com WTP abaixo da mediana recebem transferências positivas. Esse esquema <strong>rotaciona</strong> a curva de demanda em torno do preço de equilíbrio original <em>p</em>, tornando-a mais plana e elevando a elasticidade para ηᵦ₁ = 1/(1 − τ) &gt; 1. Em resposta, o monopolista reduz o preço até p̃ᵦ &lt; p.</p>
<p>A intuição para a queda de preços é a seguinte: quando o subsídio eleva a WTP de consumidores que não teriam comprado ao preço de linha de base, ele comprime a dispersão da WTP e reduz a distância desses consumidores ao consumidor marginal original. Isso aproxima sua WTP de <em>p</em> por baixo, de modo que uma pequena redução de preço induz um aumento substancial na demanda, tornando a queda de preço a resposta ótima da firma. Esquemas de subsídio mais complexos podem combinar deslocamentos e rotações da demanda, com o efeito líquido determinado pela intensidade relativa de cada força.</p>
</section>
<section id="efeitos-de-preço-do-auxílio-focalizado-num-sistema-de-demanda-flexível-1823" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="efeitos-de-preço-do-auxílio-focalizado-num-sistema-de-demanda-flexível-1823"><span class="header-section-number">2.2</span> Efeitos de preço do auxílio focalizado num sistema de demanda flexível [§18–§23]</h3>
<p>A seção 2.2 estende o framework para acomodar sistemas de demanda mais flexíveis e outras formas de auxílio financeiro, como empréstimos estudantis. Considera-se um único monopolista com custo marginal <em>c</em>, uma massa unitária de estudantes indexados por <em>i ∈ [0, 1]</em> e caracterizados por χᵢ. Uma fração ρ dos estudantes recebe auxílio financeiro; os estudantes são ordenados por sua propensão a receber o auxílio (i = 0 é o mais pobre, se o auxílio for perfeitamente focalizado por renda). A probabilidade de matrícula de um estudante <em>i</em> condicional ao status de portador de empréstimo <em>k ∈ {L, NL}</em>, características χᵢ e preço <em>p</em> é dada por sᵏᵢ(p).</p>
<p>O preço ótimo da firma, condicional a ρ, é:</p>
<p>[p^*() = _p , S(p, ) (p - c) (3)]</p>
<p>onde a matrícula total é:</p>
<p>[S(p, ) <em>0^s^L_i(p) , di + </em>^1 s^{NL}_i(p) , di (4)]</p>
<p>Diferenciando a Equação (3) com respeito a ρ, obtém-se a decomposição central do artigo:</p>
<p>[ = <em>{} - </em>{} (5)]</p>
<p>onde η é a elasticidade-preço da demanda agregada em p*; sᴸᵨ e sᴺᴸᵨ são as probabilidades de matrícula do estudante marginal portador do empréstimo com e sem o empréstimo, respectivamente; ηᴸᵨ e ηᴺᴸᵨ são suas elasticidades-preço; e Ω captura o papel da elasticidade e curvatura da demanda no <em>pass-through</em> (demanda mais inelástica eleva Ω, consistente com Weyl &amp; Fabinger, 2013).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Decomposição efeito direto vs.&nbsp;efeito composição (Eq. 5):</strong></p>
<ul>
<li><strong>Efeito direto:</strong> captado por (ηᴺᴸᵨ − ηᴸᵨ) — o auxílio reduz a sensibilidade ao preço do grupo marginal, deslocando a demanda para cima e pressionando os preços para cima; quanto maior a diferença de elasticidade com e sem empréstimo, mais forte esse efeito.</li>
<li><strong>Efeito composição:</strong> captado por (ηᴸᵨ − η) · (sᴸᵨ − sᴺᴸᵨ)/sᴺᴸᵨ — se o grupo marginal é mais sensível ao preço que a média de mercado (ηᴸᵨ &gt; η), o efeito composição pressiona os preços para baixo; se menos sensível, pressiona para cima.</li>
</ul>
</div>
</div>
<p>O <strong>insight central</strong> da análise teórica é que os efeitos de preço do auxílio focalizado podem ser decompostos em efeitos direto e de composição, com a direção do efeito composição dependendo do desenho da focalização. Estudos anteriores sobre incidência tributária focalizam-se em impostos ou subsídios uniformes, ignorando o papel da focalização na determinação da incidência.</p>
</section>
</section>
<section id="contexto-dados-e-amostra-pp.-1115" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="contexto-dados-e-amostra-pp.-1115"><span class="header-section-number">3</span> Contexto, Dados e Amostra (pp.&nbsp;11–15)</h2>
<section id="o-mercado-brasileiro-de-ensino-superior-privado-2428" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="o-mercado-brasileiro-de-ensino-superior-privado-2428"><span class="header-section-number">3.1</span> O mercado brasileiro de ensino superior privado [§24–§28]</h3>
<p>O mercado brasileiro de ensino superior compreende instituições públicas e privadas, com o setor privado mais que triplicando nas últimas duas décadas. Em 2014, 75% dos 8,8 milhões de estudantes presenciais frequentavam IES privadas, e as instituições com fins lucrativos correspondiam a 51% das matrículas privadas. O setor é altamente concentrado: as 10 maiores firmas detêm 42% do total das matrículas privadas, e as 100 maiores, 72%. As quatro maiores (Ânima Holding, Kroton, SER Educacional e Estácio) são listadas em bolsa e representam 29% das matrículas privadas. Ao contrário das instituições públicas — gratuitas, mais prestigiosas e superdemandadas —, as IES privadas cobram mensalidades e tendem a operar com excesso substancial de capacidade: em média, os cursos privados preenchem apenas 48% de suas vagas declaradas, e quase 90% matriculam menos de 80% da capacidade.</p>
<p>O <strong>FIES</strong> (Fundo de Financiamento Estudantil) é o programa federal de empréstimos subsidiados para estudantes de IES privadas. Criado em 1999, foi substancialmente expandido por uma reforma em 2010: os novos contratos passaram de menos de 20.000 em 2009 para cerca de 550.000 em 2014. Para os estudantes contemplados, o governo paga diretamente às IES, cobrindo até 100% das mensalidades, com início do pagamento 18 meses após a conclusão ou abandono do curso. Em 2014, o FIES desembolsou USD 5,8 bilhões anuais — 15% do orçamento do Ministério da Educação e cerca de um sexto das receitas das IES privadas. Em 2014, o curso mediano tinha cerca de 25% de seus estudantes com empréstimos FIES, com alguns cursos dependendo do FIES para 100% de sua matrícula.</p>
<p>Para se qualificar para o FIES, os estudantes deviam prestar o ENEM (exame nacional de alto impacto, também usado para admissão em universidades federais), sem nota mínima obrigatória inicialmente. A elegibilidade e a fração das mensalidades coberta pelo auxílio eram submetidas a teste de meios: os empréstimos cobriam entre 50% e 100% das mensalidades, dependendo da razão entre as mensalidades e a renda per capita familiar mensal. Estudantes eram inelegíveis se as mensalidades representassem menos de 20% de sua renda per capita mensal.</p>
<p>Além dos empréstimos governamentais, as IES privadas frequentemente oferecem <strong>descontos de mensalidades</strong> como forma de auxílio financeiro. Em 2014, 14% dos ingressantes receberam desconto, com taxa média de 33%. Esses descontos não são bolsas de mérito, mas estratégias de discriminação de preços voltadas a estudantes que de outro modo não poderiam arcar com as mensalidades. As IES empregam estratégias de precificação dinâmica análogas às de linhas aéreas e hotéis, utilizando plataformas online (como o QueroBolsa) que funcionam como agregadores de tarifas: 25% das ofertas ficam disponíveis por menos de uma semana, e 50% são retiradas em três semanas.</p>
</section>
<section id="dados-e-construção-da-amostra-2935" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="dados-e-construção-da-amostra-2935"><span class="header-section-number">3.2</span> Dados e construção da amostra [§29–§35]</h3>
<p>Os autores constroem um conjunto de dados individual abrangente, vinculando três fontes por identificadores individuais: (i) o <strong>Censo da Educação Superior</strong>, que cobre o universo de estudantes matriculados, com informações sobre IES, curso e status de desconto; (ii) <strong>registros administrativos do FIES</strong>, que rastreiam estudantes com empréstimos e os montantes tomados; e (iii) <strong>o banco de dados do ENEM</strong>, com notas de prova e respostas a um extenso questionário socioeconômico (raça, gênero, renda familiar, tipo de escola no ensino médio, escolaridade dos pais e planos de solicitar FIES).</p>
<p>Para mensalidades, a ausência de obrigação de reporte regulatório leva os autores a combinar quatro fontes: dados administrativos dos programas PROUNI e FIES, pesquisa do Hoper Educacional (survey representativo nacional de IES), e dados administrativos do QueroBolsa (maior plataforma de busca de descontos do país). Os últimos dois datasets são inéditos para pesquisa e foram obtidos por parcerias. Essa abordagem permite recuperar preços anuais específicos para 95% das observações curso-ano, cobrindo 98% da matrícula total.</p>
<p>A amostra de análise cobre 2012–2017. Um <strong>curso</strong> é definido como a combinação de habilitação, IES e turno (diurno ou noturno). Uma <strong>IES</strong> pode operar múltiplos cursos em diferentes campi e regiões. As regiões seguem a classificação de mesorregiões do IBGE (137 mesorregiões a partir de 5.568 municípios). Para tratabilidade computacional, a análise se restringe a regiões com pelo menos 5.000 candidatos ao ENEM e 1.000 ingressantes por ano (69 regiões), cursos privados presenciais com pelo menos 15 ingressantes anuais, estudantes com notas ENEM entre 400 e 700, e exclui bolsistas do PROUNI. A amostra final inclui mais de 20 milhões de candidatos ao ENEM e 13.567 cursos em 695 IES, cobrindo 88% dos candidatos ao ENEM em nível nacional.</p>
</section>
</section>
<section id="evidência-descritiva-pp.-1521" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="evidência-descritiva-pp.-1521"><span class="header-section-number">4</span> Evidência Descritiva (pp.&nbsp;15–21)</h2>
<section id="a-reforma-do-fies-de-2015-3640" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="a-reforma-do-fies-de-2015-3640"><span class="header-section-number">4.1</span> A Reforma do FIES de 2015 [§36–§40]</h3>
<p>A análise empírica se ancora na Reforma do FIES de 2015 — uma mudança de política importante, motivada por restrições fiscais federais, que endureceu substancialmente os critérios de elegibilidade para estudantes e IES. Para os estudantes, a reforma introduziu um teto de renda per capita familiar de 2,5 salários mínimos e nota mínima no ENEM de 450 (correspondente ao percentil 25 aproximado). Para as IES, introduziu um cap no número de estudantes com FIES por curso, com prioridade a programas de alta qualidade, cursos de saúde e IES em regiões de baixa renda. Na maioria dos cursos, a demanda por empréstimos excedeu o cap, resultando na alocação via mecanismo de aceitação diferida baseado em notas do ENEM, criando cutoffs de elegibilidade específicos por curso.</p>
<p>O impacto foi uma contração abrupta no número de novos empréstimos: de cerca de 550.000 em 2014 para aproximadamente 150.000 em 2017. As mensalidades reais caíram 5,2% no mesmo período (a queda se materializa apenas em 2016, pois os preços de 2015 já haviam sido fixados antes do anúncio da reforma). Os preços das ações das quatro maiores firmas do setor caíram bruscamente no dia do anúncio (20% a 40%), sinalizando que a reforma foi em grande parte inesperada e tinha implicações significativas para as expectativas de lucratividade futura.</p>
</section>
<section id="efeitos-do-auxílio-financeiro-sobre-mensalidades-e-matrículas-4146" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="efeitos-do-auxílio-financeiro-sobre-mensalidades-e-matrículas-4146"><span class="header-section-number">4.2</span> Efeitos do auxílio financeiro sobre mensalidades e matrículas [§41–§46]</h3>
<p>Para mensurar a exposição à reforma, os autores exploram a introdução de caps no número de estudantes com empréstimos por curso. Como esses caps foram fixados independentemente do número de estudantes com empréstimos em cada curso antes da reforma, cursos com maior participação pré-reforma no FIES experimentaram maiores reduções na disponibilidade de empréstimos. A medida de exposição é:</p>
<p>[_j = (6)]</p>
<p>onde N^L_{j,2012} é o número de estudantes com FIES no curso <em>j</em> em 2012, N_{j,2012} é a matrícula total no mesmo ano, e N̄_j é o cap imposto pela política. Um aumento de um desvio padrão na exposição corresponde a uma queda de 16 pontos percentuais no uso de empréstimos entre 2014 e 2017.</p>
<p>Os autores estimam:</p>
<p>[_{jt} = <em>j + </em>{rt} + _l _l {t=l} <em>j + </em>{jt} (7)]</p>
<p>Os resultados (Figura 3) mostram tendências pré-paralelas, validando a estratégia. Em 2017, um aumento de um desvio padrão em Exp_j está associado a uma queda de 2,1% nas mensalidades e de 9,2% na matrícula. Cursos mais expostos também apresentaram aumento no número de estudantes pagando do próprio bolso, possivelmente refletindo tanto a redução das mensalidades quanto a matrícula de estudantes que, quando disponíveis, tomam empréstimos mas continuam a se matricular sem eles.</p>
</section>
<section id="efeitos-direto-e-de-composição-4752" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="efeitos-direto-e-de-composição-4752"><span class="header-section-number">4.3</span> Efeitos direto e de composição [§47–§52]</h3>
<p>Os autores testam empiricamente se os ajustes de mensalidades observados após a reforma do FIES se alinham às predições do framework conceitual. O desafio é que as elasticidades (ηᴸᵨ − η) não são diretamente observáveis. Como proxy, supõem que a elasticidade-preço da demanda é inversamente relacionada à renda e constroem Δη_j como o diferencial log de renda entre o estudante médio e o tomador médio de FIES na mesma IES, utilizando dados de 2012. Essa medida apresenta variação substancial: nos 5% superiores da distribuição de Δη_j, os tomadores de FIES são, em média, 75% mais pobres do que o corpo discente geral; nos 5% inferiores, apenas 8% mais pobres.</p>
<p>A especificação estendida é:</p>
<p>[p_{jt} = <em>j + </em>{rt} + _0 _t _j + _C _t _j <em>j + </em>{jt} (8)]</p>
<p>Os resultados (Tabela 1) revelam um efeito de composição substancial. A coluna (1), sem heterogeneidade por Δη, indica que um aumento de um desvio padrão na exposição está associado a uma queda de 2,0% nas mensalidades pós-reforma. A coluna (3), com heterogeneidade, mostra que à medida que Δη_j aumenta, a relação entre exposição e mensalidade se torna menos negativa: para cursos nos 5% inferiores de Δη, a mesma variação de exposição está associada a uma queda de 3,9% nas mensalidades; para cursos nos 5% superiores, corresponde a um <em>aumento</em> de 0,1%. O coeficiente de interação β_C é de 0,503 (col.&nbsp;3), 0,395 (col.&nbsp;4, com efeitos fixos região-habilitação-ano) e 0,359 (col.&nbsp;5, com tendências Δη-ano), todos estatisticamente significativos a 5% ou 1%.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Especificação</th>
<th style="text-align: left;">post × Exp</th>
<th style="text-align: left;">post × Exp × Δη</th>
<th style="text-align: left;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(1) Sem heterogeneidade</td>
<td style="text-align: left;">−0,106***</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">13.447</td>
</tr>
<tr class="even">
<td style="text-align: left;">(2) + RF região-hab-ano</td>
<td style="text-align: left;">−0,102***</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">11.695</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(3) Com Δη</td>
<td style="text-align: left;">−0,099***</td>
<td style="text-align: left;">0,503***</td>
<td style="text-align: left;">13.447</td>
</tr>
<tr class="even">
<td style="text-align: left;">(4) + RF região-hab-ano</td>
<td style="text-align: left;">−0,100***</td>
<td style="text-align: left;">0,395***</td>
<td style="text-align: left;">11.695</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(5) + ΔInc-Ano FE</td>
<td style="text-align: left;">−0,098***</td>
<td style="text-align: left;">0,359**</td>
<td style="text-align: left;">11.695</td>
</tr>
</tbody>
</table>
<p><em>Erros padrão clusterizados no nível IES-ano. *** p&lt;0,01, ** p&lt;0,05, * p&lt;0,10.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Síntese da evidência reduzida:</strong> Os resultados da Seção 4 constituem evidência empírica de que os efeitos de preços do auxílio estudantil variam sistematicamente com o perfil de renda dos beneficiados, em linha com as predições do framework conceitual. Em mercados onde os tomadores de FIES tinham rendas similares às do estudante médio, a redução do auxílio levou a queda das mensalidades (consistente com a Hipótese de Bennett). Em mercados com tomadores predominantemente de baixa renda, a redução do auxílio provocou <em>aumento</em> das mensalidades — o que confirma que o efeito composição pode superar o efeito direto.</p>
</div>
</div>
</section>
</section>
<section id="modelo-de-equilíbrio-do-ensino-superior-com-auxílio-focalizado-pp.-2027" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="modelo-de-equilíbrio-do-ensino-superior-com-auxílio-focalizado-pp.-2027"><span class="header-section-number">5</span> Modelo de Equilíbrio do Ensino Superior com Auxílio Focalizado (pp.&nbsp;20–27)</h2>
<section id="demanda-5361" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="demanda-5361"><span class="header-section-number">5.1</span> Demanda [§53–§61]</h3>
<p>O modelo de equilíbrio estende o framework teórico da Seção 2.2 para um ambiente com múltiplas IES competindo em cada mercado, cada uma oferecendo um portfólio de cursos e praticando discriminação de preços. O modelo de demanda consiste num contínuo de estudantes avessos ao risco, indexados por <em>i ∈ I</em>, caracterizados por renda domiciliar w_i e nota no exame h_i. Cada combinação região-ano é tratada como um mercado distinto. Os cursos são não-seletivos: os estudantes podem se matricular em qualquer curso disponível ou escolher a opção externa (não matrícula no setor privado, incluindo matrícula em instituição pública).</p>
<p>A função de utilidade de um estudante <em>i</em> ao se matricular no curso <em>j</em> é:</p>
<p>[U_{ijrt} = <em>{} + </em>{} - _{} (9)]</p>
<p>A utilidade média δ_{jrt} é parametrizada como δ_{jr} + δ_{rt} + ξ_{jrt}, onde δ_{jr} é efeito fixo curso-região (tempo-invariante), δ_{rt} é efeito fixo região-ano, e ξ_{jrt} é um choque não observável de demanda específico ao curso-ano. A componente individual µ_{ijrt} = β_h · h_i + β_w · w_i + ε_{ijrt} captura heterogeneidade individual, onde β_h e β_w medem o impacto da nota e da renda na utilidade relativa à opção externa (não matrícula privada), e ε_{ijrt} segue distribuição de valor extremo.</p>
<p>O custo financeiro (terceiro componente) permite que os empréstimos estudantis influenciem a sensibilidade ao preço α¹_{ijrt} e o custo de financiamento de linha de base α⁰_{ijrt} de duas formas: reduzindo a sensibilidade ao preço (via taxas de juros subsidiadas e possibilidade de inadimplência) e aliviando restrições de liquidez/funcionando como empurrão comportamental para a matrícula. Formalmente:</p>
<p>[^0_{ijrt} = ^{0L} L_{ijrt} + ^{0wL} w_i L_{ijrt}]</p>
<p>[^1_{ijrt} = ^1 + ^{1w} w_i + ^{1L} L_{ijrt} + ^{1wL} w_i L_{ijrt}]</p>
<p>O preço enfrentado por um estudante depende de seu status de desconto: p^F_{jrt} (preço cheio) ou p^D_{jrt} (preço descontado). Estudantes escolhem maximizando sua utilidade, e a participação de mercado do curso <em>j</em> com status de auxílio (l, d) é dada pela expectativa dos operadores de indicadora de matrícula.</p>
</section>
<section id="alocação-do-auxílio-financeiro-6266" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="alocação-do-auxílio-financeiro-6266"><span class="header-section-number">5.2</span> Alocação do auxílio financeiro [§62–§66]</h3>
<p>O auxílio é alocado ao nível do par estudante-curso, com os estudantes tomando suas decisões de matrícula com pleno conhecimento de seus status de empréstimo e desconto. A alocação é modelada por um framework de variável latente:</p>
<p>[L_{ijrt} = {^L_w w_i + ^L_{ft} ^L_{ijrt}} {h_i h_{jrt}}]</p>
<p>[D_{ijrt} = {^D_w w_i + ^D_{ft} ^D_{ijrt}}]</p>
<p>onde ϑ^L_{ijrt} e ϑ^D_{ijrt} são termos de erro idiossincráticos com distribuição logística. O limiar de nota h_{jrt} é específico ao curso-ano, gerado endogenamente pelos caps do governo. Os parâmetros ρ^L_{ft} e ρ^D_{ft} capturam variação sistemática inexplicada na participação em auxílio entre IES, motivada por fatores como estigma social (Moffitt, 1983; Finkelstein &amp; Notowidigdo, 2019) e acesso diferenciado à informação (Castleman &amp; Page, 2015).</p>
<p>Uma implicação desse arcabouço é que a recepção de auxílio é modelada independentemente dos níveis de mensalidades — uma simplificação para manter o modelo tratável. Na realidade, as decisões de uptake podem responder a preços (um estudante que recusa um empréstimo quando as mensalidades são baixas pode aceitá-lo se os preços sobem), mas essa margem é abstraída por razões de tratabilidade computacional.</p>
</section>
<section id="oferta-e-equilíbrio-de-preços-6774" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="oferta-e-equilíbrio-de-preços-6774"><span class="header-section-number">5.3</span> Oferta e equilíbrio de preços [§67–§74]</h3>
<p>Cada IES <em>f</em> oferece um conjunto de cursos J_{ft} em cada ano e escolhe preços cheios e descontados para cada curso para maximizar lucros esperados. O modelo se afasta dos modelos padrão de oligopólio de Bertrand-Nash (Berry et al., 1995; Nevo, 2001) ao permitir que as IES fixem dois preços por curso (um para alunos com desconto e um para alunos sem desconto). Tratando matrículas com e sem desconto como produtos distintos oferecidos pela mesma IES, o problema permanece formalmente equivalente a um modelo Bertrand-Nash padrão.</p>
<p>A condição de primeira ordem resulta na equação de precificação ótima:</p>
<p>[p_{rt} = c_{rt} + <em>- </em>{rt} d_{rt} (19)]</p>
<p>onde ∆<em>{rt} é a matriz de derivadas da demanda (com elemento (ι, υ) igual a −∂s<sup>υ_{rt}/∂p</sup>ι</em>{rt} se ι e υ pertencem à mesma IES, e 0 caso contrário), e κ_{ιrt} d_{ιrt} captura fatores não explicitamente modelados que afetam a precificação relativa de matrículas com desconto versus preço cheio. A equação de precificação clarifica como a discriminação de preços altera o efeito composição: se todas as estudantes de alta sensibilidade ao preço (que tendem a receber empréstimos) também recebem desconto, o efeito composição sobre o preço cheio desaparece, pois entre os alunos de preço cheio os portadores de empréstimo não são mais sensíveis ao preço que os demais.</p>
<p>Os autores discutem as simplificações do modelo de oferta: (i) as IES tomam a demanda como dada (excluindo investimentos em qualidade, infraestrutura e marketing); (ii) a discriminação de preços é capturada de forma tratável com três hipóteses simplificadoras (estrutura de dois preços dentro do curso; as IES escolhem o tamanho do desconto mas não quais estudantes o recebem; parâmetros κ e ρ^D são invariantes à política). A evidência empírica (Apêndice E) oferece suporte a essas três hipóteses.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Advertência do modelo:</strong> O modelo abstrai de margens possivelmente relevantes, notadamente (i) endogeneidade da qualidade educacional e (ii) resposta do uptake de auxílio aos preços. Ambas as simplificações visam à tratabilidade computacional mas podem afetar as inferências sobre magnitude dos efeitos.</p>
</div>
</div>
</section>
</section>
<section id="estimação-do-modelo-pp.-2734" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="estimação-do-modelo-pp.-2734"><span class="header-section-number">6</span> Estimação do Modelo (pp.&nbsp;27–34)</h2>
<section id="instrumentos-micro-momentos-e-identificação-7584" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="instrumentos-micro-momentos-e-identificação-7584"><span class="header-section-number">6.1</span> Instrumentos, micro-momentos e identificação [§75–§84]</h3>
<p>A estimação segue o procedimento GMM de Berry, Levinsohn &amp; Pakes (1995), estendido por Petrin (2002), combinando variáveis instrumentais com micro-momentos para identificar os parâmetros. O principal desafio na estimação da demanda é a correlação potencial entre preços e o choque de demanda não observável ξ_{jrt}, que exige um instrumento para preços.</p>
<p>O instrumento de preço é <strong>Z_{jrt} = Exp_j · post_t</strong>, baseado na exposição à reforma de 2015. As condições de momentos impostas são E[Z_{jrt} · ξ_{jrt}] = 0 e E[Z_{jrt} · ω_{jrt}] = 0, que implicam que as variações de preço observadas após a reforma refletem primariamente respostas endógenas à redução na disponibilidade de empréstimos, e não choques não observados correlacionados com a exposição à política.</p>
<p>Para identificar o impacto dos empréstimos na demanda dos estudantes, os autores exploram as <strong>descontinuidades no acesso a empréstimos nos limiares de nota de elegibilidade</strong> pós-reforma. Essa estratégia de micro-momentos — análoga a uma regressão em descontinuidade — usa os cutoffs como variáveis instrumentais para o status de empréstimo, sob a hipótese de que as notas não são sistematicamente manipuladas ao redor dos cortes (hipótese plausível, dado que os limiares eram desconhecidos <em>ex ante</em>). Formalmente, o momento de corte do empréstimo exige que a diferença na taxa de matrícula ao redor dos cutoffs do modelo corresponda à diferença observada nos dados.</p>
<p>Os resultados da estimação (Tabela A.2 do Apêndice) reportam: β_h = 3,44 (nota ENEM aumenta utilidade relativa ao ensino público), β_w = −1,07 (renda reduz utilidade relativa ao ensino privado, capturando preferência por universidades públicas), α¹ = −5,10 (sensibilidade ao preço média, em log), α^{1w} = −0,42 (sensibilidade ao preço cai com renda), α^{1L} = −0,08 (empréstimo reduz sensibilidade ao preço), ρ^{Lw} = −2,27 (renda reduz probabilidade de tomar empréstimo).</p>
</section>
<section id="elasticidades-estimadas-e-aderência-do-modelo-8588" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="elasticidades-estimadas-e-aderência-do-modelo-8588"><span class="header-section-number">6.2</span> Elasticidades estimadas e aderência do modelo [§85–§88]</h3>
<p>A elasticidade-preço mediana estimada é <strong>−3,46</strong>, consistente com estimativas prévias (Armona &amp; Cao, 2024; Barahona et al., 2025). Isso confirma que as IES possuem poder de mercado moderado e que mudanças no auxílio financeiro podem provocar ajustes significativos nas mensalidades. Crucialmente, a sensibilidade ao preço varia sistematicamente com renda e status de empréstimo: a elasticidade-preço mediana é −5,07 para estudantes com renda abaixo da média e −2,96 para aqueles com renda acima da média. Receber um empréstimo reduz a sensibilidade ao preço em 11,1%, em média.</p>
<p>Os descontos de mensalidades têm correlação apenas fraca com a renda dos estudantes, o que sugere que a discriminação de preços desempenha um papel limitado no contexto brasileiro — em contraste com as IES seletivas americanas, que usam dados de solicitação de auxílio para discriminar preços com maior precisão. Essa característica do contexto brasileiro amplifica a relevância do efeito composição, tornando-o empiricamente mais pronunciado do que seria num mercado com discriminação de preços mais efetiva.</p>
</section>
</section>
<section id="simulações-contrafactuais-pp.-3338" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="simulações-contrafactuais-pp.-3338"><span class="header-section-number">7</span> Simulações Contrafactuais (pp.&nbsp;33–38)</h2>
<section id="efeitos-de-equilíbrio-dos-esquemas-de-focalização-sobre-as-mensalidades-8995" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="efeitos-de-equilíbrio-dos-esquemas-de-focalização-sobre-as-mensalidades-8995"><span class="header-section-number">7.1</span> Efeitos de equilíbrio dos esquemas de focalização sobre as mensalidades [§89–§95]</h3>
<p>Os autores utilizam o modelo estimado para avaliar os efeitos de equilíbrio de dois esquemas comuns de focalização de empréstimos: por necessidade (<em>need-based</em>) e por mérito (<em>merit-based</em>). Em ambos os casos, os empréstimos são alocados sob uma restrição de orçamento fixo igual ao do programa pré-reforma (cenários budget-neutral). Os efeitos são avaliados comparando cada esquema a um contrafactual sem empréstimos.</p>
<p>Sob <strong>focalização por necessidade</strong>, os empréstimos são direcionados a estudantes de baixa renda, mais sensíveis ao preço. O efeito composição negativo supera o efeito direto positivo, resultando em queda líquida de 0,8% nas mensalidades em relação ao cenário sem empréstimos. Sob <strong>focalização por mérito</strong>, os empréstimos são alocados a estudantes com altas notas no ENEM, fortemente correlacionadas com alta renda e baixa sensibilidade ao preço. Nesse caso, o efeito composição reforça o efeito direto, levando a um aumento de 2,2% nas mensalidades. Sob <strong>focalização aleatória</strong> (ausência de correlação com características dos estudantes), o efeito composição está ausente e apenas o efeito direto opera, elevando as mensalidades em 1,4%.</p>
<p>Os autores também exploram como os efeitos variam com o tamanho do programa (Figura 5). Sob focalização por necessidade, o efeito composição domina enquanto o orçamento é de até 1,6 vezes o nível de linha de base; além desse limiar, à medida que a renda do tomador marginal sobe, o efeito composição enfraquece e o efeito direto passa a dominar, elevando as mensalidades. Sob focalização por mérito, as mensalidades aumentam monotonicamente com o tamanho do programa, a uma taxa superior ao cenário aleatório.</p>
</section>
<section id="efeitos-de-equilíbrio-sobre-a-matrícula-96101" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="efeitos-de-equilíbrio-sobre-a-matrícula-96101"><span class="header-section-number">7.2</span> Efeitos de equilíbrio sobre a matrícula [§96–§101]</h3>
<p>Para disentrelaçar os efeitos de oferta e demanda, os autores constroem dois contrafactuais de matrícula por esquema de focalização: (i) <strong>demand-only</strong>, que isola os efeitos do lado da demanda mantendo as mensalidades fixas no nível do cenário sem empréstimos; e (ii) <strong>equilíbrio</strong>, que incorpora as respostas do lado da oferta, permitindo que as mensalidades se ajustem endogenamente.</p>
<p>No contrafactual demand-only, a focalização por necessidade gera o maior aumento total de matrícula (35,8%), seguida pelo cenário de linha de base (31,9%), alocação aleatória (28,6%) e focalização por mérito (24,2%). Essas diferenças refletem dois fatores: o número de estudantes inframarginal (que teria se matriculado mesmo sem empréstimo) e a concentração de empréstimos em cursos mais caros, que esgota o orçamento mais rapidamente. Estudantes com nota acima da mediana são 1,8 vezes mais propensos a se matricularem sem empréstimo e se matriculam em cursos que custam em média 16% mais caro.</p>
<p>No contrafactual de equilíbrio, os ajustes endógenos de preço amplificam ou atenuam os efeitos de matrícula dependendo do esquema de focalização. Sob focalização por necessidade, a queda de preços eleva o ganho de matrícula de 35,8% (demand-only) para 39,6% (equilíbrio). Sob focalização por mérito, os aumentos de preços reduzem o efeito de 24,2% para apenas 15,8%. Para a matrícula em cursos de alto desempenho (top 10% da distribuição de qualidade, medida pelos ganhos médios dos egressos), os efeitos se invertem parcialmente no contrafactual demand-only — com focalização por mérito gerando maior aumento em cursos top (47,9% vs.&nbsp;26,8%) por conta de sorting (estudantes de baixa renda, mesmo com restrições de liquidez aliviadas, tendem a se matricular em cursos de menor nível), mas convergem no equilíbrio (34,1% vs.&nbsp;31,9% nos cursos top), com os aumentos de preço decorrentes da focalização por mérito eliminando em grande parte a vantagem inicial.</p>
</section>
<section id="implicações-de-política-102104" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="implicações-de-política-102104"><span class="header-section-number">7.3</span> Implicações de política [§102–§104]</h3>
<p>Os resultados têm duas implicações de política centrais. Primeiro, programas por necessidade que priorizam estudantes de baixa renda não apenas ampliam o acesso à educação superior para os beneficiados, mas podem também exercer pressão baixista sobre as mensalidades, potencialmente melhorando a acessibilidade para todos os estudantes — independentemente do status de empréstimo. Esse duplo efeito sublinha a força da focalização por renda como instrumento de política. Segundo, os resultados sugerem que programas por mérito, que alocam auxílio com base em desempenho acadêmico, podem contribuir para o aumento das mensalidades e potencialmente prejudicar a acessibilidade e restringir o acesso mais amplo.</p>
<p>Os autores enfatizam que a análise se concentra nos efeitos de preço da focalização e abstrai de outras dimensões do design do auxílio. Estudantes com maior desempenho acadêmico podem ter menores taxas de abandono, gerar efeitos de pares positivos e apresentar maiores taxas de repagamento dos empréstimos — fatores que poderiam melhorar a sustentabilidade financeira e os benefícios mais amplos dos programas de auxílio. Esses efeitos de preços devem ser considerados juntamente com outros fatores ao avaliar a desejabilidade global de designs alternativos.</p>
</section>
</section>
<section id="conclusão-pp.-3738" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="conclusão-pp.-3738"><span class="header-section-number">8</span> Conclusão (pp.&nbsp;37–38)</h2>
<section id="síntese-das-três-contribuições-105108" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="síntese-das-três-contribuições-105108"><span class="header-section-number">8.1</span> Síntese das três contribuições [§105–§108]</h3>
<p>A seção de conclusão sintetiza as três contribuições centrais do artigo. Primeiro, a decomposição teórica do impacto do auxílio focalizado em efeito direto (que eleva as mensalidades) e efeito composição (cuja direção depende do perfil de sensibilidade ao preço dos beneficiados). Segundo, a validação empírica utilizando a reforma do FIES de 2015. Terceiro, o desenvolvimento e estimação de um modelo de equilíbrio do ensino superior.</p>
<p>Os resultados quantitativos centrais são reafirmados: um programa por necessidade reduziria as mensalidades em 0,8% (em média, em relação ao cenário sem empréstimos), enquanto um programa por mérito as elevaria em 2,2%. Os ganhos de matrícula variam de 39,6% (por necessidade) a apenas 15,8% (por mérito). Os autores sublinham que o insight sobre o efeito composição tem relevância mais ampla para além do ensino superior: nos mercados de seguro de saúde (Polyakova &amp; Ryan, 2022), por exemplo, os efeitos do ACA sobre os preços de seguro dependem de como os subsídios são focalizados. Nos mercados habitacionais, a heterogeneidade dos resultados de estudos sobre o impacto de subsídios habitacionais sobre os aluguéis (Gibbons &amp; Manning, 2006; Fack, 2006; Eriksen &amp; Ross, 2015; Brewer et al., 2019; Hyslop &amp; Rea, 2019; Ramírez Sierra et al., 2024; Ochoa, 2025) pode também ser explicada por diferenças no perfil de sensibilidade ao preço dos beneficiados, representando uma agenda promissora de pesquisa futura.</p>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">9</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> O impacto dos programas de auxílio financeiro estudantil sobre as mensalidades das IES não pode ser resumido pela Hipótese de Bennett (auxílio eleva mensalidades) nem por sua negação: o efeito líquido sobre os preços depende criticamente de <em>quem</em> recebe o auxílio, pois a focalização altera a elasticidade da demanda residual enfrentada pelas firmas.</p>
<p><strong>Natureza do argumento:</strong> O argumento é causal-estrutural: parte de uma proposição teórica sobre o mecanismo de transmissão (decomposição em efeito direto e efeito composição, Equação 5), valida os canais com evidência reduzida quasi-experimental (diferenças-em-diferenças interagidas, aproveitando a Reforma do FIES de 2015) e quantifica os efeitos de equilíbrio via modelo estrutural estimado (BLP/GMM com micro-momentos de cutoffs de elegibilidade).</p>
<p><strong>O que o texto demonstra efetivamente:</strong> - Que cursos com maior exposição à redução de FIES reduziram mensalidades, e que essa redução é heterogênea conforme o gap de renda entre estudantes médios e tomadores de FIES (evidência reduzida robusta, Tabela 1). - Que a elasticidade-preço varia sistematicamente com renda e status de empréstimo (elasticidade mediana −5,07 para baixa renda vs.&nbsp;−2,96 para alta renda; receber empréstimo reduz sensibilidade em 11,1%). - Que, no equilíbrio contrafactual, focalização por necessidade reduz mensalidades em 0,8% e eleva matrícula de 35,8% para 39,6%; focalização por mérito eleva mensalidades em 2,2% e reduz o ganho de matrícula de 24,2% para 15,8%.</p>
<p><strong>O que permanece como hipótese ou agenda:</strong> - A generalização dos resultados para outros contextos (EUA, Europa) com maior capacidade institucional de discriminação de preços e maior seletividade das IES, onde a importância do efeito composição deve ser menor. - Os efeitos de longo prazo do design de focalização sobre qualidade, abandono, peereffects e sustentabilidade fiscal dos programas. - A relevância do efeito composição em mercados habitacionais e de seguro de saúde — mencionada, mas não demonstrada, na conclusão.</p>
<p><strong>Contribuição para o debate:</strong> O artigo reposiciona o debate sobre a Hipótese de Bennett: em vez de perguntarmos se o auxílio eleva ou não as mensalidades, a pergunta relevante passa a ser <em>para quem</em> o auxílio é direcionado e qual é o perfil de sensibilidade ao preço desse grupo. Isso tem implicações diretas para o design de políticas de crédito estudantil e para a avaliação da incidência de subsídios em mercados com imperfect competition mais geralmente.</p>
</div>
</div>
</section>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v8.1</em>. A análise é adversarial sem ser destrutiva: identifica vulnerabilidades reais do argumento e reconhece contribuições genuínas com a mesma precisão. O raciocínio analítico subjacente a cada dimensão é explicitado em itálico antes do conteúdo, separado por linha horizontal.</p>
</div>
</div>
<style>
.ficha-table { width:100%; border-collapse:collapse; font-size:0.85em;
               font-family:'Segoe UI', sans-serif; }
.ficha-table th { background-color:#2c3e50; color:white; padding:8px 10px;
                  text-align:left; vertical-align:top;
                  width:200px; min-width:180px; }
.ficha-table td { padding:8px 10px; border-bottom:1px solid #ddd;
                  vertical-align:top; }
.ficha-table tr:nth-child(even) { background-color:#f9f9f9; }
.ficha-table tr:hover           { background-color:#eef2f7; }
.ficha-table em                 { color:#555; font-style:italic; }
</style>
<table class="ficha-table">
<tbody><tr>
<th>
Questão de Pesquisa
</th>
<td>
<em>A pergunta é explicitamente formulada e tem natureza causal-comparativa. A premissa central é que o efeito do auxílio sobre preços é heterogêneo segundo o perfil dos beneficiados — hipótese plausível, mas cuja operacionalização depende de premissas sobre a relação renda-elasticidade. Uma interpretação alternativa seria que a heterogeneidade observada reflete seleção de cursos (composição endógena de beneficiados) mais do que causalidade do mecanismo proposto. O ponto mais vulnerável é a tensão entre a pergunta de equilíbrio geral (como o design de focalização afeta preços) e a identificação empírica, que é parcial/local.</em>
<hr>
<strong>Pergunta central:</strong> Como as IES ajustam suas mensalidades em resposta ao auxílio financeiro estudantil, e como esse ajuste depende do perfil de sensibilidade ao preço dos beneficiados?<br> Natureza: explicativa-causal, com componente normativo implícito (qual design de focalização é mais eficiente?). A pergunta é explicitamente declarada na Introdução (p.&nbsp;1) e operacionalizada progressivamente nas três etapas do artigo.
</td>
</tr>
<tr>
<th>
Questões Secundárias
</th>
<td>
<em>As questões secundárias emergem da estrutura do argumento e são interdependentes: a credibilidade da evidência estrutural depende da validade da evidência reduzida, que por sua vez depende da qualidade da medida de exposição.</em>
<hr>
<ol type="a">
<li>O efeito composição é empiricamente relevante no contexto do ensino superior privado brasileiro? (Seção 4.3) <br>
<ol start="2" type="a">
<li>Qual é a magnitude das elasticidades-preço e como variam com renda e status de empréstimo? (Seção 6.3) <br></li>
<li>Qual esquema de focalização (necessidade vs.&nbsp;mérito vs.&nbsp;aleatório) produz maior aumento de matrículas líquido, descontados os ajustes de preços? (Seção 7.4) <br></li>
<li>Os efeitos de preço do auxílio são suficientemente grandes para afetar significativamente as decisões de matrícula? (Seção 7.4)<br> Todas as questões secundárias subordinam-se à pergunta central, contribuindo para a cadeia de identificação teoria → evidência reduzida → modelo estrutural → contrafactuais.</li>
</ol>
</li></ol></td>
</tr>
<tr>
<th>
Puzzle-Type
</th>
<td>
<em>O puzzle é genuíno: a literatura empírica documenta efeitos heterogêneos da Hipótese de Bennett sem uma explicação mecanística unificada. A contribuição teórica (decomposição direta/composição) resolve essa ambiguidade de forma elegante. A questão é se o puzzle é generalizável: contextos com maior capacidade de discriminação de preços ou maior seletividade das IES podem tornar o efeito composição menos relevante.</em>
<hr>
<strong>Classificação:</strong> Puzzle explicativo com puzzle de avaliação de política embutido.<br> O artigo resolve o puzzle de por que a Hipótese de Bennett encontra suporte misto na literatura: a resposta é que os efeitos de preços do auxílio dependem do mecanismo de focalização. Esse puzzle é genuíno e generalizável: a heterogeneidade dos efeitos do auxílio estudantil sobre mensalidades foi documentada em múltiplos países (EUA, Chile, Colômbia, Brasil), sem uma explicação unificada. A generalizabilidade para outros mercados com menor heterogeneidade de WTP entre grupos de beneficiados ou com maior capacidade de discriminação de preços por parte das IES é, todavia, uma questão em aberto.
</td>
</tr>
<tr>
<th>
Conclusão / Argumento Central
</th>
<td>
<em>A tese é clara e bem sustentada. O claim de descoberta — que o efeito composição é um mecanismo de primeira ordem na determinação da incidência de subsídios — é apoiado tanto por evidência reduzida quanto por simulações estruturais. A distinção entre o que o design identifica com força e o que depende de premissas do modelo é crucial para avaliar a robustez.</em>
<hr>
<strong>Tese:</strong> A incidência do auxílio financeiro estudantil sobre as mensalidades decompõe-se em efeito direto (sempre positivo) e efeito composição (cuja direção depende do perfil de sensibilidade ao preço dos beneficiados). Focalização por necessidade reduz mensalidades em 0,8%; focalização por mérito as eleva em 2,2%.<br> <strong>Claim of discovery:</strong> A focalização é um determinante de primeira ordem das respostas de preço ao auxílio — o que reposiciona o debate sobre a Hipótese de Bennett.<br> O claim é sustentado por: (i) evidência reduzida robusta (Tabela 1, efeito composição estatisticamente significativo em múltiplas especificações); (ii) parâmetros estruturais com sinais teoricamente coerentes; (iii) simulações contrafactuais consistentes com os resultados da evidência reduzida.
</td>
</tr>
<tr>
<th>
Métodos
</th>
<td>
<em>O design é mixed-methods estrutural, combinando diferenças-em-diferenças interagidas com modelagem estrutural BLP. O principal risco de identificação na etapa reduzida é a endogeneidade residual da medida de exposição (concentração setorial de FIES pode correlacionar-se com choques macroeconômicos específicos ao setor). Na etapa estrutural, a validade do instrumento de preços depende da exogeneidade da reforma em relação a choques de





 <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
 <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</em></td></tr></tbody></table></section></main></div></body></html>