<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-13">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Educational Expansion and Social Mobility in the 20th Century – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-eae02f4fa95dcb10ef93ab0ebebf5ad0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Educational Expansion and Social Mobility in the 20th Century – Annotated Bibliography">
<meta property="og:description" content="Breen, R. (2010). Educational expansion and social mobility in the 20th century. Social Forces, 89(2), 365–388. https://doi.org/10.1353/SOF.2010.0076">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#introdução-pp.-365366" id="toc-introdução-pp.-365366" class="nav-link" data-scroll-target="#introdução-pp.-365366"><span class="header-section-number">1</span> Introdução (pp.&nbsp;365–366)</a>
  <ul class="collapse">
  <li><a href="#apresentação-do-puzzle-e-delimitação-do-problema-13" id="toc-apresentação-do-puzzle-e-delimitação-do-problema-13" class="nav-link" data-scroll-target="#apresentação-do-puzzle-e-delimitação-do-problema-13"><span class="header-section-number">1.1</span> Apresentação do puzzle e delimitação do problema [§1–§3]</a></li>
  </ul></li>
  <li><a href="#educational-equality-pp.-366367" id="toc-educational-equality-pp.-366367" class="nav-link" data-scroll-target="#educational-equality-pp.-366367"><span class="header-section-number">2</span> Educational Equality (pp.&nbsp;366–367)</a>
  <ul class="collapse">
  <li><a href="#o-debate-sobre-desigualdade-educacional-e-sua-evolução-47" id="toc-o-debate-sobre-desigualdade-educacional-e-sua-evolução-47" class="nav-link" data-scroll-target="#o-debate-sobre-desigualdade-educacional-e-sua-evolução-47"><span class="header-section-number">2.1</span> O debate sobre desigualdade educacional e sua evolução [§4–§7]</a></li>
  </ul></li>
  <li><a href="#social-fluidity-pp.-367368" id="toc-social-fluidity-pp.-367368" class="nav-link" data-scroll-target="#social-fluidity-pp.-367368"><span class="header-section-number">3</span> Social Fluidity (pp.&nbsp;367–368)</a>
  <ul class="collapse">
  <li><a href="#o-conceito-de-fluidez-social-e-o-debate-sobre-suas-tendências-811" id="toc-o-conceito-de-fluidez-social-e-o-debate-sobre-suas-tendências-811" class="nav-link" data-scroll-target="#o-conceito-de-fluidez-social-e-o-debate-sobre-suas-tendências-811"><span class="header-section-number">3.1</span> O conceito de fluidez social e o debate sobre suas tendências [§8–§11]</a></li>
  <li><a href="#como-a-educação-pode-influenciar-a-mobilidade-social-dois-mecanismos-1214" id="toc-como-a-educação-pode-influenciar-a-mobilidade-social-dois-mecanismos-1214" class="nav-link" data-scroll-target="#como-a-educação-pode-influenciar-a-mobilidade-social-dois-mecanismos-1214"><span class="header-section-number">3.2</span> Como a educação pode influenciar a mobilidade social: dois mecanismos [§12–§14]</a></li>
  </ul></li>
  <li><a href="#how-education-might-influence-social-mobility-an-example-pp.-368369" id="toc-how-education-might-influence-social-mobility-an-example-pp.-368369" class="nav-link" data-scroll-target="#how-education-might-influence-social-mobility-an-example-pp.-368369"><span class="header-section-number">4</span> How Education Might Influence Social Mobility: An Example (pp.&nbsp;368–369)</a>
  <ul class="collapse">
  <li><a href="#ilustração-com-tabela-hipotética-222-1517" id="toc-ilustração-com-tabela-hipotética-222-1517" class="nav-link" data-scroll-target="#ilustração-com-tabela-hipotética-222-1517"><span class="header-section-number">4.1</span> Ilustração com tabela hipotética 2×2×2 [§15–§17]</a></li>
  </ul></li>
  <li><a href="#how-education-might-influence-social-mobility-formal-derivation-pp.-370371" id="toc-how-education-might-influence-social-mobility-formal-derivation-pp.-370371" class="nav-link" data-scroll-target="#how-education-might-influence-social-mobility-formal-derivation-pp.-370371"><span class="header-section-number">5</span> How Education Might Influence Social Mobility: Formal Derivation (pp.&nbsp;370–371)</a>
  <ul class="collapse">
  <li><a href="#derivação-formal-via-modelos-log-lineares-1822" id="toc-derivação-formal-via-modelos-log-lineares-1822" class="nav-link" data-scroll-target="#derivação-formal-via-modelos-log-lineares-1822"><span class="header-section-number">5.1</span> Derivação formal via modelos log-lineares [§18–§22]</a></li>
  </ul></li>
  <li><a href="#data-pp.-371373" id="toc-data-pp.-371373" class="nav-link" data-scroll-target="#data-pp.-371373"><span class="header-section-number">6</span> Data (pp.&nbsp;371–373)</a>
  <ul class="collapse">
  <li><a href="#fontes-de-dados-classificações-e-amostras-2328" id="toc-fontes-de-dados-classificações-e-amostras-2328" class="nav-link" data-scroll-target="#fontes-de-dados-classificações-e-amostras-2328"><span class="header-section-number">6.1</span> Fontes de dados, classificações e amostras [§23–§28]</a></li>
  </ul></li>
  <li><a href="#models-and-results-pp.-373376" id="toc-models-and-results-pp.-373376" class="nav-link" data-scroll-target="#models-and-results-pp.-373376"><span class="header-section-number">7</span> Models and Results (pp.&nbsp;373–376)</a>
  <ul class="collapse">
  <li><a href="#tendências-na-desigualdade-educacional-por-coorte-2931" id="toc-tendências-na-desigualdade-educacional-por-coorte-2931" class="nav-link" data-scroll-target="#tendências-na-desigualdade-educacional-por-coorte-2931"><span class="header-section-number">7.1</span> Tendências na desigualdade educacional por coorte [§29–§31]</a></li>
  <li><a href="#associação-diferencial-e-expansão-educacional-3234" id="toc-associação-diferencial-e-expansão-educacional-3234" class="nav-link" data-scroll-target="#associação-diferencial-e-expansão-educacional-3234"><span class="header-section-number">7.2</span> Associação diferencial e expansão educacional [§32–§34]</a></li>
  </ul></li>
  <li><a href="#simulations-pp.-376381" id="toc-simulations-pp.-376381" class="nav-link" data-scroll-target="#simulations-pp.-376381"><span class="header-section-number">8</span> Simulations (pp.&nbsp;376–381)</a>
  <ul class="collapse">
  <li><a href="#método-de-decomposição-contrafactual-3538" id="toc-método-de-decomposição-contrafactual-3538" class="nav-link" data-scroll-target="#método-de-decomposição-contrafactual-3538"><span class="header-section-number">8.1</span> Método de decomposição contrafactual [§35–§38]</a></li>
  <li><a href="#resultados-da-decomposição-para-alemanha-suécia-e-grã-bretanha-3944" id="toc-resultados-da-decomposição-para-alemanha-suécia-e-grã-bretanha-3944" class="nav-link" data-scroll-target="#resultados-da-decomposição-para-alemanha-suécia-e-grã-bretanha-3944"><span class="header-section-number">8.2</span> Resultados da decomposição para Alemanha, Suécia e Grã-Bretanha [§39–§44]</a></li>
  </ul></li>
  <li><a href="#conclusions-pp.-381383" id="toc-conclusions-pp.-381383" class="nav-link" data-scroll-target="#conclusions-pp.-381383"><span class="header-section-number">9</span> Conclusions (pp.&nbsp;381–383)</a>
  <ul class="collapse">
  <li><a href="#síntese-dos-resultados-por-país-4547" id="toc-síntese-dos-resultados-por-país-4547" class="nav-link" data-scroll-target="#síntese-dos-resultados-por-país-4547"><span class="header-section-number">9.1</span> Síntese dos resultados por país [§45–§47]</a></li>
  <li><a href="#implicações-de-política-e-qualificação-do-argumento-4850" id="toc-implicações-de-política-e-qualificação-do-argumento-4850" class="nav-link" data-scroll-target="#implicações-de-política-e-qualificação-do-argumento-4850"><span class="header-section-number">9.2</span> Implicações de política e qualificação do argumento [§48–§50]</a></li>
  </ul></li>
  <li><a href="#technical-appendix-pp.-387388" id="toc-technical-appendix-pp.-387388" class="nav-link" data-scroll-target="#technical-appendix-pp.-387388"><span class="header-section-number">10</span> Technical Appendix (pp.&nbsp;387–388)</a>
  <ul class="collapse">
  <li><a href="#justificativa-da-restrição-a-homens-5152" id="toc-justificativa-da-restrição-a-homens-5152" class="nav-link" data-scroll-target="#justificativa-da-restrição-a-homens-5152"><span class="header-section-number">10.1</span> Justificativa da restrição a homens [§51–§52]</a></li>
  <li><a href="#justificativa-da-ordem-de-decomposição-e-robustez-dos-slopes-5355" id="toc-justificativa-da-ordem-de-decomposição-e-robustez-dos-slopes-5355" class="nav-link" data-scroll-target="#justificativa-da-ordem-de-decomposição-e-robustez-dos-slopes-5355"><span class="header-section-number">10.2</span> Justificativa da ordem de decomposição e robustez dos slopes [§53–§55]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">11</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Educational Expansion and Social Mobility in the 20th Century</h1>
<p class="subtitle lead">Breen, R. (2010). Educational expansion and social mobility in the 20th century. <em>Social Forces</em>, <em>89</em>(2), 365–388. https://doi.org/10.1353/SOF.2010.0076</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Sociology of Education</div>
    <div class="quarto-category">Social Stratification</div>
    <div class="quarto-category">Inequality</div>
    <div class="quarto-category">Comparative</div>
    <div class="quarto-category">2010</div>
    <div class="quarto-category">2010s</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 13, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Informações Técnicas e BibTeX
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>Última atualização: 2026-05-13
Modelo: Claude Sonnet 4.6 Thinking (Perplexity)
Prompt Version: v17.4 · 2026-05-13
Gerado em: 2026-05-13T11:40:00-03:00
Ocasião da Leitura:</code></pre>
<p><strong>Entrada BibTeX → Breen2010</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">Breen2010</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="dt">author</span>  = {Breen, Richard},</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="dt">title</span>   = {Educational Expansion and Social Mobility in the 20th Century},</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="dt">year</span>    = {2010},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="dt">journal</span> = {Social Forces},</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="dt">volume</span>  = {89},</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="dt">number</span>  = {2},</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="dt">pages</span>   = {365--388},</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="dt">doi</span>     = {10.1353/SOF.2010.0076},</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.4</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A premissa central é que educação medeia a relação entre origem e destino de classe; o puzzle é que a literatura mobilidade social foca quase exclusivamente na equalização educacional e ignora o efeito composicional da expansão. O ponto mais vulnerável é a restrição da análise a homens em três países, o que limita a validade externa.</td>
<td style="text-align: left;">Em que medida a expansão educacional — por meio do efeito composicional — e a equalização educacional contribuíram para o aumento da fluidez social no século XX? Pergunta explícita no texto; natureza explicativa-quantitativa.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">Ambas as questões decorrem diretamente da questão central; a decomposição diferenciada por coorte e país permite identificar qual mecanismo prevalece em cada contexto institucional.</td>
<td style="text-align: left;">(1) Qual dos dois mecanismos — equalização ou efeito composicional — teve maior impacto sobre a fluidez social em cada país? (2) Em que medida a <em>associação diferencial</em> (OD mais fraca em níveis educacionais mais altos) é condição necessária para o efeito composicional?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno: a presença do efeito composicional não é óbvia e depende de uma interação de três vias entre origem, educação e destino que a literatura raramente formaliza. A generalização para além dos três países é parcial: os países foram selecionados deliberadamente para representar os três mundos do welfare capitalism (Esping-Andersen 1990), o que oferece cobertura teórica, mas não garante representatividade.</td>
<td style="text-align: left;">Puzzle explicativo: a literatura de mobilidade social assume implicitamente que apenas a equalização educacional pode aumentar a fluidez social, mas a expansão educacional pode fazê-lo de forma independente via efeito composicional — mecanismo sistematicamente ignorado. O puzzle é generalizável onde a associação diferencial estiver presente.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese é bem sustentada pela simulação log-linear, mas o <em>claim of discovery</em> — que a expansão, por si só, promove fluidez social — depende criticamente da existência de associação diferencial, condição que o artigo documenta empiricamente nos três países, mas que pode não ser universal.</td>
<td style="text-align: left;">Nos três países analisados (Suécia, Grã-Bretanha e Alemanha), a expansão educacional promoveu maior fluidez social por meio do efeito composicional; na Grã-Bretanha, esse foi o único mecanismo que atuou na direção da maior fluidez; na Suécia e na Alemanha, o efeito composicional complementou a equalização. O argumento combina formalização log-linear com simulação contrafactual.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">A análise quantitativa é sofisticada, mas o método de comparação de slopes para mensurar os efeitos é uma escolha discutível: as mudanças nos coeficientes entre modelos contrafactuais dependem da ordem de remoção dos termos, e embora o autor argumente robustez da ordenação, a escolha de remover o termo COD primeiro é inevitavelmente convencional. Fichamento cobre a obra inteira (artigo + apêndice técnico).</td>
<td style="text-align: left;">Estudo quantitativo-comparativo com dados de cortes repetidos. Modelos log-lineares para decompor o efeito de quatro fontes de mudança na fluidez social (efeito COD direto, retorno à educação CED, equalização OE, efeito composicional). Simulação de tabelas COD contrafactuais, avaliadas por modelo log-multiplicativo de efeitos de camada (Xie 1992) com tendência linear (e spline para Alemanha e Grã-Bretanha).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">A heterogeneidade das fontes é uma limitação: o dado alemão combina seis surveys distintos (Allbus, Zumabus, GLHS, GSOEP, Wohlfahrts, Politik in der Bundesrepublik Deutschland), o que pode introduzir inconsistências de medição que o autor minimiza referenciando Müller e Pollak (2004). O uso de proxy de coorte por grupos etários nos dados é padrão na literatura, mas introduz imprecisão na datação exata dos efeitos.</td>
<td style="text-align: left;">Fenômeno real (mobilidade social por coorte) → surveys nacionais por amostragem (GHS para Grã-Bretanha 1973–1992; Allbus e outras fontes para Alemanha 1976–2002; ULF para Suécia 1976–1999) → codificação pela escala EGP (origens e destinos de classe) e CASMIN (educação) → cross-tabulação COED × coorte → estimação log-linear → inferência contrafactual. Unidade de análise: homens de 25–64 anos em survey; nível de agregação: coorte de nascimento × país. Viés de seleção: exclusão de mulheres (justificada); possível viés de sobrevivência nos dados de coortes mais velhas.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">O resultado para a Grã-Bretanha é o mais relevante e mais robusto: o efeito composicional é a única força que atua na direção de maior fluidez, enquanto o efeito COD direto operou contra a fluidez. Isso contraria a narrativa de que a Grã-Bretanha seria um caso de imobilidade pura.</td>
<td style="text-align: left;">(1) Em todos os três países o efeito composicional contribuiu positivamente para a fluidez social; (2) na Suécia e na Alemanha (coortes mais jovens) a equalização foi o principal motor; (3) na Grã-Bretanha o efeito COD direto foi o principal fator antiequalização; (4) a variação na relação entre educação e destino de classe (CED) não foi fonte importante de mudança em nenhum dos países. Contribuição metodológica: formalização e simulação do efeito composicional, ausente na literatura anterior.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">(a) A amostra é restrita a homens, eliminando metade da população e um período histórico de grandes mudanças na participação feminina no mercado de trabalho. (b) O design é descritivo-contrafactual, não causal no sentido estrito: a decomposição mede contribuições percentuais de diferentes termos log-lineares, não relações causais identificadas por variação exógena. (c) A presença de associação diferencial (condição necessária para o efeito composicional) é documentada empiricamente, mas não é explicada causalmente. (d) A exclusão de efeitos de período, embora justificada pela literatura, pode confundir efeitos de coorte e período em países com mudanças institucionais abruptas (ex.: reunificação alemã). (e) A generalizabilidade é restrita: países do Sul Global, com expansão educacional mais recente e mercados de trabalho distintos, podem não apresentar associação diferencial.</td>
<td style="text-align: left;">O artigo responde adequadamente à questão central dentro das <em>scope conditions</em> declaradas. O argumento é mais forte para Suécia e Alemanha (onde ambas as forças se manifestam) e mais fraco para Grã-Bretanha, onde o efeito composicional é real mas estatisticamente não significante.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> Exclusão de mulheres por razões de comparabilidade inter-temporal; impossibilidade de controlar efeitos de período sem esparsar demais as tabelas (especialmente para a Alemanha); dados britânicos com faixa etária mais restrita (25–49) por limitações do GHS; distinções de classe ligeiramente diferentes entre países por restrições dos dados. <br> <strong>Não reconhecidas ou subestimadas:</strong> A heterogeneidade das fontes alemãs é minimizada; a falta de testes de significância formais para comparação de slopes entre modelos (o próprio autor reconhece em nota que os testes não são válidos porque os dados são gerados por modelo); ausência de discussão sobre a endogeneidade potencial entre expansion e equalization (equalização quase certamente implica expansão, como o autor admite brevemente); ausência de análise de sensibilidade à escolha da escala CASMIN com cinco vs.&nbsp;seis categorias; sem investigação da heterogeneidade dentro dos grupos de coorte.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A ontologia implícita é relacional-estrutural: as chances de mobilidade são determinadas por estruturas de classe que educação pode mediar, mas não eliminar. Há coerência entre essa ontologia e o método log-linear, que captura associações relativas entre categorias de classe. A influência de Goldthorpe e Erikson é dominante (EGP, Constant Flux), com diálogo com a tradição de Esping-Andersen para estruturar a comparação.</td>
<td style="text-align: left;">Sociologia da estratificação social; tradição log-linear de mobilidade social (Goldthorpe, Erikson, Hout); teoria dos mundos do welfare capitalism (Esping-Andersen 1990) como moldura comparativa. A moldura é adequada à pergunta explicativa; a escolha dos três países não é arbitrária, mas reflete os três regimes.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo com Shavit e Blossfeld (1993) é central e bem articulado. Há certa endogeneidade bibliográfica: o autor dialoga prioritariamente com sua própria produção (Breen e Jonsson 2005, 2007; Breen e Luijkx 2004, 2007; Breen et al.&nbsp;2009, 2010).</td>
<td style="text-align: left;">Erikson e Goldthorpe (1992); Shavit e Blossfeld (1993); Breen e Jonsson (2005, 2007); Müller e Pollak (2004); Hout (1988); Xie (1992); Raftery e Hout (1993); Esping-Andersen (1990).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">O artigo tem forte contribuição metodológica — a formalização do efeito composicional e a simulação contrafactual são ferramentas transferíveis para outros contextos. Para pesquisa sobre educação superior no Brasil, o argumento sobre a distinção entre expansão e equalização é diretamente relevante: o REUNI e o SISU implicaram expansão massiva, mas a equalização é controversa. A análise, porém, depende da existência de associação diferencial no mercado de trabalho brasileiro, condição que requer verificação empírica independente.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<hr>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 19%">
<col style="width: 28%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Seção</th>
<th style="text-align: left;">Título / Tema</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Introdução (pp.&nbsp;365–366)</td>
<td style="text-align: left;">Puzzle e objetivos</td>
<td style="text-align: left;">Apresentação do puzzle</td>
<td style="text-align: left;">Estabelece que a expansão educacional pode reduzir desigualdades de mobilidade de forma independente da equalização — hipótese central</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educational Equality (pp.&nbsp;366–367)</td>
<td style="text-align: left;">Debate sobre equalização</td>
<td style="text-align: left;">Revisão de literatura</td>
<td style="text-align: left;">Mapeia o estado da arte; conclui que há evidência mais recente de equalização em vários países europeus, abrindo espaço para a comparação</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Social Fluidity (pp.&nbsp;367–368)</td>
<td style="text-align: left;">Debate sobre fluidez social</td>
<td style="text-align: left;">Revisão de literatura</td>
<td style="text-align: left;">Sintetiza os achados sobre tendências temporais em fluidez social, identificando os três países como casos com diferentes trajetórias</td>
</tr>
<tr class="even">
<td style="text-align: left;">How Education Might Influence Social Mobility: An Example (pp.&nbsp;368–369)</td>
<td style="text-align: left;">Mecanismos: formalização intuitiva</td>
<td style="text-align: left;">Fundamento teórico</td>
<td style="text-align: left;">Ilustra com tabela hipotética 2×2×2 a distinção entre equalização e efeito composicional, mostrando que cada um tem magnitude distinta</td>
</tr>
<tr class="odd">
<td style="text-align: left;">How Education Might Influence Social Mobility: Formal Derivation (pp.&nbsp;370–371)</td>
<td style="text-align: left;">Formalização log-linear</td>
<td style="text-align: left;">Fundamento metodológico</td>
<td style="text-align: left;">Deriva formalmente as equações de probabilidade condicional e os modelos log-lineares que sustentam as simulações contrafactuais</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data (pp.&nbsp;371–373)</td>
<td style="text-align: left;">Descrição dos dados</td>
<td style="text-align: left;">Análise empírica</td>
<td style="text-align: left;">Descreve fontes, períodos, esquemas de classificação (EGP, CASMIN) e tamanhos amostrais — fundamento da comparação entre países</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Models and Results (pp.&nbsp;373–376)</td>
<td style="text-align: left;">Tendências observadas em OE, OD e expansão</td>
<td style="text-align: left;">Análise empírica</td>
<td style="text-align: left;">Documenta empiricamente as condições necessárias para o efeito composicional (associação diferencial, expansão, tendências de equalização)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simulations (pp.&nbsp;376–381)</td>
<td style="text-align: left;">Decomposição contrafactual dos efeitos</td>
<td style="text-align: left;">Análise empírica central</td>
<td style="text-align: left;">Quantifica as contribuições relativas de cada mecanismo para a mudança na fluidez social; resultado principal do artigo</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Conclusions (pp.&nbsp;381–383)</td>
<td style="text-align: left;">Síntese e implicações de política</td>
<td style="text-align: left;">Síntese e extensão do argumento</td>
<td style="text-align: left;">Interpreta os resultados no contexto institucional de cada país; discute implicações de política para a equalização via expansão; qualifica a recomendação de expansão isolada</td>
</tr>
<tr class="even">
<td style="text-align: left;">Technical Appendix (pp.&nbsp;387–388)</td>
<td style="text-align: left;">Justificativa da ordem de decomposição e da amostra masculina</td>
<td style="text-align: left;">Qualificação metodológica</td>
<td style="text-align: left;">Demonstra robustez da ordenação dos termos removidos; justifica exclusão de mulheres por viés de participação no mercado de trabalho</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="introdução-pp.-365366" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-365366"><span class="header-section-number">1</span> Introdução (pp.&nbsp;365–366)</h2>
<section id="apresentação-do-puzzle-e-delimitação-do-problema-13" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="apresentação-do-puzzle-e-delimitação-do-problema-13"><span class="header-section-number">1.1</span> Apresentação do puzzle e delimitação do problema [§1–§3]</h3>
<p>O artigo abre com uma afirmação canônica na sociologia da estratificação: a desigualdade educacional segundo origem social é considerada uma causa central da desigualdade nas chances de ascensão de classe. Breen, porém, identifica um vácuo analítico relevante: embora a literatura mobilize extensamente a questão da <strong>equalização educacional</strong> — a redução das diferenças por origem de classe no acesso à educação — ela praticamente ignora a possibilidade de que a <strong>expansão educacional</strong> (o crescimento absoluto dos níveis de escolaridade) possa por si mesma contribuir para a redução das desigualdades de mobilidade.</p>
<p>O autor declara explicitamente que o objetivo da pesquisa é exploratório: aplicar um novo método para descobrir quão importantes foram a equalização e a expansão para moldar a <strong>fluidez social</strong> (<em>social fluidity</em>) na Suécia, na Grã-Bretanha e na Alemanha, ao longo de coortes nascidas do início do século XX até o início dos anos 1970. A escolha desses três países é justificada duplamente: eles representam os três mundos do welfare capitalism descritos por Esping-Andersen (1990) — regime liberal (Grã-Bretanha), social-democrata (Suécia) e conservador-continental (Alemanha) — e, conforme a literatura de mobilidade já demonstrou (Breen 2004), exibem diferentes níveis e tendências de fluidez social.</p>
<p>A Suécia é descrita como a sociedade mais aberta da Europa nesse quesito, com aumento constante de fluidez durante grande parte da segunda metade do século XX (Breen e Jonsson 2007). A Grã-Bretanha, que foi uma das sociedades mais fluidas da Europa por volta de 1970, experimentou pouca variação de período desde então. A Alemanha, historicamente menos fluida que Suécia e mais próxima da França e da Itália, apresentou aumentos significativos de fluidez nas coortes nascidas após os anos 1930 (Müller e Pollak 2004). Essas trajetórias distintas tornam o conjunto um campo de teste privilegiado para avaliar em que medida equalização e expansão contribuem diferentemente para as mudanças na fluidez.</p>
<hr>
</section>
</section>
<section id="educational-equality-pp.-366367" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="educational-equality-pp.-366367"><span class="header-section-number">2</span> Educational Equality (pp.&nbsp;366–367)</h2>
<section id="o-debate-sobre-desigualdade-educacional-e-sua-evolução-47" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="o-debate-sobre-desigualdade-educacional-e-sua-evolução-47"><span class="header-section-number">2.1</span> O debate sobre desigualdade educacional e sua evolução [§4–§7]</h3>
<p>Uma das questões mais debatidas na sociologia da estratificação recente diz respeito a saber se, ao longo do século XX, as desigualdades de acesso educacional segundo origem social diminuíram ou permaneceram estáveis. Até o final da década de 1980, era amplamente aceito que a redução da desigualdade educacional seria uma consequência inevitável da modernização e da industrialização: Treiman (1970) argumentou que a influência da educação sobre o <em>status</em> ocupacional deveria ser mais forte em sociedades mais industrializadas e que o papel do <em>status</em> parental no acesso à educação deveria declinar com o mesmo processo.</p>
<p>Esse consenso foi abalado por Shavit e Blossfeld (1993), que encontraram estabilidade na desigualdade educacional em 13 países industrializados ao longo do século XX. Não obstante a expansão substancial dos sistemas educacionais — sobretudo no nível médio-inferior —, apenas dois países (Suécia e Holanda) apresentaram redução na força da associação entre origem social e nível de escolaridade. Os editores concluíram que havia “pouca mudança na desigualdade socioeconômica de oportunidade educacional” e que “o impacto das reformas educacionais sobre mudanças na estratificação educacional parece ser negligenciável.” Em outras palavras, embora os níveis absolutos de escolaridade tenham aumentado em toda parte, as <em>chances relativas</em> de avanço educacional entre pessoas de diferentes origens sociais permaneceram em geral inalteradas.</p>
<p>Breen e Jonsson (2005:226) oferecem, porém, uma revisão posterior que reverte parcialmente o diagnóstico de Shavit e Blossfeld: análises subsequentes demonstraram equalização na Alemanha (Henz e Maas 1995; Jonsson, Mills e Müller 1996; Müller e Haun 1994), na França (Vallet 2004a), na Itália (Shavit e Westerbeek 1998) e provavelmente na Noruega (Lindbekk 1998). Breen et al.&nbsp;(2009, 2010), em análises comparativas de oito países europeus, identificam uma tendência à diminuição da influência das origens sociais sobre a escolaridade nas coortes nascidas nos primeiros três quartos do século XX, com variações cross-nacionais importantes. A discrepância entre estudos é atribuída em parte a diferenças nas medidas de origem social e nos modelos estatísticos utilizados — mas Breen observa que é surpreendente que o padrão básico não seja robusto a tais variações.</p>
<hr>
</section>
</section>
<section id="social-fluidity-pp.-367368" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="social-fluidity-pp.-367368"><span class="header-section-number">3</span> Social Fluidity (pp.&nbsp;367–368)</h2>
<section id="o-conceito-de-fluidez-social-e-o-debate-sobre-suas-tendências-811" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="o-conceito-de-fluidez-social-e-o-debate-sobre-suas-tendências-811"><span class="header-section-number">3.1</span> O conceito de fluidez social e o debate sobre suas tendências [§8–§11]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>fluidez social</strong> (<em>social fluidity</em>) é definida como a razão de chances (<em>odds ratio</em>) entre respondentes nascidos em diferentes origens de classe de vir a ocupar uma posição de classe mais ou menos vantajosa. Diferentemente das taxas brutas de mobilidade — influenciadas pela estrutura de classe da sociedade —, os <em>odds ratios</em> capturam as <em>chances relativas de mobilidade</em> independentemente de mudanças nas distribuições marginais de origem e destino.</p>
</div>
</div>
<p>A educação é identificada como o principal canal pelo qual a reprodução de classe ocorre entre gerações (Ishida, Müller e Ridge 1995). A premissa central da literatura é que a desigualdade educacional importa sobretudo porque pode afetar as chances de mobilidade social: se a <strong>fluidez educacional</strong> (a independência entre origem de classe e escolaridade) aumentar, a fluidez social tende a aumentar em consequência. Erikson e Goldthorpe (1992) argumentaram por uma “estabilidade temporal elevada” da fluidez social, mas esse julgamento se baseava em comparações de grupos etários extraídos de um único survey por país — uma estratégia que confunde efeitos de coorte e de período.</p>
<p>Estudos baseados em séries de surveys repetidos ao longo do tempo são raros. Entre as exceções mais conhecidas estão Ganzeboom, Luijkx e Treiman (1989), que demonstraram “diferenças cross-nacionais e cross-temporais substanciais na extensão da mobilidade,” e Breen e Luijkx (2004), que documentaram variação significativa entre países europeus e uma tendência generalizada a maior fluidez nas últimas décadas do século XX. Análises por coorte de nascimento para países específicos — Hout (1988) para os EUA, Vallet (2004a) para a França, Müller e Pollak (2004) para a Alemanha, Breen e Jonsson (2007) para a Suécia — mostram, em todos os casos, um declínio gradual na associação entre origens e destinos de classe durante o século XX.</p>
</section>
<section id="como-a-educação-pode-influenciar-a-mobilidade-social-dois-mecanismos-1214" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="como-a-educação-pode-influenciar-a-mobilidade-social-dois-mecanismos-1214"><span class="header-section-number">3.2</span> Como a educação pode influenciar a mobilidade social: dois mecanismos [§12–§14]</h3>
<p>Seguindo Breen e Jonsson (2007), o artigo distingue dois caminhos pelos quais a educação pode aumentar a fluidez social. O primeiro é a <strong>equalização</strong> (<em>equalization</em>): quando a associação entre origem de classe e escolaridade se enfraquece ao longo das coortes, a ligação entre origem e destino de classe tende a se enfraquecer por consequência, dado que a educação é o determinante mais importante da posição de classe. O segundo caminho é <strong>composicional</strong>: se a associação origem-destino for mais fraca em níveis educacionais mais elevados — o que Breen denomina <strong>associação diferencial</strong> (<em>differential association</em>) —, e se a expansão educacional aumentar a proporção de coortes sucessivas que alcançam esses níveis, essa mudança composicional reduzirá a associação bruta entre origens e destinos. A razão é que a população passará a conter proporções crescentes de indivíduos (os mais escolarizados) para os quais as origens de classe exercem efeito relativamente fraco sobre os destinos.</p>
<blockquote class="blockquote">
<p>Breen ressalta que a preocupação dos analistas de mobilidade social com a equalização educacional é demasiado restritiva: a expansão em si — sobre cuja ocorrência não há controvérsia — pode ter a capacidade de enfraquecer a associação entre origens e destinos, mesmo na ausência de equalização.</p>
</blockquote>
<p>A <strong>associação diferencial</strong> já havia sido identificada por Hout (1988) e documentada em seguida para França (Vallet 2004b), Suécia (Erikson e Jonsson 1998) e Alemanha (Breen e Luijkx 2007). A justificativa teórica é que qualificações de nível superior funcionam como sinais mais fortes aos empregadores, deixando menos espaço para efeitos de rede social baseados em origem de classe, e/ou que os mercados de trabalho em que os graduados operam são mais meritocráticos.</p>
<hr>
</section>
</section>
<section id="how-education-might-influence-social-mobility-an-example-pp.-368369" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="how-education-might-influence-social-mobility-an-example-pp.-368369"><span class="header-section-number">4</span> How Education Might Influence Social Mobility: An Example (pp.&nbsp;368–369)</h2>
<section id="ilustração-com-tabela-hipotética-222-1517" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="ilustração-com-tabela-hipotética-222-1517"><span class="header-section-number">4.1</span> Ilustração com tabela hipotética 2×2×2 [§15–§17]</h3>
<p>Para tornar os dois mecanismos concretos antes de sua derivação formal, Breen constrói uma <strong>tabela hipotética 2×2×2</strong> em que origens de classe (classe média/classe trabalhadora), nível educacional (baixo/alto) e destino de classe (classe média/classe trabalhadora) são cruzados em dois momentos de tempo. Por design, a associação origem-destino é mais fraca no nível educacional alto, capturando a associação diferencial.</p>
<p>O cenário base (tempo = 1) apresenta um <em>odds ratio</em> OE de 1,5 e um <em>odds ratio</em> OD bruto de 4,14. No caso (a) — equalização pura, sem mudança nas distribuições marginais —, o <em>odds ratio</em> OE cai de 1,5 para 1,31 enquanto as distribuições marginais são mantidas constantes, resultando em uma redução do <em>odds ratio</em> OD bruto de 4,14 para 4,03. No caso (b) — expansão pura com associação diferencial presente, sem mudança no <em>odds ratio</em> OE —, o deslocamento da distribuição de educação para o nível mais alto reduz o <em>odds ratio</em> OD bruto para 3,87. Finalmente, no caso (c) — equalização e expansão combinadas —, o <em>odds ratio</em> OD bruto cai para 3,77. A tabela demonstra de modo intuitivo que a expansão, por si só, pode ter um impacto quantitativo maior do que a equalização sobre a fluidez bruta — resultado contraintuitivo que motiva toda a análise empírica subsequente.</p>
<blockquote class="blockquote">
<p><strong>Nota:</strong> O autor nota que o efeito composicional requer duas condições simultâneas: expansão educacional <em>e</em> associação diferencial. A ausência de qualquer uma das duas anula o mecanismo composicional, independentemente da magnitude da expansão. <a href="https://ppl-ai-file-upload.s3.us-east-1.amazonaws.com/web/direct-files/attachments/111334221/90e5243a-ff10-428d-81ba-4b87a4edcb2b/Breen-2010-Educational-Expansion-and-Social-Mobility-in-the-20th-Century.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Checksum-Mode=ENABLED&amp;X-Amz-Credential=ASIA2F3EMEYE7CHSRSYF%2F20260513%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20260513T144742Z&amp;X-Amz-Expires=3600&amp;X-Amz-Security-Token=IQoJb3JpZ2luX2VjEH8aCXVzLWVhc3QtMSJHMEUCIAOIBnnC4hnB9MWn%2Fx5QESowSjtKTYW3hLSBqlu950zQAiEArUWCUE3VKE7Lw9ssP59HP6gU25RVSB%2BoYpx6PsjDBL8q6wQIRxABGgw2OTk3NTMzMDk3MDUiDHIRMhnIKE4EjoSuaCrIBKjEJMJ6PJXrRnW2A%2Bb66qWL5%2BCcSwO6VQSQUxB0RSnHyDBV8ruwal2hhdER7wIJWfwBJ3wMi%2Buwiwzm96FhOCiijSg4NeXZf%2BVGaX%2B81VRaa2zyvH8g7iCElh31H8NFC2hV5j%2Bo5sQbdQQbRntUYW%2FbAvv9Z9kqUhosm6q1TJbeUuNIn2hK4bQ3dGEav0sOQ90Q%2FWqNpKk6mQTNjg%2FTCV0eo3MJ5QjQjUs0eys7z2OPcHL7Mc5XQjwT6UtJpgQd3Is%2F6QB4%2FNqoHNAucVrzEEiJKeMXpJ%2FfrMjgLRbRrm7HSSYmx55405DC%2FZuT3MhH1ii5rHbQkTPXUJb%2BaTb6ixgZ8gIIOQCjUPw0Brp9KeEIIsl62Z%2FM1l1%2FVpZHdgd53jWVkKrP2ok7o22vvl3XXkrkc0JPHjMQPmrBout%2FRbSI3jQB0KLKCTSNzLD3zfF5brPKHCKsO5hWxRnoTpYilIzdylN0rasARatviiuD2zz8xtheVYTKPUTxCmRbKADi2mhtzz0dOEAyaANQDW9DM46TXjG9fimYtOhwzjdvINZW8sx0F83o4X4zXXOq7W1gdqpDdeU2dsQJ4D1NPocS%2FKNzxck3ZPtdfeEJKPr2OI0Fl0rsZgpDbbvBmnXZthOsmkv2EldMBisueLmvP8iPb%2B6REqpl0e3dCNdoYasfsysu9HX37fwPvMgYT8zOr%2BBQOCzilAiDXiiGASddS5f%2FK%2BJJURyxdHSzbXDkWnWJe8EPswhBj2IcO%2FfDF2VX9h9QP0xqxG5OH6QkML2MktAGOpgBj2Zcq6tsOQEEaO1%2FiQc4r5LQ5eWS5MRj40A278xhBd9XubbhB3FmWUfa1Vu5i2hi82Zjys8lib1x%2Fzyv4GA5K%2B7oUOIEjIGkxZM6tykFIYoAj3dIkhtJFEFIR%2BfsFgdM0X4sWucEo9lhips%2FRFucGz%2BiaITbf0Qg%2B%2BJhvHlZ2r8vTJOhf1aIxroUvPho5mBF02C1%2Fd%2Fgoes%3D&amp;X-Amz-SignedHeaders=host&amp;x-id=GetObject&amp;X-Amz-Signature=11bbf5f2b6e56f0b979757e5b3a4ffec8427fe4464d31d0127d1cef1892aa642">ppl-ai-file-upload.s3.us-east-1.amazonaws</a></p>
</blockquote>
<hr>
</section>
</section>
<section id="how-education-might-influence-social-mobility-formal-derivation-pp.-370371" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="how-education-might-influence-social-mobility-formal-derivation-pp.-370371"><span class="header-section-number">5</span> How Education Might Influence Social Mobility: Formal Derivation (pp.&nbsp;370–371)</h2>
<section id="derivação-formal-via-modelos-log-lineares-1822" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="derivação-formal-via-modelos-log-lineares-1822"><span class="header-section-number">5.1</span> Derivação formal via modelos log-lineares [§18–§22]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>O coração metodológico do artigo está nessa seção. Breen considera uma <strong>cross-tabulação de quatro vias</strong> entre origem de classe (O), nível educacional (E), destino de classe (D) e coorte de nascimento (C), todas tratadas como variáveis categóricas. O objetivo é decompor a distribuição COD em componentes atribuíveis a diferentes fontes de mudança ao longo das coortes.</p>
</div>
</div>
<p>A distribuição conjunta das quatro variáveis é escrita como produto de probabilidades condicionais:</p>
<p>[p(C=i, O=j, E=k, D=l) = p(D=l C=i, O=j, E=k) p(E=k C=i, O=j) p(C=i, O=j)]</p>
<p>A margem CO é tratada como exógena e reproduzida exatamente em todos os modelos. A distribuição tridimensional COD é obtida somando sobre os níveis de E. Modelos log-lineares específicos para as tabelas COE e COED permitem recuperar as distribuições condicionais necessárias para gerar tabelas COD contrafactuais, variando sistematicamente quais termos de interação estão presentes.</p>
<p>Dois modelos log-lineares são centrais. O modelo para a tabela COE tem a forma:</p>
<p>[f_{ijk} = ^C_i + ^O_j + ^E_k + ^{CO}<em>{ij} + ^{CE}</em>{ik} + ^{OE}<em>{jk} + ^{COE}</em>{ijk}]</p>
<p>onde (^{CE}<em>{ik}) captura a expansão educacional, (^{OE}</em>{jk}) captura a associação origens-educação, e (^{COE}<em>{ijk}) captura a equalização (mudança na associação OE ao longo das coortes). O modelo para a tabela COED é análogo, acrescentando termos para o efeito direto de origem sobre destino ((^{COD}</em>{ijl})), o efeito de educação sobre destino variando por coorte ((^{CED}<em>{ikl})) e a associação diferencial ((^{OED}</em>{jkl})).</p>
<p>Breen demonstra formalmente que mesmo sem equalização — ou seja, sem o termo (^{COE}_{ijk}) — a combinação de expansão educacional e associação diferencial implica uma associação entre O, D e C, ou seja, mudança na fluidez ao longo das coortes. Esse resultado formaliza a intuição apresentada na tabela hipotética e fundamenta as simulações contrafactuais.</p>
<hr>
</section>
</section>
<section id="data-pp.-371373" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="data-pp.-371373"><span class="header-section-number">6</span> Data (pp.&nbsp;371–373)</h2>
<section id="fontes-de-dados-classificações-e-amostras-2328" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="fontes-de-dados-classificações-e-amostras-2328"><span class="header-section-number">6.1</span> Fontes de dados, classificações e amostras [§23–§28]</h3>
<p>Os dados provêm de três fontes nacionais. Para a <strong>Grã-Bretanha</strong>, o <em>General Household Survey</em> (GHS) cobre os anos 1973, 1975–1976 e 1979–1992 (com os anos 1977, 1978, 1985 e 1986 excluídos por falta de informação sobre a ocupação paterna, e o ano 1974 excluído por problemas documentados por Goldthorpe e Mills 2004). Para a <strong>Alemanha</strong>, os dados abrangem 1976 a 2002 e são extraídos principalmente do Allbus, complementado por Zumabus, surveys de bem-estar, do painel socioeconômico alemão (GSOEP) e pelo <em>German Life History Study</em>. Müller e Pollak (2004) atestam a comparabilidade dos questionários e a ausência de inconsistências sistemáticas; a análise se restringe a residentes na antiga Alemanha Ocidental para garantir comparabilidade temporal. Para a <strong>Suécia</strong>, as 24 pesquisas anuais de condições de vida (ULF, 1976–1999) conduzidas pelo Statistics Sweden formam o conjunto de dados.</p>
<p>A análise se restringe a <strong>homens</strong> (justificativa desenvolvida no apêndice técnico), na faixa etária de trabalho. Para a Alemanha e a Suécia, a faixa é de 25 a 64 anos; para a Grã-Bretanha, 25 a 49 anos (por limitação do GHS para respondentes mais velhos). As <strong>origens e destinos de classe</strong> (O e D) são definidos com o esquema EGP (Erikson e Goldthorpe 1992) em sete classes: (I) serviço superior; (II) serviço inferior; (IIIa) não-manual de rotina; (IVab) autônomos e pequenos empregadores; (IVc) agricultores; (V+VI) manuais qualificados, técnicos e supervisores; (VIIab+IIIb) semi e não qualificados. Restrições dos dados levam ao uso de seis classes tanto para a Grã-Bretanha (I+II+IVa fundidos) quanto para a Suécia (VIIab e IIIb não distinguidos).</p>
<p>A <strong>educação</strong> (E) é medida pela maior qualificação formal, codificada segundo o esquema CASMIN (Müller et al.&nbsp;1989) em cinco categorias: 1abc (apenas educação compulsória); 2ab (educação secundária intermediária, vocacional e geral); 2c (educação secundária completa); 3a (terciária inferior); 3b (terciária superior). A Suécia usa seis categorias por distinguir entre 1ab e 1c. As <strong>coortes de nascimento</strong> são definidas de modo diferente em cada país, cobrindo do início dos anos 1910 ao final dos anos 1970 na Alemanha, do início dos anos 1920 ao final dos anos 1960 na Grã-Bretanha, e do início dos anos 1910 ao final dos anos 1970 na Suécia. Os tamanhos amostrais são: 18.961 para Alemanha, 58.125,5 para Grã-Bretanha (ponderado para corrigir sobreamostragem escocesa) e 33.281 para Suécia.</p>
<blockquote class="blockquote">
<p><strong>Nota:</strong> O autor ressalta que nem todas as coortes são observadas em todos os surveys: as coortes mais velhas e mais jovens são observadas menos frequentemente, enquanto as coortes nascidas em torno do meio do século são as mais bem representadas. Isso deve ser considerado na interpretação dos resultados nas extremidades da série temporal. <a href="https://academic.oup.com/sf/article/89/2/365/2235230">academic.oup</a></p>
</blockquote>
<hr>
</section>
</section>
<section id="models-and-results-pp.-373376" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="models-and-results-pp.-373376"><span class="header-section-number">7</span> Models and Results (pp.&nbsp;373–376)</h2>
<section id="tendências-na-desigualdade-educacional-por-coorte-2931" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="tendências-na-desigualdade-educacional-por-coorte-2931"><span class="header-section-number">7.1</span> Tendências na desigualdade educacional por coorte [§29–§31]</h3>
<p>A Figura 1 apresenta as tendências na associação entre origem de classe e escolaridade ao longo das coortes, estimadas por modelos de <em>logit</em> ordenado. Para a <strong>Alemanha</strong> e a <strong>Suécia</strong>, a impressão geral é de declínio nas desigualdades de classe no acesso à educação — as linhas para diferentes origens de classe convergem progressivamente ao longo das coortes. Para a <strong>Grã-Bretanha</strong>, o padrão é menos claro; nota-se que entre as coortes mais velhas as diferenças de classe já eram menores do que na Alemanha, e que mesmo entre a coorte mais jovem elas permanecem inferiores às alemãs — embora o autor ressalve que isso deve ser interpretado à luz das diferenças nas classificações de classe britânicas, onde a classe mais alta é definida de forma mais heterogênea.</p>
</section>
<section id="associação-diferencial-e-expansão-educacional-3234" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="associação-diferencial-e-expansão-educacional-3234"><span class="header-section-number">7.2</span> Associação diferencial e expansão educacional [§32–§34]</h3>
<p>A Figura 2 documenta a <strong>associação diferencial</strong>: a força da associação origem-destino a cada nível educacional, medida por um modelo de efeito de camada log-multiplicativo (Xie 1992), com o nível de associação no nível educacional mais baixo fixado em 1. Nos três países, a tendência é de enfraquecimento da associação OD em níveis educacionais mais elevados — embora na Alemanha e na Suécia a associação seja mais fraca no nível terciário inferior (3a) do que no superior (3b). Essa constatação confirma a condição necessária para o efeito composicional em todos os três países.</p>
<p>A Figura 3 ilustra a <strong>expansão educacional</strong> comparando a distribuição educacional das segundas coortes mais velhas e mais jovens em cada país. Os três países mostram expansão clara. A expansão é particularmente pronunciada na Grã-Bretanha, onde as coortes mais velhas estavam fortemente concentradas no nível educacional mais baixo. Finalmente, a Figura 4 apresenta a tendência da associação bruta origem-destino ao longo das coortes. A <strong>Suécia</strong> exibe um declínio aproximadamente constante ao longo de todas as coortes, replicando achados de Breen e Jonsson (2007). A <strong>Alemanha</strong> apresenta um fortalecimento inicial seguido de um declínio acentuado a partir da terceira coorte (nascida entre 1931 e 1939), padrão já documentado em Müller e Pollak (2004). A <strong>Grã-Bretanha</strong> mostra um fortalecimento inicial da associação OD, seguido de estabilidade a partir da coorte nascida entre 1942 e 1948 — o modesto declínio subsequente não é estatisticamente significante.</p>
<hr>
</section>
</section>
<section id="simulations-pp.-376381" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="simulations-pp.-376381"><span class="header-section-number">8</span> Simulations (pp.&nbsp;376–381)</h2>
<section id="método-de-decomposição-contrafactual-3538" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="método-de-decomposição-contrafactual-3538"><span class="header-section-number">8.1</span> Método de decomposição contrafactual [§35–§38]</h3>
<p>Para mensurar as contribuições relativas dos quatro mecanismos de mudança — (1) o efeito direto parcial de origens sobre destinos (COD); (2) as mudanças nos retornos à educação em termos de posição de classe (CED); (3) a equalização educacional (mudança na associação OE por coorte); e (4) o efeito composicional (expansão + associação diferencial) —, Breen gera um conjunto de cinco <strong>tabelas COD contrafactuais</strong> removendo sequencialmente termos do modelo log-linear inicial.</p>
<p>O modelo inicial (1) inclui todos os efeitos nas tabelas E|OC e D|OEC exceto a interação de quatro vias COED. O segundo modelo (2) remove o termo (^{COD}<em>{ijl}) (efeito parcial direto de origens sobre destinos por coorte); como qualquer modelo com esse termo sempre reproduz o COD observado, ele deve ser removido primeiro. O terceiro modelo (3) remove o termo (^{CED}</em>{ikl}) (mudança nos retornos à educação). O quarto modelo (4) remove o termo (^{COE}<em>{ijk}) (equalização). O quinto e último modelo (5) remove simultaneamente (^{CE}</em>{ik}) (expansão) e (^{OED}_{jkl}) (associação diferencial), eliminando assim o efeito composicional. A comparação entre as tabelas COD geradas por modelos sucessivos permite isolar a contribuição de cada mecanismo.</p>
<p>O efeito de cada mecanismo sobre a fluidez é capturado comparando os <strong>slopes</strong> (()) de tendência linear obtidos pelo modelo log-multiplicativo de efeito de camada (Xie 1992) aplicado a cada tabela contrafactual. Para a Alemanha e a Grã-Bretanha, onde a tendência não é linear, uma <em>spline</em> com dois slopes é ajustada — um para as coortes mais velhas, outro para as mais jovens. Um valor positivo de () indica crescente associação OD (menor fluidez); um valor negativo indica redução (maior fluidez).</p>
<blockquote class="blockquote">
<p><strong>Nota:</strong> O próprio autor reconhece em nota de rodapé que os testes de significância estatística reportados na Tabela 3 não são testes formalmente válidos, porque os dados sobre os quais o modelo é ajustado são eles mesmos gerados por um modelo — não observações empíricas independentes. <a href="https://www.semanticscholar.org/paper/Educational-Expansion-and-Social-Mobility-in-the-Breen/12884b77847170b27d53520beeaf9e7a2e58f506">semanticscholar</a></p>
</blockquote>
</section>
<section id="resultados-da-decomposição-para-alemanha-suécia-e-grã-bretanha-3944" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="resultados-da-decomposição-para-alemanha-suécia-e-grã-bretanha-3944"><span class="header-section-number">8.2</span> Resultados da decomposição para Alemanha, Suécia e Grã-Bretanha [§39–§44]</h3>
<p>Para a <strong>Alemanha</strong>, entre as coortes mais velhas, o principal fator de <em>aumento</em> da associação OD foi o efeito COD direto — as contribuições percentuais mostram que foi esse mecanismo que impulsionou a desigualdade nas coortes mais antigas, enquanto o efeito composicional operou na direção oposta (redução da desigualdade). Entre as coortes mais jovens, os principais fatores de redução da associação OD foram o efeito composicional (68,17% da variação total no segundo slope) e a equalização educacional (31,50%), com o efeito CED contribuindo marginalmente e negativamente. O efeito COD direto nos coortes jovens levemente promoveu igualdade (0,39%).</p>
<p>Para a <strong>Suécia</strong>, onde uma tendência linear é suficiente, o efeito COD operou na direção de <em>menor</em> fluidez (slope de -1,62 no modelo sem COD, comparado com -0,96 no modelo observado — o que implica que o COD reduziu a fluidez em 68,75%). O efeito CED também reduziu ligeiramente a fluidez (-13,54%). A remoção da equalização torna o slope muito menos negativo (de -0,76 para próximo de zero), indicando que a equalização foi responsável por 103,13% da mudança observada. O efeito composicional contribuiu com 79,17% — os valores somam mais de 100% porque alguns efeitos atuaram em sentidos opostos.</p>
<p>Para a <strong>Grã-Bretanha</strong>, apenas o primeiro modelo (com todos os efeitos) apresenta slopes estatisticamente significantes. Uma vez removido o efeito COD, ambos os slopes se tornam não significantes, indicando que a variação temporal na fluidez britânica foi quase inteiramente determinada por mudanças no efeito parcial direto de origens sobre destinos — que atuou na direção de <em>menor</em> fluidez, tanto nas coortes mais velhas (-84,71%) quanto nas mais jovens (-147,24%). A equalização teve efeito equalizante nas coortes mais velhas, mas desequalizante nas mais jovens. O único mecanismo que atuou consistentemente na direção de maior fluidez foi o efeito composicional (+78,83% entre as coortes jovens), embora esse efeito não alcance significância estatística.</p>
<hr>
</section>
</section>
<section id="conclusions-pp.-381383" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="conclusions-pp.-381383"><span class="header-section-number">9</span> Conclusions (pp.&nbsp;381–383)</h2>
<section id="síntese-dos-resultados-por-país-4547" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="síntese-dos-resultados-por-país-4547"><span class="header-section-number">9.1</span> Síntese dos resultados por país [§45–§47]</h3>
<p>A conclusão retoma a lógica contrafactual: o artigo estimou o que teria acontecido com a fluidez social caso, por exemplo, a associação entre origens de classe e escolaridade tivesse permanecido constante ao longo do tempo, comparado ao que de fato ocorreu. Na <strong>Suécia</strong>, a equalização das chances educacionais teve um efeito consistente sobre o aumento da fluidez social; políticas como a eliminação de taxas para educação secundária e terciária, a introdução de refeições e materiais escolares gratuitos, e a reforma de escolas abrangentes (<em>comprehensive schools</em>) na década de 1950 tornaram as oportunidades educacionais menos dependentes dos recursos econômicos da família de origem (Erikson 1996). A igualdade de condições alcançada via tributação progressiva, redistribuição pelo welfare state (Korpi e Palme 2004) e políticas de mercado de trabalho contribuiu adicionalmente para a equalização.</p>
<p>Na <strong>Alemanha</strong>, a equalização operou principalmente nas coortes nascidas após os anos 1930. Jonsson, Mills e Müller (1996) argumentam que o período do <em>Wirtschaftswunder</em> garantiu segurança econômica a todas as classes sociais, enquanto sindicatos fortes asseguraram condições de trabalho favoráveis e acordos de pensão. Políticas educacionais específicas — como o aumento do período de educação compulsória e a elevação do nível de educação geral exigido para o acesso à aprendizagem — contribuíram indiretamente para que crianças da classe trabalhadora adquirissem maior escolaridade, mesmo que inicialmente motivadas pela aprendizagem vocacional.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>Grã-Bretanha</strong> promulgou muitas das mesmas reformas que a Suécia — a Lei de Educação de 1944 tornou o ensino secundário gratuito; a diferenciação dentro do setor público foi reduzida após o final dos anos 1960 — mas aparentemente sem o mesmo efeito equalizador. O sistema altamente diferenciado (incluindo um pequeno setor privado persistente) manteve a seleção por desempenho examinatório. O welfare state britânico nunca desempenhou o mesmo papel redistributivo do sueco, e a Grã-Bretanha nunca desenvolveu políticas de mercado de trabalho de tipo corporatista. A persistência de um mercado de trabalho para trabalhadores semi ou não qualificados pode ter incentivado crianças de classe trabalhadora a deixar a escola na idade mais jovem possível, mantendo as diferenças de classe no acesso educacional.</p>
</div>
</div>
</section>
<section id="implicações-de-política-e-qualificação-do-argumento-4850" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="implicações-de-política-e-qualificação-do-argumento-4850"><span class="header-section-number">9.2</span> Implicações de política e qualificação do argumento [§48–§50]</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>O artigo conclui que sociólogos da educação e da estratificação social têm amplamente subestimado o potencial da expansão educacional para promover maior igualdade nas chances de mobilidade, mesmo nos casos em que a equalização não ocorreu. Na Alemanha, o efeito composicional foi mais forte do que o efeito de equalização entre as coortes mais jovens; na Suécia, onde a equalização foi a principal causa do aumento de fluidez, o efeito composicional também contribuiu; na Grã-Bretanha, foi o único mecanismo que apontou na direção de maior fluidez.</p>
</div>
</div>
<p>O autor qualifica, porém, a recomendação de política pública: se os beneficiários da expansão forem principalmente jovens de origens de classe mais favorecidas, isso pode promover desigualdade educacional cujo impacto sobre a fluidez social contrabalance o efeito composicional (Jonsson e Erikson 2007). A <strong>expansão educacional isolada é, portanto, uma estratégia de risco</strong> se o objetivo é aumentar a fluidez social. Em contrapartida, <strong>promover a equalização educacional tende a ser uma estratégia mais eficaz</strong>, porque a equalização quase certamente implica expansão dos níveis médio e superior de escolaridade — dado que é improvável que a equalização ocorra por redução da participação educacional das classes médias (como notam Raftery e Hout 1993 e Breen e Jonsson 2007).</p>
<hr>
</section>
</section>
<section id="technical-appendix-pp.-387388" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="technical-appendix-pp.-387388"><span class="header-section-number">10</span> Technical Appendix (pp.&nbsp;387–388)</h2>
<section id="justificativa-da-restrição-a-homens-5152" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="justificativa-da-restrição-a-homens-5152"><span class="header-section-number">10.1</span> Justificativa da restrição a homens [§51–§52]</h3>
<p>O apêndice técnico apresenta dois conjuntos de justificativas metodológicas. O primeiro diz respeito à exclusão de mulheres: análises envolvendo posição de classe restringem atenção a pessoas atualmente no mercado de trabalho. Incluir indivíduos fora da força de trabalho implicaria usar posições de classe ocupadas no passado distante ou derivadas dos cônjuges, conforme as convenções do survey específico. Mais criticamente, comparações temporais seriam comprometidas se as taxas de participação no mercado de trabalho variassem dentro das coortes de nascimento ao longo do ciclo de vida — o que, no caso dos homens, é geralmente não problemático. Na Grã-Bretanha e na Alemanha, há tanto uma tendência histórica de crescente participação feminina quanto padrões pronunciados de participação e não-participação ao longo do ciclo de vida. Na Suécia, ao contrário, o padrão de participação feminina varia menos ao longo do ciclo de vida e se assemelha mais ao masculino — razão pela qual Breen e Jonsson (2007) incluíram mulheres em análise exclusivamente sueca.</p>
</section>
<section id="justificativa-da-ordem-de-decomposição-e-robustez-dos-slopes-5355" class="level3" data-number="10.2">
<h3 data-number="10.2" class="anchored" data-anchor-id="justificativa-da-ordem-de-decomposição-e-robustez-dos-slopes-5355"><span class="header-section-number">10.2</span> Justificativa da ordem de decomposição e robustez dos slopes [§53–§55]</h3>
<p>O segundo conjunto de justificativas trata da ordem em que os termos são removidos dos modelos. O argumento é que há pouca discricionariedade real: enquanto o termo (^{COD}<em>{ijl}) permanecer no modelo, o COD implicado sempre reproduzirá o COD observado, portanto ele deve ser removido primeiro. Além disso, o efeito composicional requer dois termos — (^{OED}</em>{jkl}) e (^{CE}_{ik}) — e removê-los separadamente tornaria o modelo de equalização não-hierárquico. O autor informa que os outros dois ordenamentos possíveis dentro dessas restrições produzem contribuições relativas quase idênticas e conclusões substantivas inalteradas.</p>
<p>A justificativa para comparar slopes em vez de comparar fluidez em uma coorte dada reside em um problema técnico: quando um termo como (^{COD}<em>{ijl}) é removido, a associação parcial OD não é fixada em seu valor na coorte mais velha, mas em um valor médio complexo ao longo de todas as coortes. Isso torna a comparação direta de associações em uma dada coorte infactível. A comparação de slopes contorna esse problema porque o slope é invariante ao reescalonamento das associações em todas as coortes pelo valor de (^{OD}</em>{jl}).</p>
<hr>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">11</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> A expansão educacional, ao deslocar coortes sucessivas para níveis de escolaridade nos quais a associação entre origens e destinos de classe é estruturalmente mais fraca (<em>associação diferencial</em>), produz por si mesma um efeito composicional que aumenta a fluidez social — mecanismo distinto e empiricamente mensurável em relação à equalização educacional e sistematicamente negligenciado pela literatura de mobilidade social.</p>
<p><strong>Natureza do argumento:</strong> O argumento é explicativo-quantitativo, com formalização log-linear e simulação contrafactual. Não é um argumento causal no sentido de identificação por variação exógena, mas uma decomposição analítica de contribuições relativas a padrões observados de mudança.</p>
<p><strong>O que o texto demonstra:</strong> (1) Que a associação diferencial existe nos três países estudados; (2) que a expansão educacional ocorreu em todos os três países; (3) que o efeito composicional teve contribuição positiva mensurável sobre a fluidez social em todos os três países; (4) que na Grã-Bretanha foi o único mecanismo operando na direção de maior fluidez; (5) que a variação nos retornos à educação (CED) não foi fonte relevante de mudança em nenhum dos três países.</p>
<p><strong>O que fica como hipótese ou agenda:</strong> A existência de associação diferencial em outros países e contextos institucionais (especialmente fora da Europa Ocidental) é pressuposta mas não demonstrada; os mecanismos causais pelos quais políticas específicas produziram equalização em alguns países (Suécia, Alemanha) e não em outros (Grã-Bretanha) são discutidos qualitativamente na conclusão, mas não testados empiricamente; a análise se restringe a homens, deixando aberta a questão de como a crescente participação feminina no mercado de trabalho interage com os mecanismos identificados.</p>
<p><strong>Contribuição para o debate:</strong> O artigo reposiciona a expansão educacional como variável independente relevante para a fluidez social — não apenas como pano de fundo sobre o qual a equalização opera —, oferece uma formalização log-linear que permite decomposição sistemática de efeitos e produz uma ferramenta metodológica transferível para outros contextos. Para pesquisas sobre expansão educacional no Sul Global, o argumento é diretamente relevante: mesmo na ausência de equalização verificada, a expansão pode promover fluidez social, desde que a condição de associação diferencial se verifique nos mercados de trabalho locais.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>