<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-05">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Higher Education, Pública e Privada – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9c28ad92f8939dd35fc671874dd1efeb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/tts-reader-2.3.0/tts-reader.js" defer="true"></script>
<link href="../site_libs/quarto-contrib/tts-reader-2.3.0/tts-reader.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Higher Education, Pública e Privada – Annotated Bibliography">
<meta property="og:description" content="Eunice R. Durham (2005)">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introdução-pp.-14" id="toc-introdução-pp.-14" class="nav-link active" data-scroll-target="#introdução-pp.-14"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–4)</a>
  <ul class="collapse">
  <li><a href="#caráter-tardio-e-emergência-precoce-do-privado-empresarial-14" id="toc-caráter-tardio-e-emergência-precoce-do-privado-empresarial-14" class="nav-link" data-scroll-target="#caráter-tardio-e-emergência-precoce-do-privado-empresarial-14"><span class="header-section-number">1.1</span> Caráter tardio e emergência precoce do privado empresarial [§1–§4]</a></li>
  <li><a href="#justificativa-da-abordagem-histórica-e-periodização-56" id="toc-justificativa-da-abordagem-histórica-e-periodização-56" class="nav-link" data-scroll-target="#justificativa-da-abordagem-histórica-e-periodização-56"><span class="header-section-number">1.2</span> Justificativa da abordagem histórica e periodização [§5–§6]</a></li>
  </ul></li>
  <li><a href="#os-primórdios-pp.-39" id="toc-os-primórdios-pp.-39" class="nav-link" data-scroll-target="#os-primórdios-pp.-39"><span class="header-section-number">2</span> Os primórdios (pp.&nbsp;3–9)</a>
  <ul class="collapse">
  <li><a href="#colônia-e-império-escolas-superiores-sem-universidades-710" id="toc-colônia-e-império-escolas-superiores-sem-universidades-710" class="nav-link" data-scroll-target="#colônia-e-império-escolas-superiores-sem-universidades-710"><span class="header-section-number">2.1</span> Colônia e Império: escolas superiores sem universidades [§7–§10]</a></li>
  <li><a href="#modernização-dos-anos-1920-e-a-criação-das-primeiras-universidades-1117" id="toc-modernização-dos-anos-1920-e-a-criação-das-primeiras-universidades-1117" class="nav-link" data-scroll-target="#modernização-dos-anos-1920-e-a-criação-das-primeiras-universidades-1117"><span class="header-section-number">2.2</span> Modernização dos anos 1920 e a criação das primeiras universidades [§11–§17]</a></li>
  </ul></li>
  <li><a href="#a-segunda-república-pp.-914" id="toc-a-segunda-república-pp.-914" class="nav-link" data-scroll-target="#a-segunda-república-pp.-914"><span class="header-section-number">3</span> A Segunda República (pp.&nbsp;9–14)</a>
  <ul class="collapse">
  <li><a href="#estabilidade-e-pressão-por-reformas-1822" id="toc-estabilidade-e-pressão-por-reformas-1822" class="nav-link" data-scroll-target="#estabilidade-e-pressão-por-reformas-1822"><span class="header-section-number">3.1</span> Estabilidade e pressão por reformas [§18–§22]</a></li>
  <li><a href="#o-movimento-estudantil-organização-ideologia-e-o-embate-da-ldb-2327" id="toc-o-movimento-estudantil-organização-ideologia-e-o-embate-da-ldb-2327" class="nav-link" data-scroll-target="#o-movimento-estudantil-organização-ideologia-e-o-embate-da-ldb-2327"><span class="header-section-number">3.2</span> O movimento estudantil: organização, ideologia e o embate da LDB [§23–§27]</a></li>
  </ul></li>
  <li><a href="#o-regime-militar-e-a-reforma-19641980-pp.-1421" id="toc-o-regime-militar-e-a-reforma-19641980-pp.-1421" class="nav-link" data-scroll-target="#o-regime-militar-e-a-reforma-19641980-pp.-1421"><span class="header-section-number">4</span> O regime militar e a reforma (1964–1980) (pp.&nbsp;14–21)</a>
  <ul class="collapse">
  <li><a href="#repressão-resistência-estudantil-e-a-mística-do-modelo-universitário-único-2830" id="toc-repressão-resistência-estudantil-e-a-mística-do-modelo-universitário-único-2830" class="nav-link" data-scroll-target="#repressão-resistência-estudantil-e-a-mística-do-modelo-universitário-único-2830"><span class="header-section-number">4.1</span> Repressão, resistência estudantil e a mística do modelo universitário único [§28–§30]</a></li>
  <li><a href="#a-reforma-universitária-de-1968-e-suas-contradições-3134" id="toc-a-reforma-universitária-de-1968-e-suas-contradições-3134" class="nav-link" data-scroll-target="#a-reforma-universitária-de-1968-e-suas-contradições-3134"><span class="header-section-number">4.2</span> A reforma universitária de 1968 e suas contradições [§31–§34]</a></li>
  <li><a href="#milagre-econômico-expansão-divergente-e-a-emergência-do-mass-private-sector-3544" id="toc-milagre-econômico-expansão-divergente-e-a-emergência-do-mass-private-sector-3544" class="nav-link" data-scroll-target="#milagre-econômico-expansão-divergente-e-a-emergência-do-mass-private-sector-3544"><span class="header-section-number">4.3</span> Milagre econômico, expansão divergente e a emergência do <em>mass private sector</em> [§35–§44]</a></li>
  </ul></li>
  <li><a href="#a-década-de-1980-pp.-2133" id="toc-a-década-de-1980-pp.-2133" class="nav-link" data-scroll-target="#a-década-de-1980-pp.-2133"><span class="header-section-number">5</span> A década de 1980 (pp.&nbsp;21‑33)</a>
  <ul class="collapse">
  <li><a href="#crise-econômica-estagnação-das-matrículas-e-gargalos-estruturais-4550" id="toc-crise-econômica-estagnação-das-matrículas-e-gargalos-estruturais-4550" class="nav-link" data-scroll-target="#crise-econômica-estagnação-das-matrículas-e-gargalos-estruturais-4550"><span class="header-section-number">5.1</span> Crise econômica, estagnação das matrículas e gargalos estruturais [§45–§50]</a></li>
  <li><a href="#fusões-federações-e-a-busca-por-autonomia-via-status-de-universidade-5154" id="toc-fusões-federações-e-a-busca-por-autonomia-via-status-de-universidade-5154" class="nav-link" data-scroll-target="#fusões-federações-e-a-busca-por-autonomia-via-status-de-universidade-5154"><span class="header-section-number">5.2</span> Fusões, federações e a busca por autonomia via <em>status</em> de universidade [§51–§54]</a></li>
  <li><a href="#o-movimento-docente-andes-corporativismo-igualitarismo-e-a-ilhas-de-competência-5570" id="toc-o-movimento-docente-andes-corporativismo-igualitarismo-e-a-ilhas-de-competência-5570" class="nav-link" data-scroll-target="#o-movimento-docente-andes-corporativismo-igualitarismo-e-a-ilhas-de-competência-5570"><span class="header-section-number">5.3</span> O movimento docente (Andes): corporativismo, igualitarismo e a “ilhas de competência” [§55–§70]</a></li>
  </ul></li>
  <li><a href="#o-período-recente-19952000-pp.-3341" id="toc-o-período-recente-19952000-pp.-3341" class="nav-link" data-scroll-target="#o-período-recente-19952000-pp.-3341"><span class="header-section-number">6</span> O período recente, 1995‑2000 (pp.&nbsp;33‑41)</a>
  <ul class="collapse">
  <li><a href="#a-ldb-de-1996-e-os-novos-instrumentos-de-controle-da-qualidade-7178" id="toc-a-ldb-de-1996-e-os-novos-instrumentos-de-controle-da-qualidade-7178" class="nav-link" data-scroll-target="#a-ldb-de-1996-e-os-novos-instrumentos-de-controle-da-qualidade-7178"><span class="header-section-number">6.1</span> A LDB de 1996 e os novos instrumentos de controle da qualidade [§71–§78]</a></li>
  <li><a href="#reações-do-setor-privado-subterfúgios-mass-private-sector-e-ausência-de-liberdade-acadêmica-7984" id="toc-reações-do-setor-privado-subterfúgios-mass-private-sector-e-ausência-de-liberdade-acadêmica-7984" class="nav-link" data-scroll-target="#reações-do-setor-privado-subterfúgios-mass-private-sector-e-ausência-de-liberdade-acadêmica-7984"><span class="header-section-number">6.2</span> Reações do setor privado: subterfúgios, <em>mass private sector</em> e ausência de liberdade acadêmica [§79–§84]</a></li>
  <li><a href="#omissões-da-política-educacional-do-período-e-a-falta-de-reforma-estrutural-no-setor-público-8589" id="toc-omissões-da-política-educacional-do-período-e-a-falta-de-reforma-estrutural-no-setor-público-8589" class="nav-link" data-scroll-target="#omissões-da-política-educacional-do-período-e-a-falta-de-reforma-estrutural-no-setor-público-8589"><span class="header-section-number">6.3</span> Omissões da política educacional do período e a falta de reforma estrutural no setor público [§85–§89]</a></li>
  </ul></li>
  <li><a href="#perspectivas-pp.-4142" id="toc-perspectivas-pp.-4142" class="nav-link" data-scroll-target="#perspectivas-pp.-4142"><span class="header-section-number">7</span> Perspectivas (pp.&nbsp;41‑42)</a>
  <ul class="collapse">
  <li><a href="#incerteza-e-risco-de-desmonte-sob-o-novo-governo-lula-9093" id="toc-incerteza-e-risco-de-desmonte-sob-o-novo-governo-lula-9093" class="nav-link" data-scroll-target="#incerteza-e-risco-de-desmonte-sob-o-novo-governo-lula-9093"><span class="header-section-number">7.1</span> Incerteza e risco de desmonte sob o novo governo Lula [§90–§93]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">8</span> Argumento Sintético</a></li>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Higher Education, Pública e Privada</h1>
<p class="subtitle lead">Eunice R. Durham (2005)</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Higher Education</div>
    <div class="quarto-category">Private Education</div>
    <div class="quarto-category">Historical Institutionalism</div>
    <div class="quarto-category">Education Policy/Politics</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<!-- Bloco inicial obrigatório -->
<p>Durham, E. R. (2005). Educação Superior, Pública e Privada. In S. Schwartzman (Org.), <em>Os Desafios da Educação no Brasil</em> (pp.&nbsp;191–234). Editora Nova Fronteira.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Entrada BibTeX → Durham2005
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@incollection</span>{<span class="ot">Durham2005</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>    = {Durham, Eunice R.},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>     = {Educação Superior, Pública e Privada},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">booktitle</span> = {Os Desafios da Educação no Brasil},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">editor</span>    = {Schwartzman, Simon},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>      = {2005},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">publisher</span> = {Nova Fronteira},</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">address</span>   = {Rio de Janeiro},</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span>     = {191--233},</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>Última atualização: 2026-05-05 Modelo: DeepSeek Chat Prompt Version: v13.0 2026-04-19 | 2026-04-24 “IA Blog Post QMD” Gerado em: 2026-05-05T12:00:00-03:00</p>
<section id="introdução-pp.-14" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-14"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–4)</h2>
<section id="caráter-tardio-e-emergência-precoce-do-privado-empresarial-14" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="caráter-tardio-e-emergência-precoce-do-privado-empresarial-14"><span class="header-section-number">1.1</span> Caráter tardio e emergência precoce do privado empresarial [§1–§4]</h3>
<p>O desenvolvimento do ensino superior brasileiro é marcado por duas características: seu caráter tardio, com as primeiras instituições criadas apenas em 1808 e as universidades nos anos 1930, e, de modo especial, o surgimento precoce de um poderoso sistema de ensino privado paralelo ao público. A partir dos anos 1960, esse setor privado adquiriu novas feições, deixando de ser uma simples coexistência de sistemas análogos e passando a subverter a concepção dominante de ensino superior centrada na indissociabilidade entre ensino e pesquisa, na liberdade acadêmica e no interesse público. O crescimento desse novo tipo de ensino privado, fenômeno recente que afeta sobretudo os países em desenvolvimento, só nos últimos anos começou a despertar interesse sistemático entre os pesquisadores, até então concentrados em países onde o fenômeno não se manifestara.</p>
<p>A especificidade do caso brasileiro — onde a tendência se manifestou muito precocemente — torna-se evidente na comparação com os demais países latino-americanos e europeus. Nesses, até o final dos anos 1980, o ensino superior se concentrava em universidades públicas estatais laicas e católicas, com raras instituições privadas de pequeno porte. No Brasil, não foi assim: as universidades representavam uma parte pequena do sistema até os anos 1980 e, além das instituições confessionais e escolas sem fins lucrativos, proliferou já a partir dos anos 1960 um estabelecimento de tipo distinto: não-confessional, não-universitário e organizado como empresa explícita ou disfarçadamente voltada à obtenção de lucro — um negócio. Desde então, o caráter preocupante da expansão desse estabelecimento privado dominou o debate, e a literatura brasileira sobre ensino superior consistiu, em grande parte, no combate de intelectuais e estudantes ao ensino privado e na defesa da universidade pública.</p>
</section>
<section id="justificativa-da-abordagem-histórica-e-periodização-56" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="justificativa-da-abordagem-histórica-e-periodização-56"><span class="header-section-number">1.2</span> Justificativa da abordagem histórica e periodização [§5–§6]</h3>
<p>A análise desse problema é crucial para entender a peculiaridade do ensino superior brasileiro, exigindo uma introdução histórica que ilumine seu processo de constituição, complexidade e heterogeneidade. A autora distingue períodos que acompanham as transformações políticas do país: o período monárquico (1808–1889), caracterizado pela implantação de escolas autônomas para formação de profissionais liberais por iniciativa da Coroa; a Primeira República (1889–1930), com descentralização e surgimento de escolas públicas estaduais/municipais e privadas, mas ainda sem universidades; a implantação do governo Vargas (1930–1945), marco da criação das primeiras universidades; o período democrático de 1945 a 1964, com ampliação das universidades públicas; o período autoritário de 1964 a 1985, quando o modelo universitário foi reformado e o sistema privado se expandiu aceleradamente na direção do <em>mass private sector</em> (Geiger, 1986); e o período mais recente, iniciado em 1985 com a redemocratização, marcado pela Constituição de 1988, pela LDB de 1996 e por profundas transformações, com o intervalo 1995–2002 sob Fernando Henrique Cardoso e incerteza quanto aos rumos a partir de 2003.</p>
</section>
</section>
<section id="os-primórdios-pp.-39" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="os-primórdios-pp.-39"><span class="header-section-number">2</span> Os primórdios (pp.&nbsp;3–9)</h2>
<section id="colônia-e-império-escolas-superiores-sem-universidades-710" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="colônia-e-império-escolas-superiores-sem-universidades-710"><span class="header-section-number">2.1</span> Colônia e Império: escolas superiores sem universidades [§7–§10]</h3>
<p>Diferentemente da América Hispânica, onde universidades católicas foram criadas já no século XVI, o Brasil colonial não teve universidades nem outras instituições de ensino superior. A Coroa portuguesa impedia a formação de quadros intelectuais na colônia, concentrando a formação de nível superior na metrópole. Até a iniciativa jesuíta de criar um seminário para o clero brasileiro foi destruída com a expulsão da Companhia de Jesus pelo marquês de Pombal no final do século XVIII. A história do ensino superior brasileiro só começou em 1808, quando a corte portuguesa, fugindo da invasão napoleônica, se transferiu para o Brasil. Nesse mesmo ano, foram fundadas a Escola de Cirurgia e Anatomia da Bahia, a de Anatomia e Cirurgia do Rio de Janeiro e a Academia de Guarda da Marinha; em 1810, a Academia Real Militar (futura Escola Politécnica) e, em 1827, as faculdades de direito de São Paulo e Olinda.</p>
<p>Não houve, então, preocupação em criar uma universidade; o objetivo era formar profissionais liberais para o aparelho de Estado e a elite local — advogados, engenheiros, médicos —, sem entregar o ensino superior à Igreja Católica, ao contrário do que ocorrera nas colônias espanholas. Enquanto nos demais países latino-americanos, no início do século XIX, se buscava substituir as antigas universidades católicas ou criar um sistema universitário estatal e laico sob os novos regimes republicanos, o Brasil, com a preservação da monarquia da dinastia de Bragança, seguiu rumo diverso. Na área educacional, consolidou-se um modelo de inspiração napoleônica: escolas autônomas de formação profissional, criadas exclusivamente pela Coroa, sem a gestão da Igreja mas sob sua influência — modelo que se assentava no pragmatismo que orientara a reforma da Universidade de Coimbra.</p>
</section>
<section id="modernização-dos-anos-1920-e-a-criação-das-primeiras-universidades-1117" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="modernização-dos-anos-1920-e-a-criação-das-primeiras-universidades-1117"><span class="header-section-number">2.2</span> Modernização dos anos 1920 e a criação das primeiras universidades [§11–§17]</h3>
<p>A década de 1920 presenciou um movimento de modernização econômica, urbana e cultural que também atingiu a educação. Educadores e cientistas propuseram a criação de universidades que não fossem meras instituições de ensino, mas “centros de saber desinteressado”, capazes de desenvolver as ciências básicas e a pesquisa, além da formação profissional. Concebia-se um sistema público, não-confessional, inspirado no modelo italiano mas com inovações norte-americanas.</p>
<p>Essa bandeira foi apropriada e reformulada pelo governo Vargas, instalado em 1930, que promoveu uma reforma marcada por intensa disputa entre elites católicas conservadoras e intelectuais liberais (Schwartzman, Boneny &amp; Costa, 2000). A Igreja reivindicava a organização da primeira universidade brasileira com fundos públicos e obteve concessões como o ensino religioso facultativo nas escolas, mas não logrou o direcionamento do financiamento público para instituições confessionais. A oposição liberal impediu esse desfecho.</p>
<p>O caráter conservador da reforma ficou evidente na organização das novas universidades: meras confederações de escolas pré-existentes que preservaram grande autonomia, com cursos rigidamente separados por carreira e faculdades que decidiam o ingresso. Os diplomas tinham o mesmo valor dentro ou fora da universidade, e não havia um nível de formação geral pré-profissional à semelhança do modelo anglo-saxônico. A estrutura baseava-se na figura do catedrático vitalício, cuja congregação detinha o poder acadêmico inclusive para nomear e demitir assistentes.</p>
<p>A inovação mais promissora foi a Faculdade de Filosofia, Ciências e Letras, pensada como o <em>college</em> norte-americano de formação básica anterior à profissionalização. No entanto, ao incorporar a formação de professores, ela se converteu em mais uma escola profissional, sem conseguir desempenhar o papel de centro da universidade. Ainda assim, foi nessa faculdade que a pesquisa básica se institucionalizou em algumas poucas universidades; a maioria permaneceu apenas como instituição de ensino.</p>
<p>As três primeiras universidades representaram os conflitos da reforma. A Universidade Nacional do Rio de Janeiro (federal) encarnou o conservadorismo do regime Vargas. A Universidade do Distrito Federal, criada por Anísio Teixeira, foi um modelo inovador, mas fechada em 1935 sob acusação de liberalismo anticlerical. Já a Universidade de São Paulo, iniciativa do governo estadual oposicionista, conseguiu manter um caráter mais inovador, com uma Faculdade de Filosofia que contou com professores europeus e onde a pesquisa se institucionalizou precocemente como função básica.</p>
<p>Apesar dessas inovações, o sistema cresceu lentamente: em 1945, contava com cerca de 42 mil alunos (48% no setor privado) e apenas três universidades públicas (Tabela 1).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tabela 1 – Evolução das matrículas em estabelecimentos públicos e privados, 1933–2001</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Ano</th>
<th>Público (N)</th>
<th>Público (%)</th>
<th>Privado (N)</th>
<th>Privado (%)</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1933</td>
<td>18.986</td>
<td>56,3</td>
<td>14.737</td>
<td>43,7</td>
<td>33.723</td>
</tr>
<tr class="even">
<td>1945</td>
<td>21.307</td>
<td>52,0</td>
<td>19.968</td>
<td>48,0</td>
<td>40.975</td>
</tr>
<tr class="odd">
<td>1960</td>
<td>59.624</td>
<td>56,0</td>
<td>42.067</td>
<td>44,0</td>
<td>95.691</td>
</tr>
<tr class="even">
<td>1965</td>
<td>182.696</td>
<td>56,2</td>
<td>142.386</td>
<td>43,8</td>
<td>352.096</td>
</tr>
<tr class="odd">
<td>1970</td>
<td>210.613</td>
<td>49,5</td>
<td>214.865</td>
<td>50,5</td>
<td>425.478</td>
</tr>
<tr class="even">
<td>1980</td>
<td>492.232</td>
<td>35,7</td>
<td>885.054</td>
<td>64,3</td>
<td>1.377.286</td>
</tr>
<tr class="odd">
<td>1990</td>
<td>578.625</td>
<td>37,6</td>
<td>961.455</td>
<td>62,4</td>
<td>1.540.080</td>
</tr>
<tr class="even">
<td>1995</td>
<td>700.540</td>
<td>39,8</td>
<td>1.059.163</td>
<td>60,2</td>
<td>1.759.703</td>
</tr>
<tr class="odd">
<td>2000</td>
<td>887.026</td>
<td>32,9</td>
<td>1.807.219</td>
<td>67,1</td>
<td>2.694.245</td>
</tr>
<tr class="even">
<td>2001</td>
<td>939.225</td>
<td>31,0</td>
<td>2.091.529</td>
<td>69,0</td>
<td>3.039.754</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="a-segunda-república-pp.-914" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="a-segunda-república-pp.-914"><span class="header-section-number">3</span> A Segunda República (pp.&nbsp;9–14)</h2>
<section id="estabilidade-e-pressão-por-reformas-1822" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="estabilidade-e-pressão-por-reformas-1822"><span class="header-section-number">3.1</span> Estabilidade e pressão por reformas [§18–§22]</h3>
<p>Entre 1945 e 1964, o ensino superior continuou se expandindo lentamente, e a participação relativa do setor privado manteve-se entre 45% e 47%. Entretanto, essa aparente estabilidade ocultava que o crescimento foi insuficiente para absorver a explosiva demanda que se manifestou no final do período, alimentando pressões por reformas.</p>
<p>As universidades públicas gratuitas foram o alvo preferido da reivindicação de ampliação de vagas. O acúmulo de candidatos excedentes aprovados no vestibular, mas sem vaga, tornou-se bandeira do movimento estudantil, e a pressão começou a surtir efeito no início dos anos 1960 com a aceleração das matrículas.</p>
<p>Se o período 1931–1945 fora marcado pela luta entre elites católicas e laicas, a partir dos anos 1950 o ator principal passou a ser o movimento estudantil, cuja mobilização pela democratização do acesso e da gestão universitária ecoava um fenômeno mundial de contestação aos governos estabelecidos.</p>
<p>No Brasil, os conflitos extrapolaram as questões universitárias e se inscreveram em intensos conflitos sociais, com forte presença de partidos e militâncias marxistas. A modernização capitalista agravou a situação da população rural e expôs as profundas desigualdades do país, criando um clima de agitação social generalizada. As pautas estudantis incluíram lutas contra o imperialismo, o capitalismo e o latifúndio, e a favor do nacionalismo, do desenvolvimento, da erradicação do analfabetismo e da reforma agrária; o marxismo tornou-se a ideologia dominante (Durham, 1994).</p>
</section>
<section id="o-movimento-estudantil-organização-ideologia-e-o-embate-da-ldb-2327" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="o-movimento-estudantil-organização-ideologia-e-o-embate-da-ldb-2327"><span class="header-section-number">3.2</span> O movimento estudantil: organização, ideologia e o embate da LDB [§23–§27]</h3>
<p>O movimento estudantil brasileiro foi mais precoce e combativo que os congêneres europeu e norte‑americano, apoiado pela centralização da União Nacional dos Estudantes (UNE), criada pelo próprio regime Vargas com inspiração corporativista. Apesar da origem estatal, a UNE não se domesticou: os estudantes se consideraram vanguarda política, social e cultural, porta‑vozes dos interesses populares e celeiro de lideranças políticas desde o século XIX.</p>
<p>Na segunda metade dos anos 1950, a discussão concentrou‑se na votação da primeira Lei de Diretrizes e Bases da Educação Nacional (LDB), prevista na Constituição de 1946. Os estudantes e setores liberais e de esquerda defendiam uma reforma profunda que criasse universidades públicas, gratuitas, associando ensino e pesquisa, e substituíssem todo o ensino privado por instituições públicas. Tal proposta chocava‑se frontalmente com os interesses do setor privado tradicional, que temia restrições à sua expansão. Consolidou‑se, assim, uma oposição entre público e privado que não mais envolvia a dimensão confessional, mas que atravessaria as décadas seguintes.</p>
<p>O setor privado caracterizava‑se, em geral, por um ensino tradicional e livresco, alheio a questões como qualificação docente e inovação curricular. As exceções mais importantes foram as universidades católicas do Rio de Janeiro e de São Paulo, que depois apoiaram o movimento estudantil. Nesse período, a posição da Igreja mudara sob influência do Concílio Vaticano II e da Teologia da Libertação, formando um setor católico de esquerda que via a alfabetização como instrumento de libertação e a juventude universitária católica como segmento radical do movimento, que mais tarde integraria a luta armada contra o regime militar.</p>
<p>A LDB aprovada em 1961 representou vitória dos setores privatistas e conservadores, preservando o <em>status quo</em> e concentrando‑se em mecanismos de controle da expansão e do conteúdo do ensino. O Conselho Federal de Educação (CFE), reformulado, tornou‑se o principal instrumento de controle, com poder de fixar currículos e autorizar novos cursos e instituições, rapidamente capturado pelas pressões do setor privado.</p>
<p>Derrotados, os estudantes radicalizaram e levaram a bandeira do governo democrático paritário (docentes e estudantes em igualdade) para as ruas.</p>
</section>
</section>
<section id="o-regime-militar-e-a-reforma-19641980-pp.-1421" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="o-regime-militar-e-a-reforma-19641980-pp.-1421"><span class="header-section-number">4</span> O regime militar e a reforma (1964–1980) (pp.&nbsp;14–21)</h2>
<section id="repressão-resistência-estudantil-e-a-mística-do-modelo-universitário-único-2830" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="repressão-resistência-estudantil-e-a-mística-do-modelo-universitário-único-2830"><span class="header-section-number">4.1</span> Repressão, resistência estudantil e a mística do modelo universitário único [§28–§30]</h3>
<p>O golpe de 1964 alterou inteiramente o quadro político. O movimento estudantil se reconfigurou como resistência, e a universidade pública tornou‑se seu baluarte, iniciando um enfrentamento direto com o governo. Após intervenções com o afastamento de docentes considerados marxistas, o decreto-lei de 1967 proibiu manifestações político‑partidárias e ausências coletivas, o que radicalizou ainda mais o movimento. Grandes passeatas e batalhas campais entre estudantes de universidades públicas e segmentos do setor privado que apoiavam o governo culminaram em 1968 com influência do maio francês, ocupações e instalação de comissões paritárias ilegais. A resposta foi a destruição do movimento pela repressão, prisão de lideranças e nova cassação de docentes, mantendo as universidades sob vigilância por mais de uma década.</p>
<p>A força e o martírio desse movimento geraram um ideal de universidade pública, gratuita, com ensino e pesquisa indissociáveis, governada de forma autônoma e tripartidária (professores, alunos, funcionários), com cursos de graduação plena que dão acesso a profissão regulamentada. Esse modelo, envolto no heroísmo da luta contra a ditadura, tornou‑se parâmetro indiscutível e inibiu uma análise crítica realista das transformações em curso no ensino superior.</p>
</section>
<section id="a-reforma-universitária-de-1968-e-suas-contradições-3134" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="a-reforma-universitária-de-1968-e-suas-contradições-3134"><span class="header-section-number">4.2</span> A reforma universitária de 1968 e suas contradições [§31–§34]</h3>
<p>Derrotado o movimento, o governo militar implementou uma reforma que incorporou reivindicações consensuais no meio acadêmico e técnico, influenciadas pelo modelo norte‑americano: abolição da cátedra, criação de departamentos, institutos básicos e faculdades profissionais, sistema de créditos e proposta de ciclo básico. Contudo, a lógica foi truncada porque as carreiras permaneceram estanques e o diploma continuou como condição necessária e suficiente para o exercício profissional. O ingresso continuou por carreira, o ciclo básico fracassou, os currículos seguiram rigidamente definidos pelo CFE e não houve verdadeira reforma curricular; a expansão do acesso se deu pela simples multiplicação de matrículas nos mesmos cursos tradicionais.</p>
<p>Apesar das limitações, a reforma direcionou o sistema federal para a organização em universidades e para a promoção da pesquisa, ideal modernizador desde 1930 que ainda não se institucionalizara de fato — a realidade era de “pequenos arquipélagos” de pesquisa em um mar de ensino. O estado de São Paulo constitui exceção pioneira: com universidade estadual desde 1934, implementou pesquisa, tempo integral e doutorado, e criou a Fapesp, consolidando liderança acadêmica.</p>
</section>
<section id="milagre-econômico-expansão-divergente-e-a-emergência-do-mass-private-sector-3544" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="milagre-econômico-expansão-divergente-e-a-emergência-do-mass-private-sector-3544"><span class="header-section-number">4.3</span> Milagre econômico, expansão divergente e a emergência do <em>mass private sector</em> [§35–§44]</h3>
<p><a href="Esse parágrafo retoma um programa anterior cortado pela página 17, provavelmente referente ao Programa de Tempo Integral e Dedicação Exclusiva."></a> O programa de estímulo à pesquisa, na prática, tornou‑se mera complementação salarial, mas criou condições para os novos mestres e doutores, tornando a universidade pública cada vez mais cara e restrita a uma elite estudantil da nova classe média, incapaz de atender a toda a demanda.</p>
<p>A década de 1970 foi de prosperidade econômica — o “milagre brasileiro” — que beneficiou a classe média, ampliou a demanda por ensino superior e aumentou os recursos federais. As instituições federais gozaram de prosperidade inédita, o que ajuda a entender por que, ao contrário de Argentina e Chile, no Brasil a repressão política não sustou, mas promoveu o crescimento do ensino superior: as matrículas saltaram de 95.691 (1960) para 1.345.000 (1980), com picos de crescimento em 1968, 1970 e 1971.</p>
<p>Embora a literatura da época afirmasse que o governo promovia a privatização, os números absolutos mostram expressivo aumento do setor público (de 182.700 para 492 mil, +260%), enquanto o setor privado cresceu 512% (de 142.386 para 885.054). Não houve privatização, mas uma expansão mais rápida do privado, que atingiu 50% das matrículas em 1970 e manteve participação superior a 60% a partir de então, consolidando uma mudança de patamar e trajetórias divergentes entre os dois setores.</p>
<p>O aumento da demanda está associado ao crescimento das camadas médias e às novas oportunidades de trabalho na economia moderna e na tecnoburocracia. Para atender à demanda massiva, o setor público precisaria diversificar tipos de curso e de instituição, como fizeram os <em>community colleges</em> norte‑americanos. Na ausência dessa diversificação, o setor privado absorveu a demanda concentrando‑se em cursos de baixo custo (administração, economia, formação de professores) com exigências acadêmicas reduzidas e sem compromisso com a pesquisa, atividade não lucrativa. A expansão deu‑se pela proliferação de escolas isoladas, ainda que já houvesse vinte universidades particulares em 1975 (Tabela 2).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tabela 2 – Evolução do número de instituições públicas e privadas, 1970‑2000</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 3%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th>Ano</th>
<th>Univ. Pública</th>
<th>Univ. Privada</th>
<th>Fac. Integradas Públicas</th>
<th>Fac. Integradas Privadas</th>
<th>Estab. Isolados Públicos</th>
<th>Estab. Isolados Privados</th>
<th>Centros Univ. Públicos</th>
<th>Centros Univ. Privados</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1970</td>
<td>32</td>
<td>15</td>
<td>–</td>
<td>–</td>
<td>139</td>
<td>463</td>
<td>–</td>
<td>–</td>
<td>639</td>
</tr>
<tr class="even">
<td>1975</td>
<td>37</td>
<td>20</td>
<td>–</td>
<td>–</td>
<td>178</td>
<td>625</td>
<td>–</td>
<td>–</td>
<td>860</td>
</tr>
<tr class="odd">
<td>1980</td>
<td>45</td>
<td>20</td>
<td>1</td>
<td>10</td>
<td>154</td>
<td>643</td>
<td>–</td>
<td>–</td>
<td>882</td>
</tr>
<tr class="even">
<td>1985</td>
<td>48</td>
<td>20</td>
<td>1</td>
<td>58</td>
<td>184</td>
<td>548</td>
<td>–</td>
<td>–</td>
<td>859</td>
</tr>
<tr class="odd">
<td>1990</td>
<td>55</td>
<td>49</td>
<td>–</td>
<td>74</td>
<td>167</td>
<td>582</td>
<td>–</td>
<td>–</td>
<td>918</td>
</tr>
<tr class="even">
<td>1995</td>
<td>68</td>
<td>59</td>
<td>3</td>
<td>84</td>
<td>147</td>
<td>490</td>
<td>–</td>
<td>–</td>
<td>851</td>
</tr>
<tr class="odd">
<td>2000</td>
<td>71</td>
<td>85</td>
<td>2</td>
<td>88</td>
<td>132</td>
<td>782</td>
<td>1</td>
<td>4</td>
<td>990</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As instituições privadas tornaram‑se um grande negócio. Parte surgiu da transformação de escolas médias, mas a lucratividade atraiu empresários sem compromisso prévio com a educação. Orientadas pela captação de demanda, passaram a ser governadas pelo mercado, constituindo o que Geiger (1986) denomina <em>mass private sector</em>, enquanto o setor público se orientava para uma demanda mais qualificada.</p>
<p>Esse segmento empresarial voltou‑se para a satisfação mais imediata da demanda social: a obtenção do diploma, valorizado pela tradição cartorial que associa o título ao acesso a profissões regulamentadas e nichos privilegiados no mercado de trabalho. A qualidade da formação tornou‑se secundária. Internamente, o sistema privado dividiu‑se entre um segmento comunitário ou confessional não lucrativo (semelhante ao público) e um segmento empresarial.</p>
<p>A expansão do setor privado concentrou‑se na região Sudeste, acompanhando o mercado e o desenvolvimento econômico. Nas regiões mais pobres, o ensino público permaneceu como principal provedor, com distribuição mais equitativa (Tabela 3).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tabela 3 – Matrículas por região geográfica, 1986‑2000 (%)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Região</th>
<th>1986</th>
<th>1996</th>
<th>2000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Norte</td>
<td>2,6</td>
<td>4,1</td>
<td>5,8</td>
</tr>
<tr class="even">
<td>Nordeste</td>
<td>16,7</td>
<td>15,0</td>
<td>15,3</td>
</tr>
<tr class="odd">
<td>Sudeste</td>
<td>55,6</td>
<td>55,0</td>
<td>51,9</td>
</tr>
<tr class="even">
<td>Sul</td>
<td>19,3</td>
<td>18,7</td>
<td>20,1</td>
</tr>
<tr class="odd">
<td>Centro‑Oeste</td>
<td>5,7</td>
<td>7,2</td>
<td>8,3</td>
</tr>
<tr class="even">
<td>Total</td>
<td>100,0</td>
<td>100,0</td>
<td>100,0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>No final dos anos 1970, o sistema brasileiro estava profundamente alterado: expansão das matrículas, estímulos à titulação e à pesquisa no setor público, e criação de um setor privado empresarial lucrativo, alheio à pesquisa e à qualidade, coexistindo com um setor não lucrativo que seguia o modelo público.</p>
</section>
</section>
<section id="a-década-de-1980-pp.-2133" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="a-década-de-1980-pp.-2133"><span class="header-section-number">5</span> A década de 1980 (pp.&nbsp;21‑33)</h2>
<section id="crise-econômica-estagnação-das-matrículas-e-gargalos-estruturais-4550" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="crise-econômica-estagnação-das-matrículas-e-gargalos-estruturais-4550"><span class="header-section-number">5.1</span> Crise econômica, estagnação das matrículas e gargalos estruturais [§45–§50]</h3>
<p>A década de 1980 foi marcada pela crise econômica e pela transição política da redemocratização, culminando na Constituição de 1988 e na primeira eleição direta para presidente. No ensino superior, a expansão estancou: entre 1980 e 1990, o total de alunos passou de 1,38 milhão para 1,54 milhão, alta de apenas 11,8%; entre 1975 e 1980 o crescimento fora de 28%, e de 1980 a 1985 de apenas 7,6%. A crise afetou especialmente a classe média que sustentava a demanda no privado, e a evasão cresceu.</p>
<p>Altos índices de repetência e evasão no ensino básico faziam com que poucos concluíssem o ensino médio. A relação concluintes‑do‑médio por vaga no superior era de 1,3 em 1980 e chegou a 1,5 em 2001 (Tabela 5), evidenciando obstáculos estruturais à ampliação do ensino superior, ligados às desigualdades sociais.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tabela 5 – Concluintes do ensino médio e número de vagas, 1980‑2000</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ano</th>
<th>Concluintes (mil)</th>
<th>Vagas (mil)</th>
<th>Concluintes por vaga</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1980</td>
<td>540</td>
<td>405</td>
<td>1,3</td>
</tr>
<tr class="even">
<td>1991</td>
<td>659</td>
<td>517</td>
<td>1,3</td>
</tr>
<tr class="odd">
<td>1994</td>
<td>749</td>
<td>574</td>
<td>1,3</td>
</tr>
<tr class="even">
<td>1997</td>
<td>1.266</td>
<td>699</td>
<td>1,8</td>
</tr>
<tr class="odd">
<td>2000</td>
<td>2.101</td>
<td>1.236</td>
<td>1,6</td>
</tr>
<tr class="even">
<td>2001</td>
<td>2.217</td>
<td>1.444</td>
<td>1,5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>O crescimento dos anos 1970 só foi possível graças a uma demanda reprimida de egressos mais velhos que haviam completado o ensino médio em cursos supletivos e já estavam inseridos no mercado de trabalho. A alta porcentagem de cursos noturnos corrobora essa interpretação: esses cursos permitiram o acesso de trabalhadores que buscavam ascensão ocupacional. Em 1986, 76,5% das matrículas do setor privado eram em cursos noturnos, contra apenas 16% nas federais. Nessas universidades, cujo discurso exaltava o compromisso popular, a resistência à criação de cursos noturnos foi grande, com a exceção da USP, que os introduziu já em 1952. Nas federais, a participação noturna subiu lentamente para 21,4% em 1999 (Tabela 6).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tabela 6 – Percentual de alunos de graduação em cursos noturnos por tipo de instituição, 1986‑1999</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tipo de Instituição</th>
<th>1986</th>
<th>1994</th>
<th>1999</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Federais</td>
<td>16,0</td>
<td>18,7</td>
<td>21,4</td>
</tr>
<tr class="even">
<td>Estaduais</td>
<td>42,6</td>
<td>45,8</td>
<td>46,3</td>
</tr>
<tr class="odd">
<td>Privadas</td>
<td>76,5</td>
<td>67,8</td>
<td>66,6</td>
</tr>
<tr class="even">
<td>Total</td>
<td>61,2</td>
<td>54,6</td>
<td>55,0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Esgotada a demanda reprimida e com o lento crescimento dos recém‑egressos do ensino médio, deixou de haver candidatos suficientes para preencher todas as vagas do setor privado. Somente muito recentemente o ensino médio voltou a crescer, puxado pela melhoria do fundamental, mas a relação egresso/vaga, após atingir 1,8 em 1997, caiu para 1,5 em 2001.</p>
</section>
<section id="fusões-federações-e-a-busca-por-autonomia-via-status-de-universidade-5154" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="fusões-federações-e-a-busca-por-autonomia-via-status-de-universidade-5154"><span class="header-section-number">5.2</span> Fusões, federações e a busca por autonomia via <em>status</em> de universidade [§51–§54]</h3>
<p>A escassez de candidatos acirrou a competição entre estabelecimentos privados. As universidades levavam vantagem por terem autonomia para criar e extinguir cursos e vagas, ajustando‑se rapidamente às preferências da clientela; os estabelecimentos maiores, com muitos cursos, absorviam melhor as oscilações de demanda.</p>
<p>Por isso, o setor privado se orientou para ampliar o tamanho por fusões e incorporações, formando federações de escolas e, posteriormente, buscando transformá‑las em universidades para obter autonomia e fugir dos controles do CFE. O CFE foi inundado por pedidos dessa natureza e a atividade de <em>lobbies</em> se intensificou. Enquanto o número de universidades privadas permaneceu estável em vinte entre 1975 e 1985, as faculdades integradas cresceram rapidamente: de 10 em 1980 para 58 em 1985 e 74 em 1990. As universidades privadas só se expandiram mais tarde: de 20 para 49 entre 1985 e 1990, um salto de 145%.</p>
<p>Assim, o final dos anos 1980 testemunhou uma nova inflexão: até então, as universidades privadas eram predominantemente confessionais ou comunitárias, sem fins lucrativos, com características próximas às públicas. A expansão a partir de 1985 foi puxada pelo setor de ensino de massa, com finalidades lucrativas e sem interesse em pesquisa ou qualificação docente.</p>
<p>O mecanismo de reconhecimento de universidades pelo CFE explica como isso foi possível. Apesar de a legislação exigir associação entre ensino e pesquisa, os critérios efetivamente aplicados eram apenas a amplitude dos campos de conhecimento e a infraestrutura mínima. A criação de federações de escolas tornava‑se o passo anterior ao <em>status</em> de universidade. O resultado foi que a multiplicação de universidades privadas não trouxe melhoria na qualidade de ensino, na titulação docente ou na pesquisa, e não gerou um <em>ethos</em> universitário de liberdade acadêmica e valorização da competência.</p>
</section>
<section id="o-movimento-docente-andes-corporativismo-igualitarismo-e-a-ilhas-de-competência-5570" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="o-movimento-docente-andes-corporativismo-igualitarismo-e-a-ilhas-de-competência-5570"><span class="header-section-number">5.3</span> O movimento docente (Andes): corporativismo, igualitarismo e a “ilhas de competência” [§55–§70]</h3>
<p>A emergência do movimento dos docentes das universidades públicas deu origem à Associação Nacional dos Docentes Universitários (Andes), que substituiu o movimento estudantil e incorporou muitas de suas bandeiras. Esse movimento, restrito ao setor público, organizou‑se a partir de lideranças marginalizadas pela ditadura.</p>
<p><a href="Os parágrafos seguintes retomam texto cuja continuidade foi interrompida por páginas ilegíveis."></a> Os sistemas de controle sobre as universidades incluíram repressão policial direta, cassação de lideranças de esquerda e triagem ideológica nas contratações, com agentes de inteligência infiltrados nas reitorias. Houve também intensa manipulação política para garantir a permanência de simpatizantes do regime na gestão.</p>
<p>A operação desses controles facilitou ingerências ilegítimas, afastou as lideranças intelectuais da governança, beneficiou docentes ligados ao governo ou às oligarquias locais e enfraqueceu os sistemas de mérito. A autonomia foi destruída e o clientelismo e a cooptação se fortaleceram. Docentes e estudantes refugiaram‑se numa oposição intransigente, atribuindo todos os males à ditadura e deixando de refletir criticamente sobre os problemas da universidade. Paralelamente, a resistência simbólica abraçou um igualitarismo radical que deslegitimou valores acadêmicos de mérito e competência.</p>
<p>A expansão das federais também contribuiu para essa desvalorização, pois as contratações, feitas fora dos mecanismos tradicionais de seleção, ampliaram o clientelismo e geraram uma enorme heterogeneidade salarial, causando insatisfação especialmente entre os docentes mais jovens e menos qualificados.</p>
<p>As atividades de pesquisa, desenvolvidas através das agências de fomento (Capes, CNPq, Finep, Fapesp), passaram a operar como um sistema paralelo à estrutura universitária, baseado na relação direta pesquisador‑agência e na qualidade da produção científica. Esse sistema fortaleceu os valores acadêmicos, mas dissociou‑os da gestão da universidade, criando “ilhas de competência” (Oliveira, 1984) em meio à mediocridade generalizada.</p>
<p>A política consistente da Capes e do CNPq ampliou de forma contínua a qualificação docente e a pesquisa, tendência que se acelerou ao longo da década (Tabela 7).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tabela 7 – Evolução da pós‑graduação: número de cursos e alunos, 1987‑1996</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 4%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Ano</th>
<th>Mestrado (cursos)</th>
<th>Doutorado (cursos)</th>
<th>Alunos novos Mestr.</th>
<th>Alunos novos Dout.</th>
<th>Matriculados Mestr.</th>
<th>Matriculados Dout.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1987</td>
<td>861</td>
<td>395</td>
<td>9.853</td>
<td>1.976</td>
<td>30.337</td>
<td>8.309</td>
</tr>
<tr class="even">
<td>1990</td>
<td>964</td>
<td>450</td>
<td>12.162</td>
<td>3.080</td>
<td>36.502</td>
<td>10.923</td>
</tr>
<tr class="odd">
<td>1993</td>
<td>1.039</td>
<td>524</td>
<td>12.816</td>
<td>4.191</td>
<td>38.265</td>
<td>15.569</td>
</tr>
<tr class="even">
<td>1996</td>
<td>1.176</td>
<td>626</td>
<td>16.255</td>
<td>5.102</td>
<td>44.925</td>
<td>22.004</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A organização dos docentes deu‑se a partir das lideranças marginalizadas, denunciando os instrumentos políticos que perpetuavam na cúpula uma minoria incompetente aliada ao regime. Suas grandes bandeiras foram a autonomia e a democratização, entendida como ampliação da participação de docentes e estudantes na gestão por mecanismos representativos.</p>
<p>A redução dos recursos públicos e o achatamento salarial levaram o movimento a incorporar uma vertente sindicalista, que o fortaleceu mas alterou sua composição, reforçando a aliança com funcionários. A vertente acadêmica foi marginalizada; as preocupações com competência docente e pesquisa serviam mais para legitimar reivindicações salariais do que para mobilizar em defesa de valores acadêmicos. Quanto mais sindicalista o movimento, maior a incorporação dos docentes menos qualificados e maior o igualitarismo, com baixa aceitação de critérios de qualificação profissional para cargos de direção.</p>
<p>A hegemonia das universidades federais nesse movimento decorre de elas formarem um bloco numeroso e unificado, com o MEC como interlocutor comum. Os problemas e reivindicações que pautam o movimento são específicos da rede federal. Nessas universidades, a escolha de dirigentes sempre esteve subordinada ao MEC e sujeita às oligarquias locais, para as quais a universidade era fonte de recursos e patronagem — em Alagoas, o orçamento da federal superava o do estado. A luta pela eleição direta dos dirigentes ganhou força como única forma de romper essa dominação e estabelecer um mínimo de autonomia. A aliança com funcionários e alunos tornou‑se crucial, e a fórmula da eleição direta tripartidária erigiu‑se a princípio indiscutível. Quanto mais autoritário fora o reitor anterior, mais exacerbada a luta por eleições tripartidas. Como os mecanismos anteriores de escolha jamais privilegiaram critérios acadêmicos, o movimento docente pôde abandonar esses valores em favor de um igualitarismo radical com amplo respaldo entre alunos e funcionários.</p>
<p><a href="Fragmento final de parágrafo não recuperado."></a> A situação se tornara a mais adequada aos interesses corporativos do conjunto de docentes e funcionários.</p>
<p>No final do período, começou a surgir um novo grupo contestador das posições da Andes: pesquisadores universitários, técnicos qualificados do MEC e reitores das estaduais paulistas, todos familiarizados com as reformas em curso na Europa e nos Estados Unidos e com a mudança do papel do Estado de executor para regulador e avaliador.</p>
<p>Os temas introduzidos por esse grupo foram autonomia e avaliação, reinterpretando a autonomia como descentralização da responsabilidade administrativa necessariamente associada ao controle público por avaliação, com recursos atrelados a critérios de desempenho em ensino e pesquisa. A primeira tentativa de implementar essas ideias ocorreu em 1985, com uma comissão de alto nível proposta por Tancredo Neves e encampada por Sarney, que levou à criação do Grupo Executivo para Reformulação da Educação Superior (Geres). Diante da reação do movimento docente, o ministro Maciel arquivou a proposta. Em 1991, o ministro José Goldemberg, ex‑reitor da USP, retomou a avaliação e criou um sistema de grande potencial para controle da qualidade, embora as propostas da Secretaria de Políticas Educacionais de criar um ensino público de massa não tenham avançado.</p>
<p>No início dos anos 1990, o aumento do percentual de docentes com mestrado ou doutorado, fruto das políticas da Capes e CNPq, já era a tendência mais importante.</p>
</section>
</section>
<section id="o-período-recente-19952000-pp.-3341" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="o-período-recente-19952000-pp.-3341"><span class="header-section-number">6</span> O período recente, 1995‑2000 (pp.&nbsp;33‑41)</h2>
<section id="a-ldb-de-1996-e-os-novos-instrumentos-de-controle-da-qualidade-7178" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="a-ldb-de-1996-e-os-novos-instrumentos-de-controle-da-qualidade-7178"><span class="header-section-number">6.1</span> A LDB de 1996 e os novos instrumentos de controle da qualidade [§71–§78]</h3>
<p>A nova LDB, votada em 1996, incorporou a exigência de associação entre ensino e pesquisa com produção científica comprovada para credenciamento e recredenciamento das universidades — exigência que, embora já constasse na legislação anterior, nunca tivera mecanismo efetivo de implementação, especialmente no setor privado. A lei também estabeleceu condições mínimas: um terço do corpo docente com mestrado ou doutorado e um terço em tempo integral, dispositivos que enfrentaram forte oposição do <em>lobby</em> privatista, mas que estabeleceram critérios objetivos alterando substantivamente o processo de criação de universidades.</p>
<p>O recredenciamento periódico das instituições, precedido de avaliação, permitiu corrigir distorções e ameaçar a situação das universidades que não passavam de grandes unidades de ensino, dando‑lhes oito anos para se adequarem. A renovação periódica do reconhecimento de cursos, associada à exigência de que os diplomas fossem legalizados, possibilitou pressão continuada pela manutenção de qualidade mínima.</p>
<p>A lei também flexibilizou o sistema: aboliu o “currículo mínimo” que engessava o ensino, substituindo‑o por diretrizes curriculares gerais, e previu cursos sequenciais de curta duração.</p>
<p>As universidades públicas federais e estaduais, que já vinham desenvolvendo pesquisa e aumentando a titulação, foram pouco afetadas. Para as privadas, porém, a lei representava ameaça de perda de <em>status</em> e autonomia.</p>
<p>A eficácia da nova legislação dependia da construção de um sistema de avaliação, principal preocupação do ministério. A iniciativa mais marcante foi o Exame Nacional de Cursos, o “Provão”, teste objetivo aplicado a todos os formandos, obrigatório para a obtenção do diploma mas sem reprovação individual, destinado a classificar comparativamente os cursos pela média de desempenho.</p>
<p>O Provão enfrentou resistência das mantenedoras privadas e, surpreendentemente, também de alunos e docentes do setor público, liderados pelo sindicato docente. Embora o exame logo demonstrasse a melhor qualidade dos cursos públicos, o corporativismo do setor público enxergava qualquer avaliação comparativa como ameaça à isonomia, à distribuição igualitária de benefícios e à unidade monolítica do sindicato. Apenas a autoavaliação, sem comparações nem consequências distributivas, era aceita. A implantação do Provão contou com forte apoio da imprensa e da sociedade; a publicação dos resultados gerou enorme interesse público, legitimou o exame e o tornou o mais poderoso instrumento de incentivo à melhoria da qualidade, inclusive influenciando o mercado: os cursos privados melhor classificados usaram o resultado como propaganda para atrair alunos.</p>
<p>Em 2001, o Provão já avaliava vinte cursos, abrangendo 1.293.170 alunos, maioria dos formandos. Paralelamente, criou‑se uma avaliação qualitativa por comissões de pares (Comissões de Avaliação das Condições de Oferta de Ensino) para complementar e corrigir a avaliação do Provão.</p>
</section>
<section id="reações-do-setor-privado-subterfúgios-mass-private-sector-e-ausência-de-liberdade-acadêmica-7984" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="reações-do-setor-privado-subterfúgios-mass-private-sector-e-ausência-de-liberdade-acadêmica-7984"><span class="header-section-number">6.2</span> Reações do setor privado: subterfúgios, <em>mass private sector</em> e ausência de liberdade acadêmica [§79–§84]</h3>
<p><a href="Parágrafo interrompido por páginas ilegíveis; o texto retoma a questão do privilégio da aposentadoria integral."></a> O privilégio corporativo da aposentadoria integral com vencimentos de ativo transformou‑se em subsídio público para o setor privado, que se viu poupado do ônus de qualificar seu próprio pessoal.</p>
<p>É verdade que o setor privado fez algum esforço de qualificação, pois a titulação docente tornou‑se critério importante nas avaliações. As instituições privadas pressionaram pela aprovação de cursos de pós‑graduação próprios. Houve avanços na titulação, mas, sem tradição de pesquisa e sem compreensão de seu significado, tiveram dificuldades para reconhecer os cursos e mobilizaram‑se para reduzir as exigências da Capes. Enquanto isso, expandiram os cursos de especialização, sobre os quais há pouco controle de qualidade.</p>
<p>Outros subterfúgios incluíram a criação de revistas próprias não indexadas e, principalmente, a abertura para o mercado global de educação superior: convênios com universidades estrangeiras para cursos a distância ou semipresenciais, com diplomas expedidos no exterior e livres dos controles da Capes.</p>
<p>Houve, também, iniciativas mais sérias. Algumas instituições, inclusive empresas de ensino, montaram pequenos grupos de pesquisa com pesquisadores aposentados do setor público, capazes de obter financiamento de agências. Todavia, são pequenos enclaves em instituições de massa, sem capacidade de influir na graduação, e sua manutenção depende das estratégias financeiras dos mantenedores.</p>
<p>Por trás de todas essas iniciativas persiste o problema básico das instituições lucrativas: a completa ausência de liberdade acadêmica e a apropriação da autonomia universitária por mantenedoras ou proprietários. Os docentes são “proletários do ensino”, submetidos às determinações e caprichos dos proprietários. O corpo dirigente costuma ser indicado pelos donos, muitas vezes parentes, raramente com qualificação. Assim, as universidades privadas lucrativas constituem frequentemente uma contrafação do modelo de universidade que inspirou a legislação e os movimentos reformistas.</p>
<p>Em contraste, o segmento não lucrativo, comunitário ou confessional, tem procurado realizar o modelo de universidade que associa ensino e pesquisa, investe em projetos pedagógicos sérios e preserva algum grau de liberdade acadêmica. Esse segmento contribui de modo muito positivo para o desenvolvimento do ensino superior brasileiro.</p>
</section>
<section id="omissões-da-política-educacional-do-período-e-a-falta-de-reforma-estrutural-no-setor-público-8589" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="omissões-da-política-educacional-do-período-e-a-falta-de-reforma-estrutural-no-setor-público-8589"><span class="header-section-number">6.3</span> Omissões da política educacional do período e a falta de reforma estrutural no setor público [§85–§89]</h3>
<p>Apesar das inovações, houve omissões importantes na política recente que afetaram particularmente o sistema público, cujos problemas estruturais não foram solucionados.</p>
<p>Não houve iniciativa para atender, em instituições públicas, a demanda crescente de educação pós‑secundária de uma população com formação escolar prévia insuficiente para ter sucesso em universidades de pesquisa. Governos federal e estaduais concentraram recursos no ensino gratuito em universidades e nos estímulos à pós‑graduação, sem diversificar estabelecimentos nem programas de ensino para uma demanda heterogênea. Também não se criou, com recursos públicos, uma universidade aberta de ensino a distância de qualidade; a tarefa foi delegada a universidades presenciais sem competência ou recursos para tanto. As iniciativas públicas foram limitadas, e as particulares não alcançaram a qualidade necessária. O ensino a distância pressionou pela abertura a instituições estrangeiras interessadas na exportação de cursos, enquanto a democratização do acesso continuou dependente do ensino privado de massa, atividade lucrativa que, por seu imediatismo, não promoveu a renovação do ensino capaz de corrigir as deficiências da escolaridade anterior e oferecer formação adequada ao mercado de trabalho.</p>
<p>Tampouco se realizou uma reforma administrativa do ensino público que quebrasse o centralismo burocrático e racionalizasse o uso dos recursos. O problema central é a ausência de autonomia administrativa e financeira nas universidades públicas (com exceção das estaduais paulistas). Sem ela, é impossível alterar a gestão e vincular o financiamento a critérios de desempenho. A Constituição de 1988 assegurou a autonomia didática, científica, administrativa e financeira, mas a submissão às rígidas regras do funcionalismo público e aos controles orçamentários a tornaram letra morta. O controle de vagas e da carreira permaneceu centralizado, a folha de pagamento (cerca de 90% dos recursos) é executada diretamente pelo ministério, e a liberdade dos 10% restantes é tolhida pela separação entre custeio e capital e pelo detalhamento do Congresso. Assim, não se logrou associar o orçamento ao número de alunos, à qualificação docente ou ao desempenho estudantil. A pesquisa segue dependente do financiamento extra‑orçamentário das agências, baseado na qualidade, mas não há avaliação institucional que integre ensino e pesquisa.</p>
<p>A situação é agravada pelas vitórias constitucionais do movimento corporativo de docentes e funcionários: aposentadoria integral, estabilidade plena, irredutibilidade de vencimentos e incorporação permanente de qualquer benefício temporário. O quadro de pessoal tornou‑se extremamente rígido, impermeável à avaliação de mérito, de modo que qualquer inovação depende de recursos adicionais. Brunner (1991) analisou a impossibilidade de modernizar e racionalizar universidades públicas nesse sistema, comum à América Latina. Sem uma reforma de grande alcance, o ensino público não poderá ampliar o atendimento à população, e a oportunidade de fazê‑la sob o governo Fernando Henrique Cardoso foi perdida.</p>
</section>
</section>
<section id="perspectivas-pp.-4142" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="perspectivas-pp.-4142"><span class="header-section-number">7</span> Perspectivas (pp.&nbsp;41‑42)</h2>
<section id="incerteza-e-risco-de-desmonte-sob-o-novo-governo-lula-9093" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="incerteza-e-risco-de-desmonte-sob-o-novo-governo-lula-9093"><span class="header-section-number">7.1</span> Incerteza e risco de desmonte sob o novo governo Lula [§90–§93]</h3>
<p>Com a vitória do Partido dos Trabalhadores e a posse de Lula em 2003, assume um partido de oposição ao governo anterior, cujo <em>slogan</em> era “acabar com tudo que está aí”. Tem havido, de fato, um grande desmonte da máquina administrativa que atingiu inclusive os setores técnicos.</p>
<p>No Ministério da Educação, a transformação se dá pela substituição dos quadros anteriores por membros do Sindicato de Docentes, que sempre combateram violentamente os processos de avaliação implantados e se opuseram intransigentemente a qualquer reforma que diferenciasse instituições por mérito e desempenho ou ameaçasse a estabilidade e os benefícios corporativos. Até o momento, não há proposta consistente e integrada para o ensino superior e a avaliação; apenas iniciativas pontuais ou casuísticas.</p>
<p>A autora julga cedo para avaliar, mas vê poucas perspectivas de uma reforma mais profunda e teme que as realizações do período anterior sejam destruídas sem que se avance para a consolidação de um sistema de recredenciamento baseado em avaliações institucionais.</p>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">8</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A tese central do texto é que a peculiar trajetória do ensino superior brasileiro — marcada pelo surgimento precoce de um poderoso setor privado empresarial voltado ao lucro — resultou da incapacidade histórica do setor público de diversificar‑se para atender à demanda de massa, de arranjos políticos conservadores que capturaram os mecanismos de regulação (especialmente o Conselho Federal de Educação) e de um ciclo de retroalimentação corporativa no setor federal que inviabilizou reformas estruturais, consolidando assim um sistema dual em que o setor privado responde ao mercado enquanto o público se elitiza e se distancia da democratização do acesso. O argumento é predominantemente descritivo‑explicativo, mas carrega forte componente normativo ao defender a necessidade de autonomia administrativa com avaliação de desempenho e de diversificação institucional pública. O texto demonstra empiricamente as trajetórias divergentes dos setores público e privado e identifica o mecanismo político que permitiu a transmutação de federações de escolas em universidades empresariais sem qualidade. Fica como hipótese, contudo, se a introdução de avaliações de resultado (Provão) poderia, por si só, reconfigurar o setor privado e equilibrar o sistema, e se a reforma gerencial do público seria politicamente factível diante da força do corporativismo sindical. A principal contribuição para o debate é oferecer uma narrativa histórica minuciosa que articula dinâmica política, evolução institucional e dados quantitativos, desvelando as origens do <em>mass private sector</em> brasileiro de forma muito anterior ao reconhecimento internacional desse fenômeno.</p>
</div>
</div>
</section>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v13.0</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A pergunta central não é formulada explicitamente; pode‑se reconstruí‑la como: <em>Como e por que o Brasil desenvolveu, precocemente, um sistema de ensino superior privado de massa de caráter empresarial, e quais foram suas consequências para a configuração do sistema?</em> Trata‑se de uma pergunta explicativa, embora o texto também busque avaliar os efeitos desse desenvolvimento. A reconstrução é plausível, já que a autora insiste na especificidade do caso brasileiro e na necessidade de uma análise histórica para compreendê‑la.</td>
<td style="text-align: left;">Pergunta reconstruída: <em>Como e por que o Brasil desenvolveu, precocemente, um sistema de ensino superior privado de massa de caráter empresarial, e quais foram suas consequências para a configuração do sistema?</em> Natureza: explicativa e avaliativa.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">O texto desdobra‑se em perguntas secundárias que estruturam a narrativa: (1) Quais as fases e marcos políticos da evolução do ensino superior brasileiro? (2) Como as relações entre Estado, Igreja, elites e movimento estudantil moldaram as políticas de regulação e expansão? (3) Como o setor privado empresarial conseguiu contornar as exigências formais de associação entre ensino e pesquisa? (4) Por que o setor público não se diversificou para atender à demanda massiva? (5) Quais os efeitos do corporativismo docente sobre a modernização do sistema público? Essas perguntas são funcionalmente subordinadas à pergunta central e a operacionalizam em sequência histórica.</td>
<td style="text-align: left;">(1) Quais as fases e marcos políticos da evolução do ensino superior brasileiro? (2) Como as relações entre Estado, Igreja, elites e movimento estudantil moldaram as políticas de regulação e expansão? (3) Como o setor privado empresarial conseguiu contornar as exigências formais de associação entre ensino e pesquisa? (4) Por que o setor público não se diversificou? (5) Quais os efeitos do corporativismo docente sobre a modernização do setor público?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O <em>puzzle</em> é uma combinação de <strong>explicação de divergência institucional</strong> e <strong>avaliação de política</strong>. Por que, diferentemente da maioria dos países latino‑americanos e europeus, o Brasil desenvolveu precocemente um <em>mass private sector</em> lucrativo, e por que o setor público não conseguiu absorver a demanda? O <em>puzzle</em> é genuíno e generalizável como caso‑limite de falha de coordenação estatal e captura regulatória, ainda que a autora não use essa linguagem.</td>
<td style="text-align: left;"><em>Puzzle</em> de divergência institucional e avaliação de política. Genuíno: contrasta com o padrão regional de predominância de universidades públicas e católicas. Generalizável como estudo de caso de captura regulatória e expansão de mercado em educação superior.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese é que o caráter dual do sistema brasileiro — público elitizado e privado empresarial de massa — decorre de uma sequência de escolhas políticas (não criação de <em>community colleges</em> públicos, leniência do CFE, vitórias corporativas na Constituição de 1988) que, somadas à forte demanda por diplomas, produziram um setor privado regido pelo mercado e um setor público paralisado pela rigidez administrativa e pelo igualitarismo sindical. O <em>claim of discovery</em> é que a expansão privada não foi privatização, mas uma trajetória divergente precoce que escapou à regulação estatal. O argumento é causal‑histórico, apoiado em séries de matrículas e análises de mudanças normativas. O que efetivamente o sustenta são as evidências quantitativas da trajetória divergente e o mapeamento do papel do CFE.</td>
<td style="text-align: left;">A tese é que o sistema dual brasileiro (público elitizado, privado empresarial de massa) resulta de escolhas políticas que combinaram captura regulatória pelo privado e paralisia corporativa no público, impedindo a diversificação do setor público e favorecendo a expansão mercantil. <em>Claim of discovery</em>: a expansão privada foi muito precoce e não uma privatização, mas uma divergência fomentada pelo Estado através da leniência regulatória.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">Estudo histórico‑institucional baseado em fontes secundárias, documentos legais (Constituição, LDBs, decretos), dados censitários do MEC (Censo da Educação Superior) e referências à literatura acadêmica. A estratégia argumentativa é a narrativa processual, organizada em períodos políticos, com interpretação das estatísticas e das mudanças normativas. Não há teste formal de hipóteses; a identificação causal repousa na cronologia e na demonstração de que o CFE deliberadamente não exigia pesquisa para o reconhecimento de universidades. Limitações: ausência de contrafactual explícito e de análise de mecanismos de nível micro (escolha de estudantes, estratégias de mantenedores).</td>
<td style="text-align: left;">Estudo histórico‑institucional com análise documental e de dados censitários. Estratégia narrativa periodizada. Principais fontes: Censo do Ensino Superior, legislação, literatura acadêmica. Sem teste formal de hipóteses; a inferência causal é baseada em cronologia e análise normativa.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">Fenômeno real (matrículas, instituições) → observação via Censo MEC e legislação → coleta de dados agregados para 1933‑2001 → operacionalização em tabelas de evolução de matrículas e instituições → análise descritiva e interpretação histórica → inferência causal por meio da associação entre mudanças políticas e expansão dos setores. Unidade de análise: o sistema de ensino superior brasileiro como um todo e, em alguns momentos, as IES por dependência administrativa. Nível de agregação: majoritariamente nacional e por setor (público/privado, federal/estadual/privado, regiões). O DGP é apropriado para estabelecer correlações temporais e mudanças de composição, mas é fraco para identificar causalidade micro.</td>
<td style="text-align: left;">Fenômeno real (matrículas, IES) → Censo MEC → dados agregados → tabelas descritivas → interpretação histórica. Unidade: sistema nacional e setores. Agregação: nacional e por dependência administrativa. Força: rastreamento de tendências de longo prazo. Limitação: não permite inferência sobre decisões individuais ou mecanismos micro.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">Principais achados empíricos: (1) a participação do setor privado saltou de 44% (1960) para 69% (2001); (2) a expansão veio de escolas isoladas e, depois, de universidades criadas sem exigência de pesquisa; (3) o setor público tornou‑se mais qualificado (mestres/doutores, pós‑graduação), mas não expandiu a oferta para a demanda de massa. Contribuição teórico‑metodológica: oferece uma periodização original e uma narrativa unificada que liga a dinâmica política à evolução quantitativa. O design identifica com força a mudança de patamar e o papel do CFE; é mais especulativo ao atribuir a não diversificação do público apenas à rigidez e ao corporativismo, sem explorar contraexemplos de estados que diversificaram.</td>
<td style="text-align: left;">Achados empíricos: forte expansão do setor privado sem melhora de qualidade; setor público se elitizou sem diversificar; CFE falhou em exigir indissociabilidade ensino‑pesquisa. Contribuição: periodização original e integração de dados quantitativos com análise política. O <em>claim</em> de que a leniência do CFE explica a configuração do privado está bem documentado; já a inferência de que o corporativismo é a causa principal da rigidez do público carece de evidência contrafactual.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">A autora responde adequadamente à pergunta reconstruída, demonstrando que a divergência foi precoce e que o arcabouço normativo (CFE) a viabilizou. O ponto mais forte é a demonstração de que a exigência formal de pesquisa jamais foi implementada para o privado, minando a retórica reformista. O ponto mais vulnerável é a tese de que o corporativismo e a Constituição de 1988 impedem qualquer modernização do público: a narrativa não enfrenta casos como o das estaduais paulistas, que mantêm autonomia e avaliação, e tampouco explora mecanismos pelos quais a avaliação (Provão) poderia, gradualmente, diferenciar as federais sem reforma constitucional. As ameaças à identificação são típicas de estudos de caso único: a trajetória pode ser superdeterminada, e a seleção do caso brasileiro como outlier não é formalizada. A generalizabilidade é limitada, mas o mecanismo de captura regulatória é teoricamente relevante para além do caso.</td>
<td style="text-align: left;">Responde à pergunta; demonstra divergência e captura do CFE. Ponto forte: evidência de que a exigência de pesquisa era letra morta para o privado. Ponto vulnerável: atribuição do imobilismo público exclusivamente ao corporativismo sindical e à Constituição, sem explorar variação (ex.: estaduais paulistas). Ameaça de superdeterminação em caso único; validade externa do mecanismo de captura regulatória é plausível, mas não testada.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> A autora não formula limitações explicitamente, mas sinaliza incerteza quanto aos rumos futuros e ao risco de desmonte. <strong>Não reconhecidas ou subestimadas:</strong> A narrativa trata o setor público como um bloco monolítico, subestimando a heterogeneidade entre federais e estaduais paulistas; não discute a possível melhora de qualidade induzida pelo Provão no setor privado de massa; não analisa os efeitos distributivos do sistema dual (quem se beneficia do ensino gratuito de elite); e não considera que a rigidez administrativa possa ser, em parte, uma proteção contra o clientelismo local.</td>
<td style="text-align: left;"><strong>Reconhecidas:</strong> Incerteza sobre o futuro e risco de desmonte. <strong>Não reconhecidas:</strong> Heterogeneidade interna do setor público; efeitos dinâmicos da avaliação (Provão) sobre o privado; distribuição de benefícios do sistema dual; e possível trade‑off entre rigidez e proteção contra clientelismo.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">O texto insere‑se na tradição da sociologia histórica e da análise institucional, com forte influência da literatura comparada sobre sistemas de ensino superior (Geiger) e da análise de políticas públicas. A moldura teórica é mais implícita que explícita: a autora opera com os conceitos de <em>mass private sector</em>, captura regulatória e dependência de trajetória, sem adotar um protocolo rígido. A ontologia implícita é de atores coletivos (Igreja, movimento estudantil, sindicato, empresários) que disputam o desenho institucional; o método narrativo é coerente com essa ontologia.</td>
<td style="text-align: left;">Tradição: sociologia histórica e análise institucional comparada, com conceitos de <em>mass private sector</em> (Geiger) e dependência de trajetória. Moldura implícita baseada em atores coletivos e disputa institucional. Coerência com método narrativo.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">Geiger (1986) — <em>mass private sector</em>; Schwartzman (1991, 2000) — análise histórica; Teixeira (1969) — reforma universitária; Durham (1994) — movimento estudantil; Brunner (1991) — modernização da América Latina; Oliveira (1984) — “ilhas de competência”. O diálogo é rico na literatura brasileira sobre educação, mas pouco engaja a literatura internacional mais recente sobre governança regulatória e <em>marketization</em> do ensino superior (ex.: Brown, Marginson).</td>
<td style="text-align: left;">Referências centrais: Geiger (1986), Schwartzman (1991, 2000), Teixeira (1969), Durham (1994), Brunner (1991). Diálogo forte com a produção brasileira; comparativamente fraco com a literatura internacional sobre mercantilização e regulação do ensino superior pós‑anos 2000.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">Vulnerabilidades adicionais: a narrativa assume que a demanda por ensino superior é homogênea e que o diploma é valorizado apenas pelo efeito cartorial, sem discutir a diversificação de retornos no mercado de trabalho; a tipologia do setor privado (empresarial <em>vs.</em> comunitário/confessional) é dicotômica e não captura <em>cases</em> híbridos. A validade externa é maior para países da América Latina com tradições cartoriais e corporativismo docente, mas a conclusão pessimista sobre o governo Lula reflete um viés de conjuntura que deveria ser explicitado como tal. Para o leitor interessado em reformas regulatórias, faltam sugestões concretas sobre <em>design</em> de avaliação institucional que concilie autonomia e <em>accountability</em>. A omissão de uma análise dos <em>community colleges</em> como alternativa factível no contexto federativo brasileiro enfraquece a parte propositiva.</td>
<td style="text-align: left;">Vulnerabilidades: trata demanda como homogênea; tipologia público‑privado binária; viés de conjuntura ao analisar governo Lula. Faltam propostas de <em>design</em> institucional para avaliação. A comparação com <em>community colleges</em> não é desenvolvida como alternativa realista no federalismo brasileiro.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>