<!-- ¶ 1 -->
Tasha Fairfield and Candelaria Garay

<!-- ¶ 2 -->
# Redistribution under the right in Latin America: electoral competition and organized actors in policymaking

<!-- ¶ 3 -->
Original citation: Fairfield, Tasha and Garay, Candelaria (2017) Redistribution under the right in Latin America: electoral competition and organized actors in policymaking. Comparative Political Studies. ISSN 0010 - 4140

<!-- ¶ 4 -->
This version available at: http://eprints.lse.ac.uk/68941/

<!-- ¶ 5 -->
Available in LSE Research Online: January 2017

<!-- ¶ 6 -->
LSE has developed LSE Research Online so that users may access research output of the School. Copyright © and Moral Rights for the papers on this site are retained by the individual authors and/or other copyright owners. Users may download and/or print one copy of any article(s) in LSE Research Online to facilitate their private study or for non-commercial research. You may not engage in further distribution of the material or use it for any profit-making activities or any commercial gain. You may freely distribute the URL (http://eprints.lse.ac.uk) of the LSE Research Online website.

<!-- ¶ 7 -->
This document is the author’s final accepted version of the journal article. There may be differences between this version and the published version. You are advised to consult the publisher’s version if you wish to cite from it.

<!-- ¶ 8 -->
1

<!-- ¶ 9 -->
Redistribution under the Right in Latin America: Electoral Competition and Organized Actors in Policymaking

<!-- ¶ 10 -->
Tasha Fairfield London School of Economics T.A.Fairfield@LSE.ac.uk

<!-- ¶ 11 -->
Candelaria Garay Harvard University Candelaria_garay@hks.harvard.edu

<!-- ¶ 12 -->
Jan. 4, 2017 Forthcoming, Comparative Political Studies

<!-- ¶ 13 -->
Abstract

<!-- ¶ 14 -->
Unexpected social policy expansion and progressive tax reforms initiated by right-wing governments in Latin America highlight the need for further theory development on the politics of redistribution. We focus on electoral competition for low-income voters in conjunction with the power of organized actors––both business and social movements. We argue that electoral competition motivates redistribution under left-wing and right-wing incumbents alike, although such initiatives are more modest when conservatives dominate and business is well-organized. Social mobilization drives more substantial redistribution by counterbalancing business power and focusing incumbents on securing social peace and surviving in office. By characterizing distinctive features of social-policy politics and tax-policy politics and theorizing linkages between the two realms, we contribute to broader debates on the relative influence of voters versus organized interests in policymaking. We apply our theory to explain “least-likely” cases of redistributive policies under conservative governments in Mexico (2006-2012) and Chile ( 2010 - 2014).

<!-- ¶ 15 -->
2

<!-- ¶ 16 -->
## 1. Introduction

Despite a wealth of recent research, understanding the politics of redistribution in unequal democracies remains one of the most salient issues in contemporary political science. Unexpected developments under right-wing governments in Latin America highlight the need for further theory development and a focus on the politics of policymaking. The Fox (2000-2006) and Calderón (2006-2012) administrations in Mexico and the Piñera (2010-2014) administration in Chile enacted pro-poor social policies and tax increases targeting elites despite clear preferences for small government and close ties to business. Similar policy outcomes occurred under Uribe (2002-2010) in Colombia. Influential theories that focus on the role of left-party dominance, median-voter preferences, and/or resource abundance to explain equity-enhancing reforms do not adequately account for this phenomenon of redistribution under conservative incumbents, which could become more prevalent with a rise of the right looming on the horizon. This paper elaborates a theoretical framework for analyzing the politics of redistribution in highly unequal democracies that emphasizes the role of electoral competition for low-income voters in conjunction with the power of organized societal actors, including both business and social movements. We argue that electoral competition for low-income voters plays an important role in driving redistributive reforms under left-wing and right-wing incumbents alike, although initiatives tend to be more modest when conservatives dominate the government and business is well-organized. Social movement mobilization in turn drives redistributive initiatives that depart significantly from conservative governments’ preferences, by counterbalancing business power and focusing incumbents on the imperatives of securing continuity in office and social peace. While in other studies we focus on social policy expansion (Garay 2016 ) or progressive taxation (Fairfield 2015a), this paper explicitly integrates both aspects of redistribution within a unified framework. We characterize distinctive features of politics in each policy realm— electoral competition and social movement pressures are generally most salient for social policy expansion, whereas business tends to dominate direct-tax politics. We also theorize linkages between the two policy domains—concern over fiscal discipline transmits political pressures or constraints on the tax side of redistribution to the spending side, and vice versa. Our endeavor contributes not only to literature on redistribution but also to broader debates on the relative influence of voters versus organized interests in policymaking (Hacker and Pierson 2010, Trumbull 2012, Culpepper 2011). We apply our theory to explain “least-likely” cases of redistributive measures launched by right-wing incumbents in Mexico and Chile. In Mexico under Fox and Calderón, electoral competition for low-income voters motivated social policy expansion and assets taxes that deviated from the traditional policy preferences of the National Action Party (PAN) and its core business constituency. In Chile, electoral competition similarly motivated the Piñera administration to expand social-policy benefits and increase corporate taxes. Direct tax increases were especially surprising considering that these presidents advocated business-friendly flat taxes (Calderón) and tax incentives (Piñera) during their campaigns.^1 Yet redistributive initiatives in these cases remained limited in accord with the policy preferences of right coalitions and their core business constituencies. However, student-movement mobilization in Chile in 2011 placed additional social policy and tax reforms on Piñera’s agenda. Sustained large-scale protest destabilized the government, altered business’ strategic calculations, and drove significant redistributive reforms that the administration would not otherwise have considered. The redistributive policies we examine comprise social programs benefitting lower-income groups and tax initiatives targeting high-income sectors. This focus is sensible for analyzing redistributive politics in Latin American for the following reasons. First, low-income citizens tend to hold precarious, informal-sector jobs and were historically excluded from social-policy protections provided to formal-sector workers. We examine non-discretionary social programs, in contrast to the large literature on clientelistic benefits. Second, taxes extracted from the top decile can make an important direct contribution to redistribution, given that on average, the top 10% in Latin America captures 39% of total income whereas the lower 20% captures only 3.8% (Cepal). While literature on advanced welfare states emphasizes the importance of broad-based consumption taxes for financing redistributive spending, we focus on direct taxes on income and assets, which target the rich. Moreover, direct taxes account for the bulk of Latin America’s revenue shortfalls compared to developed democracies. Our in-depth case studies reflect our conviction that close attention to policymaking processes is imperative for advancing theory on redistributive politics. We employ process tracing to substantiate our arguments, elucidate causal mechanisms, and assess rival hypotheses (Appendix), drawing on evidence from fieldwork, systematic newspaper analysis, and primary and secondary sources. Our focus is on explaining within-country, over-time variation, while also illustrating that similar causal processes operate cross-nationally.

(^1) _Reforma 12/6/2006, Mercurio_ 4/23/2010.

<!-- ¶ 20 -->
## 2. Prevailing Explanations of Redistribution

Influential studies on redistribution emphasize median-voter preferences, economic resources, and partisanship. While we build on insights from these approaches, we find that on their own they do not provide adequate explanatory traction.^2

<!-- ¶ 21 -->
## Inequality and the Median Voter

Classic median-voter theories, which remain influential despite a growing body of critiques (e.g. Ansell and Samuels 2014), predict that higher inequality leads to greater redistribution. Recent work elaborates more nuanced approaches emphasizing the structure of inequality. Lupu and Pontusson (2011) argue that median voters support left parties that promote redistribution when income distributions are highly skewed, such that the median voter is more proximate to the poor than the affluent. Neither classic nor more nuanced median-voter approaches explain levels of redistribution in Latin America. Not only is inequality notoriously high, but income distributions are heavily skewed—a phenomenon termed “top driven inequality” (Birdsall et al. 2000). In Chile, tax- return data indicates that the top 1% receives over 22% of income and profits (Fairfield and Jorratt 2015). Yet redistribution achieved through taxation and spending is surprisingly low (Goñi et al. 2011) from a median-voter theory perspective. Moreover, enactment of progressive policies does not correlate clearly with either absolute levels of, or changes in inequality. In Chile, one of Latin America’s most unequal countries, social policy expansion has lagged behind Brazil (slightly higher inequality) and Argentina (lower inequality), and tax increases have been marginal compared to Brazil and Argentina. Furthermore, although inequality in Chile declined slightly since 2000, societal demands for redistribution increased, as evidenced by public opinion and waves of protest during the Piñera administration.

<!-- ¶ 22 -->
(^2) The Appendix evaluates additional alternative arguments, including the role of technocrats (Ewig 2016).

<!-- ¶ 23 -->
4

<!-- ¶ 24 -->
Two central problems with median-voter approaches help explain these paradoxes. First, neither the level nor the structure of inequality is a good predictor of voter preferences (Haggard et al. 2013, Lieberman and McClendon 2013). Second, median-voter preferences need not determine policy outcomes. One fundamental reason is that organized actors—a key component of our analytical framework—play a crucial role in policymaking (Hacker and Pierson 2010, Korpi 2006). Political parties strive to represent their core constituencies, and the demands of organized interests including business associations, labor unions, and social movements may be much more pressing for policymakers than median-voter preferences. Voters matter in our framework, but we focus on the dynamics of electoral competition and politicians’ efforts to offer policies that attract specific constituencies, instead of assuming that policy positions are tailored to match the median voter’s structurally pre-determined redistributive preferences.

<!-- ¶ 25 -->
## Economic Resources

Scholars have argued that capital scarcity in a context of international economic integration pressured Latin American governments to limit taxation and social spending in the 1980s and 1990s (Haggard and Kaufman 200 8 , Kaufman and Segura-Ubiergo 2001), whereas commodity booms in the 2000s sustained redistribution under left-wing governments in resource-rich countries (Levitsky and Roberts 2011). Resource wealth and economic growth clearly enhance capacity for social spending. Especially where resource sectors are under state control, governments can bypass the often- problematic issue of taxing economic elites, without risking (at least short-term) macroeconomic instability. Yet economic resources alone do not adequately explain the timing, design, and scope of redistributive innovations. Regarding social policy, politicians must have incentives to prioritize lower-income groups rather than allocating revenue to other sectors or other policy goals. Conversely, motivated politicians have expanded social programs despite resource constraints (e.g. McGuire 2010 ). Regarding taxation, reforms may address concerns other than revenue need—fairness, economic efficiency, long-term fiscal stability—and such reforms may in themselves have redistributive effects. Furthermore, the relationship between growth and policymakers’ willingness to initiate progressive tax reforms is highly variable. In Chile, growing revenue from the state-owned copper company and taxes on the privately-owned copper sector has not led policymakers to increase social spending nearly as much as resource arguments would anticipate. Policymakers have shown strong commitment to fiscal discipline and have institutionalized rules that prevent spending copper surpluses on current expenditures. Some of the copper surplus was allocated to help finance pension reform in 2008; in this case, incumbent technocrats argued that Chile’s strong economic position made raising taxes unnecessary, as resource arguments would predict. However, we emphasize that the resource boom neither resulted in dramatic social policy expansion nor eliminated debate on taxing economic elites. Indeed, Piñera’s corporate tax increases would be quite surprising for resource-based explanations of redistribution, which would at most predict higher taxation of extractive sectors. Similar points apply to Mexico, where the timing of social policy expansion does not correlate with high economic growth; in fact, some innovations were introduced during years of only modest, or even negative growth. Moreover, the commodity boom did not produce major windfalls in Mexico compared to other resource-rich Latin American countries, since on average commodities represented only 23% of Mexico’s export revenues from 2002-2013 (Cepalstat).

<!-- ¶ 26 -->
5

<!-- ¶ 27 -->
Likewise, governments proposed tax increases at varying points in oil-revenue and economic- growth cycles—sometimes targeting elites and sometimes not (Magar et. al 2009: 27 – 28, 43 ).

<!-- ¶ 28 -->
## Partisanship

Partisan approaches link redistribution to left dominance in government. For example, Huber and Stephens (2012:240) argue that the rise of left parties in Latin America reduced poverty and inequality, and that variation in left-party strength explains significant cross-national differences on these indicators. We agree that partisanship matters for redistribution. Parties try to imprint their preferences in public policies, and their relative power helps explain the scope and design of redistributive policies. But partisanship is insufficient for explaining decisions to adopt such policies in the first place. On the one hand, right parties do occasionally initiate redistributive policies, while on the other hand, left and labor-based parties in Latin America’s highly fragmented societies have often prioritized relatively privileged formal-sector workers over socially-excluded sectors in greatest need of redistribution. Meanwhile, societal actors pursuing interest-based rather than electoral goals, including social movements and business associations, play important roles in triggering or blocking redistribution. While these actors may influence policymaking through ties to parties, they can also use non-partisan power resources including organization, financial resources, and capacity for large-scale protest. In fact, societal actors may be disconnected from the party system; for example, social movements in contemporary Chile eschew party affiliation, even though their demands are ideologically more proximate to left parties. Accordingly, the relative strength and salience of societal actors in policy debates is not necessarily captured by classic partisan measures like the share of left vs. right seats in congress. In sum, we argue that while partisan affiliation shapes politicians’ preferences regarding redistribution, it does not determine whether those preferences are prioritized, translated into policy proposals, or subsequently adopted.

<!-- ¶ 29 -->
## 3. Electoral Competition and Organized Actors

When do incumbents, particularly those from conservative parties with core constituencies in upper-income sectors (Gibson 1996), initiate redistributive policies? As elaborated below, electoral competition, business actors, and social movements play key roles in encouraging or discouraging redistributive initiatives. Analyzing both business and social movements is a central contribution of our framework, given that most studies focus on one type of actor or the other. Traditional power-resource approaches to social policy and taxation emphasized labor unions and left parties without explicitly analyzing business actors. Subsequent research (Mares 2003, Swenson 1991) sometimes overstated business’s role in promoting social protection (Hacker and Pierson 2002, Korpi 2006). Moreover, civil society actors other than formal-sector labor unions have been relatively neglected in comparative welfare literature on unequal democracies.^3 In addition, integrating organized actors and electoral incentives in redistributive politics contributes to a broader debate in literature on inequality and economic policymaking. A large body of research prioritizes the importance of electoral accountability in driving policy decisions (Beramendi et. al 2015). Hacker and Pierson ( 2012 ) counter that organized actors are much more consequential and emphasize the frequent dominance of business interests, whereas Trumbull

<!-- ¶ 30 -->
(^3) For exceptions see Garay (2007, 2017), Anria and Niedzwiecki (2016).

<!-- ¶ 31 -->
(2012) contends that business often loses in policy debates. We build on and advance efforts to delineate conditions under which the interests of voters, business, or other organized actors prevail and the extent of their impact on policy outcomes (Culpepper 2011, Hacker and Pierson 2010 ) in several ways. First, we draw distinctions between typical tax-policy and social-policy political dynamics and elaborate interactions between the two domains. Second, we emphasize strategic calculations and assessments of relative power that affect policymakers’ decisions and organized actors’ responses to policy initiatives. Third, we highlight that organized actors can heighten or lower issue salience, thereby altering the electoral incentives that incumbents face.

<!-- ¶ 32 -->
## Electoral Competition

Incumbents commonly seek continuity in office through reelection or succession by partisan allies. Intense competition affects incumbents’ prospects for continuity in power and motivates policy decisions to improve their electoral standing. Electoral competition may lead incumbents to adopt policies that maximize the interests of their core constituencies, if they are competing to retain those voters, or to cater to a broader electorate, if competition focuses on other sectors. When electoral competition involves non-aligned low-income voters, parties across the ideological spectrum promote redistributive policies to build support. Populist and left parties promote policies with appeal beyond their organized labor constituencies. And right-wing parties may counter-intuitively promote redistributive policies that deviate from the interests of their core upper-income constituencies. This latter dynamic is especially likely when challengers have a reputation for promoting popular redistributive policies, or when challengers can credibly claim that incumbents represent the wealthy. Under these conditions, the right’s core constituencies may accept modest deviations from their preferred policies as strategically imperative. As partisan approaches would anticipate, competition from left parties can drive these dynamics; however, as our Mexican cases will illustrate, competition for low-income voters can motivate the right to promote progressive policies even when the left is weak. In Latin America, social policy expansion to low-income sectors has been common in contexts of tight electoral competition (Garay 2016). Parties across the ideological spectrum have made campaign promises to expand transfers or services, and they have followed through on these promises in office to consolidate support. The scope and content of these policies is shaped by partisan preferences and power differentials in congress, since reforms proposed by the executive must usually be negotiated in this arena. Electoral competition tends to play a less direct role in explaining decisions to tax elites. Public distaste for regressive consumption taxes in contexts of strong electoral competition can motivate politicians to propose progressive tax increases when revenue needs arise, and social policy expansion driven by electoral competition may generate those revenue needs. Yet Latin American presidential candidates have rarely competed for votes by promising to tax the rich.^4 Although policy design matters critically (e.g., Hacker & Pierson 2010), our broader research suggests that social programs that provide tangible benefits naturally tend to draw greater interest and support from lower-income groups than taxes targeting economic elites, which have no visible, direct effect on lower-income citizens. Progressive taxation can only benefit the poor _indirectly_ —by financing social spending and/or substituting for regressive revenue-raising measures. Unless governments make compelling public appeals and link progressive taxation to visible benefits for non-elites, politicians who oppose taxing elites face minimal risk of electoral

<!-- ¶ 33 -->
(^4) Excepting extractive-resource taxation, which taps nationalist sentiments.

<!-- ¶ 34 -->
7

<!-- ¶ 35 -->
punishment (Fairfield 2015 a). However, emergence of public debate on taxation in connection with active demands for social programs may raise the salience of progressive taxation and generate greater public understanding and support for such initiatives. Our treatment of electoral competition differs from median-voter models and demand- centered approaches in which politicians respond to pre-existing, manifest policy preferences.^5 We view electoral competition as motivating politicians to proactively offer redistributive policies that they anticipate will attract the constituencies they seek to court—which may not necessarily include the median voter. Broad brush-strokes depicting contours of public opinion (e.g. education ranking high among a set of agenda items, or support for the principle that wealthier citizens should bear a higher share of the tax burden) inform politicians’ decisions, and governments sometimes conduct polls to assess support for particular policies. But our broader research suggests that politicians intuitively recognize the support-building potential of social policy expansion without need to systematically assess the distribution of preferences among sectors they aim to attract. And regarding taxation, evidence suggests that findings from American politics that public opinion on tax policy is vague and ill-formed (Bartels 2008 , Graetz and Shapiro 2005 ) apply to Latin America as well (Fairfield 2015a).

<!-- ¶ 36 -->
## Organized Business

While business actors in unequal democracies may not oppose social policy expansion and poverty alleviation, they generally prefer that social spending be modest and financed through growth rather than taxes. Business owners tend to particularly resist corporate and personal income tax increases, which target their resources more directly than consumption taxes, and they are central actors in tax politics. Organization is a fundamental source of business power. Strong encompassing associations, as opposed to fragmented, overlapping, or rival associations, help business advance their interests through two main mechanisms. First, encompassing associations facilitate unity and collective action, which legitimates business demands. When business is uncoordinated, their demands can more easily be dismissed as narrow, particularistic, and against the public good. Second, strong organization strengthens business’s bargaining position by making it harder for policymakers to divide and conquer. Concessions needed to split a broad business opposition front will be more substantial when business associations can effectively forge consensus among their members and coordinate lobbying. While some argue that strong business organization promotes equity in advanced democracies (e.g. Martin and Swank 2012), we rarely observe this dynamic in Latin America, where the structure of capitalism and the nature of business preferences are very different (Schneider 2013). Multiple other power resources promote business influence. Core constituency relationships with conservative parties, as in Chile and Mexico, help business mobilize politicians to advance their interests. On highly technical issues like taxation, conservative politicians may even take direct instruction from business on which measures to advocate and which to oppose. Recruitment into government, where business leaders are appointed to executive-branch positions or state agencies, affords a direct role in policymaking. This practice was widespread in Chile under Piñera. Where business has strong and multiple sources of power, tax decisions are constrained by business interests. When electoral incentives motivate politicians to deviate from business preferences, those deviations are generally minor. Governments often negotiate concessions

<!-- ¶ 37 -->
(^5) Regarding advanced democracies, see Hall (2015).

<!-- ¶ 38 -->
8

<!-- ¶ 39 -->
(e.g. exemptions or lower rates), include compensations (e.g. eliminating other taxes that business dislikes), and/or channel part of the revenue raised into budgetary items that business supports. Our case studies illustrate the ways in which right governments use creative framing and policy bundling to balance pressures for progressive tax reform against the interests of organized business constituencies.^6 However, extraordinary contexts can alter strategic calculations and lead business to refrain from actively opposing income tax increases.

<!-- ¶ 40 -->
## Social Movements

Social movements do not form easily and may have difficulty sustaining collective action; however, when they do coalesce around specific demands, they influence policymaking through multiple mechanisms. We focus here on the role of large-scale mobilizational capacity, which is especially important when alternative strategies (e.g., pressure through institutional channels) are not available or not viable. First, strong and sustained protest can destabilize governments by disrupting societal, economic, and government activities. Second, social mobilization around redistributive demands in unequal societies can gain public support and undermine the government’s electoral prospects unless policy responses satisfy those demands. Third, demonstrations on one set of issues can catalyze protest around new sets of issues, generating a cycle of destabilizing contention and pushing incumbents to acquiesce in order to restore social peace. In contexts of sustained social mobilization, incumbents’ responses often show exceptional departures from their policy priorities. Social movements may set the policy agenda, and reform proposals may be negotiated directly with movement leaders. Pressure from mobilized social sectors tends to have a much greater impact on policy decisions than electoral incentives alone. Social mobilization has been a critical factor driving incumbents to expand benefits for labor- market outsiders and has significantly influenced policy design in Argentina and Brazil (e.g. Weyland 1996, Garay 2016 ). Social mobilization has also motivated incumbents to tax economic elites. Beyond creating revenue needs to finance social policy, popular mobilization against broad-based or regressive taxes, or anticipation thereof, motivates revenue-strapped governments to increase progressive direct taxes instead. And in some cases, including the 2011 Chilean student protests, social movements explicitly demand redistributive taxation. Sustained and disruptive protest counterbalances business power and motivates economic elites to accept redistributive policies with minimal resistance for the sake of restoring social peace and precluding pressure for more radical reforms.

<!-- ¶ 41 -->
## Integrating Analysis of Social Policy and Tax Policy

Our framework clarifies differences between social-policy and tax-policy politics while elucidating the ways in which the two arenas interact. At the first tier of analysis, electoral competition and/or social movements play a predominant direct role in social policy expansion, whereas business dominates direct-tax politics. On the social policy side, electoral competition promotes relatively modest initiatives, whereas social movement mobilization drives more significant expansion of benefits. On the tax side, when business has strong and multiple sources of power, governments are unlikely to increase progressive direct taxes. Less typically, business power can be counteracted by social mobilization and/or electoral competition. Yet by and large, direct taxation in highly-unequal democracies tends to entail debate between economic elites and political elites, whereas social policy engenders greater policymaker engagement with popular

<!-- ¶ 42 -->
(^6) On reform strategies more broadly see Fairfield (2015a:53–62).

<!-- ¶ 43 -->
9

<!-- ¶ 44 -->
sectors—negotiation with social movements, and/or engagement with voters via responsiveness to electoral incentives. At a second level of analysis, concern over fiscal discipline transmits political pressures from the social policy arena to the tax arena and vice versa. On the one hand, electoral competition and/or social movements acting on the spending side can have an indirect effect on tax policy, by simultaneously creating revenue needs and making regressive tax increases politically infeasible, thereby compelling policymakers to tax economic elites. On the other hand, powerful business interests acting on the tax side can have an indirect effect on social policy, by constraining policymakers’ ability to raise revenue for spending. In some cases, concern over fiscal discipline tightly couples social policy with tax policy (e.g. Chile under Concertación governments); in others, social-spending commitments gradually build pressure on the tax side (e.g. Mexico). Revenue abundance may weaken the fiscal-discipline connection and focus redistributive debates mainly on spending; however, the extent to which policymakers prioritize fiscal discipline and eschew spending natural-resource windfalls varies widely. Figure 1 illustrates the typical roles played by our three explanatory factors. Our Mexican cases display typical dynamics with regard to electoral competition, which directly motivated social policy expansion and indirectly promoted progressive tax initiatives, and business, which worked to ensure that those tax initiatives were modest. Our Chilean cases display the typical political dynamics in the social policy arena but also showcase less typical direct roles for electoral competition and social mobilization in driving progressive tax initiatives that business would otherwise have blocked.

<!-- ¶ 45 -->
Constraining : Business

<!-- ¶ 46 -->
SOCIAL POLICY DIRECT EXPANSION Fiscal Discipline TAXATION

<!-- ¶ 47 -->
Promoting : Electoral Competition Social Mobilization

<!-- ¶ 48 -->
## Figure 1: Typical Redistributive-Policy Political Dynamics

Bold arrows indicate direct roles; dashed arrows indicate indirect roles.

<!-- ¶ 49 -->
## 4. Mexico

Electoral competition drove redistributive initiatives in Mexico under Fox (2000-2006) and Calderón (2006-2012). Both presidents represented the PAN, a programmatic conservative party with close connections to big business (Lujambio 2001). Competition between Mexico’s three major parties—the historically hegemonic PRI, the PAN, and the center-left PRD—intensified in the late 1990s (Figure 2 ). While the PRI had traditionally mobilized low-income voters in large numbers, obtaining solid victories in districts where these voters are concentrated, the PAN made significant gains among this constituency at

<!-- ¶ 50 -->
Revenue constraint

<!-- ¶ 51 -->
Revenue need; Regressive taxes infeasible

<!-- ¶ 52 -->
10

<!-- ¶ 53 -->
the PRI’s expense in the 2000 presidential election. Ecological data show that 39% of low- income municipalities^7 experienced electoral competition—defined as a margin of less than 10 percentage points for the winner and/or a victory for the challenging-party candidate (in this case the PAN). In 2006, when the PAN defended the presidency against the PRD, 71% of low- income municipalities experienced electoral competition.^8

<!-- ¶ 54 -->
## Figure 2. Vote Shares in Presidential Elections, Mexico (1982–2006)

Source: IFE.

<!-- ¶ 55 -->
Regarding social policy, this intense electoral competition for low-income voters spurred a major expansion of benefits and services to previously uncovered citizens, which, while unprecedented, remained limited in terms of benefit levels and the role of the state. Regarding taxation, electoral competition precluded unpopular broad-based tax increases and thereby compelled Calderón to propose a significant but modest tax on business instead to close a growing fiscal gap.

<!-- ¶ 56 -->
## Social Policy

Until the 2000s, social policy did not reach low-income populations on a significant scale, even though roughly half of Mexicans lived in poverty. Under Fox and subsequently Calderón, health care, income support, and pensions were extended to large swaths of the low-income population. Given Mexico’s historically low social spending and limited covereage, these initiatives constituted a significant departure from the status quo. Social policy had played an important role in the 2000 presidential campaign. Seeking to gain an edge over the PRI candidate, Fox pledged to increase social spending and proclaimed that “every Mexican” would have access to “primary care and hospital services.”^9 Upon winning office after 71 years of PRI rule, Fox sought to consolidate support from low-income sectors, who had voted for the PAN in unprecedented numbers, by honoring these campaign promises.

<!-- ¶ 57 -->
(^7) Municipalities in which at least 55% of the population lacks formal-sector health insurance according to the 2000 census (data from INEGI-SIMBAD). (^8) Elaborated with electoral data from CIDAC. (^9) _Reforma_ 05/26/2000. 0 10 20 30 40 50 60 70 80 90 100 1982 1988 1994 2000 2006 **%""vote"share"** PRI PAN PRD/DemocraticFront

<!-- ¶ 58 -->
11

<!-- ¶ 59 -->
In his first years in office, he transformed and significantly expanded a pre-existing, small-scale conditional cash transfer program that reached only rural areas, creating the much broader _Oportunidades_ program, and he piloted _Seguro Popular,_ a voluntary health scheme to cover uninsured individuals. _Seguro Popular,_ Fox’s flagship social program, was submitted to Congress in 2002 and passed a year later with broad support from PAN legislators and the PRI, which was also competing for low-income voters. Reflecting the preferences of the PAN and conservative politicians from the PRI, _Seguro Popular_ required non-indigent citizens to pay premiums and fees and allowed private hospitals to provide services. Several politicians from the center-left PRD opposed these aspects of _Seguro Popular_ and criticized the program as too limited in scope (Ortiz 2006; interviews: Laurell 2007 , Vega-Galina 2006). However, with 10.2% and 12.5% of the seats in the lower and upper chambers respectively, the PRD lacked sufficient representation in congress to secure concessions. The Fox period is a noteworthy case where explanations emphasizing resource abundance or the role of challenges from the left in motivating social policy expansion fall short. Contrary to economic-bonanza arguments, social-policy expansion began in 2001, a year of negative growth followed by two years of only modest growth. And political competition involved primarily the PAN and the PRI, which had turned to the right in the 1990s (Gibson1997, Murillo 2009 ). However, competition from the left surged as the 2006 elections approached and spurred additional innovations. The PRD’s rising politician López-Obrador promised to expand social policy with an emphasis on universal pensions. As mayor of Mexico City, López-Obrador won massive support by enacting a similar program within his jurisdiction. A PRD social policy advisor (interview, 2007) highlighted the political importance of pension expansion: “The increase in popularity [López-Obrador] attained with this program was impressive. Why wouldn’t I vote for this candidate who did so much for my grandpa?” Pensions became a central issue on the agenda and pushed the government to respond quickly (interview, Gomez- Hermosillo 2007). Despite initially discrediting Lopez-Obrador’s call for non-contributory pensions as populist and unfair to those who had saved for retirement,^10 Fox launched a pension program for senior members of households enrolled in _Oportunidades_ a few months before the election, which was interpreted by many as an effort to improve prospects for the PAN candidate, Calderón (interview: Perez Bejerano, 2007) After Calderón’s razor-thin 2006 victory, López-Obrador contested the elections, claiming fraud. Encampments and protests disrupted Calderón’s inaugural ceremony and continued into his term. In this context, the PRD proposed and successfully obtained funding for a new pension program within the 2007 budget (interviews Pérez-Bejerano, Navarro Quintero 2007). Electoral competition thereby pushed the PAN to expand pensions beyond its original agenda. The balance of power in congress shaped the design of the pension program. The PAN held a plurality, but the PRD now had enough seats to play a significant role in negotiations. The PRD advocated a universal benefit equivalent to 50% of the minimum wage for seniors aged 70 or older. The PAN preferred less generous benefits targeted to seniors in extreme poverty. The compromise reached established funding for a benefit level of roughly one third of the minimum wage, which, after additional extensions in subsequent years, reached roughly half of citizens over 65 without social security contributions in 2010.

<!-- ¶ 60 -->
(^10) _Jornada_ 03/18/2005.

<!-- ¶ 61 -->
12

<!-- ¶ 62 -->
## Direct Taxation

Upon taking office, Calderón sought revenue to promote medium-term fiscal stability given declining oil reserves, economic deceleration, and the longstanding problem of Mexico’s remarkably low tax take. While tax reform was not directly coupled to social policy, the new spending commitments—especially pension expansion and health care—contributed to budgetary pressures and concern over pending inflation and fiscal deficits.^11 As expected of the right, the administration wished to raise revenue through consumption taxes in accord with business preferences.^12 However, electoral competition indirectly motivated Calderón to propose progressive direct taxes by removing regressive alternatives from the agenda. Given continued PRD protest contesting the 2006 election, Calderón needed not only to consolidate support among the low-income constituencies he had courted during the election, but also to legitimate his presidency more broadly. Increasing the VAT was manifestly unpopular and perceived as harming poor households.^13 The opposition parties had rejected Fox’s 2001 initiative to raise the VAT and broaden its base—some PAN legislators even voted against these measures (Romero 2015:169). Taxing economic elites was the only feasible option, and Calderón’s 2007 reform accordingly targeted the PAN’s own business constituency. The central feature was a minimum corporate income tax ( _impuesto empresarial a tasa única,_ IETU) intended to curtail rampant avoidance and evasion. The reform also included a tax on cash deposits, another anti-evasion measure directed at informal-sector businesses. The government sought to balance the interests of the broader electorate against those of its core business constituency by alternatively emphasizing spending goals that appealed to one sector or the other. In accord with the need to build legitimacy and consolidate electoral support, the administration framed the initiative as a “fiscal reform for those who have least.”^14 However, when business raised objections to the IETU, the administration shifted from emphasizing funding for social spending to promising that half of the revenue generated would finance infrastructure to promote growth,^15 which appealed more to the private sector. Rhetorical links to social spending and poverty reduction resumed prominence in late July while the lower house evaluated the bill. For example, Calderon asserted: “The fiscal reform for those who have least opens the possibility of equalizing the terrible gaps in Mexico between rich and poor, north and south, cities and countryside.”^16 Despite vociferous complaints, especially regarding the IETU, evidence suggests that Mexico’s business peak associations (CCE, CMHN, COPARMEX)—some of the strongest in Latin America (Schneider 2004:39-40)—accepted the reform. First, compensations included in the reform package and expectations of longer-term policy gains assuaged the powerful business sector. The IETU replaced the old assets tax, which business viewed even less favorably (CEESP 2007b), and the government promised to move toward a flat income tax (CCE 2010:17), which business enthusiastically advocated (CEESP 2007a). The government’s promises to spend the proceeds not only on social spending for the poor—an objective that business finds difficult to openly oppose—but also on infrastructure further placated business (CEE 2010:17). Second, the peak associations recognized that the government needed revenue to ensure fiscal discipline,

<!-- ¶ 63 -->
(^11) _Reforma_ 1/8/2007. (^12) Early reform drafts included VAT changes similar to Fox’s 2001 initiative (Romero 2015:171); Calderón subsequently proposed a flat consumption tax (2009). 13 91% opposed applying the VAT to food and medicine (Elizondo 2014:21). (^14) _Reforma_ 6/20/2007. (^15) _Reforma,_ 7/18/2007. (^16) _Reforma_ 7/26/2007.

<!-- ¶ 64 -->
13

<!-- ¶ 65 -->
particularly in light of growing public pension costs (CEESP 2007:2), and they understood that VAT reform was infeasible.^17 Given these considerations, CMHN’s president asserted: “The IETU like any tax is not perfect, but it’s better than doing nothing.”^18 The head of Grupo Bimbo likewise publicly supported Calderón’s reform and announced: “We will back the IETU.”^19 The Mexican peak associations accordingly focused on ensuring that the IETU would be “the least burdensome possible,”^20 which primarily entailed coordinated lobbying for a lower rate.^21 At the same time, however, the CCE’s think tank produced a remarkably positive report on the IETU (CEESP 2007b), which we interpret as a further sign of business acquiescence to the tax. Finally, it is likely that a strategic interest in strengthening Calderón’s precarious political position also encouraged business to refrain from deploying its sources of power—including organizational resources, the core constituency relationship with PAN, and informal ties to the PRI forged during market reform in the 1990s^22 —to obstruct the IETU. The CCE’s praise for “positive efforts by the Calderón administration, on issues of finance management, cost reduction, infrastructure, and public security”^23 during the tax reform debate is consistent with this interpretation. A similar dynamic operated in the social policy arena, where the prospect of López-Obrador’s rise to power contributed to business support for expanding benefits to low- income groups (interview: business-association informant 2006). The government managed to pass the reform with support from the PRI, despite PRD opposition. Whereas the PRD framed the bill as regressive and demanded taxes that targeted economic elites more visibly, the PRI condoned the reform for affecting privileged sectors rather than the poor.^24 Yet the PRI nevertheless advocated modifications in line with business demands. PRI legislators joined PAN representatives in pushing for a lower IETU rate and deductions benefitting sectors including maquiladoras and private schools, which the executive branch eventually accepted.^25 Notwithstanding these concessions to business, the government estimated the IETU’s revenue yield at 1%GDP (SHCP 2011:75). In the Mexican context, this constitutes a modest but significant tax increase, of similar magnitude to other revenue-raising initiatives from 1983- 2013 (Magar et. al, Unda 2015 ).

<!-- ¶ 66 -->
## 5. Chile

Chile provides additional cases of social policy expansion and progressive tax increases under the right. Our analysis examines how the Piñera administration, the governing _Coalición por el Cambio_ (RN-UDI coalition), and their powerful business constituency responded to electoral incentives and social mobilization. As in Mexico under Fox and Calderón, electoral competition motivated social policy expansion during Piñera’s first year in office. Piñera sought to consolidate broad electoral support, despite the _Coalición’s_ reputation for favoring economic

<!-- ¶ 67 -->
(^17) _Reforma_ 7/9/2007. (^18) Ibid. (^19) _Reforma_ 9/12/ (^20) _Reforma_ 7/9/ (^21) _Reforma_ 7/21/2007. Narrow business sectors like maquiladoras that anticipated a hard hit from the IETU lobbied separately for special treatments. (^22) Schamis (1999:257), Teichman 2002:499-500. (^23) _Reforma_ 8/27/2007. (^24) _Reforma_ 7/16/2007. (^25) _Reforma_ 8/1/2007. Securing PRI votes also required a host of concessions on unrelated issues, including electoral reform and decentralization of spending.

<!-- ¶ 68 -->
14

<!-- ¶ 69 -->
elites. These initiatives were packaged in rhetoric that created high expectations despite their modest scope, a mismatch that evidences the _Coalición’s_ dilemma of attracting lower-income voters without alienating its core business constituency, which preferred small government. Electoral considerations also motivated Piñera to finance reconstruction after Chile’s 2010 earthquake by temporarily increasing direct taxes, despite controversy within the governing coalition and business. Subsequently, the emergence of social mobilization forced new social policy and tax initiatives onto the government’s agenda, counterbalanced business power, and compelled the _Coalición_ to adopt reforms that notably departed from right-party and business preferences.

<!-- ¶ 70 -->
## Electoral Competition and Modest Reforms (2010-2011)

Redistributive policies during Piñera’s first two years were driven by tight electoral competition between the governing _Coalición_ and the opposition _Concertación,_ in a context of growing partisan dealignment. The proportion of voters who did not identify with any major coalition increased sharply after 2005 to around 50% (Luna and Altman 2011:150). Lower-income voters became especially important for the right’s vote-share expansion since the late 1990s, when Lagos faced an extremely close presidential race against UDI candidate Lavin. Electoral competition in districts where the majority of the population is low- income was limited in the first years of democracy but grew dramatically beginning in 1999, as the right strove to mobilize electoral support (Figure 3). Courting lower-income voters therefore played an important role in shaping the executive’s agenda and legislators’ responses to policy initiatives.

<!-- ¶ 71 -->
## Figure 3. Electoral Competition for Low-income Voters, Presidential Elections, Chile 1989-2010.

Notes: Share of low-income municipalities, i.e., those with at least 55% of the population classified in FONASA health insurance groups A or B—indigent or earning under minimum wage--where the challenging party wins and/or the margin of victory is less than 10 percentage points. Sources: Electoral Data from Historical Dataset of Elections from Observatorio Político-Electoral Universidad Diego Portales. Health coverage data for 2011 from Observatorio Social, Gobierno de Chile.

<!-- ¶ 72 -->
0%

<!-- ¶ 73 -->
10%

<!-- ¶ 74 -->
20%

<!-- ¶ 75 -->
30%

<!-- ¶ 76 -->
40%

<!-- ¶ 77 -->
50%

<!-- ¶ 78 -->
60%

<!-- ¶ 79 -->
70%

<!-- ¶ 80 -->
80%

<!-- ¶ 81 -->
90%

<!-- ¶ 82 -->
100%

<!-- ¶ 83 -->
1989 1993 2000 2005 2009

<!-- ¶ 84 -->
Low@incomemunicipalitieswithelectoralcompetition

<!-- ¶ 85 -->
15

<!-- ¶ 86 -->
## Social Policy

Piñera’s initiatives represented the continuation of a process of social policy expansion that began in the early 2000s in response to electoral competition. During the presidential campaign, Piñera promised new transfers for indigent families, elimination of health insurance contributions for low-income pensioners, and quality improvements in public schools, with the goal of attracting broad support—especially from low-income voters—in the highly competitive electoral environment. These initiatives were portrayed as critical for achieving central campaign promises: eradicating indigence by 2014 and poverty by 2018.^26 Piñera also pledged to extend maternity leave for female workers with social security contributions from three to six months. After assuming office, Piñera introduced his Ethical Family Income program ( _Ingreso Etico Familiar,_ IEF), which extended new transfers and social assistance to indigent families (3.7% of the population). The benefits included a small non-conditional transfer, a transfer for working women and subsidies for their employers, as well as job search assistance for up to two years. Additionally, the IEF provided a one-time payment to children from households in the four poorest income deciles who ranked among the top 30% of their class. The center-left responded to the IEF initiative with caution. _Concertación_ legislators maintained that fighting indigence required more permanent and more generous benefits.^27 The name of the program was borrowed from a Chilean bishop’s high-profile exhortation to establish an “ethical salary” of 250,000 pesos, more than twice the prevailing minimum wage.^28 Part of the debate regarding the IEF concerned whether the program should guarantee a minimum income as requested by the bishop, rather than the government’s proposed package of transfers which would amount to only about 53,000 pesos for a family of four for a maximum of two years_._ According to _Concertación_ senator Zaldívar: “Talking about ‘ethical family income’ raises expectations beyond what the program really offers. [The IEF] is good but it is also very modest. The subsidies ... are too small to reach the ethical family income that civil society, congress, and the executive have been talking about.”^29 Moreover, the absence of detailed eligibility criteria elicited strong criticism from _Concertación_ legislators who feared the Ministry of Social Development, charged with implementing the IEF, would subsequently establish stringent conditions, resulting in even fewer beneficiaries than anticipated. Despite the criticisms, key _Concertación_ legislators supported the bill to avoid popular discontent over perceived blocking of the government’s flagship social policy. The government accused the _Concertación_ of obstructionism as soon as the first criticisms of the IEF were raised. The IEF’s popularity and similarity to _Chile Solidario_ , a program the _Concertación_ introduced in 2004, also elicited acceptance. Student protests in 2011 (analyzed below), which undermined support for both government and opposition, further compelled the _Concertación_ to approve the program in 2012.^30 Other components of Piñera’s social-policy agenda—elimination of retirees’ health insurance contributions and extension of maternity leave—generated similar political dynamics. _Concertación_ legislators advocated expanding the scope of benefits, whereas _Coalición_ legislators sought to restrict their value, as with maternity leave, or to target only the very poor, as in the case of the health insurance contribution. When the _Concertación_ proposed an

<!-- ¶ 87 -->
(^26) _Mercurio_ 5/22/2010, Piñera 2010. (^27) The program would have a total budget of 410 million dollars. (^28) _Mercurio_ 8/3/2007. (^29) Diario de Sesiones, Legislature 360, Senate, Session 14a, 5/2/2012. (^30) Concertación approval was 14%; disapproval reached 73% ( _MercoPress_ , 11/8/2011).

<!-- ¶ 88 -->
16

<!-- ¶ 89 -->
alternative social agenda that included more encompassing benefits,^31 the _Coalición_ responded with accusations of obstructionism.^32 The _Concertación_ feared the political cost of rejecting Piñera’s proposals and appearing to hinder social policy expansion. These concerns were particularly salient in the context of hardship produced by the earthquake and intense competition with the right coalition for popular support. As a result the center-left ultimately approved all of the government’s main social policy initiatives. During the debate on these social programs, business grumbled about growing public expenditure and negative impacts on female employment (interviews: CPC-A, ABIF 2011). Business informants privately derided Piñera’s “populist” turn and prioritization of electoral concerns over economic efficiency (interview: ABIF 2011). However, they recognized that the government was politically obliged to fulfill its campaign promises (CPC-A 2011), and they opted to publicly support a president who they expected would govern the economy in accord with business interests (interviews: ABIF, SNA 2011). Despite business’s concerns, social policy outcomes in all cases were consistent with the right and its core constituency’s preference for modest, targeted benefits. Elimination of pension contributions reached the most vulnerable retirees only. Maternity leave had a slightly broader scope but was nonetheless restricted to female workers with at least three consecutive social security payments before pregnancy, a requirement that excluded most of the informal sector, and benefits during the last three months tapered by 50%. The CPC (2012) celebrated congress’s adoption of its main recommendations for “reconciling maternity protection with the right to work and the activities of private enterprise.”

<!-- ¶ 90 -->
## Direct Taxation

Chile’s 2010 earthquake—days before Piñera’s inauguration—wreaked damage estimated at USD30 billion. Prominent economists affiliated with the right-wing coalition maintained that given Chile’s strong macroeconomic position, reconstruction could be fully financed via international borrowing and Chile’s copper-stabilization fund.^33 Resource-abundance arguments might predict similar measures and/or higher taxation of the booming copper sector. However, Piñera surprised everyone by including not just a copper royalty increase, but also a general corporate tax increase—initiatives that business and the right had long opposed—in his reconstruction package.^34 As with social policy, concern with consolidating public support in a context of strong electoral competition played a key role in motivating these tax increases. Public opinion usually mattered only marginally for taxation in Chile; political elites and organized business were the dominant actors in this policy area. However, criticisms of Piñera’s questionable status as the country’s wealthiest businessman and its highest elected official threatened to undermine his legitimacy and compelled the administration to propose a modest deviation from its business constituency’s policy preferences. In contrast to Calderón’s 2007 tax reform, the indirect effects of electoral competition were overshadowed by a less typical _direct_ role whereby the Piñera administration anticipated a public opinion dividend from the tax increase itself. As in Mexico

<!-- ¶ 91 -->
(^31) “Agenda Social sin Letra Chica” Concertación, May 2011. (^32) Concertación legislators complained that congress should not hold “take it or leave it” votes that precluded modifications (Senator Walker, _Terra_ 5/9/2011). (^33) _Mercurio,_ 9/11/ (^34) See Fairfield (2015a) for analysis of other aspects of this and the 2011 reform.

<!-- ¶ 92 -->
17

<!-- ¶ 93 -->
after 2006, the relative strength of the left coalition helped shape the government’s policy decisions. Throughout the 2009 presidential campaign, the _Concertación_ strove to discredit Piñera for mixing money and politics. Forbes estimated Piñera’s net worth at USD2 billion; his holdings included the television station Chilevisión and a 26% share in the airline LAN.^35 To preclude conflicts of interest, Piñera promised to sell his LAN shares. However, he retained an 11% holding upon taking office. The manner in which Piñera divested of these remaining shares incurred further censure; the _Concertación_ charged that he opted to sell his entire holding company in order to minimize his taxes. _Concertación_ Senator Zaldívar accused Piñera not only of avoiding USD 50 million in taxes,^36 but also of incurring a conflict of interest given that as president, Piñera appointed the tax agency director who would review the operation.^37 Criticisms emanated from within the right as well. RN’s president asserted that Piñera’s slow divestiture likely cost him over half a million votes.^38 Meanwhile, right politicians urged Piñera to sell Chilevisión, echoing _Concertación_ concerns about conflicts of interest with presidential appointments to the TV regulatory agency: “There is no one in the _Coalición por el Cambio_ who believes that it is reasonable, possible, or even legal for President Piñera to maintain ownership of Chilevisión.”^39 In this context, government advisors proposed temporarily raising the corporate tax from 17% to 20% to undercut perceptions of a close association between Piñera and big business. Regarding the proposal, a government source explained: “The discussion has extended beyond a purely technical sphere and has become political.”^40 A _Mercurio_ (4/11/2010) survey found 74% support among Santiago respondents for increasing the corporate tax; confidential polls conducted by the executive branch confirmed the measure’s popularity.^41 This is therefore a case where a government expected that progressive taxation in and of itself would boost public support (interview, Executive Advisor 2011 ). Despite arguing that the direct tax increases should be permanent, the center-left accepted most of executive’s bill, mirroring the social policy dynamics described above. First, the perceived risk of antagonizing public opinion by delaying funds for reconstruction pressured the _Concertación_ to acquiesce.^42 Second, raising the corporate tax to 20% had been a _Concertación_ goal since 1990, although few governments had attempted reforms toward that end given anticipated resistance from business and the right. By coopting this policy objective, the government put the _Concertación_ on the defensive and weakened its moral authority for criticizing the administration. An UDI legislator explained: “The government took a battle flag away from the _Concertación_ , because this government has dared to do what the _Concertación_ perhaps wanted to do but never dared to try,” (interview, Silva 2011).^43 Right-party legislators also accepted the reform, despite complaints from hardline _Coalición_ members. First, the direct-tax increases were explicitly temporary, and, like

<!-- ¶ 94 -->
(^35) BBC _Mundo, Cono Sur,_ 2/6/2011. (^36) _Mostrador_ 3/22/2010. (^37) _Mostrador_ 3/24/2010. (^38) _Mercurio_ 3/29/2010. (^39) RN Senator Allamand, _Mercurio_ 4/13/2010. (^40) _Mercurio_ 3/30/ (^41) Likewise, raising the copper royalty was patently popular. (^42) Diario de Sesiones, legislature 358, session 25a, 6/9/2010. (^43) Regarding the royalty, the _Concertación_ managed to push the government to make the reform somewhat more substantial, given potential rewards to outbidding on this popular policy issue.

<!-- ¶ 95 -->
18

<!-- ¶ 96 -->
Calderón’s proposal, the package included other measures that appealed to the right and its core business constituency—a reduction of the stamp tax and tax credits for donations. After an average revenue yield of 0.25%GDP for the first two years, the reform would produce a permanent annual revenue loss of approximately 0.2%GDP. Right-party informants identified these longer-term tax cuts as critical for ensuring their coalition’s support (interviews: Silva, Coloma, Ulloa, Larraín, 2011). Second, legislators either conceded that financing earthquake reconstruction justified the tax increases, or found it difficult to argue differently in public (interviews Silva, Coloma, Ulloa, Larraín, 2011). Furthermore, the UDI, the most ideologically neoliberal of the two right parties, recognized that the tax increases were popular and that opposing them could incur political costs, potentially jeopardizing the right’s prospects for a second term and the UDI’s aspirations to assume leadership within the coalition (interviews: CPC-A, Zaldívar, 2011 ). Similar strategic considerations motivated business to refrain from leveraging its multiple sources of power—including organization and partisan ties to the right—to resist higher taxation. Business informants identified the temporary nature of the tax increase as critical, and they lauded the tax benefits as a step in the right direction (interview: CPC-A 2011). Business also recognized that the earthquake created a moral imperative to contribute to reconstruction, which the Piñera administration repeatedly emphasized.^44 According to one informant (SNA 2011), “extraordinary events required extraordinary measures.” Business informants who maintained that tax increases were unnecessary given Chile’s strong macroeconomic position nevertheless acknowledged that business was in a weak position to resist (interviews ABIF, Sonami, CNC, 2 011). Had they rejected higher taxes, the business associations would have suffered social condemnation (interviews: Mining Ministry, Sonami 2011) and demand for more radical tax increases. In this context, business opted for strategic restraint, anticipating that they would win other policy gains in the future: “We decided not to show our teeth... it was our government,” (business-association informant 2011).

<!-- ¶ 97 -->
## Mass Protest and Broader Innovations (2011-2014)

Mass protest, spurred by the student movement, dramatically shifted the political dynamics of redistributive policies. Whereas competition for votes and concern over public opinion were the primary factors motivating Piñera’s initial social-policy and tax proposals, popular protest, which attained an unprecedented scale and duration,^45 became the key driver behind education and tax proposals thereafter. The Piñera administration responded to social mobilization by initiating reforms that deviated markedly from the right’s established agenda. Education reforms were a dramatic departure from the status quo. Tax measures remained moderate in cross- national perspective in terms of revenue yield yet nonetheless constituted the largest direct tax increase since Chile’s renowned 1990 tax reform. Moreover, the protests opened debate on education and tax policy that far exceeded the bounds of what was considered appropriate and feasible during the prior two decades, paving the way for far-reaching redistributive initiatives when the center-left coalition returned to power in 2014. In both policy areas, the primary factor motivating reforms was the imperative of achieving social peace. In the competitive electoral context, public opinion, which sided with the students

<!-- ¶ 98 -->
(^44) 3/19/2010 icare.cl/noticias Nuevas autoridades llaman a los empresarios para que ayuden en la reconstrucción del País. (^45) Based on systematic newspaper search and coding. On demobilization prior to the student protests, see Delamaza (2010).

<!-- ¶ 99 -->
19

<!-- ¶ 100 -->
against the government, played a role as well; the right coalition recognized that it had no future in the presidential palace unless the government resolved the conflict. Destabilization produced by mass mobilization fundamentally drove these dynamics.

<!-- ¶ 101 -->
## Emergence of Contestation

The 2011 mobilizations had antecedents in high-school student protests that erupted in 2006 over transportation fares and the general law of education (LOCE) enacted by the Pinochet dictatorship. The market mechanisms Pinochet introduced, including an extensive voucher system that stimulated growth in the for-profit private-school sector, were viewed by many as reinforcing glaring inequities in access and quality of education available to low-income versus high-income students. Reforms under Concertacion administrations had done little to reduce inequities given the strength of conservative interests. In response to the 2006 protests, a new education law was approved, but it maintained the main features of LOCE (Pribble 2013:105). High-school student mobilization quickly died out, due to internal divisions and the movement’s limited success at influencing the reform process (Donoso 2013). However, these protests gave future leaders valuable experience. When the young activists entered university, they improved coordination between Chile’s multiple student federations and expanded their membership base (interview: Jackson 2012). After relatively isolated protests over bus fares and scholarships in early 2010, student mobilization intensified later that year when Piñera initiated education reforms that conflicted with the students’ agenda. In accord with his campaign platform,^46 the president’s bill, which mainly focused on secondary education, increased financial incentives based on performance and enacted intuitional changes that would grant principals more autonomy (e.g., in evaluating teachers and firing underperforming teachers).^47 Additional reforms were planned for higher education,^48 which the students anticipated would provide further benefits for private universities. Piñera’s agenda catalyzed a strong sense of common purpose within the student movement: “We all had to set aside our internal differences to fight against a common enemy, which were these reforms that no one agreed with... This scenario of risk made us set aside our differences and act as a more unitary bloc,” (Jackson 2012, interview). The Confederation of Chilean University Students (CONFECH) and the Federation of University Students (FECH) mobilized for increased funding, quality education, and lower interest rates on student loans. Protests began in April and escalated in May. On May 12, coordinated demonstrations were held throughout Chile and brought 100,000 people into the streets. Student leaders challenged Piñera to respond to their demands during the annual May 21 presidential address.^49 Piñera’s failure to address student demands motivated them to scale up protest, which continued on a massive scale through October. The FECH president called for “radicalizing the movement” and urged universities to “call strikes, occupations, and generate pressure to obtain once and for all a response from the government.”^50 Collective action escalated, including occupations of hundreds of schools and universities as well as continued street protests that received support from labor unions and civil society more broadly.^51 For example, a nationwide

<!-- ¶ 102 -->
(^46) Piñera (2010) (^47) Legislatura 358, Sesión 104, Mensaje 517,11/22/2010. (^48) _Tercera,_ 6/20/2010. (^49) _Nacion_ , 5/12/2011. (^50) _Nación_ , 5/23/2011. (^51) _Nación_ , 6/14/2011.

<!-- ¶ 103 -->
20

<!-- ¶ 104 -->
day of protest in June 2011 mobilized 400,000 people, and a national strike was held in August to support student demands. Meanwhile, student demands expanded to challenge the basic tenets of education in Chile, calling for recentralization of municipal schools, re-establishment of public schools as the central pillar of the educational system, an end to “profit” in higher education, and free quality education for all. Furthermore, the student movement broke new ground by raising broader issues of inequality and progressive taxation. It framed problems with the educational system as symptomatic of a development model that perpetuated extreme inequality. In line with this diagnosis, when the government dismissed their education demands as too costly, the students countered that business and the rich should pay higher taxes (Jackson 2012, interview). In addition to mass participation in protests, the student movement received critical support from public opinion. According to CEP, 82% supported student demands, 64% approved of strikes and demonstrations, and close to 70% rejected using police to vacate buildings occupied by students. Meanwhile, support for the government fell precipitously. A July poll indicated that 81% of Chileans considered that Minister of Education Lavín, previously one of the right’s most popular politicians, had failed to solve the conflict.^52 Polls in September reported 76% disapproval of the government’s handling of the conflict.^53 By November, the government’s approval ratings sunk to 22%, while disapproval reached 62% (CEP 2012:54)—by far the worst figures reported since the transition to democracy. Public discontent created additional pressure to address student demands.^54

<!-- ¶ 105 -->
## Education Policy

Incessant, massive demonstrations drove the government to propose education reforms that deviated markedly from the right’s traditional agenda (Piñera 2010).^55 Piñera initially sought to increase pre-school funding and improve the quality of education while maintaining the existing educational system largely untouched. However, student protests instigated a debate on free higher education, as well as broader reforms regarding student loans, scholarships, non-profit universities (which were accused of sheltering for-profit business), and structural reforms including recentralization of the education system. Chile had strikingly expensive tuition and low public spending on higher education, which focused disproportionally on loans relative to scholarships (OECD 2009). A large share of students graduating with college degrees could not pay back their debt (Urzúa 2012). In July 2011, after the first massive wave of protests, Piñera announced the Great National Agreement for Education (GANE) with a public appeal to “end the takeovers and protests.”^56 Beyond expanding kindergarten services for low-income families, GANE aimed to directly address student demands by including a 4 billion dollar education fund, a new agency to monitor profit-related university activities, more scholarships with higher funding per student, and better terms of credit for loans. Students and allies nevertheless rejected GANE, arguing that it did not satisfy their demands for free education. Continued protest raised the salience of the debate, which the students helped to make broadly-accessible to society, and further damaged Piñera’s popularity. In response, the

<!-- ¶ 106 -->
(^52) _Nación_ , 7/5/2011. (^53) [http://www.adimark.cl/es/estudios/archivo.asp?id=130](http://www.adimark.cl/es/estudios/archivo.asp?id=130) (^54) _Mercurio_ 6/14/2011. (^55) On education, see Pribble 2013. (^56) _Tercera_ 7/5/2011

<!-- ¶ 107 -->
21

<!-- ¶ 108 -->
government established new channels of communication with the movement. A new education minister was appointed to facilitate dialogue and forge a common agenda, and the student movement was granted improved access to high-level policymakers. Overall, student protest elicited important policy responses, despite falling short of student demands. In 2012, the government submitted two bills to improve the terms of student credit for higher education and to refinance student debt. With these reforms, interest rates dropped from 6% to 2%, and students are now expected to repay no more than 10% of their income after graduation. At the same time, the government effected a major increase in scholarships from about 120,000 in 2009 to 400,000 by 2014, reaching roughly 35% of students, and public spending jumped from 14.6% to 34.6% of total spending in higher education between 2010 and

<!-- ¶ 109 -->
2014.^57 These initiatives entailed a sharp departure from the status quo. Sustained student mobilization paved the way for additional far-reaching reforms when the center-left returned to power under Bachelet (2014-present). Piñera and the _Coalición_ had rejected student demands for free education and recentralization of the system, an issue that divided politicians within the main coalitions. After extensive debate, however, Congress enacted free higher education for eligible students within the poorest 60% of the population (conditional on academic performance) as well as measures recentralizing aspects of the education system.

<!-- ¶ 110 -->
## Direct Taxation

Student protest not only compelled the government to initiate substantial education reform, but also pushed Piñera to pursue additional tax increases. Student mobilization forced progressive direct taxation back onto the agenda, despite the executive’s promise that the 2010 corporate tax increase would be temporary. As was also true in 2010, political considerations took precedence over advice from conservative technocrats—Piñera’s own Finance Minister resisted the 2012 tax reform on the grounds that it could undermine growth (interview: Executive-advisor 2012). Social mobilization both created major new revenue needs and precluded recourse to broad-based taxes. By July 2011 it was clear that restoring social peace and improving the government’s abysmal approval ratings required more generous public assistance for students. Although many _Coalición_ members maintained that education initiatives did not require higher taxation, concern over fiscal discipline prevailed—social-policy commitments made during Piñera’s first years contributed to budgetary pressures (interview: Executive-advisor 2012). Moreover, the executive recognized that “facing the social demand for more public financing of higher education, the only possibility was to go for the corporate tax,” (ibid.). Given the student movement’s denunciation of Chile’s “scandalous” levels of inequality, any other proposal likely would have exacerbated social conflict and public opprobrium. Electoral incentives in this case operated primarily on the spending side of the fiscal equation, in contrast to the more atypical 2010 reform where the executive anticipated a boost in public support from raising the corporate tax. With public attention focused on education, the electoral logic operated “not with the tax reform [itself], but with the tax reform as an instrument for [financing] the educational reform,” (interview, Executive Advisor 2012). However, the student movement’s remarkable direct engagement on taxation played an important role in intensifying these incentives. By demanding that the government tax the rich to finance education reform, the students raised the public salience of progressive taxation, which in turn

<!-- ¶ 111 -->
(^57) Mineduc 2015; Diario de Sesión, Legislatura 360, Sesión 68, 08/08/2012

<!-- ¶ 112 -->
22

<!-- ¶ 113 -->
pressured politicians from the center of the political spectrum to support such initiatives. These politicians included a minority current within the _Coalición_ as well as conservative-leaning members of the _Concertación_ who had been reluctant to pursue redistribution through taxation: “All the actors have modified their positioning, under the pressure to represent society—what happens on taxation is due to the social mobilization,” (interview, Auth 2012). More importantly, the students’ call for taxing the rich blew the lid off of the debate on tax reform in Chile. Whereas increasing the corporate tax to 20% was the maximal demand voiced by mainstream political actors in previous years, the _Concertación_ and two left-wing opposition parties issued a joint proposal that included overhauling the core business-friendly feature of Chile’s tax system: deferred taxation of reinvested capital income. The Piñera administration and the business sector reacted to these unwelcome developments and the students’ continued mobilizational power by recalibrating their strategic assessments. Rather than trying to hold the line against tax increases, which was judged a losing battle, they pursued the second-best option: minimizing the scope of tax reform and ending the debate as quickly as possible to preclude more radical demands from gaining traction (2012 interviews: Executive Advisor, CPC-A, LyD, CPC-B). As an industrial-association informant explained: “What we would have preferred was for the discussion not to be opened. Given that it was opened, we would like to close it quickly,” (SOFOFA 2012). After extended internal debate and consultations with business, the executive branch announced its decision to permanently set the corporate tax at 20%, along with multiple measures to reduce income-tax avoidance, as part of its May 2012 bill for financing educational reform. Social mobilization thereby pressured the right to initiate Chile’s most substantial direct tax increase since the 1990 reform. Essentially all of the reform’s anticipated revenue yield, 0.4% GDP, stemmed from taxes that targeted the _Coalición’s_ core business constituency. Informants of all types agreed that Piñera never would have proposed tax increases beyond the temporary 2010 measures had the student movement not succeeded in orchestrating sustained mobilization and building public support for their demands (2012 interviews: Auth, Macaya, CPC-B). Moreover, the student movement had a profound impact on tax politics in the longer run, dramatically broadening the scope of debate on progressive taxation and paving the way for Bachelet’s far-reaching, equity-enhancing 2014 tax reform. While the 2012 reform showcases a critical role for social movements in demanding progressive taxation, subsequent developments under Bachelet are consistent with our theory that social policy expansion typically entails greater engagement with popular sectors than taxing economic elites. The student movement sustained mobilization on education policy but did not remain active on taxation. Taxation moved back toward the realm of elite politics, allowing business and the right to win important concessions on the 2014 tax reform (Fairfield 2015b).

<!-- ¶ 114 -->
## 6. Conclusion

Measures undertaken by conservative governments in Chile and in Mexico lend support to our framework for explaining redistributive reforms. Succinctly, electoral competition led incumbents to expand social programs, while powerful organized business responded to attempts at increasing direct taxation by seeking to curtail their scope while accepting modest reforms when concern over fiscal discipline prevailed or when strategic calculations regarding longer- term interests encouraged support for the incumbent. Popular mobilization put stronger pressures on governments to both expand social policy and raise progressive taxes to fund them, yielding reforms that deviated more markedly from the right’s agenda.

<!-- ¶ 115 -->
23

<!-- ¶ 116 -->
Two main implications for future research on the politics of redistribution emerge from our analysis. First, our framework highlights the importance of simultaneously analyzing electoral dynamics and organized interests—business and social movements—when studying redistribution. Whereas previous studies tend to stress the importance of one of these factors or the other, we advocate explicitly integrating them. Examining strategic calculations made by policymakers and organized actors in response to both electoral incentives and assessments of the balance of power among societal actors is critical. Understanding the different ways in which electoral incentives and pressure from organized actors operate in the tax and social- policy arenas and how politics interact across the two arenas is also imperative. Second, analyzing social policy expansion and progressive tax initiatives by right–wing governments may contribute to our understanding of the dilemmas conservative parties face when seeking to construct electoral coalitions with low-income sectors without alienating upper- income core constituencies (Gibson 1996). A growing comparative literature on this topic describes various strategies for resolving this dilemma that do not entail meaningful redistribution, including provision of rudimentary welfare services to the poor through non-state organizations indirectly linked to conservative parties (Thachil 2014), and segmented linkage strategies whereby conservative parties provide inexpensive clientelistic benefits for low-income voters that do not conflict with programmatic representation for the upper-income core constituency (Luna 2014). In contrast, we observe non-discretionary, state-based social programs embraced by conservative governments after winning office, financed in some cases by taxing their core constituencies, with the goal of consolidating electoral support from the poor or maintaining social peace in the context of social mobilization. Analyzing when conservative parties choose to promulgate non-discretionary benefits for low-income voters and how they reconcile those initiatives with the non-redistributive, low-tax preferences of upper-income constituencies, as well as the conditions under which the latter view compromise as desirable, is fundamental for understanding the politics of redistribution in highly unequal societies.

<!-- ¶ 117 -->
## Acknowledgments

We thank Matthew Carnes, Robert Kaufman, and three anonymous reviewers for detailed comments on earlier versions of this work. We are also grateful to the editors of _Comparative Political Studies,_ A.E. Charman, and Gustavo Macías Flores.

<!-- ¶ 118 -->
## Supplementary Materials

The appendix, “Evidence and Alternative Explanations: A Bayesian Approach to Process Tracing,” is available at [http://tashafairfield.wixsite.com/home/articles](http://tashafairfield.wixsite.com/home/articles)_._

<!-- ¶ 119 -->
24

<!-- ¶ 120 -->
## References

Anria, Santiago, and Sara Niedzwiecki. 2016. “Social Movements and Social Policy: the Bolivian Renta Dignidad.” _Studies in Comparative International Development_ 51(3):308-27. Ansell, Ben, and David Samuels. 2014. _Inequality and Democratization: an Elite-Competition Approach_. New York: Cambridge University Press. Bartels, Larry. 2008. _Unequal Democracy_. Princeton: Princeton University Press. Beramendi, Pablo, Silja Hausermann, Herbert Kitschelt, and Hanspeter Kriesi. 2015. _The Politics of Advanced Capitalism._ New York: Cambridge University Press. Birdsall, Nancy, Carol Graham, and Stefano Pettinato. 2000. “Stuck in the Tunnel: Is Globalization Muddling the Middle Class?” Center of Social and Economic Dynamics Working Paper #14. Centro de Estudios Públicos (CEP). 2012. “Estudio Nacional de Opinión Pública No 68.” Santiago, Chile. Centro de Estudios Económicos del Sector Privado (CEESP) 2007a. “Acerca de la Tasa Única de Impuesto.” [http://www.ccpm.org.mx/avisos/ceespmarzoimpuesto.pdf](http://www.ccpm.org.mx/avisos/ceespmarzoimpuesto.pdf) _____. 2007b. “Acerca de la Competitividad y la Política Fiscal.” [http://www.ccpm.org.mx/avisos/ceesp3septiembrepoliticafiscal.pdf](http://www.ccpm.org.mx/avisos/ceesp3septiembrepoliticafiscal.pdf) Centro de Estudios Públicos (CEP). 2012. “Estudio Nacional de Opinión Pública No 68.” Santiago, Chile. Consejo Coordinador Empresarial (CCE). 2010. “Informe 2007-2010.” Mexico. Comisión Económica para América Latina y el Caribe (CEPAL). 2006. “Anuario Estadístico de América Latina y el Caribe.” Santiago, Chile. [http://www.cepal.org](http://www.cepal.org) Confederación de la Producción y del Comercio (CPC). 2012. “Memoria 2011-2012: Laboral.” [http://www.cpc.cl/wp-content/uploads/2012/06/32-Laboral_2012.pdf](http://www.cpc.cl/wp-content/uploads/2012/06/32-Laboral_2012.pdf) Culpepper, Pepper. 2011. _Quiet Politics and Business Power._ New York: Cambridge University Press. Delamaza, Gonzalo. 2010. “La Disputa por la Participación en la Democracia Elitista Chilena,” _Latin American Research Review_ 45: 274-97. Donoso, Sofía. 2013. “Dynamics of Change in Chile: Explaining the Emergence of the 2006 Pingüino Movement,” _Journal of Latin American Studies_ 45:1-29. Elizondo, Carlos. 2014. “Progresividad y eficacia del gasto public en México.” Wilson Center Working Paper. Ewig, Christina. 2016. “Reform and Electoral Competition: Convergence Toward Equity in Latin American Health Sectors.” _Comparative Political Studies_ 49(2):184-218. Fairfield, Tasha. 2015 a. _Private Wealth and Public Revenue in Latin America: Business Power and Tax Politics._ New York: Cambridge University Press. –––––. 2015b. “Structural Power in Comparative Political Economy: Perspectives from Policy Formulation in Latin America,” _Business and Politics_ 17(3): 411 - 442. Fairfield, Tasha and Michel Jorratt. 2015. “Top Income Shares, Business Profits, and Effective Tax Rates in Contemporary Chile.” _Review of Income and Wealth._ doi:10.1111/roiw.12196. Garay, Candelaria. 2007. “Social Policy and Collective Action: Unemployed Workers, Community Associations, and Protest in Argentina,” _Politics & Society_ 35( 2 ): 301 - 28. _____. 2016. _Social Policy Expansion in Latin America_. New York: Cambridge University Press. Gibson, Edward. 1996. _Class and Conservative Parties, Argentina in Comparative Perspective._ Baltimore: Johns Hopkins University Press.

<!-- ¶ 121 -->
25

<!-- ¶ 122 -->
_____. 1997. “The Populist Road to Market Reform: Policy and Electoral Coalitions in Mexico and in Argentina,” _World Politics_ 49: 339 - 60. Goñi, Edwin, Humberto López , and Luis Servén. 2011. “Fiscal Redistribution and Income Inequality in Latin America.” _World Development_ 39 (9):1558–69. Graetz, Michael, and Ian Shapiro. 2005. _Death by a Thousand Cuts._ Princeton University Press. Hacker, Jacob, and Paul Pierson. 2002. “Business Power and Social Policy: Employers and the Formation of the American Welfare State.” _Politics and Society_ 30: 277 – 325. _____. 2010. “Winner-Take-All Politics.” _Politics and Society_ 38:152- 204. Haggard, Stephan, and Robert Kaufman. 2008. _Development, Democracy, and Welfare States: Latin America, East Asia, and Eastern Europe._ Princeton University Press. Haggard, Stephan, Robert Kaufman, and James Long. 2013. “Income, Occupation, and Preferences for Redistribution in the Developing World,” _Studies in Comparative International Development_ 48 (2): 113 - 140. Hall, Peter. 2014. “How Growth Regimes Evolve in the Developed Democracies,” paper presented to the Europeanists Conference. Huber, Evelyn and John D. Stephens. 2012. _Democracy and the Left. Social Policy and Inequality in Latin America._ Chicago: Chicago University Press. Kaufman, Robert, and Segura-Ubiergo. 2001. “Globalization, Domestic Politics, and Social Spending in Latin America,” _World Politics_ 53 (4):553-587. Korpi, Walter. 2006. “Power Resources and Employer-Centered Approaches in Explanations of Welfare States and Varieties of Capitalism: Protagonists, Consenters, and Antagonists,” _World Politics_ 58(2): 168 - 206. Levitsky, Steven and Kenneth Roberts. 20 1 1. “Latin America’s Left Turn, A Conceptual and Theoretical Overview” in _Latin America’s Left Turn: Political Diversity and the Search for Alternatives,_ Baltimore: Johns Hopkins University Press. Lieberman, Evan, and Gwyneth McClendon. 2013. “The Ethnicity−Policy Preference Link in Sub-Saharan Africa,” _Comparative Political Studies_ 46:574. Lujambio, Alonso. 2001. “Democratization through Federalism? The National Action Party Strategy, 1939-1995,” in Kevin Middlebrook, ed. _Party Politics and the Struggle for Democracy in Mexico_. La Jolla: Center for U.S.-Mexican Studies, USDC. Luna, Juan Pablo. 2014. _Segmented Representation. Political Party Strategies in Unequal Democracies._ Oxford University Press. Luna, Juan Pablo, and David Altman. 2011. “Uprooted but Stable: Chilean Parties and the Concept of Party System Institutionalization.” _Latin American Politics and Society_ 53 (2): 1 – 28. Lupu, Noam and Jonas Pontusson. 2011. “The Structure of Inequality and the Politics of Redistribution,” American Political Science Review 105(2): 316 - 336. Magaloni, Beatriz. 2006. _Voting for Autocracy: Hegemonic Party Survival and its Demise in Mexico._ Cambridge University Press. Magar, Eric, Vidal Romero, and Jeffrey Timmons. 2009. “The Political Economy of Fiscal Reforms in Latin America: Mexico.” [http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1963863](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1963863) Mares, Isabela. 2003. _The Politics of Social Risk: Business and Welfare State Development._ New York: Cambridge University Press. Martin, Cathy Jo, and Duane Swank 2012. _The Political Construction of Business Interests._ Cambridge University Press.

<!-- ¶ 123 -->
26

<!-- ¶ 124 -->
McGuire, James. 2010. _Wealth, Health and Democracy in East Asia and Latin America._ New York: Cambridge University Press. MINEDUC. 2015. _Serie Evidencias_ no 31. Santiago, Chile. Ortiz, Mauricio. 2006. _El Seguro Popular. Una crónica de la democracia._ Mexico: Fondo de Cultura Económica. Piñera, Sebastián. 2010. “Programa de Gobierno para el Cambio, el Futuro, y la Esperanza.” Chile. Pribble, Jennifer. 2013. _Welfare and Party Politics in Latin America_. New York: Cambridge University Press Romero, Vidal. 2015. “The Political Economy of Progressive Tax Reforms in Mexico.” In James Mahon, Marcelo Bergman, and Cynthia Arnson, Eds., _Progressive Tax Reform and Equality in Latin America,_ Wilson Center. Schneider, Ben. 2004. _Business Politics and the State in Twentieth-Century Latin America._ New York: Cambridge University Press. _____. 2013. _Hierarchical Capitalism in Latin America._ Cambridge University Press. Schamis, Hector. 1999. “Distributional Coalitions and the Politics of Economic Reform in Latin America.” _World Politics_ 51(2): 236 - 68. Secretareia de Hacienda y Crédito Público (SHCP). 2011. “El Impuesto Empresarial a Tasa Única.” Mexico. Swenson, Peter. 1991. _Capitalists against Markets._ New York: Oxford University Press. Teichman, Judith 2001. _The Politics of Freeing Markets in Latin America_. Chapel Hill: University of North Carolina Press. Thachil, Tariq. 2014. _Elite Parties, Poor Voters: How Social Services Win Votes in India._ New York: Cambridge University Press. Trumbull, Gunnar. 2012. _Strength in Numbers: The Political Power of Weak Interests._ Harvard University Press. Unda, Mónica. 2015. “The Battle for a Superficial Reform: Congressional Approval Process for Mexico’s 2013 Tax Reform.” Presented at the Latin American Studies Association conference, Puerto Rico. Weyland, Kurt. 1996. _Democracy Without Equity: Failures of Reform in Brazil._ Pittsburgh: University of Pittsburgh Press.

<!-- ¶ 125 -->
## Interviews

Auth, Pepe. PPD deputy. Interviewed by Tasha Fairfield, 6/25/2012, Santiago. ABIF. Banking sector informant. Interviewed by Tasha Fairfield, 4/25/2011, Santiago. Coloma, Juan Antonio. UDI senator. Interviewed by Tasha Fairfield, 4/4,/2011, Santiago. Business-association informant. Interviewed by Candelaria Garay, 2006, Mexico City. Business-association informant, Interviewed by Tasha Fairfield, 2011. Santiago. CNC. National Chamber of Commerce. Interviewed by Tasha Fairfield, 5/6/2011, Santiago. CPC-A. General manager, Production and Commerce Confederation. Interviewed by Tasha Fairfield, 4/26/2011; 6/26/2012, Santiago. CPC-B. Former manager, Production and Commerce Confederation. Interviewed by Tasha Fairfield, 7/5/2012. Santiago. Executive Advisor. Piñera administration. Interviewed by Tasha Fairfield, 4/27/2011; 6/26/2012, Santiago.

<!-- ¶ 126 -->
27

<!-- ¶ 127 -->
Jackson, Georgio. Student movement leader. Interviewed by Tasha Fairfield, 7/11/2012, Santiago. Larraín, Carlos. RN Senator. Interviewed by Tasha Fairfield, 5/11/ 2011 , Santiago. Laurell, Asa Cristina. Secretary of Health, Government of Mexico City. Interviewed by Candelaria Garay, 5/8/ 2007 , Mexico City.. LyD. Libertad y Desarrollo informant. Interviewed by Tasha Fairfield, 4/2/2011; 6/25/2012, Santiago. Macaya, Javier. UDI deputy. Interviewed by Tasha Fairfield, 7/3/2012, Santiago. Mining Ministry. Government informant. Interviewed by Tasha Fairfield, 4/28/2011, Santiago. Novoa, Jovino. UDI senator. Interviewed by Tasha Fairfield, 5/ 11 / 2011 , Santiago. Pérez- Bejerano, Marta. PRD Politician. Interviewed by Tasha Fairfield, 5/15/2007. Mexico City. PRD Social Policy Expert. Interviewed by Candelaria Garay, 5/5/2007, Mexico City. Silva, Ernesto. UDI deputy. Interviewed by Tasha Fairfield, 5/4/2011, Santiago. SNA. Agricultural association. Interviewed by Tasha Fairfield, 5/6/2011, Santiago. Sofofa. Industry association staff member. Interviewed by Tasha Fairfield, 6/28/2012, Santiago. Sonami. Mining association staff member. Interviewed by Tasha Fairfield, 5/2/2011, Santiago. Ulloa, Jorge. UDI deputy. Interviewed by Tasha Fairfield, 5/ 4 / 2011 , Santiago. Vega-Galina, Roberto. Workers’ National Union. Interviewed by Candelaria Garay, 9/26/2006. Mexico City. Zaldívar, Andrés. PDC senator. Interviewed by Tasha Fairfield, 5/9/ 2011 , Santiago.

