<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-22">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Why Inequalities Persist: Parties’ (Non)Responses to Economic Inequality, 1970–2020 – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-446ba4faaf7890b510536beef49c91e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Why Inequalities Persist: Parties’ (Non)Responses to Economic Inequality, 1970–2020 – Annotated Bibliography">
<meta property="og:description" content="Horn, A., Haselmayer, M., &amp; Klüser, K. J. (2026). Why inequalities persist: Parties’ (non)responses to economic inequality, 1970–2020. American Political Science Review, 120(1), 346–364. https://doi.org/10.1017/S0003055425100907">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#introdução-reações-programáticas-à-desigualdade-pp.-346347" id="toc-introdução-reações-programáticas-à-desigualdade-pp.-346347" class="nav-link" data-scroll-target="#introdução-reações-programáticas-à-desigualdade-pp.-346347"><span class="header-section-number">1</span> Introdução: Reações Programáticas à Desigualdade (pp.&nbsp;346–347)</a>
  <ul class="collapse">
  <li><a href="#o-puzzle-de-partida-e-a-tensão-na-literatura-14" id="toc-o-puzzle-de-partida-e-a-tensão-na-literatura-14" class="nav-link" data-scroll-target="#o-puzzle-de-partida-e-a-tensão-na-literatura-14"><span class="header-section-number">1.1</span> O puzzle de partida e a tensão na literatura [§1–§4]</a></li>
  <li><a href="#contribuição-teórica-nível-versus-mudança-58" id="toc-contribuição-teórica-nível-versus-mudança-58" class="nav-link" data-scroll-target="#contribuição-teórica-nível-versus-mudança-58"><span class="header-section-number">1.2</span> Contribuição teórica: nível versus mudança [§5–§8]</a></li>
  <li><a href="#contribuição-empírica-nova-medida-de-igualdade-econômica-911" id="toc-contribuição-empírica-nova-medida-de-igualdade-econômica-911" class="nav-link" data-scroll-target="#contribuição-empírica-nova-medida-de-igualdade-econômica-911"><span class="header-section-number">1.3</span> Contribuição empírica: nova medida de igualdade econômica [§9–§11]</a></li>
  </ul></li>
  <li><a href="#por-que-partidos-reagem-a-mudanças-não-a-níveis-de-desigualdade-pp.-347351" id="toc-por-que-partidos-reagem-a-mudanças-não-a-níveis-de-desigualdade-pp.-347351" class="nav-link" data-scroll-target="#por-que-partidos-reagem-a-mudanças-não-a-níveis-de-desigualdade-pp.-347351"><span class="header-section-number">2</span> Por que Partidos Reagem a Mudanças, Não a Níveis de Desigualdade (pp.&nbsp;347–351)</a>
  <ul class="collapse">
  <li><a href="#por-que-partidos-não-respondem-revisão-da-literatura-cética-1215" id="toc-por-que-partidos-não-respondem-revisão-da-literatura-cética-1215" class="nav-link" data-scroll-target="#por-que-partidos-não-respondem-revisão-da-literatura-cética-1215"><span class="header-section-number">2.1</span> Por que partidos não respondem: revisão da literatura cética [§12–§15]</a></li>
  <li><a href="#por-que-partidos-respondem-responsividade-programática-1618" id="toc-por-que-partidos-respondem-responsividade-programática-1618" class="nav-link" data-scroll-target="#por-que-partidos-respondem-responsividade-programática-1618"><span class="header-section-number">2.2</span> Por que partidos respondem: responsividade programática [§16–§18]</a></li>
  <li><a href="#os-três-mecanismos-visibilidade-mobilização-e-viés-do-status-quo-1925" id="toc-os-três-mecanismos-visibilidade-mobilização-e-viés-do-status-quo-1925" class="nav-link" data-scroll-target="#os-três-mecanismos-visibilidade-mobilização-e-viés-do-status-quo-1925"><span class="header-section-number">2.3</span> Os três mecanismos: visibilidade, mobilização e viés do status quo [§19–§25]</a></li>
  <li><a href="#heterogeneidade-entre-países-2628" id="toc-heterogeneidade-entre-países-2628" class="nav-link" data-scroll-target="#heterogeneidade-entre-países-2628"><span class="header-section-number">2.4</span> Heterogeneidade entre países [§26–§28]</a></li>
  </ul></li>
  <li><a href="#novos-dados-conceitos-de-igualdade-partidária-versus-medidas-existentes-pp.-351352" id="toc-novos-dados-conceitos-de-igualdade-partidária-versus-medidas-existentes-pp.-351352" class="nav-link" data-scroll-target="#novos-dados-conceitos-de-igualdade-partidária-versus-medidas-existentes-pp.-351352"><span class="header-section-number">3</span> Novos Dados: Conceitos de Igualdade Partidária versus Medidas Existentes (pp.&nbsp;351–352)</a>
  <ul class="collapse">
  <li><a href="#o-problema-de-mensuração-dos-estudos-precedentes-2933" id="toc-o-problema-de-mensuração-dos-estudos-precedentes-2933" class="nav-link" data-scroll-target="#o-problema-de-mensuração-dos-estudos-precedentes-2933"><span class="header-section-number">3.1</span> O problema de mensuração dos estudos precedentes [§29–§33]</a></li>
  <li><a href="#o-conceito-de-igualdade-econômica-de-classe-34" id="toc-o-conceito-de-igualdade-econômica-de-classe-34" class="nav-link" data-scroll-target="#o-conceito-de-igualdade-econômica-de-classe-34"><span class="header-section-number">3.2</span> O conceito de igualdade econômica de classe [§34]</a></li>
  </ul></li>
  <li><a href="#crowdcoding-de-conceitos-de-igualdade-em-12-países-pp.-353354" id="toc-crowdcoding-de-conceitos-de-igualdade-em-12-países-pp.-353354" class="nav-link" data-scroll-target="#crowdcoding-de-conceitos-de-igualdade-em-12-países-pp.-353354"><span class="header-section-number">4</span> Crowdcoding de Conceitos de Igualdade em 12 Países (pp.&nbsp;353–354)</a>
  <ul class="collapse">
  <li><a href="#pipeline-de-coleta-e-validação-3540" id="toc-pipeline-de-coleta-e-validação-3540" class="nav-link" data-scroll-target="#pipeline-de-coleta-e-validação-3540"><span class="header-section-number">4.1</span> Pipeline de coleta e validação [§35–§40]</a></li>
  </ul></li>
  <li><a href="#desigualdade-econômica-escolhas-conceituais-pp.-354355" id="toc-desigualdade-econômica-escolhas-conceituais-pp.-354355" class="nav-link" data-scroll-target="#desigualdade-econômica-escolhas-conceituais-pp.-354355"><span class="header-section-number">5</span> Desigualdade Econômica: Escolhas Conceituais (pp.&nbsp;354–355)</a>
  <ul class="collapse">
  <li><a href="#limitações-das-medidas-existentes-e-a-escolha-do-share-dos-50-inferiores-4144" id="toc-limitações-das-medidas-existentes-e-a-escolha-do-share-dos-50-inferiores-4144" class="nav-link" data-scroll-target="#limitações-das-medidas-existentes-e-a-escolha-do-share-dos-50-inferiores-4144"><span class="header-section-number">5.1</span> Limitações das medidas existentes e a escolha do share dos 50% inferiores [§41–§44]</a></li>
  </ul></li>
  <li><a href="#dados-e-métodos-pp.-354356" id="toc-dados-e-métodos-pp.-354356" class="nav-link" data-scroll-target="#dados-e-métodos-pp.-354356"><span class="header-section-number">6</span> Dados e Métodos (pp.&nbsp;354–356)</a>
  <ul class="collapse">
  <li><a href="#variável-dependente-independentes-controles-e-especificação-do-modelo-4552" id="toc-variável-dependente-independentes-controles-e-especificação-do-modelo-4552" class="nav-link" data-scroll-target="#variável-dependente-independentes-controles-e-especificação-do-modelo-4552"><span class="header-section-number">6.1</span> Variável dependente, independentes, controles e especificação do modelo [§45–§52]</a></li>
  </ul></li>
  <li><a href="#resultados-pp.-355360" id="toc-resultados-pp.-355360" class="nav-link" data-scroll-target="#resultados-pp.-355360"><span class="header-section-number">7</span> Resultados (pp.&nbsp;355–360)</a>
  <ul class="collapse">
  <li><a href="#respostas-a-níveis-de-desigualdade-5358" id="toc-respostas-a-níveis-de-desigualdade-5358" class="nav-link" data-scroll-target="#respostas-a-níveis-de-desigualdade-5358"><span class="header-section-number">7.1</span> Respostas a níveis de desigualdade [§53–§58]</a></li>
  <li><a href="#respostas-a-mudanças-de-desigualdade-5964" id="toc-respostas-a-mudanças-de-desigualdade-5964" class="nav-link" data-scroll-target="#respostas-a-mudanças-de-desigualdade-5964"><span class="header-section-number">7.2</span> Respostas a mudanças de desigualdade [§59–§64]</a></li>
  <li><a href="#resumo-dos-resultados-e-robustez-6566" id="toc-resumo-dos-resultados-e-robustez-6566" class="nav-link" data-scroll-target="#resumo-dos-resultados-e-robustez-6566"><span class="header-section-number">7.3</span> Resumo dos resultados e robustez [§65–§66]</a></li>
  </ul></li>
  <li><a href="#análises-adicionais-pp.-360361" id="toc-análises-adicionais-pp.-360361" class="nav-link" data-scroll-target="#análises-adicionais-pp.-360361"><span class="header-section-number">8</span> Análises Adicionais (pp.&nbsp;360–361)</a>
  <ul class="collapse">
  <li><a href="#welfare-states-indicadores-alternativos-salários-reais-e-heterogeneidade-6772" id="toc-welfare-states-indicadores-alternativos-salários-reais-e-heterogeneidade-6772" class="nav-link" data-scroll-target="#welfare-states-indicadores-alternativos-salários-reais-e-heterogeneidade-6772"><span class="header-section-number">8.1</span> Welfare states, indicadores alternativos, salários reais e heterogeneidade [§67–§72]</a></li>
  <li><a href="#ganhos-do-top-1-e-fim-da-expansão-7377" id="toc-ganhos-do-top-1-e-fim-da-expansão-7377" class="nav-link" data-scroll-target="#ganhos-do-top-1-e-fim-da-expansão-7377"><span class="header-section-number">8.2</span> Ganhos do top 1% e fim da expansão [§73–§77]</a></li>
  <li><a href="#interpretação-substantiva-7882" id="toc-interpretação-substantiva-7882" class="nav-link" data-scroll-target="#interpretação-substantiva-7882"><span class="header-section-number">8.3</span> Interpretação substantiva [§78–§82]</a></li>
  </ul></li>
  <li><a href="#conclusão-pp.-361364" id="toc-conclusão-pp.-361364" class="nav-link" data-scroll-target="#conclusão-pp.-361364"><span class="header-section-number">9</span> Conclusão (pp.&nbsp;361–364)</a>
  <ul class="collapse">
  <li><a href="#o-efeito-de-catraca-8388" id="toc-o-efeito-de-catraca-8388" class="nav-link" data-scroll-target="#o-efeito-de-catraca-8388"><span class="header-section-number">9.1</span> O efeito de catraca [§83–§88]</a></li>
  <li><a href="#contribuição-para-o-debate-8994" id="toc-contribuição-para-o-debate-8994" class="nav-link" data-scroll-target="#contribuição-para-o-debate-8994"><span class="header-section-number">9.2</span> Contribuição para o debate [§89–§94]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">10</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Why Inequalities Persist: Parties’ (Non)Responses to Economic Inequality, 1970–2020</h1>
<p class="subtitle lead">Horn, A., Haselmayer, M., &amp; Klüser, K. J. (2026). Why inequalities persist: Parties’ (non)responses to economic inequality, 1970–2020. <em>American Political Science Review</em>, <em>120</em>(1), 346–364. https://doi.org/10.1017/S0003055425100907</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Political Economy</div>
    <div class="quarto-category">Comparative Politics</div>
    <div class="quarto-category">Inequality</div>
    <div class="quarto-category">Party Politics</div>
    <div class="quarto-category">Welfare State/Social Policy</div>
    <div class="quarto-category">Western Europe</div>
    <div class="quarto-category">2026</div>
    <div class="quarto-category">2020s</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Informações Técnicas e BibTeX
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>Última atualização: 2026-05-22
Modelo: Perplexity — Claude Sonnet 4.6 Thinking
Prompt Version: v17.4 · 2026-05-13
Gerado em: 2026-05-22T21:37:00-03:00
Ocasião da Leitura:</code></pre>
<p><strong>Entrada BibTeX → Horn-etal2026</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">Horn</span>-<span class="ot">etal2026</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>  = {Horn, Alexander and Haselmayer, Martin and Kl{<span class="ch">\"</span>u}ser, K. Jonathan},</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>   = {Why Inequalities Persist: Parties' (Non)Responses to Economic</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>             Inequality, 1970--2020},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>    = {2026},</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">journal</span> = {American Political Science Review},</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">volume</span>  = {120},</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">number</span>  = {1},</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span>   = {346--364},</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="dt">doi</span>     = {10.1017/S0003055425100907},</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<hr>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.4</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A pergunta é formulada com clareza nas primeiras linhas do abstract. A premissa central é que os estudos existentes não distinguem adequadamente entre <em>níveis</em> e <em>mudanças</em> de desigualdade, nem separam igualdade econômica de igualdade de direitos — o que contamina as inferências. O ponto mais vulnerável desta formulação é que a pergunta assume que a diferenciação nível/variação é a chave para reconciliar a literatura, sem considerar que os mecanismos causais subjacentes podem ser endógenos uns aos outros.</td>
<td style="text-align: left;">Pergunta central: os partidos respondem programaticamente à desigualdade econômica? Pergunta de natureza causal-explicativa, com componente descritivo (identificar padrões de resposta) e explicativo (por que tais padrões ocorrem). Explicitada pelos autores.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">Os autores diferenciam dois efeitos (nível e mudança) e dois tipos de partido (esquerda/direita), o que gera quatro sub-perguntas. A relação lógica entre elas é aditiva: cada sub-pergunta é necessária para derivar as expectativas teóricas centrais e para compreender por que a desigualdade não é autocorretiva.</td>
<td style="text-align: left;">(1) Os partidos respondem a <em>níveis</em> elevados de desigualdade? (2) Os partidos respondem a <em>aumentos</em> de desigualdade? (3) Existe heterogeneidade partidária esquerda-direita nas respostas? (4) A diferença nível/mudança explica as contradições da literatura prévia? Todas as sub-perguntas se articulam diretamente com a tese de que a desigualdade não é autocorretiva.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno: a coexistência de resultados contraditórios na literatura não é trivialmente atribuível a diferenças de caso ou período — ela deriva de uma contaminação conceitual e de mensuração demonstrável. A contribuição é tanto puzzle explicativo quanto gap descritivo. O puzzle tem generalizabilidade para além dos 12 países estudados, na medida em que o problema de mensuração afeta toda a literatura comparada sobre responsividade partidária.</td>
<td style="text-align: left;">Puzzle explicativo + gap descritivo. Por que a desigualdade persiste mesmo em democracias com partidos de esquerda programáticos? E por que estudos anteriores encontraram evidências contraditórias de resposta da esquerda? O puzzle é avaliado como genuíno: os autores demonstram empiricamente que as medidas previamente usadas (índices econômicos do MARPOR, escala Rile) capturam dimensões múltiplas de igualdade sem distinguir redistribuição econômica de direitos iguais — o que cria aparência de responsividade onde não existe.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">O argumento é construído sobre três pilares cumulativos (visibilidade, mobilização, viés do status quo) e sustentado por evidências empíricas de regressões de efeitos mistos. O <em>claim of discovery</em> é forte no que concerne à resposta ao aumento (bem identificada), mas mais fraco para a ausência de resposta a níveis — que pode refletir a omissão de variáveis de longo prazo ou endogeneidade entre níveis de desigualdade e composição eleitoral da esquerda.</td>
<td style="text-align: left;">Tese: partidos de esquerda respondem a <em>aumentos</em> de desigualdade, mas não a <em>níveis</em> elevados; partidos de direita não respondem em nenhum dos casos. Isso cria um “efeito de catraca” (<em>ratchet effect</em>): a esquerda resiste à piora, mas não combate a desigualdade já entrincheirada. Argumento de natureza causal-explicativa combinada com contribuição metodológica (nova medida).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O desenho é quantitativo com séries temporais comparadas. Para textos desta natureza (análise de manifesto + modelo de efeitos mistos), a validade interna depende criticamente da qualidade da variável dependente (medida de igualdade econômica) e da especificação do modelo. Os autores lidam com ambos de forma cuidadosa, mas os mecanismos teóricos propostos (visibilidade, mobilização, viés do status quo) não são testados diretamente — são inferidos ex-post. <strong>O fichamento cobre a obra inteira (artigo completo, pp.&nbsp;346–364).</strong></td>
<td style="text-align: left;">Estudo quantitativo, cross-national, longitudinal. Dados: 965 manifestos partidários de 12 países OCDE (1970–2020), segmentados em 850.000 quasi-frases. Variável dependente: share de referências positivas à igualdade econômica por manifesto (obtida via <em>crowdcoding</em> no Amazon Mechanical Turk com filtragem por ML). Variáveis independentes: medidas de desigualdade pré-impostos (bottom 50% share, top 1%, razões 90–10 e 90–50, Gini), partidarismo esquerda/direita, turnout, controles partidários e de país. Estimação: regressão linear de efeitos mistos com interceptos aleatórios por partido e país, interação desigualdade × partidarismo.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP é bem documentado e reprodutível (dados arquivados no Harvard Dataverse). O uso de market inequality (pré-impostos e transferências) é justificado para evitar endogeneidade, mas cria uma limitação: não captura a desigualdade <em>percebida</em>, que é o canal teórico relevante nos argumentos de visibilidade e viés do status quo. O crowdcoding via AMT pode introduzir viés de seleção de codificadores (restrição geográfica por IP) e problemas de equivalência funcional entre países com tradições linguísticas distintas.</td>
<td style="text-align: left;">Fenômeno real (desigualdade de renda) → observação via manifestos partidários → coleta (MARPOR API + fontes manuais) → filtragem por classificador de regressão logística (recall ≥ 0.80) → revisão por assistentes de pesquisa → crowdcoding em AMT (5 codificações/unidade, voto majoritário, Krippendorff’s α = 0.72) → operacionalização como share de quasi-frases sobre igualdade econômica por manifesto → desigualdade medida via WID e SWIID. Unidade de análise: partido em eleição. Nível de agregação: party-election. Inferência: correlacional com argumentação causal, sem identificação por variação exógena.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">Os achados sobre resposta a mudanças são robustos a múltiplas especificações. A ausência de resposta a níveis é mais frágil teoricamente — o coeficiente negativo de β₁ (desemphasizing em contextos de alta desigualdade) é plausível mas não permite distinguir entre mecanismo estratégico (adaptação racional) e seleção amostral (esquerda já moderada em contextos desiguais). A contribuição metodológica (nova medida) é o ponto mais sólido e duradouro do artigo.</td>
<td style="text-align: left;"><strong>Empíricos:</strong> (1) partidos de esquerda não respondem a níveis elevados de desigualdade; ao contrário, de-enfatizam igualdade econômica em contextos altamente desiguais; (2) partidos de esquerda respondem positivamente a <em>aumentos</em> de desigualdade (especialmente perda de participação dos 50% mais pobres); (3) nenhum partido responde a ganhos do top 1%; (4) partidos de direita são consistentemente não responsivos. <strong>Metodológicos:</strong> nova medida válida de igualdade econômica de classe (<em>Varieties of Egalitarianism</em>), distinguindo-a de igualdade de direitos; demonstração de que medidas existentes têm correlação ~0.3 com a nova medida.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">(a) <strong>Viés de seleção/composição:</strong> o argumento de que a esquerda abandona os mais pobres em contextos de alta desigualdade poderia refletir mudança endógena na composição do eleitorado da esquerda (terciarização, Häusermann e Kitschelt 2024), não apenas resposta estratégica. (b) <strong>Compatibilidade DGP-claim:</strong> os mecanismos (visibilidade, mobilização, status quo bias) não são testados diretamente; os autores reconhecem isso, mas não delineiam condições falsificadoras. (c) <strong>Confundidores:</strong> o modelo não controla para variações na composição ideológica intrapartidária ao longo do tempo, nem para a influência de organizações externas (sindicatos, movimentos sociais). (d) <strong>SUTVA e independência:</strong> manifestos de eleições próximas em um mesmo país não são independentes; os interceptos aleatórios lidam com parte da não-independência, mas não com dependência temporal serial. (e) <strong>Generalizabilidade:</strong> limitada a 12 democracias OCDE de capitalismo avançado; os próprios autores alertam sobre Europa Oriental e do Sul. (f) <strong>Scope conditions não declaradas:</strong> o argumento pressupõe sistemas partidários com partidos de esquerda programáticos — o que não é universal, inclusive em algumas democracias da amostra em determinados períodos.</td>
<td style="text-align: left;">O artigo responde adequadamente à pergunta dentro de seu desenho, mas as afirmações causais excedem o que o design identifica com força. O argumento de “efeito de catraca” é sugestivo e plausível, mas hipotético em sua forma mais forte.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> (1) os mecanismos (visibilidade, mobilização, status quo bias) não são testados diretamente; (2) generalizabilidade limitada para Europa do Leste e do Sul; (3) foco em manifestos, que podem ser <em>window-dressing</em>; (4) amostra reduzida de estados de bem-estar social-democratas (apenas Dinamarca e Suécia). <br> <strong>Não reconhecidas ou subestimadas:</strong> (1) endogeneidade entre composição eleitoral da esquerda e níveis de desigualdade — a “adaptação” estratégica e a mudança estrutural no eleitorado são observacionalmente equivalentes; (2) a medida de desigualdade pré-impostos não alinha com o canal perceptual teórico (o que os eleitores <em>percebem</em> é desigualdade pós-transferências); (3) o crowdcoding pode ser menos válido para manifestos em idiomas não anglófonos com nuances culturais específicas na codificação de igualdade — o α de Krippendorff varia de 0.6 a 0.85 por país, o que é relevante para países não-anglófonos; (4) o artigo não discute o potencial efeito de composição entre períodos (os partidos de esquerda de 1970 são muito distintos dos de 2020 em composição e eleitorado).</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A moldura teórica articula economia política com teoria cognitiva/comportamental (sistema justification, meritocracy beliefs) e teoria eleitoral (demobilização, competição partidária). A combinação é coerente com o tipo de pergunta, mas a pluralidade de mecanismos não testados diretamente cria um argumento <em>omnibus</em> — em que qualquer resultado negativo nos dados poderia ser explicado por ao menos um dos mecanismos. Isso reduz a falseabilidade da teoria.</td>
<td style="text-align: left;">Traditions: economia política comparada (Pontusson e Rueda 2010; Tavits e Potter 2015); teoria de poder de recursos (Korpi 1983); teoria de transformação de sistemas partidários (Häusermann e Kitschelt 2024); psicologia política da desigualdade (Trump 2018; Mijs 2021; Jost, Banaji e Nosek 2004); agenda-setting e gatekeeping (McCombs 2005; Galtung e Ruge 1965). A coerência ontológica é boa: o argumento é consistentemente racionalista-estratégico com reconhecimento de constrangimentos cognitivos e institucionais.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo com a literatura é amplo e equilibrado. Destacam-se: Pontusson e Rueda (2010) e Tavits e Potter (2015) como estudos de referência a serem corrigidos; Atkinson (1970) para justificar limites do Gini; Solt (2008; 2010) sobre mobilização e desigualdade; Mijs (2021) e Trump (2018) sobre legitimação da desigualdade; Piketty (2020) e Gilens e Page (2014) como contexto do debate público-acadêmico; Häusermann e Kitschelt (2024) sobre transformação da esquerda. O diálogo com a literatura sobre <em>agenda-setting</em> (McCall 2013; Schröder e Vietze 2015) é um ponto positivo que não encontra paralelo na maioria dos artigos desta literatura.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">O artigo é uma contribuição metodológica de primeira ordem para a literatura de economia política comparada: a nova medida <em>Varieties of Egalitarianism</em> provavelmente terá uso independente de seus resultados substantivos. Para a pesquisa do leitor (sistemas de cotas e desigualdade educacional no Brasil), o mecanismo de viés do status quo e o argumento sobre <em>lock-in</em> de desigualdades entrincheiradas são diretamente relevantes — especialmente a ideia de que em contextos de alta desigualdade, os incentivos para resposta redistributiva são estruturalmente enfraquecidos, o que se aplica tanto a partidos quanto, possivelmente, a instituições de acesso à educação. O argumento sobre “efeito de catraca” merece aplicação cuidadosa em contextos não-OCDE.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<hr>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 19%">
<col style="width: 28%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Seção</th>
<th style="text-align: left;">Título / Tema</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Introdução</td>
<td style="text-align: left;">Reações programáticas à desigualdade</td>
<td style="text-align: left;">Apresentação do puzzle e da tese</td>
<td style="text-align: left;">Estabelece a contradição entre a literatura otimista (esquerda responde) e o ceticismo amplo; formula a hipótese de reconciliação via distinção nível/mudança</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção teórica 1</td>
<td style="text-align: left;">Por que partidos não respondem</td>
<td style="text-align: left;">Revisão de literatura — perspectiva cética</td>
<td style="text-align: left;">Mobiliza três tradições (morte da classe, abandono histórico da classe trabalhadora, democracia desigual) para fundar expectativas negativas</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seção teórica 2</td>
<td style="text-align: left;">Por que partidos respondem — respostas programáticas</td>
<td style="text-align: left;">Revisão de literatura — perspectiva otimista</td>
<td style="text-align: left;">Apresenta os estudos de Pontusson-Rueda e Tavits-Potter que encontram responsividade da esquerda como alvo a ser reavaliado</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção teórica 3</td>
<td style="text-align: left;">Por que partidos respondem a mudanças, não a níveis</td>
<td style="text-align: left;">Fundamento teórico central</td>
<td style="text-align: left;">Desenvolve os três mecanismos (visibilidade, mobilização, viés do status quo) que explicam o padrão diferencial; deriva as duas expectativas formais</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Subseção teórica</td>
<td style="text-align: left;">Heterogeneidade entre países</td>
<td style="text-align: left;">Qualificação</td>
<td style="text-align: left;">Antecipa moderadores contextuais (regime de bem-estar, sistema eleitoral, competitividade) a serem tratados na análise de robustez</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção empírica 1</td>
<td style="text-align: left;">Novos dados sobre conceitos de igualdade</td>
<td style="text-align: left;">Contribuição metodológica + análise descritiva</td>
<td style="text-align: left;">Demonstra que medidas existentes conflacionam igualdade econômica com direitos iguais; apresenta a trajetória em U do igualitarismo econômico (1980–2020)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seção empírica 2</td>
<td style="text-align: left;">Crowdcoding em 12 países</td>
<td style="text-align: left;">Descrição do DGP</td>
<td style="text-align: left;">Detalha o pipeline de coleta e validação da variável dependente; justifica a confiabilidade do crowdcoding (α = 0.72)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção empírica 3</td>
<td style="text-align: left;">Escolhas conceituais de desigualdade</td>
<td style="text-align: left;">Justificação da variável independente</td>
<td style="text-align: left;">Argumenta pela superioridade teórica do share dos 50% inferiores sobre o Gini e o top 1% para capturar incentivos eleitorais da esquerda</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seção empírica 4</td>
<td style="text-align: left;">Dados e métodos</td>
<td style="text-align: left;">Especificação do modelo</td>
<td style="text-align: left;">Formaliza o modelo de efeitos mistos com interação desigualdade × partidarismo; justifica o uso de desigualdade de mercado</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção de resultados</td>
<td style="text-align: left;">Resultados principais</td>
<td style="text-align: left;">Análise empírica central</td>
<td style="text-align: left;">Confirma Expectativa 1 (sem resposta a níveis) e Expectativa 2 (resposta da esquerda a aumentos); documenta a exceção do top 1%; apresenta os coeficientes de Table 1 e Figure 2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seção de robustez e análises adicionais</td>
<td style="text-align: left;">Robustez, heterogeneidade e exceção do 1%</td>
<td style="text-align: left;">Qualificação e extensão do argumento</td>
<td style="text-align: left;">Testa welfare states, períodos históricos, países Anglo-Saxões vs.&nbsp;europeus; discute a exceção dos ganhos do top 1% via visibilidade, elite bias e conhecimento da economia</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão</td>
<td style="text-align: left;">Efeito de catraca em vez de autocorreção democrática</td>
<td style="text-align: left;">Síntese e agenda</td>
<td style="text-align: left;">Nomeia o mecanismo central como <em>ratchet effect</em>; reconcilia todas as perspectivas da literatura; aponta agenda futura sobre políticas e perfis de predistribuição</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="introdução-reações-programáticas-à-desigualdade-pp.-346347" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-reações-programáticas-à-desigualdade-pp.-346347"><span class="header-section-number">1</span> Introdução: Reações Programáticas à Desigualdade (pp.&nbsp;346–347)</h2>
<section id="o-puzzle-de-partida-e-a-tensão-na-literatura-14" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="o-puzzle-de-partida-e-a-tensão-na-literatura-14"><span class="header-section-number">1.1</span> O puzzle de partida e a tensão na literatura [§1–§4]</h3>
<p>O artigo abre com uma provocação direta: embora a desigualdade econômica seja um dos maiores desafios para as democracias contemporâneas, com implicações profundas para as condições de vida, representação política e equidade, a pesquisa sobre como os partidos reagem a ela permanece inconclusiva. Os autores situam a relevância do problema citando suas implicações para a qualidade da representação democrática e o bem-estar material dos cidadãos.</p>
<p>A tensão na literatura é apresentada como um duplo impasse. Por um lado, a vasta literatura sobre transformação pós-industrial dos sistemas partidários e o enfraquecimento dos laços de classe — representada por Häusermann e Bornschier (2023) e Marks et al.&nbsp;(2021) — sugere que mesmo os partidos de esquerda perderam os incentivos para adotar agendas redistributivas em contextos de alta desigualdade, dado o realinhamento eleitoral em direção a uma nova classe média mais abastada e orientada a questões socioculturais. Por outro lado, estudos especificamente voltados às respostas programáticas dos partidos — especialmente Pontusson e Rueda (2010) e Tavits e Potter (2015) — encontram evidências de responsividade da esquerda, sugerindo que alta desigualdade amplia a base eleitoral receptiva a propostas redistributivas, seguindo uma lógica próxima ao teorema do eleitor mediano.</p>
<p>Essa contradição, segundo os autores, não é apenas aparente: ela é produto de uma limitação de dados. Até o momento do artigo, a ausência de séries temporais comparáveis sobre ênfase em igualdade <em>econômica</em> nos programas partidários impediu a investigação direta das questões do lado da oferta — isto é, de como os partidos se posicionam concretamente em termos redistributivos em resposta à desigualdade.</p>
</section>
<section id="contribuição-teórica-nível-versus-mudança-58" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="contribuição-teórica-nível-versus-mudança-58"><span class="header-section-number">1.2</span> Contribuição teórica: nível versus mudança [§5–§8]</h3>
<p>A contribuição teórica central é apresentada ainda na introdução como um argumento de reconciliação entre as perspectivas afirmativa e cética. Os autores partem da premissa básica, compartilhada com a literatura precedente, de que partidos de esquerda têm maiores incentivos para responder à desigualdade porque ela afeta e expande sua constituência menos abastada. Contudo, afirmam que é necessário diferenciar entre reações a <em>níveis</em> elevados de desigualdade e reações a <em>aumentos</em> de desigualdade.</p>
<p>Para explicar por que mesmo a esquerda falha em responder à desigualdade entrincheirada, os autores desenvolvem e combinam três argumentos — visibilidade, mobilização e viés do status quo. O argumento da <strong>visibilidade</strong> apoia-se nas teorias de noticiabilidade e gatekeeping (Galtung e Ruge 1965; Shoemaker e Vos 2009) para afirmar que a mídia prioriza mudanças e eventos novos, e não níveis persistentes de desigualdade. Assim, desigualdade estruturalmente alta permanece invisível e não incentiva respostas partidárias, enquanto desigualdade <em>crescente</em> mobiliza atenção pública e política. O argumento da <strong>mobilização</strong> sustenta que altos níveis de desigualdade deprimem o comparecimento eleitoral dos mais pobres (Solt 2008; 2010), enfraquecendo precisamente a base da esquerda e reduzindo seus incentivos para plataformas fortemente redistributivas (Anderson e Beramendi 2012). Por fim, o argumento do <strong>viés do status quo</strong> recorre à psicologia política da desigualdade: mesmo quando a desigualdade é percebida, mecanismos cognitivos de justificação do sistema (Jost, Banaji e Nosek 2004) e crenças meritocráticas (Mijs 2021) levam os indivíduos a legitimar os níveis existentes de desigualdade, reduzindo a demanda por redistribuição. Por contraste, experimentos mostram que a consciência de desigualdade <em>crescente</em> — não de níveis altos — aumenta o apoio a políticas redistributivas (Kuziemko et al.&nbsp;2015; McCall et al.&nbsp;2017).</p>
<blockquote class="blockquote">
<p>O argumento da introdução pode ser sintetizado assim: a desigualdade persistentemente alta é, em certo sentido, politicamente <em>invisível</em> — normalizada pela mídia, pelo viés cognitivo e pela própria demobilização que produz. Apenas a desigualdade <em>em movimento</em> aciona os mecanismos que transformam privação econômica em demanda e oferta política redistributiva.</p>
</blockquote>
<p>Embora os autores reconheçam que esses mecanismos não são formalmente testados — o que eles equiparam aos estudos de referência que também não os testam —, argumentam que eles, em conjunto, fornecem uma racionalidade crível para o padrão empírico esperado. Duas expectativas são formalizadas: (1) nem esquerda nem direita respondem a níveis elevados de desigualdade; (2) a esquerda responde a <em>aumentos</em> de desigualdade, enquanto a direita permanece não responsiva.</p>
</section>
<section id="contribuição-empírica-nova-medida-de-igualdade-econômica-911" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="contribuição-empírica-nova-medida-de-igualdade-econômica-911"><span class="header-section-number">1.3</span> Contribuição empírica: nova medida de igualdade econômica [§9–§11]</h3>
<p>A contribuição empírica é apresentada como inseparável da teórica: sem os novos dados, a pergunta sobre responsividade a desigualdade econômica stricto sensu não seria respondível. Os estudos existentes utilizam índices excessivamente amplos derivados do MARPOR (<em>Manifesto Project</em>) que conflacionam referências positivas à igualdade econômica e redistributiva com declarações sobre igualdade de direitos e antidiscriminação — categorias conceitualmente distintas com correlação de apenas 0.19 entre si. A correlação entre os indicadores existentes e a nova medida de igualdade econômica de classe desenvolvida pelos autores gira em torno de 0.3, o que demonstra que os estudos anteriores essencialmente mensuraram outra coisa.</p>
<p>A resposta a essa limitação é o desenvolvimento de um pipeline de coleta de dados que combina aprendizado de máquina para filtragem, validação por especialistas e crowdcoding em larga escala para classificar enunciados programáticos de partidos em 12 países OCDE entre 1970 e 2020. Esse pipeline permite distinguir referências positivas à igualdade econômica de outras categorias de igualdade — pré-requisito, segundo os autores, para explicar por que os partidos respondem ou não respondem à desigualdade econômica.</p>
<hr>
</section>
</section>
<section id="por-que-partidos-reagem-a-mudanças-não-a-níveis-de-desigualdade-pp.-347351" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="por-que-partidos-reagem-a-mudanças-não-a-níveis-de-desigualdade-pp.-347351"><span class="header-section-number">2</span> Por que Partidos Reagem a Mudanças, Não a Níveis de Desigualdade (pp.&nbsp;347–351)</h2>
<section id="por-que-partidos-não-respondem-revisão-da-literatura-cética-1215" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="por-que-partidos-não-respondem-revisão-da-literatura-cética-1215"><span class="header-section-number">2.1</span> Por que partidos não respondem: revisão da literatura cética [§12–§15]</h3>
<p>A seção teórica começa mapeando as tradições que levam a expectativas negativas quanto à responsividade partidária à desigualdade. Os autores identificam três corpos de literatura.</p>
<p>O primeiro é a literatura sobre transformação dos sistemas partidários, clivagens e a “morte da classe” (Häusermann e Bornschier 2023; Marks et al.&nbsp;2021). Nessa perspectiva, a tertiarização da economia reconfigurou os grupos de suporte eleitoral da esquerda: as novas classes médias educadas — os “profissionais socioculturais” (Beramendi et al.&nbsp;2015) — são, em média, mais abastadas, mais escolarizadas e mais orientadas a questões socioculturais do que econômicas. Como resultado, redistribuição, nivelamento e consumo do Estado de bem-estar tornaram-se menos centrais para os grupos eleitorais nucleares da esquerda contemporânea, ainda que o foco empírico dessa tradição recaia mais sobre recalibração do que sobre desigualdade per se.</p>
<blockquote class="blockquote">
<p><strong>Nota:</strong> Os autores observam que, embora Kitschelt (1994) e Häusermann e Kitschelt (2024) sejam obras centrais nessa tradição, o foco delas recai sobre recalibração do Estado de bem-estar, e não sobre desigualdade e redistribuição diretamente. Isso implica que a evidência de “morte da resposta redistributiva” nessa tradição é inferida, não diretamente testada. <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/3d7baa52-b40c-4acb-b003-5ee05a60c75f/why_inequalities_persist_parties_nonresponses_to_economic_inequality.pdf?AWSAccessKeyId=ASIA2F3EMEYEYJZEW7W4&amp;Signature=lU%2F7lblRrTLwJ4FTyihyf2z8FHQ%3D&amp;x-amz-security-token=IQoJb3JpZ2luX2VjEF4aCXVzLWVhc3QtMSJHMEUCIHy6DOxSqLPbgsN0pmDDNsM8sianNKKv4xNAu%2BaT6BwZAiEAiO7lMEyPlfDn1zjLCraHEl1Tdo%2B1BI0hRGiZKybYgSUq8wQIJxABGgw2OTk3NTMzMDk3MDUiDK0LIyRqiH%2Ft3OxGeCrQBFhCZa7C1qOn8qlSoo2CxKuImJ7d58hMGrTF1KQuzTwxt9DA0YY0PliFluj7S81DQTafwLnKGorgLgH3ZLySnYY3m5UjHY1rQj%2FPshlM2lrb0WO1p8x%2B82AAcqyGKzghI9AWrCvWKlfGf0Avlnf2fcF99kEiAcnALkZAuHbBP6y4LorfMpsflqZO4DrqRGkXw5QwqH3gRL594JpmuxA450Ked3FjIzmb7cXoA98MmZOFk6QeztnlCUbfonPR1h5LUZrP44k%2F59aGIi20FMuqD8GiufLVRghAcE10C9ZssKbYfWwvxYH7K08zc6CGMA8x5AAueMwoa5EfuKJoZ8FegeWqBKfmBzo8%2F1SR735VUdI5fF5bx8XR50l22d4beJ5qRv8xFoKUt8hS1dP1N%2F31JMJPnNVt10SHRVkznyEqNyutbjO3YQ9EOkdQ0heb0UFljkvhnE5tpaM9pA3Grjulxqqs0XeBEjuAVEBjHH6ghYqrnASwOIwLiTBucvE0R4WXe1OHJj6GgggU9h3%2Fqq1xFo%2FhEe3DSlUUskkZ0KBxMNgRrG%2BzdZUAkUgYdTjKNhyqX2pQpIM5d95tommdr3iqyEjh41LYx0LwgUxYqT%2B91ep9gRTXEX4XivSXKVV8CNJMIQuWIpoKoOMWNHfJjW00od7RI5nRxqFDTcYGbJ1fSvjoFYK4mqWTHvrvlkHx4dxVjPWu1gFgRCLmn7k6nDFz3dRKVC4qd95kpTOFPK0oF1cAoggawQZaeqrfqCbxWjTPF2rGdMDqct6MEJ21rKJCuY4w15XD0AY6mAHyfAZeLKez%2FrSTRZi2UKkTUBtcsN21WauNFBAGUyJRdPZdSmEyjs3%2FmAZWsIPPzVwT%2BMy9mJwx0wTmXs8czXvGpDVMwZ%2FC1mWO2%2BqmCk2rUH5B9iPZTUQEkSEetq%2BxSR8lpXLDRn915LNg39Noe1iRBPUH6XNRlIdTdHqQORPMvLruhm8vq59wt6nEyVkTLUIWcOD4Cdzj5w%3D%3D&amp;Expires=1779486766">ppl-ai-file-upload.s3.amazonaws</a></p>
</blockquote>
<p>O segundo corpo é o das pesquisas histórico-comparadas que investigam as mudanças na relação entre partidos de esquerda e a classe trabalhadora. Para os Estados Unidos, trabalhos como Eidlin (2018) e Ferguson e Rogers (1986) contestam a narrativa de que os Democratas se moveram à direita por mudança nas preferências do eleitorado, enfatizando em vez disso o declínio dos sindicatos e a crescente importância das doações empresariais. Para o Reino Unido, Evans e Tilley (2017) documentam o abandono da classe trabalhadora pelo Partido Trabalhista como um processo interativo de mudança eleitoral e exclusão política. Ambos os casos ilustram como prioridades estratégicas e mudanças nos grupos de suporte enfraqueceram os incentivos da esquerda para endereçar disparidades materiais.</p>
<p>O terceiro corpo é a literatura sobre “democracia desigual”, que examina a ligação entre preferências de grupos econômicos e políticas públicas. Evidências convergentes para os Estados Unidos (Bartels 2008; Gilens 2012; Gilens e Page 2014), Europa (Elsässer, Hense e Schäfer 2021; Mathisen 2023; Schakel 2021) e comparativamente (Lefkofridi e Giger 2020; Lupu e Warner 2022) sugerem que governos produzem resultados políticos enviesados em favor dos mais ricos, com pouca ou nenhuma influência dos mais pobres. Os autores reconhecem que, embora essa literatura forneça contexto crucial, ela não avalia diretamente as respostas programáticas dos partidos — que é o que o artigo se propõe a fazer.</p>
</section>
<section id="por-que-partidos-respondem-responsividade-programática-1618" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="por-que-partidos-respondem-responsividade-programática-1618"><span class="header-section-number">2.2</span> Por que partidos respondem: responsividade programática [§16–§18]</h3>
<p>Em contraste com a literatura cética, uma tradição específica de pesquisa em economia política argumenta que partidos de esquerda ajustam suas plataformas em resposta à desigualdade. O argumento central desta literatura parte do teorema do eleitor mediano (Meltzer e Richard 1981), mas o desloca: dado que o eleitor mediano raramente é beneficiário líquido dos sistemas de transferência (Milanovic 2000), os incentivos da esquerda são moldados pelas condições materiais de suas constituências abaixo da mediana. À medida que eleitores “caem para categorias socioeconômicas mais baixas” em contextos de alta desigualdade (Tavits e Potter 2015, 744), tornam-se mais receptivos a apelos redistributivos, gerando dois mecanismos: expansão do share do eleitorado em dificuldade (Tavits e Potter 2015) e ampliação da lacuna entre grupos de baixa e média renda (Pontusson e Rueda 2010), ambos reforçando os incentivos redistributivos da esquerda.</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> Os autores registram uma inconsistência metodológica reveladora nos estudos que afirmam basear-se em grupos abaixo da mediana: tanto Tavits e Potter (2015) quanto Pontusson e Rueda (2010) utilizam, na prática, medidas que não capturam a situação dos mais pobres — respectivamente o Gini pré-impostos e o share do top 1%. Essa inconsistência entre teoria (grupos abaixo da mediana) e operacionalização (medidas que não os capturam) é um dos argumentos centrais para justificar os novos dados introduzidos no artigo.</p>
</blockquote>
<p>Os autores reconhecem que a mobilização de grupos de baixa renda condiciona a responsividade da esquerda (Pontusson e Rueda 2010): alta desigualdade dificulta essa mobilização (Anderson e Beramendi 2012), o que constitui apenas um dos múltiplos fatores sistêmicos que constrangem as respostas partidárias.</p>
</section>
<section id="os-três-mecanismos-visibilidade-mobilização-e-viés-do-status-quo-1925" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="os-três-mecanismos-visibilidade-mobilização-e-viés-do-status-quo-1925"><span class="header-section-number">2.3</span> Os três mecanismos: visibilidade, mobilização e viés do status quo [§19–§25]</h3>
<p>Os autores desenvolvem com mais detalhe os três argumentos já introduzidos na abertura do artigo.</p>
<p>Para a <strong>visibilidade</strong>, o argumento recorre a evidências empíricas sobre cobertura midiática da desigualdade: McCall (2013) para os EUA e Schröder e Vietze (2015) para a Alemanha mostram que a atenção midiática à desigualdade não reflete seus níveis reais, focando em vez disso em <em>disparidades crescentes</em>. Isso implica que a desigualdade persistentemente alta permanece invisível ao público e, por conseguinte, não cria os incentivos para que partidos respondam via ênfase em igualdade econômica. A desigualdade em alta, ao contrário, é nova, tem maior valor-notícia e produz conflitos tangíveis — gerando cobertura que, por sua vez, cria incentivos para a resposta da esquerda.</p>
<p>Para a <strong>mobilização</strong>, o argumento formaliza o mecanismo de supressão eleitoral: a desigualdade alta deprime o comparecimento entre eleitores de baixa renda (Fenzl 2018; Gallego 2015; Mahler 2008; Solt 2008), que constituem ainda o núcleo da base eleitoral da esquerda (Abou-Chadi e Hix 2021; Pontusson e Rueda 2010). Com sua base encolhida, partidos de esquerda têm incentivos para migrar para o centro e apelar a eleitores moderados (Anderson e Beramendi 2012; Barth, Finseraas e Moene 2015), abandonando plataformas redistributivas fortes. Os autores apontam em rodapé uma limitação importante: o argumento de turnout é mais evidência <em>contra</em> efeitos de nível do que <em>a favor</em> de efeitos de mudança, já que assumiria que os partidos antecipam barreiras futuras de mobilização — premissa que não é explicitada na teoria.</p>
<p>Para o <strong>viés do status quo</strong>, os autores mobilizam a literatura de psicologia política. Indivíduos legitimam os níveis de desigualdade existentes por meio de justificação do sistema (Jost, Banaji e Nosek 2004) e crenças meritocráticas (Mijs 2021), ajustando suas expectativas do que constitui desigualdade “justa” ao nível real — ainda que persista uma lacuna entre ideal e real. Por contraste, experimentos de Kuziemko et al.&nbsp;(2015) e McCall et al.&nbsp;(2017) mostram que o conhecimento de desigualdade <em>crescente</em> — não de níveis — aumenta o apoio a redistribuição. Isso implica que o viés do status quo inibe respostas a níveis, mas não a aumentos.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Expectativas formais
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Expectativa 1:</strong> Nem partidos de esquerda nem de direita são responsivos a níveis elevados de desigualdade.</p>
<p><strong>Expectativa 2:</strong> Partidos de esquerda enfatizam igualdade econômica de classe em resposta a desigualdade crescente. Partidos de direita permanecem não responsivos ao aumento de desigualdade.</p>
</div>
</div>
</section>
<section id="heterogeneidade-entre-países-2628" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="heterogeneidade-entre-países-2628"><span class="header-section-number">2.4</span> Heterogeneidade entre países [§26–§28]</h3>
<p>Os autores reconhecem que fatores sistêmicos e contextuais modulam os efeitos esperados. Três dimensões são antecipadas para guiar as análises de robustez: (1) <strong>regimes de bem-estar</strong>: Estados de bem-estar universais escandinavos podem politizar a desigualdade preventivamente, mesmo quando os níveis são baixos (Svallfors 1997; Esping-Andersen 1990), ao contrário dos modelos Anglo-Saxões de mercado; (2) <strong>competitividade do sistema partidário</strong>: maior número de partidos efetivos e entrada de novos partidos aumentam os incentivos de resposta, especialmente sob representação proporcional (Iversen e Soskice 2006; Anderson e Beramendi 2012); (3) <strong>sistema eleitoral</strong>: representação proporcional tende a amplificar a responsividade da esquerda por criar pressão competitiva e ameaça de novos partidos. Estas dimensões serão retomadas na análise de robustez.</p>
<hr>
</section>
</section>
<section id="novos-dados-conceitos-de-igualdade-partidária-versus-medidas-existentes-pp.-351352" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="novos-dados-conceitos-de-igualdade-partidária-versus-medidas-existentes-pp.-351352"><span class="header-section-number">3</span> Novos Dados: Conceitos de Igualdade Partidária versus Medidas Existentes (pp.&nbsp;351–352)</h2>
<section id="o-problema-de-mensuração-dos-estudos-precedentes-2933" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="o-problema-de-mensuração-dos-estudos-precedentes-2933"><span class="header-section-number">3.1</span> O problema de mensuração dos estudos precedentes [§29–§33]</h3>
<p>Esta seção demonstra empiricamente o problema que motiva o novo conjunto de dados. Os dois estudos mais importantes sobre respostas programáticas dos partidos à desigualdade — Pontusson e Rueda (2010) e Tavits e Potter (2015) — reconhecidamente não capturaram ênfase em redistribuição e igualdade econômica stricto sensu, mas sim índices amplos que combinam múltiplas dimensões de igualdade.</p>
<p>Os autores ilustram o problema com exemplos concretos de declarações de manifestos que foram utilizadas nesses estudos como evidência de “apelos econômicos redistributivos” (Tavits e Potter 2015, 744), mas que claramente não o são: a menção do Partido Democrata americano à eliminação de mascotes esportivas de estereótipos depreciativos (2016), a defesa do Partido Verde do Canadá da dignidade das pessoas com deficiência (2008), ou a declaração do Labour britânico de que “as diferenças das pessoas não são desculpa para tratá-las mal” (2015). Estas são claramente declarações sobre direitos iguais e antidiscriminação, não sobre redistribuição de renda ou riqueza. Os autores contrastam esses exemplos com declarações genuinamente redistributivas, como a proposta trabalhista de introduzir um imposto sobre fortunas acima de £100.000 (1974) ou de pedir apenas ao top 5% de contribuintes que pagassem mais para financiar serviços públicos (2017).</p>
<p>A distinção conceitual remonta ao debate entre “política de redistribuição” e “política de reconhecimento” (Fraser e Honneth 2003), e os autores apontam que, no campo da pesquisa sobre desigualdade econômica, o conceito de igualdade econômica refere-se consistentemente a renda e redistribuição — não a direitos grupais. A correlação de apenas 0.19 entre as duas dimensões valida empiricamente a distinção conceitual, e as correlações de ~0.3 entre medidas existentes e a nova medida de igualdade econômica de classe evidenciam que os estudos precedentes mensuraram um constructo distinto.</p>
</section>
<section id="o-conceito-de-igualdade-econômica-de-classe-34" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="o-conceito-de-igualdade-econômica-de-classe-34"><span class="header-section-number">3.2</span> O conceito de igualdade econômica de classe [§34]</h3>
<p>Os autores adotam o termo <strong>igualdade econômica de classe</strong> (<em>class-based economic equality</em>) para a dimensão substantiva de interesse, reconhecendo que direitos iguais podem ter dimensão econômica — mas que essa sobreposição não justifica o uso de indicadores compostos. A ênfase específica em “classe” sinaliza a filiação ao debate distributivo, em contraste com as dimensões de reconhecimento cultural e antidiscriminação.</p>
<hr>
</section>
</section>
<section id="crowdcoding-de-conceitos-de-igualdade-em-12-países-pp.-353354" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="crowdcoding-de-conceitos-de-igualdade-em-12-países-pp.-353354"><span class="header-section-number">4</span> Crowdcoding de Conceitos de Igualdade em 12 Países (pp.&nbsp;353–354)</h2>
<section id="pipeline-de-coleta-e-validação-3540" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pipeline-de-coleta-e-validação-3540"><span class="header-section-number">4.1</span> Pipeline de coleta e validação [§35–§40]</h3>
<p>Esta seção descreve detalhadamente o processo de construção do dado. O <em>crowdcoding</em> refere-se à coleta ou anotação online de dados mediante julgamentos múltiplos de codificadores não especializados — abordagem apresentada como meio de escalar o julgamento especialista para tarefas ainda demasiado complexas para automação plena (Benoit et al.&nbsp;2016). Os autores coletaram 965 manifestos partidários de 12 países OCDE (Austrália, Áustria, Canadá, Dinamarca, França, Alemanha, Irlanda, Nova Zelândia, Suíça, Suécia, Reino Unido e Estados Unidos) entre 1970 e 2020, sendo 544 recuperados via API do MARPOR e o restante coletado manualmente de arquivos e bibliotecas.</p>
<p>O pipeline operou em três estágios. Primeiro, seguindo o MARPOR, os manifestos foram segmentados em quasi-frases como unidades de análise semântica — textos anteriores a 1998, não disponíveis em forma digitalizada, foram segmentados por um classificador binário. O processo gerou 850.000 quasi-frases. Segundo, um classificador de regressão logística foi treinado para identificar quasi-frases relacionadas a igualdade, calibrado para alta revocação (recall ≥ 0.80) ao custo de mais falsos positivos; as potencialmente relevantes foram revisadas por assistentes de pesquisa, resultando em aproximadamente 55.451 quasi-frases sobre igualdade e justiça social. Terceiro, essas quasi-frases foram distribuídas no Amazon Mechanical Turk (AMT) de fevereiro a maio de 2022, com cinco julgamentos por unidade, restrição geográfica por IP a países culturalmente similares, e controle de qualidade por conjunto de teste validado unanimemente por três especialistas.</p>
<p>Ao todo, 293 trabalhadores contribuíram, com o trabalhador modal codificando 180 unidades. As codificações foram agregadas por voto majoritário; aproximadamente 1,5% das unidades sem categoria modal foram excluídas como indecidíveis. A qualidade foi avaliada por alfa de Krippendorff de 0.72 entre a multidão e os especialistas (2.904 unidades codificadas), com valores por país entre 0.6 e 0.85 — considerado como concordância muito boa pelos padrões da análise de conteúdo quantitativa.</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> Os autores fornecem detalhes éticos relevantes: o procedimento foi aprovado pelo data officer da Universidade de Konstanz sem preocupações éticas; não houve engano, a remuneração atendeu ao salário mínimo local, e as instruções de codificação são reproduzidas no Apêndice A4.</p>
</blockquote>
<hr>
</section>
</section>
<section id="desigualdade-econômica-escolhas-conceituais-pp.-354355" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="desigualdade-econômica-escolhas-conceituais-pp.-354355"><span class="header-section-number">5</span> Desigualdade Econômica: Escolhas Conceituais (pp.&nbsp;354–355)</h2>
<section id="limitações-das-medidas-existentes-e-a-escolha-do-share-dos-50-inferiores-4144" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="limitações-das-medidas-existentes-e-a-escolha-do-share-dos-50-inferiores-4144"><span class="header-section-number">5.1</span> Limitações das medidas existentes e a escolha do share dos 50% inferiores [§41–§44]</h3>
<p>Os autores justificam a escolha de medidas de desigualdade que capturam a posição relativa de grupos em vez da dispersão geral da renda. O coeficiente de Gini, embora amplamente utilizado, é particularmente sensível a deslocamentos de renda no meio da distribuição (Atkinson 1970, 256–7), mascarando variações-chave entre grupos (Blesch, Hauser e Jachimowicz 2022) e não refletindo adequadamente a situação relativa dos eleitores de baixa renda. O share do top 1% tampouco captura se os grupos de baixa renda estão perdendo terreno em relação à classe média ou ao topo.</p>
<p>A medida central adotada é o <strong>share dos 50% inferiores da renda</strong> (<em>below-median-income share</em>), derivada do World Income Database (WID), que combina contas nacionais, pesquisas e dados fiscais para a mais ampla cobertura comparativa disponível (Piketty e Saez 2014). Essa medida reflete diretamente a parcela da renda total que cabe aos grupos de baixa renda, alinhando-se ao argumento de que a esquerda responde às condições econômicas de sua constituência de baixa renda. Medidas complementares incluem as razões 90–50 e 90–10 (capturando a posição relativa das extremas e medianas do grupo abaixo da mediana) e — por razões de comparabilidade com estudos anteriores e relevância no debate público — o Gini (SWIID de Solt 2020) e o share do top 1%.</p>
<hr>
</section>
</section>
<section id="dados-e-métodos-pp.-354356" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="dados-e-métodos-pp.-354356"><span class="header-section-number">6</span> Dados e Métodos (pp.&nbsp;354–356)</h2>
<section id="variável-dependente-independentes-controles-e-especificação-do-modelo-4552" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="variável-dependente-independentes-controles-e-especificação-do-modelo-4552"><span class="header-section-number">6.1</span> Variável dependente, independentes, controles e especificação do modelo [§45–§52]</h3>
<p>A amostra cobre 12 países OCDE com variações relevantes em termos do papel do Estado, instituições e tipo de economia de mercado. A variável dependente é o share de declarações positivas de igualdade econômica como proporção do total de quasi-frases do manifesto de um partido em uma eleição. Para ilustrar a variação: em 2019, o Partido Social-Democrata dinamarquês (<em>Socialdemokratiet</em>) dedicou 8,4% (238/2.842) de suas declarações à igualdade econômica, os Conservadores dedicaram 2,5% (28/1.131), e o Partido Socialista (<em>Socialistisk Folkeparti</em>) liderou com 11,7% (84/719). A média entre os 12 países é de 3,2%.</p>
<p>As variáveis independentes são todas as medidas de desigualdade de mercado descritas acima, mensuradas no nível do país no ano anterior à eleição (L1 para níveis) ou como primeiras diferenças entre t₀ e t₋₁ (D para mudanças). O uso de desigualdade de mercado (pré-impostos e transferências) é justificado para alinhar com estudos de referência, maior disponibilidade de dados e menor risco de endogeneizar redistribuição na explicação. O partidarismo é codificado conforme as famílias partidárias do MARPOR (Volkens et al.&nbsp;2021), com partidos de esquerda incluindo social-democratas, verdes e comunistas, e partidos de direita incluindo liberais, democratas cristãos, conservadores e nacionalistas.</p>
<p>Os controles incluem turnout eleitoral (como proxy para mobilização de eleitores de baixa renda, derivado do dataset Quality of Government de Teorell et al.&nbsp;2022), além de controles partidários (idade do partido, tamanho do partido, status de partido de nicho) e de país (número efetivo de partidos — ENP, crescimento do PIB). A especificação do modelo intencional­mente imita Tavits e Potter (2015) para permitir comparação direta, estimando:</p>
<p>[ _{cpe} = _0 + _1 + _2 ( ) + _3 + Z+ _c + <em>p + </em>{cpe} ]</p>
<p>onde INEQ é um substituto para as medidas de desigualdade, <em>partisanship</em> é um dummy que denota partidos de direita, (Z) é uma matriz de controles com seus coeficientes, e (_c + _p) são interceptos aleatórios no nível de país e partido. Nessa especificação, (_1) representa a resposta dos partidos de esquerda a níveis ou mudanças de desigualdade, e (_2) captura a diferença de resposta entre partidos de direita e esquerda.</p>
<hr>
</section>
</section>
<section id="resultados-pp.-355360" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="resultados-pp.-355360"><span class="header-section-number">7</span> Resultados (pp.&nbsp;355–360)</h2>
<section id="respostas-a-níveis-de-desigualdade-5358" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="respostas-a-níveis-de-desigualdade-5358"><span class="header-section-number">7.1</span> Respostas a níveis de desigualdade [§53–§58]</h3>
<p>Os autores apresentam os resultados para os dois conjuntos de expectativas separadamente. Quanto aos níveis de desigualdade (coluna esquerda da Figure 2, modelos “L1” da Table 1), a evidência corrobora a Expectativa 1: não há resposta positiva de partidos de esquerda a níveis elevados de desigualdade.</p>
<p>O resultado mais relevante diz respeito ao share dos 50% inferiores. O coeficiente positivo de (_1 = 0.15) (se = 0.08, marginalmente significativo) indica a tendência de partidos de esquerda a <em>de-enfatizar</em> igualdade econômica de classe quando a desigualdade é alta — ou seja, quando a participação dos mais pobres na renda é baixa. O termo de interação ((_2 = -0.21), se = 0.09) indica que esse padrão não se replica nos partidos de direita. Em termos substantivos: em contextos de alta desigualdade (10º percentil do share dos 50% inferiores), tanto partidos de esquerda quanto de direita dedicam cerca de 3% de seus manifestos a declarações igualitárias econômicas — sem diferença partidária discernível. Em contextos de baixa desigualdade (90º percentil do share), a divergência se abre: a esquerda dedica 4,9% e a direita 2,1%. A convergência em contextos de alta desigualdade é puxada pela <em>de-ênfase da esquerda</em>, não por aumento da direita.</p>
<p>Para as razões de renda (90–50 e 90–10), o padrão é similar: em níveis baixos de desigualdade, partidos de esquerda dedicam ~4,8% dos manifestos à igualdade econômica, em contraste com ~2,3% da direita; quando a desigualdade é alta (90º percentil: o percentil 90 ganha aproximadamente o triplo do percentil 50), as diferenças desaparecem, com ambos os grupos convergindo para ~2,3%. Para o top 1%, os coeficientes são estatisticamente insignificantes. Para o Gini, contrariando evidências anteriores de Tavits e Potter (2015), não há reação da esquerda a níveis mais altos ((_1 = 1.91), n.s.), o que os autores atribuem à insensibilidade do Gini à situação dos mais pobres.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Achado crítico sobre níveis
</div>
</div>
<div class="callout-body-container callout-body">
<p>A esquerda de-enfatiza igualdade econômica precisamente quando os grupos de baixa renda mais precisariam de resposta redistributiva — em contextos de alta desigualdade. Esse resultado corrobora a visão de que a esquerda abandonou seus grupos nucleares mais marginalizados.</p>
</div>
</div>
</section>
<section id="respostas-a-mudanças-de-desigualdade-5964" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="respostas-a-mudanças-de-desigualdade-5964"><span class="header-section-number">7.2</span> Respostas a mudanças de desigualdade [§59–§64]</h3>
<p>Para as mudanças de desigualdade (coluna direita da Figure 2, modelos “D” da Table 1), os resultados alinham-se com a Expectativa 2. Partidos de esquerda respondem a aumentos de desigualdade com mais ênfase em igualdade econômica, enquanto partidos de direita permanecem não responsivos.</p>
<p>Quanto ao share dos 50% inferiores, o coeficiente de (_1 = -0.64) (se = 0.27) indica que quando os 50% mais pobres perdem participação na renda, a esquerda aumenta sua ênfase em igualdade econômica. Em termos substantivos: uma diminuição anual de 0,7 ponto percentual no share dos 50% inferiores (10º percentil dos casos) leva os partidos de esquerda a dedicar 4,8% <em>a mais</em> de seus manifestos à igualdade econômica. Em contraste, quando os mais pobres ganham participação (90º percentil), a esquerda reduz sua ênfase em ~15% — uma mudança superior a um desvio-padrão considerando todos os partidos. O termo de interação ((_2 = 0.99), se = 0.34) confirma que esse padrão não se aplica aos partidos de direita.</p>
<p>Para as razões de renda, o padrão se replica: ao longo dos percentis 10 a 90 de mudança na razão 90–10, partidos de esquerda aumentam o share de declarações igualitárias em 14,1%; para a razão 90–50, o aumento é de 8% (0,3 pontos percentuais). Em ambos os casos, linhas planas para a direita confirmam a não responsividade desses partidos.</p>
<p>A exceção notável é o top 1%: nenhum partido responde a mudanças no share do percentil mais rico ((_1 = -0.11), n.s.; (_2 = 0.01), n.s.). O resultado alinha-se à intuição teórica dos autores de que ganhos em um grupo pequeno e concentrado no topo são menos visíveis e menos tangíveis. Para o Gini, a ausência de resposta a mudanças ((_1 = -0.14), n.s.) confirma a inadequação dessa medida para capturar os incentivos eleitorais relevantes — mudanças anuais típicas no Gini (~0,1 unidade) são excessivamente marginais para serem percebidas pelos partidos.</p>
<p>Adicionalmente, os autores testam se a ênfase em direitos iguais depende de níveis ou mudanças de desigualdade econômica: os coeficientes relevantes são todos estatisticamente indistinguíveis de zero, confirmando que a dimensão de direitos iguais segue sua própria trajetória, independente dos movimentos de desigualdade econômica.</p>
</section>
<section id="resumo-dos-resultados-e-robustez-6566" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="resumo-dos-resultados-e-robustez-6566"><span class="header-section-number">7.3</span> Resumo dos resultados e robustez [§65–§66]</h3>
<p>Os autores sintetizam: ao contrário dos estudos anteriores baseados em medidas multidimensionais que conflacionam igualdade econômica com outros aspectos, os resultados fornecem no máximo evidências parciais para a ideia otimista de que a desigualdade é autocorretiva nas democracias. Em contextos de alta desigualdade, esquerda e direita tornam-se indistinguíveis na ênfase à igualdade econômica — o que sugere abandono dos grupos mais marginalizados. Quando a desigualdade está em alta, a esquerda ainda reage. Nenhum partido reage a ganhos do top — o que ajuda a explicar por que a concentração de renda no topo cresce tão rapidamente.</p>
<p>A seção de robustez (SI Apêndice C) reporta testes com diversas especificações de modelo (efeitos fixos, defasagens), controles adicionais (sistema eleitoral, redistribuição, dummies de décadas), categorizações alternativas de partidos, exclusão de observações (partidos de franja com menos de 2%, outliers, dados imputados pelo WID), estimativas de erro padrão clusterizados por país, e interações não lineares via KRLS (<em>Kernel Regularized Least Squares</em>). O procedimento Romano-Wolf foi aplicado para controlar a taxa de erro nos múltiplos testes estatísticos. Em geral, esses testes corroboram os resultados.</p>
<hr>
</section>
</section>
<section id="análises-adicionais-pp.-360361" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="análises-adicionais-pp.-360361"><span class="header-section-number">8</span> Análises Adicionais (pp.&nbsp;360–361)</h2>
<section id="welfare-states-indicadores-alternativos-salários-reais-e-heterogeneidade-6772" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="welfare-states-indicadores-alternativos-salários-reais-e-heterogeneidade-6772"><span class="header-section-number">8.1</span> Welfare states, indicadores alternativos, salários reais e heterogeneidade [§67–§72]</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Implicação de heterogeneidade contextual
</div>
</div>
<div class="callout-body-container callout-body">
<p>Embora os resultados principais sejam robustos a diferentes recortes temporais e geográficos, a lógica preventiva dos Estados de bem-estar escandinavos — politizar a desigualdade mesmo quando baixa — não encontra confirmação estatisticamente significativa na amostra de apenas dois países social-democratas. Isso aponta para uma limitação importante da comparação com apenas 12 países.</p>
</div>
</div>
<p>A análise adicional contempla quatro eixos. Primeiro, os autores investigam se o resultado de nível poderia refletir um padrão escandinavo de politização preventiva — isto é, Estados de bem-estar igualitários discutindo mais desigualdade quando os níveis são baixos. Duas estratégias empíricas são empregadas: inclusão de dummy para regimes social-democratas (não altera os resultados) e uso da “agenda do sistema partidário” como proxy para politização (Green-Pedersen e Mortensen 2015). Nenhuma das estratégias sugere politização preventiva em contextos igualitários — embora os autores reconheçam que, com apenas dois países social-democratas na amostra, a evidência seja tentativa.</p>
<p>Segundo, indicadores alternativos (share dos 40% inferiores, share do top 10%, razão 60:40) produzem padrões muito similares aos da análise principal. Destaque para a razão 60:40, que exibe susceptibilidade política particularmente clara — o que os autores vinculam ao trabalho de Kevins et al.&nbsp;(2018), que identifica a classe média alta como principal “régua de comparação” da desigualdade nos indivíduos.</p>
<p>Terceiro, controles para salários reais de trabalhadores de produção não alteram os resultados (Bottom 50 (D): (_1 = -0.65), se = 0.27; (_2 = 0.32), se = 0.29). Os coeficientes permanecem significativos e consistentes com a análise principal, sugerindo que a relação entre desigualdade e políticas públicas não é afetada por variações nos salários reais.</p>
</section>
<section id="ganhos-do-top-1-e-fim-da-expansão-7377" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="ganhos-do-top-1-e-fim-da-expansão-7377"><span class="header-section-number">8.2</span> Ganhos do top 1% e fim da expansão [§73–§77]</h3>
<p>A análise de heterogeneidade ainda testa uma hipótese específica para os ganhos do top 1%. Os autores mostram que a ausência de resposta a aumentos na renda do 1% mais rico permanece inalterada mesmo quando se introduzem interações com período e estrutura partidária. A interpretação proposta é que ganhos no topo são politicamente menos visíveis e mais fáceis de acomodar cognitivamente do que perdas ou ganhos na base da distribuição. Em outras palavras, o topo pode enriquecer sem provocar o mesmo tipo de mobilização que uma deterioração na posição relativa dos estratos mais baixos.</p>
<p>Os autores também verificam se os resultados seriam diferentes em períodos mais recentes, especialmente após a Grande Recessão. O padrão não muda de modo substantivo: a esquerda continua sensível a aumentos na desigualdade, mas não a seus níveis. Essa estabilidade temporal reforça a ideia de que o mecanismo não é conjuntural, mas estrutural.</p>
</section>
<section id="interpretação-substantiva-7882" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="interpretação-substantiva-7882"><span class="header-section-number">8.3</span> Interpretação substantiva [§78–§82]</h3>
<p>A seção de discussão amarra os resultados à tese mais ampla do artigo. Os autores argumentam que a esquerda não corrige a desigualdade alta porque os contextos de alta desigualdade reduzem simultaneamente a visibilidade do problema, a mobilização da base mais pobre e a disposição cognitiva para tratá-lo como injustiça. Quando a desigualdade aumenta, porém, ela se torna mais visível, mais politizável e mais capaz de ativar respostas redistributivas.</p>
<p>O ponto mais forte da interpretação é que ela reconcilia resultados contraditórios da literatura sem precisar escolher entre “a esquerda responde” e “a esquerda não responde”. O que muda é o objeto empírico: níveis versus mudanças, e igualdade econômica versus igualdade de direitos. O ponto mais vulnerável, contudo, é que essa síntese depende de múltiplos mecanismos não identificados separadamente; assim, o artigo explica bem o padrão agregado, mas não discrimina com plena nitidez qual mecanismo pesa mais em cada contexto.</p>
<hr>
</section>
</section>
<section id="conclusão-pp.-361364" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="conclusão-pp.-361364"><span class="header-section-number">9</span> Conclusão (pp.&nbsp;361–364)</h2>
<section id="o-efeito-de-catraca-8388" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="o-efeito-de-catraca-8388"><span class="header-section-number">9.1</span> O efeito de catraca [§83–§88]</h3>
<p>A conclusão retoma a tese em forma condensada: partidos de esquerda respondem a aumentos de desigualdade, mas não a níveis altos de desigualdade; partidos de direita não respondem a nenhum dos dois. Os autores nomeiam a implicação central como um <strong>efeito de catraca</strong>: a desigualdade crescente pode desencadear reação política, mas a desigualdade já instalada tende a se estabilizar, porque os mecanismos que poderiam corrigi-la são enfraquecidos pela própria estrutura desigual.</p>
<p>Essa conclusão é importante porque reposiciona o debate sobre responsividade democrática. A democracia não aparece como mecanismo autocorretivo automático, ao menos não em relação a desigualdades profundas e persistentes. Em vez disso, ela parece reagir mais facilmente a mudanças recentes do que a estruturas duráveis, o que ajuda a entender por que a desigualdade pode continuar alta por longos períodos mesmo sob competição partidária.</p>
</section>
<section id="contribuição-para-o-debate-8994" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="contribuição-para-o-debate-8994"><span class="header-section-number">9.2</span> Contribuição para o debate [§89–§94]</h3>
<p>Os autores encerram apontando três contribuições. Primeiro, a contribuição substantiva: uma explicação para a persistência da desigualdade que não depende de cinismo democrático total, mas de um conjunto de incentivos assimétricos. Segundo, a contribuição metodológica: uma nova medida de igualdade econômica de classe, que separa redistribuição de reconhecimento e corrige um problema de mensuração que afetava a literatura. Terceiro, a contribuição teórica: a distinção entre nível e mudança de desigualdade, que ajuda a reconciliar resultados anteriores aparentemente inconsistentes.</p>
<p>Eles também sugerem uma agenda futura sobre <em>predistribution</em> e perfis programáticos mais amplos de partidos, além de pesquisas em outros contextos para testar a generalização do padrão. O encerramento reafirma que a desigualdade persiste não porque não seja politicamente relevante, mas porque sua persistência altera os próprios incentivos de resposta.</p>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">10</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A tese central do texto é que partidos — especialmente os de esquerda — respondem a <em>aumentos</em> de desigualdade econômica, mas não a seus <em>níveis</em> elevados, o que ajuda a explicar por que a desigualdade permanece alta nas democracias contemporâneas. O argumento é causal-explicativo e combina teoria de responsividade partidária, mecanismos cognitivos e um novo desenho de mensuração para mostrar que a aparente contradição da literatura decorre de distinguir mal desigualdade econômica de outras formas de igualdade e de confundir níveis com mudanças. O texto demonstra, com dados comparados de 12 países OCDE entre 1970 e 2020, que a esquerda reage ao agravamento da desigualdade, mas não corrige a desigualdade já entrincheirada; o restante fica como explicação plausível e agenda para testes mais diretos. Sua contribuição mais ampla é mostrar que democracias podem reagir a deteriorações visíveis sem produzir autocorreção estrutural, o que é central para debates sobre representação, desigualdade e persistência institucional.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>