<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-06-07">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: O Cativeiro da Terra – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9c28ad92f8939dd35fc671874dd1efeb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/tts-reader-1.0.0/tts-reader.js" defer="true"></script>
<link href="../site_libs/quarto-contrib/tts-reader-1.0.0/tts-reader.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: O Cativeiro da Terra – Annotated Bibliography">
<meta property="og:description" content="Martins, J. de S. (2012). O cativeiro da terra (9ª ed., revista e ampliada). Editora Contexto.">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#prefácio-nova-edição-revista-e-ampliada-pp.-926" id="toc-prefácio-nova-edição-revista-e-ampliada-pp.-926" class="nav-link" data-scroll-target="#prefácio-nova-edição-revista-e-ampliada-pp.-926"><span class="header-section-number">1</span> Prefácio — <em>Nova edição, revista e ampliada</em> (pp.&nbsp;9–26)</a>
  <ul class="collapse">
  <li><a href="#o-cativeiro-como-matriz-estrutural-cap.pref-15" id="toc-o-cativeiro-como-matriz-estrutural-cap.pref-15" class="nav-link" data-scroll-target="#o-cativeiro-como-matriz-estrutural-cap.pref-15"><span class="header-section-number">1.1</span> O cativeiro como matriz estrutural [Cap.Pref §1–§5]</a></li>
  <li><a href="#estrutura-e-revisões-da-9ª-edição-cap.pref-612" id="toc-estrutura-e-revisões-da-9ª-edição-cap.pref-612" class="nav-link" data-scroll-target="#estrutura-e-revisões-da-9ª-edição-cap.pref-612"><span class="header-section-number">1.2</span> Estrutura e revisões da 9ª edição [Cap.Pref §6–§12]</a></li>
  </ul></li>
  <li><a href="#apresentação-pp.-2743" id="toc-apresentação-pp.-2743" class="nav-link" data-scroll-target="#apresentação-pp.-2743"><span class="header-section-number">2</span> Apresentação (pp.&nbsp;27–43)</a>
  <ul class="collapse">
  <li><a href="#crítica-ao-marxismo-vulgar-e-ao-althusserianismo-cap.apres-18" id="toc-crítica-ao-marxismo-vulgar-e-ao-althusserianismo-cap.apres-18" class="nav-link" data-scroll-target="#crítica-ao-marxismo-vulgar-e-ao-althusserianismo-cap.apres-18"><span class="header-section-number">2.1</span> Crítica ao “marxismo vulgar” e ao althusserianismo [Cap.Apres §1–§8]</a></li>
  <li><a href="#a-hipótese-central-e-as-inovações-teóricas-cap.apres-917" id="toc-a-hipótese-central-e-as-inovações-teóricas-cap.apres-917" class="nav-link" data-scroll-target="#a-hipótese-central-e-as-inovações-teóricas-cap.apres-917"><span class="header-section-number">2.2</span> A hipótese central e as inovações teóricas [Cap.Apres §9–§17]</a></li>
  </ul></li>
  <li><a href="#capítulo-1-a-produção-capitalista-de-relações-não-capitalistas-de-produção-pp.-45145" id="toc-capítulo-1-a-produção-capitalista-de-relações-não-capitalistas-de-produção-pp.-45145" class="nav-link" data-scroll-target="#capítulo-1-a-produção-capitalista-de-relações-não-capitalistas-de-produção-pp.-45145"><span class="header-section-number">3</span> Capítulo 1: A produção capitalista de relações não capitalistas de produção (pp.&nbsp;45–145)</a>
  <ul class="collapse">
  <li><a href="#a-dinâmica-dos-contrários-refutação-do-consenso-cap.1-19" id="toc-a-dinâmica-dos-contrários-refutação-do-consenso-cap.1-19" class="nav-link" data-scroll-target="#a-dinâmica-dos-contrários-refutação-do-consenso-cap.1-19"><span class="header-section-number">3.1</span> A dinâmica dos contrários: refutação do consenso [Cap.1 §1–§9]</a></li>
  <li><a href="#a-natureza-do-escravo-como-renda-capitalizada-cap.1-1018" id="toc-a-natureza-do-escravo-como-renda-capitalizada-cap.1-1018" class="nav-link" data-scroll-target="#a-natureza-do-escravo-como-renda-capitalizada-cap.1-1018"><span class="header-section-number">3.2</span> A natureza do escravo como renda capitalizada [Cap.1 §10–§18]</a></li>
  <li><a href="#o-colonato-como-relação-não-capitalista-produzida-pelo-capital-cap.1-1934" id="toc-o-colonato-como-relação-não-capitalista-produzida-pelo-capital-cap.1-1934" class="nav-link" data-scroll-target="#o-colonato-como-relação-não-capitalista-produzida-pelo-capital-cap.1-1934"><span class="header-section-number">3.3</span> O colonato como relação não capitalista produzida pelo capital [Cap.1 §19–§34]</a></li>
  <li><a href="#renda-fundiária-e-reprodução-capitalista-do-capital-cap.1-3552" id="toc-renda-fundiária-e-reprodução-capitalista-do-capital-cap.1-3552" class="nav-link" data-scroll-target="#renda-fundiária-e-reprodução-capitalista-do-capital-cap.1-3552"><span class="header-section-number">3.4</span> Renda fundiária e reprodução capitalista do capital [Cap.1 §35–§52]</a></li>
  <li><a href="#imigração-subsidiada-e-a-produção-artificial-da-escassez-de-terras-cap.1-5372" id="toc-imigração-subsidiada-e-a-produção-artificial-da-escassez-de-terras-cap.1-5372" class="nav-link" data-scroll-target="#imigração-subsidiada-e-a-produção-artificial-da-escassez-de-terras-cap.1-5372"><span class="header-section-number">3.5</span> Imigração subsidiada e a produção artificial da escassez de terras [Cap.1 §53–§72]</a></li>
  <li><a href="#composição-orgânica-do-capital-e-trabalho-no-colonato-cap.1-7392" id="toc-composição-orgânica-do-capital-e-trabalho-no-colonato-cap.1-7392" class="nav-link" data-scroll-target="#composição-orgânica-do-capital-e-trabalho-no-colonato-cap.1-7392"><span class="header-section-number">3.6</span> Composição orgânica do capital e trabalho no colonato [Cap.1 §73–§92]</a></li>
  </ul></li>
  <li><a href="#capítulo-2-uma-imigração-tardia-pp.-147189" id="toc-capítulo-2-uma-imigração-tardia-pp.-147189" class="nav-link" data-scroll-target="#capítulo-2-uma-imigração-tardia-pp.-147189"><span class="header-section-number">4</span> Capítulo 2: Uma imigração tardia (pp.&nbsp;147–189)</a>
  <ul class="collapse">
  <li><a href="#o-pressuposto-homogeneizante-e-a-diferença-italiana-espanhola-cap.2-16" id="toc-o-pressuposto-homogeneizante-e-a-diferença-italiana-espanhola-cap.2-16" class="nav-link" data-scroll-target="#o-pressuposto-homogeneizante-e-a-diferença-italiana-espanhola-cap.2-16"><span class="header-section-number">4.1</span> O pressuposto homogeneizante e a diferença italiana-espanhola [Cap.2 §1–§6]</a></li>
  <li><a href="#diferenças-estruturais-entre-as-imigrações-italiana-e-espanhola-cap.2-716" id="toc-diferenças-estruturais-entre-as-imigrações-italiana-e-espanhola-cap.2-716" class="nav-link" data-scroll-target="#diferenças-estruturais-entre-as-imigrações-italiana-e-espanhola-cap.2-716"><span class="header-section-number">4.2</span> Diferenças estruturais entre as imigrações italiana e espanhola [Cap.2 §7–§16]</a></li>
  <li><a href="#o-colonato-em-transformação-da-sujeição-à-monetização-parcial-cap.2-1727" id="toc-o-colonato-em-transformação-da-sujeição-à-monetização-parcial-cap.2-1727" class="nav-link" data-scroll-target="#o-colonato-em-transformação-da-sujeição-à-monetização-parcial-cap.2-1727"><span class="header-section-number">4.3</span> O colonato em transformação: da sujeição à monetização parcial [Cap.2 §17–§27]</a></li>
  </ul></li>
  <li><a href="#capítulo-3-do-trabalho-escravo-ao-assalariado-nas-fazendas-de-café-18801914-pp.-191257" id="toc-capítulo-3-do-trabalho-escravo-ao-assalariado-nas-fazendas-de-café-18801914-pp.-191257" class="nav-link" data-scroll-target="#capítulo-3-do-trabalho-escravo-ao-assalariado-nas-fazendas-de-café-18801914-pp.-191257"><span class="header-section-number">5</span> Capítulo 3: Do trabalho escravo ao assalariado nas fazendas de café, 1880–1914 (pp.&nbsp;191–257)</a>
  <ul class="collapse">
  <li><a href="#quatro-problemas-população-produção-e-força-de-trabalho-cap.3-17" id="toc-quatro-problemas-população-produção-e-força-de-trabalho-cap.3-17" class="nav-link" data-scroll-target="#quatro-problemas-população-produção-e-força-de-trabalho-cap.3-17"><span class="header-section-number">5.1</span> Quatro problemas: população, produção e força de trabalho [Cap.3 §1–§7]</a></li>
  <li><a href="#a-dívida-e-a-roça-como-mecanismos-de-sujeição-cap.3-818" id="toc-a-dívida-e-a-roça-como-mecanismos-de-sujeição-cap.3-818" class="nav-link" data-scroll-target="#a-dívida-e-a-roça-como-mecanismos-de-sujeição-cap.3-818"><span class="header-section-number">5.2</span> A dívida e a roça como mecanismos de sujeição [Cap.3 §8–§18]</a></li>
  <li><a href="#a-lei-de-terras-de-1850-como-mecanismo-estrutural-cap.3-1932" id="toc-a-lei-de-terras-de-1850-como-mecanismo-estrutural-cap.3-1932" class="nav-link" data-scroll-target="#a-lei-de-terras-de-1850-como-mecanismo-estrutural-cap.3-1932"><span class="header-section-number">5.3</span> A Lei de Terras de 1850 como mecanismo estrutural [Cap.3 §19–§32]</a></li>
  <li><a href="#formas-de-trabalho-e-movimento-da-população-cap.3-3352" id="toc-formas-de-trabalho-e-movimento-da-população-cap.3-3352" class="nav-link" data-scroll-target="#formas-de-trabalho-e-movimento-da-população-cap.3-3352"><span class="header-section-number">5.4</span> Formas de trabalho e movimento da população [Cap.3 §33–§52]</a></li>
  </ul></li>
  <li><a href="#capítulo-4-as-relações-de-classe-e-a-produção-ideológica-da-noção-de-trabalho-pp.-283305" id="toc-capítulo-4-as-relações-de-classe-e-a-produção-ideológica-da-noção-de-trabalho-pp.-283305" class="nav-link" data-scroll-target="#capítulo-4-as-relações-de-classe-e-a-produção-ideológica-da-noção-de-trabalho-pp.-283305"><span class="header-section-number">6</span> Capítulo 4: As relações de classe e a produção ideológica da noção de trabalho (pp.&nbsp;283–305)</a>
  <ul class="collapse">
  <li><a href="#trabalho-livre-e-origem-do-contingente-operário-cap.4-17" id="toc-trabalho-livre-e-origem-do-contingente-operário-cap.4-17" class="nav-link" data-scroll-target="#trabalho-livre-e-origem-do-contingente-operário-cap.4-17"><span class="header-section-number">6.1</span> Trabalho livre e origem do contingente operário [Cap.4 §1–§7]</a></li>
  <li><a href="#a-ética-do-trabalho-como-produção-burguesa-cap.4-818" id="toc-a-ética-do-trabalho-como-produção-burguesa-cap.4-818" class="nav-link" data-scroll-target="#a-ética-do-trabalho-como-produção-burguesa-cap.4-818"><span class="header-section-number">6.2</span> A ética do trabalho como produção burguesa [Cap.4 §8–§18]</a></li>
  <li><a href="#a-origem-comercial-e-o-caráter-de-classe-da-abolição-cap.4-1930" id="toc-a-origem-comercial-e-o-caráter-de-classe-da-abolição-cap.4-1930" class="nav-link" data-scroll-target="#a-origem-comercial-e-o-caráter-de-classe-da-abolição-cap.4-1930"><span class="header-section-number">6.3</span> A origem comercial e o caráter de classe da abolição [Cap.4 §19–§30]</a></li>
  </ul></li>
  <li><a href="#capítulo-5-o-café-e-a-gênese-da-industrialização-em-são-paulo-pp.-307355" id="toc-capítulo-5-o-café-e-a-gênese-da-industrialização-em-são-paulo-pp.-307355" class="nav-link" data-scroll-target="#capítulo-5-o-café-e-a-gênese-da-industrialização-em-são-paulo-pp.-307355"><span class="header-section-number">7</span> Capítulo 5: O café e a gênese da industrialização em São Paulo (pp.&nbsp;307–355)</a>
  <ul class="collapse">
  <li><a href="#a-controvérsia-na-literatura-furtado-simonsen-e-a-industrialização-inconsciente-cap.5-19" id="toc-a-controvérsia-na-literatura-furtado-simonsen-e-a-industrialização-inconsciente-cap.5-19" class="nav-link" data-scroll-target="#a-controvérsia-na-literatura-furtado-simonsen-e-a-industrialização-inconsciente-cap.5-19"><span class="header-section-number">7.1</span> A controvérsia na literatura: Furtado, Simonsen e a industrialização “inconsciente” [Cap.5 §1–§9]</a></li>
  <li><a href="#a-dissolução-da-dicotomia-agro-industrial-cap.5-1022" id="toc-a-dissolução-da-dicotomia-agro-industrial-cap.5-1022" class="nav-link" data-scroll-target="#a-dissolução-da-dicotomia-agro-industrial-cap.5-1022"><span class="header-section-number">7.2</span> A dissolução da dicotomia agro-industrial [Cap.5 §10–§22]</a></li>
  </ul></li>
  <li><a href="#capítulo-6-empresários-e-trabalhadores-de-origem-italiana-no-desenvolvimento-industrial-brasileiro-em-1880-e-1914-pp.-357435" id="toc-capítulo-6-empresários-e-trabalhadores-de-origem-italiana-no-desenvolvimento-industrial-brasileiro-em-1880-e-1914-pp.-357435" class="nav-link" data-scroll-target="#capítulo-6-empresários-e-trabalhadores-de-origem-italiana-no-desenvolvimento-industrial-brasileiro-em-1880-e-1914-pp.-357435"><span class="header-section-number">8</span> Capítulo 6: Empresários e trabalhadores de origem italiana no desenvolvimento industrial brasileiro em 1880 e 1914 (pp.&nbsp;357–435)</a>
  <ul class="collapse">
  <li><a href="#três-destinos-do-imigrante-italiano-cap.6-18" id="toc-três-destinos-do-imigrante-italiano-cap.6-18" class="nav-link" data-scroll-target="#três-destinos-do-imigrante-italiano-cap.6-18"><span class="header-section-number">8.1</span> Três destinos do imigrante italiano [Cap.6 §1–§8]</a></li>
  <li><a href="#imigração-subsidiada-como-mecanismo-de-sujeição-cap.6-921" id="toc-imigração-subsidiada-como-mecanismo-de-sujeição-cap.6-921" class="nav-link" data-scroll-target="#imigração-subsidiada-como-mecanismo-de-sujeição-cap.6-921"><span class="header-section-number">8.2</span> Imigração subsidiada como mecanismo de sujeição [Cap.6 §9–§21]</a></li>
  <li><a href="#os-empresários-italianos-origem-capital-e-condição-não-capitalista-cap.6-2242" id="toc-os-empresários-italianos-origem-capital-e-condição-não-capitalista-cap.6-2242" class="nav-link" data-scroll-target="#os-empresários-italianos-origem-capital-e-condição-não-capitalista-cap.6-2242"><span class="header-section-number">8.3</span> Os empresários italianos: origem, capital e condição não capitalista [Cap.6 §22–§42]</a></li>
  </ul></li>
  <li><a href="#capítulo-7-o-imaginário-da-ascensão-social-pelo-trabalho-a-morte-do-burguês-mítico-pp.-437463" id="toc-capítulo-7-o-imaginário-da-ascensão-social-pelo-trabalho-a-morte-do-burguês-mítico-pp.-437463" class="nav-link" data-scroll-target="#capítulo-7-o-imaginário-da-ascensão-social-pelo-trabalho-a-morte-do-burguês-mítico-pp.-437463"><span class="header-section-number">9</span> Capítulo 7: O imaginário da ascensão social pelo trabalho / A morte do burguês mítico (pp.&nbsp;437–463)</a>
  <ul class="collapse">
  <li><a href="#o-mito-matarazzo-e-a-proletarização-das-aspirações-burguesas-cap.7-110" id="toc-o-mito-matarazzo-e-a-proletarização-das-aspirações-burguesas-cap.7-110" class="nav-link" data-scroll-target="#o-mito-matarazzo-e-a-proletarização-das-aspirações-burguesas-cap.7-110"><span class="header-section-number">9.1</span> O mito Matarazzo e a proletarização das aspirações burguesas [Cap.7 §1–§10]</a></li>
  <li><a href="#a-vida-do-burguês-como-morte-do-mito-cap.7-1118" id="toc-a-vida-do-burguês-como-morte-do-mito-cap.7-1118" class="nav-link" data-scroll-target="#a-vida-do-burguês-como-morte-do-mito-cap.7-1118"><span class="header-section-number">9.2</span> A vida do burguês como morte do mito [Cap.7 §11–§18]</a></li>
  <li><a href="#o-aburguesamento-das-aspirações-operárias-e-a-ambiguidade-de-classe-cap.7-1924" id="toc-o-aburguesamento-das-aspirações-operárias-e-a-ambiguidade-de-classe-cap.7-1924" class="nav-link" data-scroll-target="#o-aburguesamento-das-aspirações-operárias-e-a-ambiguidade-de-classe-cap.7-1924"><span class="header-section-number">9.3</span> O aburguesamento das aspirações operárias e a ambiguidade de classe [Cap.7 §19–§24]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">10</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: O Cativeiro da Terra</h1>
<p class="subtitle lead">Martins, J. de S. (2012). <em>O cativeiro da terra</em> (9ª ed., revista e ampliada). Editora Contexto.</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Historical Sociology</div>
    <div class="quarto-category">Political Economy</div>
    <div class="quarto-category">Labor Relations</div>
    <div class="quarto-category">Coffee Economy</div>
    <div class="quarto-category">Social Stratification</div>
    <div class="quarto-category">Brazil</div>
    <div class="quarto-category">2012</div>
    <div class="quarto-category">2010s</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Informações Técnicas e BibTeX
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>Última atualização: 2026-06-07
Modelo: Claude Sonnet 4.6
Prompt Version: v17.4 · 2026-05-13
Gerado em: 2026-06-07T00:00:00-03:00
Ocasião da Leitura:</code></pre>
<p><strong>Entrada BibTeX → Martins2012</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@book</span>{<span class="ot">Martins2012</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>    = {Martins, José de Souza},</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>     = {O cativeiro da terra},</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>      = {2012},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">publisher</span> = {Editora Contexto},</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">address</span>   = {São Paulo},</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">edition</span>   = {9},</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">note</span>      = {Edição revista e ampliada. 1ª edição: 1979, Livraria Editora Ciências Humanas},</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">isbn</span>      = {Não informado no PDF},</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.4</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A premissa central é que a transição do trabalho escravo ao trabalho livre no Brasil não seguiu o padrão clássico do assalariamento. O ponto mais vulnerável é o risco de naturalizar a singularidade brasileira sem a contrastar sistematicamente com outros casos. A interpretação alternativa mais crível é a de que as relações não capitalistas seriam apenas uma fase transitória de um processo inevitavelmente convergente ao assalariamento “típico”.</td>
<td style="text-align: left;">Por que o capitalismo brasileiro produziu e reproduziu relações não capitalistas de produção? Por que a abolição da escravidão negra não resultou em trabalho assalariado, mas em formas sui generis de sujeição da força de trabalho — o colonato — baseadas na monopolização da propriedade fundiária? Pergunta de natureza explicativa e causal (mecanísmica), centrada no processo histórico da transição entre modos de produção no contexto específico da economia cafeeira de São Paulo.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">As questões secundárias orbitam o núcleo da produção capitalista de relações não capitalistas e têm relação de especificação progressiva com a questão central.</td>
<td style="text-align: left;">(1) Como a Lei de Terras de 1850 funcionou como mecanismo estrutural de coerção do trabalho livre? (2) Como diferentes ondas imigratórias (italiana e espanhola) encontraram configurações distintas da economia cafeeira, revelando a dinâmica evolutiva do colonato? (3) Qual a relação entre a economia cafeeira e a gênese da industrialização em São Paulo? (4) Como a ideologia do “trabalho” foi produzida pela burguesia agrária e industrial para legitimar a exploração de classe? (5) Como o mito do burguês self-made (Matarazzo) funcionou como mecanismo ideológico de reprodução da dominação?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno e relevante além do caso: a coexistência de capitalismo e relações não capitalistas é problema estrutural de economias periféricas e coloniais, não uma anomalia brasileira. A tendência evolucionista que supõe uma transição linear ao assalariamento “clássico” é o alvo crítico explícito.</td>
<td style="text-align: left;">Puzzle explicativo de alta relevância teórica: a economia cafeeira brasileira expandiu-se tanto sob trabalho escravo quanto sob trabalho “livre” sem que o segundo assumisse a forma salarial clássica. Caio Prado Júnior e Florestan Fernandes, entre outros, afirmam que o escravo foi substituído pelo assalariado; Martins demonstra que a substituição produziu o colonato — forma não capitalista de exploração da força de trabalho pelo capital. A explicação desse desvio do padrão canônico da literatura é o coração do puzzle.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese é causal-estrutural e de caráter historicamente fundado. O claim of discovery repousa sobre a reinterpretação da função da propriedade fundiária na acumulação capitalista e da natureza do escravo como renda capitalizada (e não como capital fixo), o que sustenta a análise do colonato como forma não capitalista produzida pelo próprio capital.</td>
<td style="text-align: left;">O <strong>cativeiro da terra</strong> — a monopolização institucional da propriedade fundiária como instrumento de coerção da força de trabalho livre — é a matriz estrutural do capitalismo brasileiro. A Lei de Terras de 1850 instituiu o princípio: “se o trabalho fosse livre, a terra teria que ser escrava.” O colonato resultou não de um atraso pré-capitalista, mas foi produzido pelo próprio capitalismo cafeeiro como solução à crise do trabalho escravo, condicionando a lentidão histórica da constituição das classes sociais e a conformação ideológica da classe trabalhadora. A industrialização, longe de romper com essa matriz, reproduziu-a sob nova roupagem ideológica: o mito da ascensão social pelo trabalho.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O design combina análise teórica marxiana com pesquisa documental histórica de arquivo. Trata-se de uma obra de sociologia histórica com pretensões de teoria social geral a partir de um caso. O principal risco metodológico é a seleção de fontes para confirmar uma tese já constituída. O fichamento cobre a obra inteira (9ª edição revista e ampliada, 2012), que incorpora três capítulos novos (caps. 2, 3 e 6) à obra original de 1979.</td>
<td style="text-align: left;">Sociologia histórica de caráter qualitativo e documental. O autor mobiliza: (a) pesquisa de arquivo extensiva (relatórios do Departamento Estadual do Trabalho, atas do Conselho de Estado, inventários de fazendas, imprensa da época em língua italiana e espanhola, boletins agrícolas, documentação do Departamento de Commerce dos EUA sobre São Paulo); (b) análise teórica marxiana heterodoxa, privilegiando especialmente os volumes 2 e 3 de <em>O capital</em> e os <em>Grundrisse</em>; (c) análise crítica da literatura secundária de referência (Caio Prado Júnior, Celso Furtado, Florestan Fernandes, Warren Dean, Paula Beiguelman, Maria Sylvia de Carvalho Franco). A estratégia argumentativa é a da reconstituição histórica dialética do processo social, oposta ao procedimento classificatório (feudal vs.&nbsp;capitalista).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP envolve seleção de fontes documentais primárias e secundárias para um período e região específicos. Risco de viés de seleção: a documentação disponível (boletins, inventários, relatórios) tende a superamostrar fazendas maiores e mais formalizadas, sub-representando as margens do sistema. A imprensa étnica em língua italiana e espanhola é mobilizada de forma ilustrativa, não sistemática. A unidade de análise oscila entre relações de produção (abstrato) e fazendas/imigrantes individuais (concreto), o que cria às vezes saltos inferências.</td>
<td style="text-align: left;">Fenômeno real: relações de produção no complexo cafeeiro paulista (1850–1930) → observação: documentação de arquivo (relatórios governamentais, inventários, imprensa étnica, correspondências empresariais, censos) → coleta: pesquisa em arquivos estaduais de São Paulo, consulado americano, Junta Comercial do Estado → operacionalização: reconstituição qualitativa do processo de trabalho, da renda capitalizada e da ideologia; → análise: interpretação dialética marxiana → inferência: causal-mecanísmica (o cativeiro da terra produz colonato e ideologia do trabalho). Unidade de análise: relações de produção no nível da fazenda cafeeira; nível de agregação: economia cafeeira de São Paulo, com generalizações ao Brasil.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">Os achados empíricos sobre a imigração espanhola (Cap. 2) e os empresários italianos (Cap. 6) são contribuições documentais substantivas. A reinterpretação do escravo como renda capitalizada (e não capital fixo) é a inovação teórica mais ousada. O claim causal sobre o colonato como produto não capitalista do capitalismo é bem sustentado empiricamente para a economia cafeeira de São Paulo.</td>
<td style="text-align: left;">(1) <strong>Teórica:</strong> Reformulação das categorias marxianas — o escravo não é capital fixo, mas renda capitalizada; o colonato não é pré-capitalismo residual, mas forma não capitalista produzida pelo capital; (2) <strong>Empírica/comparativa:</strong> A comparação entre imigrantes espanhóis (tardios, camponeses, baixa mobilidade) e italianos (precoces, estratificados, maior mobilidade) revela como diferentes momentos da economia cafeeira produziram inserções distintas; (3) <strong>Histórica:</strong> A gênese da Lei de Terras de 1850 é reconstituída como mecanismo deliberado de coerção laboral, complementar à cessação do tráfico negreiro; (4) <strong>Ideológica:</strong> A produção do mito da ascensão social pelo trabalho (culminando no caso Matarazzo) é analisada como mecanismo de legitimação da exploração de classe com efeitos estruturantes até a industrialização.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">A vulnerabilidade principal está no salto da análise de São Paulo para afirmações sobre o “capitalismo brasileiro” em geral. Segundo ponto fraco: a categoria de “renda capitalizada” aplicada ao escravo, embora fecunda, é operacionalizada axiomaticamente, sem um teste contra hipóteses alternativas plausíveis. Terceiro ponto: os capítulos posteriores (5, 6, 7) têm menor densidade teórica e mais caráter ensaístico, reduzindo a coerência do volume.</td>
<td style="text-align: left;">(a) <strong>Viés de seleção de caso:</strong> A análise empírica se concentra quase exclusivamente em São Paulo e nos cafezais, mas as generalizações alcançam “a sociedade brasileira” sem qualificação suficiente; (b) <strong>Compatibilidade DGP-claim:</strong> O claim sobre a gênese do colonato como resposta capitalista à crise da escravidão é bem sustentado, mas os mecanismos ideológicos (Cap. 4 e 7) têm sustentação empírica mais fraca; (c) <strong>Eliminação de hipóteses alternativas:</strong> O autor refuta sistematicamente a hipótese “feudal” e a hipótese “assalariamento clássico”, mas testa menos a hipótese culturalista sobre o ethos do trabalho imigrante; (d) <strong>Ausência de perspectiva de gênero e raça:</strong> O trabalho doméstico das mulheres colonas é estruturalmente invisível na análise do colonato, assim como as trajetórias específicas dos trabalhadores negros após a abolição; (e) <strong>Scope conditions:</strong> A análise é explicitamente sobre São Paulo e o café, mas a tese do “cativeiro da terra” é proposta como matriz nacional.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;">O autor reconhece a concisão de formulações na edição original e a necessidade de expansão; reconhece que a imprensa e os documentos consultados sobre capítulos específicos (como o cap. 6) têm origem fragmentária; reconhece o caráter polêmico e a posição no debate sobre modos de produção da época.</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> Formulações concisas na 1ª edição que foram substituídas por explanações mais largas nesta edição; limitações da pesquisa documental disponível sobre os empresários italianos (cap. 6); reconhecimento do viés do debate latino-americano sobre modos de produção que contextualizou a obra original. <br> <strong>Não reconhecidas ou subestimadas:</strong> A ausência quase total de perspectiva de gênero e raça na análise do colonato e da industrialização; a variação inter-regional (São Paulo vs.&nbsp;Nordeste vs.&nbsp;Minas Gerais) não é sistematicamente controlada; o salto inferencial de “economia cafeeira paulista” para “capitalismo brasileiro” como totalidade; a menor densidade empírica dos capítulos ensaísticos (7) em relação aos teóricos e documentais (1, 3).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A filiação marxiana heterodoxa (marxiana, não marxista) é coerente com o método empírico-dialético adotado. A crítica ao althusserianismo é bem fundamentada. Há, porém, um risco de reificação das categorias marxianas: a “renda capitalizada” é mobilizada como chave explicativa universal sem ser adequadamente operacionalizada em termos mensuráveis. A ontologia é realista-histórica, coerente com o método qualitativo adotado.</td>
<td style="text-align: left;">Marxismo heterodoxo de base marxiana (em oposição explícita ao “marxismo vulgar”, ao estruturalismo althusseriano e ao evolucionismo linear). O autor privilegia os volumes 2 e 3 de <em>O capital</em> (teoria da renda da terra, processo de valorização do capital) e os <em>Grundrisse</em>, normalmente menos mobilizados na literatura brasileira de então. A tradição de referência é a sociologia histórica crítica, com diálogo com a historiografia econômica brasileira (Caio Prado Júnior, Celso Furtado) e com a sociologia das classes (Florestan Fernandes). A ontologia é explicitamente processual e dialética, crítica de qualquer “totalidade fechada”.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo com a literatura secundária é desigual: profundo com os clássicos brasileiros (Caio Prado Júnior, Florestan Fernandes), mas ocasionalmente superficial com autores citados apenas para refutação. A ausência de diálogo com a historiografia agrária mais recente (Sérgio Milliet, Warren Dean são mencionados, mas pouco elaborados) é perceptível.</td>
<td style="text-align: left;">Karl Marx (<em>O capital</em>, vols. 1–3; <em>Grundrisse</em>), Rosa Luxemburg, Florestan Fernandes, Caio Prado Júnior, Celso Furtado, Maria Sylvia de Carvalho Franco, Warren Dean, Paula Beiguelman, Franco Venturi (<em>Il populismo russo</em>), José María Aricó (<em>Marx y América Latina</em>), Louis Couty, Pierre Denis, Paula Beiguelman, Roberto Cochrane Simonsen, György Lukács (crítica ao “marxismo vulgar” de Sweezy).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">Obra de referência fundadora na sociologia histórica brasileira. A 9ª edição (2012) é a versão definitiva do autor, incorporando revisões substantivas e três capítulos novos. Relevante para a dissertação de Tales como: (1) chave interpretativa da Lei de Terras de 1850 como mecanismo estrutural de desigualdade de longo prazo; (2) análise dos mecanismos de coerção não capitalista em economias capitalistas periféricas; (3) articulação entre estrutura econômica e produção ideológica como mecanismo de reprodução da dominação. O fichamento cobre a obra completa. Tipo de texto: livro completo de autor único; entrada BibTeX <code>@book</code>.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 29%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Capítulo</th>
<th style="text-align: left;">Título</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Prefácio</td>
<td style="text-align: left;"><em>Nova edição, revista e ampliada</em></td>
<td style="text-align: left;">Enquadramento histórico e apresentação da tese</td>
<td style="text-align: left;">Enuncia em linguagem acessível a tese central do “cativeiro da terra”: a fórmula “se o trabalho fosse livre, a terra teria que ser escrava”; justifica as alterações da 9ª edição e situa o livro no debate contemporâneo</td>
</tr>
<tr class="even">
<td style="text-align: left;">Apresentação</td>
<td style="text-align: left;"><em>[sem título]</em></td>
<td style="text-align: left;">Fundamento teórico-metodológico</td>
<td style="text-align: left;">Critica o “marxismo vulgar” althusseriano e o evolucionismo linear; apresenta a orientação metodológica marxiana heterodoxa; formula a hipótese da produção capitalista de relações não capitalistas e a reinterpretação do escravo como renda capitalizada</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cap. 1</td>
<td style="text-align: left;">A produção capitalista de relações não capitalistas de produção</td>
<td style="text-align: left;">Estudo de caso analítico central</td>
<td style="text-align: left;">Demonstra empirica e teoricamente que o colonato não era trabalho assalariado, mas forma não capitalista de sujeição da força de trabalho produzida pelo capital; articula a teoria da renda capitalizada ao caso do escravo e ao regime de colonato</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cap. 2</td>
<td style="text-align: left;">Uma imigração tardia</td>
<td style="text-align: left;">Extensão comparativa do argumento</td>
<td style="text-align: left;">Aprofunda a análise do colonato via comparação entre imigrantes espanhóis (tardios) e italianos (precoces); mostra como diferentes momentos da economia cafeeira produziram formas distintas de sujeição e mobilidade do trabalho</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cap. 3</td>
<td style="text-align: left;">Do trabalho escravo ao assalariado nas fazendas de café, 1880–1914</td>
<td style="text-align: left;">Análise empírica da transição</td>
<td style="text-align: left;">Analisa os quatro problemas estruturais da relação população-produção; reconstitui o papel da Lei de Terras e da dívida colonial como mecanismos de sujeição do trabalhador livre; demonstra a longa duração da transição incompleta ao assalariamento</td>
</tr>
<tr class="even">
<td style="text-align: left;">[Álbum fotográfico]</td>
<td style="text-align: left;"><em>[sem título]</em></td>
<td style="text-align: left;">Documentação iconográfica</td>
<td style="text-align: left;">Não fichado; constitui evidência visual da condição dos colonos e das práticas de trabalho nas fazendas de café</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cap. 4</td>
<td style="text-align: left;">As relações de classe e a produção ideológica da noção de trabalho</td>
<td style="text-align: left;">Fundamento ideológico</td>
<td style="text-align: left;">Demonstra como a burguesia agrária e industrial produziu a ideologia do “trabalho” como mecanismo de legitimação da exploração de classe; mostra que a ética do trabalho não era uma característica cultural do imigrante, mas uma produção da burguesia</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cap. 5</td>
<td style="text-align: left;">O café e a gênese da industrialização em São Paulo</td>
<td style="text-align: left;">Revisão crítica de literatura</td>
<td style="text-align: left;">Questiona as interpretações de Celso Furtado e outros sobre a relação entre economia cafeeira e industrialização; propõe uma interpretação alternativa que reconhece a articulação de capitais entre fazendeiros e industriais, dissolvendo a dicotomia agro-industrial</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cap. 6</td>
<td style="text-align: left;">Empresários e trabalhadores de origem italiana no desenvolvimento industrial brasileiro em 1880 e 1914</td>
<td style="text-align: left;">Estudo de caso empírico</td>
<td style="text-align: left;">Desmistifica a trajetória dos imigrantes italianos como empreendedores; distingue as três trajetórias do imigrante italiano (colonato, núcleos coloniais, cidades); reconstitui as condições não capitalistas de absorção da força de trabalho na indústria nascente</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cap. 7</td>
<td style="text-align: left;">O imaginário da ascensão social pelo trabalho / A morte do burguês mítico</td>
<td style="text-align: left;">Síntese ideológica e conclusão implícita</td>
<td style="text-align: left;">Analisa o mito Matarazzo como mecanismo ideológico de reprodução da dominação de classe; mostra como a “morte do burguês mítico” (com o conde Chiquinho) expõe a deterioração do mito da ascensão pelo trabalho e a emergência de uma consciência de classe mais clara, embora ambígua</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="prefácio-nova-edição-revista-e-ampliada-pp.-926" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="prefácio-nova-edição-revista-e-ampliada-pp.-926"><span class="header-section-number">1</span> Prefácio — <em>Nova edição, revista e ampliada</em> (pp.&nbsp;9–26)</h2>
<section id="o-cativeiro-como-matriz-estrutural-cap.pref-15" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="o-cativeiro-como-matriz-estrutural-cap.pref-15"><span class="header-section-number">1.1</span> O cativeiro como matriz estrutural [Cap.Pref §1–§5]</h3>
<p>O Prefácio desta 9ª edição (definitiva, segundo o autor) abre com uma síntese de notável densidade argumentativa, que apresenta a tese central de toda a obra em linguagem deliberadamente acessível. Martins parte de uma constatação: o desenvolvimento capitalista no Brasil não seguiu o modelo consagrado na literatura especializada, mas teve sua própria circunstância histórica. Para compreender essa singularidade, o autor propõe uma diferença fundamental de origem que permanece e regula o presente.</p>
<p>Diante do esgotamento do escravismo e da inevitabilidade do trabalho livre, o Brasil decidiu, em 1850, pela cessação do tráfico negreiro, condenando assim a escravidão. Optou pela imigração estrangeira de trabalhadores livres. Contudo, duas semanas depois da cessação do tráfico, o mesmo Estado aprovou a Lei de Terras, instituindo um novo regime de propriedade em que a condição de proprietário dependia não apenas da condição de homem livre, mas também de pecúlio para a compra da terra. O país selecionaria, por meio de seus agentes na Europa, o imigrante pobre, desprovido de meios, que chegasse ao Brasil sem outra alternativa senão a de trabalhar em latifúndio alheio para eventualmente tornar-se proprietário de sua própria terra.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central do livro</strong>, enunciada no Prefácio: “O país inventou a fórmula simples da coerção laboral do homem livre: se a terra fosse livre, o trabalho tinha que ser escravo; se o trabalho fosse livre, a terra tinha que ser escrava. O cativeiro da terra é a matriz estrutural e histórica da sociedade que somos hoje.”</p>
</div>
</div>
<p>O autor contrasta essa opção brasileira com a norte-americana: doze anos depois, o <em>Homestead Act</em> de Abraham Lincoln optou pela livre ocupação das terras livres como mecanismo de esvaziamento do escravismo, permitindo que mesmo os ex-escravos pudessem se tornar proprietários de terra sem ônus. No modelo brasileiro, a propriedade da terra se institucionalizou como propriedade territorial capitalista, presidindo o processo de instauração e consolidação do capitalismo, acasalando terra e capital e concentrando a repartição da mais-valia. Isso representou o modo brasileiro de acelerar a entrada no mundo moderno — o recurso compensatório da pilhagem colonial que condenara o país ao atraso. A transição para o capitalismo foi, portanto, vagarosa e extraviada em atalhos de inovações sociais e econômicas tópicas.</p>
</section>
<section id="estrutura-e-revisões-da-9ª-edição-cap.pref-612" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="estrutura-e-revisões-da-9ª-edição-cap.pref-612"><span class="header-section-number">1.2</span> Estrutura e revisões da 9ª edição [Cap.Pref §6–§12]</h3>
<p>O Prefácio informa as alterações efetuadas para a edição definitiva. O capítulo 1 recebeu acréscimos significativos, desenvolvendo temas que na edição original ficaram limitados a formulações concisas. Três capítulos inteiramente novos foram incorporados à obra: o capítulo 2 (sobre o imigrante espanhol no colonato, como contraponto comparativo à imigração italiana); o capítulo 3 (sobre o processo de libertação do salário como categoria de mediação, no longo e complexo processo da produção do café); e o capítulo 6 (sobre o desenvolvimento industrial e o imigrante italiano nas duas categorias sociais — empresários e trabalhadores — que protagonizaram a industrialização brasileira nas suas décadas iniciais). A sequência dos capítulos originais foi alterada: o capítulo sobre a produção ideológica da noção de trabalho foi antecipado em relação ao capítulo sobre a gênese da industrialização, pois a ideologia da ascensão social pelo trabalho, embora geneticamente referida ao colonato, tomou conta também da ideologia operária e urbana.</p>
<blockquote class="blockquote">
<p>O autor destaca que a obra tem “um retorno insistente ao tema do cativeiro da terra, suas origens e suas decorrências” ao longo dos sete capítulos, e que ele empreendeu revisão de estilo para uniformizar um texto escrito em diferentes momentos de sua reflexão.</p>
</blockquote>
<hr>
</section>
</section>
<section id="apresentação-pp.-2743" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="apresentação-pp.-2743"><span class="header-section-number">2</span> Apresentação (pp.&nbsp;27–43)</h2>
<section id="crítica-ao-marxismo-vulgar-e-ao-althusserianismo-cap.apres-18" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="crítica-ao-marxismo-vulgar-e-ao-althusserianismo-cap.apres-18"><span class="header-section-number">2.1</span> Crítica ao “marxismo vulgar” e ao althusserianismo [Cap.Apres §1–§8]</h3>
<p>A Apresentação tem função de manifesto metodológico. Martins abre declarando que orienta sua pesquisa teórica e empírica pelo problema da <strong>produção capitalista de relações não capitalistas de produção</strong> no marco da reprodução capitalista do capital de origem não capitalista. Diante dos impasses do debate “feudalismo versus capitalismo” — que tentava classificar a sociedade brasileira em “tipos macroestruturais” —, o autor propõe uma alternativa metodológica que privilegia o concreto histórico em detrimento da nominação conceitual.</p>
<p>A crítica ao marxismo althusseriano e ao “marxismo vulgar” (na definição de Lukács) é central. O autor denuncia a petrificação e reificação da noção de <strong>formação econômico-social</strong>, que passou a substituir funcionalisticamente a noção de “sistema social” sem que o processo de pensamento subjacente tivesse sofrido transformação correspondente. Igualmente, o conceito de <strong>modo de produção</strong> foi reduzido a uma classificação de etapas econômicas (como faz Paul Sweezy), perdendo o conteúdo dialético que Marx lhe atribuiu: modo historicamente determinado de exploração da força de trabalho no processo de produção, no qual são produzidas também as relações sociais fundamentais e as representações que as legitimam ideologicamente.</p>
<blockquote class="blockquote">
<p><strong>Nota 1:</strong> O autor critica especificamente a obra de Marta Harnecker como exemplo de vulgarização althusseriana que vincula o conceito de formação econômico-social a espaços geográficos (“América Latina”), produzindo uma totalidade fechada e a-histórica. [nota incluída por relevância argumentativa]</p>
</blockquote>
<p>A partir da Universidade de Louvain, uma corrente do althusserianismo marcada pela articulação entre estrutura e superestrutura teria chegado ao Brasil com grande impacto nos autores da Teologia da Libertação. Nesse contexto, a religião seria protegida no âmbito mecanicista da superestrutura, ganhando legitimidade no corpo do marxismo mas perdendo seu caráter próprio ao ser reduzida a epifenômeno da materialidade social.</p>
</section>
<section id="a-hipótese-central-e-as-inovações-teóricas-cap.apres-917" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="a-hipótese-central-e-as-inovações-teóricas-cap.apres-917"><span class="header-section-number">2.2</span> A hipótese central e as inovações teóricas [Cap.Apres §9–§17]</h3>
<p>O caminho metodológico escolhido é o marxiano ortodoxo: privilegiar o concreto, o processo social em sua dimensão histórica. O que Martins define como descoberta e inovação interpretativa decorre desse procedimento: a observação de que o próprio capital engendra e reproduz relações não capitalistas de produção, numa coexistência de <strong>tempos sociais de datas entre si diversas</strong>. O acesso privilegiado a essa constatação se dá pela reflexão sobre a análise que Marx faz da <strong>renda territorial</strong> na sociedade capitalista.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hipótese central da Apresentação:</strong> A renda da terra, sendo de origem pré-capitalista, contraditória e obstáculo à expansão do capital, perde esse caráter à medida que é absorvida pelo processo do capital e se transforma em <strong>renda territorial capitalizada</strong>. Isso introduz uma irracionalidade na reprodução do capital que é superada pela repartição da mais-valia sob forma de lucro, juro ou renda. Martins estende esse raciocínio para além das relações pré-capitalistas, incluindo o que Marx e Rosa Luxemburg definiram como relações não capitalistas, permitindo analisar o colonato como forma historicamente criada na substituição do trabalhador escravo.</p>
</div>
</div>
<p>A segunda inovação teórica fundamental é a interpretação do <strong>escravo como renda capitalizada</strong> e não como capital fixo. Essa formulação, segundo Martins, é essencial para repensar a questão da exploração do trabalho do período colonial à atualidade e a questão da renda fundiária no Brasil. O autor fundamenta essa interpretação no próprio Marx, que situa a escravidão no marco teórico da renda fundiária — aspecto sistematicamente omitido pela literatura brasileira com efeitos teóricos e políticos graves.</p>
<blockquote class="blockquote">
<p><strong>Nota 2:</strong> A crítica à omissão da teoria da renda territorial em autores brasileiros de referência é direta e polêmica: “Essa omissão tem representado não somente um atraso teórico nas análises das ciências humanas entre nós, mas, sobretudo, um atraso político.” [nota incluída por relevância argumentativa]</p>
</blockquote>
<p>A Apresentação conclui situando a pesquisa no movimento do capital em seu conjunto: a transição do escravismo para o trabalho assalariado em São Paulo foi um processo planejado, controlado e relativamente lento — de quase 40 anos — por iniciativa dos próprios fazendeiros de café, que eram ao mesmo tempo investidores em empreendimentos ferroviários, comerciais, financeiros e industriais. Essa singularidade histórica reveste o processo do capital de características que o diferenciam substantivamente do modelo de referência da literatura histórica e sociológica internacional.</p>
<hr>
</section>
</section>
<section id="capítulo-1-a-produção-capitalista-de-relações-não-capitalistas-de-produção-pp.-45145" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="capítulo-1-a-produção-capitalista-de-relações-não-capitalistas-de-produção-pp.-45145"><span class="header-section-number">3</span> Capítulo 1: A produção capitalista de relações não capitalistas de produção (pp.&nbsp;45–145)</h2>
<section id="a-dinâmica-dos-contrários-refutação-do-consenso-cap.1-19" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="a-dinâmica-dos-contrários-refutação-do-consenso-cap.1-19"><span class="header-section-number">3.1</span> A dinâmica dos contrários: refutação do consenso [Cap.1 §1–§9]</h3>
<p>Martins abre o capítulo central da obra desafiando o consenso da literatura especializada. O lugar-comum entre historiadores, sociólogos, economistas e cientistas políticos é que a servidão negra foi substituída pelo trabalho assalariado. Caio Prado Júnior afirma que a lavoura cafeeira baseou-se em escravos negros “substituídos mais tarde por trabalhadores assalariados”; Florestan Fernandes assinala que, com a abolição, as tendências de reintegração da ordem social e econômica “expeliu o negro e o mulato do sistema capitalista de relações de produção no campo”. Autores mais recentes são ainda mais enfáticos: “com a imigração massiva, o trabalho escravo cedeu lugar ao trabalho assalariado nas plantações de café.”</p>
<p>O procedimento teórico que Martins critica é de natureza epistemológica: a projeção do capital personificado pelo fazendeiro sobre as relações de produção internas à fazenda. Como o fazendeiro-capitalista personificava o capital comercial, inferiu-se daí que as relações de produção da fazenda seriam capitalistas. Esse procedimento é equivocado porque descarta a reconstituição das mediações reais entre o capital e o trabalho. O importante, insiste Martins, é descobrir <strong>que forma de capital</strong> o fazendeiro personificava — e a resposta é que ele personificava o capital comercial, cuja racionalidade se esgotava no nível da circulação das mercadorias.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conceito-chave: colonato</strong> — Regime de trabalho que prevaleceu nas fazendas de café por cerca de um século (até fins dos anos 1950). Baseado na produção direta dos meios de vida pelo próprio trabalhador (trato dos cafezais, roça de alimentos, cultivo intercalar), combinada com pagamento em dinheiro por tarefas específicas (carpa, colheita). Não era trabalho assalariado: o salário não era a mediação central da relação entre capital e trabalho.</p>
</div>
</div>
</section>
<section id="a-natureza-do-escravo-como-renda-capitalizada-cap.1-1018" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="a-natureza-do-escravo-como-renda-capitalizada-cap.1-1018"><span class="header-section-number">3.2</span> A natureza do escravo como renda capitalizada [Cap.1 §10–§18]</h3>
<p>A transformação das relações de produção originou-se na esfera da circulação, na crise do comércio de escravos que produziu seus efeitos mais drásticos a partir de 1850, quando o tráfico negreiro foi definitivamente proibido. A hegemonia do comércio na determinação das relações de produção na economia colonial é sublinhada: nessa economia, não só o produto do trabalho, mas o próprio trabalhador, era objeto de comércio. O escravo, antes de ser produtor direto, tinha que ser objeto de comércio — tinha que produzir lucro já antes de começar a produzir mercadoria.</p>
<p>A exploração do escravo no processo produtivo estava, portanto, precedida de parâmetros e relações comerciais que a determinavam. O fazendeiro calculava o rendimento do escravo pela taxa de juros de mercado, pelo lucro médio que equivaleria ao rendimento de seu capital se aplicado em outro negócio. A consequência teórica fundamental é que o escravo não entrava no processo de trabalho como capital fixo (meio de produção), mas como <strong>renda capitalizada</strong> — como tributo antecipado ao fornecedor de mão de obra (o traficante), equivalente à lógica da renda territorial capitalizada. Tanto a terra quanto o escravo têm em comum o fato de não serem produtos do trabalho, de não terem valor no sentido marxiano, mas terem preço — preço determinado pela capitalização de uma renda esperada.</p>
<blockquote class="blockquote">
<p><strong>Nota 3:</strong> Martins apoia-se em Marx para demonstrar que o preço do escravo correspondia à capitalização de sua mais-valia esperada: “O preço que se paga pelo escravo não é senão a mais-valia ou lucro futuro capitalizado”, citando como referência as análises de Louis Couty sobre a economia cafeeira. [nota incluída por relevância argumentativa]</p>
</blockquote>
</section>
<section id="o-colonato-como-relação-não-capitalista-produzida-pelo-capital-cap.1-1934" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="o-colonato-como-relação-não-capitalista-produzida-pelo-capital-cap.1-1934"><span class="header-section-number">3.3</span> O colonato como relação não capitalista produzida pelo capital [Cap.1 §19–§34]</h3>
<p>A crise do escravismo engendrou o colonato como a modalidade de trabalho que superaria o escravo — o trabalho livre, ainda não o trabalho assalariado. O trabalhador livre que veio substituir o escravo não diferia dele por estar divorciado dos meios de produção — característica comum a ambos. Diferia na medida em que o trabalho livre se baseava na separação do trabalhador de sua <strong>força de trabalho</strong>, que no escravo se confundiam.</p>
<p>A contradição que permeia a emergência do trabalho livre expressa-se na transformação das relações de produção como meio para preservar a economia colonial de exportação: tratava-se de <strong>mudar para manter</strong>. As relações de produção se transformaram, mas o produto (o café) e o processo de trabalho permaneceram essencialmente os mesmos. O colono continuou a fazer exatamente o que o escravo fazia — mudando apenas a forma social da organização do trabalho, do trabalho coletivo do eito para o trabalho familiar.</p>
<p>O colonato era, portanto, a solução capitalista para a crise do trabalho escravo que preservava a racionalidade da economia de exportação sem instaurar plenamente as relações capitalistas de produção. A sujeição do trabalho, que no cativeiro se dava pela coerção física, passou a se dar por mecanismos econômicos não salariais: o endividamento do colono (pela dívida da passagem, pelo endividamento na venda de produtos no armazém do fazendeiro), a dependência da roça de alimentos (meio de vida produzido diretamente pelo trabalhador), e a exclusão do acesso à propriedade da terra pela Lei de Terras.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Mecanismo estrutural do cativeiro da terra
</div>
</div>
<div class="callout-body-container callout-body">
<p>O nexo estrutural central da argumentação de Martins: a Lei de Terras de 1850 não foi uma política fundiária qualquer — foi o instrumento jurídico-institucional que converteu a terra em equivalente de capital, tornando a compra o único acesso legítimo à propriedade. Isso produziu artificialmente uma superpopulação relativa fictícia — uma “falsa carência de terras” para o trabalho familiar — que tornava compulsório o trabalho dos imigrantes pobres nas fazendas de café. O cativeiro da terra era, portanto, a própria condição de possibilidade do trabalho “livre” como forma de sujeição não capitalista ao capital.</p>
</div>
</div>
</section>
<section id="renda-fundiária-e-reprodução-capitalista-do-capital-cap.1-3552" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="renda-fundiária-e-reprodução-capitalista-do-capital-cap.1-3552"><span class="header-section-number">3.4</span> Renda fundiária e reprodução capitalista do capital [Cap.1 §35–§52]</h3>
<p>A longa seção central do capítulo aprofunda a análise teórica da renda territorial no capitalismo brasileiro. Martins retoma a análise marxiana da renda fundiária e suas três formas — renda em trabalho, renda em espécie e renda em dinheiro — para demonstrar que o colonato era essencialmente uma forma de <strong>renda em trabalho e em espécie</strong> que se revestia superficialmente da forma monetária nas parcelas de pagamento em dinheiro. O capital do fazendeiro não era um capital que se realizava predominantemente como capital industrial ou produtivo, mas como capital que obtinha renda fundiária capitalizada.</p>
<p>O fazendeiro de café, ao mesmo tempo rentista e capitalista, exemplificava a unicidade de capital e propriedade da terra que inaugurou e difundiu rapidamente no Brasil “a modernidade desse capitalismo singular”. A expansão para zonas novas (a terra-roxa de Ribeirão Preto e da Alta Mogiana), movida pela renda diferencial da terra mais fértil, e a diversificação dos investimentos dos fazendeiros em ferrovias, bancos, indústrias e empresas comerciais a partir da última década do século XIX, compõem o quadro de um empresário híbrido — o “fazendeiro-capitalista” — que não era simplesmente um proprietário fundiário pré-capitalista.</p>
<blockquote class="blockquote">
<p><strong>Nota 4:</strong> Martins registra que a contabilidade das fazendas cafeeiras era organizada com base em livros de contas-correntes — contabilidade de circulação, não de custos —, indicando que a racionalidade do capital personificada pelo fazendeiro se esgotava no nível da circulação das mercadorias. A ausência de contabilidade de custos nas fazendas é tomada como evidência da natureza comercial (e não industrial) do capital cafeeiro.</p>
</blockquote>
</section>
<section id="imigração-subsidiada-e-a-produção-artificial-da-escassez-de-terras-cap.1-5372" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="imigração-subsidiada-e-a-produção-artificial-da-escassez-de-terras-cap.1-5372"><span class="header-section-number">3.5</span> Imigração subsidiada e a produção artificial da escassez de terras [Cap.1 §53–§72]</h3>
<p>Martins analisa detidamente o mecanismo pelo qual o Estado brasileiro produziu a superpopulação relativa necessária à sujeição do trabalho livre. A imigração em massa subsidiada pelo Estado — cujos custos de transporte e alojamento eram socializados pela Fazenda Pública — foi o instrumento político central. O imigrante chegava ao Brasil “desprovido de meios”, sob a tutela do fazendeiro, condicionado a trabalhar na fazenda por tempo indeterminado antes de poder acumular o pecúlio necessário à compra de terra.</p>
<p>A Lei de Terras de 1850 e a política de imigração subsidiada funcionavam como sistema integrado de coerção não capitalista da força de trabalho. Aqui reside o “cativeiro da terra”: a terra livre, monopolizada pelo Estado e pelos fazendeiros, tornava o trabalho livre compulsório. O Conselho de Estado, em consulta de 1842 já na fase de gestação da Lei de Terras, enunciou com clareza o princípio: “tornar mais custosa a aquisição de terras” para garantir que o imigrante pobre alugasse “o seu trabalho efetivamente por algum tempo, antes de obter meios de se fazer proprietário.”</p>
</section>
<section id="composição-orgânica-do-capital-e-trabalho-no-colonato-cap.1-7392" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="composição-orgânica-do-capital-e-trabalho-no-colonato-cap.1-7392"><span class="header-section-number">3.6</span> Composição orgânica do capital e trabalho no colonato [Cap.1 §73–§92]</h3>
<p>A seção final do capítulo articula a análise da produção de café à teoria marxiana da composição orgânica do capital. A produção de café se baseava em uma aparente alta composição orgânica do capital (dado o alto custo das terras e dos cafezais em implantação), mas na verdade escondia uma baixíssima composição porque o trabalhador colono produzia diretamente uma parcela considerável dos seus próprios meios de vida (roça, horta, galinhas). Isso significava que o capital não precisava desembolsar o equivalente integral do valor da força de trabalho — parte desse valor era produzida pelo próprio trabalhador dentro da fazenda, mediante acesso concedido pelo fazendeiro à terra para cultivo de subsistência.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Implicação teórica para a teoria da mais-valia
</div>
</div>
<div class="callout-body-container callout-body">
<p>A produção direta dos meios de vida pelo colono equivalia a uma forma de extração de mais-valia absoluta disfarçada de relação não monetária: o fazendeiro se apropriava de trabalho não pago (o trato dos cafezais e a colheita) e ao mesmo tempo não precisava pagar integralmente a reprodução da força de trabalho (que era parcialmente garantida pela roça e pela horta). O colonato era, portanto, não apenas uma relação não capitalista de produção, mas uma forma de extração intensificada de mais-valia através de mecanismos não salariais.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="capítulo-2-uma-imigração-tardia-pp.-147189" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="capítulo-2-uma-imigração-tardia-pp.-147189"><span class="header-section-number">4</span> Capítulo 2: Uma imigração tardia (pp.&nbsp;147–189)</h2>
<section id="o-pressuposto-homogeneizante-e-a-diferença-italiana-espanhola-cap.2-16" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="o-pressuposto-homogeneizante-e-a-diferença-italiana-espanhola-cap.2-16"><span class="header-section-number">4.1</span> O pressuposto homogeneizante e a diferença italiana-espanhola [Cap.2 §1–§6]</h3>
<p>O segundo capítulo parte de uma constatação empírica: é lugar-comum tratar os imigrantes de diferentes nacionalidades como se tivessem cumprido uma mesma trajetória no Brasil. O perfil do “imigrante típico” na literatura é o do imigrante italiano — e o imigrante espanhol é geralmente subsumido nessa categoria. Martins argumenta que essa homogeneização encobre diferenças importantes que revelam, na verdade, transformações nas próprias relações de trabalho.</p>
<p>A perspectiva comparativa adotada não tem como objetivo principal o imigrante espanhol em si, mas usar a diferença representada por ele para analisar a dinâmica do colonato e suas transformações ao longo do tempo. A diferenciação do trabalhador rural pela nacionalidade encobria um fato crucial: a diferença de nacionalidade frequentemente escondia <strong>mudanças nas relações de trabalho</strong> e nas relações entre renda fundiária e acumulação de capital.</p>
</section>
<section id="diferenças-estruturais-entre-as-imigrações-italiana-e-espanhola-cap.2-716" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="diferenças-estruturais-entre-as-imigrações-italiana-e-espanhola-cap.2-716"><span class="header-section-number">4.2</span> Diferenças estruturais entre as imigrações italiana e espanhola [Cap.2 §7–§16]</h3>
<p>O imigrante italiano chegou ao Brasil em um momento em que o colonato estava emergindo de diferentes experimentos de parceria e empreitada, quando a questão do trabalho livre ainda estava relativamente aberta. As reações dos imigrantes italianos às formas assumidas pela exploração do trabalho, mesmo dispersas e desarticuladas, tiveram papel decisivo na demolição das concepções escravistas escondidas por trás da dominação pessoal do fazendeiro e do endividamento do trabalhador.</p>
<p>O imigrante espanhol chegou em momento substancialmente diferente. A partir de 1905, quando a imigração italiana subvencionada foi interrompida pelo Decreto Prinetti (que proibiu a emigração subsidiada para o Brasil a partir da Itália), a imigração espanhola tornou-se a mais numerosa por alguns anos. Esses imigrantes se destinaram a zonas novas, menos férteis, onde a expansão do café avançava sobre terras de menor qualidade. Diferentemente dos italianos, a imigração espanhola era <strong>predominantemente de camponeses</strong> — sem a estratificação de classes da italiana, que incluía comerciantes, capitalistas, artesãos, intelectuais e operários.</p>
<blockquote class="blockquote">
<p><strong>Nota 5:</strong> O autor cita um jornal de língua espanhola editado em São Paulo, de 1904: “Com quantos capitalistas, comerciantes, industriais, etc., etc., conta a colônia [espanhola]?” — a questão retórica ilustra a homogeneidade proletária da imigração espanhola. No censo de 1920, havia apenas 267 estabelecimentos industriais pertencentes a espanhóis em todo o Brasil, contra 2.119 italianos, sendo estas igualmente pequenas. [nota incluída por relevância argumentativa]</p>
</blockquote>
</section>
<section id="o-colonato-em-transformação-da-sujeição-à-monetização-parcial-cap.2-1727" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="o-colonato-em-transformação-da-sujeição-à-monetização-parcial-cap.2-1727"><span class="header-section-number">4.3</span> O colonato em transformação: da sujeição à monetização parcial [Cap.2 §17–§27]</h3>
<p>Uma das principais modificações nas relações de trabalho, imposta em grande parte pela ação e pressão dos próprios imigrantes italianos, foi a ampliação do pagamento em dinheiro e o acerto mensal (em vez do acerto anual) com o trabalhador. Quando o imigrante espanhol chegou, o colonato já estava modificado por essas pressões. A perspectiva do imigrante espanhol estava, portanto, mais próxima do trabalho assalariado — resultante da lenta desagregação do colonato.</p>
<p>O pagamento em dinheiro era, contudo, um ardil que em termos reais empobreceu o imigrante espanhol ainda mais. Um caso ilustrativo de 1908: um colono espanhol com mulher e três filhos, ao fim de um mês de trabalho, recebeu apenas Rs. 24$000 — insuficientes para a sobrevivência da família. No colonato típico, ao menos o trabalhador podia subsistir com o produto da horta e da agricultura intercalar. Os imigrantes espanhóis desse período estão entre os mais pobres e os de menor mobilidade social.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Implicação comparativa
</div>
</div>
<div class="callout-body-container callout-body">
<p>O capítulo 2 funciona como um experimento quase natural dentro do colonato: ao comparar imigrantes de características similares (ambos pobres, majoritariamente rurais) que chegaram em momentos distintos e em condições distintas do mercado de trabalho cafeeiro, Martins isola analiticamente a variável “momento histórico do colonato” para explicar trajetórias diferenciadas. O imigrante espanhol, chegando numa fase de maior monetização e deterioração das condições do colonato, obteve pior resultado mesmo sendo individualmente similar ao italiano.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="capítulo-3-do-trabalho-escravo-ao-assalariado-nas-fazendas-de-café-18801914-pp.-191257" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="capítulo-3-do-trabalho-escravo-ao-assalariado-nas-fazendas-de-café-18801914-pp.-191257"><span class="header-section-number">5</span> Capítulo 3: Do trabalho escravo ao assalariado nas fazendas de café, 1880–1914 (pp.&nbsp;191–257)</h2>
<section id="quatro-problemas-população-produção-e-força-de-trabalho-cap.3-17" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="quatro-problemas-população-produção-e-força-de-trabalho-cap.3-17"><span class="header-section-number">5.1</span> Quatro problemas: população, produção e força de trabalho [Cap.3 §1–§7]</h3>
<p>A tese principal deste capítulo é que ao modo de explorar a força de trabalho nas fazendas de café corresponderam momentos específicos do movimento da população — especialmente a imigração estrangeira e as migrações internas. Tanto a tese de uma transição do trabalho escravo ao trabalho assalariado quanto a tese de que a imigração teria uma dinâmica convergente são recusadas. O autor enuncia quatro problemas estruturais que organizam o capítulo:</p>
<p>O primeiro problema é: por que, dispondo o país de uma grande massa de homens livres e pobres no campo, teve o café que recorrer à imigração estrangeira para substituir o escravo? O segundo problema: por que o escravo não foi substituído por trabalhadores assalariados, mas por formas não capitalistas de exploração da força de trabalho (parceria, colonato)? O terceiro problema: como se combinaram a dinâmica da população e a dinâmica da produção? O quarto problema: qual a relação entre as características do movimento populacional e o modo de organizar o trabalho na fazenda?</p>
</section>
<section id="a-dívida-e-a-roça-como-mecanismos-de-sujeição-cap.3-818" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="a-dívida-e-a-roça-como-mecanismos-de-sujeição-cap.3-818"><span class="header-section-number">5.2</span> A dívida e a roça como mecanismos de sujeição [Cap.3 §8–§18]</h3>
<p>O autor examina detidamente as respostas aos quatro problemas estruturais. A principal razão pela qual o café recorreu à imigração estrangeira em vez de incorporar os camponeses livres brasileiros residia não em razões de competência ou cultura, mas na própria estrutura das relações de sujeição necessárias ao colonato. Os camponeses livres do campo brasileiro — caboclos, caipiras, moradores de fazenda — haviam construído ao longo de gerações formas de vida e trabalho que os tornavam relativamente resistentes à sujeição total ao fazendeiro. Já o imigrante estrangeiro chegava completamente desprovido de meios, sem rede de proteção, sem terra, sem parentes estabelecidos — condição que o tornava maximamente dependente do fazendeiro.</p>
<p>A dívida da passagem era o mecanismo inaugural de sujeição: ao chegar ao Brasil com a passagem paga pelo fazendeiro (ou pelo governo), o imigrante imediatamente acumulava um débito que precisaria saldar com o trabalho. Sobre esse débito incidiam juros. A isso se somavam as compras no armazém do fazendeiro — frequentemente o único fornecedor na fazenda —, que eram debitadas nas contas-correntes do colono. O resultado era um sistema de endividamento perpétuo análogo ao peonage norte-americano: o colono que quisesse mudar de fazenda precisava que o novo fazendeiro “comprasse” sua dívida do anterior.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Sujeição por dívida como forma de trabalho não capitalista
</div>
</div>
<div class="callout-body-container callout-body">
<p>A subjugação por dívida anulava completamente não só a liberdade de trabalho do colono, mas também a sua liberdade civil. O casamento de um colono dependia do assentimento do patrão; a ausência não autorizada da fazenda era motivo de tensão severa. Martins demonstra que a distância entre a condição de um escravo negro e a de um colono italiano, no plano prático, era muito menor do que a distância jurídica entre os dois regimes sugere.</p>
</div>
</div>
</section>
<section id="a-lei-de-terras-de-1850-como-mecanismo-estrutural-cap.3-1932" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="a-lei-de-terras-de-1850-como-mecanismo-estrutural-cap.3-1932"><span class="header-section-number">5.3</span> A Lei de Terras de 1850 como mecanismo estrutural [Cap.3 §19–§32]</h3>
<p>A seção sobre a Lei de Terras é a mais densa do capítulo. A lei de 1850 não foi uma política fundiária neutra — foi um instrumento deliberado de criação das condições de sujeição do trabalho imigrante. Uma consulta do Conselho de Estado, já em 1842, na fase de gestação da lei, estabelecia com clareza o princípio: tornando mais custosa a aquisição de terras, garantia-se que o imigrante pobre alugasse seu trabalho por algum tempo antes de obter meios de se tornar proprietário.</p>
<p>O longo debate de mais de trinta anos que precedeu a aprovação da lei havia considerado a alternativa da reforma agrária — a fragmentação do latifúndio e a disseminação da pequena propriedade — como instrumento de separação entre a propriedade da terra e a do capital, pressuposto da libertação do capital e da emancipação do capitalismo. Essa alternativa foi derrotada. Os grandes proprietários, já modernos no momento da transição para o trabalho livre porque conscientes de que sua riqueza era tolhida pela escravidão, optaram pela conversão da terra em equivalente de mercadoria — instrumento de coerção do trabalho livre.</p>
<blockquote class="blockquote">
<p><strong>Nota 6:</strong> O Registro Paroquial de Terras, determinado pela Lei de Terras em 1854, era o instrumento de consolidação da propriedade fundiária. Os leitores dos Registros de diferentes regiões constatam que os posseiros — muitos dos quais mestiços remanescentes da escravidão indígena — foram frequentemente levados ao pároco para declarar expressamente que as terras que ocupavam eram do fazendeiro, não deles. Nesse ato, sem o saber, renunciavam ao direito que a própria lei lhes conferia. Era a “suave” violência cultural e política da dominação patrimonial.</p>
</blockquote>
</section>
<section id="formas-de-trabalho-e-movimento-da-população-cap.3-3352" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="formas-de-trabalho-e-movimento-da-população-cap.3-3352"><span class="header-section-number">5.4</span> Formas de trabalho e movimento da população [Cap.3 §33–§52]</h3>
<p>O capítulo analisa em detalhe as formas específicas de organização do trabalho no colonato e sua relação com o movimento da população. Entre 1877 e 1914, a região cafeeira de São Paulo recebeu 1.779.470 imigrantes, dos quais 845.816 eram italianos. O movimento de população estava diretamente determinado pelo modo de exploração da força de trabalho e pelo modo de criação da riqueza através do café.</p>
<p>O colonato era fundamentalmente baseado no trabalho familiar: o colono contratava por família, não por indivíduo. Isso explica a predominância de famílias nas correntes migratórias subsidiadas. A contratação familiar permitia ao fazendeiro obter simultaneamente o trabalho do colono, da esposa e dos filhos, pagando apenas um salário parcial ao chefe de família. O trabalho das mulheres e das crianças — essencial para a carpa dos cafezais e para a roça de alimentos — era assim incorporado ao processo produtivo sem custo adicional para o capital.</p>
<blockquote class="blockquote">
<p><strong>Nota 7:</strong> O autor distingue o colhedor assalariado temporário (camarada) do colono: o primeiro era um trabalhador sem vínculo permanente com a fazenda, contratado especificamente para a colheita, que recebia pagamento em dinheiro por quantidade colhida. A existência desse trabalhador assalariado temporário não deve ser confundida com a transformação geral do colonato em relação salarial. [nota incluída por relevância argumentativa]</p>
</blockquote>
<p>A fase de beneficiamento moderno do café — com máquinas secadoras e descascadeiras — inaugurou uma nova frente de monetização da relação de trabalho: as tarefas de beneficiamento eram contratadas separadamente e pagas em dinheiro por unidade produzida, em contraste com as tarefas de trato (carpa) e colheita, que compunham o núcleo do colonato. Essa segmentação gradualmente enfraqueceu a lógica interna do colonato e abriu caminho para formas mais próximas do assalariamento.</p>
<hr>
</section>
</section>
<section id="capítulo-4-as-relações-de-classe-e-a-produção-ideológica-da-noção-de-trabalho-pp.-283305" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="capítulo-4-as-relações-de-classe-e-a-produção-ideológica-da-noção-de-trabalho-pp.-283305"><span class="header-section-number">6</span> Capítulo 4: As relações de classe e a produção ideológica da noção de trabalho (pp.&nbsp;283–305)</h2>
<section id="trabalho-livre-e-origem-do-contingente-operário-cap.4-17" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="trabalho-livre-e-origem-do-contingente-operário-cap.4-17"><span class="header-section-number">6.1</span> Trabalho livre e origem do contingente operário [Cap.4 §1–§7]</h3>
<p>O capítulo analisa a produção ideológica da noção de trabalho como contribuição ao entendimento das relações de classe na sociedade brasileira. O trabalho, sendo o núcleo das relações de classe, possibilita a compreensão das formas do conflito social e do que, aparentemente, surge na cena política como acomodação entre classes historicamente contrapostas.</p>
<p>O contingente de trabalhadores livres no Brasil era constituído predominantemente de imigrantes estrangeiros — italianos, espanhóis, portugueses, alemães — com experiência basicamente rural e camponesa, não operária. O processo de acumulação primitiva que separa o trabalhador de seus meios de produção ocorreu <strong>fora</strong> da sociedade brasileira, nas sociedades de origem: a própria emigração foi episódio dessa expropriação original. A sociedade brasileira recebeu o trabalhador livre sem ter realizado a acumulação responsável por tal liberação — a terra permaneceu monopolizada pelos grandes proprietários e pelo Estado.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conceito-chave: acumulação primitiva à brasileira</strong> — A Lei de Terras de 1850, ao determinar o Registro Paroquial das terras, produziu na prática o nosso tênue equivalente da acumulação primitiva: a expropriação legal e “suave” dos posseiros — especialmente mestiços remanescentes da escravidão indígena —, que foram levados a registrar em nome do fazendeiro terras que eram efetivamente suas, pela dominação patrimonial que os reduzia a seres sem vontade própria.</p>
</div>
</div>
</section>
<section id="a-ética-do-trabalho-como-produção-burguesa-cap.4-818" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="a-ética-do-trabalho-como-produção-burguesa-cap.4-818"><span class="header-section-number">6.2</span> A ética do trabalho como produção burguesa [Cap.4 §8–§18]</h3>
<p>A interpretação conservadora e restauracionista que o imigrante desenvolveu sobre sua trajetória — a ideia de que a sociedade brasileira oferecia de volta o que lhe haviam tirado no país de origem — criou o terreno subjetivo para a ideologia do <em>fare l’America</em>: a ascensão social pelo trabalho. Mas Martins demonstra que essa ética não era uma característica cultural ou psicológica do imigrante — era uma <strong>produção da burguesia</strong>.</p>
<p>O advento do trabalho livre separou a pessoa do trabalhador da sua força de trabalho. Os mecanismos ideológicos que legitimavam a sujeição da pessoa pela desigualdade de origem (brancos como filhos de Abel, negros como filhos de Caim) perderam eficácia. A sujeição da pessoa foi substituída pela sujeição do trabalho ao capital. Sob a igualdade jurídica formal entre patrão e operário, como justificar que um ficasse cada vez mais rico e o outro não? Essa é a indagação oculta que norteia todo o debate sobre a Abolição.</p>
<p>A resposta elaborada pela burguesia foi reconhecer que o trabalho é a fonte da riqueza — mas manipular esse reconhecimento de modo a torná-lo instrumento da dominação. O caminho: era preciso trabalhar para enriquecer; mas como a terra era monopolizada, o trabalhador precisava trabalhar para um terceiro (fazendeiro, patrão) para ganhar o dinheiro que comprasse a terra que supostamente o enriqueceria. A riqueza não frutificaria do trabalho que se acrescentava à riqueza já criada, mas da ética que associava trabalho e privação. A vida penosa e sofrida resultante da exploração legitimava-se na concepção do trabalho como condição da riqueza própria.</p>
<blockquote class="blockquote">
<p><strong>Nota 8:</strong> O autor destaca que a Lei de Terras consagrava, ao mesmo tempo em que o criava, o que não existia plenamente: a terra como equivalente de capital. Ao tornar o acesso à terra dependente da compra, mobilizou as instituições jurídicas e policiais na defesa da propriedade fundiária, garantindo o caráter compulsório da venda da força de trabalho.</p>
</blockquote>
</section>
<section id="a-origem-comercial-e-o-caráter-de-classe-da-abolição-cap.4-1930" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="a-origem-comercial-e-o-caráter-de-classe-da-abolição-cap.4-1930"><span class="header-section-number">6.3</span> A origem comercial e o caráter de classe da abolição [Cap.4 §19–§30]</h3>
<p>O capítulo avança para uma análise da gênese histórica da escravidão negra como determinada pelo comércio — e não o contrário. A produção fundada no trabalho escravo resultou do comércio de escravos. Daí que o tráfico negreiro constituísse o ponto nuclear e sensível da escravidão: extinto o tráfico, a escravidão estava condenada. A economia colonial brasileira pode ser redefinida como regime em que a produção é subjugada pelo comércio — não só o produto do trabalho, mas o próprio trabalhador, é objeto de comércio.</p>
<p>A abolição não foi processo estritamente interno: resultou em grande parte de pressões da Inglaterra, que havia abolido a escravidão nas Índias Ocidentais em 1833 e pressionava o Brasil para eliminar a concorrência “desleal” do açúcar escravista brasileiro com o açúcar colonial britânico. A dimensão internacional da abolição — vinculada a interesses de diferentes grupos de pressão nas relações comerciais entre os impérios — é assim incorporada à análise.</p>
<hr>
</section>
</section>
<section id="capítulo-5-o-café-e-a-gênese-da-industrialização-em-são-paulo-pp.-307355" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="capítulo-5-o-café-e-a-gênese-da-industrialização-em-são-paulo-pp.-307355"><span class="header-section-number">7</span> Capítulo 5: O café e a gênese da industrialização em São Paulo (pp.&nbsp;307–355)</h2>
<section id="a-controvérsia-na-literatura-furtado-simonsen-e-a-industrialização-inconsciente-cap.5-19" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="a-controvérsia-na-literatura-furtado-simonsen-e-a-industrialização-inconsciente-cap.5-19"><span class="header-section-number">7.1</span> A controvérsia na literatura: Furtado, Simonsen e a industrialização “inconsciente” [Cap.5 §1–§9]</h3>
<p>Este capítulo é uma revisão crítica da literatura sobre a industrialização brasileira. Martins identifica falhas em estudos referenciais: afirmações, hipóteses e conclusões que são negadas pelos fatos empíricos. A tendência ao esquematismo — apoiado no que se conhece dos países de referência da história da industrialização — induz à leitura seletiva das informações e a conclusões questionáveis.</p>
<p>O ponto de partida é a crítica a Celso Furtado (<em>Formação econômica do Brasil</em>): a obra surpreende pela ausência de um capítulo sobre as origens da indústria no Brasil, passando diretamente da transição para o trabalho assalariado (século XIX) à transição para o sistema industrial (século XX) sem esclarecer a gênese industrial. Furtado argumenta que a política do governo durante a Crise de 1929 — a compra e queima do café com crédito interno — produziu uma “socialização das perdas” que, inconscientemente, estimulou a industrialização por substituição de importações.</p>
<p>Martins questiona o caráter “inconsciente” dessa política: há indicações de que o governo brasileiro, mesmo antes da Revolução de 1930, estava ciente de que evitar o desemprego era parte dos objetivos da política econômica. O próprio José Maria Whitaker, responsável pela política econômica do Governo Provisório de Vargas, explica as decisões governamentais como resposta à paralisação industrial e comercial causada pela crise cafeeira — não como política meramente protetora dos cafeicultores.</p>
</section>
<section id="a-dissolução-da-dicotomia-agro-industrial-cap.5-1022" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="a-dissolução-da-dicotomia-agro-industrial-cap.5-1022"><span class="header-section-number">7.2</span> A dissolução da dicotomia agro-industrial [Cap.5 §10–§22]</h3>
<p>A contribuição teórica central do capítulo é a dissolução da dicotomia entre burguesia agrária (cafeicultores) e burguesia industrial, amplamente pressuposta na literatura. Martins demonstra empiricamente que muitos fazendeiros eram simultaneamente acionistas de empresas não agrícolas, bancos e indústrias — e que muitos industriais se tornaram fazendeiros para verticalizar suas economias. O Estado brasileiro não estava exclusivamente comprometido com os representantes da economia do café, nem refém dos seus interesses, nem contraposto aos industriais.</p>
<p>Os autores que pressupõem essa dicotomia forçam o uso de um esquema interpretativo que toma a Crise de 1929 como divisora numa equivocada passagem de “pré-capitalismo a capitalismo”, e a Revolução de outubro de 1930 como a “revolução burguesa” de que o Brasil carecia. Martins desmistifica esse esquema ao reconstituir a continuidade entre os capitais cafeeiro, comercial, financeiro e industrial: trata-se do mesmo empresário de transição que acumulou riqueza em diferentes frentes.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Contribuição ao debate sobre desenvolvimento periférico
</div>
</div>
<div class="callout-body-container callout-body">
<p>A análise de Martins sobre a gênese da industrialização antecipa debates posteriores sobre capitalismo dependente e sobre o papel do Estado na industrialização brasileira. Ao mostrar que o empresário cafeeiro e o industrial não eram classes distintas com interesses conflitantes, mas frequentemente o mesmo agente econômico em diferentes atividades, dissolve a base da teoria da “revolução burguesa” como ruptura com a herança agrária.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="capítulo-6-empresários-e-trabalhadores-de-origem-italiana-no-desenvolvimento-industrial-brasileiro-em-1880-e-1914-pp.-357435" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="capítulo-6-empresários-e-trabalhadores-de-origem-italiana-no-desenvolvimento-industrial-brasileiro-em-1880-e-1914-pp.-357435"><span class="header-section-number">8</span> Capítulo 6: Empresários e trabalhadores de origem italiana no desenvolvimento industrial brasileiro em 1880 e 1914 (pp.&nbsp;357–435)</h2>
<section id="três-destinos-do-imigrante-italiano-cap.6-18" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="três-destinos-do-imigrante-italiano-cap.6-18"><span class="header-section-number">8.1</span> Três destinos do imigrante italiano [Cap.6 §1–§8]</h3>
<p>O capítulo mais extenso da versão ampliada da obra distingue analiticamente três trajetórias distintas dos imigrantes italianos no Brasil: (1) os destinados compulsoriamente às fazendas de café do interior de São Paulo, constituindo a grande maioria; (2) os enviados para núcleos coloniais oficiais, geralmente em regiões pioneiras do Sul e Sudeste; (3) os que se dirigiram às cidades como pequenos negociantes, artesãos, operários ou capitalistas.</p>
<p>A impressão difundida de que os imigrantes italianos vieram como trabalhadores assalariados e que muitos enriqueceram pelo trabalho árduo é desmistificada em ambas as direções: a grande massa não trabalhou em condições de assalariamento clássico, e os que se tornaram grandes empresários têm origem muito distinta dos que foram destinados ao trabalho nos cafezais. A confusão entre as três trajetórias serve à sustentação do mito da ascensão social pelo trabalho.</p>
</section>
<section id="imigração-subsidiada-como-mecanismo-de-sujeição-cap.6-921" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="imigração-subsidiada-como-mecanismo-de-sujeição-cap.6-921"><span class="header-section-number">8.2</span> Imigração subsidiada como mecanismo de sujeição [Cap.6 §9–§21]</h3>
<p>O período analisado (1877–1914) recebeu 1.728.620 imigrantes apenas na região de São Paulo, dos quais 845.816 eram italianos. A imigração subvencionada atingiu 57,5% do total dos imigrantes, chegando a 98,9% em 1891. Os imigrantes subvencionados chegavam já direcionados para fazendas específicas: na estação ferroviária de chegada, fazendeiros ou seus gerentes percorriam a plataforma examinando e escolhendo imigrantes — procedimento que reproduzia a lógica da escolha de escravos no mercado.</p>
<p>O sistema de dívida da passagem, de alojamento e de mantimentos durante o período de adaptação criava imediatamente um vínculo de dependência que cerceava a liberdade do colono. A movimentação do imigrante dependia dos seus recursos próprios, geralmente escassos. Além disso, a imigração subvencionada recrutava de preferência <strong>famílias</strong>, não trabalhadores individuais — o que garantia ao fazendeiro o trabalho de todos os membros da família pelo contrato com o chefe.</p>
<blockquote class="blockquote">
<p><strong>Nota 9:</strong> Contratos de engajamento assinados em Gênova entre recrutadores-concessionários do governo brasileiro e os interessados em migrar estabeleciam condições rígidas para a localização final dos imigrantes, sendo extremamente difícil a remoção para outras áreas, a reemigração ou o repatriamento. O imigrante que tentava fugir da Hospedaria de Imigrantes para ficar na cidade de São Paulo era exceção audaciosa, não regra. [nota incluída por relevância argumentativa]</p>
</blockquote>
</section>
<section id="os-empresários-italianos-origem-capital-e-condição-não-capitalista-cap.6-2242" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="os-empresários-italianos-origem-capital-e-condição-não-capitalista-cap.6-2242"><span class="header-section-number">8.3</span> Os empresários italianos: origem, capital e condição não capitalista [Cap.6 §22–§42]</h3>
<p>A seção central do capítulo desfaz a mitologia em torno da emergência dos empresários italianos. Os grandes industriais de origem italiana — como Francisco Matarazzo — não eram ex-colonos que enriqueceram pelo trabalho árduo nas fazendas. Tinham origem social distinta (pequena burguesia europeia, em muitos casos com algum capital de início) e se instalaram nas cidades, não nas fazendas. Sua trajetória foi a de capitalistas que encontraram oportunidades na economia urbana em expansão graças à prosperidade cafeeira — não a trajetória do imigrante pobre que virou rico pelo esforço.</p>
<p>A pequena e média indústria, por décadas o abrigo da classe operária nascente fora dos marcos da grande indústria, tinha caráter predominantemente artesanal. Muitos estabelecimentos classificados como “indústria” eram oficinas com menos de dez operários, dirigidas pelo próprio proprietário com caráter pessoal e patrimonial. O trabalhador artesão que “subia” à condição de pequeno patrão não realizava uma ascensão à burguesia industrial clássica — realizava uma versão em escala reduzida da mesma condição de exploração, agora como explorador de si mesmo e de uns poucos auxiliares.</p>
<p>O autor analisa também o movimento operário italiano em São Paulo — as greves de 1901 a 1917 —, mostrando que o caráter artesanal do trabalho impregnou a consciência dos trabalhadores e produziu uma cultura de classe marcada pela aspiração ao trabalho independente, não à transformação das relações de classe. O anarcossindicalismo e o socialismo utópico, predominantes no movimento operário italiano de São Paulo, expressavam essa aspiração ao trabalho autônomo — forma proletarizada da ética burguesa do trabalho independente.</p>
<hr>
</section>
</section>
<section id="capítulo-7-o-imaginário-da-ascensão-social-pelo-trabalho-a-morte-do-burguês-mítico-pp.-437463" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="capítulo-7-o-imaginário-da-ascensão-social-pelo-trabalho-a-morte-do-burguês-mítico-pp.-437463"><span class="header-section-number">9</span> Capítulo 7: O imaginário da ascensão social pelo trabalho / A morte do burguês mítico (pp.&nbsp;437–463)</h2>
<section id="o-mito-matarazzo-e-a-proletarização-das-aspirações-burguesas-cap.7-110" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="o-mito-matarazzo-e-a-proletarização-das-aspirações-burguesas-cap.7-110"><span class="header-section-number">9.1</span> O mito Matarazzo e a proletarização das aspirações burguesas [Cap.7 §1–§10]</h3>
<p>O capítulo final, que reúne dois textos originalmente separados, analisa o mito do burguês self-made como mecanismo ideológico de reprodução da dominação de classe. O caso do conde Francisco Matarazzo — imigrante italiano que chegou ao Brasil em 1881 e construiu um dos maiores impérios industriais da América Latina — é o analisador privilegiado.</p>
<p>Quando ficou claro que a escravidão seria abolida, a burguesia agrária se preocupou não apenas com a substituição do trabalhador cativo, mas com a forma que deveria assumir a <strong>preservação da dominação burguesa</strong> nas novas condições. O mecanismo ideológico que legitimava a sujeição da pessoa (pela desigualdade racial de origem) perdera a eficácia com o advento do trabalho livre. Sob a igualdade formal entre patrão e operário, era necessário um novo mecanismo de legitimação da desigualdade econômica.</p>
<p>O primeiro passo foi reconhecer que o trabalho é a fonte da riqueza — mas de imediato bloquear o acesso autônomo do trabalhador à terra (via Lei de Terras), tornando compulsório o trabalho assalariado. O segundo passo foi construir uma narrativa em que o enriquecimento através do trabalho áreo e da privação sistemática era a forma legítima e real de mobilidade social. O burguês mítico era a prova viva dessa narrativa.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conceito-chave: burguês mítico</strong> — Figura ideológica que representa o trabalhador que se tornou capitalista pelo esforço próprio, pela privação e pelo trabalho árduo. Funciona como prova empírica de que a ordem capitalista é justa e oferece oportunidades iguais a todos. Matarazzo foi o principal operacionalizador desse mito no Brasil, cultivando deliberadamente sua autobiografia como colono-pobre-que-enriqueceu junto aos trabalhadores, enquanto mantinha, junto à burguesia, a narrativa de sua origem fidalga italiana.</p>
</div>
</div>
</section>
<section id="a-vida-do-burguês-como-morte-do-mito-cap.7-1118" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="a-vida-do-burguês-como-morte-do-mito-cap.7-1118"><span class="header-section-number">9.2</span> A vida do burguês como morte do mito [Cap.7 §11–§18]</h3>
<p>O conde Francisco Matarazzo Júnior (conde Chiquinho) personificou, sem o saber, a decadência do mais importante mito de sustentação da exploração de classe. Nascido já no palacete da Avenida Paulista, educado nas pretensões aristocráticas do pai (que havia recebido o título condal por serviços ao fascismo de Mussolini), o conde Chiquinho viveu apenas a condição do aristocrata — sem nunca ter sido um imigrante pobre, sem ter trabalhado em fazendas, sem ter passado privações. Sua trajetória negava empiricamente a narrativa do burguês self-made.</p>
<p>Os quarenta anos de direção do conde Chiquinho (1937–1977) foram quarenta anos de deterioração do mito Matarazzo. Os operários descobriram que, ao contrário do que supunham os seus companheiros da primeira metade do século XX, o trabalho do operário não enriquece o próprio operário. A morte do mito foi facilitada pela constatação de que o conde rico não era consequência do seu próprio trabalho — era herdeiro de um império construído pela exploração de dezenas de milhares de trabalhadores.</p>
<blockquote class="blockquote">
<p><strong>Nota 10:</strong> Martins menciona pesquisa empírica realizada em 1974 em vários bairros de São Paulo que comprovou a amplitude do mito Matarazzo, compartilhado inclusive por trabalhadores do Nordeste que o conheciam antes de migrar para São Paulo. O mito havia se tornando um patrimônio cultural da classe operária brasileira — não apenas paulista — ilustrando a força dos mecanismos ideológicos de reprodução da dominação.</p>
</blockquote>
</section>
<section id="o-aburguesamento-das-aspirações-operárias-e-a-ambiguidade-de-classe-cap.7-1924" class="level3" data-number="9.3">
<h3 data-number="9.3" class="anchored" data-anchor-id="o-aburguesamento-das-aspirações-operárias-e-a-ambiguidade-de-classe-cap.7-1924"><span class="header-section-number">9.3</span> O aburguesamento das aspirações operárias e a ambiguidade de classe [Cap.7 §19–§24]</h3>
<p>A industrialização brasileira encontrou no mito do burguês enriquecido pelo trabalho e pela vida penosa um ingrediente vital para a legitimação da exploração de classe. Ao contrário da burguesia agrária, que teve que produzir laboriosamente a ideologia de transição do trabalho escravo ao trabalho livre, a burguesia industrial encontrou prontas a justificativa e a legitimação da exploração do trabalhador — herdadas do colonato.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>O paternalismo e o populismo empresarial como mecanismo ideológico
</div>
</div>
<div class="callout-body-container callout-body">
<p>O paternalismo empresarial — cultivado pelo próprio Matarazzo, que visitava suas fábricas e se apresentava como pai de seus operários — e o populismo de empresa (culminando na demonstração de 20 mil trabalhadores nas ruas de São Paulo em 1929 em homenagem ao velho conde) estavam diretamente fundados na concepção ideológica do trabalho como caminho de ascensão. A dominação e a exploração do capital tornaram-se concebidas como legítimas porque a riqueza não seria fruto do trabalho proletário, mas do trabalho próprio do empresário — invertendo a realidade.</p>
</div>
</div>
<p>A morte do burguês mítico ocorreu com a emergência ampla do processo de concentração do capital. O capital concentrado tornou cada vez menos plausível a narrativa de que o trabalhador poderia repetir a trajetória do grande capitalista. Com isso, emergiu na classe operária uma consciência de classe mais clara — mas ambígua: marcada pela tensão entre a consciência do antagonismo entre trabalho proletário criador e a concepção capitalista do trabalho como caminho de ascensão individual.</p>
<hr>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">10</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> O capitalismo brasileiro não seguiu a trajetória clássica do assalariamento porque instituiu deliberadamente, por meio da Lei de Terras de 1850 e da imigração subsidiada, o cativeiro da terra como mecanismo de coerção do trabalho livre — produzindo o colonato como forma não capitalista de exploração da força de trabalho gerada pelo próprio capital cafeeiro para superar a crise da escravidão sem romper com a economia de exportação.</p>
<p><strong>Natureza do argumento:</strong> Causal-mecanísmica, de base teórica marxiana heterodoxa (marxiana, não marxista), com fundamento em pesquisa documental histórica. O argumento é ao mesmo tempo uma contribuição teórica à teoria marxiana da renda capitalizada (reinterpretação do escravo como renda capitalizada, não capital fixo) e uma demonstração empírica sobre o processo histórico da transição do trabalho escravo ao trabalho livre em São Paulo (1850–1930).</p>
<p><strong>O que o texto demonstra:</strong> (1) Que o colonato era uma relação de produção não capitalista produzida pelo próprio capitalismo cafeeiro, não um resíduo pré-capitalista; (2) que a Lei de Terras de 1850 funcionou como mecanismo estrutural de coerção da força de trabalho livre, complementar à cessação do tráfico negreiro; (3) que diferentes ondas imigratórias encontraram configurações distintas da economia cafeeira, revelando a dinâmica evolutiva do colonato; (4) que a ideologia do “trabalho” foi uma produção deliberada da burguesia agrária e industrial para legitimar a exploração de classe nas novas condições do trabalho livre.</p>
<p><strong>O que fica como hipótese ou agenda:</strong> A extensão do argumento a outras regiões além de São Paulo; o papel da escravidão indígena como antecedente estrutural da escravidão negra e do colonato; os mecanismos específicos pelos quais o cativeiro da terra se estendeu à industrialização do século XX e à formação do mercado de trabalho urbano. O capítulo 7 esboça, mais do que demonstra, a continuidade do mecanismo ideológico do cativeiro da terra na sociedade industrial.</p>
<p><strong>Progressão argumentativa entre os capítulos:</strong> A obra avança de uma crítica teórica e metodológica à literatura existente (Apresentação e Cap. 1) para a análise do mecanismo estrutural (Lei de Terras, colonato), passando pela dimensão comparativa (Cap. 2) e histórica-empírica (Cap. 3), chegando à dimensão ideológica (Cap. 4 e 7) e à revisão crítica da narrativa da industrialização (Caps. 5 e 6). O conjunto constrói uma interpretação totalizante do capitalismo brasileiro como capitalismo singular, marcado pela contemporaneidade de relações de trabalho atrasadas e acumulação de capital avançada.</p>
<p><strong>Contribuição para o debate mais amplo:</strong> <em>O cativeiro da terra</em> é uma das obras fundadoras da sociologia histórica brasileira. No debate latino-americano sobre modos de produção, representa uma alternativa metodológica superior tanto ao dualismo (feudal vs.&nbsp;capitalista) quanto ao evolucionismo do “assalariamento inevitável”: demonstra que o capital pode produzir e reproduzir relações não capitalistas não como desvio, mas como necessidade estrutural. A reinterpretação do escravo como renda capitalizada e do colonato como forma não capitalista gerada pelo capitalismo é contribuição à teoria das transições entre modos de produção em economias periféricas com relevância além do caso brasileiro.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>