<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-14">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Race and the political ecology of education in Brazil – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9c28ad92f8939dd35fc671874dd1efeb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/tts-reader-2.3.0/tts-reader.js" defer="true"></script>
<link href="../site_libs/quarto-contrib/tts-reader-2.3.0/tts-reader.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Race and the political ecology of education in Brazil – Annotated Bibliography">
<meta property="og:description" content="Meek, D., Daquin, J., Girardi, E. P., Fernandes, B. M., Sobreiro do Filho, J., Tarlau, R., &amp; Vuelta, R. (2024). Race and the political ecology of education in Brazil: A spatial analysis of rural school closures. Journal of Political Ecology, 31. https://doi.org/[não informado no PDF]">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#mapa-argumentativo" id="toc-mapa-argumentativo" class="nav-link" data-scroll-target="#mapa-argumentativo">Mapa Argumentativo</a></li>
  <li><a href="#sec-introducao" id="toc-sec-introducao" class="nav-link" data-scroll-target="#sec-introducao"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–3)</a>
  <ul class="collapse">
  <li><a href="#apresentação-do-puzzle-e-das-três-questões-geográficas-16" id="toc-apresentação-do-puzzle-e-das-três-questões-geográficas-16" class="nav-link" data-scroll-target="#apresentação-do-puzzle-e-das-três-questões-geográficas-16"><span class="header-section-number">1.1</span> Apresentação do puzzle e das três questões geográficas [§1–§6]</a></li>
  </ul></li>
  <li><a href="#sec-secao2a" id="toc-sec-secao2a" class="nav-link" data-scroll-target="#sec-secao2a"><span class="header-section-number">2</span> Geografia Racial e Injustiça Epistêmica (pp.&nbsp;4–5)</a>
  <ul class="collapse">
  <li><a href="#distribuição-demográfica-e-ambiguidade-das-categorias-de-cor-710" id="toc-distribuição-demográfica-e-ambiguidade-das-categorias-de-cor-710" class="nav-link" data-scroll-target="#distribuição-demográfica-e-ambiguidade-das-categorias-de-cor-710"><span class="header-section-number">2.1</span> Distribuição demográfica e ambiguidade das categorias de cor [§7–§10]</a></li>
  <li><a href="#coloniality-injustiça-epistêmica-e-a-lógica-do-fechamento-escolar-1113" id="toc-coloniality-injustiça-epistêmica-e-a-lógica-do-fechamento-escolar-1113" class="nav-link" data-scroll-target="#coloniality-injustiça-epistêmica-e-a-lógica-do-fechamento-escolar-1113"><span class="header-section-number">2.2</span> Coloniality, injustiça epistêmica e a lógica do fechamento escolar [§11–§13]</a></li>
  </ul></li>
  <li><a href="#sec-secao2b" id="toc-sec-secao2b" class="nav-link" data-scroll-target="#sec-secao2b"><span class="header-section-number">3</span> Educação, Raça e a Questão Agrária no Brasil (pp.&nbsp;5–10)</a>
  <ul class="collapse">
  <li><a href="#o-mito-da-democracia-racial-e-o-estado-como-agente-de-branqueamento-1418" id="toc-o-mito-da-democracia-racial-e-o-estado-como-agente-de-branqueamento-1418" class="nav-link" data-scroll-target="#o-mito-da-democracia-racial-e-o-estado-como-agente-de-branqueamento-1418"><span class="header-section-number">3.1</span> O mito da democracia racial e o Estado como agente de branqueamento [§14–§18]</a></li>
  <li><a href="#economia-política-da-educação-e-o-papel-dos-movimentos-sociais-1923" id="toc-economia-política-da-educação-e-o-papel-dos-movimentos-sociais-1923" class="nav-link" data-scroll-target="#economia-política-da-educação-e-o-papel-dos-movimentos-sociais-1923"><span class="header-section-number">3.2</span> Economia política da educação e o papel dos movimentos sociais [§19–§23]</a></li>
  <li><a href="#educação-do-campo-nucleação-e-imaginários-espaciais-em-conflito-2431" id="toc-educação-do-campo-nucleação-e-imaginários-espaciais-em-conflito-2431" class="nav-link" data-scroll-target="#educação-do-campo-nucleação-e-imaginários-espaciais-em-conflito-2431"><span class="header-section-number">3.3</span> Educação do Campo, nucleação e imaginários espaciais em conflito [§24–§31]</a></li>
  </ul></li>
  <li><a href="#sec-metodos" id="toc-sec-metodos" class="nav-link" data-scroll-target="#sec-metodos"><span class="header-section-number">4</span> Métodos e Análises (pp.&nbsp;10–12)</a>
  <ul class="collapse">
  <li><a href="#banco-de-dados-e-operacionalização-do-fechamento-escolar-3236" id="toc-banco-de-dados-e-operacionalização-do-fechamento-escolar-3236" class="nav-link" data-scroll-target="#banco-de-dados-e-operacionalização-do-fechamento-escolar-3236"><span class="header-section-number">4.1</span> Banco de dados e operacionalização do fechamento escolar [§32–§36]</a></li>
  <li><a href="#análise-geoespacial-e-regressão-de-painel-3740" id="toc-análise-geoespacial-e-regressão-de-painel-3740" class="nav-link" data-scroll-target="#análise-geoespacial-e-regressão-de-painel-3740"><span class="header-section-number">4.2</span> Análise geoespacial e regressão de painel [§37–§40]</a></li>
  </ul></li>
  <li><a href="#sec-resultados" id="toc-sec-resultados" class="nav-link" data-scroll-target="#sec-resultados"><span class="header-section-number">5</span> Resultados (pp.&nbsp;12–20)</a>
  <ul class="collapse">
  <li><a href="#padrão-regional-e-institucional-dos-fechamentos-4147" id="toc-padrão-regional-e-institucional-dos-fechamentos-4147" class="nav-link" data-scroll-target="#padrão-regional-e-institucional-dos-fechamentos-4147"><span class="header-section-number">5.1</span> Padrão regional e institucional dos fechamentos [§41–§47]</a></li>
  <li><a href="#ciclos-políticos-e-temporalidade-dos-fechamentos-4852" id="toc-ciclos-políticos-e-temporalidade-dos-fechamentos-4852" class="nav-link" data-scroll-target="#ciclos-políticos-e-temporalidade-dos-fechamentos-4852"><span class="header-section-number">5.2</span> Ciclos políticos e temporalidade dos fechamentos [§48–§52]</a></li>
  <li><a href="#fatores-preditores-dos-fechamentos-análise-multivariada-5359" id="toc-fatores-preditores-dos-fechamentos-análise-multivariada-5359" class="nav-link" data-scroll-target="#fatores-preditores-dos-fechamentos-análise-multivariada-5359"><span class="header-section-number">5.3</span> Fatores preditores dos fechamentos: análise multivariada [§53–§59]</a></li>
  </ul></li>
  <li><a href="#sec-conclusoes" id="toc-sec-conclusoes" class="nav-link" data-scroll-target="#sec-conclusoes"><span class="header-section-number">6</span> Conclusões (pp.&nbsp;20–21)</a>
  <ul class="collapse">
  <li><a href="#contribuições-teóricas-e-metodológicas-6065" id="toc-contribuições-teóricas-e-metodológicas-6065" class="nav-link" data-scroll-target="#contribuições-teóricas-e-metodológicas-6065"><span class="header-section-number">6.1</span> Contribuições teóricas e metodológicas [§60–§65]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">7</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Race and the political ecology of education in Brazil</h1>
<p class="subtitle lead">Meek, D., Daquin, J., Girardi, E. P., Fernandes, B. M., Sobreiro do Filho, J., Tarlau, R., &amp; Vuelta, R. (2024). Race and the political ecology of education in Brazil: A spatial analysis of rural school closures. <em>Journal of Political Ecology</em>, <em>31</em>. https://doi.org/[não informado no PDF]</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Political Ecology</div>
    <div class="quarto-category">Education Policy</div>
    <div class="quarto-category">Race and Inequality</div>
    <div class="quarto-category">Brazil</div>
    <div class="quarto-category">2024</div>
    <div class="quarto-category">2020s</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 14, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Informações Técnicas e BibTeX
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>Última atualização: 2026-05-14
Modelo: Claude claude-sonnet-4-5 (Perplexity, powered by Sonnet 4.6 Thinking)
Prompt Version: v17.4 · 2026-05-13
Gerado em: 2026-05-14T23:46:00-03:00
Ocasião da Leitura:</code></pre>
<p><strong>Entrada BibTeX → Meek-etal2024</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">Meek</span>-<span class="ot">etal2024</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>    = {Meek, David and Daquin, Jane and Girardi, Eduardo Paulon and</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>               Fernandes, Bernardo Man{<span class="ch">\c</span>{c}}ano and Sobreiro do Filho, Jos{<span class="ch">\'</span>e} and</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>               Tarlau, Rebeca and Vuelta, Raquel},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>     = {Race and the political ecology of education in {Brazil}:</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>               {A} spatial analysis of rural school closures},</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>      = {2024},</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">journal</span>   = {Journal of Political Ecology},</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">volume</span>    = {31},</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="dt">doi</span>       = {não informado no PDF},</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v17.4</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A pergunta central assume que o fechamento de escolas rurais no Brasil é um fenômeno com lógica espacial e racial. Isso é uma premissa implícita que o desenho confirmatório não testou contra hipóteses alternativas igualmente plausíveis (e.g., simplesmente declínio demográfico rural).</td>
<td style="text-align: left;">Quais são os fatores sociais, políticos e econômicos que estruturam o padrão espacial do fechamento de escolas rurais no Brasil entre 1994 e 2020, e em que medida raça e concentração fundiária são determinantes desse processo? Natureza: explicativa/descritiva.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">As três subperguntas — onde as escolas fecham (espacialmente), se raça prediz os fechamentos, e se concentração fundiária os condiciona — são operacionalizadas de forma relativamente independente, mas o artigo não as integra numa única especificação causal unificada.</td>
<td style="text-align: left;">(1) Como os fechamentos se distribuem espacialmente no Brasil? (2) A composição racial do município prediz a taxa de fechamentos? (3) A concentração fundiária (GINI) prediz a taxa de fechamentos? As três subperguntas têm relação direta e progressiva com a tese central.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno: a escala do fenômeno (142.401 escolas, 65% do total) é empiricamente subestimada na literatura de ecologia política da educação. A generalizabilidade além do Brasil é limitada, mas o argumento conceitual sobre colonialidade e conhecimento tem alcance amplo.</td>
<td style="text-align: left;">Puzzle descritivo-explicativo: a literatura de ecologia política da educação havia documentado pouco sobre como raça estrutura geograficamente o acesso à educação rural. O artigo trata esse silêncio como lacuna teórica e empírica.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese combina achados quantitativos com enquadramento normativo (coloniality, injustiça epistêmica). O “claim of discovery” — que raça e concentração fundiária causam fechamentos — é mais forte descritivamente do que causalmente, dado o design observacional.</td>
<td style="text-align: left;">O fechamento massivo de escolas rurais no Brasil é um processo racializado e estruturado pela desigualdade fundiária: municípios com maior proporção de residentes negros e maior índice de Gini apresentam taxas significativamente mais altas de fechamento escolar, o que reflete a operação histórica e contemporânea do racismo estrutural e do capitalismo agrário sobre o acesso ao conhecimento.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O design é quantitativo-espacial com dois estágios: (a) análise geoespacial de hotspots (Getis-Ord*) com dados 1994–2020 para todos os municípios brasileiros; (b) regressão binomial negativa de painel com efeitos aleatórios para dois anos (2006 e 2017). A restrição a apenas dois pontos temporais na fase multivarida limita substancialmente as inferências sobre tendências longitudinais. O fichamento cobre a obra inteira.</td>
<td style="text-align: left;">Estudo quantitativo com análise espacial e regressão de painel. Fontes: Censo Escolar (INEP, 1996–2021) para escolas; Censo Demográfico (IBGE 2010) para dados raciais; fontes agrárias para Gini fundiário. Ferramenta SIG: ArcMap 10.5. Análise estatística: STATA 17.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">A raça é medida pelo Censo 2010 (corte único), enquanto os fechamentos cobrem 25 anos — isso introduz um problema de defasagem temporal severo: a composição racial de 2010 é usada para predizer fechamentos de 1994–2020. A unidade de análise é o município, mas o fenômeno opera no nível da escola e da comunidade, introduzindo falácia ecológica.</td>
<td style="text-align: left;">Fenômeno real (fechamento escolar) → registros administrativos anuais do INEP → banco relacional em MS Access → operacionalização de “escola fechada” por comparação bianual (ativa/paralisada no ano t → extinta no ano t+1) → análise em dois estágios (hotspot + regressão). Unidade: município (N=5.412). Dois períodos para a regressão (2006, 2017). Viés potencial: escolas que mudam de categoria rural→urbana não são contadas como fechadas, o que pode subestimar o fenômeno em áreas de reclassificação territorial.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">Os achados descritivos (tabelas 1–3) são bem documentados e robustos. Os achados inferenciais (tabela 4) são tecnicamente sólidos mas sofrem das limitações do DGP descritas acima. A contribuição teórica — introduzir raça como dimensão central na ecologia política da educação — é genuína e bem articulada.</td>
<td style="text-align: left;">Descritivos: 142.401 escolas rurais fechadas (65%); concentração no Nordeste (48,6% do total) e Sul (17,1%); 90% dos fechamentos em escolas municipais. Inferenciais: GINI fundiário é o preditor mais forte (IRR=3,28; p&lt;0,01); proporção de negros é o segundo (IRR=2,75; p&lt;0,001); urbanização reduz fechamentos (IRR=0,49); orientação política federal não é estatisticamente significativa. Contribuição metodológica: uso de big data censitário combinado com análise espacial para questão educacional crítica.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">(a) <strong>Falácia ecológica</strong>: inferir sobre comunidades negras a partir de proporções municipais é problemático — município com 30% de negros pode ter fechamentos concentrados em bairros/assentamentos específicos, e o design não capta isso. (b) <strong>Causalidade reversa parcial</strong>: municípios onde escolas já fecharam podem ter visto evasão de populações negras (seleção amostral dinâmica não discutida). (c) <strong>Confundidores omitidos</strong>: densidade demográfica rural, distância de centros urbanos e investimento per capita em educação não aparecem como controles. (d) <strong>Dois pontos temporais</strong>: a análise de painel com apenas 2006 e 2017 não permite verificar se a associação raça-fechamentos se mantém em outros períodos; os hotspots descritivos mostram variação temporal considerável. (e) O achado de que “orientação política federal não é significativa” é empiricamente importante mas subteorizado — o artigo atribui isso à autonomia municipal sem explorar como o poder local media raça e fundiário.</td>
<td style="text-align: left;">O design identifica com força a correlação entre Gini e fechamentos, e entre composição racial e fechamentos; identifica com menor força a direção causal e os mecanismos intermediários.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> Restrição a dois períodos na análise multivariada; inconsistências nos microdados do Censo Escolar (escolas que mudam de categoria); ausência de análise do nível municipal de decisão política. <br> <strong>Não reconhecidas ou subestimadas:</strong> Falácia ecológica na inferência sobre “comunidades negras”; mensuração de raça com dado censitário de corte único (2010) aplicado a série temporal de 25 anos; ausência de controles para densidade demográfica rural e investimento educacional per capita; possível viés de seleção por reclassificação rural-urbana; o modelo de efeitos aleatórios assume ausência de correlação entre os efeitos não observados e os regressores, o que é discutível dada a estrutura da desigualdade fundiária brasileira.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A moldura da ecologia política da educação (Meek 2020) é usada com coerência: articula questões de poder, economia política e movimentos sociais. A incorporação de colonialidade do saber (Porto-Gonçalves, Santos) e de interseccionalidade é relevante e bem calibrada ao objeto. A ontologia implícita é relacional e construtivista, coerente com a estratégia qualitativo-crítica da literatura review, mas parcialmente em tensão com o positivismo inferencial do componente quantitativo.</td>
<td style="text-align: left;">Ecologia política da educação; colonialidade do poder e do saber (Quijano/Santos); pedagogia crítica (Freire); questão agrária (Bernstein, McMichael); interseccionalidade.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">Meek (2020) é a referência central para o quadro teórico; Dávila (2003), Winant (1992), Marcus (2013) para raça no Brasil; Bernstein (1996, 2004, 2008), McMichael (1997) para questão agrária; Tarlau (2013, 2015, 2017, 2018) para MST e educação do campo. O diálogo com literatura quantitativa sobre determinantes de fechamento escolar em outros países é praticamente ausente — uma lacuna que enfraquece a contextualização comparativa.</td>
<td style="text-align: left;">Referências centrais bem integradas; ausência de literatura quantitativa comparada sobre fechamentos escolares.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">O artigo é pioneiro ao cruzar análise espacial censitária em grande escala com quadro teórico crítico de raça e ecologia política. A principal vulnerabilidade está na distância entre o “claim of discovery” (processo fundamentalmente racializado) e o que o design realmente identifica (correlação ecológica entre composição municipal e fechamentos). Para a pesquisa do leitor em políticas de ensino superior e desigualdade educacional no Brasil, o artigo oferece tanto uma metodologia de análise de dados censitários do INEP quanto um enquadramento teórico interseccional aplicável a outros níveis de ensino.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="mapa-argumentativo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-argumentativo">Mapa Argumentativo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 19%">
<col style="width: 28%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Seção</th>
<th style="text-align: left;">Título / Tema</th>
<th style="text-align: left;">Função argumentativa</th>
<th style="text-align: left;">Contribuição para a tese central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Introdução</td>
<td style="text-align: left;">Escopo do problema e três questões geográficas</td>
<td style="text-align: left;">Apresentação do puzzle e das hipóteses centrais</td>
<td style="text-align: left;">Estabelece a escala do fenômeno (142.401 escolas; 65%) e anuncia os três achados principais como antecipação da tese</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção 2a</td>
<td style="text-align: left;">Geografia das categorias raciais e injustiça epistêmica</td>
<td style="text-align: left;">Fundamento teórico-conceitual</td>
<td style="text-align: left;">Demonstra que a distribuição geográfica de raça no Brasil é herança colonial, criando a base para a hipótese de que fechamentos seguem essa mesma lógica territorial</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seção 2b</td>
<td style="text-align: left;">Educação, raça e questão agrária no Brasil</td>
<td style="text-align: left;">Revisão histórica e contextualização teórica</td>
<td style="text-align: left;">Articula a história do uso da educação como instrumento de branqueamento e dominação agrária; introduz Freire, MST e Educação do Campo como vetores de resistência</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção 3</td>
<td style="text-align: left;">Métodos e análises</td>
<td style="text-align: left;">Fundamento metodológico</td>
<td style="text-align: left;">Justifica as escolhas de DGP (Censo Escolar), operacionalização de “escola fechada”, análise espacial (Getis-Ord*) e regressão binomial negativa de painel</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seção 4</td>
<td style="text-align: left;">Resultados</td>
<td style="text-align: left;">Análise empírica</td>
<td style="text-align: left;">Apresenta os achados descritivos (Tabelas 1–3, Figuras 1–3) e inferenciais (Tabela 4), confirmando as três hipóteses; introduz achado sobre transição agrária como qualificação</td>
</tr>
<tr class="even">
<td style="text-align: left;">Seção 5</td>
<td style="text-align: left;">Conclusões</td>
<td style="text-align: left;">Síntese e agenda</td>
<td style="text-align: left;">Reafirma a tese de que raça e Gini fundiário estruturam os fechamentos; propõe contribuições teóricas (interseccionalidade na ecologia política da educação) e agenda de pesquisa futura</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-introducao" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="sec-introducao"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–3)</h2>
<section id="apresentação-do-puzzle-e-das-três-questões-geográficas-16" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="apresentação-do-puzzle-e-das-três-questões-geográficas-16"><span class="header-section-number">1.1</span> Apresentação do puzzle e das três questões geográficas [§1–§6]</h3>
<p>O artigo se abre contextualizando um processo de escala extraordinária: nas últimas vinte e cinco anos, o Estado brasileiro fechou mais de 142.401 escolas rurais, o que corresponde a 65% de toda a rede escolar rural existente no período. Em 2016 isoladamente, mais de 11.732 escolas foram encerradas. Os autores enquadram esse fenômeno não como uma série de decisões administrativas pontuais, mas como um <strong>processo territorial espacialmente extenso e intensivo</strong>, cuja lógica precisa ser explicada.</p>
<p>A contribuição teórica anunciada é dupla. No campo da ecologia política da educação — perspectiva que os autores definem, com base em Meek (2020), como “atenta à forma como a distribuição de poder e recursos entre entidades políticas e culturais interconectadas medeia processos pedagógicos” —, as questões de raça haviam permanecido largamente invisíveis. O artigo propõe preencher essa lacuna por meio de três contribuições: (1) demonstrar como uma lente histórica ilumina a inequidade racializada desde uma perspectiva de ecologia política da educação; (2) mostrar como raça, educação e formação do Estado se entrelaçam no Brasil; e (3) evidenciar como movimentos sociais de base mobilizam a educação como instrumento de resistência ao capitalismo agrário.</p>
<p>O artigo organiza seus resultados em torno de três perguntas geográficas explícitas, que o texto antecipa com as respostas principais ainda na introdução. Primeiro, o padrão espacial dos fechamentos concentra-se em hotspots que coincidem com territórios de comunidades de cor e com presença do agronegócio — nas regiões Centro-Oeste e Sul, onde o agronegócio é mais forte, aproximadamente 80% das escolas foram fechadas; no Norte e Nordeste, com maior proporção de pessoas de cor, cerca de 60% das escolas rurais desapareceram. Segundo, a composição racial do município é preditora significativa: em municípios com maior proporção de residentes negros autodeclarados, a taxa de incidência de fechamentos é 175% maior. Terceiro, a concentração fundiária é o preditor de maior tamanho de efeito: um aumento de uma unidade no índice de Gini está associado a uma elevação de 228% na taxa de fechamentos.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A introdução opera como síntese antecipada: ao revelar os achados centrais já nos primeiros parágrafos, os autores estabelecem o argumento como confirmação empírica de uma denúncia dos movimentos sociais rurais — o que confere coerência normativa ao texto, mas também revela a estrutura confirmacionista do desenho de pesquisa.</p>
</div>
</div>
</section>
</section>
<section id="sec-secao2a" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-secao2a"><span class="header-section-number">2</span> Geografia Racial e Injustiça Epistêmica (pp.&nbsp;4–5)</h2>
<section id="distribuição-demográfica-e-ambiguidade-das-categorias-de-cor-710" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="distribuição-demográfica-e-ambiguidade-das-categorias-de-cor-710"><span class="header-section-number">2.1</span> Distribuição demográfica e ambiguidade das categorias de cor [§7–§10]</h3>
<p>Os autores iniciam essa seção reconhecendo o problema semântico e político inerente ao uso de categorias de cor no Brasil. Os censos brasileiros historicamente utilizaram o termo <em>côr</em> (cor) em vez de raça ou etnia, e apenas em 1991 a categoria <em>indígena</em> foi incluída. O termo <em>pardo</em> é próximo do sem sentido analítico, abrangendo desde “meio-negro” até “moreno de pele escura” (Marcus 2013: 1290). Mesmo os termos <em>preto</em> e <em>branco</em> não são vinculantes nem binários no Brasil — são construções flexíveis, arbitrárias e de múltiplos subtextos. Reconhecendo essas ambiguidades, os autores optam por trabalhar com as categorias censitárias disponíveis, que ainda assim oferecem orientação sobre a distribuição demográfica.</p>
<p>Os dados do IBGE 2010 mostram que a região mais populosa é o Sudeste (42,6% da população), com São Paulo e Rio de Janeiro como centros urbanos principais. O Nordeste é o segundo (28,1%), seguido do Sul (14,8%), Norte (7,6%) e Centro-Oeste (6,9%). A composição racial nacional é: brancos (53,8%), pardos (38,5%), pretos (6,2%), amarelos (0,4%), indígenas (0,4%) e não declarados (0,7%). Regionalmente, o Sul tem a maior proporção de brancos autodeclarados (84%), o Norte tem a maior proporção de pardos (64%) e o Nordeste concentra a maior proporção de pretos (8%). A região Norte também é lar da maior população indígena (1,6%).</p>
</section>
<section id="coloniality-injustiça-epistêmica-e-a-lógica-do-fechamento-escolar-1113" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="coloniality-injustiça-epistêmica-e-a-lógica-do-fechamento-escolar-1113"><span class="header-section-number">2.2</span> Coloniality, injustiça epistêmica e a lógica do fechamento escolar [§11–§13]</h3>
<p>Os autores argumentam que esses padrões demográficos regionais não são acidentais: são herança direta da agricultura de plantation colonial — bananas, cacau e açúcar no Nordeste — que estruturou a distribuição de populações afrodescendentes no país (Marcus 2013). Essa territorialização racializada foi reciprocamente reforçada pela <strong>coloniality do poder</strong> e pela geopolítica da produção de conhecimento. O colonialismo inscreveu a branquitude como identidade padrão associada à produção legítima de saber. A concepção de que camponeses são “desprovidos de conhecimento” é produto de um processo racializado de invisibilização.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Os autores invocam Santos (2002) para afirmar que o que o cânone ocidental não reconhece como legítimo é negado e tornado invisível. O fechamento de escolas rurais é enquadrado, a partir desse raciocínio, como apagamento de <strong>epistemologias camponesas negras</strong> — um marcador de colonialidade. Em resposta, movimentos sociais agrários buscam tornar visíveis outros sistemas de saber, engajando-se no que Porto-Gonçalves (2006) denomina <em>re-existência</em>.</p>
</div>
</div>
</section>
</section>
<section id="sec-secao2b" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-secao2b"><span class="header-section-number">3</span> Educação, Raça e a Questão Agrária no Brasil (pp.&nbsp;5–10)</h2>
<section id="o-mito-da-democracia-racial-e-o-estado-como-agente-de-branqueamento-1418" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="o-mito-da-democracia-racial-e-o-estado-como-agente-de-branqueamento-1418"><span class="header-section-number">3.1</span> O mito da democracia racial e o Estado como agente de branqueamento [§14–§18]</h3>
<p>A seção se inicia com a afirmação de que o Brasil é, para muitos, um país onde falar sobre raça “não faz sentido”. Desde a década de 1930, o país foi apresentado como democracia racial — ideia popularizada por Gilberto Freyre, sustentando que o Brasil seria único entre as antigas colônias em sua harmonia racial e aceitação da miscigenação. A partir dos anos 1950, porém, esse imaginário começou a ruir à medida que a discriminação estrutural contra afro-brasileiros tornava-se mais visível. Os autores seguem Serrão (2022), Silva (2016) e Guimarães (2001) ao rejeitar esse mito e propor que o racismo estrutural opera territorialmente.</p>
<p>O artigo reconstrói a história da educação brasileira como instrumento de formação racial do Estado. Willinsky (1998) é mobilizado para mostrar que desde o colonialismo europeu, o “estudo, classificação e ordenamento da humanidade em contexto imperial deu origem a ideias peculiares e poderosas de raça, cultura e nação” (p.&nbsp;3). No Brasil, entre 1917 e 1945, o Estado expandiu o sistema escolar com o objetivo declarado de “aperfeiçoar a raça” — criar uma “raça brasileira” saudável, culturalmente europeia e fisicamente apta (Dávila 2003: 3). A negritude era associada ao passado e à patologia; a mistura racial simbolizava progresso rumo à branquitude; a branquitude era associada à saúde, à ciência e à modernidade. As reformas educacionais do período privilegiaram aparência, hábitos e valores da classe média branca. Como Dávila (2003) argumenta, reformar o sistema de ensino era a estratégia central para construir uma nação culturalmente branca.</p>
<p>Durante a ditadura militar (1964–1984), o regime investiu em educação como instrumento de desenvolvimento econômico urbano, concentrando gastos no ensino médio e superior em centros urbanos e deixando as regiões rurais em situação de crônica subinvestimento. A Lei de Reforma Educacional de 1971 cedeu alguma autoridade sobre o ensino básico aos estados, mas apenas a Constituição de 1988 devolveu plenamente esse controle a estados e municípios. Ainda assim, duas décadas de política econômica urbano-industrial deixaram sequelas profundas nas regiões rurais. Entre 1980 e 1996, a proporção de alunos que concluíam a quarta série no Brasil subiu de 50% para 75%, e os que terminavam o ensino médio, de 17% para 25% (Reimers 2000: 67) — mas a vasta maioria das crianças deixadas para trás nessa expansão eram de zonas rurais.</p>
</section>
<section id="economia-política-da-educação-e-o-papel-dos-movimentos-sociais-1923" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="economia-política-da-educação-e-o-papel-dos-movimentos-sociais-1923"><span class="header-section-number">3.2</span> Economia política da educação e o papel dos movimentos sociais [§19–§23]</h3>
<p>Os autores articulam a economia política da educação diretamente com a questão agrária. A disparidade geográfica na oferta educacional replica a distribuição historicamente inequitativa da terra (Plank 1987). Municípios rurais no Norte e Nordeste historicamente recebiam um sexto dos recursos destinados aos municípios do Sul urbano (Gadotti 1992), e em 1990 os gastos por aluno nos estados mais pobres do Nordeste eram um terço daqueles nos estados mais ricos do Sul (Reimers 2000). Governos municipais controlados por latifundiários engajados em clientelismo são os administradores burocráticos das escolas públicas rurais (Tarlau 2013). A classe dominante brasileira governou simultaneamente a terra e a educação com o objetivo de preservar o capitalismo agro-industrial e deslocar o campesinato para áreas urbanas.</p>
<p>Paulo Freire (1921–1997) é apresentado como ponto de viragem nessa trajetória. Seu trabalho no Nordeste — e posteriormente no Chile — articulou uma compreensão de consciência crítica e práxis diretamente conectada ao campesinato: em <em>Ação cultural para a liberdade</em> (1970), o termo “camponês” aparece mais de 70 vezes. Como Michael Apple (2003) observa, Freire sabia por experiência própria que a opressão é “codificada por cor”, e que a política de raça era arena central de contestação nas lutas dos afro-brasileiros.</p>
<blockquote class="blockquote">
<p><strong>Nota:</strong> Haymes (2002) realizou análise crítica detalhada sobre a presença e ausência de raça nos escritos de Freire, referência que os autores citam em nota de rodapé mas não desenvolvem no corpo do texto. <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/51a156d6-65e1-4d9a-82af-199bfdd408d1/jpe-5135-meek.pdf?AWSAccessKeyId=ASIA2F3EMEYE6HQVZ3TP&amp;Signature=uGL%2FHKq%2FDZvxiwKqqQOem%2F1101g%3D&amp;x-amz-security-token=IQoJb3JpZ2luX2VjEKD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJGMEQCIFOrPJNBZl31OThdxSFXP0CK73G6KTYl2AxXi1LIB8dZAiBiSGnB2852Xj26tgvbSud54PoR37YIJpbmTkKJHNVMpirzBAhpEAEaDDY5OTc1MzMwOTcwNSIMoZUFTE4o%2FTxPjNTLKtAESKH8Za007TMR0%2B4PVL%2FTDi5p6wwa254E9%2FTjiqt2wDKQgcVfykX%2FYrNXC367LcQJORpqgVda0Bc0ut88RqQIJKprW9eJtLfsRGTUAkWqOdKB0ICbDipUaqPDFrj8KwzOM6oBadRwpnqMwvTQkzKIhU9YgmazOzVgtH87swKe7pxikAb8n7S9zPckX7chQXb7Addwjiy1oowHovJrfTXHuXxLoqTaa9dke9PFY8lRZyCuiSGRrO0RISCpvAAR77KzP8iTDU7NLl84pvjnfX8f5xFvZupIL0WZLLclR1%2BK6EnzGo6udRaTNLR%2B2T1jI4PEJP1akuFGC%2BVh%2FwSGtjuGkRHMPB5Jlj85Hh6hOoh0%2FvRXbRU4e0y4eixWQBvnLv410xA67lyBw2rsfQ%2FdgZjzqw3pfnNLkZznsRzg0l0y8YGR5o74rlMdWjhcqWxz%2BoMxb6Ef3JDsF%2FwoAcSp9rftbbRnmTbMONlLy%2BI40wRqvg2sTlHjWtonPJ8IToqXJZZSydDbVTkeT8Mhw5yZ%2BTGoXzvo4q%2BmIC36wBM7CQAVOsUE4GEyMBxNb4pJuAWCAQ1WJD46KHQiYeVvhKa8JbNY0IfBaZBJScC4488koesplQkjj%2FS6xVTgJdQIFSJTpZzgxDGdxQHjGmd2oskLq6HY6y6op3nid8RP%2FZCESIQ9IaLGgRYtRTxJMTXK7qYww9Nodfki8db8Az1g9WCVQZres9zpyV%2BKRokODeT6Cr2bvra7TIqLTXtDapPJh7cLdRGV1mrKVHhQBSyUoGkhvKfUajCbspnQBjqZAatl9mVTNNs2pevj9QAW5O8loquRf0VNFNPcfgQDv0kk3MkTMc4yd1NE3XVz%2BfqwyaE7oeTWbU%2B1SyFKzQXDKY2BJ0%2BY4hOnXA9V1%2BSlM9GZIVhk23ZoGLNk%2F2tMhsjoVKwB8FQTFRpEiR%2Fp4QUOzZS%2B2M4YWf6Mxjze70vtn4Zq6qsCN77V4hxGvxLXv5hib%2FYPk%2FmIwFnnZA%3D%3D&amp;Expires=1778803218">ppl-ai-file-upload.s3.amazonaws</a></p>
</blockquote>
<p>O Movimento dos Trabalhadores Sem Terra (MST) é apresentado como o ator que transformou a pedagogia crítica freiriana em programa educacional organizado. Ao longo dos anos 1980, líderes do MST que ocupavam terra para conquistar direitos agrários também desenvolveram atividades pedagógicas para crianças e programas de alfabetização para adultos em acampamentos. Na Primeira Reunião Nacional de Educadores da Reforma Agrária (ENERA) em 1997, representantes de organizações internacionais como UNESCO e UNICEF incentivaram o MST a expandir seu programa educacional para incluir populações indígenas, comunidades negras e trabalhadores rurais — momento em que o conceito de <strong>Educação do Campo</strong> entrou no debate nacional.</p>
</section>
<section id="educação-do-campo-nucleação-e-imaginários-espaciais-em-conflito-2431" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="educação-do-campo-nucleação-e-imaginários-espaciais-em-conflito-2431"><span class="header-section-number">3.3</span> Educação do Campo, nucleação e imaginários espaciais em conflito [§24–§31]</h3>
<p>A <em>Educação do Campo</em> é definida pelos autores como educação que se origina do campo e é relevante para ele, um paradigma que valoriza a identidade agrária, as práticas agroecológicas e a soberania alimentar. Segundo o <em>Dicionário da Educação do Campo</em> (Caldart et al.&nbsp;2012), essa proposta combina a luta pela educação com a luta pela terra, reforma agrária, direito ao trabalho, cultura e soberania alimentar. Ela se opõe diametralmente à “educação rural” tradicional, que os autores descrevem como ligada aos interesses do agronegócio — denegratória das áreas rurais e orientada para encorajar estudantes a migrar para cidades. As <em>escolas do campo</em> integram <strong>formação</strong> (desenvolvimento de liderança política, educação crítica e conscientização) ao lado de oportunidades educativas convencionais.</p>
<p>O fechamento de escolas rurais opera através de um processo espacial conhecido como <strong>nucleação</strong> (<em>nucleação</em>): escolas rurais com baixa matrícula são identificadas, seus alunos são transferidos para escolas maiores centralizadas, e as escolas esvaziadas são fechadas. Quando não há escolas suficientes para esse processo, os alunos são simplesmente levados de ônibus até a cidade mais próxima. Miguel Arroyo (2007) argumenta que as políticas de nucleação são manifestações de uma política pública inspirada pelas demandas de “modernização” da agricultura e expansão do agronegócio. O MST compartilha dessa leitura: nas palavras de Erivan Hilário, do setor de educação do MST, “o fechamento de escolas no campo não pode ser entendido apenas como tendência educacional. O que está em jogo é a escolha do governo de um modelo de desenvolvimento para as áreas rurais, que é o agronegócio.”</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>O conceito de <strong>imaginários espaciais</strong> (Wolford 2004) é central para o argumento: o agronegócio concebe o espaço rural como vazio de pessoas, homogêneo e orientado para a produção — o que legitima a consolidação de propriedades e viabiliza um modelo de alta tecnologia e baixo insumo de trabalho. Em contraste, os movimentos camponeses articulam uma visão alternativa em que os espaços rurais são produzidos por tradições agrárias e produzem vida. A Educação do Campo é, nesse sentido, um argumento espacial sobre educação.</p>
</div>
</div>
<p>A seção se encerra com a discussão da dimensão etno-racial da Educação do Campo. Munanga e Gomes (2016) fornecem o conceito de “etno-racial” para capturar simultaneamente a dimensão cultural (língua, tradição, ancestralidade) e a racial (características físicas visíveis) do que significa “ser negro” no Brasil. Silva e Barbosa (1997) sugerem que a educação tornou-se espaço central tanto para denunciar a desumanização de sujeitos negros quanto para desenvolver consciência crítica. A Educação do Campo é descrita como projeto que rejeita o mito da democracia racial e constrói epistemologias baseadas nas experiências vividas pelo campesinato negro, articulando o que Walsh (2009) denomina <strong>interculturalidade crítica</strong>.</p>
</section>
</section>
<section id="sec-metodos" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-metodos"><span class="header-section-number">4</span> Métodos e Análises (pp.&nbsp;10–12)</h2>
<section id="banco-de-dados-e-operacionalização-do-fechamento-escolar-3236" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="banco-de-dados-e-operacionalização-do-fechamento-escolar-3236"><span class="header-section-number">4.1</span> Banco de dados e operacionalização do fechamento escolar [§32–§36]</h3>
<p>O artigo baseia-se em um banco de dados de registros escolares municipais cobrindo todos os municípios brasileiros entre 1996 e 2021. A fonte primária é o <strong>Censo Escolar</strong> (<em>Censo Escolar</em>), principal instrumento de coleta de estatísticas educacionais do país, administrado pelo INEP em colaboração com secretarias municipais, estaduais e federais. O banco contém dados sobre matrícula, professores, modalidades de ensino e localização da escola, entre mais de cem variáveis. Os dados do Censo Escolar informam a distribuição de recursos do FUNDEB (Fundo de Manutenção e Desenvolvimento da Educação Básica) aos governos estaduais e municipais.</p>
<p>Para calcular o número de fechamentos municipais, os autores construíram um banco relacional em Microsoft Access, extraindo as seguintes variáveis: ano do censo, “variável de escola” (status operacional, localização, tipo administrativo), código de unidade federativa, sigla do estado, código e nome do município, e código da escola. O código municipal funcionou como chave relacional para integrar diversas bases.</p>
<p>A operacionalização de “escola fechada” foi uma etapa metodologicamente crítica. Segundo o INEP, uma escola é classificada como “Extinta” quando encerrou definitivamente as atividades escolares (distinta de “Ativa” ou “Paralisada”). Para escolas rurais, indígenas e quilombolas, a Lei n.º 12.960/2014 estabeleceu que o fechamento deve ser precedido de manifestação do órgão regulador e da comunidade escolar. Os autores definiram “escola fechada” como aquela que aparece com o status “extinta” no ano t e estava “ativa” ou “paralisada” no ano t-1. Para evitar duplicações geradas por inconsistências históricas nos microdados — especialmente em censos anteriores a 2007 —, utilizaram comparações bianuais.</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> As notas de rodapé 5 e 6 do artigo detalham inconsistências metodológicas significativas: escolas podem mudar de localização (rural→urbana), de tipo administrativo ou de código municipal (quando um município se divide). Uma escola que era rural/paralisada/estadual em 2012 e passou a ser municipal/ativa/urbana em 2013 não é contada como fechada, mesmo que a escola original tenha efetivamente encerrado suas atividades sob aquela configuração. Isso introduz potencial subestimação sistemática em áreas de expansão urbana.</p>
</blockquote>
</section>
<section id="análise-geoespacial-e-regressão-de-painel-3740" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="análise-geoespacial-e-regressão-de-painel-3740"><span class="header-section-number">4.2</span> Análise geoespacial e regressão de painel [§37–§40]</h3>
<p>Para a análise espacial, os autores utilizaram ArcMap 10.5 e calcularam o número de fechamentos/aberturas de escolas para oito períodos correspondentes aos ciclos eleitorais federais (1994, 1998, 2002, 2006, 2010, 2014, 2016, 2020). O primeiro passo foi testar a autocorrelação espacial dos fechamentos com o índice de Moran’s I. O resultado confirmou autocorrelação estatisticamente significativa (Z=31,0; p=0), justificando a aplicação do teste de hotspot <strong>Getis-Ord*</strong> — que identifica concentrações espacialmente significativas de fechamentos escolares.</p>
<p>Na segunda etapa, os autores construíram um banco de variáveis adicionais: taxas de analfabetismo, pós-graduação e cursos de Educação do Campo; variáveis agrárias (índice de Gini fundiário, percentual de agricultores familiares, proporção de agricultores proprietários); e dados demográficos (raça e nível socioeconômico). A análise estatística usou o programa STATA 17. O modelo escolhido foi a <strong>regressão binomial negativa de painel com efeitos aleatórios</strong>, justificada por três razões: (a) variação mínima em alguns municípios; (b) sobredispersão da variável dependente (média=2,41; DP=8,19); (c) teste de Hausman não-significativo ((^2(11)=3,70); p=0,81), que justifica efeitos aleatórios sobre efeitos fixos. A análise multivariada ficou restrita a dois anos — 2006 e 2017 — por disponibilidade de dados completos, resultando em 10.824 observações (de 11.140 possíveis, com 316 excluídos por deleção listwise).</p>
</section>
</section>
<section id="sec-resultados" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="sec-resultados"><span class="header-section-number">5</span> Resultados (pp.&nbsp;12–20)</h2>
<section id="padrão-regional-e-institucional-dos-fechamentos-4147" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="padrão-regional-e-institucional-dos-fechamentos-4147"><span class="header-section-number">5.1</span> Padrão regional e institucional dos fechamentos [§41–§47]</h3>
<p>Os autores apresentam os resultados descritivos agrupados geograficamente, sustentando que as disparidades regionais são empiricamente pronunciadas e teoricamente orientadas pela ecologia política regional (Blaikie e Brookfield 1987). A Tabela 1 revela que 65% de todas as escolas rurais brasileiras foram fechadas entre 1994 e 2020 — um total de 142.401 estabelecimentos. As regiões com maior percentual de fechamentos são o Sul (83%) e o Centro-Oeste (80%), onde o agronegócio tem maior controle territorial. O Nordeste e o Norte — com a maior proporção de pessoas de cor — apresentam, respectivamente, 63% e 58% de fechamentos. O Sudeste tem 59%.</p>
<p>Institucionalmente, 90% de todos os fechamentos rurais ocorrem em escolas municipais, 9% em estaduais e aproximadamente 1% em federais e privadas. Como as escolas municipais são responsáveis pelo <strong>Ensino Fundamental</strong>, a crise de fechamentos incide precisamente na educação elementar — o que impede as comunidades rurais de obter a formação básica necessária para acessar o ensino médio e superior.</p>
<p>A Tabela 2 detalha os fechamentos por estado. Mato Grosso do Sul encabeza o ranking nacional com 93% das escolas rurais fechadas. Rondônia, na Amazônia ocidental, fechou 89%. Os estados da Região Sul — Paraná, Santa Catarina e Rio Grande do Sul — apresentam taxas de 85%, 85% e 80%, respectivamente. Em contraste, o Distrito Federal (23%) e o Amapá (30%) têm as menores taxas.</p>
</section>
<section id="ciclos-políticos-e-temporalidade-dos-fechamentos-4852" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="ciclos-políticos-e-temporalidade-dos-fechamentos-4852"><span class="header-section-number">5.2</span> Ciclos políticos e temporalidade dos fechamentos [§48–§52]</h3>
<p>A Tabela 3 mostra que o fenômeno perpassa todos os governos do período, mas com intensidades muito distintas. Dos 142.401 fechamentos, 73.868 (51,8%) ocorreram durante os dois mandatos de Fernando Henrique Cardoso (FHC), a uma média de 9.233 escolas por ano. Nos dois mandatos de Lula, esse número caiu para 32.850 (23,1%), com média de 4.106 por ano. No primeiro mandato de Dilma Rousseff, a média caiu para 3.588 anuais; no segundo, o número foi de 4.151 (2,9%) antes de ser interrompido pelo golpe político de 2016. Após o golpe, durante o governo Temer, houve uma alta precipitada: 11.732 fechamentos (8,2%) somente em 2016. Sob Bolsonaro, a taxa recuou levemente para 7.670 (5,3%).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Os autores interpretam a queda nos governos petistas como resultado de políticas favoráveis à Educação do Campo e de pressão dos movimentos sociais, em especial o MST. Contudo, como o próprio artigo reconhece, a orientação político-ideológica do partido federal <strong>não</strong> foi uma variável estatisticamente significativa no modelo de regressão — o que sugere que o mecanismo opera predominantemente no nível municipal, não federal.</p>
</div>
</div>
<p>Os mapas de hotspots (Figura 3) mostram que as maiores concentrações de fechamentos nas décadas de 1990 e 2000 estavam no Nordeste e no Sul. A diferença entre os primeiros três mapas (1994–2002) e os cinco seguintes é marcante: os hotspots diminuem tanto em intensidade quanto em extensão ao longo do tempo. Rondônia, que foi um hotspot persistente nos anos 1990, deixou de sê-lo a partir de 2010 — o que os autores apontam como questão para pesquisa futura sem resposta no artigo.</p>
</section>
<section id="fatores-preditores-dos-fechamentos-análise-multivariada-5359" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="fatores-preditores-dos-fechamentos-análise-multivariada-5359"><span class="header-section-number">5.3</span> Fatores preditores dos fechamentos: análise multivariada [§53–§59]</h3>
<p>A Tabela 4 apresenta o modelo de regressão binomial negativa com os Incident Rate Ratios (IRR). O índice de Gini fundiário é o preditor mais forte: IRR=3,28 (p&lt;0,01), indicando que um aumento de uma unidade no Gini está associado a um aumento de 228% na taxa de fechamentos. A proporção de residentes negros no município é o segundo preditor mais forte: IRR=2,75 (p&lt;0,001), correspondendo a um aumento de 175% na taxa de incidência. A urbanização tem efeito protetor: IRR=0,49 (p&lt;0,001), reduzindo os fechamentos em cerca de 51%. O número de famílias assentadas aumenta os fechamentos em 6% (IRR=1,06; p&lt;0,001). A proporção de agricultores não-proprietários reduz os fechamentos em 31% (IRR=0,69; p&lt;0,01). A agricultura não-subsistência reduz os fechamentos em 38% (IRR=0,62; p&lt;0,05). As variáveis de orientação política (centro, direita) não são estatisticamente significativas.</p>
<p>Os achados sobre pequenas propriedades rurais e agricultura não-subsistência parecem aparentemente contraditórios com o argumento central. Os autores interpretam esse resultado como evidência de que pequenas propriedades (menos de 200 ha) estão em transição da agricultura familiar para a agricultura comercial, com intensificação do trabalho assalariado e mecanização — um processo de <strong>despesantização</strong> em que a demanda por escolas rurais cai por substituição de força de trabalho familiar por trabalho contratado. Esse processo de diferenciação de classes é respaldado por McMichael (1997, 2012) e Bernstein (2004, 2008). O artigo exemplifica com o caso da região metropolitana de São Paulo, onde pequenas fazendas transitam para produção intensiva de plantas ornamentais com base em trabalho assalariado.</p>
<blockquote class="blockquote">
<p><strong>Nota :</strong> O artigo inclui um achado temporal relevante: o IRR para 2017 em relação a 2006 é 0,88 (p&lt;0,001), indicando redução significativa na taxa de fechamentos no período mais recente. Os autores atribuem isso ao aumento de municípios com zero fechamentos, o que é consistente com a leitura descritiva dos mapas de hotspots.</p>
</blockquote>
</section>
</section>
<section id="sec-conclusoes" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-conclusoes"><span class="header-section-number">6</span> Conclusões (pp.&nbsp;20–21)</h2>
<section id="contribuições-teóricas-e-metodológicas-6065" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="contribuições-teóricas-e-metodológicas-6065"><span class="header-section-number">6.1</span> Contribuições teóricas e metodológicas [§60–§65]</h3>
<p>A seção conclusiva abre com Roderick Neumann (2005: 1) para reafirmar que “o ambiente e a forma como adquirimos, disseminamos e legitimamos conhecimento sobre ele são altamente politizados, reflexivos de relações de poder e contestados.” Os autores propõem ter contribuído para a ecologia política da educação em três dimensões interseccionais.</p>
<p>A primeira contribuição é teórica: a análise demonstra que raça estrutura não apenas o acesso a recursos educacionais, mas também o conteúdo pedagógico. O movimento Educação do Campo é apresentado como modelo de resistência interseccional, articulando saberes de comunidades negras, indígenas e camponesas por meio do <em>diálogo das saberes</em> (Martínez-Torres e Rosset 2014). Os resultados empíricos confirmam que a desigualdade racial histórica é preditor estatisticamente significativo dos fechamentos — evidência de que o controle da produção de conhecimento é inseparável da questão fundiária.</p>
<p>A segunda contribuição é metodológica: a combinação de análise geoespacial avançada e regressão de painel em dados censitários de grande escala permite responder a uma pergunta fundamentalmente espacial sobre a crise. Os autores reiteram os três eixos interseccionais que propõem para pesquisa futura: (a) como histórias de violência estrutural racializam o espaço educacional; (b) como a concentração fundiária é, em si mesma, uma forma de concentração de conhecimento; (c) como a Educação do Campo oferece um modelo de resistência interseccional a partir de posições subalternas.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>O artigo termina com uma questão aberta: se os fechamentos foram maiores sob governos conservadores e menores sob governos de esquerda, mas essa variável não é estatisticamente significativa no modelo, que outros fatores — provavelmente ao nível municipal — explicam essa variação? Os autores sugerem que clientelismo e compra de votos em eleições municipais disputadas poderiam ser hipóteses relevantes para pesquisa futura, mas não as testam.</p>
</div>
</div>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">7</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> O fechamento massivo de escolas rurais no Brasil (65% do total entre 1994 e 2020) é um processo fundamentalmente racializado e estruturado pela desigualdade fundiária, no qual municípios com maior proporção de residentes negros e maiores índices de concentração de terra apresentam taxas significativamente mais altas de encerramento escolar — configurando o que os autores denominam uma crise de ecologia política da educação em que racismo estrutural e capitalismo agrário se sobrepõem territorialmente.</p>
<p><strong>Natureza do argumento:</strong> Misto — descritivo-explicativo na dimensão empírica (análise espacial e regressão de painel); teórico-normativo na dimensão da ecologia política da educação e da colonialidade do saber. O argumento é de contribuição teórica (integrar raça à ecologia política da educação) sustentada por evidência quantitativa.</p>
<p><strong>O que o texto demonstra:</strong> (a) Que o fenômeno dos fechamentos tem padrão espacial não-aleatório, com hotspots identificáveis e persistentes; (b) que raça e Gini fundiário são os preditores mais robustos da variação intermunicipal nas taxas de fechamento; (c) que 90% dos fechamentos ocorrem em escolas municipais de ensino fundamental, o que revela o locus institucional da crise; (d) que o ciclo político federal afeta descritivamente a escala dos fechamentos, mas não é variável estatisticamente significativa no modelo.</p>
<p><strong>O que fica como hipótese ou agenda:</strong> O mecanismo causal intermediário entre raça/terra e fechamentos não é identificado — o design correlacional em nível municipal não explica <em>como</em> essa relação opera (via clientelismo? via pressão do agronegócio sobre prefeitos? via lógica burocrática de nucleação?). O caso de Rondônia, que reverteu o padrão de hotspot, permanece sem explicação. A hipótese sobre clientelismo municipal é sugerida mas não testada.</p>
<p><strong>Contribuição para o debate:</strong> O artigo inova ao deslocar a ecologia política da educação de uma agenda centrada em lugar, escala e pós-humanismo para uma que coloca raça no centro da análise. Metodologicamente, representa o uso mais sistemático de dados censitários em grande escala aplicado a questões de ecologia política educacional no Brasil. Para o campo da política educacional comparada, o artigo oferece evidência de que a gestão descentralizada (municipalização) pode amplificar desigualdades raciais quando desacompanhada de mecanismos redistributivos robustos — um resultado com implicações para debates sobre descentralização em outros países do Sul Global.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>