<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-06">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Trade Unions and Left Parties in Sweden 1986–2018 – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-446ba4faaf7890b510536beef49c91e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Trade Unions and Left Parties in Sweden 1986–2018 – Annotated Bibliography">
<meta property="og:description" content="Ray &amp; Pontusson (2023)">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introdução-pp.-16" id="toc-introdução-pp.-16" class="nav-link active" data-scroll-target="#introdução-pp.-16"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–6)</a>
  <ul class="collapse">
  <li><a href="#contexto-puzzle-e-objetivo-12" id="toc-contexto-puzzle-e-objetivo-12" class="nav-link" data-scroll-target="#contexto-puzzle-e-objetivo-12"><span class="header-section-number">1.1</span> Contexto, puzzle e objetivo [§1–§2]</a></li>
  <li><a href="#literatura-e-mecanismo-teórico-central-35" id="toc-literatura-e-mecanismo-teórico-central-35" class="nav-link" data-scroll-target="#literatura-e-mecanismo-teórico-central-35"><span class="header-section-number">1.2</span> Literatura e mecanismo teórico central [§3–§5]</a></li>
  <li><a href="#três-desenvolvimentos-adversos-e-estrutura-do-argumento-68" id="toc-três-desenvolvimentos-adversos-e-estrutura-do-argumento-68" class="nav-link" data-scroll-target="#três-desenvolvimentos-adversos-e-estrutura-do-argumento-68"><span class="header-section-number">1.3</span> Três desenvolvimentos adversos e estrutura do argumento [§6–§8]</a></li>
  </ul></li>
  <li><a href="#declínio-eleitoral-e-mudança-estrutural-pp.-68" id="toc-declínio-eleitoral-e-mudança-estrutural-pp.-68" class="nav-link" data-scroll-target="#declínio-eleitoral-e-mudança-estrutural-pp.-68"><span class="header-section-number">2</span> Declínio Eleitoral e Mudança Estrutural (pp.&nbsp;6–8)</a>
  <ul class="collapse">
  <li><a href="#trajetória-eleitoral-do-sap-e-emergência-da-direita-populista-911" id="toc-trajetória-eleitoral-do-sap-e-emergência-da-direita-populista-911" class="nav-link" data-scroll-target="#trajetória-eleitoral-do-sap-e-emergência-da-direita-populista-911"><span class="header-section-number">2.1</span> Trajetória eleitoral do SAP e emergência da direita populista [§9–§11]</a></li>
  <li><a href="#transformação-da-estrutura-de-classes-1213" id="toc-transformação-da-estrutura-de-classes-1213" class="nav-link" data-scroll-target="#transformação-da-estrutura-de-classes-1213"><span class="header-section-number">2.2</span> Transformação da estrutura de classes [§12–§13]</a></li>
  </ul></li>
  <li><a href="#filiação-sindical-e-preferências-partidárias-mecanismos-teóricos-pp.-711" id="toc-filiação-sindical-e-preferências-partidárias-mecanismos-teóricos-pp.-711" class="nav-link" data-scroll-target="#filiação-sindical-e-preferências-partidárias-mecanismos-teóricos-pp.-711"><span class="header-section-number">3</span> Filiação Sindical e Preferências Partidárias: Mecanismos Teóricos (pp.&nbsp;7–11)</a>
  <ul class="collapse">
  <li><a href="#três-linhas-de-argumento-sobre-os-efeitos-da-filiação-sindical-1416" id="toc-três-linhas-de-argumento-sobre-os-efeitos-da-filiação-sindical-1416" class="nav-link" data-scroll-target="#três-linhas-de-argumento-sobre-os-efeitos-da-filiação-sindical-1416"><span class="header-section-number">3.1</span> Três linhas de argumento sobre os efeitos da filiação sindical [§14–§16]</a></li>
  <li><a href="#heterogeneidade-dos-sindicatos-e-problema-da-auto-seleção-1719" id="toc-heterogeneidade-dos-sindicatos-e-problema-da-auto-seleção-1719" class="nav-link" data-scroll-target="#heterogeneidade-dos-sindicatos-e-problema-da-auto-seleção-1719"><span class="header-section-number">3.2</span> Heterogeneidade dos sindicatos e problema da auto-seleção [§17–§19]</a></li>
  <li><a href="#variação-contextual-e-hipóteses-temporais-2021" id="toc-variação-contextual-e-hipóteses-temporais-2021" class="nav-link" data-scroll-target="#variação-contextual-e-hipóteses-temporais-2021"><span class="header-section-number">3.3</span> Variação contextual e hipóteses temporais [§20–§21]</a></li>
  </ul></li>
  <li><a href="#estrutura-organizacional-dos-sindicatos-suecos-pp.-1222" id="toc-estrutura-organizacional-dos-sindicatos-suecos-pp.-1222" class="nav-link" data-scroll-target="#estrutura-organizacional-dos-sindicatos-suecos-pp.-1222"><span class="header-section-number">4</span> Estrutura Organizacional dos Sindicatos Suecos (pp.&nbsp;12–22)</a>
  <ul class="collapse">
  <li><a href="#lo-tco-e-saco-origens-e-diferenças-2226" id="toc-lo-tco-e-saco-origens-e-diferenças-2226" class="nav-link" data-scroll-target="#lo-tco-e-saco-origens-e-diferenças-2226"><span class="header-section-number">4.1</span> LO, TCO e SACO: origens e diferenças [§22–§26]</a></li>
  <li><a href="#evolução-da-base-de-filiação-19862018-2729" id="toc-evolução-da-base-de-filiação-19862018-2729" class="nav-link" data-scroll-target="#evolução-da-base-de-filiação-19862018-2729"><span class="header-section-number">4.2</span> Evolução da base de filiação (1986–2018) [§27–§29]</a></li>
  <li><a href="#tendências-de-de-sindicalização-por-classe-figuras-36-3033" id="toc-tendências-de-de-sindicalização-por-classe-figuras-36-3033" class="nav-link" data-scroll-target="#tendências-de-de-sindicalização-por-classe-figuras-36-3033"><span class="header-section-number">4.3</span> Tendências de de-sindicalização por classe (Figuras 3–6) [§30–§33]</a></li>
  <li><a href="#causas-da-de-sindicalização-3438" id="toc-causas-da-de-sindicalização-3438" class="nav-link" data-scroll-target="#causas-da-de-sindicalização-3438"><span class="header-section-number">4.4</span> Causas da de-sindicalização [§34–§38]</a></li>
  </ul></li>
  <li><a href="#filiação-sindical-e-preferências-partidárias-análise-empírica-pp.-2331" id="toc-filiação-sindical-e-preferências-partidárias-análise-empírica-pp.-2331" class="nav-link" data-scroll-target="#filiação-sindical-e-preferências-partidárias-análise-empírica-pp.-2331"><span class="header-section-number">5</span> Filiação Sindical e Preferências Partidárias: Análise Empírica (pp.&nbsp;23–31)</a>
  <ul class="collapse">
  <li><a href="#estratégia-de-identificação-e-variáveis-3941" id="toc-estratégia-de-identificação-e-variáveis-3941" class="nav-link" data-scroll-target="#estratégia-de-identificação-e-variáveis-3941"><span class="header-section-number">5.1</span> Estratégia de identificação e variáveis [§39–§41]</a></li>
  <li><a href="#efeitos-médios-da-filiação-sindical-figura-7-e-tabela-a2-4244" id="toc-efeitos-médios-da-filiação-sindical-figura-7-e-tabela-a2-4244" class="nav-link" data-scroll-target="#efeitos-médios-da-filiação-sindical-figura-7-e-tabela-a2-4244"><span class="header-section-number">5.2</span> Efeitos médios da filiação sindical (Figura 7 e Tabela A2) [§42–§44]</a></li>
  <li><a href="#variação-temporal-dos-efeitos-sindicais-figuras-89-e-tabelas-a3a5-4549" id="toc-variação-temporal-dos-efeitos-sindicais-figuras-89-e-tabelas-a3a5-4549" class="nav-link" data-scroll-target="#variação-temporal-dos-efeitos-sindicais-figuras-89-e-tabelas-a3a5-4549"><span class="header-section-number">5.3</span> Variação temporal dos efeitos sindicais (Figuras 8–9 e Tabelas A3–A5) [§45–§49]</a></li>
  </ul></li>
  <li><a href="#conclusão-pp.-3031" id="toc-conclusão-pp.-3031" class="nav-link" data-scroll-target="#conclusão-pp.-3031"><span class="header-section-number">6</span> Conclusão (pp.&nbsp;30–31)</a>
  <ul class="collapse">
  <li><a href="#síntese-dos-resultados-5052" id="toc-síntese-dos-resultados-5052" class="nav-link" data-scroll-target="#síntese-dos-resultados-5052"><span class="header-section-number">6.1</span> Síntese dos resultados [§50–§52]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">7</span> Argumento Sintético</a></li>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Trade Unions and Left Parties in Sweden 1986–2018</h1>
<p class="subtitle lead">Ray &amp; Pontusson (2023)</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Sindicalismo Comparado</div>
    <div class="quarto-category">Comportamento Eleitoral</div>
    <div class="quarto-category">Socialdemocracia</div>
    <div class="quarto-category">Political Economy</div>
    <div class="quarto-category">Welfare State/Social Policy</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Ray, A. A., &amp; Pontusson, J. (2023). <em>Trade unions and left parties in Sweden 1986–2018</em> (Working Paper No.&nbsp;44). Unequal Democracies, University of Geneva, Department of Political Science and International Relations.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Entrada BibTeX → Ray-Pontusson2023
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@techreport</span>{<span class="ot">Ray</span>-<span class="ot">Pontusson2023</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>      = {Ray, Ari Arundhati and Pontusson, Jonas},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>       = {Trade Unions and Left Parties in Sweden 1986--2018},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>        = {2023},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">institution</span> = {University of Geneva, Department of Political Science and International Relations},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">type</span>        = {Working Paper},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">number</span>      = {44},</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">series</span>      = {Unequal Democracies},</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">month</span>       = {March},</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>Última atualização: 2026-05-06 Modelo: Perplexity, powered by Claude Sonnet 4.6 Thinking Prompt Version: v13.0 2026-04-19 | 2026-04-24 “IA Blog Post QMD” Gerado em: 2026-05-06T21:39:00-03:00</p>
<hr>
<section id="introdução-pp.-16" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-16"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–6)</h2>
<section id="contexto-puzzle-e-objetivo-12" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="contexto-puzzle-e-objetivo-12"><span class="header-section-number">1.1</span> Contexto, puzzle e objetivo [§1–§2]</h3>
<p>O artigo explora como as transformações no cenário de relações industriais sueco e na política sindical afetaram o apoio eleitoral aos partidos de esquerda desde meados da década de 1980. A Suécia é frequentemente citada como o exemplo <em>par excellence</em> da socialdemocracia bem-sucedida: o Partido Social-Democrata dos Trabalhadores (SAP) governou de 1932 a 1976, interrompido por apenas 100 dias, e permaneceu no poder por 29 dos 47 anos seguintes. Contudo, desde 1994, o apoio eleitoral ao SAP e à esquerda sueca em seu conjunto declinou em aproximadamente 20 pontos percentuais até 2018.</p>
<p>É lugar-comum na literatura atribuir a dominância histórica da socialdemocracia sueca à força e ao caráter abrangente dos sindicatos suecos, em especial os sindicatos de colarinho azul filiados à confederação LO. O argumento clássico de Przeworski e Sprague (1986) parte da constatação de que a classe trabalhadora jamais se tornou a maioria eleitoral antecipada pelo marxismo, de modo que partidos sociais-democratas precisam apelar a eleitores da classe média — e que sindicatos abrangentes mitigam o <em>trade-off</em> resultante ao reforçar a identidade de classe dos trabalhadores.</p>
</section>
<section id="literatura-e-mecanismo-teórico-central-35" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="literatura-e-mecanismo-teórico-central-35"><span class="header-section-number">1.2</span> Literatura e mecanismo teórico central [§3–§5]</h3>
<p>O que distingue os países escandinavos não é apenas a alta taxa de sindicalização entre trabalhadores manuais, mas sobretudo a elevada sindicalização dos trabalhadores de colarinho branco, vinculada à existência de sindicatos separados para esse segmento. Svensson (1994) documenta como a TCO (confederação setorial de colarinho branco) emergiu como grupo de interesse pivô nos anos 1960, com membros do SAP assumindo posições de liderança e orientando os sindicatos filiados à TCO em direção a práticas compatíveis com o projeto socialdemocrata. Essa sindicalização de colarinho branco teria possibilitado que os social-democratas mobilizassem eleitores de classe média em termos mais consistentes com a mobilização da classe trabalhadora do que em outros países.</p>
<p>O sistema sueco de seguro-desemprego administrado pelos próprios sindicatos — o chamado <strong>sistema de Ghent</strong> — cria incentivos seletivos para a filiação sindical e é invocado como explicação-chave para a alta taxa de sindicalização. Rothstein (1992) acrescenta que os social-democratas optaram estrategicamente pelo sistema de Ghent nos anos 1930, em vez de um seguro estatal, antecipando seus efeitos organizacionais de longo prazo.</p>
</section>
<section id="três-desenvolvimentos-adversos-e-estrutura-do-argumento-68" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="três-desenvolvimentos-adversos-e-estrutura-do-argumento-68"><span class="header-section-number">1.3</span> Três desenvolvimentos adversos e estrutura do argumento [§6–§8]</h3>
<blockquote class="blockquote">
<p>Qual é o impacto das transformações no sindicalismo sueco — de-sindicalização, fragmentação organizacional e reorientação das práticas sindicais — sobre o apoio eleitoral aos partidos de esquerda no período 1986–2018?</p>
</blockquote>
<p>Os autores identificam três desenvolvimentos que enfraqueceram a capacidade mobilizacional da esquerda sueca. O primeiro é a <strong>de-sindicalização</strong>: a taxa de sindicalização dos trabalhadores de colarinho azul declinou acentuadamente desde o início dos anos 1990, e a dos trabalhadores de colarinho branco com menor escolaridade também caiu nas últimas duas décadas. O segundo é o <strong>deslocamento organizacional</strong>: com a expansão do ensino superior, filiados de colarinho branco migraram de sindicatos setoriais (TCO) para sindicatos ocupacionais mais estreitos (SACO), cujas práticas de negociação e advocacia de políticas são menos propícias a gerar apoio eleitoral para a esquerda. O terceiro é a <strong>reorientação das práticas sindicais</strong>: a descentralização da negociação coletiva, o recuo do <em>welfare state</em> e a crescente competição entre sindicatos tornaram todos os sindicatos — inclusive os tradicionalmente filiados à esquerda — mais focados na entrega de benefícios concretos a seus próprios membros, em detrimento de objetivos coletivos redistributivos.</p>
<p>O artigo está organizado da seguinte forma: os autores começam descrevendo o declínio eleitoral da esquerda sueca e as mudanças estruturais na composição de classe da força de trabalho; em seguida, revisam a literatura sobre os efeitos da filiação sindical nas preferências políticas; depois, mobilizam dados administrativos e dados das pesquisas SOM para descrever tendências de sindicalização; e, por fim, analisam os efeitos da filiação sindical sobre as preferências partidárias com base em modelos OLS com dados SOM para 1986–2018.</p>
<p>Dois pontos metodológicos merecem atenção desde o início. Primeiro, os autores reconhecem que as transformações no cenário sindical não são variáveis exógenas — governos social-democratas e de centro-direita contribuíram para essas mudanças. O artigo propõe, portanto, analisar a <strong>co-evolução</strong> entre política sindical e política eleitoral. Segundo, o trabalho explicitamente não busca estimar efeitos causais no sentido técnico-econométrico, mas sim descrever associações e padrões temporais que permitem avaliações sobre o mecanismo em questão.</p>
<hr>
</section>
</section>
<section id="declínio-eleitoral-e-mudança-estrutural-pp.-68" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="declínio-eleitoral-e-mudança-estrutural-pp.-68"><span class="header-section-number">2</span> Declínio Eleitoral e Mudança Estrutural (pp.&nbsp;6–8)</h2>
<section id="trajetória-eleitoral-do-sap-e-emergência-da-direita-populista-911" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="trajetória-eleitoral-do-sap-e-emergência-da-direita-populista-911"><span class="header-section-number">2.1</span> Trajetória eleitoral do SAP e emergência da direita populista [§9–§11]</h3>
<p>A análise histórico-eleitoral revela que o SAP oscilou entre 43% e 46% nas décadas de 1970 e 1980, caiu para 37,7% em 1991, recuperou-se em 1994 e depois perdeu apoio em quase todas as eleições até 2018. A fatia do partido em 2018 (28,3%) foi a menor desde a introdução do sufrágio universal em 1919. O declínio da esquerda como bloco foi ainda mais pronunciado: a soma de SAP, Partido de Esquerda e Verdes caiu de 56,5% em 1994 para 36,3% em 2018.</p>
<p>O Partido dos Democratas Suecos (SD), de direita populista, entrou no parlamento em 2010 com 5,7% e chegou a 20,5% em 2022, tornando-se o maior partido “burguês”. O SD exemplifica o <strong>chauvinismo de <em>welfare</em></strong>: combina oposição à imigração com apoio a benefícios sociais para os “nativos merecedores” e atrai eleitores tradicionais social-democratas de classe trabalhadora e baixa classe média. Os autores advertem, porém, que o declínio eleitoral da esquerda claramente precede o avanço do SD em 2010, sugerindo que a ascensão do populismo de direita é consequência, tanto quanto causa, da capacidade mobilizacional declinante do SAP (cf.&nbsp;Oskarsson e Demker 2015).</p>
</section>
<section id="transformação-da-estrutura-de-classes-1213" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="transformação-da-estrutura-de-classes-1213"><span class="header-section-number">2.2</span> Transformação da estrutura de classes [§12–§13]</h3>
<p>Com base em dados SOM, os autores rastreiam a evolução da estrutura de classes da força de trabalho sueca de 1986 a 2018, subdividindo-a em quatro categorias: trabalhadores de colarinho azul (<em>arbetare</em>), colarinho branco sem ensino superior, colarinho branco com ensino superior e “outros” (agricultores, pequenos empresários e profissionais autônomos). O dado mais saliente não é o declínio do colarinho azul — de 55% para pouco menos de 45% — mas a expansão dramática dos trabalhadores de colarinho branco com ensino superior: de aproximadamente 15% no início dos anos 1980 para 33% no final dos 2010s.</p>
<p>Essa transformação estrutural tem implicações diretas para a sindicalização, pois o crescimento da categoria de colarinho branco universitário favoreceu os sindicatos ocupacionais da SACO em detrimento dos setoriais da TCO. Os autores observam que mudanças na composição de classe da força de trabalho se traduzem em mudanças na estrutura de classe do eleitorado com alguma defasagem temporal, dado que os aposentados representavam 28% do eleitorado sueco em 2021.</p>
<hr>
</section>
</section>
<section id="filiação-sindical-e-preferências-partidárias-mecanismos-teóricos-pp.-711" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="filiação-sindical-e-preferências-partidárias-mecanismos-teóricos-pp.-711"><span class="header-section-number">3</span> Filiação Sindical e Preferências Partidárias: Mecanismos Teóricos (pp.&nbsp;7–11)</h2>
<section id="três-linhas-de-argumento-sobre-os-efeitos-da-filiação-sindical-1416" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="três-linhas-de-argumento-sobre-os-efeitos-da-filiação-sindical-1416"><span class="header-section-number">3.1</span> Três linhas de argumento sobre os efeitos da filiação sindical [§14–§16]</h3>
<p>A literatura comparada sobre os efeitos políticos da filiação sindical articula três argumentos distintos. O primeiro é o <strong>efeito de participação</strong>: a filiação sindical promove o interesse pela política e facilita a participação eleitoral. Nessa versão pura, os sindicatos não afetam as preferências políticas dos membros, mas simplesmente aumentam a participação — o que beneficia a esquerda na medida em que os sindicatos organizam indivíduos cujos “interesses objetivos” se alinham com os partidos de esquerda.</p>
<p>O segundo é o <strong>efeito de esclarecimento</strong> (<em>enlightenment effect</em>): as atividades e informações associadas à filiação sindical ajudam os indivíduos a conectar suas preferências de política pública às plataformas dos partidos. Este efeito beneficia a esquerda na medida em que os sindicatos organizam pessoas cujas preferências redistributivas se alinham com os compromissos dos partidos de esquerda, mas que poderiam ser “distraídas” por outras considerações — como, por exemplo, a questão imigratória que “contra-pressiona” muitos trabalhadores de classe baixa (cf.&nbsp;Rennwald e Mosimann 2023).</p>
<p>O terceiro — e empiricamente mais exigente — é o <strong>efeito de preferência</strong> (<em>preference effect</em>), desenvolvido por Mosimann e Pontusson (2017, 2022): a filiação sindical efetivamente molda as preferências de políticas, em particular as preferências redistributivas. Os sindicatos que historicamente praticam <strong>política salarial solidarista</strong> — nivelando diferenciais de rendimentos por negociação coletiva — promovem normas igualitárias entre seus membros. Na Suécia dos anos 1960–1970, o modelo Rehn-Meidner representou um constructo intelectual coerente que desafiava o suposto <em>trade-off</em> entre igualitarismo e crescimento econômico, reforçando o apoio universal ao <em>welfare state</em> redistributivo.</p>
</section>
<section id="heterogeneidade-dos-sindicatos-e-problema-da-auto-seleção-1719" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="heterogeneidade-dos-sindicatos-e-problema-da-auto-seleção-1719"><span class="header-section-number">3.2</span> Heterogeneidade dos sindicatos e problema da auto-seleção [§17–§19]</h3>
<p>Os autores enfatizam que “sindicatos” não são todos iguais. Distinções relevantes incluem: (a) sindicatos com laços históricos a partidos de esquerda <em>versus</em> sindicatos que se pretendem politicamente neutros; (b) sindicatos <strong>abrangentes</strong> (que incluem trabalhadores de baixo salário) <em>versus</em> <strong>sindicatos ocupacionais</strong> que organizam apenas assalariados qualificados e relativamente bem pagos. Essas distinções afetam o mecanismo esperado: a filiação à mesma organização que inclui trabalhadores de saúde gerais tende a produzir normas igualitárias mais fortes do que a filiação a uma associação exclusiva de médicos especialistas.</p>
<p>O problema da <strong>auto-seleção</strong> é central na literatura: indivíduos que optam por se filiar a sindicatos de esquerda provavelmente já são de esquerda. No caso sueco, dois fatores mitigam esse viés. Primeiro, os incentivos seletivos para a filiação criados pelo sistema de Ghent são muito fortes. Segundo, a vasta maioria dos trabalhadores de colarinho azul e do colarinho branco sem ensino superior não tem escolha sobre qual sindicato integrar — o que reduz substancialmente o escopo da auto-seleção ideológica.</p>
</section>
<section id="variação-contextual-e-hipóteses-temporais-2021" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="variação-contextual-e-hipóteses-temporais-2021"><span class="header-section-number">3.3</span> Variação contextual e hipóteses temporais [§20–§21]</h3>
<p>Os autores também esperam que os efeitos da filiação sindical variem em função do contexto temporal. A lógica da auto-seleção sugeriria que a de-sindicalização <em>intensifica</em> o efeito de esquerda da filiação sindical, pois os indivíduos de orientação direitista tenderiam a ser os primeiros a sair. A hipótese alternativa dos autores é que a socialização sindical tem efeitos duradouros e que a de-sindicalização está associada a uma <em>diminuição</em> das diferenças políticas entre filiados e não-filiados, já que aumenta a proporção de ex-membros entre os não-sindicalizados.</p>
<p>A competição entre sindicatos constitui outro fator contextual relevante. Sindicatos ocupacionais “upscale” que disputam membros qualificados com sindicatos setoriais constrangem o igualitarismo destes últimos ao forçá-los a prover incentivos seletivos em vez de redistribuição ampla. Os autores preveem que essa dinâmica deve se traduzir em uma diminuição do efeito de filiação sobre as atitudes políticas — formando, junto com a descentralização da negociação salarial e o recuo do <em>welfare state</em>, um <strong>ciclo vicioso</strong> que enfraquece os vínculos entre sindicatos e esquerda.</p>
<hr>
</section>
</section>
<section id="estrutura-organizacional-dos-sindicatos-suecos-pp.-1222" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="estrutura-organizacional-dos-sindicatos-suecos-pp.-1222"><span class="header-section-number">4</span> Estrutura Organizacional dos Sindicatos Suecos (pp.&nbsp;12–22)</h2>
<section id="lo-tco-e-saco-origens-e-diferenças-2226" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="lo-tco-e-saco-origens-e-diferenças-2226"><span class="header-section-number">4.1</span> LO, TCO e SACO: origens e diferenças [§22–§26]</h3>
<p>A fragmentação organizacional do sindicalismo sueco remonta às décadas de 1930 e 1940 e possui três dimensões sobrepostas: (i) a distinção entre sindicatos de colarinho azul e branco; (ii) a distinção entre <strong>sindicatos setoriais</strong> (organizam por setor de atividade) e <strong>sindicatos ocupacionais</strong> (organizam por qualificação profissional); e (iii) a distinção entre sindicatos social-democratas e sindicatos politicamente neutros. Fundada em 1898, a LO é a confederação de sindicatos de colarinho azul com vínculos históricos ao SAP. Até recentemente, era prática corrente os diretórios locais de sindicatos filiados à LO afiliarem-se coletivamente ao SAP, permitindo que membros individuais optassem por não participar. Em 1990, sob ameaça de proibição parlamentar, o SAP descontinuou essa prática, com consequente queda na filiação partidária. Ainda assim, muitos vínculos organizacionais e informais entre LO e SAP persistem (Aylott 2003; Jansson 2017).</p>
<p>A TCO surgiu como o equivalente “apolítico” de colarinho branco da LO, organizando trabalhadores assalariados em sindicatos setoriais. Conforme reconta Svensson (1994), a TCO tornou-se aliada-chave da LO e do SAP na luta pela reforma previdenciária dos anos 1950, quando os social-democratas passaram de uma “aliança trabalhador-agricultor” para uma “estratégia do assalariado”. Nas décadas de 1960 e 1970, a TCO e a LO coordenaram cada vez mais suas negociações salariais e esforços de influência sobre as políticas governamentais. O surgimento dos sindicatos setoriais de colarinho branco impulsionou associações profissionais de advogados, médicos e engenheiros a se mobilizarem em defesa dos diferenciais salariais. Essas associações formaram a SACO (1947), com membros restritos a graduados universitários, atuando predominantemente no setor público até os anos 1970 e construindo reputação de militância <em>contra</em> as políticas salariais solidaristas da LO-TCO.</p>
</section>
<section id="evolução-da-base-de-filiação-19862018-2729" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="evolução-da-base-de-filiação-19862018-2729"><span class="header-section-number">4.2</span> Evolução da base de filiação (1986–2018) [§27–§29]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tabela 1 — Membros economicamente ativos por confederação (em milhares), 1986 e 2018</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Confederação</th>
<th style="text-align: right;">1986</th>
<th style="text-align: right;">2018</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LO</td>
<td style="text-align: right;">2.004</td>
<td style="text-align: right;">1.233</td>
</tr>
<tr class="even">
<td style="text-align: left;">TCO</td>
<td style="text-align: right;">1.108</td>
<td style="text-align: right;">1.097</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SACO</td>
<td style="text-align: right;">219</td>
<td style="text-align: right;">539</td>
</tr>
<tr class="even">
<td style="text-align: left;">Independentes</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">103</td>
</tr>
</tbody>
</table>
<p><em>Fonte: Kjellberg (2019b), Apêndice 4, Tabela 46. Inclui desempregados; exclui estudantes em tempo integral e aposentados.</em></p>
</div>
</div>
<p>A LO perdeu quase 40% de seus membros economicamente ativos entre 1986 e 2018, passando de 2.004 para 1.233 mil. A TCO manteve-se relativamente estável (de 1.108 para 1.097 mil), enquanto a SACO mais que dobrou (de 219 para 539 mil) e os sindicatos independentes quintuplicaram. Em 2018, a LO contava com 14 sindicatos filiados (era 17 em 1986, após fusões e uma saída), dos quais 11 de base setorial respondendo por mais de 97% dos membros. Os dois maiores — o Sindicato dos Municipais (<em>Kommunal</em>) e o Sindicato dos Trabalhadores da Manufatura (<em>IF Metall</em>) — sozinhos representavam mais de 60% do total da LO.</p>
<p>Na TCO, a composição interna também se deslocou: em 1986, havia 11 sindicatos setoriais e 9 ocupacionais; em 2018, a proporção havia mudado para 8–9 setoriais e 4–5 ocupacionais. Os sindicatos setoriais ainda dominavam — representando 88% da filiação total da TCO ao se incluir o Sindicato dos Professores (<em>Lärarförbundet</em>) —, mas a pressão dos sindicatos da SACO por membros universitários era crescente. A SACO mantinha 20–22 sindicatos filiados, todos de base ocupacional/profissional, com o maior deles — a Associação dos Engenheiros Suecos — respondendo por cerca de um quinto do total em 2018.</p>
</section>
<section id="tendências-de-de-sindicalização-por-classe-figuras-36-3033" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="tendências-de-de-sindicalização-por-classe-figuras-36-3033"><span class="header-section-number">4.3</span> Tendências de de-sindicalização por classe (Figuras 3–6) [§30–§33]</h3>
<p>Os dados das pesquisas SOM revelam trajetórias diferenciadas de sindicalização por classe. Entre trabalhadores de colarinho azul, a taxa de filiação a sindicatos da LO declinou de 77% na segunda metade dos anos 1980 para 42% na segunda metade dos 2010s — sendo a de-sindicalização (e não a migração para outros sindicatos) o fenômeno dominante, com a proporção de não-sindicalizados subindo de 18% para quase 40%. Entre os trabalhadores de colarinho branco sem ensino superior, a de-sindicalização foi menos pronunciada (de 21% para 27% de não-sindicalizados), mas também envolveu perdas para sindicatos da LO, enquanto a filiação à TCO permaneceu estável entre 55 e 60%. Entre os trabalhadores de colarinho branco com ensino superior, observa-se aumento nos não-sindicalizados (de 17% para 26%) e declínio na filiação TCO (de 47% para 33%), com a SACO ligeiramente estável (de 34% para 37%).</p>
<p>A Figura 6, que apresenta a sindicalização de trabalhadores de colarinho branco por setor, é particularmente reveladora: no setor privado, a sindicalização total manteve-se estável, mas a participação da TCO caiu cerca de 15 pontos percentuais e a da SACO cresceu correspondentemente. No setor público, houve alguma de-sindicalização geral e, mais significativamente, os sindicatos da SACO quase alcançaram os da TCO em termos de participação. Os autores enfatizam que a principal razão para o crescimento relativo da SACO não é a migração de membros, mas a expansão da força de trabalho universitariamente qualificada — reflexo das políticas de expansão do ensino superior implementadas principalmente pelo governo social-democrata que assumiu em 1994. A questão de se os formuladores de políticas social-democratas reconheceram o problema que a expansão do ensino superior criaria para os sindicatos da TCO fica em aberto.</p>
</section>
<section id="causas-da-de-sindicalização-3438" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="causas-da-de-sindicalização-3438"><span class="header-section-number">4.4</span> Causas da de-sindicalização [§34–§38]</h3>
<p>A literatura atribui comumente a de-sindicalização à reforma do seguro-desemprego implementada pelo governo de centro-direita que chegou ao poder em 2006 (cf.&nbsp;Kjellberg e Ibsen 2016; Gordon 2017). A reforma introduziu um sistema de prêmios variáveis — dependentes da taxa de desemprego do setor coberto pelo fundo —, o que levou a um aumento dramático dos prêmios, especialmente para trabalhadores de colarinho azul em setores mais expostos ao desemprego, provocando uma saída em massa dos fundos de seguro-desemprego administrados pelos sindicatos. Contudo, os autores ressaltam que o declínio do colarinho azul começou já nos anos 1990 e continuou mesmo após o abandono do “princípio de mercado” para os prêmios em 2014 — portanto outros fatores precisam ser considerados.</p>
<p>A <strong>privatização extensiva dos serviços públicos</strong>, empreendida tanto por governos social-democratas quanto de centro-direita nas décadas de 1990 e 2000, representa um desenvolvimento importante e relativamente negligenciado pelos especialistas em relações industriais (cf.&nbsp;Gingrich 2011). A privatização assumiu sobretudo a forma de terceirização de serviços (refeições, limpeza etc.) por entidades públicas (escolas, hospitais, instalações de assistência) para empresas privadas — e os trabalhadores dessas subcontratadas, embora frequentemente identificados como “servidores públicos” nas estatísticas oficiais, têm menor propensão a se sindicalizar.</p>
<p>A expansão do <strong>emprego temporário</strong> constitui outro fator relevante: indivíduos com contratos temporários são muito menos propensos a se filiar a sindicatos do que os com contratos permanentes. Na Suécia, governos de centro-direita removeram restrições sobre contratos temporários na crise do início dos anos 1990, com novas desregulamentações implementadas pelos social-democratas no final dos anos 1990 e pelos partidos burgueses na crise de 2008–09. Entre jovens de 15–24 anos, a incidência de emprego temporário subiu de 48,4% em 1997 para o pico histórico de 57,3% em 2008. Finalmente, a sindicalização de trabalhadores nascidos no exterior declinou mais acentuadamente do que a de trabalhadores nascidos na Suécia: em 2019, a taxa de sindicalização de colarinho azul de nascidos no exterior era de 51%, versus 64% para os nascidos no país (dados: Kjellberg e Nergaard 2022).</p>
<hr>
</section>
</section>
<section id="filiação-sindical-e-preferências-partidárias-análise-empírica-pp.-2331" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="filiação-sindical-e-preferências-partidárias-análise-empírica-pp.-2331"><span class="header-section-number">5</span> Filiação Sindical e Preferências Partidárias: Análise Empírica (pp.&nbsp;23–31)</h2>
<section id="estratégia-de-identificação-e-variáveis-3941" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="estratégia-de-identificação-e-variáveis-3941"><span class="header-section-number">5.1</span> Estratégia de identificação e variáveis [§39–§41]</h3>
<p>As pesquisas SOM perguntam anualmente aos respondentes qual partido preferem (“Qual partido você prefere hoje?”). Os autores interpretam as respostas como indicativas da intenção de voto e estimam modelos OLS para a probabilidade de preferir o SAP e a probabilidade de preferir qualquer partido da esquerda (SAP, Partido de Esquerda e Verdes). A análise é segmentada por classe ocupacional — colarinho azul, colarinho branco não-terciário e colarinho branco terciário. A <strong>variável independente de interesse</strong> é uma variável categórica indicando filiação a sindicato da LO, da TCO ou da SACO, com não-sindicalizados como categoria de referência. Os modelos controlam por gênero, faixa etária, nível educacional, setor de emprego e região de residência, incluindo efeitos-fixos de ano para capturar tendências temporais.</p>
</section>
<section id="efeitos-médios-da-filiação-sindical-figura-7-e-tabela-a2-4244" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="efeitos-médios-da-filiação-sindical-figura-7-e-tabela-a2-4244"><span class="header-section-number">5.2</span> Efeitos médios da filiação sindical (Figura 7 e Tabela A2) [§42–§44]</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Os resultados para o período completo 1986–2018 (Figura 7) mostram que membros sindicais, independentemente da afiliação confederal, são mais propensos a votar em partidos de esquerda e no SAP do que não-filiados. O efeito da filiação sindical sobre a probabilidade de preferir o SAP varia de 4 pontos percentuais (colarinho branco terciário filiado à SACO) a 26 pontos percentuais (colarinho branco não-terciário filiado à LO). Para qualquer partido de esquerda, o intervalo vai de 9 a 29 pontos percentuais.</p>
</div>
</div>
<p>Uma descoberta relevante é que a sindicalização entre trabalhadores de colarinho branco terciário favorece sobretudo partidos de esquerda <em>outros que não o SAP</em>, o que é especialmente pronunciado para membros da SACO. Os autores também identificam diferenças intra-classe significativas: entre colarinho azul e não-terciário branco, membros da LO são, em média, mais à esquerda do que membros da TCO; e entre colarinho branco terciário, membros da TCO são mais à esquerda do que membros da SACO. Isso sugere alguma <strong>triagem ideológica/partidária</strong>: quando há escolha disponível, indivíduos de esquerda tendem a ingressar em sindicatos de esquerda.</p>
<p>O resultado mais notável da Tabela A2 é que o efeito de pertencer a um sindicato da TCO sobre as preferências dos trabalhadores de colarinho branco não-terciários é estatisticamente indistinguível do efeito de pertencer a um sindicato da LO sobre os trabalhadores de colarinho azul (coeficientes de 0,15 e 0,16, respectivamente, com erros-padrão de 0,01). Isso reforça o papel central dos sindicatos setoriais — tanto da LO quanto da TCO — como mecanismos de mobilização eleitoral da esquerda.</p>
</section>
<section id="variação-temporal-dos-efeitos-sindicais-figuras-89-e-tabelas-a3a5-4549" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="variação-temporal-dos-efeitos-sindicais-figuras-89-e-tabelas-a3a5-4549"><span class="header-section-number">5.3</span> Variação temporal dos efeitos sindicais (Figuras 8–9 e Tabelas A3–A5) [§45–§49]</h3>
<p>Para verificar se os efeitos da filiação sindical foram estáveis ao longo do tempo, os autores estimam um modelo de interação entre dummies de período e indicadores de classe/filiação confederal. Os resultados mostram que os membros de sindicatos da LO (colarinho azul) e da TCO (colarinho branco não-terciário) tornaram-se <em>menos</em> distintos em termos de orientação para a esquerda em relação aos não-sindicalizados de suas respectivas classes. A diferença na propensão de preferir um partido de esquerda entre membros da LO e trabalhadores de colarinho azul não-sindicalizados caiu aproximadamente <strong>15 pontos percentuais</strong> desde a segunda metade dos anos 1980 (de 0,32 para 0,14 segundo as Tabelas A3). O padrão é idêntico para os membros da TCO de colarinho branco não-terciário (de 0,24 para 0,10 segundo a Tabela A4).</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esses resultados contradizem diretamente a hipótese de auto-seleção intensificada pela de-sindicalização. Se indivíduos de direita estivessem abandonando os sindicatos, o efeito residual de esquerda entre os membros deveria aumentar — o que claramente não ocorreu. Isso sugere que a mudança reflete transformações nas práticas e na retórica dos próprios sindicatos, não apenas na composição de seus membros.</p>
</div>
</div>
<p>Os autores propõem uma explicação mais unificada: tanto a LO quanto a TCO foram forçadas a aceitar procedimentos de fixação individual de salários em empresas privadas e no setor público, tornando a solidariedade salarial um elemento menos proeminente do que fazem e do que comunicam a seus membros. Em resposta às perdas de filiação, os sindicatos passaram a enfatizar serviços individualizados e seguros complementares (especialmente seguros-desemprego suplementares negociados com empregadores) — o que Kjellberg (2019a) documenta como parte da nova lógica de atuação sindical. Descentralização da negociação salarial, retração do <em>welfare state</em> e competição inter-sindical formam, assim, um <strong>ciclo vicioso</strong> que explica o declínio dos efeitos da filiação sobre as preferências partidárias.</p>
<p>Para trabalhadores de colarinho branco terciário (Figura 9 e Tabela A5), o padrão é diferente: membros de sindicatos da TCO nessa categoria também se tornaram menos distintamente à esquerda, mas a mudança é menos pronunciada; já membros da SACO exibem propensão relativamente estável de favorecer partidos de esquerda ao longo de todo o período. A aparente convergência dos efeitos TCO e SACO nos anos 2010 entre o colarinho branco terciário pode ser atribuída ao deslocamento de membros da TCO para a SACO e ao crescimento da SACO via recrutamento de novos entrantes no mercado de trabalho — tornando os sindicatos SACO mais abrangentes e ideologicamente heterogêneos ao longo do tempo.</p>
<hr>
</section>
</section>
<section id="conclusão-pp.-3031" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="conclusão-pp.-3031"><span class="header-section-number">6</span> Conclusão (pp.&nbsp;30–31)</h2>
<section id="síntese-dos-resultados-5052" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="síntese-dos-resultados-5052"><span class="header-section-number">6.1</span> Síntese dos resultados [§50–§52]</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>A análise confirma que membros de sindicatos suecos ainda são mais favoráveis à esquerda do que os demais cidadãos, e que a de-sindicalização é relevante para explicar o declínio eleitoral da esquerda desde meados dos anos 1990. Contudo, a vantagem eleitoral que os partidos de esquerda desfrutam entre trabalhadores de colarinho azul e colarinho branco não-terciário sindicalizados diminuiu substancialmente. Com o tempo, os efeitos de pertencer a sindicatos da LO e da TCO tornaram-se semelhantes aos efeitos (estáveis) de pertencer a sindicatos da SACO. Os sindicatos suecos tornaram-se mais focados na defesa dos interesses de curto prazo de seus membros e menos atores de mudança social. Nesse sentido, “os sindicatos suecos tornaram-se mais parecidos com os sindicatos de outras democracias liberais.”</p>
</div>
</div>
<p>Os dois mecanismos centrais — de-sindicalização e ascensão dos sindicatos ocupacionais — tiveram efeitos distintos: a de-sindicalização encolheu o tamanho do grupo que, em média, vota na esquerda; a migração para sindicatos da SACO reduziu a “taxa de conversão” eleitoral da filiação. Ambos os mecanismos, contudo, são parcialmente endógenos às escolhas de política pública de governos social-democratas e de centro-direita — o que torna a co-evolução entre política sindical e política eleitoral o enquadramento analítico adequado.</p>
<hr>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">7</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> A queda no apoio eleitoral aos partidos de esquerda na Suécia desde meados dos anos 1990 é parcialmente explicada por dois processos complementares no sindicalismo: (1) a de-sindicalização entre trabalhadores de colarinho azul e colarinho branco não-terciário, que reduziu o tamanho do grupo mais propenso a votar na esquerda; e (2) a erosão do efeito de filiação sindical sobre as preferências partidárias — especialmente nos sindicatos da LO e da TCO —, atribuível à descentralização da negociação salarial, ao recuo do <em>welfare state</em> e à crescente competição inter-sindical, que transformaram os sindicatos em organizações focadas em benefícios individuais em vez de redistribuição coletiva.</p>
<p><strong>Natureza do argumento:</strong> Predominantemente descritivo-explicativo. O artigo não estima efeitos causais no sentido econométrico rigoroso, mas mobiliza modelos de regressão com controles e efeitos-fixos de ano para documentar associações e padrões temporais.</p>
<p><strong>O que o texto demonstra:</strong> (a) A existência de um efeito positivo robusto e estatisticamente significativo da filiação sindical sobre a propensão de votar em partidos de esquerda, diferenciado por classe e confederação; (b) o declínio temporal desse efeito nos sindicatos da LO e da TCO, sem o correspondente fortalecimento esperado pela hipótese de auto-seleção.</p>
<p><strong>O que permanece como hipótese ou agenda:</strong> Os mecanismos específicos pelos quais as mudanças organizacionais se traduzem em mudanças nas preferências dos membros (solidariedade salarial <em>versus</em> comunicação sindical <em>versus</em> composição de membros) não são diretamente identificados. A questão de se as políticas de expansão do ensino superior pelos social-democratas nos anos 1990 foram estrategicamente miopes fica em aberto.</p>
<p><strong>Contribuição ao debate:</strong> O artigo avança a literatura sobre o <strong>dilema eleitoral da socialdemocracia</strong> (Przeworski e Sprague 1986; Rennwald e Pontusson 2021) ao documentar que o problema não é apenas o encolhimento da classe trabalhadora, mas também a transformação funcional dos sindicatos que antes amplificavam a identidade de classe. Contribui também para a literatura sobre <strong>variedades de sindicalismo</strong> (Mosimann e Pontusson 2017, 2022) ao mostrar que a distinção entre sindicatos setoriais e ocupacionais tem consequências eleitorais mensuráveis no longo prazo.</p>
</div>
</div>
<hr>
</section>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v13.0</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A pergunta é bem delimitada, mas a natureza predominantemente descritivo-explicativa — e não causal — não é completamente explicitada pelos autores. Uma interpretação alternativa seria enquadrar o paper como um <em>puzzle</em> de mudança institucional (por que os sindicatos suecos perderam sua eficácia mobilizacional?), não apenas como análise de declínio eleitoral. O ponto mais vulnerável é a ausência de separação analítica clara entre os dois mecanismos (de-sindicalização versus erosão do efeito condicional).</td>
<td style="text-align: left;">Como as transformações no cenário sindical sueco — de-sindicalização, fragmentação organizacional e reorientação das práticas sindicais — afetaram o apoio eleitoral aos partidos de esquerda entre 1986 e 2018? A pergunta é predominantemente explicativa, com forte componente descritivo. Explicitada na introdução, embora a formulação precisa dos dois mecanismos só apareça depois de alguma discussão teórica.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">A literatura sobre os efeitos da filiação sindical frequentemente ignora a variação interna entre tipos de sindicatos; a pergunta sobre variação temporal dos efeitos é metodologicamente mais exigente e representa o principal valor agregado do paper.</td>
<td style="text-align: left;">(1) Qual é o efeito diferencial da filiação sindical sobre as preferências partidárias conforme a confederação (LO, TCO, SACO) e a classe ocupacional? (2) Os efeitos da filiação sindical sobre as preferências partidárias foram estáveis ao longo do tempo? (3) Quais são os fatores que explicam a de-sindicalização entre trabalhadores de colarinho azul e colarinho branco sem ensino superior? As questões secundárias são subsidiárias e essenciais para a interpretação do argumento central.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno — a combinação de de-sindicalização <em>e</em> erosão do efeito condicional é mais interessante do que qualquer um dos fenômenos isoladamente. A generalizabilidade além do caso sueco é plausível mas dependente de condições específicas (sistema de Ghent, alta densidade sindical histórica). O paper não testa sistematicamente a generalizabilidade.</td>
<td style="text-align: left;">Puzzle explicativo combinado com gap descritivo: a literatura anterior documentou a de-sindicalização e o declínio eleitoral da esquerda, mas não havia demonstrado empiricamente a erosão do efeito de filiação sindical sobre as preferências partidárias ao longo do tempo. O puzzle é genuíno; sua generalizabilidade para outros contextos com arquiteturas sindicais diferentes (ex.: Reino Unido, EUA) é plausível, mas condicionada à presença de incentivos seletivos comparáveis à filiação sindical.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese é clara e empiricamente sustentada para a parte descritiva, mas a identificação dos mecanismos causais por trás da erosão do efeito temporal é mais especulativa. O <em>claim</em> central — que o ciclo vicioso (descentralização + retração do welfare + competição inter-sindical) explica a mudança — não é testado diretamente com design de identificação adequado.</td>
<td style="text-align: left;">A queda no apoio eleitoral aos partidos de esquerda na Suécia resulta tanto da de-sindicalização (efeito composicional) quanto da erosão do “efeito de esquerda” da filiação, especialmente em sindicatos da LO e da TCO. O argumento é descritivo-explicativo; o <em>claim of discovery</em> é a documentação empírica da erosão temporal do efeito condicional, que não havia sido estabelecida sistematicamente para o caso sueco com dados longitudinais de survey.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O principal limite de identificação é a impossibilidade de separar efeitos causais da filiação sindical de seleção residual não observada — os autores reconhecem o problema mas não o resolvem por design. A análise de variação temporal via interações é metodologicamente correta para o objetivo descritivo, mas não permite inferência causal sobre os mecanismos específicos.</td>
<td style="text-align: left;">Estudo quantitativo-observacional longitudinal. Fontes de dados: pesquisas SOM (1986–2018, amostra anual representativa da população sueca entre 16–85 anos, via registro fiscal) e dados administrativos de Kjellberg sobre filiação sindical. Técnicas: modelos OLS com variáveis dependentes binárias (preferência por SAP; preferência por qualquer partido de esquerda), variável independente categórica de filiação confederal, controles sociodemográficos e efeitos-fixos de ano; análise temporal via modelos de interação com dummies de período.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">A dependência de uma única fonte de survey (SOM) é uma limitação não reconhecida; a codificação da afiliação confederal para os anos 2012–2018 (via reclassificação manual) introduz possível erro de mensuração. A intenção de voto como proxy do comportamento eleitoral real é uma simplificação padrão, mas não discutida.</td>
<td style="text-align: left;">Fenômeno real: co-evolução entre sindicalismo e apoio eleitoral à esquerda. Observação: intenção de voto autodeclarada em surveys anuais. Coleta: SOM (respondentes entre 16–85 anos, selecionados do registro fiscal sueco, surveys postais desde 1986); dados administrativos de confederações. Operacionalização: classe ocupacional por categoria autorreferida (SOM); filiação sindical por confederação; preferência partidária binarizada. Análise: OLS com interações temporais. Inferência: associacional/descritiva, com alguma pretensão explicativa sobre mecanismos. Unidade de análise: indivíduo; nível de agregação: nacional.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">O achado sobre erosão temporal do efeito é o mais original e robusto. A documentação de que o efeito da TCO para colarinho branco não-terciário é indistinguível do efeito da LO para colarinho azul é relevante teoricamente. A discussão sobre ciclo vicioso (descentralização + welfare + competição) é plausível mas não identificada causalmente.</td>
<td style="text-align: left;">Empíricos: (1) Filiação a qualquer confederação aumenta a propensão de votar à esquerda em relação aos não-sindicalizados, com efeitos variando de 4 pp (SACO, terciário) a 26 pp (LO, não-terciário) sobre preferência pelo SAP. (2) O efeito de esquerda da filiação à LO e à TCO declinou aproximadamente 15 pp desde a segunda metade dos anos 1980. (3) O efeito da SACO para terciários permaneceu relativamente estável. Contribuições teórico-metodológicas: documentação sistemática da erosão temporal dos efeitos sindicais com dados longitudinais; distinção empírica entre mecanismo composicional (de-sindicalização) e mecanismo condicional (erosão do efeito).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">A distinção entre hipótese de auto-seleção e hipótese de socialização é discutida de forma correta, mas a refutação da hipótese de auto-seleção é apenas indireta (ausência do padrão esperado, não teste direto). A atribuição causal ao “ciclo vicioso” (descentralização + welfare + competição inter-sindical) permanece altamente especulativa, pois os autores não apresentam evidência direta de que as mudanças organizacionais alteraram as práticas comunicativas dos sindicatos e que essas mudanças, por sua vez, alteraram as preferências dos membros.</td>
<td style="text-align: left;">A resposta à pergunta principal é satisfatória no nível descritivo: os autores documentam claramente os dois mecanismos (composicional e condicional). O ponto mais vulnerável é a interpretação causal da erosão temporal — há múltiplas explicações alternativas plausíveis (ex.: mudanças na composição sociológica dos membros por setor, geração ou escolaridade que não são completamente controladas). Ameaças à identificação incluem: variáveis omitidas correlacionadas com a filiação sindical e com a orientação política ao longo do tempo (ex.: estrutura industrial, escolaridade dos pais, valores pós-materialistas). A análise de robustez é limitada. Generalizabilidade: alta plausibilidade para países com sistemas de Ghent similares (Dinamarca, Finlândia, Bélgica); baixa para países sem esse sistema.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;">A separação entre reconhecidas e não reconhecidas é relevante: os autores são honestos sobre o problema da co-evolução (endogeneidade) mas não exploram todas as suas implicações metodológicas.</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> Endogeneidade das transformações sindicais (governos social-democratas contribuíram para as mudanças estudadas); problemas de auto-seleção na filiação sindical (mitigados mas não eliminados); impossibilidade de testar se a expansão do ensino superior foi estrategicamente miope do ponto de vista socialdemocrata. <br> <strong>Não reconhecidas ou subestimadas:</strong> A codificação manual da afiliação confederal para 2012–2018 introduz erro de mensuração não discutido; a análise não controla adequadamente por heterogeneidade geracional (novos entrantes no mercado de trabalho versus membros de longa data); a ausência de dados de painel implica que a variação temporal identificada pode refletir mudanças na composição do pool de filiados, não mudanças nas atitudes dos mesmos indivíduos ao longo do tempo; a variável de intenção de voto como proxy do comportamento eleitoral real não é discutida.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A combinação de teoria da mobilização de classe com análise de variedades de sindicalismo é coerente e produtiva. A moldura teórica não é explicitamente localizada em uma tradição única, o que é uma força (ecletismo produtivo) e uma fraqueza (falta de diálogo com o institucionalismo histórico sobre mudança organizacional).</td>
<td style="text-align: left;">Tradição do power resources approach (Korpi 1983; Przeworski e Sprague 1986) revisitada sob o prisma das variedades de sindicalismo (Mosimann e Pontusson 2017, 2022). A moldura é adequada ao tipo de pergunta e à evidência disponível. A coerência entre ontologia implícita (realismo moderado sobre classes e interesses coletivos) e método (análise quantitativa com controles) é satisfatória. Há subutilização do institucionalismo histórico para analisar as causas das transformações organizacionais, o que enfraquece a interpretação do “ciclo vicioso”.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo com a literatura de relações industriais é forte (Kjellberg, Jansson); o diálogo com a literatura de institucionalismo histórico e mudança institucional (Streeck, Mahoney e Thelen) é ausente, o que representa uma lacuna relevante dado que o paper trata explicitamente de co-evolução institucional.</td>
<td style="text-align: left;">Przeworski e Sprague (1986); Korpi (1983); Rothstein (1992); Svensson (1994); Mosimann e Pontusson (2017, 2022); Rennwald e Pontusson (2021); Kjellberg (2013, 2019a, 2019b, 2022); Jansson (2017, 2022); Arndt (2018); Arndt e Rennwald (2016); Gingrich (2011); Baccaro e Howell (2017). Pontusson (2013) e Rasmussen e Pontusson (2018) são claramente parte do programa de pesquisa do segundo autor.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">A ausência de qualquer análise de <em>placebo</em> ou de robustez alternativa é uma limitação para um working paper que aspira a contribuir com a literatura comparada. Para a agenda de pesquisa do leitor (política educacional, desigualdade e coalizões políticas no Brasil), o paper oferece um modelo analítico relevante: a expansão do ensino superior pode ter efeitos não intencionais sobre as bases organizacionais dos partidos de esquerda ao deslocar trabalhadores de sindicatos setoriais abrangentes para associações ocupacionais mais estreitas.</td>
<td style="text-align: left;">Vulnerabilidades adicionais: a análise temporal termina em 2018 e não incorpora a eleição de 2022 nem os efeitos pós-pandemia sobre o trabalho e o sindicalismo. A discussão sobre imigração e de-sindicalização dos trabalhadores nascidos no exterior é introduzida mas não integrada ao modelo empírico. O paper tem valor analítico direto para a agenda de pesquisa do leitor sobre desigualdade educacional e coalizões políticas: a relação entre expansão do ensino superior (como no Brasil pós-REUNI e pós-PROUNI) e mudanças na base organizacional dos partidos de esquerda representa uma hipótese generalizável a explorar.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>