<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-05-07">
<meta name="description" content="Tales Mançano — Annotated Bibliography">

<title>Fichamento: Modelo de expansão da educação superior no Brasil: predomínio privado/mercantil e desafios para a regulação e a formação universitária – Annotated Bibliography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9c28ad92f8939dd35fc671874dd1efeb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/tts-reader-2.3.0/tts-reader.js" defer="true"></script>
<link href="../site_libs/quarto-contrib/tts-reader-2.3.0/tts-reader.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Fichamento: Modelo de expansão da educação superior no Brasil: predomínio privado/mercantil e desafios para a regulação e a formação universitária – Annotated Bibliography">
<meta property="og:description" content="Sguissardi (2008)">
<meta property="og:site_name" content="Annotated Bibliography">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Annotated Bibliography</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://mancano-tales.github.io" target="_blank"> 
<span class="menu-text">← Tales Mançano</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Bibliography</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introdução-pp.-991993" id="toc-introdução-pp.-991993" class="nav-link active" data-scroll-target="#introdução-pp.-991993"><span class="header-section-number">1</span> Introdução (pp.&nbsp;991–993)</a>
  <ul class="collapse">
  <li><a href="#contextualização-e-questão-central-13" id="toc-contextualização-e-questão-central-13" class="nav-link" data-scroll-target="#contextualização-e-questão-central-13"><span class="header-section-number">1.1</span> Contextualização e questão central [§1–§3]</a></li>
  </ul></li>
  <li><a href="#a-crise-financeira-mundial-e-o-mercado-educacional-pp.-993996" id="toc-a-crise-financeira-mundial-e-o-mercado-educacional-pp.-993996" class="nav-link" data-scroll-target="#a-crise-financeira-mundial-e-o-mercado-educacional-pp.-993996"><span class="header-section-number">2</span> A Crise Financeira Mundial e o Mercado Educacional (pp.&nbsp;993–996)</a>
  <ul class="collapse">
  <li><a href="#a-lição-de-marx-e-o-capitalismo-mundializado-47" id="toc-a-lição-de-marx-e-o-capitalismo-mundializado-47" class="nav-link" data-scroll-target="#a-lição-de-marx-e-o-capitalismo-mundializado-47"><span class="header-section-number">2.1</span> A lição de Marx e o capitalismo mundializado [§4–§7]</a></li>
  <li><a href="#lições-da-crise-e-o-mercado-educacional-810" id="toc-lições-da-crise-e-o-mercado-educacional-810" class="nav-link" data-scroll-target="#lições-da-crise-e-o-mercado-educacional-810"><span class="header-section-number">2.2</span> Lições da crise e o mercado educacional [§8–§10]</a></li>
  </ul></li>
  <li><a href="#a-expansão-da-educação-superior-no-brasil-dados-e-tendências-pp.-9961003" id="toc-a-expansão-da-educação-superior-no-brasil-dados-e-tendências-pp.-9961003" class="nav-link" data-scroll-target="#a-expansão-da-educação-superior-no-brasil-dados-e-tendências-pp.-9961003"><span class="header-section-number">3</span> A Expansão da Educação Superior no Brasil — Dados e Tendências (pp.&nbsp;996–1003)</a>
  <ul class="collapse">
  <li><a href="#periodização-e-evolução-19641994-1116" id="toc-periodização-e-evolução-19641994-1116" class="nav-link" data-scroll-target="#periodização-e-evolução-19641994-1116"><span class="header-section-number">3.1</span> Periodização e evolução 1964–1994 [§11–§16]</a></li>
  <li><a href="#aceleração-da-privatização-no-período-19942006-1722" id="toc-aceleração-da-privatização-no-período-19942006-1722" class="nav-link" data-scroll-target="#aceleração-da-privatização-no-período-19942006-1722"><span class="header-section-number">3.2</span> Aceleração da privatização no período 1994–2006 [§17–§22]</a></li>
  </ul></li>
  <li><a href="#mercadorização-da-educação-superior-pp.-10001003" id="toc-mercadorização-da-educação-superior-pp.-10001003" class="nav-link" data-scroll-target="#mercadorização-da-educação-superior-pp.-10001003"><span class="header-section-number">4</span> Mercadorização da Educação Superior (pp.&nbsp;1000–1003)</a>
  <ul class="collapse">
  <li><a href="#o-marco-legal-e-o-decreto-2.3061997-2328" id="toc-o-marco-legal-e-o-decreto-2.3061997-2328" class="nav-link" data-scroll-target="#o-marco-legal-e-o-decreto-2.3061997-2328"><span class="header-section-number">4.1</span> O marco legal e o Decreto 2.306/1997 [§23–§28]</a></li>
  <li><a href="#dados-da-mercadorização-19992006-2933" id="toc-dados-da-mercadorização-19992006-2933" class="nav-link" data-scroll-target="#dados-da-mercadorização-19992006-2933"><span class="header-section-number">4.2</span> Dados da mercadorização 1999–2006 [§29–§33]</a></li>
  </ul></li>
  <li><a href="#a-efervescência-do-mercado-educacional-pp.-10031007" id="toc-a-efervescência-do-mercado-educacional-pp.-10031007" class="nav-link" data-scroll-target="#a-efervescência-do-mercado-educacional-pp.-10031007"><span class="header-section-number">5</span> A Efervescência do Mercado Educacional (pp.&nbsp;1003–1007)</a>
  <ul class="collapse">
  <li><a href="#fundos-de-investimento-e-oligopolização-3440" id="toc-fundos-de-investimento-e-oligopolização-3440" class="nav-link" data-scroll-target="#fundos-de-investimento-e-oligopolização-3440"><span class="header-section-number">5.1</span> Fundos de investimento e oligopolização [§34–§40]</a></li>
  <li><a href="#lógica-do-negócio-e-migração-para-fins-lucrativos-4146" id="toc-lógica-do-negócio-e-migração-para-fins-lucrativos-4146" class="nav-link" data-scroll-target="#lógica-do-negócio-e-migração-para-fins-lucrativos-4146"><span class="header-section-number">5.2</span> Lógica do negócio e migração para fins lucrativos [§41–§46]</a></li>
  </ul></li>
  <li><a href="#dificuldades-de-regulação-e-controle-pp.-10071009" id="toc-dificuldades-de-regulação-e-controle-pp.-10071009" class="nav-link" data-scroll-target="#dificuldades-de-regulação-e-controle-pp.-10071009"><span class="header-section-number">6</span> Dificuldades de Regulação e Controle (pp.&nbsp;1007–1009)</a>
  <ul class="collapse">
  <li><a href="#insuficiência-histórica-do-controle-estatal-4754" id="toc-insuficiência-histórica-do-controle-estatal-4754" class="nav-link" data-scroll-target="#insuficiência-histórica-do-controle-estatal-4754"><span class="header-section-number">6.1</span> Insuficiência histórica do controle estatal [§47–§54]</a></li>
  </ul></li>
  <li><a href="#das-funções-da-universidade-segundo-anísio-teixeira-pp.-10091011" id="toc-das-funções-da-universidade-segundo-anísio-teixeira-pp.-10091011" class="nav-link" data-scroll-target="#das-funções-da-universidade-segundo-anísio-teixeira-pp.-10091011"><span class="header-section-number">7</span> Das Funções da Universidade segundo Anísio Teixeira (pp.&nbsp;1009–1011)</a>
  <ul class="collapse">
  <li><a href="#a-universidade-como-locus-do-saber-vivo-5561" id="toc-a-universidade-como-locus-do-saber-vivo-5561" class="nav-link" data-scroll-target="#a-universidade-como-locus-do-saber-vivo-5561"><span class="header-section-number">7.1</span> A universidade como locus do saber vivo [§55–§61]</a></li>
  <li><a href="#as-quatro-funções-universitárias-6265" id="toc-as-quatro-funções-universitárias-6265" class="nav-link" data-scroll-target="#as-quatro-funções-universitárias-6265"><span class="header-section-number">7.2</span> As quatro funções universitárias [§62–§65]</a></li>
  </ul></li>
  <li><a href="#das-contradições-da-regulação-no-âmbito-do-estado-público-privadomercantil-pp.-10111012" id="toc-das-contradições-da-regulação-no-âmbito-do-estado-público-privadomercantil-pp.-10111012" class="nav-link" data-scroll-target="#das-contradições-da-regulação-no-âmbito-do-estado-público-privadomercantil-pp.-10111012"><span class="header-section-number">8</span> Das Contradições da Regulação no Âmbito do Estado Público-Privado/Mercantil (pp.&nbsp;1011–1012)</a>
  <ul class="collapse">
  <li><a href="#estado-como-espaço-de-contradição-6670" id="toc-estado-como-espaço-de-contradição-6670" class="nav-link" data-scroll-target="#estado-como-espaço-de-contradição-6670"><span class="header-section-number">8.1</span> Estado como espaço de contradição [§66–§70]</a></li>
  </ul></li>
  <li><a href="#da-educação-mercadoria-e-da-mercadoria-educação-pp.-10121014" id="toc-da-educação-mercadoria-e-da-mercadoria-educação-pp.-10121014" class="nav-link" data-scroll-target="#da-educação-mercadoria-e-da-mercadoria-educação-pp.-10121014"><span class="header-section-number">9</span> Da Educação-Mercadoria e da Mercadoria-Educação (pp.&nbsp;1012–1014)</a>
  <ul class="collapse">
  <li><a href="#duas-categorias-uma-mesma-moeda-7177" id="toc-duas-categorias-uma-mesma-moeda-7177" class="nav-link" data-scroll-target="#duas-categorias-uma-mesma-moeda-7177"><span class="header-section-number">9.1</span> Duas categorias, uma mesma moeda [§71–§77]</a></li>
  </ul></li>
  <li><a href="#considerações-e-questões-finais-pp.-10141017" id="toc-considerações-e-questões-finais-pp.-10141017" class="nav-link" data-scroll-target="#considerações-e-questões-finais-pp.-10141017"><span class="header-section-number">10</span> Considerações e Questões Finais (pp.&nbsp;1014–1017)</a>
  <ul class="collapse">
  <li><a href="#diagnóstico-e-desafios-finais-7886" id="toc-diagnóstico-e-desafios-finais-7886" class="nav-link" data-scroll-target="#diagnóstico-e-desafios-finais-7886"><span class="header-section-number">10.1</span> Diagnóstico e desafios finais [§78–§86]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">11</span> Argumento Sintético</a></li>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Modelo de expansão da educação superior no Brasil: predomínio privado/mercantil e desafios para a regulação e a formação universitária</h1>
<p class="subtitle lead">Sguissardi (2008)</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Brazil</div>
    <div class="quarto-category">Sociology of Education</div>
    <div class="quarto-category">Tertiary Education</div>
    <div class="quarto-category">Private Education</div>
    <div class="quarto-category">Education Policy/Politics</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Sguissardi, V. (2008). Modelo de expansão da educação superior no Brasil: predomínio privado/mercantil e desafios para a regulação e a formação universitária. <em>Educação &amp; Sociedade</em>, <em>29</em>(105), 991–1022.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Entrada BibTeX → Sguissardi2008
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">Sguissardi2008</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>  = {Sguissardi, Valdemar},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>   = {Modelo de expansão da educação superior no Brasil: predomínio privado/mercantil e desafios para a regulação e a formação universitária},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>    = {2008},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">journal</span> = {Educação <span class="ch">\&amp;</span> Sociedade},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">volume</span>  = {29},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">number</span>  = {105},</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span>   = {991--1022},</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>Última atualização: 2026-05-07 Modelo: Perplexity, powered by Claude Sonnet 4.6 Thinking Prompt Version: v13.0 2026-04-19 | 2026-04-24 “IA Blog Post QMD” Gerado em: 2026-05-07T13:01:00-03:00</p>
<hr>
<section id="introdução-pp.-991993" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-991993"><span class="header-section-number">1</span> Introdução (pp.&nbsp;991–993)</h2>
<section id="contextualização-e-questão-central-13" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="contextualização-e-questão-central-13"><span class="header-section-number">1.1</span> Contextualização e questão central [§1–§3]</h3>
<p>O artigo parte de uma pergunta provocativa e deliberadamente conectiva: qual a relação entre a crise financeira mundial de 2008 e o modelo de expansão da educação superior no Brasil? Essa questão impõe-se, segundo o autor, ao analista das políticas de educação superior quando se depara com três ordens de fatos simultâneos: as ações do governo federal expandindo vagas e titulações nas Instituições Federais de Ensino Superior (IFES) — pela multiplicação de <em>campi</em>, pela criação de novas universidades federais e pelo Programa de Apoio a Planos de Reestruturação e Expansão das Universidades Federais (REUNI); o expressivo aumento de Instituições de Ensino Superior (IES) com fins lucrativos e a acelerada multiplicação de “aquisições” e “incorporações” de IES isoladas e de “redes” universitárias por fundos de investimento; e, por fim, as dificuldades enfrentadas pelos órgãos estatais reguladores em promover efetivamente a regulação e o controle do sistema.</p>
<p>O autor anuncia que a resposta a essa pergunta inicial deverá iluminar questões relativas aos desafios da <strong>formação universitária</strong> diante de uma concepção de educação superior crescentemente orientada pelo mercado, que conduz o que ele denomina “estreita e neopragmática <strong>sociabilidade produtiva</strong>”. A resposta exige, segundo o texto, um percurso analítico que passe por dados empíricos da expansão do sistema, pela discussão de categorias teóricas (mercadoria, regulação, funções da universidade) e pela reflexão normativa sobre o futuro da instituição universitária.</p>
<p>Para responder à questão e às que dela derivam, o autor anuncia três movimentos: (1) expor dados da realidade; (2) estabelecer parâmetros analíticos — as funções da universidade, as contradições do Estado e da regulação estatal, o modelo de expansão, a produção da <em>educação-mercadoria</em> e da <em>mercadoria-educação</em>, a desregulação do mercado financeiro e a constituição do mercado educacional; (3) levantar questões e alertas quanto à formação universitária e ao futuro da educação superior no Brasil.</p>
<hr>
</section>
</section>
<section id="a-crise-financeira-mundial-e-o-mercado-educacional-pp.-993996" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="a-crise-financeira-mundial-e-o-mercado-educacional-pp.-993996"><span class="header-section-number">2</span> A Crise Financeira Mundial e o Mercado Educacional (pp.&nbsp;993–996)</h2>
<section id="a-lição-de-marx-e-o-capitalismo-mundializado-47" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="a-lição-de-marx-e-o-capitalismo-mundializado-47"><span class="header-section-number">2.1</span> A lição de Marx e o capitalismo mundializado [§4–§7]</h3>
<p>O autor recorre ao clássico diagnóstico de Marx e Engels — “<em>tudo o que é sólido desmancha no ar</em>” — para introduzir a crise capitalista de 2008 como pano de fundo analítico. Sguissardi retoma, a partir do economista César Benjamim, as três tendências que Marx apontava para a sociedade capitalista em consolidação: (a) a compulsão de transformar incessantemente bens materiais e simbólicos em mercadoria — “no limite, <em>tudo seria transformado em mercadoria</em>”; (b) a compulsão de ampliar o espaço geográfico do circuito mercantil — “no limite, <em>esse espaço seria todo o planeta</em>”; (c) a compulsão de inventar sempre novos bens e novas necessidades, alterando “profundamente a cultura e as formas de sociabilidade” para criar o consumidor dessas novas necessidades.</p>
<p>Esses três elementos são declarados essenciais para a análise do tema central do artigo: a transformação da educação em mercadoria e a expansão global do mercado educacional. O autor conecta explicitamente esses elementos às categorias de <strong>educação-mercadoria</strong> e <strong>mercadoria-educação</strong> formuladas por José Rodrigues (2007), e enfatiza que a <em>sociabilidade produtiva</em> é o conceito que nomeia o tipo de formação humana resultante desse processo.</p>
<p>Para entender a crise e suas dificuldades, Sguissardi também cita Wallerstein (<em>Le Monde</em>, 12/10/2008), para quem “o capitalismo é onívoro, capta o lucro onde ele seja maior”, e Belluzzo (2008), que ironiza os “fanáticos do livre mercado” e os “sacerdotes dos mercados eficientes” que forneceram respeitabilidade científica a hipóteses improváveis. Cesar Benjamim complementa com a síntese: “Mais uma vez, os Estados tentarão salvar o capitalismo da ação predatória dos capitalistas. Karl Marx manda lembranças.”</p>
</section>
<section id="lições-da-crise-e-o-mercado-educacional-810" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="lições-da-crise-e-o-mercado-educacional-810"><span class="header-section-number">2.2</span> Lições da crise e o mercado educacional [§8–§10]</h3>
<p>As principais lições da crise financeira são representadas, no texto, pelas reflexões do Frei Betto (2008): a crise derruba o dogma do livre mercado como panaceia; ainda não é o fim do capitalismo, mas pode ser a agonia do neoliberalismo que hipertrofiou o sistema financeiro; repete-se a “velha receita” — após privatizar os ganhos, o sistema socializa os prejuízos; e a exclusão de dois terços da humanidade do acesso a bens essenciais é a verdadeira medida do fracasso capitalista.</p>
<p>O autor aplica o raciocínio diretamente ao mercado educacional com uma série de perguntas retóricas: por que as premissas válidas para o livre mercado em geral não se aplicariam ao mercado educacional? Por que a educação seria uma “missão sagrada” e os detentores dos fundos de investimento em educação, “sumos-sacerdotes”? Sguissardi responde que tal excepcionalismo se sustenta apenas para quem ignora a dinâmica capitalista, que profana o que era sagrado.</p>
<hr>
</section>
</section>
<section id="a-expansão-da-educação-superior-no-brasil-dados-e-tendências-pp.-9961003" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="a-expansão-da-educação-superior-no-brasil-dados-e-tendências-pp.-9961003"><span class="header-section-number">3</span> A Expansão da Educação Superior no Brasil — Dados e Tendências (pp.&nbsp;996–1003)</h2>
<section id="periodização-e-evolução-19641994-1116" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="periodização-e-evolução-19641994-1116"><span class="header-section-number">3.1</span> Periodização e evolução 1964–1994 [§11–§16]</h3>
<p>O autor analisa a evolução da educação superior brasileira em duas grandes etapas, com dados sistematizados pelo MEC/INEP. A primeira etapa cobre três décadas (1964–1994) e a segunda dois governos FHC e o primeiro governo Lula (1994–2006). Em ambas, o foco recai sobre a classificação por categoria administrativa: pública e privada.</p>
<p>Na análise do período 1964–1994 (Tabela 1), os principais destaques são:</p>
<ol type="1">
<li>Em 1964, ao início do regime militar-autoritário, havia 142.386 matrículas totais, com predominância pública: 61,6% públicas e 38,4% privadas.</li>
<li>Na primeira década do regime (1964–1974), o total de matrículas foi multiplicado por mais de cinco vezes (559,8%), mas as matrículas privadas cresceram 990,1% contra apenas 289,1% das públicas, invertendo a proporção: 36,4% públicas e 63,6% privadas. Isso constitui, segundo o autor, o <strong>primeiro grande movimento de privatização do sistema</strong>.</li>
<li>Na segunda década (1974–1984), houve uma pequena inversão: crescimento de 67,7% nas públicas e 38,7% nas privadas, resultando em 40,9% e 59,1%, respectivamente, e crescimento total muito inferior (49,3%).</li>
<li>Na terceira década (1984–1994), o crescimento foi ainda menor — 18,7%, cerca de 1,5% ao ano —, mantendo praticamente inalterada a proporção: 41,6% públicas e 58,4% privadas.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Ano</th>
<th style="text-align: right;">Total</th>
<th style="text-align: right;">Matrículas Públicas</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Matrículas Privadas</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1964</td>
<td style="text-align: right;">142.386</td>
<td style="text-align: right;">87.665</td>
<td style="text-align: right;">61,6</td>
<td style="text-align: right;">54.721</td>
<td style="text-align: right;">38,4</td>
</tr>
<tr class="even">
<td style="text-align: right;">1974</td>
<td style="text-align: right;">937.593</td>
<td style="text-align: right;">341.028</td>
<td style="text-align: right;">36,4</td>
<td style="text-align: right;">596.565</td>
<td style="text-align: right;">63,5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1984</td>
<td style="text-align: right;">1.399.539</td>
<td style="text-align: right;">571.879</td>
<td style="text-align: right;">40,9</td>
<td style="text-align: right;">827.660</td>
<td style="text-align: right;">59,1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1994</td>
<td style="text-align: right;">1.661.034</td>
<td style="text-align: right;">690.450</td>
<td style="text-align: right;">41,6</td>
<td style="text-align: right;">970.584</td>
<td style="text-align: right;">58,4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Δ% 1964–1994</td>
<td style="text-align: right;">1.065,7</td>
<td style="text-align: right;">687,6</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">1.673,7</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
</section>
<section id="aceleração-da-privatização-no-período-19942006-1722" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="aceleração-da-privatização-no-período-19942006-1722"><span class="header-section-number">3.2</span> Aceleração da privatização no período 1994–2006 [§17–§22]</h3>
<p>A segunda etapa (Tabela 2) mostra a retomada e o recrudescimento do processo de expansão pela via da privatização. No octênio 1994–2002 (governos FHC), quase dobra o número de IES (851 → 1.637, +92,4%), mas as IES públicas <em>reduzem</em> seu número em -10,5%, enquanto as privadas crescem 127,8%. A proporção, que em 1994 era de 25,6% públicas e 74,4% privadas, passa em 2002 para 11,9% públicas e 88,1% privadas.</p>
<p>Quanto às matrículas, o crescimento total no octênio foi de 109,5%, mas apenas 52,3% nas públicas e 150,2% nas privadas. A proporção, estável há cerca de 20 anos em torno de 40%/60%, passa em oito anos para 30,2% públicas e 69,8% privadas. No quatriênio 2002–2006 (primeiro governo Lula), o ritmo de crescimento das IES desacelera (38,7% total), mas a desproporção persiste: +27% nas públicas contra +40,2% nas privadas; nas matrículas, +15% públicas e +42,6% privadas, resultando em 25,8% e 74,2% no final de 2006. No período completo 1994–2006, as IES públicas cresceram apenas 13,7% contra 219,4% das privadas; as matrículas públicas cresceram 75% contra 275,2% das privadas.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 3%">
<col style="width: 11%">
<col style="width: 3%">
<col style="width: 23%">
<col style="width: 13%">
<col style="width: 3%">
<col style="width: 13%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Ano</th>
<th style="text-align: right;">Total IES</th>
<th style="text-align: right;">IES Públ.</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">IES Priv.</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Total Matrículas (mil)</th>
<th style="text-align: right;">Públ. (mil)</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Priv. (mil)</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1994</td>
<td style="text-align: right;">851</td>
<td style="text-align: right;">218</td>
<td style="text-align: right;">25,6</td>
<td style="text-align: right;">633</td>
<td style="text-align: right;">74,4</td>
<td style="text-align: right;">1.661</td>
<td style="text-align: right;">690</td>
<td style="text-align: right;">41,6</td>
<td style="text-align: right;">970</td>
<td style="text-align: right;">58,4</td>
</tr>
<tr class="even">
<td style="text-align: right;">2002</td>
<td style="text-align: right;">1.637</td>
<td style="text-align: right;">195</td>
<td style="text-align: right;">11,9</td>
<td style="text-align: right;">1.442</td>
<td style="text-align: right;">88,1</td>
<td style="text-align: right;">3.479</td>
<td style="text-align: right;">1.051</td>
<td style="text-align: right;">30,2</td>
<td style="text-align: right;">2.428</td>
<td style="text-align: right;">69,8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2006</td>
<td style="text-align: right;">2.270</td>
<td style="text-align: right;">248</td>
<td style="text-align: right;">11,0</td>
<td style="text-align: right;">2.022</td>
<td style="text-align: right;">89,0</td>
<td style="text-align: right;">4.676</td>
<td style="text-align: right;">1.209</td>
<td style="text-align: right;">25,8</td>
<td style="text-align: right;">3.467</td>
<td style="text-align: right;">74,2</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="mercadorização-da-educação-superior-pp.-10001003" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="mercadorização-da-educação-superior-pp.-10001003"><span class="header-section-number">4</span> Mercadorização da Educação Superior (pp.&nbsp;1000–1003)</h2>
<section id="o-marco-legal-e-o-decreto-2.3061997-2328" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="o-marco-legal-e-o-decreto-2.3061997-2328"><span class="header-section-number">4.1</span> O marco legal e o Decreto 2.306/1997 [§23–§28]</h3>
<p>Sguissardi identifica um fenômeno relativamente recente e qualitativamente distinto no modelo de expansão: a <strong>mercadorização</strong> acelerada da educação superior. O autor situa esse processo à sombra das recomendações do Banco Mundial de 1994 (<em>Higher Education: The Lessons of Experience</em>), que propunha maior diferenciação institucional, diversificação de fontes de financiamento (incluindo pagamento pelos alunos das IES públicas), adoção da “universidade de ensino” em vez da “universidade de pesquisa” (neo-humboldtiana), e recomendava às autoridades atenção aos “sinais do mercado”.</p>
<p>A Lei de Diretrizes e Bases da Educação Nacional (LDB), aprovada em dezembro de 1996, é descrita como um “guarda-chuva jurídico” que possibilitou a edição de decretos normatizadores alinhados com essas recomendações. O mais expressivo é o Decreto n.&nbsp;2.306, de 19 de agosto de 1997, que reconheceu a educação superior como um bem de serviço comercializável — objeto de lucro e acumulação —, submetendo as IES privadas com fins lucrativos ao regime de legislação mercantil “como se comerciais fossem”. O autor destaca que este decreto antecipou e foi além mesmo da polêmica Agenda dos Acordos Gerais do Comércio e dos Serviços (AGCS/OMC) de 1996, que propunha a desregulamentação dos serviços educacionais como se fossem comerciais, mas que continua sem acordo naquele âmbito.</p>
<p>Em 1998, o Banco Mundial reforçou essa orientação com a tese de que o ensino superior teria “muitas das características de um bem privado”, fornecendo amparo intelectual à abertura do mercado educacional no Brasil. É a partir de 1999 que o Censo da Educação Superior do INEP começa a separar IES privadas (sem fins lucrativos) das particulares (com fins lucrativos), permitindo acompanhar empiricamente a mercadorização.</p>
</section>
<section id="dados-da-mercadorização-19992006-2933" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="dados-da-mercadorização-19992006-2933"><span class="header-section-number">4.2</span> Dados da mercadorização 1999–2006 [§29–§33]</h3>
<p>Entre 1999 e 2006, o número total de IES cresceu 107%, mas as IES particulares (privadas com fins lucrativos) cresceram 200%, enquanto as IES públicas cresceram apenas 29,2% e as IES privadas sem fins lucrativos apenas 16%.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 3%">
<col style="width: 28%">
<col style="width: 3%">
<col style="width: 32%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Ano</th>
<th style="text-align: right;">Total IES</th>
<th style="text-align: right;">Públicas</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Privadas (s/ fins luc.)</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Particulares (c/ fins luc.)</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1999</td>
<td style="text-align: right;">1.097</td>
<td style="text-align: right;">192</td>
<td style="text-align: right;">17,5</td>
<td style="text-align: right;">379</td>
<td style="text-align: right;">34,5</td>
<td style="text-align: right;">526</td>
<td style="text-align: right;">48,0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2006</td>
<td style="text-align: right;">2.270</td>
<td style="text-align: right;">248</td>
<td style="text-align: right;">11,0</td>
<td style="text-align: right;">439</td>
<td style="text-align: right;">19,0</td>
<td style="text-align: right;">1.583</td>
<td style="text-align: right;">70,0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Δ%</td>
<td style="text-align: right;">107,0</td>
<td style="text-align: right;">29,2</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">16,0</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">200,0</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
<p>No que diz respeito às matrículas (Tabela 4), em 1999, as particulares representavam apenas 27,8% (651.362 matrículas) do total. Em 2006, esse percentual sobe para 41,2% (1.924.166 matrículas), crescimento de 195%, enquanto as públicas cresceram 45% e as privadas sem fins lucrativos 74%. O crescimento total das matrículas foi de 97,3%.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 27%">
<col style="width: 15%">
<col style="width: 4%">
<col style="width: 15%">
<col style="width: 4%">
<col style="width: 21%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Ano</th>
<th style="text-align: right;">Total Matrículas</th>
<th style="text-align: right;">Públicas</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Privadas</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Particulares</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1999</td>
<td style="text-align: right;">2.369.945</td>
<td style="text-align: right;">832.022</td>
<td style="text-align: right;">35,0</td>
<td style="text-align: right;">886.561</td>
<td style="text-align: right;">37,4</td>
<td style="text-align: right;">651.362</td>
<td style="text-align: right;">27,8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2006</td>
<td style="text-align: right;">4.676.646</td>
<td style="text-align: right;">1.209.304</td>
<td style="text-align: right;">25,8</td>
<td style="text-align: right;">1.543.176</td>
<td style="text-align: right;">33,0</td>
<td style="text-align: right;">1.924.166</td>
<td style="text-align: right;">41,2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Δ%</td>
<td style="text-align: right;">97,3</td>
<td style="text-align: right;">45,0</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">74,0</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">195,0</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
<p>Projetando o ritmo de crescimento dos sete anos anteriores para o quadriênio 2007–2010, Sguissardi estimava que as IES particulares chegariam a 81% do total, com 50% das matrículas do sistema concentradas nesse segmento.</p>
<hr>
</section>
</section>
<section id="a-efervescência-do-mercado-educacional-pp.-10031007" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="a-efervescência-do-mercado-educacional-pp.-10031007"><span class="header-section-number">5</span> A Efervescência do Mercado Educacional (pp.&nbsp;1003–1007)</h2>
<section id="fundos-de-investimento-e-oligopolização-3440" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="fundos-de-investimento-e-oligopolização-3440"><span class="header-section-number">5.1</span> Fundos de investimento e oligopolização [§34–§40]</h3>
<p>O autor descreve um fenômeno novo e acelerado: a entrada de grandes fundos de investimento (principalmente estrangeiros) no mercado educacional brasileiro, à semelhança do que já ocorria nos mercados financeiro, industrial e comercial. A revista <em>Ensino Superior</em> do SEMESP (edição 101, fevereiro de 2007) anunciava “A consolidação do mercado”, estimando que até 2010, 60% das IES com menos de 500 alunos seriam extintas e as restantes absorvidas por mantenedoras maiores ou fundos de investimento. O consultor financeiro Renato de Souza Neto, ex-sócio da Paulo Renato Souza Consultores, sintetizou: “O setor vai se consolidar em uma economia de escala, em que grandes grupos oferecerão ensino superior barato, com uma qualidade razoável.”</p>
<p>O padrão identificado é: “grandes fundos de investimentos e capital externo apostam seus dólares nos grandes grupos nacionais, que estão comprando instituições médias, que, por sua vez, incorporam as pequenas.” Os principais “consolidadores” identificados eram: a Universidade Anhembi Morumbi (do grupo norte-americano <em>Laureate Education</em>, ex-<em>Sylvan Inc.</em>, presente em 18 países e controlando 30 instituições, com cerca de R$ 1 bilhão investido no Brasil); a rede <em>Whitney International University System</em>; o Grupo Anhanguera (nacional, com 47 <em>campi</em> em julho de 2008, 300 cursos, 140 mil alunos, 15 aquisições entre 2006 e julho de 2008, R$ 1 bilhão captado na BOVESPA); o <em>Apollo Group</em> norte-americano; o Centro Universitário UNA (mineiro); e a Universidade Estácio de Sá (carioca). Quatro redes já tinham aberto capital e negociavam ações na BOVESPA: Anhanguera, Estácio de Sá, SEB (Sistema Educacional Brasileiro) e Kroton (dona da marca Pitágoras, que captou R$ 396 milhões). O total captado em um ano no mercado de capitais alcançou cerca de R$ 1,9 bilhão, com cerca de duas dezenas de fundos dispondo de R$ 3 bilhões para aplicação no setor educacional.</p>
</section>
<section id="lógica-do-negócio-e-migração-para-fins-lucrativos-4146" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="lógica-do-negócio-e-migração-para-fins-lucrativos-4146"><span class="header-section-number">5.2</span> Lógica do negócio e migração para fins lucrativos [§41–§46]</h3>
<p>O autor descreve a lógica de funcionamento dos grandes grupos: compram instituições baratas e endividadas, reestruturando-as via gestão inteligente de dívidas e riscos, e as fazem gerar lucro em dois ou três anos. O crescimento do mercado é respaldado pela comparação com países vizinhos latino-americanos, cujas taxas de cobertura da educação superior seriam duas a três vezes maiores que as do Brasil (taxa líquida de 13% e taxa bruta de 20%).</p>
<p>Uma pesquisa da CM Consultoria (divulgada pela Universia em 2003) já apontava o ensino superior particular brasileiro como “objeto de desejo do capital”, dado que o setor movimentava R$ 15 bilhões anuais. Em 2003, apenas cerca de 500 das 1.762 IES privadas tinham declaradamente “fins lucrativos”; em 2006, já eram 1.583 as IES particulares/privado-mercantis. O autor explica esse crescimento por dois fatores: (a) vantagens comparativas — as IES sem fins lucrativos não conferem ao mantenedor a propriedade do patrimônio nem a possibilidade de sucessão, gerando incentivo à migração legal para a condição lucrativa; (b) as facilidades oferecidas pelo Ministério da Fazenda para essa transformação. Além disso, a ausência de qualquer limite efetivo à participação de capital estrangeiro nas empresas educacionais — a proposta de limite de 30% constava do Projeto de Lei da Reforma Universitária, mas sem previsão de aprovação — facilitava a internacionalização do mercado.</p>
<hr>
</section>
</section>
<section id="dificuldades-de-regulação-e-controle-pp.-10071009" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="dificuldades-de-regulação-e-controle-pp.-10071009"><span class="header-section-number">6</span> Dificuldades de Regulação e Controle (pp.&nbsp;1007–1009)</h2>
<section id="insuficiência-histórica-do-controle-estatal-4754" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="insuficiência-histórica-do-controle-estatal-4754"><span class="header-section-number">6.1</span> Insuficiência histórica do controle estatal [§47–§54]</h3>
<p>Em setembro de 2008, a <em>Folha de S. Paulo</em> revelou que universidades reprovadas pelo MEC (com conceitos 1 e 2 no Índice Geral de Cursos — IGC) não estavam sendo fiscalizadas desde 1995. Das nove instituições reprovadas, em seis a autorização era anterior a 1996 e uma não passava por análise desde 1975. Especialistas atribuíam a situação a falhas do MEC no controle de qualidade das escolas, tanto nas gestões FHC quanto Lula. A LDB de 1996 determina que todas as IES devem passar periodicamente por análise de seus indicadores de qualidade, mas a lei sistematicamente não foi cumprida.</p>
<p>O ex-ministro Paulo Renato de Souza, que em 2001 baixou portaria determinando prazo de 90 dias para início do recredenciamento das instituições, reconheceu a dificuldade: “A resistência das instituições foi grande, não consegui aplicar o processo. Muitas obtiveram liminares na Justiça.” E declarou sobre a dificuldade de descredenciamento: “Tentei fechar alguns cursos e não consegui, mesmo tendo uma série de elementos técnicos.” Durante os sete anos de aplicação do <em>Provão</em> (1997–2002), não houve nenhum fechamento de curso por determinação superior.</p>
<p>A situação é agravada por um embate jurídico: dirigentes de universidades abertas antes da LDB/1996 alegam não mais precisar do recredenciamento, mas o MEC, apoiado numa ADI do STF de 2004, sustenta o contrário. As autoridades reconhecem a dificuldade, mas apontam o SINAES (2004) como novo ordenamento jurídico que regularizaria a situação ao completar seu ciclo avaliativo. Sguissardi registra ainda que os órgãos de supervisão do MEC, em parceria com conselhos profissionais de direito, medicina e pedagogia, têm levado ao descredenciamento de instituições e fechamento de cursos, mas de forma ainda insuficiente diante da dimensão do sistema.</p>
<hr>
</section>
</section>
<section id="das-funções-da-universidade-segundo-anísio-teixeira-pp.-10091011" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="das-funções-da-universidade-segundo-anísio-teixeira-pp.-10091011"><span class="header-section-number">7</span> Das Funções da Universidade segundo Anísio Teixeira (pp.&nbsp;1009–1011)</h2>
<section id="a-universidade-como-locus-do-saber-vivo-5561" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="a-universidade-como-locus-do-saber-vivo-5561"><span class="header-section-number">7.1</span> A universidade como locus do saber vivo [§55–§61]</h3>
<p>Para fundamentar a crítica normativa ao modelo de expansão mercantil, Sguissardi recorre à obra de <strong>Anísio Teixeira</strong>, descrito como um dos mais respeitados mestres da teoria e da história da universidade no Brasil. O autor destaca dois textos centrais de Anísio: o discurso inaugural como reitor da Universidade do Distrito Federal (31 de julho de 1935) e as notas sobre a universidade publicadas em <em>Educação e Universidade</em> (1998).</p>
<p>No discurso inaugural, Anísio define a função da universidade como única e exclusiva: não se trata apenas de difundir conhecimentos (o livro faz isso), nem de conservar a experiência humana (o livro também conserva), nem de preparar práticos e profissionais (aprendizagem direta e escolas singelas bastam para isso). Trata-se, sim, de “manter uma atmosfera de saber para se preparar o homem que o serve e o desenvolve”, de “conservar o saber vivo e não morto, nos livros ou no empirismo das práticas não intelectualizadas”, de “formular intelectualmente a experiência humana, sempre renovada, para que a mesma se torne consciente e progressiva.”</p>
</section>
<section id="as-quatro-funções-universitárias-6265" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="as-quatro-funções-universitárias-6265"><span class="header-section-number">7.2</span> As quatro funções universitárias [§62–§65]</h3>
<p>No segundo texto, Anísio enumera quatro funções fundamentais da universidade, que nas brasileiras “se cumprem de modo fragmentado, incerto e às vezes acidentado”:</p>
<ol type="1">
<li><strong>Formação profissional</strong>: preparar profissionais para carreiras de base intelectual, científica e técnica.</li>
<li><strong>Alargamento da mente humana</strong>: iniciação do estudante na vida intelectual, prolongamento de sua visão, ampliação da imaginação — algo mais que cultura geral, obtido pela associação com “a mais apaixonante atividade humana: a busca do saber”.</li>
<li><strong>Desenvolvimento do saber humano</strong>: a universidade não só cultiva e transmite o saber, mas pesquisa, descobre e aumenta o conhecimento; ela é o “centro da elaboração do próprio saber, de busca desinteressada do conhecimento, da ciência e saber fundamental básico”.</li>
<li><strong>Transmissão de uma cultura comum</strong>: nisto, diz Anísio, “a universidade brasileira mais falhou” — relativamente desinteressada pelo Brasil, ela não logrou constituir-se transmissora de uma cultura comum nacional.</li>
</ol>
<p>Sem a universidade com tais funções, afirmara Anísio em 1934, “não chega a existir um povo” — a nação que não a tem não pode ter “existência autônoma, vivendo, tão-somente, como um reflexo dos demais”. Sguissardi mobiliza esse legado normativo para contrastar com a lógica mercantil que reduz a universidade a uma “indústria de ensino”.</p>
<hr>
</section>
</section>
<section id="das-contradições-da-regulação-no-âmbito-do-estado-público-privadomercantil-pp.-10111012" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="das-contradições-da-regulação-no-âmbito-do-estado-público-privadomercantil-pp.-10111012"><span class="header-section-number">8</span> Das Contradições da Regulação no Âmbito do Estado Público-Privado/Mercantil (pp.&nbsp;1011–1012)</h2>
<section id="estado-como-espaço-de-contradição-6670" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="estado-como-espaço-de-contradição-6670"><span class="header-section-number">8.1</span> Estado como espaço de contradição [§66–§70]</h3>
<p>O autor argumenta que não é possível analisar o modelo de expansão sem interrogar a questão da <strong>regulação</strong>, que por sua vez só pode ser compreendida no âmbito de um Estado que “carrega necessariamente as marcas das contradições da sociedade e do modo de produção capitalistas”. Retomando Marx, Sguissardi afirma que o Estado moderno não é entidade acima dos interesses de classes, mas uma “construção social, espaço de contradição entre os interesses públicos e privados ou privado/mercantis”, funcionando sob o predomínio ora destes, ora daqueles. Cita Mauro Santayana (2008) sobre como o neoliberalismo, nos últimos 30 anos, reduziu a tarefa do Estado à manutenção dos privilégios do capital.</p>
<p>Empregando a metáfora de Bourdieu, Sguissardi descreve o Estado como composto por uma “mão esquerda” (dos interesses sociais mais amplos), submetida ao “livre arbítrio” de uma “mão direita” (dos burocratas do Ministério da Fazenda, dos bancos). É nesse contexto que se dá o processo de regulação, definida, com Roger Dale, como atividades de controle para a definição de parâmetros “para o fornecimento dos serviços educativos, que o Estado assume através de políticas e sanções legais”. O maior avanço normativo foi o Decreto n.&nbsp;5.773 (Decreto-Ponte), de 09/05/2006, que dispõe sobre o exercício das funções de regulação, supervisão e avaliação das IES, tendo no SINAES e no modelo CAPES de avaliação seu principal apoio.</p>
<p>O autor aponta a tensão estrutural entre regulação/controle estatal e a autonomia da cultura de avaliação institucional, que não tem sido característica do sistema no Brasil — nem no setor público, nem no privado, e muito menos no privado/mercantil. O ponto mais problemático é a necessidade de conciliar a regulação do Estado com instituições que fazem do lucro seu principal objetivo: “O livre mercado já demonstrou, nas crises passadas do capitalismo e especialmente na atual, do que é capaz.”</p>
<hr>
</section>
</section>
<section id="da-educação-mercadoria-e-da-mercadoria-educação-pp.-10121014" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="da-educação-mercadoria-e-da-mercadoria-educação-pp.-10121014"><span class="header-section-number">9</span> Da Educação-Mercadoria e da Mercadoria-Educação (pp.&nbsp;1012–1014)</h2>
<section id="duas-categorias-uma-mesma-moeda-7177" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="duas-categorias-uma-mesma-moeda-7177"><span class="header-section-number">9.1</span> Duas categorias, uma mesma moeda [§71–§77]</h3>
<p>O autor explora em detalhe as duas categorias centrais de José Rodrigues (2007), conectando-as ao contexto da expansão mercantil da educação superior. A <strong>educação-mercadoria</strong> refere-se ao serviço educacional tratado como mercadoria a ser vendida no mercado educacional: “se um capital em particular estiver buscando sua valorização a partir da venda de serviços educacionais […], esse capital comercial tenderá a tratar a prática social educacional como uma mercadoria cujo fim é ser vendida no mercado educacional.” O caso típico é o curso de graduação prestado por uma universidade privada.</p>
<p>A <strong>mercadoria-educação</strong>, por outro lado, refere-se ao modo como o capital industrial encaraa educação: como insumo necessário à produção de outras mercadorias — “se a educação e o conhecimento são encarados como insumos necessários à produção de outras mercadorias […], o capital industrial tenderá a encarar a prática social educacional como uma mercadoria-educação.” São duas perspectivas de como o capital busca valorizar-se, ou seja, duas faces da mesma moeda.</p>
<p>Nenhuma dessas formas é isenta de contradições. Do lado da educação-mercadoria, o limite é estabelecido pela relação oferta-demanda. Do lado da mercadoria-educação, há uma contradição: a expansão rápida de profissionais graduados favorece imediatamente o capital industrial ao criar um exército de reserva que rebaixa salários, mas se esse exército é constituído por graduados sem as qualificações requeridas pelo processo produtivo, o capital industrial encontrará sérias dificuldades a médio e longo prazo.</p>
<p>O autor conclui que os empresários da educação buscarão, por todos os meios, valorizar e controlar a educação-mercadoria; os empresários industriais e comerciais, por sua vez, pressionarão o sistema (público ou privado) para obter a mercadoria-educação que melhor sirva à valorização de seu capital. Interessantemente, os empresários industriais tendem a valorizar mais a educação superior pública, pela maior possibilidade histórica de produzir os profissionais que lhes interessam; os empresários da educação, diferentemente, precisam garantir seu negócio e, no máximo, valorizam as públicas como formadoras de bons professores — insumo para extrair mais-valia da acumulação privada.</p>
<hr>
</section>
</section>
<section id="considerações-e-questões-finais-pp.-10141017" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="considerações-e-questões-finais-pp.-10141017"><span class="header-section-number">10</span> Considerações e Questões Finais (pp.&nbsp;1014–1017)</h2>
<section id="diagnóstico-e-desafios-finais-7886" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="diagnóstico-e-desafios-finais-7886"><span class="header-section-number">10.1</span> Diagnóstico e desafios finais [§78–§86]</h3>
<p>Na síntese final, Sguissardi retoma o elemento empírico central — a “corrida do ouro” da educação-mercadoria — e o interpreta como manifestação direta das três tendências marxianas: a compulsão de transformar tudo em mercadoria, de ampliar o espaço mercantil a todo o planeta, e de criar o consumidor das novas necessidades alterando a cultura e as formas de sociabilidade.</p>
<p>O autor observa que muito poucas diferenças existem entre o <em>modus faciendi</em> dos “consolidadores” do mercado educacional e o dos empresários do mercado financeiro, industrial e comercial: “Competir e, no máximo, garantir a <em>empregabilidade</em> dos estudantes/clientes são as preocupações que afligem e ao mesmo tempo se põem como desafio para todos.” Diante dessa lógica, as quatro funções universitárias pensadas por Anísio Teixeira ficam progressivamente esvaziadas — especialmente a segunda (alargamento da mente), a terceira (desenvolvimento do saber) e a quarta (transmissão de cultura comum). Mesmo a primeira — formação profissional — tende a tornar-se empobrecida na ausência das demais, resultando numa “formação de uma sociabilidade produtiva, estreita e neopragmática, eficiente mas alienada.”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>O autor questiona se é razoável esperar que IES que se conduzem pela lógica mercantil priorizem “a mais apaixonante atividade humana: a busca do saber”; o desenvolvimento desinteressado do conhecimento; ou a transmissão de uma cultura comum nacional.</p>
</div>
</div>
<p>Em face desse quadro, os olhos dos que se preocupam com a formação universitária voltam-se para o Estado e sua função reguladora. Mas, como demonstrado, uma série de obstáculos estruturais se impõe: a natureza do próprio Estado (predominantemente público ou privado/mercantil?); a concepção vigente de educação superior (direito e bem público, ou serviço e bem privado/mercantil?); e a natureza da regulação (privilégio da competição e eficiência do mercado, ou defesa do interesse público e cidadão?).</p>
<p>O artigo encerra com uma analogia que é também uma advertência: assim como o livre mercado, sem controle, pode estar levando ao suicídio do capitalismo, a hegemonia do mercado educacional no sistema, sem efetiva regulação e controle do Estado e da sociedade civil, pode significar, “a médio prazo, o suicídio da própria instituição universitária, a ‘mansão da liberdade’, como diria Anísio Teixeira.”</p>
<hr>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">11</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> O modelo de expansão da educação superior no Brasil tem se estruturado, desde a segunda metade dos anos 1990, pelo predomínio crescente de interesses privado/mercantis — materializados na mercadorização acelerada do sistema, na entrada de grandes fundos de investimento e na oligopolização do setor —, o que desafia a capacidade regulatória do Estado e compromete as funções universitárias essenciais à formação de profissionais/cidadãos críticos.</p>
<p><strong>Natureza do argumento:</strong> Predominantemente descritivo-diagnóstico, com forte componente normativo. O texto combina análise quantitativa de dados do MEC/INEP com enquadramento teórico marxista e com a invocação de um ideal normativo de universidade (Anísio Teixeira) como horizonte crítico.</p>
<p><strong>O que o texto demonstra:</strong> A trajetória empírica da privatização e mercadorização do sistema de educação superior brasileiro entre 1964 e 2006 (com ênfase em 1994–2006) e a insuficiência histórica da regulação estatal. Demonstra, com dados, a aceleração do processo mercantil e a entrada do capital financeiro no setor educacional.</p>
<p><strong>O que fica como hipótese ou agenda:</strong> A relação causal entre a mercadorização do sistema e o efetivo comprometimento das funções universitárias não é demonstrada empiricamente — permanece como hipótese normativa. Também fica em aberto se a regulação estatal seria capaz ou suficiente para reverter o processo, dado o caráter contraditório do próprio Estado.</p>
<p><strong>Contribuição ao debate:</strong> O texto articula, de maneira didática e polemicamente eficaz, três planos — dados empíricos, teoria marxista da mercadorização e normatividade teixeiriana — para diagnosticar um problema estrutural do ensino superior brasileiro. Insere-se no debate sobre a relação entre Estado, mercado e educação, contribuindo com uma análise histórico-institucional da privatização e com a aplicação das categorias de Rodrigues (2007) ao contexto brasileiro.</p>
</div>
</div>
<hr>
</section>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v13.0</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A pergunta é formulada de forma retórica e conectiva, articulando crise financeira global e expansão educacional. O ponto mais vulnerável é a falta de explicitação do mecanismo que conecta os dois fenômenos além da analogia estrutural marxiana. Interpretação alternativa: a expansão privada poderia ser analisada como resposta a demanda reprimida, sem necessariamente implicar comprometimento da formação.</td>
<td style="text-align: left;">Qual a relação entre a atual crise financeira mundial e o modelo de expansão da educação superior no Brasil, e que desafios esse modelo impõe para a regulação estatal e a formação universitária? Natureza: explicativa-normativa. A pergunta está explicitada na introdução.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">As questões secundárias estruturam o percurso analítico do artigo e são logicamente subordinadas à questão central, formando um roteiro progressivo de análise.</td>
<td style="text-align: left;">(1) Como se deu historicamente o processo de privatização e mercadorização da educação superior no Brasil? (2) Quais as funções da universidade que estão ameaçadas por esse modelo? (3) Em que medida o Estado é capaz de regular efetivamente um sistema de expansão marcado pelo interesse privado/mercantil? (4) Como as categorias de educação-mercadoria e mercadoria-educação permitem compreender a lógica do capital educacional?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle tem genuinidade empírica — os dados quantitativos são sólidos e revelam uma tendência real. Contudo, o salto do descritivo para o normativo (“o modelo compromete a formação”) não é acompanhado de evidências sobre os efeitos reais na qualidade formativa, tornando a dimensão explicativa do puzzle parcialmente especulativa.</td>
<td style="text-align: left;">Combinação de gap descritivo (a mercadorização acelerada não havia sido sistematizada com esses dados) e debate normativo (o que esse modelo implica para a missão da universidade). O puzzle é generalizável para outros países em desenvolvimento que seguiram trajetórias similares de liberalização do mercado educacional.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">O argumento central é coerente internamente, mas descansa em uma analogia (mercado educacional = mercado financeiro) que não é suficientemente argumentada. O <em>claim of discovery</em> — a ameaça ao ideal universitário — é sustentado indiretamente pela demonstração da expansão mercantil, não por evidências diretas de deterioração formativa.</td>
<td style="text-align: left;">O modelo de expansão da educação superior no Brasil está estruturalmente dominado por interesses privado/mercantis que, sem regulação efetiva, tendem a esvaziar as funções essenciais da universidade e a produzir uma formação empobrecida e instrumentalmente orientada para o mercado. O argumento é predominantemente descritivo-normativo; o <em>claim</em> de comprometimento da formação é sustentado por inferência lógica, não por evidência empírica direta.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O texto analisa dados longitudinais do MEC/INEP sem aplicar técnicas estatísticas inferenciais; a análise permanece no nível descritivo. A estratégia argumentativa combina análise de tendências com mobilização de referências teóricas e normativas, sem controle por variáveis confundidoras.</td>
<td style="text-align: left;">Estudo analítico-descritivo com análise de dados secundários longitudinais (Censo da Educação Superior do MEC/INEP, 1964–2006), revisão de imprensa especializada e de consultorias setoriais, e enquadramento teórico marxista. Sem controle experimental ou quase-experimental. Argumentação de tipo teórico-normativo nas seções de análise de funções e regulação.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP é transparente nas seções empíricas. A fragilidade está nas seções normativas, onde a “observação” são textos normativos de Anísio Teixeira mobilizados como critério avaliativo externo ao fenômeno analisado. Não há discussão sobre ado. Não há discussão sobre tura ou comparabilidade das categorias do Censo ao longo do tempo.</td>
<td style="text-align: left;">Fenômeno real (expansão mercantil da educação superior) → observação via dados do Censo da Educação Superiado. Não há discussão sobre imprensa + documentoado. Não há discussão sobre onalização por categorias adminisado. Não há discussão sobre particado. Não há discussão sobre e tendências perado. Não há discussão sobre trajetória do sisado. Não há discussão sobre sistema de educação superior brasileado. Não há discussão sobre iscussão sobre dos e Contribuições</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Obado. Não há discussão sobre discussão sobre ortante para o campo de política de educação superior no Brasil, especialmente pela sistematização dos dados de mercadorização. ado. Não há discussão sobre do. Não há discussão sobre scussão sobre políticas de acesso, é rado. Não há discussão sobre ão problematiza a relação entre expansão privada eado. Não há discussão sobre acesso —ado. Não há discussão sobre lorada. A análise histórico-institucional da privatizaçado. Não há discussão sobre ns de layering instado. Não há discussão sobre discussão sobre Não há discussão sobre s efeitos distrado. Não há discussão sobre ão os alunos das IES privado/mercantis? A expansão privada ampliou ou restado. Não há discussão sobre lneráveis? Essas perguntas não são foado. Não há discussão sobre 2008) e desenado. Não há discussão sobre ado. Não há discussão sobre o e a consado. Não há discussão sobre cionais na BOVESPA —ado. Não há discussão sobre is pertinente, mas exigeado. Não há discussão sobre cussão sobre bloco <code>.qmd</code> está pronto para ser salvo como arquivo <code>.qmd</code> e renderizado com <code>quarto render</code> em HTML. Ele cobre integralmentado. Não há discussão sobre ução às consado. Não há discussão sobre as tabelas do original reproduzidas em Markado. Não há discussão sobre te formatadoado. Não há discussão sobre parágrafos (§1ado. Não há discussão sobre e a ficha analítica crítica com 12 dimensado. Não há discussão sobre sobre</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mancano-tales\.github\.io\/Annotated-Bibliography");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://mancano-tales.github.io">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mancano-tales/Annotated-Bibliography" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>